### ISSUE TITLE
Feature request for global transform

### ISSUE THREAD

**Issue by Rtowne-Janrain** [TykTechnologies/tyk#1010]
This is a feature request to have a global transform/middleware ability not tied to specific API's.

For example, 
if all API's should include a header transform to add `Strict-Transport-Security: max-age=xxxxxx;`, it would be nice to have a central place to add this as opposed to making sure each individual API remembers to add it to its config.

This is a new feature request based on v2.3.7 current abilities.

**Comment by bitsofinfo** [comment]
+1

But also make it configurable for applicable for multiple API_IDs, like a grouping....but not necessarily blanket "all" coverage

**Comment by nfedyk** [comment]
+1 we can benefit from this

**Comment by bmudda** [comment]
+1

**Comment by mvdan** [comment]
Please use reactions like thumbs up instead of ading +1 comments - the latter will just send notifications to everyone and make the thread longer to no benefit.

**Comment by lonelycode** [comment]
Would suggest having all or specific JS functions might be the most effective thing to do here:

- Add a new middleware hook that fires regardless of the in bound API listen path, this takes care of a global inbound traffic
- Make it easier to write generic specific JSVM code by introducing a shared namespace for the JSVM as suggested in #853 e.g. some kind of tyk_contrib.js which can be added to the middleware dir and is loaded as a common lib.

This would make it easier for grouped APIs (they just invoke shared code) while also allowing a blanket approach and means we don;t need to introduce additional code-execution logic beyond the existing path matching.

**Comment by bitsofinfo** [comment]
not stale, these stale bots are ultra annoying

**Comment by andyo-tyk** [comment]
This is something that is still on the list of feature requests for improving Tyk's custom middleware support. I propose closing this ticket due to its age, but will make a note to update with a comment as and when we address this request.

Please feel free to comment and I can re-open if you prefer.
