### ISSUE TITLE
Allow '.' in slugs

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1013]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Slugs do not allow '.', they should for versioned URLs

**What is the expected behavior?**
I should be able to use '.'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
This only affects hybrid

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by bitsofinfo** [comment]
So is this restriction for a particular reason or side effect of an underlying lib?

**Comment by mvdan** [comment]
@bitsofinfo this was an oversight in our own code - and I believe the fix has already been merged for the .3.8 releases.

**Comment by bitsofinfo** [comment]
K, was looking in the release notes and didn't see this linked

**Comment by mvdan** [comment]
In https://github.com/TykTechnologies/tyk/releases/tag/v2.3.8, you can see it under the dashboard changelog: `Fix API spec validation for URL containing dot . symbol`.

**Comment by bitsofinfo** [comment]
Just pulled the 1.3.8/2.3.8, running a hybrid container and still seeing the '.' being stripped from the slugs

**Comment by lonelycode** [comment]
@bitsofinfo have you hard -refreshed your dashboard?

**Comment by lonelycode** [comment]
@bitsofinfo This was an error on our part, the change made it to package, but not to cloud - that's being addressed now.

**Comment by mvdan** [comment]
@bitsofinfo thanks for the quick report :)

**Comment by bitsofinfo** [comment]
cloud is fixed, thanks!
