### ISSUE TITLE
Dashboard: "Traffic Activity by Key" should show alias in title

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1014]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

click on a key w/ an alias, the alias is not displayed in dashboard "Traffic Activity by Key"

**What is the expected behavior?**

Should show the alias

1.3.7

**Comment by nickReyn** [comment]
Internal comment: Linked to issue 207 in Analytics repo

**Comment by bitsofinfo** [comment]
not stale @letzya @nickReyn @ConsM

**Comment by bitsofinfo** [comment]
not stale @letzya @nickReyn @ConsM
