### ISSUE TITLE
Remote address context variable should be aware of proxies

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk#1017]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently `remote_addr` context variable for header/body transformations only accounts for the last direct hop (or whatever golang http request's `RemoteAddr` provides). This doesn't serve much purpose when the gateway is accessed through a reverse proxy or a load balancer (such as on Tyk Cloud).

**What is the expected behavior?**
When `X-Real-Ip` or `X-Forwarded-For` headers are present the `remote_addr` context variable should contain the first hop that is not on a private network if it's the latter and just the whole value if it's the former. It may be beneficial to make this configurable since those headers are easy to spoof if the source is not trusted.

For the Tyk Cloud, infrastructure should also make sure the real IP is forwarded from the load balancers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. On Tyk Cloud or any other environment behind a load balancer create an API with a request header transformation, which adds a header with `$tyk_context.remote_addr` value. The API must display request headers (e.g. httpbin's `headers` resource).
2. Make sure context variables are enabled for this API.
3. Make a request to it and observe custom headers. The added header will show the IP of last hop before the gateway instead of the client's IP.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.8 and most likely all the previous ones.

**Comment by mvdan** [comment]
I've touched this code before, should be simple enough.
