### ISSUE TITLE
Policy source as file is not valid

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1034]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
```
    "policies": {
        "policy_source": "file",
        "policy_record_name": "./policies/policies.json"
    },
```
Configured the policy as above, and I can see the policy is loaded when the tyk starts. But actually, the data in the policies.json is not applied, which can be verified via the dashboard.
**What is the expected behavior?**
Load the policy as what I defined in the separated `policies.json` file, instead of from dashboard service or even mongo.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Modify the `policies` field of `tyk.conf ` as above, and modify the info in the json, then view the policy from dashboard.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.7

P.S. If the way I use separated policy is not correct, please  specify, since I have already followed your doc here https://tyk.io/docs/security/security-policies/policies-guide/ .

**Comment by lonelycode** [comment]
This is not a bug, tyk community edition is configured with files and does not use the dashboard at all. There is no link between the files in the gateway and the dashboard.

**Comment by hustshawn** [comment]
Do you mean if I use the dashboard, the file configured policy would not work?

**Comment by lonelycode** [comment]
What I mean is that's you need to use a file based configuration and not use the dashboard, or use a dashboard based configuration and no files - the two are mutually exclusive. Trying to use them together causes weird behaviour.

Basically, if you are using dashboard, you are using Tyk Pro, and should use tutorials and guides that are focussed on the dashboard.

If you are using just the gateway, then you are using community edition, this can only be configured with files.
