### ISSUE TITLE
Allow to configure "target url" and "Authentication mode" per API version

### ISSUE THREAD

**Issue by dlecan** [TykTechnologies/tyk#104]
"target url" and "Authentication mode" can be configured by API.

I have a use case where api versionning leads to different target URL:
- V1 -> http://first_internal_endpoint
- V2 -> http://another_internal_endpoint

I know I could create a new API, but from a client view, this is really "just" a new version of the API.

Allow to configure "target url" and "Authentication mode" per API version would answer to this use case.

**Comment by lonelycode** [comment]
It's possible, but we'd need to move all targeting from the main definition into the version info, that includes service discovery. It would basically create a whole new API definition within the definition object.

Might be easier to just create a new version... ;-)

This might be a consideration for v2, hwere we make breaking changes to definitions, and might separate out targets completely.

**Comment by lonelycode** [comment]
Target can now be changed per version. Auth not yet.
