### ISSUE TITLE
Add support for a canonical path instead of the request's one

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1040]
**Do you want to request a *feature* or report a *bug*?**
Feature/bug

**What is the current behavior?**
Tyk bases its decisions on the URL.Path as it passes through the MW, if it changes the path in some way, other MW needs to work on the transformed path. This is undesirable.

**What is the expected behavior?**
I should be able to base all tracking and MW matches on the canonical inbound path that first hits the gateway.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Create an API
Add a URL rewrite for pathA to PathB
Add a response transform for pathA

Expected: Response transform fires
Actual: Response transform does not fire, if you modify it to be based on pathB, it will fire.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

An easy fix for this would be to keep a copy of the original URL object in the context, thennuse this for matches - to retain backwards compatibility, we should do a second check on the actual URL object if there's a miss on the first one.

The canonical object should then also be used for analytics - this will improve accuracy.

**Comment by lonelycode** [comment]
Edit: This should apply before stripping the listen path.

**Comment by buger** [comment]
What if just add new AnalyticRecord field, which contains new value?

**Comment by lonelycode** [comment]
Then the filters in dashboard need to be rewritten to use the new field too, feels like duplicating data and indexes. 

That’s a lesser problem though, the bigger issue is the matching between middleware.
