### ISSUE TITLE
As a user I should be able to override the full response from JSVM middleware

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1043]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can't modify responses from middleware, only errors

**What is the expected behavior?**
I should be able to use `ReturnOverrides` to modify a response.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
I assume this it 2.4 ?

**Comment by buger** [comment]
Coprocess part was implemented in terms of https://github.com/TykTechnologies/tyk/pull/763

**Comment by lonelycode** [comment]
If it fits and can be tested, would be good to put it into 2.4, but since it's not in the project plan it won't be the end of the world if it makes it into 2.4.1

**Comment by mvdan** [comment]
@buger we already merged the PR, so this should be closed I think (or at least kept in 2.4 so we add the docs for it)

**Comment by mvdan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JSVM middleware plugins that act on the response object](https://trello.com/c/tTUOP0KT/120-jsvm-middleware-plugins-that-act-on-the-response-object)

**Comment by buger** [comment]
@matiasinsaurralde just to clarify, it was fixed for JSVM too? And if so, can I see some examples?

**Comment by matiasinsaurralde** [comment]
Looks like it was fixed for JSVM too, by Martin. I think we don't have any samples for this 😮

**Comment by buger** [comment]
@matiasinsaurralde if you can provide the sample, we can update docs. Thank you!

**Comment by l3ender** [comment]
Is this different than https://github.com/TykTechnologies/tyk/issues/1526

**Comment by sedkis** [comment]
Nope, same!
