### ISSUE TITLE
TykJsResponse: not available in JSVM middleware but only Virtual Path functions

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1049]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The `TykJsResponse` gives complete control over what tyk returns to the caller based on code you define in a function, but it is only available when using Virtual Path functionality. It is not available in JSVM middleware which only presents the extremely limited "ReturnOverrides" functionality which also wraps everything in JSON which is not always desired.

**What is the expected behavior?**

Whether using VirtualPath functions or JSVM middleware, the developer should be able to have full control over the response returned in a fashion similar to `TykJsResponse`

The features themselves are so close in functionality and purpose, it just seems odd the inconsistency in the API/feature set in regards to TykJsResponse being available for use

In order for us to implement what we want (interception of request and full mutation of response) we are limited to VirtualPath functions which have to be replicated across many api defs rather than referenced via bundled and versioned middleware.

The workaround is putting the VirtualPath function in tyk.js and referencing the function name in every API def VirtualPath matches, but again this is less than ideal and requires further customization of a default container/installation. 

This (`TykJsResponse`) should simply be available in the JSVM middleware API. ReturnOverrides works for simple error use cases, but the JSON wrapping it does of the desired body (and content type) is assumed (but not always desired)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.3.8

**Comment by lonelycode** [comment]
this is already possible with non-JS middleware using the ReturnOverrides object, and a patch for JS has been put in place for a future version.

If you want to get this to work, use a rich plugin and not the JSVM.

**Comment by lonelycode** [comment]
Relevant PR: 
https://github.com/TykTechnologies/tyk/pull/1042

**Comment by bitsofinfo** [comment]
It appears this support was added? in #1042, the docs however don't see to reflect it. 

https://tyk.io/docs/customise-tyk/plugins/javascript-middleware/middleware-scripting-guide/

**Comment by buger** [comment]
You are right field was added to the docs, but description itself not. 

@marksou we need to extend JSVM guide with `return_overrides` example similar to what we have in python guide https://tyk.io/docs/customise-tyk/plugins/rich-plugins/rich-plugins-work/#returnoverides

Example code:

```
var testJSVMData = new TykJS.TykMiddleware.NewMiddleware({});

testJSVMData.NewProcessRequest(function(request, session, config) {
	request.ReturnOverrides.ResponseError = "Foobarbaz"
	request.ReturnOverrides.ResponseCode = 200
	request.ReturnOverrides.ResponseHeaders = {
		"X-Foo": "Bar",
		"X-Baz": "Qux"
	}
	return testJSVMData.ReturnData(request, {});
});
```
