### ISSUE TITLE
Expose request headers to $tyk_context

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1051]
**Do you want to request a *feature* or report a *bug*?**
Feature/enhancement

**What is the current behavior?**
Initially, the issue was raised because there is no way to "rename" request header without middleware. If we will have headers in $tyk_context, the process of renaming header will be, deleting old header, and adding new with the original value.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by lonelycode** [comment]
So, headers are already exposed to context, you can access any header from context by using:

    $tyk_context.headers_HEADERNAME

Or (for body transforms):

    {{._tyk_context.headers_HEADERNAME}}

Relevant code has been [there for a while](https://github.com/TykTechnologies/tyk/blob/master/mw_context_vars.go#L39) It was just never documented.

**Comment by mvdan** [comment]
If I remember correctly, @matiasinsaurralde raised this following a user's request. Matias, you should describe this feature to the user, at least until we have proper documentation for it in place.

(do we have documentation for it now? should we ticket that up?)

**Comment by buger** [comment]
See #documentaton slack room. Documentation in process, and once done, matias will send a link
