### ISSUE TITLE
Add support for HEAD methods in the Dashboard API Designer

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1055]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I cannot set HEAD request matches in the API Designer though it should be supported by the gateway

**What is the expected behavior?**
That I can set HEAD matches

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Go to the API Designer, add an endpoint, try to change the method to HEAD

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All?

**Comment by ilijabojanovic** [comment]
Verified on Refactoring
