### ISSUE TITLE
As a dashboard admin I want to be able to create and assign access-control groups to other dashboard users

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1057]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently there is only one level of access for dashboard users, everyone is an admin. Or permissions can be manually self-assigned on each account.

**What is the expected behavior?**
An admin should be able to create and manage access-control groups that can be assigned to dashboard users. These would then restrict access to certain features and that user would not be able to change their own access control.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.8

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Access-level groups for dashboard users 🔑](https://trello.com/c/TJZtj407/485-access-level-groups-for-dashboard-users-%F0%9F%94%91)

**Comment by l3ender** [comment]
Is this still something that is planned and being worked on?

**Comment by buger** [comment]
Actually it is already done. Tyk Dashboard now has notion of User Groups. 
Just note that this feature available only for Pro licenses with >= 2 nodes.
