### ISSUE TITLE
As a Tyk user I want the access-level groups in the Dashboard to map to the access-level groups in my organisation 

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1058]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, the Tyk Identity broker (TIB) can't assign dashboard access permissions based on the existing groups the organisation has. Every user is assigned as an admin.

**What is the expected behavior?**
Access-level groups the organisation has, should be mirrored in the dashboard.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.8

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mapping my organisation's access-level groups to Dashboard access-level groups](https://trello.com/c/mn7yzIFg/486-mapping-my-organisations-access-level-groups-to-dashboard-access-level-groups)

**Comment by buger** [comment]
Do not forget about https://github.com/TykTechnologies/tyk-identity-broker/issues/9

**Comment by letzya** [comment]
Per @lonelycode: That should be handled in TIB, so add it to the product backlog.
