### ISSUE TITLE
Add PORT parameter for bootstrap script to add initial user and organisation

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1064]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
If we change listen_port in configuration file of the dashboard, the bootstrap script no longer run.

**What is the expected behavior?**
Add a second parameter in script for port or change LOCALIP parameter to include port number

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard  1.3.2

**Comment by mvdan** [comment]
It's a bit silly that the script takes a host and not an address. We could make it accept both `localhost` and `localhost:3000`, so that you may optionally give the port too.
