### ISSUE TITLE
Tyk always logs error on startup: "Instrumentation is enabled, but no connectionstring set for statsd"

### ISSUE THREAD

**Issue by ChristianCiach** [TykTechnologies/tyk#1066]
The error mentioned inside the title is always logged and cannot be disabled. "main.go" always calls `SetupInstrumentation(true)` (with the hardcoded `true`), regardless of any settings.

Seen with tyk-gateway 2.3.8.

**Comment by ChristianCiach** [comment]
Sorry, wrong project.

**Comment by buger** [comment]
Treat this message like a notification. But yeah, we should improve it.

**Comment by mvdan** [comment]
It's true that the flag is ignored since last december, and it's not clear why. I'll send a patch.
