### ISSUE TITLE
Directory bundles cannot be created 

### ISSUE THREAD

**Issue by raoulbillard** [TykTechnologies/tyk#1067]
When you add bundles in your tyk the directory "bundles" has to be created in /midleware and when tyk try to do so it failled. tyk version 1.3.9

**Comment by matiasinsaurralde** [comment]
Hi, are you using the packaged version of Tyk?
If that's the case run:
```
mkdir /opt/tyk-gateway/middleware/bundles
```

**Comment by raoulbillard** [comment]
I runned that and it work well, but in the future i hope that's may be fix.

**Comment by matiasinsaurralde** [comment]
Thanks, we've created an issue here #1068.
