### ISSUE TITLE
Provide a bundle directory by default

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1068]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
The user has to manually create the `middleware/bundles` directory when using plugin bundles.
The Hybrid image contains an empty "bundles" directory. The packaged versions don't.

**What is the expected behavior?**
Tyk could create it automatically or provide an empty directory.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Configure a plugin bundle
Start Tyk and wait for the plugin bundle download
Described in #1067 and other tickets.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Packaged versions of Tyk.

**Comment by mvdan** [comment]
Sounds like the right fix is to have the gateway create the dir if it doesn't exist - then we don't need to worry about shipping empty directories.

**Comment by lonelycode** [comment]
THRis has been done in the gRPC-proxy branch

**Comment by ilijabojanovic** [comment]
Released
