### ISSUE TITLE
Connect to Redis using UNIX socket?

### ISSUE THREAD

**Issue by toringe** [TykTechnologies/tyk#107]
Given the default configuration file for Tyk, it seems the connection to Redis can only be made over TCP., by specifying host and port. Would it be possible to also support unix domain sockets when running Redis on the same host as Tyk?

According to official Redis [documentation](http://redis.io/topics/benchmarks): 

> Depending on the platform, unix domain sockets can achieve around 50% more throughput than the TCP/IP loopback (on Linux for instance).

**Comment by mvdan** [comment]
Thanks for the suggestion, @toringe, and sorry about the long wait. Will look into this soon.
