### ISSUE TITLE
As a user I should be able to version API catalogue entries

### ISSUE THREAD

**Issue by ELE3E** [TykTechnologies/tyk#1082]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
You can add a Swagger definition as documentation. When you make an update to the API by adding a new version for example, you're not able to show the changes made to the API in terms of definition, analogue to the API setup itself.
**What is the expected behavior?**
Updateable Swagger definition per version
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All, not worked with previous versions

**Comment by buger** [comment]
Thank you! 

How do you think it should work/look instead?

**Comment by ELE3E** [comment]
To me it would seem logical to link api catalogues to existing API definitions, so that the catalogue is aware of all of the setttings you've entered there, like versions, slug definition, etc.
In fact, in my API setup required me to add a swagger definition with (in my case) an endpoint only at the root and put a slug in that is stripped upstream.
In the API Catalogue i had to add my slug to the endpoint, otherwise it wouldn't compose the right url. If I would have put the slug in the basePath, it would compose the url with a forward slash at the end (which doesn't work, should it work?)
In the case that the API definition is linked (optionally maybe) to the API definition, this could be just added to the url instead of having to customize the swagger defnition just for the documentations page.
I think it would be fair to allow for uploading an updated definition for newer versions.
This actually links a bit with #1083

**Comment by lonelycode** [comment]
Worth noting that the catalogue entries are linked to policies and can potentially grant access to multiple services as part of an aPI product, instead of just 1-to-1. 

So linking them up could be problematic in cases where the policy grants access to many apis. Which in micro service environments is very likely.
