### ISSUE TITLE
Add version and authentication imposed by API configuration in API Catalogue

### ISSUE THREAD

**Issue by ELE3E** [TykTechnologies/tyk#1083]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
You can add your swagger documentation to an API catalogue item, similarly as you've used that same documentation to create your API configuration. However, in the API configuration, you can add authentication on top and version it. This obviously requires the user to add version and authentication to the header/url. This is not reflected in the API Catalogue which makes the "Try it out" button not work as it expects the authentication and version to be there. Should this be added manually to the swagger definition for the catalogue entry? If so, how does one automatically use the key requested by that same developer before.
Another note: shouldn't the "Try it out" functionality be disabled as long as a developer has not actually requested and received a key?
**What is the expected behavior?**
I expect the "Try it out" functionality to be disabled if no key was requested and not granted
I expect to superimpose the versioning and authentication features, imposed by the API setup, to the documentation as well.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All, no prior version used before.

**Comment by buger** [comment]
@lghiur needs your input here
