### ISSUE TITLE
Support for OpenAPI v3

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#1084]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
OpenAPI v3 is not supported.

**What is the expected behavior?**
As a user I can import API definitions using OpenAPI v3 format, and I can also import definitions for use with portal documentation.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
N/A

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for OpenAPI v3](https://trello.com/c/sVJkI76u/488-support-for-openapi-v3)
