### ISSUE TITLE
Skip URL cleaning isn't working

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1093]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the custom HTTP server options are used and the "skip_url_cleaning" flag is enabled, the URL cleaning is still triggered.

**What is the expected behavior?**
The URL cleaning process should not occur. Seems like a regression of #377.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Enable "skip_url_cleaning".
Create an API
Send a request like "http://localhost:8080/test-api/http://tyk.io": a redirect to  "http://localhost:8080/test-api/http:/tyk.io" happens (this shouldn't happen)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest version.

**Comment by lonelycode** [comment]
@mvdan can you review that this doesn't undo some of the work you did on the reloads?
