### ISSUE TITLE
Set Default Expiration in Policy Creation

### ISSUE THREAD

**Issue by rilindo** [TykTechnologies/tyk#110]
It appears that there is no option to set the default expiration when we create a default policy. It resulted in confusion when we create a new key with the default policy and not realizing that it will expire premature. Consequently, we ended up having to remember to specify the default expiration date manually after we attach a policy.

It would be great to set the default expiration when we create a policy, which reduce the need to manually set it for every key we create.

**Comment by lonelycode** [comment]
This is a good point, will add it into the roadmap

**Comment by lonelycode** [comment]
Fixed in 1.9
