### ISSUE TITLE
How to use with Dynomite ?

### ISSUE THREAD

**Issue by mNantern** [TykTechnologies/tyk#1130]
I'm testing a multi-Datacenter Tyk deployment and I was trying it with [Dynomite](https://github.com/Netflix/dynomite) (it looks more lightweight than MDCB) but I have some issues right now:

1. Tyk is issuing some strange request like `CLUSTER INFO` which does not exist in redis 2.8.19 (my current version). I have `"enable_cluster": false` in my storage config.
2. `SUBSCRIBE tyk.cluster.notification` does not seem to be supported by Dynomite right now. Is it mandatory to run Tyk ?

Thank you !

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Tyk failed to connect to Redis through [Dynomite](https://github.com/Netflix/dynomite)

**What is the expected behavior?**
Tyk can use Dynomite in order to  provide cross Datacenter Replication

**Comment by mNantern** [comment]
You can find here the list of supported command by Dynomite:  https://github.com/Netflix/dynomite/blob/3ad2d235428175b10e6568e566f7ef76d11dc413/notes/redis.md

**Comment by buger** [comment]
Well, first of all, it is not right to compare MDCB with this project. Note that MDCB is not a k/v database, and also it does not allow you to have the multi-master configuration. The goal of MDCB is to control multiple data centers with a single dashboard, and in addition, in case of failover, seamlessly switch from one DC to another. Usually, when you want to have multi-master, the main issue becomes a latency between DCs', and your application logic (not only gateway) should handle it somehow. 

If we talking about Redis replacement, Tyk internally use https://github.com/TykTechnologies/tyk/tree/master/vendor/github.com/lonelycode/redigocluster/rediscluster (which is a fork), and probably "CLUSTER INFO" issue can be solved by not calling this function if "isCluster" set to false https://github.com/TykTechnologies/tyk/blob/master/vendor/github.com/lonelycode/redigocluster/rediscluster/rediscluster.go#L74 (feel free to open PR).

With PubSub (SUBSCRIBE), it will be harder. Tyk depends on it a lot, and the whole cluster keeps itself in sync thanks to pub-sub communication. If Dynamo do not support it, Tyk can't work with it.

If your DC's not located in different parts of the world, maybe you can consider using Redis Cluster, it is a quite mature project.

**Comment by mNantern** [comment]
Thank you for your response ! 

Indeed MDCB has not the same goal as Dynomite. I was just looking for a way to deploy a multi DC Tyk Open-Source so I only need Redis replication.

I will try with Redis Cluster, thanks !
