### ISSUE TITLE
tyk_quickstart docker-compose windows

### ISSUE THREAD

**Issue by manuelbcd** [TykTechnologies/tyk#1134]
I cannot run tyk quickstart on Windows7

 docker-compose up -d 

Output:
(windows: ERROR: for tyk_gateway  Cannot create container for service tyk_gateway: invalid bind mount spec)

**Comment by matiasinsaurralde** [comment]
Hi, can you try using this flag?
```
COMPOSE_CONVERT_WINDOWS_PATHS=1 docker-compose up -d
```
Best.

**Comment by manuelbcd** [comment]
Hi @matiasinsaurralde thanks for your response.  Yes already tried in two different laptops with windows7

ERROR: for tyk_pump  Cannot start service tyk_pump: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container
init caused \"rootfs_linux.go:57: mounting \\\"/c/docker/tyk_quickstart/pump.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0d2eff975d16b71bc80
756b6334fff23fc7055573ef815778fa55f41329f68a6\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0d2eff975d16b71bc80756b6334fff23fc7055573ef815778fa55f41329f68a6/opt/ty
k-pump/pump.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
