### ISSUE TITLE
Redis master/slave support

### ISSUE THREAD

**Issue by richard-hulm** [TykTechnologies/tyk#114]
When run in replication mode, you can have multiple redis nodes. Only the master node accepts writes, but any slave can be used for reading values.

Would it be possible to specify two DNS entries for redis, so we can have a write-enabled DNS and a read-enabled DNS, this would mean we could share the read-load across all the nodes?

**Comment by lonelycode** [comment]
Tyk doesn't do many pure reads - most keyspace activity is read/write (transactions), analytics are all writes, only initial key lookups for auth are pure reads. 

It's a possibility - we'd need to modify Tyk to use a read-only DNS for reads and seperate one for writes. 

Have you considered redis cluster?

**Comment by richard-hulm** [comment]
We have, but that seemed to be more geared towards different nodes for different keysets, and still left you with replica sets where only the master would accept writes.

For now we're not scaling for performance, so redis-cluster seemed like overkill for our needs.

It's not an essential feature by any means, as redirecting all requests to the master isn't the end of the world, just thought I'd see if it was easily doable

Cheers,

**Comment by lonelycode** [comment]
I see, we need a middle-ground.

Will investigate, it should be possible, the driver is quite malleable and needs some work inthe next version anyway. Will take a look.

I wonder if one of the proxies has already solved this (twemproxy etc)?

**Comment by richard-hulm** [comment]
Just an update on this as well - we've currently got our redis nodes separated by two DNS entries

We specify the redis-master DNS entry for Tyk, but on a failover, the DNS entry updates to use the new address. 

However, Tyk still seems to use the old node address, as (when it comes back up) it's still a valid Redis node, it just can't accept writes anymore. Do you have any suggestions as to how to get around this?

**Comment by lonelycode** [comment]
First check would be if the DNS update is propagated properly to the Tyk node?

Second option (and one most people use I think), is HAProxy + Sentinel. This would give you automatic failover without needing DNS changes, since HAProxy offers a single point of entry (you can active/standby this too if you need to), and then have sentinel elect a new master from your slaves, completely transparent to Tyk.

Nice little writeup here: http://www.101tech.net/2014/08/08/highly-available-redis-cluster/

**Comment by richard-hulm** [comment]
Yep it's definitely propagated to the node, just confirmed that.

We already use sentinel for fail-over, we just don't use HAProxy as we're using Consul for our service discovery, so we have a redis-master service with a health check, meaning the redis-master.service.consul address always points to the current master.

I agree HA proxy would be a solution here but am hesitant to add another item to our stack for this, would it not be possible to add hitting a slave node as another failure case which would prompt a retry forcing a refresh of the address?

Cheers,

**Comment by lonelycode** [comment]
I think I've spotted where it's going wrong:

https://github.com/lonelycode/tyk/blob/master/redis_cluster_handler.go#L71

When reads, writes or anything fails, the app is meant to re-run the Connect() function - this is fine if it's the same server, the connection just resumes (driver is quite clever like that). But this function is actually not doing anything since the db object is initialised already.

So it doesn't re-create the connection pool (as in, there's no system call to re-evaluate the IP addresses) which causes the behaviour you are describing... will look at this now.

**Comment by lonelycode** [comment]
Update on this, the driver handles reconnects just fine, but it's a deeper problem that will need some investigating (the reconnect IP is already resolved, which means that the entire connection pool needs to be destroyed and then recreated). DNS swapping won't be something easily fixed for now I'm afraid. Suggest a proxy approach for now.

**Comment by richard-hulm** [comment]
Hmm ok - thanks for having a look. We'll consider using something like HA proxy

**Comment by lonelycode** [comment]
I just took apart the storage handler and added a bunch of forced reconnects and disconnects to completely replace the pool.

It's a tricky problem, mainly trying to get all the components to listen to the same pool again. Will keep working on it, but no promises :-/

**Comment by richard-hulm** [comment]
Just revisiting this on our end - currently our "fix" is to restart the dashboard whenever the redis-master address changes, so it's always looking at the latest address, and adding retrys to our configuration service to handle the brief downtime....

Decided implementing a proxy would add too much complexity in terms of doubling up places which check which node is currently the master and adding to components which could fail

Is there any update on how possible this is on your side?

**Comment by lonelycode** [comment]
No update recently, we've been deep in finalising the next version, I will take a look at this once we've got the bulk of the new system ready, we're very close...

**Comment by mvdan** [comment]
@lonelycode if I undersatnd properly, we now support this? Or is a redis cluster a different thing?

**Comment by lonelycode** [comment]
@mvdan redis cluster is different from redis sentinel, it wil require a driver change as redigo has stopped adding new major features. There are wrappers and proposalls about though to add sentinel support (much like our cluster support is provided by a wrapper).
