### ISSUE TITLE
Response Transform middleware strips escaping characters

### ISSUE THREAD

**Issue by pastaman-lg** [TykTechnologies/tyk#1145]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Response transform middleware strips backslashes from JSON values

**What is the expected behavior?**
Resulting JSON object should have escaped characters preserved.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Input:
`{ "myField": "Here is \"the\" value" }`

Transform:
`{ "newField": "{{.myField}}" }`

Result:
`{ "newField": "Here is "the" value" }`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.8

**Comment by buger** [comment]
Thank you for reporting!

**Comment by mvdan** [comment]
This is sort of expected, because we decode the JSON and then use the value directly in the template.

Do we always want to keep JSON input as JSON, and XML input as XML? If so, then the fix for this is simple.

**Comment by mvdan** [comment]
@pastaman-lg please see the pull request above. In 2.4, you should use the following template:

    { "newField": {{.myField | jsonMarshal}} }

`jsonMarshal` will convert `foo"bar` into `"foo\"bar"`, so it will do what you're after.

**Comment by pastaman-lg** [comment]
@mvdan awesome, thanks for quick turnaround!

**Comment by ilijabojanovic** [comment]
Verified

**Comment by mvdan** [comment]
Not yet merged.
