### ISSUE TITLE
Customize dashboard notifications starting port via config file

### ISSUE THREAD

**Issue by csbogdan** [TykTechnologies/tyk#1147]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Port 5000 is hardcoded
**What is the expected behavior?**
Would like the ability to customize the starting port for dashboard notifications via dashboard config file
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customize dashboard notifications starting port via config file](https://trello.com/c/HNypZKSA/503-customize-dashboard-notifications-starting-port-via-config-file)

**Comment by ilijabojanovic** [comment]
Verified
