### ISSUE TITLE
`active` configuration flag not honored in API definition

### ISSUE THREAD

**Issue by klyr** [TykTechnologies/tyk#1151]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

- Only using Tyk gateway (no dashboard)
- Using .json configuration files

Creating a API with the "active: false" does not disable the API. Endpoints are still server regardless of the `active` flag being set or not.

**What is the expected behavior?**

When not using the dashboard,
When using .json configuration files for API definitions,

When the `active` flag is `false`, I expect the API to be disabled, even if the API configuration file is present.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Not working on current `master` (6a87c9cce0f8cd044f777f34a5f8d1e5ba91f421)
Was not working on (4b1a502bcf7a8cda41f2891fc64e0979630e901f)

In Tyk Gateway code, I cannot see any occurrence of code checking the value of the `Active` field of an API definition.

I suspect it's only used by the Dashboard, in this case, https://tyk.io/docs/tyk-rest-api/api-definition-object-details/ should be updated.

Cheers

**Comment by MangoMM** [comment]
I think I have managed to recreate this issue:

Inactive API
```
curl -X POST \
  http://localhost:8080/tyk/apis/ \
  -H 'cache-control: no-cache' \
  -H 'x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7' \
  -d '{
    "name": "Inactive",
    "slug": "inactive-api",
    "api_id": "inactive-api",
    "org_id": "53ac07777cbb8c2d53000002",
    "use_keyless": true,
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "use_extended_paths": true
            }
        }
    },
    "proxy": {
        "listen_path": "/inactive-api/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true
    },
    "active": false,
    "domain": ""
 }'
```

Active API
```
curl -X POST \
  http://localhost:8080/tyk/apis/ \
  -H 'cache-control: no-cache' \
  -H 'x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7' \
  -d '{
    "name": "Active Api",
    "slug": "active-api",
    "api_id": "active-api",
    "org_id": "53ac07777cbb8c2d53000002",
    "use_keyless": true,
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "use_extended_paths": true
            }
        }
    },
    "proxy": {
        "listen_path": "/active-api/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true
    },
    "active": true,
    "domain": ""
 }'
```

After a hot reload:
```
[Sep 28 20:42:50]  INFO main: Processed and listening on: /inactive-api/{rest:.*}
[Sep 28 20:42:50]  INFO main: Processed and listening on: /active-api/{rest:.*}
```

And a curl to http://localhost:8080/inactive-api/ returns the httpbin page.

**Comment by mvdan** [comment]
Commit reverted, as we need a better way to not break backwards compat.

**Comment by lonelycode** [comment]
Late to the party here - this field is only used by the dashboard, since on the gateway only configs, api ids are arbitrary, deleting the api altogether and recreating it is just as easy as setting a bool in the object.

We should update the documentation

**Comment by lflorit** [comment]
Yes but this means we have to manage the API configs elsewhere, not a big task but it has to be done...

**Comment by lonelycode** [comment]
Sure - however given this is a file-based configuration doing so with source control would be trivial.

Not saying this wouldn’t be nice to have - but it’s a feature request not a bug, we’ll prioritise it into a release instead of a patch.
