### ISSUE TITLE
As a dashboard user I want to be able to send encrypted keys to developers

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1152]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Current behaviour** 
Currently, if a developer requests a key using the portal, the key is sent to them via email, unencrypted. Some of our clients need a higher security layer than this.

**Requirements**
- I can turn on/off whether I want keys sent to developers via email, to be encrypted 
- If turned on, all keys developers receive via email will be encrypted
- Developers are provided a way to decrypt the key for use

**Comment by buger** [comment]
Not sure what you mean by encryption here. Instead of sending key, we can send link with a secret ID pointing to the portal, and key will be shown only 1 time, in portal UI.

**Comment by nickReyn** [comment]
That sounds good. I guess by encrypted I was referring to that if some intercepted/saw the email, they couldn't find out the key. 
I will follow up and ask for clarification with the client this idea came from.

**Comment by nickReyn** [comment]
HMAC secret would also need to be shown, not just the key

**Comment by Preravana** [comment]
Hi, I am using Tyk on-premise using Docker. Here, keys are not even sent to email. But in cloud version, Keys are automatically sent to email, once requests to key have made. Is there any solution for this?

**Comment by james-tyk** [comment]
Hi @Preravana - this ticket is about adding encryption to key notifications.  

Tyk (in docker) can send notifications, you can find details for that in the documentation here : https://tyk.io/docs/publish/portal-events-notifications/

Please note that support queries, should be directed to community.tyk.io or via your paid support account, our Github presence is for feature requests / bug reports, not tech support.
