### ISSUE TITLE
Dashboard "Traffic Activity by Key" allow searching by alias keywords

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1156]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Searching does not seem to work when searching for textual content within an session alias

**What is the expected behavior?**

Should be able to free text search against session alias text content

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
not stale @nickReyn

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.

Thank you for supporting Tyk.
