### ISSUE TITLE
Dashboard "Traffic Activity per API" allow sorting

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1157]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Dashboard "Traffic Activity per API" cannot sort 

**What is the expected behavior?**

Should be able to sort

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.
Thank you for supporting Tyk.
