### ISSUE TITLE
Dashboard "Traffic Activity per API" allow searching 

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1158]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Dashboard "Traffic Activity per API" cannot search on anything. (i.e. like search on the api name to filter things)

**What is the expected behavior?**

Should be able to search

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.
Thank you for supporting Tyk.
