### ISSUE TITLE
Pipe logging to correct files per logging level

### ISSUE THREAD

**Issue by csbogdan** [TykTechnologies/tyk#1159]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
All logging happens only in stderr, no matter the logging level of the entry. stdout is not used.
**What is the expected behavior?**
INFO and regular application log entries should be piped to stdout, whistle warning, error, critical and debug should go to stderr.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
I have never seen logging levels be put in stdout and stderr. And I'm fairly sure the general practice is to show logs in stderr, as they are messages and not actual program output.

Why would different output files be helpful? If you want to filter them, you can fairly easily do it with a program parsing line by line.

**Comment by csbogdan** [comment]
The only reason why splitting this makes sense for me is for centralized logging purposes, where we use different transformations and cleanup policies for different types of logs.

I'm not using tyk for long enough to know yet all types of log messages, so I can't argue on the  messages versus program output statement. However, looking at provided service file by tyk and how there's a clear intent to use two distinct logging streams, it seems there might be a plan to actually use stdout for something. In this case, it makes total sense to only use stderr for its intended purposes.

Changing info to stdout is a simple change, and getting back to current behavior can be easily be achieved with > /path/to/stderr_file 2>&1 at startup.

Cheers.

**Comment by mvdan** [comment]
Perhaps I'm missing something, but I still don't understand why you think stderr is just for errors. It has been used for all kinds of logging messages for a long time. Tyk needs to provide output in some modes, such as when importing APIs from swagger or when linting a configuration file (the last one is in the works), so we absolutely can't have the log messages be mixed with those.

Moreover, we have at least four logging levels - debug, info, warn and error. We would get into an endless discussion of where each one of them belongs.

> Changing info to stdout is a simple change, and getting back to current behavior can be easily be achieved

Note that this would break many user's programs and setups. A change being simple to implement doesn't mean it's simple for users to adapt or upgrade to.

As said before, the logs are formatted in a way that is easy to parse (however, I notice now that they're pretty-formatted even if you pipe its output like `tyk | cat`, will file an issue). It would be fairly trivial to write a program to filter by the logging level. And it would have none of the problems described above.

Hope this helps.

**Comment by mvdan** [comment]
Actually, I forgot to pipe the logs properly. If you do it with `|&`, you do get the easily-parseable output:

```
 $ tyk |& cat
time="Sep 28 09:25:59" level=info msg="PIDFile location set to: /var/run/tyk-gateway.pid"
time="Sep 28 09:25:59" level=info msg="Initialising Tyk REST API Endpoints"
time="Sep 28 09:25:59" level=info msg="--> Standard listener (http)"
[...]
```

**Comment by mvdan** [comment]
I still don't think this is worthwhile - particularly given that anything can be done by parsing the log output. Feel free to reopen if you have answers to my comment above, or anything to add in favor of the change.
