### ISSUE TITLE
Add way to validate inbound JSON objects with JSON Schema

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1163]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently inbound requests can;t be validated against a strict schema

**What is the expected behavior?**
I should be able to vlaidate inbound object into my API against a JSON Schema

**Comment by lonelycode** [comment]
Relevant PR (because the link failed, again): https://github.com/TykTechnologies/tyk/pull/1180

**Comment by buger** [comment]
@lonelycode you need include task number to issue comment not header, to make links work

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add way to validate inbound JSON objects with JSON Schema](https://trello.com/c/BcJr3TN4/504-add-way-to-validate-inbound-json-objects-with-json-schema)
