### ISSUE TITLE
JWT: Regenerate internal token if policy claim different

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1167]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JWT: Regenerate internal token if policy claim different](https://trello.com/c/gW0FVsYY/426-jwt-regenerate-internal-token-if-policy-claim-different)

**Comment by buger** [comment]
Should be fixed by https://github.com/TykTechnologies/tyk/issues/1379 in 2.5.X
