### ISSUE TITLE
JWT: Set a default policy ID if policy claim not set

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1168]
**Do you want to request a *feature* or report a *bug*?**
Feature

From Trello roadmap - need more information

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JWT: Set a default policy ID if policy claim not set](https://trello.com/c/HQeuLS67/425-jwt-set-a-default-policy-id-if-policy-claim-not-set)

**Comment by buger** [comment]
Was released as part of 2.8
