### ISSUE TITLE
UI: Enable the addition of pre, auth, postauth and post-proc middleware script links

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1174]
Do you want to request a feature or report a bug?
Feature

From Trello roadmap - need more information

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI: Enable the addition of pre, auth, postauth and post-proc middleware script links](https://trello.com/c/F6LmFNcz/377-ui-enable-the-addition-of-pre-auth-postauth-and-post-proc-middleware-script-links)

**Comment by andyo-tyk** [comment]
Tyk's extensive range of custom middleware options are documented here: https://tyk.io/docs/plugins/plugin-types/plugintypes/

Please re-open this ticket if you feel this does not answer your query.
