### ISSUE TITLE
NewMultiTargetProxy always returns nil on master

### ISSUE THREAD

**Issue by jacyo** [TykTechnologies/tyk#1177]
NewMultiTargetProxy return nil

bug bug

**Comment by buger** [comment]
Can you pls clarify your issue?

**Comment by jacyo** [comment]
The NewMultiTargetProxy always return nil on master branch

**Comment by mvdan** [comment]
Well, that is true, but it's always been like that - including on 2.3. What were you trying to do?

**Comment by mvdan** [comment]
Oh, actually not. It used to be an initialising method, and now it's a constructor. Seems like a regression that we didn't catch because it has no tests.
