### ISSUE TITLE
Trigger debug mode from tyk.conf instead of the command line

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1182]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behaviour?**

The gateway can be started in debug mode using --debug or TYK_LOGLEVEL=debug command. 
However a hybrid customer who can only affect their gateway instance through it's configuration file would like to be able to start debug mode with a config option.

**What is the expected behaviour?**

User set's a json field in the tyk.conf such as "debug_mode": "true", and this sets the log output to debug mode.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions

**Comment by mvdan** [comment]
Let me suggest adding a `loglevel` or `log_level` one instead. That way, we cover the possibility of setting other log levels, not just `debug` and `info` (the latter being the default).

It would take the same values that `TYK_LOGLEVEL` can.

**Comment by joshblakeley** [comment]
Good idea @mvdan
