### ISSUE TITLE
As a "super-admin" user I want to be able to manage organisations on a dashboard

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1189]
Nick to add more details next week

**Comment by agata-wit** [comment]
@nickReyn I know this is a very old request but would you mind adding some more info about the expected functionality? What would you like the experience to be like? What should be possible to do?

**Comment by joshblakeley** [comment]
@agata-wit Nick hasn't worked for Tyk for years so probably not right to expect a response
