### ISSUE TITLE
APIs loaded from file not in dashboard

### ISSUE THREAD

**Issue by joshbenner** [TykTechnologies/tyk#119]
I have an API loading via /etc/tyk/apps. I can confirm it exists in Tyk by requesting it via node/apis/{id}. However, it does not appear in the dashboard, and I cannot access via the advanced management API, even with a user without any organization ID (ie: super-user, as I understand it).

What am I missing?

**Comment by lonelycode** [comment]
If you want to use the dashboard, you'll need to configure Tyk to load Apis from mongo DB. The dashboard does not work with Tyk in file-based mode. File based mode is basically tyk's stand-alone setting (so it can just work or of the box, no dependencies except Redis).See step 1 here:https://tyk.io/v1.8/setup/install-dashboard/

**Comment by joshbenner** [comment]
I'm looking for a workflow that lets us maintain API definitions in source control and deploy them with simple, repeatable steps, while also having the advantages of dashboard. Is there a different direction I should sniff in?

**Comment by lonelycode** [comment]
You could use a small script that pushes the file based versions to the advanced API:

https://tyk.io/advanced-api-v0-9/api-definitions/
