### ISSUE TITLE
Provide a way to override upstream target in middleware

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1192]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Currently middleware cannot override upstream target.
**What is the expected behavior?**
Support is added for overriding upstream URL from middleware plugin e.g. with header or context variable
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by tyomo4ka** [comment]
@lonelycode What's the status of this?

**Comment by asoorm** [comment]
@buger I think this issue can be closed
@tyomo4ka Feature has been available for quite some time

https://tyk.io/docs/release-notes/version-2.5/#advanced-url-rewrites
https://tyk.io/docs/transform-traffic/url-rewriting/

Tyk 2.8 also introduces looping support which allows more complex request pipelines. https://tyk.io/docs/release-notes/version-2.8/#looping
