### ISSUE TITLE
Update gateway upstream cache control to enable canonical header support for caching operations

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1195]
Add a new option `EnableUpstreamCacheControlWithCanonicalHeaders`, if set, this will implement caching behaviour based on the rules set by the [standard cache-control headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control). 

The current cache control allows for custom headers to be used, but it is not very powerful or standards compliant

**Comment by davegarvey** [comment]
Same as #604 ?
