### ISSUE TITLE
Custom Config passed through the Spec object to CoProcess Middlewares

### ISSUE THREAD

**Issue by ArturoSerrano** [TykTechnologies/tyk#1197]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The current behavior is that the spec object in the coprocess middleware only contains the APIID and the ORGID.

**What is the expected behavior?**
We want to be able to pass any fields through the Spec object.  We are aware of the ConfigData being available to JavaScript plugins, however, due to the map[string]interface{} type not being compatible with any protobuf3 field, that object can't be passed to CoProccess plugins.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Not a bug
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest

Please see the following requests relating to this:
https://community.tyk.io/t/python-plugin-spec-fields/1925
https://community.tyk.io/t/config-data-in-a-python-middleware/1924

I am working on a PR for this.  It will create another field in the tyk.conf that will be a map[string]string which can be inserted into the protobuf3 Spec field.

PR: https://github.com/TykTechnologies/tyk/pull/1198

**Comment by matiasinsaurralde** [comment]
Hi, thanks, sounds like a very useful enhancement!
