### ISSUE TITLE
Reset password link is broken

### ISSUE THREAD

**Issue by dave-kennedy** [TykTechnologies/tyk#120]
Click "Forgot password?" link on [this page](https://cloud.tyk.io/login) takes you [here](https://cloud.tyk.io/reset-password.html), which is a 404:

![image](https://cloud.githubusercontent.com/assets/13735532/10522091/884c0d70-7330-11e5-9fe5-a2c11bb26a12.png)

**Comment by lonelycode** [comment]
Thanks for the heads up - we'll check it out. In the mean time, If you want us to reset your password let us know at support@tyk.io :-)

**Comment by dave-kennedy** [comment]
Thanks but I figured it out. I have two passwords - one for cloud.tyk.io and one for admin.cloud.tyk.io, which was confusing me.
