### ISSUE TITLE
The API Token to get list of keys return all keys whatever the api-id value

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1214]
**Do you want to request a *feature* or report a *bug*?**
bug on Tyk Dashboard v1.3.9

**What is the current behavior?**
The API Token to get list of keys for an api return all the keys whatever the api-id in url : /api/apis/{api-id}}/keys
The api /api/apis/{api-id}}/keys/{key-id} have the same problem.

**What is the expected behavior?**
The API should return only the keys for the api-id provided.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I use curl with this command :
`
curl --insecure -H "authorization:myauth" https://myserveri/api/apis/toto/keys
`
The API "toto" doesn't exist in my dashboard.

return for example :
`{"data":{"keys":["59ad23838dc4d829ab360d0592411c47981846f55cef1780b199ee5e","59ad23838dc4d829ab360d05a9cbf4f720724a6f6d28846e870f6833","59ad23838dc4d829ab360d05f5539cb5b3d049c658c43dcbca6c3579","59ad23838dc4d829ab360d05d17598b1574446837dccf92568e0ce5f"]},"pages":0}
`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard v1.3.9

**Comment by joshblakeley** [comment]
This is not a bug. The reason the api-id is in the request just to identify the back-end to query.
This is somewhat non-intuitive and we will change our docs to help clarify.
