### ISSUE TITLE
Wrong page number in responses API

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1215]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
The page number in json response api for API Dashboard and API Admin Dashboard start by zero. 

**What is the expected behavior?**
The page number should start by 1.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
With curl

`
curl --insecure --silent -H "admin-auth:12345" https://orion-dev-apidashboard-1.zsi.agri/admin/organisations/
`
returns 
`
{.... ,"pages":0}
`
it should be :
`
{.... ,"pages":1}
`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.3.9

**Comment by mvdan** [comment]
Thanks for reporting!

We noticed this too a while ago, and there already are a couple of internal issues open about it (where the dashboard code lives). I'm going to close this one in favor of the others. Until the fix is released, this is a off-by-one error so it should be easy to work around.
