### ISSUE TITLE
pass HTTP method to gRPC plugin request

### ISSUE THREAD

**Issue by amitmandke** [TykTechnologies/tyk#1219]
**Do you want to request a *feature* or report a *bug*?**
new feature
**What is the current behavior?**
HTTP method (GET, POST etc) is not available in gRPC plugin. 
**What is the expected behavior?**
Make HTTP method available in "MiniRequestObject" for gRPC plugin. Or any rich plugin for that matter.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
NA (new feature)
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
NA (new feature)

**Comment by Rouzz** [comment]
Hi, I came by the same issue.
Any info on when it will become available ?

My only hope so far is for each method of the API to add some kind of 'X-HTTP-method' header that will allow the middleware to process requests based on HTTP methods.
That's the only way I could think of in the meantime :)

**Comment by buger** [comment]
@matiasinsaurralde so, it looks like we need extend our protobuffers file, and include this field.

**Comment by buger** [comment]
Was implemented in 2.5
