### ISSUE TITLE
PYTHONPATH isn't correctly set in some environments

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1221]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Tyk isn't able to initialize the Python dispatcher because the PYTHONPATH isn't correctly set (sometimes it doesn't include the Tyk root directory: "/opt/tyk-gateway").
Same occurs with the extracted bundle directories.

**What is the expected behavior?**
The dispatcher should work fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
It's hard to reproduce but from internal reports we know that it occurs sometimes, specially when the users create their custom initialization scripts, etc.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All.

**Comment by ilijabojanovic** [comment]
Released
