### ISSUE TITLE
Dashboard: broken pagination Portal Management -> Pages

### ISSUE THREAD

**Issue by antizol** [TykTechnologies/tyk#1222]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Regardless of the selected page, the dashboard will only show the first page, meaning some pages are not accesible from the UI. 

**What is the expected behavior?**
All pages need to be accesible from the UI according to the page the user has selected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Tyk Dashboard: go to -> Portal Management -> Pages
- Create 10+ page templates (so the UI needs at least 2 pages to display them
- navigate through page 1 and 2

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard 1.3.7

**Comment by ft-george-toader** [comment]
app.js change line 9097 to PortalPages.get({p:$scope.current_page},

Please fix asap.
Thank you!

**Comment by ConsM** [comment]
Thanks for reporting it. This bug fix will be part of the next release

**Comment by lonelycode** [comment]
As a workaround (while we fix) it is possible to increase the average page size from 10 to an arbitrary value by setting a new size in the `tyk_analytics.conf` called `page_size`

**Comment by buger** [comment]
This is fixed in 2.4 which going be released in the next few weeks
