### ISSUE TITLE
Improve "Registered API Configurations" screen in dashboard

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1233]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

non-existant search/sort options on the "Registered API Configurations" screen. Makes is quite cumbersome for admins to find an api.  Also the last "page" of the pagination is always empty (bug)

**What is the expected behavior?**

Should be able to search/sort the listed apis rather than having to click page after page to find what you want to manage.

**Comment by nickReyn** [comment]
Thanks for this. We have this on our roadmap as part of ongoing improvements to the dashboard. Keep an eye on the next few dashboard releases 👍

**Comment by nickReyn** [comment]
https://github.com/TykTechnologies/tyk-analytics/issues/448

**Comment by buger** [comment]
API search is planned for 2.5

**Comment by nickReyn** [comment]
Closing this as search was released as part of v1.5 . More advanced search and sorting options to come in v1.6.
