### ISSUE TITLE
Expose "domain" field in API definition dashboard editor

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1234]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Cannot edit the "domain" attribute value of an api definition in the hybrid dashboard

**What is the expected behavior?**

Should be able to edit the "domain" attribute of an api definition in the hybrid dashboard

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.3.9

**Comment by nickReyn** [comment]
hey @bitsofinfo we're going to be releasing a feature in the API designer UI which enables you to edit the raw api definition, which should solve this issue, and also address issues you have raised before about exposing more API def options in the UI.

Aiming for 2.6 release for this.

**Comment by asoorm** [comment]
Think we can close this ticket.

![screen shot 2018-05-15 at 14 40 50](https://user-images.githubusercontent.com/1465130/40060361-4acf168a-584e-11e8-993f-ea36a65ccdb1.png)
