### ISSUE TITLE
Invalid dashboard JSON import results in silent failure 

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1235]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When importing some JSON for a new API def in the hybrid dashboard, if the JSON has some syntax error, the form is submitted but no error/warning is displayed. The api list remains the same but there is no message presented to the user. 

**What is the expected behavior?**

Please present a simple warning/or error message indicating the error

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.3.9 hybrid, cloud dashboard

**Comment by peloncano** [comment]
+1 the UI needs to be consistent across the dashboard letting the user know that the JSON was invalid, similar to the way it is done in Advanced Options -> Config Data.

![2017-10-19_jsi6o](https://user-images.githubusercontent.com/1165911/31795676-bd6e8a16-b4f4-11e7-85ae-ab0637c00187.jpg)

**Comment by ConsM** [comment]
Thanks for reporting it. We have raised an issue and will be improved in the next release.

**Comment by buger** [comment]
@ConsM it feels like we fixed this bug in 2.4, can you pls re-check?

**Comment by ConsM** [comment]
Yes this is fixed in 2.4 and will display a more verbose error message
