### ISSUE TITLE
Python middleware path issue with protected api

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1238]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we reload api definition protected with auth, middleware is still purged
Example
```
tyk-gateway_1    | time="Oct 23 02:45:37" level=warning msg="Purging middleware: 'middleware'"
tyk-pump_1       | time="Oct 23 02:46:14" level=info msg="Writing 1 records"
tyk-pump_1       | time="Oct 23 02:46:14" level=info msg="Purging 1 records"
tyk-gateway_1    | time="Oct 23 02:46:23" level=warning msg="Key not found in storage engine" err="Key not found" inbound-key="****10a5"
tyk-gateway_1    | time="Oct 23 02:46:23" level=error msg="Can't dispatch 'MyLDAPMidleware', hook is not defined."
```
**What is the expected behavior?**
Gateway reload should reload all api definitions with custom middleware 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
@matiasinsaurralde you need to made same PR for master too?

**Comment by ilijabojanovic** [comment]
Verified

**Comment by buger** [comment]
@matiasinsaurralde Keeping it open so you would not forget merge it to master

**Comment by mvdan** [comment]
@buger @matiasinsaurralde I assume this must go into 2.4 too - has it been taken care of?

**Comment by buger** [comment]
This fix contained breaking changes required users middleware files be named `middleware.py`, so lot of user middleware broke. Trying to find solution which is cross compatible.
