### ISSUE TITLE
When using ReturnOverrides, queries are not shown in Log browser

### ISSUE THREAD

**Issue by Rouzz** [TykTechnologies/tyk#1245]
**Do you want to request a *feature* or report a *bug*?**
I guess it's a bug.

**What is the current behavior?**
When using ReturnOverrides, the request flow is stopped and thus the analytics middleware is bypassed.

**What is the expected behavior?**
I would expect that queries that got resolved via ReturnOverrides are shown in the logs like any other queries of the API.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
* Create a post middleware in NodeJS (gRPC)
* Stop the request flow using ReturnOverrides
* Test the middleware
* Check that the call is not shown in the Log browser

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

Thanks !
Robert

**Comment by buger** [comment]
Thank you for reporting!

We are going to fix it in 2.5
