### ISSUE TITLE
Python/CP Session objects do not carry metadata information through

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1249]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I set the metadata object in middleware, it does not get carried through to the object that gets stored in Tyk. 

Usually I would use metadata to set headers later on in the request chain, but in the case of dynamic middleware, I *can* set this in the middleware, however this requires every request to pass through my middleware for the same user.

If I am using the ID extractor, I can use the meta data field of the session objec tto store information to have Tyk inject, which would be much faster than having my middleware do it.

**What is the expected behavior?**
When I set:

```
session.metadata = json.dumps({"foo":"bar"})
```

For it to be available in the `SessionState` object. So that I can reference it in other parts of my gateway configuration.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Follow this guide to create an auth middleware: https://tyk.io/docs/customise-tyk/plugins/rich-plugins/python/custom-auth-python-tutorial/
- Modify `middleware.py` to include:

```
import json      # <--- Add this

@Hook
def MyAuthMiddleware(request, session, metadata, spec):
    auth_header = request.get_header('Authorization')
    if auth_header == '47a0c79c427728b3df4af62b9228c8ae':
        session.rate = 1000.0
        session.per = 1.0
        session.metadata = json.dumps({"foo":"bar"})     # <--- Add this
        metadata["token"] = "47a0c79c427728b3df4af62b9228c8ae"
    return request, session, metadata
```

 - Create a new API that has a global inject:

```
"version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default",
        "use_extended_paths": true,
        "global_headers": {
          "x-foo": "$tyk_meta.foo",
          "x-bar": "baz"
        }
      }
    }
  },
```

Make a request to your API:

    curl http://<IP Address>:8080/my-api/my-path -H 'Authorization: 47a0c79c427728b3df4af62b9228c8ae'

You should see:

```
~/s/tyk-develop-env> http GET localhost:8181/testing/get "Authorization:Basic YWRtaW46U2VjcmV0MTIz3"
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 363
Content-Type: application/json
Date: Mon, 30 Oct 2017 00:11:59 GMT
Server: meinheld/0.6.1
Via: 1.1 vegur
X-Powered-By: Flask
X-Processed-Time: 0.000876903533936
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 99
X-Ratelimit-Reset: 1509322320

{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Authorization": "Basic YWRtaW46U2VjcmV0MTIz3",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.9",
        "X-Bar": "baz",
        "X-Foo": "bar"
    },
    "origin": "172.18.0.1, 202.89.129.13",
    "url": "http://httpbin.org/get"
}
```

You will see (No `X-Foo` header):

```
~/s/tyk-develop-env> http GET localhost:8181/testing/get "Authorization:Basic YWRtaW46U2VjcmV0MTIz3"
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 363
Content-Type: application/json
Date: Mon, 30 Oct 2017 00:11:59 GMT
Server: meinheld/0.6.1
Via: 1.1 vegur
X-Powered-By: Flask
X-Processed-Time: 0.000876903533936
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 99
X-Ratelimit-Reset: 1509322320

{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Authorization": "Basic YWRtaW46U2VjcmV0MTIz3",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.9",
        "X-Bar": "baz"
    },
    "origin": "172.18.0.1, 202.89.129.13",
    "url": "http://httpbin.org/get"
}
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by ilijabojanovic** [comment]
Verified @lonelycode we also should merge this on 2.4 release.

**Comment by buger** [comment]
already merged
