### ISSUE TITLE
[Request] Tyk-Dashboard package for Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by dragon28** [TykTechnologies/tyk#1255]
Hello Tyk Developers,

I am requesting tyk-dashboard package for Ubuntu 16.05 xenial.

Thank you.

**Comment by buger** [comment]
@excieve can we extend package cloud to do this? Right now we have packages only for `trusty` and `precise`

**Comment by buger** [comment]
@dragon28 even now you can download deb file from here and install it manually https://packagecloud.io/tyk/tyk-dashboard

**Comment by excieve** [comment]
@dragon28 Manually changing the distro release to `precise` in `/etc/apt/sources.list.d/tyk_tyk-dashboard.list` (and other tyk repos) should work just fine until we add a package specifically for it. We don't really depend on anything distro-specific in these packages.

**Comment by dragon28** [comment]
Hello @buger and @excieve 

Thank you for replying and providing support.

It help a lot with the solution which provided by you guys :+1: 

Thanks again
