### ISSUE TITLE
A setting to enable/disable enforced unique naming for APIs and Policies

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1257]
## The problem
We do not enforce API and policy naming to be unique, which causes problems when multiple users are using one dashboard. We should enable our users to choose whether to enable/disable this, so it doesn't introduce breaking changes to those with existing APIs and Policies.

## Solution
Enable users to toggle whether they would like API and policies to enforce unique naming. The default would be OFF, not introducing breaking changes to existing APIs and Policies.

If switched on, display an error message when a non-unique name is used

**Comment by nextmetaphor** [comment]
Having unique API names is particularly important when setting up policies: if duplicate API names are used then it makes it almost impossible to understand which API a policy is referencing, as it is the API `name` field (and not the underlying `api_id`)  that is displayed in the dashboard.

If duplicate API names are permitted, it may be worth showing both fields (`name` and `api_id`) in the dashboard to help differentiate here.

**Comment by buger** [comment]
> If duplicate API names are permitted, it may be worth showing both fields (name and api_id) in the dashboard to help differentiate here.

Like it! If API has same names, detect it on UI and attach API ID, smth like "API 1: <api-id>". Should work only for dropdowns.
