### ISSUE TITLE
"Create API Definition" Dashboard Call Overwrites "api_id" Field

### ISSUE THREAD

**Issue by nextmetaphor** [TykTechnologies/tyk#1265]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The [`/api/apis/ [POST]`](https://tyk.io/docs/tyk-dashboard-api/api-definitions#create-api-definition) dashboard API accepts an `api_definition` object which may contain an `api_id` field. However, if this field is specified it is overwritten by an auto-generated value. 

**What is the expected behavior?**
If the `api_id` is not specified then an auto-generated value should be used; however, if an `api_id` field is specified, then the value specified should be used and not be overwritten. Additionally, the call should fail if the `api_id` is not unique.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See [https://community.tyk.io/t/how-create-an-api-definition-with-custom-api-id/319](https://community.tyk.io/t/how-create-an-api-definition-with-custom-api-id/319).

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I'm not aware of any previous versions when this worked.

**Comment by lonelycode** [comment]
I believe you can set the api_id with a PUT

**Comment by buger** [comment]
I will close it. Feel free to re-open if PUT wont work for you.

**Comment by tomirio619** [comment]
I'm experiencing the same problem as described initially (using Tyk 2.9.3.1). Creating an API with POST on `/api/apis` overrides the provided `api_id`. A PUT on that same API `/api/apis/id` with an `api_id` in the API definition does not change the `api_id`.

**Comment by tomirio619** [comment]
An example that shows this behavior:
```python
import json
import os

import requests

TYK_DASHBOARD_API_URL = os.getenv("TYK_DASHBOARD_API_URL")
TYK_DASHBOARD_API_KEY = os.getenv("TYK_DASHBOARD_API_KEY")

session = requests.Session()
session.headers.update({"Authorization": TYK_DASHBOARD_API_KEY})

api_def = """
{
  "api_id": "e830046147ae4a7d7c98570783ce67ff",
  "org_id": "5e554e19274a9600012a3eb1",
  "name": "KNMI KDP Open Data API",
  "slug": "open-data-api",
  "active": true,
  "auth": {
    "auth_header_name": "authorization"
  },
  "definition": {
    "location": "header",
    "key": "version"
  },
  "version_data": {
    "not_versioned": true,
    "default_version": "",
    "versions": {
      "v1": {
        "name": "v1"
      }
    }
  },
  "proxy": {
    "target_url": "http://httpbin.org",
    "strip_listen_path": true,
    "listen_path": "/hello-world/"
  }
}
"""
api_def = json.loads(api_def)

session = requests.Session()
session.headers.update({"Authorization": TYK_DASHBOARD_API_KEY})
create_response = session.post(TYK_DASHBOARD_API_URL + "/apis", json={"api_definition": api_def})
internal_api_id = create_response.json().get("Meta")
update_response = session.put(TYK_DASHBOARD_API_URL + "/apis/{}".format(internal_api_id),
                              json={"api_definition": api_def})

get_response = session.get(TYK_DASHBOARD_API_URL + "/apis/{}".format(internal_api_id))
api_id = get_response.json().get("api_definition").get("api_id")

# should print true if api_id is updated successfully
print(api_id == api_def.get("api_id"))

```
