### ISSUE TITLE
Show / Allow Filtering of APIs in Dashboard Based on Segmentation Tag

### ISSUE THREAD

**Issue by nextmetaphor** [TykTechnologies/tyk#1266]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The "Select API" screen on the dashboard doesn't indicate (or allow filtering on) [segmented gateways](https://www.tyk.io/docs/manage-multiple-environments/with-on-premise/#configure-gateway-as-shard).

**What is the expected behavior?**
It would be helpful if the APIs deployed on segmented gateways could be identified from the dashboard, in order to answer "*what APIs are deployed on segment x?*" queries

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I'm not aware of this being supported in any previous versions of the dashboard.

**Comment by lonelycode** [comment]
The segments aren’t in the dashboard drop down, but they are available as tags - if you add the name of the segment to the tab list filter and run the query it will segment the data on the tag (the cluster segment). 

We may wan to clarify that in the docs

**Comment by buger** [comment]
We plan to implement API search user interface in 2.5, and this issues should be solved.
