### ISSUE TITLE
API loader is fragile when many endpoints are set up on a single domain

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1271]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a hybrid node is reloading, there is a chance that two similar paths that only slightly differ in length will load in a different order.

**What is the expected behavior?**
The endpoints should always load in longest-first order

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create Two APIs with *slugs* of user and user-login
2. Differentiate them somehow (maybe a header inject)
3. Send requests to the gateway between hot reloads - the match order will swap

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Hybrid, potentially others

**Comment by mvdan** [comment]
If this was indeed on stable (since Hybrid runs 2.3.x), my recent sort order changes like 177758fe93fb8bc78ad8ba0632fdb4400beb722a cannot be a cause since they were never backported to stable.

Still looking at this, but at least we can rule that out.

**Comment by mvdan** [comment]
I have also written a test to check that the sorting by path works with tricky listen paths in semi-random initial orders, and it passes fine on master.

**Comment by ewah** [comment]
So quickly I've made a gorilla mux script. 

```
package main

import ("fmt"; "net/http"; "github.com/gorilla/mux")

func helloCatchAll(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "hello CatchAll\n") }
func helloRoot(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "hello Root\n") }
func helloHello(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "hello Hello\n") }
func helloWorld(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "hello World\n") }

func main() {
  r := mux.NewRouter()

  // as per api_loader.go:loadApps around line 555
  // concurrency says these can happen at any order
  s1 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/hello-world'
  s2 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/hello'
  s3 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/'

  // as per api_loader.go:loadApps around line 582
  // these proper happen in descending order
  s1.HandleFunc("/hello-world{rest:.*}", helloWorld)
  s2.HandleFunc("/hello{rest:.*}", helloHello)
  s3.HandleFunc("/{rest:.*}", helloRoot)
  r.HandleFunc("/{rest:.*}", helloCatchAll)

  err := http.ListenAndServe(":6000", r)
  print(err)
}
```

sending `GET /hello-world/ HTTP/1.1\nHost: abc.xyz\n\n` returns properly  `hello World`

but because s1, s2, and s3 get created concurrently in api_loader execution can look like. 
```
  s2 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/hello'
  s1 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/hello-world'
  s3 := r.Host("{fqdn:abc.xyz}").Subrouter() // for '/'
```

sending `GET /user-license/ HTTP/1.1\nHost: abc.xyz\n\n` returns incorrectly  `hello Hello`

It seems that the muxer is iterating through an array of matchers (Subrouters and other stuff) in the order created.  (`git/gorilla/mux/route.go`: func (r *Route) Subrouter() *Router {...}`)

**Comment by mvdan** [comment]
@ewah you might be onto something - thanks for helping us debug the issue.

I had been looking at the host matchers before, as I knew they were done in a bit of a weird way. Usually, the host routers would sit at the highest level, meaning that we would have one host route per host and not one per endpoint. It's the same idea that you're proposing with re-using the host routes, but perhaps a bit cleaner and easier to understand.
