### ISSUE TITLE
Disable forwarding auth related data to the upstream

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1273]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

Currently auth related header information is proxied to the upstream.

**What is the expected behavior?**

Auth related headers can be stripped from requests when proxied through the gateway as it presents a possible security issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All versions

**Comment by mvdan** [comment]
I assume this would optional and configurable via either the API definition or the gateway config file.

**Comment by MangoMM** [comment]
I think in API definition it would make sense. `strip_auth: true`, `strip_auth: false`. 

From dashboard perspective, It would be good to have a checkbox option when setting up auth saying `strip auth` with default on. I think that this should be configurable at API level.

**Comment by mvdan** [comment]
I would also do it per-API, I think.

Careful with making the default behavior in 2.x. Still possible to do so as long as it's well documented and for good reason, but in general we can only make breaking changes in 3.0.

**Comment by csbogdan** [comment]
Just wanted to point out that this is in fact a security issue, not exactly a feature request. Stripping auth data from backends calls should’ve been default behavior, and only then adding the option to not remove them could’ve been considered a feature request, on api level.

**Comment by lonelycode** [comment]
@csbogdan What about APIs that make use of OpenID Connect ID tokens, or use JSON Web Tokens? Or SAML envelopes, or APIs that use legacy tokens that are injected into the gateway by the user because their upstream needs them? Or what about OAuth APIs that use an external provider such as Okta or Ping where the identity of the user may need to be interrogated post-hoc?

**Comment by lonelycode** [comment]
Added model support for the new setting to dashboard here, need assistance with FE @lghiur (https://github.com/TykTechnologies/tyk-analytics/tree/strip-auth)

**Comment by buger** [comment]
I created new milestone 2.3.13. It also should include fix for DRL on low rates.
