### ISSUE TITLE
Expose more information on key events

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1274]
## Problem
Some of our customers need more information exposed for key event, e.g. expose more information in the key event emails when a key is **created/deleted/requested/approved**

Currently it's difficult to get this. 

## Solution
Expose more information, such as: Name and email of the key requestor. 

## Information needed
Add which information you would like to be exposed in the comments below. We can then use this to plan the feature further.

**Comment by buger** [comment]
Key request event needs access to the developer object

**Comment by nickReyn** [comment]
http://support.tyk.io/a/tickets/1518
