### ISSUE TITLE
As a user I want to be able to define different rate limits/quotas on different APIs with one policy

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1277]
### Example use case
Let's say we have two different policies: Free and Paid, and two APIs: API1 and API2. At present, the rate limits for API1 and API2 defined in Free and Paid are aggregated. However, what we want to have is as following:

Free: 40 req/min rate limit for API1, 10 req/min rate limit for API2;
Paid: 80 req/min rate limit for API1, 20 req/min rate limit for API2.

**Comment by buger** [comment]
I remember that we already had such request, and I proposed to extend multi-policy approach to merge multiple non partitioned policies too, if they have difference access rules.

**Comment by nickReyn** [comment]
Cool, are you able to link the issues please? Created this for public tracking

**Comment by TimMcCauley** [comment]
Another important reason for this feature is because different endpoints may point to services that consume different levels of resources, computationally speaking. I want to be able to sell different amounts of requests per api endpoint for a specific plan, similarly to [mapzen's rate limits](https://mapzen.com/documentation/overview/rate-limits/).

Free: 2500 requests per day for API1, 1000 requests per day for API2;
Paid: 5000 requests per day for API1, 2000 requests per day for API2;

**Comment by buger** [comment]
@TimMcCauley right, so you probably mean quotas here. If so, yes, quotas will be the part of this issue too.

**Comment by TimMcCauley** [comment]
@buger correct, that's what I mean, thanks.

**Comment by TimMcCauley** [comment]
@nickReyn any thrilling updates for this issue? Thanks

**Comment by buger** [comment]
@TimMcCauley actually yes, this will be part of 2.8 which going to be released in a few weeks from now.

**Comment by TimMcCauley** [comment]
Superb, thanks @buger

**Comment by TimMcCauley** [comment]
@buger just a quick question, do you have an ETA for 2.8 ? Thanks a bunch

**Comment by joshblakeley** [comment]
We are near the end of testing currently so hopefully next week.

**Comment by joshblakeley** [comment]
Happy new year @TimMcCauley I was a little optimistic last time wrt release schedule apologies for that. 
For 2.8 January should happen - i'm just fresh back in the office so i'll check back in this week for you when i know more for certain.

**Comment by TimMcCauley** [comment]
Hey @joshblakeley - please don't kill me for asking but are there any updates by any chance? 🥇

**Comment by joshblakeley** [comment]
Hi Tim!

We are looking at about a month to go for 2.8 i think- we had to rearrange some priorities to get certain features into the release. Sorry I cant be more specific than that and thanks for your patience!

**Comment by TimMcCauley** [comment]
Hey @joshblakeley sorry for asking again ;) we have multiple API services which are ready for release but need this beautiful tyk feature first; to this end: are there any news by any chance? Cheers mate

**Comment by joshblakeley** [comment]
We are past code freeze for 2.8 as of last week so it's all going through QA now.

**Comment by TimMcCauley** [comment]
Josh, thank you.

**Comment by TimMcCauley** [comment]
@joshblakeley one last quick question: are there any docs we can use for this update in order for us to prepare our frontend/dashboard code considering the 2.8 changes (our API dashboard currently reads the historic quota information from the tyk API which I guess will now be "extended" as one policy can have many APIs with different quotas)? Thank you a bunch

**Comment by TimMcCauley** [comment]
Hi again @joshblakeley - any optimistic updates for us?

**Comment by asoorm** [comment]
Closing because implemented & deployed.
