### ISSUE TITLE
Fire AuthFailed event when using custom auth plugins

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1279]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It's not possible to use a custom auth plugin and attach an event listener to the "AuthFailed" event.

**What is the expected behavior?**
It should be possible to trigger this event when using a custom auth plugin.
This scenario doesn't make sense if you're attaching an event handler that's implemented in a plugin, as the plugin already knows about this authentication event. However the user may want to attach `eh_web_hook_handler` or similar (built-in) while using a plugin for authentication.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Create a plugin that implements an authentication mechanism and also an event handler:
```python
from tyk.decorators import *

@Hook
def MyAuthMiddleware(request, session, metadata, spec):
    print("MyAuthMiddleware is called")
    return request, session, metadata

@Event
def MyEventHandler(event, spec):
    print("MyEventHandler is called")
    print(event, spec)
```
- Generate a bundle and configure the API definition to load it and also set an event handler:
```json
{
    "enable_coprocess_auth": true,
    "use_keyless": false,
    "enable_coprocess_auth": true,
    "custom_middleware_bundle": "bundle.zip",
    "event_handlers": {
      "events": {
        "AuthFailure": [
          {
            "handler_name": "cp_dynamic_handler",
            "handler_meta": {
              "name": "MyEventHandler"
            }
          }
        ]
      }
    }
}
```
- When you send a request and the authentication fails, `MyEventHandler` won't be triggered.
- If you change `enable_coprocess_auth` to `false`, `MyEventHandler` will be triggered because the built-in authentication mechanism will be used and `AuthKey` is correctly setup on this one.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master from what I've tested

**Comment by ilijabojanovic** [comment]
@buger @matiasinsaurralde 

ENV: On-prem
Branch: Master

During testing with steps from description i was not able to verify this issue. When i tigger call to api with bundle i see panics in log:

```
[Dec 27 23:55:04] DEBUG coprocess: CoProcess Request, HookType: Pre
2017/12/27 23:55:04 http: panic serving 127.0.0.1:54712: runtime error: invalid memory address or nil pointer dereference
goroutine 10081 [running]:
net/http.(*conn).serve.func1(0xc420694960)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x4934900, 0x5062bd0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.(*CoProcessor).Dispatch(0xc4205fb920, 0xc420a263c0, 0xc420a263c0, 0x2, 0xc420b71aa0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/coprocess_native.go:49 +0xe3
main.(*CoProcessMiddleware).ProcessRequest(0xc420ae5d40, 0x4faf920, 0xc4202e40e0, 0xc42000b300, 0x0, 0x0, 0x1c, 0xc420b97b60, 0x62004b0)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/coprocess.go:246 +0x311
main.createMiddleware.func1.1(0x4faf920, 0xc4202e40e0, 0xc42000b300)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/middleware.go:74 +0x5f9
net/http.HandlerFunc.ServeHTTP(0xc420aca080, 0x4faf920, 0xc4202e40e0, 0xc42000b300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420309540, 0x4faf920, 0xc4202e40e0, 0xc42000b300)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
main.mainHandler.ServeHTTP(0x4faf920, 0xc4202e40e0, 0xc42000b100)
	/Users/ilijabojanovic/work/src/github.com/TykTechnologies/tyk/main.go:1281 +0x4b
main.(*mainHandler).ServeHTTP(0x50aa6f0, 0x4faf920, 0xc4202e40e0, 0xc42000b100)
	<autogenerated>:740 +0x63
net/http.serverHandler.ServeHTTP(0xc42027e0b0, 0x4faf920, 0xc4202e40e0, 0xc42000b100)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420694960, 0x4fb0820, 0xc420a26140)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```
Gateway always reload after this error

**Comment by buger** [comment]
What tags did you used to build gateway?

**Comment by ilijabojanovic** [comment]
@buger 
go build -tags 'coprocess python' && ./tyk --conf=./tyk_local.conf --debug --httpprofile

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic I've been trying to reproduce this with my test bundle, can you share yours?

**Comment by matiasinsaurralde** [comment]
Bump @ilijabojanovic, or is it the same as #1260?

**Comment by ilijabojanovic** [comment]
@matiasinsaurralde Yes i had similar issue as in #1260

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic You can test this again, following the steps we did last time with #1260.
