### ISSUE TITLE
Expose global size limite parameter in Dashboard

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1281]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Set global request size limit is not possible in the dashboard.

**What is the expected behavior?**
A field in the API definition would be nice to set this parameter.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard 2.3.9

Thanks

**Comment by buger** [comment]
Just to clarify, you want to block requests which body size bigger than some value?

**Comment by Pinpin31** [comment]
Yes the same thing that is possible in endpoint designer per path but globally per api. It's actually possible in definition model (json file for gateway) : https://tyk.io/docs/control-limit-traffic/request-size-limits/#max-request-size-with-api
But I didn't find the parameter through the dashboard.
Thanks

**Comment by buger** [comment]
Got it, created internal dashboard issue, and milestoned

**Comment by Pinpin31** [comment]
Great.
Thanks
