### ISSUE TITLE
Add support for TLS redis connections

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1289]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Unable to connect TLS secured ElasticCache

**What is the expected behavior?**
While Redis officially do not support TLS connections and recommends using smth like `spiped` or `stunnel` for implementing secure proxy between server and client, the more and more Redis hostings, including ElasticCach adding support for secure connections. It works by adding proxy on their side which handles TLS termination, and some of the popular clients, including `https://github.com/go-redis/redis`, already support this feature.

**Comment by buger** [comment]
In theory extending current driver to support TLS dialer should be doable, however, needs investigation. However switching to [go-redis](https://github.com/TykTechnologies/tyk/issues/667) sounds cool too, and we are [planning it for a long time](https://github.com/TykTechnologies/tyk/issues/667).

**Comment by bitsofinfo** [comment]
This is definitely an issue for us as well. We'd like to start leveraging Azure's redis offering but are stuck w/ an on premise cluster until this can be made possible

**Comment by joshblakeley** [comment]
Implemented in 2.6

**Comment by paltryeffort** [comment]
Hello,
I tried redis over TLS using tykio/tyk-hybrid-docker:v2.6.2 but I can't get it to work. I couldn't find any special option in the documentation so I just use the standard config:

 ```
 "storage": {
        "type": "redis",
        "host" : "somehost.redis.cache.windows.net",
        "port" : 6380,
        "username": "",
        "database": 0,
        ...
```
When using "log_level": "debug" I get the following:

```
time="Jun 25 14:47:39" level=debug msg="Setting up analytics DB connection" 
time="Jun 25 14:47:39" level=debug msg="Connecting to redis cluster" 
time="Jun 25 14:47:39" level=debug msg="Creating new Redis connection pool" 
time="Jun 25 14:47:39" level=info msg="Connection dropped, reconnecting..." 
time="Jun 25 14:49:05" level=debug msg="Using RPC cache purge" 
time="Jun 25 14:49:05" level=debug msg="Storage Engine already initialised..." 
time="Jun 25 14:49:05" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Jun 25 14:49:05" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Jun 25 14:49:05" level=debug msg="Notifier will not work in hybrid mode" 
time="Jun 25 14:49:05" level=debug msg="Storage Engine already initialised..." 
time="Jun 25 14:49:05" level=debug msg="Storage Engine already initialised..." 
time="Jun 25 14:49:05" level=debug msg="Timeout set to: 10" 
time="Jun 25 14:49:05" level=debug msg="Checking URL: http://cloud.tyk.io/1337/tyk/webhook" 
time="Jun 25 14:49:05" level=info msg="Setting up analytics normaliser" 
time="Jun 25 14:49:05" level=debug msg="Redis log hook active" 
time="Jun 25 14:49:05" level=info msg="PIDFile location set to: ./tyk-gateway.pid" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f9da6]

goroutine 133 [running]:
github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc.(*DispatcherClient).Call(0x0, 0xe96fa1, 0x4, 0x0, 0x0, 0x203a6c6562614c20, 0x206e6769536f5722, 0x230a22616e696843, 0x3a6c616972655320)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc/dispatcher.go:446 +0x26
main.(*RPCPurger).PurgeCache(0xc4202e8fc8)
	/src/github.com/TykTechnologies/tyk/rpc_analytics_purger.go:45 +0x69
main.RPCPurger.PurgeLoop(0x14d9d00, 0xc4202898a0, 0xc42005b0e0)
	/src/github.com/TykTechnologies/tyk/rpc_analytics_purger.go:39 +0x42
created by main.setupGlobals.func2
	/src/github.com/TykTechnologies/tyk/main.go:178 +0xb8
2018/06/25 14:49:05.211275 [INFO] (runner) child process died
2018/06/25 14:49:05.211337 [ERR] (cli) child process died with exit code 2
```

It says "connecting to redis" cluster although it's not a cluster. It hangs about a minute until it prints the rest.

**Comment by asoorm** [comment]
I don't know if above panic message is a red-herring or not... but in your storage config, could you add the `"use_ssl": true` field?

```
"storage": {
       "type": "redis",
       "host" : "somehost.redis.cache.windows.net",
       "port" : 6380,
       "username": "",
       "database": 0,
       "use_ssl": true
}
```
