### ISSUE TITLE
Redirect user to log in screen after session expires in dashboard

### ISSUE THREAD

**Issue by TimMcCauley** [TykTechnologies/tyk#1296]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
After a certain amount of time a session expires of a logged in dashboard user. If the user tries to navigate an error will pop up.

**What is the expected behavior?**
While this being the expected behaviour (expiry of a session), it would be handy if the dashboard automatically directs the user back to the login screen, after the session expires. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Any

**Comment by ConsM** [comment]
Hi Tim, thanks for your suggestion.
There's already a fix for this and will be included in the next (2.4) release.

**Comment by buger** [comment]
This is already implemented in upcoming 2.4, which going to be released at the start of the next week. 👍

**Comment by TimMcCauley** [comment]
👍  perfect and extremely handy. Thanks @ConsM @buger
