### ISSUE TITLE
If beginning of a random path of api call matches an existing slug we return 403 (instead of 404.)

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1297]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`http://my-instance.com:8080/api1 works`, but
`http://my-tyk-instance.com:8080/api1ss` (i.e. adding some letters at the end of the slug) generates  **403 forbidden** while putting some string right after the hostname `http://my-tyk-instance.com:8080/ss` just gives `404 page not found`
**What is the expected behavior?**
http://my-tyk-instance.com:8080/api1ss ==> should return 404

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. create api
2. make a call to it, check it's fine
3. make a call with some extra chars at the end.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3

**Comment by mvdan** [comment]
I cannot reproduce this. Before the API is created, both without and with extra chars are 404. After the API is created, both are 200.

I even added tests for this, which pass:

```
diff --git a/gateway_test.go b/gateway_test.go
index 752269da..7fe4162d 100644
--- a/gateway_test.go
+++ b/gateway_test.go
@@ -919,8 +919,10 @@ func TestListener(t *testing.T) {
 		{method: "POST", path: "/tyk/apis", body: sampleAPI, adminAuth: true, code: 200},
 		// API definitions not reloaded yet
 		{method: "GET", path: "/sample", code: 404},
+		{method: "GET", path: "/samplefoo", code: 404},
 		{method: "GET", path: "/tyk/reload/?block=true", adminAuth: true, code: 200},
 		{method: "GET", path: "/sample", code: 200},
+		{method: "GET", path: "/samplefoo", code: 200},
 	}
 
 	// have all needed reload ticks ready
```

Please provide an API definition and the `curl` commands to reproduce it. Does it reproduce when the API is keyless?

**Comment by letzya** [comment]
Happens only with this api, will check again.

**Comment by asoorm** [comment]
I cannot reproduce:

Correct
```
$ curl -X GET https://ahmet-1.cloud.tyk.io/api1/ -I
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Date: Mon, 20 Nov 2017 16:13:43 GMT
Content-Length: 46
Connection: keep-alive
```

Not found for all other combinations:
```
$ curl -X GET https://ahmet-1.cloud.tyk.io/api1ss -I
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Nov 2017 16:13:31 GMT
X-Content-Type-Options: nosniff
Content-Length: 19
Connection: keep-alive
```

```
ahmet@Ahmets-MBP ~ $ curl -X GET https://ahmet-1.cloud.tyk.io/api1 -I
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Nov 2017 16:13:36 GMT
X-Content-Type-Options: nosniff
Content-Length: 19
Connection: keep-alive
```

```
$ curl -X GET https://ahmet-1.cloud.tyk.io/api1ss/ -I
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Nov 2017 16:13:48 GMT
X-Content-Type-Options: nosniff
Content-Length: 19
Connection: keep-alive
```

**Comment by letzya** [comment]
Ahmet, Dan has already checked it and I replied 2 hours ago that it happens only with a specific api i.e. I will check again.

**Comment by letzya** [comment]
Can't reproduce but it is happening on one of my apis. Maybe tomorrow we can have a look together?

**Comment by letzya** [comment]
@mvdan I think it's because I named my api as 'api2'.

**Comment by mvdan** [comment]
The problem was that the request was going to a different API, thus the 403.
