### ISSUE TITLE
hash key make collide

### ISSUE THREAD

**Issue by jacyo** [TykTechnologies/tyk#1309]
func doHash(in string) string {
	h := murmur3.New32()
	h.Write([]byte(in))
	return hex.EncodeToString(h.Sum(nil))
}

func main() {
	fmt.Println(doHash("defaultf1bfc265b48841f1b1dcdc26cd39eadf"))
	fmt.Println(doHash("defaultf1bfc265b48841f1b1dcdc26cd39eade"))
}

Output:
319d3ab3
319d3ab3

**Comment by jacyo** [comment]
github.com/spaolacci/murmur3
The package need to be updated.

**Comment by mvdan** [comment]
@jacyo what is the commit that you think fixed this issue?

**Comment by buger** [comment]
If there is a way to fix murmur hash and keep compatibility with old keys, let's try to do it.

In general, I would say that we need to make hash function configurable like this https://github.com/TykTechnologies/tyk/issues/509. Keep old behavior default, and introduce fixed one under new value.

**Comment by jacyo** [comment]
It's difficult to keep compatibility with old keys.
