### ISSUE TITLE
Provide authentication for registred user with admin API SSO  

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1310]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The Admin API SSO contains two endpoint  : 
* /admin/sso to generate temporary authentication token
* /tap?nonce= to login on dashboard with default SSO permission 

**What is the expected behavior?**
It would be nice to match the authentication token with registred user in dashboard and to set permission access with registred user.

The body for endpoint "/admin/sso" would be :
{
        "ForSection": "dashboard",
        "OrgID": "588b4f0bb275ff0001cc7471",
        "login": "sylvain.perrinel@****"
}
And the nonce generate would be attach to the user sylvain.perrinel (if registred in dashboard) with permissions setted in Dashboard.
Then the endpoint  "/tap?nonce=" would login the user attached to the nonce.

With this feature, TIB will authenticate registred user with SSO.
Thanks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard 1.4.0

**Comment by buger** [comment]
Like it! I think it also make sense add dashboard option, to allow SSO login only for registered users.

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk-analytics/pull/982 was merged to `release-1.7` branch
<details><summary></summary>Created via API</details>

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk-analytics/pull/982 was merged to `release-1.8` branch
<details><summary></summary>Created via API</details>
