### ISSUE TITLE
Allow global url rewrite for an api

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1311]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
To globally rewrite an url for an api, you need to configure for each endpoint :
![capture du 2017-11-23 17-52-45](https://user-images.githubusercontent.com/1773969/33183234-5152d8a2-d077-11e7-8e2b-63370edce083.png)
For this example, I need to provide a token in parameter of the url for each endpoint.

**What is the expected behavior?**
It would be nice to have a global url rewrite for the API in endpoint designer.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard 1.4.0

**Comment by andyo-tyk** [comment]
I'm closing this as "won't do" - we are investigating ways to manage this sort of problem as part of a wider piece of work, so I've logged this internally, however at this stage we don't have a plan to implement a Global URL rewrite.

If this changes then I will update this issue.
