### ISSUE TITLE
If key is attached to a policy, then in dashboard reflect this by disabling the fields that policy has priority over.

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1315]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behaviour?**

When a key is attached to a policy, it's rate limits/quotas etc will currently override that key. In the dashboard UI the key values can still be changed in the editing fields even though this will not have any affect while still attached to the policy.

**What is the expected behaviour?**

Some possible approaches:

- If key is attached to a policy, then in dashboard UI  disabling the fields that policy has priority over.
- Overwrite the key values with the attached policy values in the UI.
- Same as first approach and also display somewhere the attached policies values for reference.

**Comment by buger** [comment]
@ConsM would you like to take a look? I prefer approach 1).

**Comment by ConsM** [comment]
@buger sure
@nickReyn any suggestions from your perspective ?

**Comment by lghiur** [comment]
@buger what's the release number we would like this for? 1.5?

**Comment by buger** [comment]
This is a small task and good for @ConsM, so yeah 1.5

**Comment by nickReyn** [comment]
Sounds good. I prefer option 3, because if we are disabling fields, we need to tell the user why.
A line of text under the field like **"This value is being overwritten by the (Policy name here) policy"** could suffice?

**Comment by nickReyn** [comment]
Or if that's too complex, **"This value is being overwritten by an attached policy"** ?

**Comment by letzya** [comment]
@buger doesn't that make this [ticket unnecessary ](https://github.com/TykTechnologies/product/issues/32)?

**Comment by buger** [comment]
Your ticket is about API behavior, it is a bit different.

**Comment by letzya** [comment]
It's from the same source and meeting and what they want is to see what are the rate limits and quotas of a certain key. That ticket is another related aspect.  The fact is that they want the key to get updated **after** a policy gets **changed**. If updating a policy would be reflected in the key (during policy update) or needs to be triggered with a click of a button it doesn't matter but it would  allow for this ticket to show the correct information in case we will show the policy's values on the key's page.

**Comment by lonelycode** [comment]
@letzya Your ticket is related, but not the same as this. This ticket is to inform the user that the rate limits and the quota in the UI *cannot be edited* because they are bein set by a policy, this means this is an aesthetic change.

The issue you reference is a functional one, it requires the policy to applied to the token at the time of reading so that the token is always in line with what is stated in it's linked policy. Basically we can have both, and they do not interact.

**Comment by lonelycode** [comment]
I propose we go with Option 3 here, for closure :-)

**Comment by nickReyn** [comment]
@lghiur what do you think of:

> Sounds good. I prefer option 3, because if we are disabling fields, we need to tell the user why.
> A line of text under the field like "This value is being overwritten by the (Policy name here) policy" could suffice?

**Comment by lghiur** [comment]
@nickReyn what do you think about this?
![screencapture-localhost-9000-1512637075654](https://user-images.githubusercontent.com/6229829/33706707-e19a7c84-db2c-11e7-86e7-c3c78c553fed.png)

**Comment by nickReyn** [comment]
Looks good dude. As discussed offline, just to make the fields look a bit more obvious they are disabled. E.g. make the text in them grey or smth

**Comment by ilijabojanovic** [comment]
During test this change i found few issues:
When we create key and attach that key to old policy (e.g created on 1.4.X or 1.3.X) all sections are locked for editing other words they are enforced by default.
If we create new policy and after that try to attach new key to new policy everything looking good.

Here is video:
https://screencast.com/t/pSjDbFLoANf

Note: QA is new policy, novapolisa is old policy

**Comment by ilijabojanovic** [comment]
Verified
