### ISSUE TITLE
tyk-python process does not suppport python 3.5

### ISSUE THREAD

**Issue by rahogata** [TykTechnologies/tyk#1324]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
tyk python process not starting if python 3.5 is installed in Ubuntu 16.04 LTS.

**What is the expected behavior?**
tyk python process should start and support python 3.5.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1) Install python 3.5
2) Make sure python command linked to python3.5 binary.
3) Install tyk in Ubuntu 16.04 LTS as per the documentation.
4) Install libpython3.5, protobuf.
5) start tyk-python service.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I used Tyk 2.4.0

**Comment by excieve** [comment]
Thanks for your report @shiva2991. The packaged binaries are currently built against Python 3.4, which may be binary incompatible with 3.5. There are currently three options around it:
 1) using our docker images, which come with vetted components
 2) installing Python 3.4, along with `protobuf` and `grpcio` using pip for this distribution
 3) compiling Tyk gateway from sources against 3.5

We're also working on a better support for various versions of Python in #1283.
