### ISSUE TITLE
Python plugin enhancements

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1335]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Currently we experience difference issues when using Python plugins:
- The plugins are currently loaded as Python modules in the standard way and the global namespace is shared by all of them, this causes some issues when a user needs to use different plugins for different APIs using similar names.
- Relative imports are affected by the global namespace issue as well.
- Adding bundle paths to the `PYTHONPATH` makes it harder to isolate the plugins in this way.

I'm working on #1260, which is a refactor of the Python code that we use to handle the plugins.
It also includes a few Go code tweaks and we expect to cover all this logic in #1321:
- Namespace the Python modules that are part of a plugin bundle internally.
- Implement our own loader based on `importlib` which it's the standard mechanism for `import`-related customizations.
- Simplify the dispatcher logic.
- Avoid using `PYTHONPATH` because it uses the global namespace (`sys.modules`).
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by lonelycode** [comment]
We need to make sure we document this extremely carefully.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Python plugin enhancements](https://trello.com/c/WAOdDDdS/507-python-plugin-enhancements)
