### ISSUE TITLE
Dashboard users can't change their own passwords, if they don't have "Users write" rights set

### ISSUE THREAD

**Issue by antizol** [TykTechnologies/tyk#1349]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Dashboard users can't change their own passwords, if they don't have "Users write" rights set.

**What is the expected behavior?**
Users should be able to re-set their password even if they don't have rights to add new users.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
 - create a new user in the dashboard without administrative priviledges, and without users write access
 - the newly created user can't change their password upon logging in

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4

**Comment by ilijabojanovic** [comment]
Verified @buger please merge in to release-1.7 branch
