### ISSUE TITLE
Cannot set a portal domain name with more than 2 dots

### ISSUE THREAD

**Issue by gfouquet** [TykTechnologies/tyk#1355]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Tyk dashboard refuses to set a portail domain name with more than 2 dots from the GUI eg. "portal.dev.mydomain.org"

**What is the expected behavior?**
Tyk dashboard accepts portail domain names with more than 2 dots

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Working scenario :
1. Log into the dashboard as an admin
1. Click Your developer portal > Set your portal domain
1. Input "portal.mydomain.org"

-> A dialog with "CNAME Updated" pops up and portal domain name is updated

Non-working scenario : 
1. Log into the dashboard as an admin
1. Click Your developer portal > Set your portal domain
1. Input "portal.dev.mydomain.org"

-> A dialog with "There was a problem updating your CNAME, please contact support" pops up and portal domain name is not updated

When updating the portail name directly in mongodb, it works correctly ("cname" prop of the "tyk_organisations" collection)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.4.1 and previous versions are affected

**Comment by buger** [comment]
Thank you for reporting, will try to fix in following bugfix releases.
