### ISSUE TITLE
 Slug property of Portal page is overwritten upon editing 

### ISSUE THREAD

**Issue by gfouquet** [TykTechnologies/tyk#1358]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When you edit a portal page, the slug property is automatically overwritten with the title property

**What is the expected behavior?**
The slug property stays as it was originally input

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Log into the dashboard as an admin
2. Open Portal Management > Pages
3. Click Add page
4. Fill form with these props :
* title : Test page (the slug field automatically fills with "test-page")
* slug : test
* type : default page template
5. Click create
6. In page list, click Edit for Test page

-> the "slug" property gets overwritten with "test-page" without warning. If you happen to click Save, the previous value is lost

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.4.1, I don't know for previous ones

**Comment by buger** [comment]
Thank you! We will investigate.

**Comment by ConsM** [comment]
@gfouquet confirmed, fix will be part of the next major release (v1.5)

**Comment by ilijabojanovic** [comment]
Verified
