### ISSUE TITLE
Global cache ignores enabled url-rewrite on endpoint

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1359]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When global cache is enabled on api definition, global cache ignores url-rewrite feature on endpoint
**What is the expected behavior?**
When we have global cache enabled, url rewrite should work.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api definition 
2. Enable global cache on advanced tab
3. Add url rewrite plugin for some endpoint 
4. Trigger call to endpoint with url rewrite enabled
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4.X

**Comment by buger** [comment]
False alarm
