### ISSUE TITLE
key getting deleted automatically

### ISSUE THREAD

**Issue by tandonraghav** [TykTechnologies/tyk#136]
This is something weird which is happening as key is getting deleted automatically and i am not able to see the key in the dashboard and not able to access also.
This is my request to create a key:-
{
  "allowance": 999,
  "rate": 1000,
  "per": 60,
  "expires": 0,
  "quota_max": -1,
  "quota_renews": -1,
  "quota_remaining": 0,
  "quota_renewal_rate": 0,
  "access_rights": {
    "41d73ffbd3e641d15d5da26810572271": {
      "api_name": "api",
      "api_id": "41d73ffbd3e641d15d5da26810572271",
      "versions": [
        "v1"
      ],
      "allowed_urls": [
        {
          "methods": ["POST"],
          "url": "/v1/****"
        },
        {
          "methods": ["POST"],
          "url": "/users/login"
        }
      ]
    }
  },
  "org_id": ""
}

Am i doing something wrong here? what are the possible scenarios where this cam happen?

**Comment by lonelycode** [comment]
Yeah you've set expire to 0 which means it will expire almost instantly. Use -1 for never expire, otherwise set a value.

**Comment by tandonraghav** [comment]
But it is not expiring instantly and expiring after a day. Even in dashboard I can see Expires:Never (--).
What does this mean then?

**Comment by lonelycode** [comment]
So they key actually works for 24 hours? As in, you can use it?

**Comment by tandonraghav** [comment]
yes i am able to use it for a day, but then it gets deleted suddenly.

**Comment by lonelycode** [comment]
Hmmm, that is a little odd - so the reason dashboard is saying never is because it can't match your value to one of the presets (or it might just be a select bug, I think it's having trouble converting the value to a date)

The expiry is meant to be an epoch value, so if it's 0 the key is expired (sometime in 1970), so it's weird that you can use it.

However Tyk does not delete keys instantly, it expires then first (returns an error to the user) but then drops they key from memory some time after. Just in case you want to edit or change the key. 

Which explains while it exists for a day... Although it should be expired in software terms, not existence terms. Try setting -1, or a UNIX epoch value in the future.

**Comment by tandonraghav** [comment]
ok...i will set to -1 and then let you know if still the issue persists.

**Comment by tandonraghav** [comment]
Hey,
This is so frustating now, happening on a consistent basis, my keys are
getting purged after certain time.
How can i debug this issue. Please help as i am very close to release.

The request for key creation is:-

{
    "allowance": 999,
    "rate": 1000,
    "per": 60,
    "expires": -1,
    "quota_max": -1,
    "quota_renews": -1,
    "quota_remaining": 0,
    "quota_renewal_rate": 0,
    "access_rights": {
        "41d73ffbd3e641d15d5da26810572271": {
            "api_name": "charge_api",
            "api_id": "41d73ffbd3e641d15d5da26810572271",
   "versions": ["v1"]

        }
    },
    "org_id": ""
}

Is there some purge setting in redis/mongo which is creating this issue?

**Comment by lonelycode** [comment]
Are you restarting redis?

**Comment by tandonraghav** [comment]
No. I didnt restarted, but why that will be an issue?
Please let me know if u need any other config.

**Comment by lonelycode** [comment]
In your API definition have you set "session_lifetime" to anything other than 0?

**Comment by tandonraghav** [comment]
this is what is my api_def in mongo:-

{ "_id" : ObjectId("564a47fac871bb49a5000001"), "name" : "charge_api",
"slug" : "charge_api", "api_id" : "41d73ffbd3e641d15d5da26810572271",
"org_id" : "", "use_keyless" : false, "use_oauth2" : false, "oauth_meta" :
{ "allowed_access_types" : [ ], "allowed_authorize_types" : [ ],
"auth_login_redirect" : "" }, "auth" : { "use_param" : false, "use_cookie"
: false, "auth_header_name" : "key" }, "use_basic_auth" : false,
"notifications" : { "shared_secret" : "", "oauth_on_keychange_url" : "" },
"enable_signature_checking" : false, "hmac_allowed_clock_skew" : -1,
"definition" : { "location" : "url", "key" : "x-api-version" },
"version_data" : { "not_versioned" : false, "versions" : { "djI=" : {
"name" : "djI=", "expires" : "", "paths" : { "ignored" : [ ], "white_list"
: [ ], "black_list" : [ ] }, "use_extended_paths" : true, "extended_paths"
: { "ignored" : [ ], "white_list" : [ ], "black_list" : [ ], "cache" : [ ],
"transform" : [ ], "transform_response" : [ ], "transform_headers" : [ ],
"transform_response_headers" : [ ], "hard_timeouts" : [ ],
"circuit_breakers" : [ ], "url_rewrites" : [ ], "virtual" : [ ] } }, "djE="
: { "name" : "djE=", "expires" : "", "paths" : { "ignored" : [ ],
"white_list" : [ ], "black_list" : [ ] }, "use_extended_paths" : true,
"extended_paths" : { "ignored" : [ ], "white_list" : [ ], "black_list" : [
], "cache" : [ ], "transform" : [ ], "transform_response" : [ ],
"transform_headers" : [ ], "transform_response_headers" : [ ],
"hard_timeouts" : [ ], "circuit_breakers" : [ ], "url_rewrites" : [ ],
"virtual" : [ ] } } } }, "proxy" : { "listen_path" : "/charge_api/",
"target_url" : "http://localhost:8091/charge_api", "strip_listen_path" :
true, "enable_load_balancing" : false, "target_list" : [ ],
"service_discovery" : { "use_discovery_service" : false, "query_endpoint" :
"", "use_nested_query" : false, "parent_data_path" : "", "data_path" :
"hostname", "port_data_path" : "port", "use_target_list" : false,
"cache_timeout" : NumberLong(60), "endpoint_returns_list" : false } },
"custom_middleware" : { "pre" : [ ], "post" : [ ], "response" : [ ] },
"cache_options" : { "cache_timeout" : NumberLong(60), "enable_cache" :
false, "cache_all_safe_requests" : false, "enable_upstream_cache_control" :
false }, "session_lifetime" : NumberLong(0), "active" : true,
"auth_provider" : { "name" : "", "storage_engine" : "", "meta" : {  } },
"session_provider" : { "name" : "", "storage_engine" : "", "meta" : null },
"event_handlers" : { "events" : {  } }, "enable_batch_request_support" :
false, "enable_ip_whitelisting" : false, "allowed_ips" : [ ],
"dont_set_quota_on_create" : false, "expire_analytics_after" :
NumberLong(0), "response_processors" : [ ], "CORS" : { "enable" : false,
"allowed_origins" : [ ], "allowed_methods" : [ ], "allowed_headers" : [ ],
"exposed_headers" : [ ], "allow_credentials" : false, "max_age" : 24,
"options_passthrough" : false, "debug" : false }, "tags" : [ ],
"hook_references" : [ ] }

My API's are not deleted and they are still in ACTIVE state.
Is that to do something with Redis eviction policy/purge?

**Comment by tandonraghav** [comment]
Does that definition looks good to you?
Also , I can create keys by both PUT/POST request, I hope that is not
causing the issue.

**Comment by lonelycode** [comment]
Well, if you were restarting redis - you might have been losing data on the restart unless you explicitly save the data

If you had session lifetime set to larger than 0, then the session cache would expire all keys after x seconds, but it's 0 in your conf, so that's not it.

You've set the expire on the key to -1, so that will stop it from dropping the key after a forced expiry (in fact I don't think it drops them at all).

When you POST it creates a key using your custom key name, if you PUT it updates a key (under the hood it's the same SET operation).

Lets take a look at your tyk.conf file.

Also, how have you set up redis?

**Comment by tandonraghav** [comment]
Sure,
Tyk.conf

{
  "listen_port": ****,
  "secret": "XXXX",
  "template_path": "/etc/tyk/templates",
  "tyk_js_path": "/etc/tyk/js/tyk.js",
  "use_db_app_configs": true,
  "app_path": "/etc/tyk/apps",
  "middleware_path": "/etc/tyk/middleware",
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 6379,
    "username": "***",
    "password": "***",
    "database": 0,
    "optimisation_max_idle": 500
  },
  "enable_analytics": true,
  "analytics_config": {
        "type": "mongo",
        "csv_dir": "/tmp",
        "mongo_url": "mongodb://localhost/tyk_analytics",
        "mongo_db_name": "tyk_analytics",
        "mongo_collection": "tyk_analytics",
        "purge_delay": 10
},
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "mongo",
    "policy_record_name": "tyk_policies"
    },
  "hash_keys": false,
  "suppress_redis_signal_reload": false
}

I am new to redis so I just went with default settings.
Do I need to do something to make it persistent for life time?

**Comment by lonelycode** [comment]
Potentially - by default Redis will lose everything stored in it if the process restarts. 
To make it persistent you need to set the appendonly option in the conf file (Google it) - though this could adversely affect disk space on the instance, so it needs to be managed.
Alternatively you need an active backup so it never goes down (master slave).
Though you did say that the instance or process isn't restarting... So it shouldn't be that.
I'm assuming you just installed Redis on a box somewhere and left the defaults? Can you tell me more about the Redis setup?

**Comment by tandonraghav** [comment]
Right i just went with the default settings, its better i go through redis.
But what exactly you are looking in redis setup? Its all default configs.

**Comment by lonelycode** [comment]
This is the topic you want:
http://redis.io/topics/persistence

**Comment by tandonraghav** [comment]
Thanks fr ur time...will go through that...

**Comment by tandonraghav** [comment]
This is resolved, just some redis config.

**Comment by senj** [comment]
@tandonraghav can you explaine a bit what you changed please?

**Comment by tandonraghav** [comment]
No that was actually the redis eviction policy...making it persistent made
it work...now the keys wont get deleted...

**Comment by talibsiddique** [comment]
@tandonraghav  what exactly you did to resolve this  issue, I am also facing the same issue even if setting keys PERSIS or EXPIRY for 100yrs it get deleted automatically after some time.

**Comment by pragatisharma23** [comment]
hey @tandonraghav,
please help me out for the same I'm also facing the same issue . my redis data is clearing after some time. what exact changes did you make to resolve this issue. i have need to solve it asap because I'm near about to deliver the project. and not able to why is this happening

**Comment by vinhql** [comment]
I also have the same problem. I spent a lot of time searching. If anyone has a solution, please share it with me

**Comment by pclokcer** [comment]
you can look this 
https://redis.io/docs/reference/eviction/
