### ISSUE TITLE
Batch Requests do not work when listen path is /

### ISSUE THREAD

**Issue by ryoung-mbo** [TykTechnologies/tyk#1364]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Our organization has a custom domain for one of our APIs with the listen path set to `/`. We would like to use the batch requests feature for this API.
When the listen path is set to `/`, the Batch Request feature does not work.

**What is the expected behavior?**
Even with a listen patch set to `/` the batch request feature should work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Follow the [example](https://tyk.io/docs/tyk-rest-api/batch-requests/) for the documentation with batch requests. 

> **NOTE**  The documentation says the path is `/tyk/batch`. It's actually `/tky/batch/`.

For a positive test, set the **Listen path** to `/httpbin/` and make `/tyk/batch/` POST *a la* the example. It should work.
Now set the **Listen path** to `/` and the same request no longer works. It says `403 - Forbidden` even though the other end-points (`/get`) work consistently. I've tried this with and without a custom domain and it behaves the same way.

Error in the logs:
> time="Dec 17 05:12:41" level=warning msg="Attempted administrative access with invalid or missing key!" 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4.2
I don't believe this has worked in previous versions.

**Comment by buger** [comment]
Thank you for the report.

It happens because "/tyk/*" endpoints reserved for control API, and this routes loaded on Tyk start https://github.com/TykTechnologies/tyk/blob/827003094c4212e7a2354c14d1f9161f74119437/main.go#L356-L359

Not sure what is the best way to fix this edge case. I would propose you to move Control API to a separate domain or separate port to solve the issue using `control_api_hostname` or `control_api_port`.

**Comment by ryoung-mbo** [comment]
I figured it was an edge case. We do have other work-arounds (specifically, we set up a different API definition just for our one app to use batch) but I didn't know about the one you suggested. We'll look into it!

I was going to suggest that the code above could include a check for a custom domain before assuming it's a control API.
