### ISSUE TITLE
Enabled detail_recording cannot display the results for non-200 requests, eg. 403

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1365]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Currently can only show the 200 response.
**What is the expected behavior?**
Capture also the non-200 requests, like 403. Cuz it will help me debug what is going wrong, key error? or sth.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
latest

**Comment by buger** [comment]
May I wonder why you closed it?
