### ISSUE TITLE
Block dashboard languages api to only read language files

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1369]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The API to get languages can read all json files of dashboard installation :
https://apidashboard-usager-pprd.national.argi/api/language?lang=../../../opt/tyk-dashboard/schemas/tyk_config
It's a security vulnerability : Local File Inclusion.
I try to read a json file on the server to get an admin password or anything else but it appears to be blocked :
https://apidashboard-orion.national.agri/api/language?lang=../../../opt/tyk-identity-broker/profiles

**What is the expected behavior?**
The API to get languages must filter on directory lang of the dashboard installation or use the configuration of the dashboard to only authorize the configured language file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk dashboard 2.4.2

**Comment by buger** [comment]
Ouch! Definitely, a serious issue will try to fix in next patch release.

**Comment by buger** [comment]
@joshblakeley ^

**Comment by joshblakeley** [comment]
Will get a fix pushed
