### ISSUE TITLE
Tyk not responding with CORS headers only for HTTP Options request

### ISSUE THREAD

**Issue by mnv104** [TykTechnologies/tyk#137]
Hello,
I am a newbie to this forum and not sure if I am posting at the right place. Apologies if I missed something.
I have looked at previous posts and tried following some of the suggestions to no avail and hence the need to raise this issue.

I have setup a new tyk API end point to take care of an upstream app's middleware needs (authentication etc). The tyk end point works perfectly via curl.
However, I need it to work from Javascript and this is where my CORS troubles started.
I have enabled CORS support in tyk since the upstream app does not take care of that.
When I do a HTTP options request, I see that tyk does not respond back with the header that the browsers wants/expects but when I do a HTTP get request, tyk does respond correctly. What am I doing wrong?

curl --include -X OPTIONS  --header "origin: http://localhost" --header "authorization:5655163c1dc22b0001000001c1c5915e754e434662d370c341dcbe92" "http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1"  
HTTP/1.1 200 OK
Date: Mon, 30 Nov 2015 23:44:50 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers

<----- This is the error on javascript console
XMLHttpRequest cannot load http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.

As can be seen in the curl response, I don't see the Access-Control-Allow-Origin header.

When doing a http get request, curl does show the right headers

curl --include -X GET  --header "origin: http://localhost" --header "authorization:5655163c1dc22b0001000001c1c5915e754e434662d370c341dcbe92" "http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1"  
HTTP/1.1 200 OK
Date: Mon, 30 Nov 2015 23:49:37 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost <--- It is present here..
Vary: Origin
X-Ratelimit-Limit: -1
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1448417629
X-Tyk-Cached-Response: 1

I am attaching the screenshot of the CORS setup/advanced settings page...
![1](https://cloud.githubusercontent.com/assets/2385067/11488381/edd25c12-977a-11e5-8261-e3c257d8d984.png)

**Comment by lonelycode** [comment]
I don't think you need to make the CORS headers allowed, Tyk handles that for you.

Also, you don't need to allow OPTIONS as that is part of the CORS standard, Tyk will respond appropriately to a preflight from a browser, allowing OPTIONS could be doing something weird like making it try to pass through.

Lastly, a preflight request from a browser will strip out Authorization headers according to the spec, so you don't need to send them.

What you need to look at is the actual OPTIONS request in your browser (not the console) to see what is coming back - check the network tab to see what Tyk is responding with to the OPTIONS request that the browser sends pre-flight.

You also seem to have a very aggressive cache enabled (all safe requests - this includes options) I would disable that (though it shouldn't affect things - I can see your second GET is returning cached responses), but the CORS middleware should just be responding and not passing through.

You could try a more verbose and specific options test to get more data:

curl -H "Origin: http://example.com" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS --verbose \
"http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1"

Again, would be good to see what the browser is doing.

**Comment by mnv104** [comment]
Thanks for the reply. Much appreciated. Right now, I am just playing around with basic things before deploying this in production. I will tone down some of the aggressive defaults in production.

This is the output from the curl command you requested,

curl -H "Origin: http://example.com" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS --verbose "http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to testorg.tyk.docker (127.0.0.1) port 8888 (#0)
> OPTIONS /aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: testorg.tyk.docker:8888
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 200 OK
< Date: Tue, 01 Dec 2015 01:11:03 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< 
* Connection #0 to host testorg.tyk.docker left intact

I don't see the Access-Control-Allow-Origin header that the browser is expecting in the response as part of the OPTIONS request..... The response header above matches with what I see in the browser as well.

and I am also attaching the browser network and console tab output.

![screenshot from 2015-11-30 17 14 13](https://cloud.githubusercontent.com/assets/2385067/11489646/0458d564-9786-11e5-8212-48f055c3c4ba.png)
![screenshot from 2015-11-30 17 15 29](https://cloud.githubusercontent.com/assets/2385067/11489647/045abd20-9786-11e5-8205-ec229c299321.png)

This is the basic html code that drives the ajax request

<!DOCTYPE html>
<html>

<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.js"></script>

<script>

$( document ).ready(function() {

  var request = $.ajax({
		    url: "http://testorg.tyk.docker:8888/aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1",
		    headers: {"authorization": "5655163c1dc22b0001000001c1c5915e754e434662d370c341dcbe92"},
		    }).done(function( data ) {
			console.log("done");
		    }).fail( function(xhr, textStatus, errorThrown) {
			alert(xhr.responseText);
			alert(textStatus);
		    }); 
});
		       
</script>
</head>


<body>
</body>
</html>

Please let me know if I missed something basic here.
thanks again for the guidance!
Murali

**Comment by mnv104** [comment]
The curl output in my previous post appears to be misformatted,

Hostname was NOT found in DNS cache
Trying 127.0.0.1...
 Connected to testorg.tyk.docker (127.0.0.1) port 8888 (#0)
 OPTIONS /aolCourseSearch/?jsonIndent=1&type=search&ctype=12415&lat=12.79&long=77.51&center_list=1 HTTP/1.1
 User-Agent: curl/7.38.0
 Host: testorg.tyk.docker:8888
 Accept: */*
 Origin: http://example.com
 Access-Control-Request-Method: POST
 Access-Control-Request-Headers: X-Requested-With
 
 HTTP/1.1 200 OK
 Date: Tue, 01 Dec 2015 01:25:10 GMT
 Content-Type: text/plain; charset=utf-8
 Content-Length: 0
 Connection: keep-alive
 Vary: Origin
 Vary: Access-Control-Request-Method
 Vary: Access-Control-Request-Headers
 
 Connection #0 to host testorg.tyk.docker left intact

**Comment by lonelycode** [comment]
Ok that's a bit odd. Did you remove the allowed headers  values and switch the caching off?

**Comment by lonelycode** [comment]
Also please post your JS so we can replicate

**Comment by lonelycode** [comment]
One idea: Remove the authorised headers you have there - the browser is asking if the 'accept' and 'Authorization' headers are allowed in its request, this will fail since they are not according to your config so add these in and remove the CORS ones.

Also, maybe disable allow credentials

**Comment by wen96** [comment]
I had exactly the same issue and adding 'Accept' and 'Authorization' headers in CORS config solve it. 
Thanks Martin.
