### ISSUE TITLE
OAuth: Is it possible to get tokens without using the basic auth on client_credentials

### ISSUE THREAD

**Issue by lopssh** [TykTechnologies/tyk#1373]
hi, 

i'm working with tyk's oauth2, after my reading on the [(Almost) Definitive Guide to OAuth with Tyk](https://docs.google.com/document/d/17Eon4K1QQ6-2xl0BXft2k8WYsL7KJkS2duCYje88WVA/pub), i can work very well with the client_credentials method now. 
but i hope to do to obtain an access_token without the basic authroization header (Because client_id and client_secret are repeated with some of the text provided in the querystring), and to get tokens just provision client_id and client_secret like `&grant_type=client_credentials&client_id=[id]&client_secret=[secret]` without any other things.
what should i do can do for this?

sorry for my poor english..

**Comment by lopssh** [comment]
Is the basic auth header necessary?

**Comment by buger** [comment]
@lopssh have you closed it because the issue is solved?

**Comment by LOpSSH** [comment]
> @LOpSSH have you closed it because the issue is solved?

Ya, I've solved this problem but forgot how this problem was solved...

**Comment by lolleko** [comment]
Sorry for reviving this issue after 4 years:

But I would also like to know if it is possible to use client_credentials verification without the Authorization header. The docs (https://tyk.io/docs/basic-config-and-security/security/authentication--authorization/oauth2-0/client-credentials-grant/) are not clear on this.

For example, this curl request works (returns a token):

```
curl --location 'abc.com/oauth/token' --header 'Content-Type: application/x-www-form-urlencoded' --header 'Authorization: Basic JHM2QmhkUmtxdDNAOiQ3RmpmcDBaQnIxS3REUmJuZlZkbUl3QA'  --data-urlencode 'grant_type=client_credentials' 
```

while this one doesn't:

```
curl --location 'abc.com/oauth/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'client_id=$s6BhdRkqt3@' --data-urlencode 'client_secret=$7Fjfp0ZBr1KtDRbnfVdmIw@'
```

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}
```
