### ISSUE TITLE
Unrequested URL Encoding while proxying

### ISSUE THREAD

**Issue by paolo-rodeghiero** [TykTechnologies/tyk#1374]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When asking an URL that contains parenthesis, which are used by some proprietary backends like SFCC to define arrays of parameters, they get converted to URL encoded characters like %28 and %29 and therefore get interpreted as a single value

e.g.

  GET http://gateway/promotions/(Test_GWP,Test_GWP)   --->  http://upstream/promotions/ %28Test_GWP,Test_GWP%29

Response: promotion id "(Test_GWA,Test_GWB)" not found

**What is the expected behavior?**

The same behaviour if upstream is called directly, without URL encoding the result

e.g.   GET http://gateway/promotions/(Test_GWP,Test_GWP)   --->  http://upstream/promotions/ (Test_GWP,Test_GWP)

Response: the data on promotion Test_GWA and Test_GWB

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

We can't provide as the affected SFCC backend is protected by a non public shareable secret.
If you contact us, we can provide privately

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Current version 2.4
No idea on . older versions

**Comment by buger** [comment]
@paolo-rodeghiero try setting the following settings in tyk.conf:

```
"http_server_options": {
...
  "override_defaults": true,
  "skip_url_cleaning": true,
...
}
```

**Comment by paolo-rodeghiero** [comment]
Thanks for your fast reply Leonid.
I tried but no changes  - same behaviour described

**Comment by buger** [comment]
@dencoded any ideas?

**Comment by dencoded** [comment]
@buger I will check

**Comment by dencoded** [comment]
@buger at 1st look I wasn't able to replicate this issue.

also, `"skip_url_cleaning": true` just switches of usage of logic https://golang.org/src/path/path.go?s=2075:2105#L64 which removes from path extra `/`, `.` and `..`, it doesn't do any kind of URL encoding for incoming request or transforming URI segments if I understand right.

I would ask @paolo-rodeghiero for some details:
- full tyk config and API spec for that path - to have some idea what middlewares are involved
- make sure nothing seats in the middle of tyk-gateway and SFCC-upstream

**Comment by paolo-rodeghiero** [comment]
Hello @buger and @dencoded ,
before opening the bug I replicated it in various environment without anything in the middle.
On top, I replicated it on Tyk Cloud environment - https://palo-it.cloud.tyk.io/test-sfcc-promotions/

Here attached you see the api configuration

`{
    "id": "5a3b9b4eb4a56b000132f5e6",
    "name": "Test SFCC",
    "slug": "test-sfcc-promotions",
    "api_id": "23e95de6a36b4653719ad6f5a6bab1e8",
    "org_id": "58fa1d2cb26ac9000111df50",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/23e95de6a36b4653719ad6f5a6bab1e8/",
        "target_url": "https://dev11-web1-sephorasa.demandware.net/s/Sephora_FR/dw/shop/v17_8/promotions/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}`

To reproduce it, you need a SFCC client_id secret that I can't share with you here - I can provide it but only via email. I'm trying to get my client approving to have the secret disclosed to you publicly

**Comment by dencoded** [comment]
@paolo-rodeghiero thanks for providing more details and your API definition - it helped to localize the issue. I was able to replicate this problem so there is no need to ask your client for any secret client IDs disclosure.

I've already submitted PR for this issue.
