### ISSUE TITLE
Tyk js path error handling

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1378]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we enable "tyk_js_path" in tyk.conf, gateway throws error in log.
```
time=“Dec 14 17:14:44” level=error msg=“Could not load user’s TykJS: open ./js/tyk.js: no such file or directory”
```
**What is the expected behavior?**
We should better handle this configuration option, since this can affect all hybrid users which manually mount js files
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Edit tyk.conf and add tyk_js_path line
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All/Master and stable

**Comment by buger** [comment]
Was fixed in 2.5
