### ISSUE TITLE
Validate Policy ID in stored token against that in JWT in case the jWT is varying a modified policy ID.

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1379]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
JWTs thatvhave their policy ID changed in the token will continue to use the one that they were intitially created with.

**What is the expected behavior?**
The policy claim if should be validated against the apply_policy field in the internal token to ebsure it is copied properly 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Create a JWT with a Policy field with Policy A
Use the token with the api
Create the same JWT (same sub) with a new policy field for policy B
Use the token with the api
Policy A will still be active.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Current

(Not verified, based on this thread: https://community.tyk.io/t/expired-underlying-token-with-jwt/2158/12)

**Comment by buger** [comment]
I think it is already fixed by https://github.com/TykTechnologies/tyk/pull/1325

Original issue: #607

**Comment by lonelycode** [comment]
That looks like it causes the request to fail if the policy doesn’t match what was created in first use, but if the JWT is valid then the policy should just be switched because the signature is valid?

**Comment by buger** [comment]
So, the issue, is that it should pick up a new policy for a new valid JWT, and right now it sort of cached?

The valid way is to delete association with old policy when new valid JWT found?

**Comment by lonelycode** [comment]
The JWT flow with tyk as it is now will create an internal token based of failure the policy field the first time the JWT is seen and is validated.

After that the cached version is used so long as the JWT is valid.

But if the JWT is valid and the policy ID changes to a different valid ID, then the gateway should respect the change, since the credentials issue is externally trusted by the JWT issuer. So basically we need to recreate the internal token (or update the policy of and make sure the creds are applied) when the policy ID changes to a different valid policy ID (and the JWT itself is valid).

**Comment by lonelycode** [comment]
> The JWT flow with tyk as it is now will create an internal token based of failure the policy field the first time the JWT is seen and is validated.

Typo: 

The JWT flow with tyk as it is now will create an internal token based on the the policy field the first time the JWT is seen and is validated.

**Comment by buger** [comment]
@dencoded found a new bug:

> when policy_id is changed in JWT we don't apply it on 1st API request right away. Just setting new policy ID worked but after two request to API which was confusing.

Merging https://github.com/TykTechnologies/tyk/pull/1572 and moving to re-testing
