### ISSUE TITLE
If Tyk configured to terminate SSL, and tyk service accessed using web browser it shows client certificate window

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1381]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If user tries to access resource proxied by Tyk inside **browser** and user has at least once *client* certificate installed on the system, it will show him prompt to select certificate. 
**What is the expected behavior?**
Tyk supports mutual TLS authentication and authorization, and issue that at the moment it sends "RequestClientCert" command inside TLS handshake for all APIs, but should do this only for APIs protected with Mutual TLS. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Configure standard API, install 1 client certificaite on the machine, access it with web browser
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Issue introduced in 2.5

**Comment by buger** [comment]
Looking one more time, it can be not related to SNI at all, and more to like IE XMLHttpRequest behave. Seems like issue happens only for Portal "Try it out" functionality.

**Comment by ilijabojanovic** [comment]
Verified

**Comment by velmuruganvelayutham** [comment]
@buger  is it possible to enable Client Certificate per API irrespective of domain ?.
