### ISSUE TITLE
No visual feedback when updating an API in the catalog

### ISSUE THREAD

**Issue by allan-simon** [TykTechnologies/tyk#139]
it seems the only feedback one's get is on the top right,  which is not visible as when you click on update you're at the bottom of the page (and at least on firefox , the page stays at the bottom)

**Comment by allan-simon** [comment]
actually it seems most of the forms have this problem,  one has to manually scroll up,  and check the block on the top right to see what's up.

**Comment by lonelycode** [comment]
It should auto-scroll, it could be that we missed it in some of the UI components. 

I take your point that there should be more useful feedback (maybe in the form of a success dialog).

**Comment by mvdan** [comment]
Hi @allan-simon,

We've addressed this issue in the upcoming 2.4 release. Thanks for your input!

**Comment by allan-simon** [comment]
awesome, thank you
