### ISSUE TITLE
Error in response for invalid key with exactly 3 letters is wrong

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1399]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
> "error": "Key not authorised"

**What is the expected behaviour?**
>  "error": "Access to this API has been disallowed"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create an api with Auth Token
2. Send a Get request with the header `Authorization: aaa`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tested on cloud so 2.4

**Comment by letzya** [comment]
Happens also with access_token generated by oauth/token endpoint:
Token with 1,2 or 3 chars gives incorrect response:

> yaara@Yaara's Mac ~ $ curl  https://letz2.cloud.tyk.io/oauth2.0-api/ -H 'authorization: bearer ddd'
> {
>     "error": "Access to this API has been disallowed"
> }

**Comment by ilijabojanovic** [comment]
Verified @buger please merge in release-2.7 and master branches
