### ISSUE TITLE
Not able to click on "edit" button in #/portal/catalogue

### ISSUE THREAD

**Issue by allan-simon** [TykTechnologies/tyk#140]
The button does nothing, no error in the console.

**Comment by lonelycode** [comment]
Which browser are you using?

**Comment by allan-simon** [comment]
firefox 42 on ubuntu

**Comment by lonelycode** [comment]
Awesome, thanks - probably screwed up HTML element... we've had this happen elsewhere with FF :-/ 

Can confirm it's OK in Chrome though.

**Comment by lonelycode** [comment]
Fixed (requires re-install)

**Comment by allan-simon** [comment]
great, thanks for the reactivity :)
