### ISSUE TITLE
Allow multi-policy system to merge policies

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1409]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
In multi-policy mode, policies must be segmented i.e. policy1 sets access rights, policy2 sets rate limits, policy3 sets quota

**What is the expected behavior?**
Should be able to use multi-policy mode without segmenting the policies i.e. each can set a mix of access rights, rate limits and quotas, and the combination of policies will describe the overall permissions.

**Comment by buger** [comment]
I believe we already had task like this here, on in product repo. The easiest way to solve this, detect multiple policies with access rights, and if such found, add policy_id as a prefix to session token. In other words, each policy will get own session object (separate quotas and rate limits). 

It brings lot of questions how we going to maintain such keys, especially on UI. Needs thorough planning.

**Comment by nickReyn** [comment]
Is this related to https://github.com/TykTechnologies/product/issues/6 and https://github.com/TykTechnologies/tyk/issues/1277?

**Comment by LuanvP** [comment]
@nickReyn not quite, those issues are asking that the same policy can set different rates/quotas for different API's, whereas this one is about wanting to use multiple policies to create the same effect. Maybe we can look at merging the issues? @buger 

**Use case as described by the customer request:**

1.Create 3 APIs: api1, api2, api3, each with Auth Token.

2. Create Policy1 with access to api1 and api2.

3.Create PolicyRL with access to api3 and a rate limit (3 request/sec)

4. Create a token and with multi-policy apply both Policy1 and PolicyRL.

**Current behaviour:**
The token has access and rate limiting for api3 as expected, but does not have access to api1 or api2.

**Expected behaviour:**
The token should have access to all 3 API's, and it should be rate limited on api3 only.
