### ISSUE TITLE
Protect all cookies with secure and httpOnly options for Dasboard and Portal

### ISSUE THREAD

**Issue by Pinpin31** [TykTechnologies/tyk#1410]
**Do you want to request a *feature* or report a *bug*?**
security bug

**What is the current behavior?**
Some session cookies of Dashboard and Portal are not protected with "Secure" and "HttpOnly" options.
![cookies-tyk-dashboard](https://user-images.githubusercontent.com/1773969/35093826-bfd0efb0-fc43-11e7-9f04-e8e2dee5e0d9.png)
![cookies-tyk-portal](https://user-images.githubusercontent.com/1773969/35093834-c264402e-fc43-11e7-8e7f-2a1ad8ce780c.png)

An attacker able to execute JavaScript code on the browser of other users could access cookies not protected by the attribute "HttpOnly". In case of a "Man-in-the-Middle" attack, it was also possible to compromise the cookies passing in clear on the network.

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard 1.4.2

**Comment by buger** [comment]
Thank you for reporting!
