### ISSUE TITLE
Custom tags for analytics entries

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1428]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the expected behavior?**
Configure custom tags in `tyk.config` that are added to every analytics line. 
Useful for determining which gateway slave generated that line.
Should be agnostic of `node_is_segmented` setting

**Comment by buger** [comment]
Add new configuration option called "analytic_tags" to "analytic_configs" part of tyk.conf, track all usages of `analytics.RecordHit` function, and ensure that `AnalyticsRecord#tags` will get updated with data from config.
