### ISSUE TITLE
Key restrictions

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1430]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the expected behavior?**
To prevent unauthorized use and quota theft, it should be possible to restrict key usage.
Key restriction should let you specify which websites (referrers) or IP addresses, allowed to use it.

Inspired by Google API keys:

![image](https://user-images.githubusercontent.com/14009/35402584-b43275d0-0205-11e8-8906-efdd9fa0f2e1.png)

**Comment by pete-rai** [comment]
Ordinance Survey also provide this feature on their APIs. For a standard web app, the key may well be visible inside downloaded JavaScript. Then it is open for simple, cut-n-paste theft. Keeping the key on the server only, would require some messy and redundant calls via the server. If you do add this (and hopefully you will), do add it to the developer portal API as well.

**Comment by hustshawn** [comment]
when this feature would be released ?
