### ISSUE TITLE
tyk_quickstart is pulling 2.4

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1431]
tyk_quickstart is pulling 2.4, compose file should be updated to latest of everything

**Comment by bitsofinfo** [comment]
Tried manually changing it myself getting:

```
Pulling tyk_dashboard (tykio/tyk-dashboard:v1.5.0)...
ERROR: manifest for tykio/tyk-dashboard:v1.5.0 not found
```

**Comment by nickReyn** [comment]
Should be fine now - let us know if any issues 👍
