### ISSUE TITLE
Display API ID some where on dashboard "API Designer - Edit API" interface

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1434]
Display API ID some where on dashboard "API Designer - Edit API" interface

Right now the only clear way to find the API id is in the api list view. It should be clearly displayed somewhere in the "API Designer - Edit API" interfaces

**Comment by nickReyn** [comment]
Suggest we add it to the top of the page, using same style as on the policy page. @lghiur

**Comment by nickReyn** [comment]
@lghiur seems we have this data in the object on this page - so UI only work?

**Comment by bitsofinfo** [comment]
not stale

**Comment by agata-wit** [comment]
This has been already added in 3.2. Users can now see both API URL and ID at the top of the API designer page

![image](https://user-images.githubusercontent.com/85508803/125929131-d60cbf04-3ef6-4054-a67a-b0f410286cc1.png)

Issue closed.
