### ISSUE TITLE
Make JSVM middleware "timeout" configurable

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1435]
https://github.com/TykTechnologies/tyk/blob/3f1fd288633611619311449559a8ce83ff11e9f2/mw_js_plugin.go#L340

Currently is hardwired for 5s

Have needs in development where things are slower to bump this number up

**Comment by buger** [comment]
@LuanvP add a new configuration option to tyk.conf with a sensible name and make sure that it will default to 5 if not set.

**Comment by LuanvP** [comment]
Issues while testing for this was due to this issue https://github.com/TykTechnologies/tyk-analytics/issues/696

VirtualEndpoint middleware was using same JSVM object but not checking the timeout value, unlike DynamicMiddleware.

**Comment by bitsofinfo** [comment]
Verified this works, thanks!
