### ISSUE TITLE
Add retries with exponential backoffs

### ISSUE THREAD

**Issue by ajohnstone** [TykTechnologies/tyk#144]
In the documentation it is recommended to use nginx in front of the api gateway, nginx will retry requests upon failure. It would be ideal for tyk to handle retries at the application level and specify the backoff algorithm.

This should allow for endpoints to have configurable retries globally and for individual API endpoints.
The retries should have stats shown on the dashboard to show retries and failure rates.

_A little thought may be required as to, how to handle alerting on such failures and how this data would be exposed._

**Comment by lonelycode** [comment]
As of v1.9 nginx is no longer a requirement for Tyk, domain handling happens entirely within the Tyk node.

How does NginX indicate a request has been retried? It could be captured (we don;t store request data atm, but we're looking to expand that)

**Comment by ajohnstone** [comment]
Sorry, should have been clearer I've updated the original ticket, as I wrote the ticket in a rush.
