### ISSUE TITLE
Keys created via API do not display HMAC secret on Dashboard

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1444]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When viewing a key in the Dashboard, keys that have HMAC enabled instead display the following error: 
![screen shot 2018-01-30 at 10 17 15](https://user-images.githubusercontent.com/28846119/35562549-a2829db6-05ab-11e8-9d6d-0c879e7f4ca9.png)

**What is the expected behavior?**
The secret should be displayed:
![screen shot 2018-01-30 at 10 52 38](https://user-images.githubusercontent.com/28846119/35562582-b791a706-05ab-11e8-978f-389f58386d8b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create key via API call with "hmac_enabled": true,
Lookup key in Dashboard,
HMAC secret is missing

**Note:** This is currently only an issue for keys created via the API, keys created via the dashboard behave as expected. As a workaround, the secret can be found by requesting the key record via API.

**Comment by ilijabojanovic** [comment]
Verified
