### ISSUE TITLE
Endpoint designer, URLRewriter config disappears 

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1454]
1.5/2.5 docker quick start

In end point designer I declare the following and hit update, after looking at the POST config after the update, the url re-writer config is empty/gone.

I would guess this must be due to some validation error, but there is no indication of this. Its also unclear in the UI if the rewrite to target above the "triggers" is required... as you seem to redeclare your own "rewrite to" per each trigger.

Overall super confusing

<img width="1002" alt="screen shot 2018-02-02 at 9 34 38 am" src="https://user-images.githubusercontent.com/1743646/35738373-b5fa8860-07fc-11e8-81c0-3e12f9e149cf.png">

**Comment by buger** [comment]
This bug was fixed in 2.5.1/1.5.1 release 1 day ago. Try to fetch latest docker images.

**Comment by bitsofinfo** [comment]
thx!
