### ISSUE TITLE
Tarpit new requests instead of rejecting

### ISSUE THREAD

**Issue by cbrunnkvist** [TykTechnologies/tyk#1459]
**Do you want to request a *feature* or report a *bug*?**

*Feature request*

 (also called _blocking_, _sleeping_, or _enqueuing_ requests)

**What is the current behavior?**

Given the request limit of 1 request per 1 minute 
And with request A just started
When request B starts
Then it immediately gets sent a `429 Rate Limit Exceeded` response
And then it terminates

**What is the expected behavior?**

Given the request limit of 1 request per 1 minute 
And with request A just started
When request B starts
Then it simply blocks until rate limit is no longer exceeded
And it gets sent upstream and processes like normal

**Further details**

Perhaps mainly for internal API use cases where I fundamentally trust clients not to DoS me, I just want the request to block while rate is excessive. This in order to avoid having to update multiple disparate clients to manage 429 and corresponding transactional retry logic. I want to maximize the chance that the request _eventually_ pass through, while guaranteeing the upstream source a somewhat even request rate.

Possible tarpit configuration parameters would include:
- maximum delay (max time a request can spend in the tarpit = value used for deciding immediately upon new request if it should be rejected or delayed)

Does this make sense? Feedback or ideas for workarounds welcome.

**Comment by cbrunnkvist** [comment]
https://blog.codecentric.de/en/2014/12/haproxy-http-header-rate-limiting/

**Comment by asoorm** [comment]
A few thoughts:

When an API has more than a pre-defined limit of active connections, new requests are placed on a FIFO queue.

Once the number of active connections has dropped below the limit, the queue is drained by allowing the requests in the queue to process.

The queue has a capacity and each request in the queue is assigned a timeout. In the event that the number of requests in the queue exceeds the capacity, or a request is in the queue for more than the assigned timeout, the request is cancelled and a Service Unavailable response is returned.

Tyk currently has the concept of quotas and rate limits. These are hard limits in that going over this usage will return a rate limit exceeded error.

As a means to protect the upstream service from becoming overloaded, but also reduce the number of "unsuccessful requests" an API owner may wish to configure a throttle within Tyk's API configuration.

As such, an API definition must be configurable by:

* Number of concurrent / active connections to that endpoint/service
* Backlog queue size
* Queue Request TTL

See: https://godoc.org/github.com/go-chi/chi/middleware#Throttle
See: https://godoc.org/github.com/go-chi/chi/middleware#ThrottleBacklog
