### ISSUE TITLE
when using SSO for admin dashboard, carry user information in audit logs, instead of ssoSession@ssoSession.com

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk#1462]
**Do you want to request a *feature* or report a *bug*?**
Feature

### Requirements
When using SSO for admin dashboard, carry user information in audit logs, instead of ssoSession@ssoSession.com

**Comment by joshblakeley** [comment]
The reason we have the `ssoSession@ssoSession.com` in logs is because that is the default when there is no email set.

Would we rather have a blank placeholder?

**Comment by buger** [comment]
@letzya is working on the fix to replace it with real email

**Comment by joshblakeley** [comment]
Ok i'll leave it to her :)

**Comment by joshblakeley** [comment]
Maybe just warn that no email is set?

**Comment by joshblakeley** [comment]
Sorry i don't know as much as you do - is the email important for the sso functionality we have?

**Comment by csbogdan** [comment]
Hello. The email, or some unique way to identify the user, is important for audit purposes really. That's where this request comes from.

**Comment by snaredla7** [comment]
We need this feature as without it there is no point in enabling LDAP authentication with Dashboard.
