### ISSUE TITLE
Analytics Data Not Showing

### ISSUE THREAD

**Issue by polds** [TykTechnologies/tyk#147]
I have just set up a clean installation of Tyk that uses an external Redis cluster and an external Mongo server with sharding. I can see analytics are being added to Mongo:

```
{
  "_id": ObjectId("56690536c9a9d840e6af8a14"),
  "method": "GET",
  "path": "",
  "contentlength": NumberLong(0),
  "useragent": "Go-http-client/1.1",
  "day": 10,
  "month": 12,
  "year": 2015,
  "hour": 4,
  "responsecode": 200,
  "apikey": "00000000",
  "timestamp": new Date(1449723190672),
  "apiversion": "Non Versioned",
  "apiname": "HttpBin",
  "apiid": "40df2294498d4293769d423900412226",
  "orgid": "5668f77f7582400ad8000001",
  "oauthid": "",
  "requesttime": NumberLong(1),
  "tags": [

  ],
  "expireAt": new Date(4603323190672)
}
```

But the dashboard doesn't show any of these analytics. We're using the latest Tyk Dashboard + Gateway and Mongo 3.0.7.

My tyk_analytics.conf looks like this:

```
    ...
    "mongo_url": "mongodb://10.0.0.147:27017/tyk_analytics",
    "mongo_collection": "tyk_analytics",
    ...
```

Edit: Same behavior as #30 but I am running on Mongo 2.6+

**Comment by lonelycode** [comment]
There's a bug with the date range for December - it sets the end date to month 0, when it should be month 1 - try selecting Jan in the end date drop down and pressing the search icon. The stats should show up.

**Comment by polds** [comment]
ah.. huh. Yeah that worked.

Strange I had spun up a Vagrant version of Tyk this morning and it didn't exhibit this bug. Thanks :)
