### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by maaydin** [TykTechnologies/tyk#1472]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Tyk exits with exit code 2
**What is the expected behavior?**
Tyk continue to serve
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Hard to reproduce but error occurs when automated tests run
  - Running dockerized version
  - Using file based configs
  - Using policies
  - Using middleware js scripts
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
 2.4.2-2.5.1

Beginning of the trace from tyk 2.4.2 version. Full trace attached.
[tyk-fatal-error-stacktrace.txt](https://github.com/TykTechnologies/tyk/files/1719982/tyk-fatal-error-stacktrace.txt)

fatal error: concurrent map iteration and map write
goroutine 78971 [running]:
runtime.throw(0xe14ac0, 0x26)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc424655a58 sp=0xc424655a38
runtime.mapiternext(0xc42cbc2fc0)
	/usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc424655b08 sp=0xc424655a58
reflect.mapiternext(0xc42cbc2fc0)
	/usr/local/go/src/runtime/hashmap.go:1156 +0x2b fp=0xc424655b20 sp=0xc424655b08
reflect.Value.MapKeys(0xcf1980, 0xc42fae1be8, 0x195, 0x0, 0xc424655c48, 0x70701f)
	/usr/local/go/src/reflect/value.go:1112 +0x1bc fp=0xc424655bd0 sp=0xc424655b20
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.encodeMapValue(0xc423d15740, 0xcf1980, 0xc42fae1be8, 0x195, 0xcf1980, 0xc42fae1be8)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode_map.go:19 +0xe0 fp=0xc424655c58 sp=0xc424655bd0
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.(*field).EncodeValue(0xc42757e740, 0xc423d15740, 0xde3f40, 0xc42fae1ba0, 0x199, 0x0, 0x0)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/types.go:86 +0x82 fp=0xc424655ca0 sp=0xc424655c58
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.encodeStructValue(0xc423d15740, 0xde3f40, 0xc42fae1ba0, 0x199, 0xc42fae1ba0, 0x199)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode_map.go:145 +0x16a fp=0xc424655d10 sp=0xc424655ca0
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.ptrEncoderFunc.func1(0xc423d15740, 0xd49d40, 0xc42fae1ba0, 0x16, 0xd49d40, 0xc42fae1ba0)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode_value.go:100 +0xd4 fp=0xc424655d58 sp=0xc424655d10
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).EncodeValue(0xc423d15740, 0xd49d40, 0xc42fae1ba0, 0x16, 0x16, 0x0)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode.go:116 +0x8c fp=0xc424655d98 sp=0xc424655d58
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).encode(0xc423d15740, 0xd49d40, 0xc42fae1ba0, 0x30, 0xd53aa0)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode.go:111 +0x21c fp=0xc424655de0 sp=0xc424655d98
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).Encode(0xc423d15740, 0xc424655f20, 0x1, 0x1, 0x9, 0x9)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode.go:66 +0x5b fp=0xc424655e28 sp=0xc424655de0
github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack%2ev2.Marshal(0xc424655f20, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0xc424655f00, 0x536fec, 0xc425e3ca10)
	/src/github.com/TykTechnologies/tyk/vendor/gopkg.in/vmihailenco/msgpack.v2/encode.go:33 +0x15a fp=0xc424655eb0 sp=0xc424655e28
github.com/TykTechnologies/tyk/user.(*SessionState).Hash(0xc42fae1ba0, 0x10, 0x10)
	/src/github.com/TykTechnologies/tyk/user/session.go:86 +0x7a fp=0xc424655f78 sp=0xc424655eb0
github.com/TykTechnologies/tyk/user.(*SessionState).HasChanged(0xc42fae1ba0, 0xc424656110)
	/src/github.com/TykTechnologies/tyk/user/session.go:95 +0x4e fp=0xc424655fb0 sp=0xc424655f78
main.(*DefaultSessionManager).UpdateSession(0xc4232609c0, 0xc4298289ef, 0x21, 0xc42fae1ba0, 0x0, 0x0, 0x199)
	/src/github.com/TykTechnologies/tyk/auth_manager.go:113 +0x40 fp=0xc424656048 sp=0xc424655fb0
main.BaseMiddleware.ApplyPolicies(0xc42011b340, 0x1330be0, 0xc42b285040, 0xc4298289ef, 0x21, 0xc42fae1ba0, 0xc42bf7a680, 0x0)
	/src/github.com/TykTechnologies/tyk/middleware.go:253 +0xbbf fp=0xc424656470 sp=0xc424656048
main.BaseMiddleware.CheckSessionAndIdentityForValidKey(0xc42011b340, 0x1330be0, 0xc42b285040, 0xc4298289ef, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/src/github.com/TykTechnologies/tyk/middleware.go:283 +0x389 fp=0xc424656f50 sp=0xc424656470
main.(*AuthKey).ProcessRequest(0xc42a6c2060, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100, 0x0, 0x0, 0x10, 0xc42a667438, 0x446df5)
	/src/github.com/TykTechnologies/tyk/mw_auth_key.go:91 +0x5c4 fp=0xc4246573d0 sp=0xc424656f50
main.createMiddleware.func1.1(0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/middleware.go:74 +0x5f9 fp=0xc424657538 sp=0xc4246573d0
net/http.HandlerFunc.ServeHTTP(0xc42a81a240, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc424657560 sp=0xc424657538
main.createMiddleware.func1.1(0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/middleware.go:88 +0x7ec fp=0xc4246576c8 sp=0xc424657560
net/http.HandlerFunc.ServeHTTP(0xc42a81a280, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc4246576f0 sp=0xc4246576c8
main.createMiddleware.func1.1(0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/middleware.go:88 +0x7ec fp=0xc424657858 sp=0xc4246576f0
net/http.HandlerFunc.ServeHTTP(0xc42a81a2c0, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc424657880 sp=0xc424657858
main.createMiddleware.func1.1(0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/middleware.go:88 +0x7ec fp=0xc4246579e8 sp=0xc424657880
net/http.HandlerFunc.ServeHTTP(0xc42a81a300, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc424657a10 sp=0xc4246579e8
main.createMiddleware.func1.1(0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/middleware.go:88 +0x7ec fp=0xc424657b78 sp=0xc424657a10
net/http.HandlerFunc.ServeHTTP(0xc42a81a340, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc424657ba0 sp=0xc424657b78
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42031ceb0, 0x1330ee0, 0xc42634dc00, 0xc42f2b2100)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c fp=0xc424657ca0 sp=0xc424657ba0
main.mainHandler.ServeHTTP(0x1330ee0, 0xc42634dc00, 0xc42a3d9f00)
	/src/github.com/TykTechnologies/tyk/main.go:1272 +0x4b fp=0xc424657cd0 sp=0xc424657ca0
main.(*mainHandler).ServeHTTP(0x142a620, 0x1330ee0, 0xc42634dc00, 0xc42a3d9f00)
	<autogenerated>:744 +0x63 fp=0xc424657d10 sp=0xc424657cd0
net/http.serverHandler.ServeHTTP(0xc42b28c8f0, 0x1330ee0, 0xc42634dc00, 0xc42a3d9f00)
	/usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc424657d58 sp=0xc424657d10
net/http.(*conn).serve(0xc42b24da40, 0x1331d20, 0xc4243a5000)
	/usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc424657fc8 sp=0xc424657d58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc424657fd0 sp=0xc424657fc8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
goroutine 1 [chan receive, 9 minutes]:
github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain.Wait(0x1330ce0, 0xc42000e828, 0x0, 0x0, 0x13248e0)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/TykTechnologies/goagain/goagain.go:210 +0x19f
main.main()

**Comment by matiasinsaurralde** [comment]
Can you confirm that this occur when running the automated tests? Which parameters are you using?

**Comment by maaydin** [comment]
Yes, when running automated tests in parallel. After some investigations we found that partitioned policies causes the exception, we have temporarily closed partitioned policies and everything works fine.

Latest trace and the sample api definitions (removed some of the definitions/policies in the same pattern) attached, hope it helps you to reproduce the case:
[tyk-mf.zip](https://github.com/TykTechnologies/tyk/files/1751085/tyk-mf.zip)
[concurrent map iteration and map write-fatal-error.txt](https://github.com/TykTechnologies/tyk/files/1751087/concurrent.map.iteration.and.map.write-fatal-error.txt)

@zeldal & @bilalyasar spent some time on this issue and here their notes:

It seems synchronization part is missing to achieve Atomic SessionState Updates when multiple API call with same session occurs concurrently(using localsessioncache). In general, SessionState can be modified with different ApplyPolicy calls, that might cause inconsistencies without giving Concurrent Modification Errors. In our case partitioned policies are applying at https://github.com/TykTechnologies/tyk/blob/v2.5.1/middleware.go#L217, that is causing concurrent modification on Map while other routine iterating over.

We hope this will help further.

**Comment by matiasinsaurralde** [comment]
Thanks @zeldal, @bilalyasar, @maaydin, this is very useful for us.

**Comment by buger** [comment]
Fixed in master, scheduled to next patch release
