### ISSUE TITLE
Load balancing adjusted for actual load on backend

### ISSUE THREAD

**Issue by larsnaesbye** [TykTechnologies/tyk#1497]
**Do you want to request a *feature* or report a *bug*?**
Request a feature
**What is the current behavior?**
Load balancing using self-healing round robin
**What is the expected behavior?**
The option to dispatch requests depending on backend server load
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
The current version (2.5.1). I can't see how to get load information into Tyk. I haven't tried the mentioned service discovery option, though.

**Comment by asoorm** [comment]
I think you could take a look at `Service Discovery` & also `Uptime Tests`.

Uptime tests can flag if a host is down and, if the internal Load Balancer is in use, that host can be removed from the list throughout the period that the host is down.

The service discovery can also be used to auto-configure the load balancer target list.

**Comment by larsnaesbye** [comment]
Well, isn't this just based on whether the backend is available or not in a round robin scenario? Better load balancing could perhaps base the ratio of requests on a load parameter fro the backend...?

**Comment by buger** [comment]
So, how do you see this implemented from your point of view? 
The main issue here is how tyk will decide weighting of the server, for example, we can probably add way to specify weights which you can assign to upstream servers, but I'm not sure if this is what you mean.

**Comment by larsnaesbye** [comment]
Well, I was thinking of some kind of backend load information collected and the number of requests sent to that specific backend adjusted accordingly. A heartbeat is just an up/down indicator.
For example, some Web Feature Service requests are quite taxing on backend processing power while taking several seconds to finish. Others are quite simple and fast.
Balancing between backend servers could then be to send the next requests to the lesser burdened servers.

**Comment by buger** [comment]
Do you know examples of another systems which do it like this?

**Comment by larsnaesbye** [comment]
Yes, our internally developed legacy system (which I am now trying to find a suitable community-driven replacement for, e.g. Tyk) uses recent response time differences to adjust request dispatching.

**Comment by asoorm** [comment]
I can think of a few strategies if we decide to implement this... Some will require tracking of number of currently active connections to each host.

1. Keep a list and send traffic to the host which has least number of requests at that given moment in time.

2. Potentially picking a lower overhead soln such as randomly selecting x% of hosts from the pool, then LB to the least loaded.

3. moving avg response time based LB

These are probably quite a naive approaches - and I would probably want to run some tests to see what happens and how system would react under different scenarios.

**Comment by larsnaesbye** [comment]
Exactly what I was thinking of, @asoorm. 1 and/or 3 would be really useful for the scenarios we have here.

**Comment by larsnaesbye** [comment]
Here's how we do it in our system: Each node broadcasts on multicast UDP small packages of load information for every backend the node services. These packages are serialized Java POJO in our case.
The other nodes listen and factor it into their load balancing. It tends to work quite well, giving stable reply times.
