### ISSUE TITLE
Possible to override the Redigo settings?

### ISSUE THREAD

**Issue by polds** [TykTechnologies/tyk#150]
Just tried sending our Tyk Gateway cluster through a blitz rush 0-1000 users and about 30 seconds in it started throwing tons of 500 Errors and the logs indicate things such as:

```
time="2015-12-11T04:37:45Z" level=error msg="Transacton failed: redigo: connection pool exhausted"
time="2015-12-11T04:37:45Z" level=error msg="Multi command failed: return index is out of range"
time="2015-12-11T04:37:45Z" level=error msg="Error trying to delete keys:"
time="2015-12-11T04:37:45Z" level=error msg="redigo: connection pool exhausted"
```

Our setup:

Tyk Gateway Nodes:
 - 3 m3.medium - non-purging

Tyk Dashboard Nodes:
  - 2 m3.medium - Dashboard + Gateway - purging

Redis Cluster
 - Elasticache - cache.m1.small - 2 Read Replicas

MongoDB Cluster
 - Master - 1 m3.medium
 - Config - 3 m3.medium 

It doesn't appear that the Elasticache servers were being taxed, so I'm wondering if the Redigo pool settings can be overridden at all.

**Comment by lonelycode** [comment]
Yeah it's all in the config file, you can change the connection pool size by setting two values:

storage{
...
optimisation_max_idle: 2000,
optimisation_max_active:3000,
...
}

**Comment by polds** [comment]
Yep that worked, thank you.

**Comment by lonelycode** [comment]
Would you be willing to share your results? Always interesting for us - you can email me directly if you like on martin@tyk.io

**Comment by sousmangoosta** [comment]
Hey @lonelycode,

I have same issue since upgrade from 1.7.3 to 2.2.0.
Do you see some changes related ?

Thx

**Comment by lonelycode** [comment]
@sousmangoosta That's about as clear as mud, if this is a bug, please raise a new ticket with the actual details of the issue. If it's a question about how Tyk works or a problem with your configuration please see our [community forum](https://community.tyk.io)
