### ISSUE TITLE
OpenID Connect, invalid/expired token returning 403 instead of 401

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1503]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When a token is expired, gateway returns 403
**What is the expected behavior?**
Should return 401 as specified here: https://tools.ietf.org/html/rfc6750#section-3.1

Note: A valid token with insufficient privileges should return 403

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by matiasinsaurralde** [comment]
Any steps to reproduce this?

**Comment by ilijabojanovic** [comment]
Verified
