### ISSUE TITLE
tyk.conf - when using the dashboard, shouldnt require to set the its uri twice in`policies` and `db_app_conf_options`

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1505]
**Do you want to request a *feature* or report a *bug*?**
Feature, could cause behavioral bugs.

**What is the current behavior?**
Conf file requires to define the dashboard in 2 places:

>      "policies": {
>          "policy_source": "service",
>           "**policy_connection_string**": "http://my-tyk-instance.com:3000",
>           "policy_record_name": "",
>           "allow_explicit_policy_id": false
>      },
>       "use_db_app_configs": true,
>       "db_app_conf_options": {
>           "**connection_string**": "http://my-tyk-instance.com:3000",
>           "node_is_segmented": false,
>           "tags": null
>       },

**What is the expected behavior?**
db_app_conf_options should be enough and _policy_connection_string_ can get it's value from there if  _"policy_source" is "service"._
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
the regular set up for GW that is not running headless.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All (2.5.2 at the moment)

**Comment by letzya** [comment]
Put as Priority: Low since it's working as it is (though it can make our users' lives easier and less error prone)

**Comment by l3ender** [comment]
Commenting as to not let this drop. These types of fixes make the product better and more usable in the long term.

**Comment by andyo-tyk** [comment]
This fix was merged to master in 2019 so I'm closing the ticket.

@l3ender if you think there's still something here please don't hesitate to reopen/comment and we'll look into it again.
