### ISSUE TITLE
Swagger import from url

### ISSUE THREAD

**Issue by adrien-candiotti** [TykTechnologies/tyk#151]
I imported my swagger definition by copy pasting it but noticed that I can't import it from an endpoint.
As most implementation that expose a documentation for a swagger specification also expose a json version of it, it would be awesome to import it via a url so that we don't have to update it manually each time it changes.

What do you think?

**Comment by lonelycode** [comment]
You can add an endpoint swagger JSON in the portal for publication, but not to define an API.

Good idea though -)

**Comment by JosephEarl** [comment]
:+1: - this is how I thought would work initially, until I realised I had to paste the content in

**Comment by lonelycode** [comment]
URL based import is supported for the portal. For the gateway, it's injected and converted as raw JSON.

We'll look into adding this in future.

**Comment by adrien-candiotti** [comment]
That would be great :)

A webhook to reupdate it automatically would be cool too but that's a bit too much to ask haha :P

**Comment by JosephEarl** [comment]
Does URL based import load the original Swagger file once? Or every time I load the page?

**Comment by lonelycode** [comment]
Every time, it's not an import

**Comment by JosephEarl** [comment]
Awesome. That's what I need then... although I need to set up a small server in front of my micro services first to combine the swaggers. Been using Tyk in a dev/test environment and was getting bored with repasting the swagger.json and updating links to the docs, that will save me some time, thanks!
