### ISSUE TITLE
Modify Response Header/Body should support Context Variables

### ISSUE THREAD

**Issue by zeldal** [TykTechnologies/tyk#1510]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Modify Response Header/Body doesn't support Context Variables

**What is the expected behavior?**
Modify Response Header/Body should support Context Variables

**Comment by buger** [comment]
This PR #1511 adds new `replaceTykVariables`, which should be straightforward to use inside `HeaderInjector` and `HeaderTransform` middlewares which used for responses. 

Regarding body transformation, it is done using `ResponseTransformMiddleware` and we should took context variable support code from `TransformMiddleware`, looking at the code there can be a lot of re-use.

**Comment by ilijabojanovic** [comment]
Verified
