### ISSUE TITLE
Add "append/addHeaders" functionality to JSVM request object

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1514]
**Do you want to request a *feature* or report a *bug*?**

feature/bug

**What is the current behavior?**

If I need to set multiple headers in a JSVM plugin based on conditional logic, every call to "request.setHeaders" overwrites the last one. 

This is especially detrimental if I have a chain of plugins that use request headers to exchange arguments downstream, or headers set by plugin A, that need to be consumed by plugin C (the existence of plugin B that sets headers, wipes out plugin's A headers)...

i.e. A(set x)->B(set y)->C(needs x, but missing cause B wiped it, B has no knowledge of A nor should it)

```
request.setHeaders({x:y,a:b})
request.setHeaders({c:d})

Yields headers = "c=d"
```

**What is the expected behavior?**

Would just like an "appendHeaders" or "addHeaders" function instead

```
request.addHeaders({x:y,a:b})
request.addHeaders({c:d})

Yields headers = "c=d, x=y, a=b"
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All current

**Comment by beyerjsb** [comment]
I had the same problem, though I expected a completely different resolution:

https://community.tyk.io/t/tyk-gateway-virtual-endpoint-request-headers-vs-response-headers-inconsistency/3221/6

For me, the headers of all request and response objects should be consistent as arrays.

**Comment by letzya** [comment]
@matiasinsaurralde can you please have a look?

**Comment by bitsofinfo** [comment]
not stale

**Comment by tobiasb** [comment]
Any update here?

**Comment by agata-wit** [comment]
@tobiasb is this in any relation to what you opened here https://github.com/TykTechnologies/tyk/issues/3622 ?

**Comment by andyo-tyk** [comment]
Closing as this is not currently on our roadmap, but we may return to it later if there is renewed interest from users.
