### ISSUE TITLE
Expose request "protocol" to JSVM middleware plugins

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1516]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Have no idea what protocol (http or https) the current request was requested with when it hit tyk

**What is the expected behavior?**

should have access to something like `request.Protocol`

**Comment by buger** [comment]
@joshblakeley re-opening seems like it still not work as expected. Pls add unit tests for both VirtualEndpoint, JSVM plugin and Python. In our current test suite you can find examples for writing tests for all of this plugin types.

I would say we need to make such tests generalized, and check all minirequestObject fields, as well as context/meta, for all plugin types.

**Comment by joshblakeley** [comment]
If aim is just to differentiate between http and https we can check if `request.TLS == nil` and pass on that information. I think that is more reliable than hoping the url scheme is actually populated.

For most request the Go http package will not populate most of the URL fields in the request as per `RFC 7230, Section 5.3`

**Comment by bitsofinfo** [comment]
fine w/ that, just need a reliable indicator of the scheme tls or no tls

**Comment by buger** [comment]
@joshblakeley I think the root issue also is that current feature code was implemented only for virtual endpoint, but also needs be extended for both JSVM, and Coprocess middleware.

**Comment by joshblakeley** [comment]
Even in virtual endpoint I couldn't get it to be non blank so will try other approach and apply it to all possibilities.
