### ISSUE TITLE
Doc clarification: JSVM: declared functions in plugins are globally available

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1517]
**Do you want to request a *feature* or report a *bug*?**

I'm not sure if this is a bug, or a nice undocumented feature. It bit me today when doing some development and it was completely confusing. 

**What is the current behavior?**

I have 2 JSVM plugins, declared in separate JS files under middleware/

**pluginA.js**
```
function someFunction1() {
    //implementation A
}
var pluginA = new TykJS.TykMiddleware.NewMiddleware({});
pluginA.NewProcessRequest(function(request, session, config) {
   // do something
   someFunction1();
   return pluginA.ReturnData(request,{});
});
```

**pluginB.js**
```
function someFunction1() {
    //implementation B
}
var pluginB = new TykJS.TykMiddleware.NewMiddleware({});
pluginB.NewProcessRequest(function(request, session, config) {
   // do something
   someFunction1();
   return pluginB.ReturnData(request,{});
});
```

When pluginA runs, and calls `someFunction1()`, it actually invokes the implementation declared in `pluginB` (because pluginB is declared after pluginA in the custom_middleware for the API)

**What is the expected behavior?**

Well, in my case this is fine because in reality I was copying the function around figuring they were scoped per plugin, its actually nicer to be able to declare the function one time instead of copying it around to all plugins that need it...... **however** maybe I missed this in the documentation, but that was not clear from the get-go. I figured each "plugin" was scoped properly namespacing wise, but it would appear they are all loaded into the same namespace and the last "function" of the same name wins.

In all reality this is fine for me, and actually prefer this behavior now that I see how it works....however perhaps some clarification in the docs or developer guide?

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

all

**Comment by matiasinsaurralde** [comment]
Thanks for the suggestion @bitsofinfo

**Comment by bitsofinfo** [comment]
No problem, just want to ensure this is tracked somewhere or documented, because I'm about to leverage this as a "feature", and would need to know if that behavior changes :)

**Comment by matiasinsaurralde** [comment]
Follow up here: https://github.com/TykTechnologies/tyk-docs/pull/348
