### ISSUE TITLE
TykMakeHttpRequest does not send query string parameters on a GET

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1518]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
I expect a GET to: `https://myhost:8443/service/testws?wsdl`

What I happens is a get to `https://myhost:8443/service/testws%3Fwsdl`

```
var newRequest = {
    "Method": "GET",
    "Body": "",
    "Headers": {
        "X-My-Apigw-Request-Id":request_id,
        "X-My-B3-Traceid":x_my_b3_traceid
     },
    "Domain": "https://myhost:8443",
    "Resource": "/service/testws?wsdl"
};

var rawWsdlResp = TykMakeHttpRequest(JSON.stringify(newRequest));
```

Also tried the below with `FormData` but just does a GET to `https://myhost:8443/service/testws`
w/ no query string.

```
var newRequest = {
    "Method": "GET",
    "Body": "",
    "Headers": {
        "X-My-Apigw-Request-Id":request_id,
        "X-My-B3-Traceid":x_my_b3_traceid
     },
    "Domain": "https://myhost:8443",
    "Resource": "/service/testws",
    "FormData": {"wsdl":""}
};

var rawWsdlResp = TykMakeHttpRequest(JSON.stringify(newRequest));
```
Verified with tcpdumps

**What is the expected behavior?**

That I can use TykMakeHttpRequest to do a GET request with a query string

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.5.2

**Comment by bitsofinfo** [comment]
https://community.tyk.io/t/tykmakehttprequest-and-url-params/1008/8

**Comment by bitsofinfo** [comment]
FYI works with TykBatchRequest.

**Comment by joshblakeley** [comment]
Although not obvious, if you add the query params at the end of the domain field they should get added correctly to the request when using TykMakeHttpRequest
