### ISSUE TITLE
TykMakeHttpRequest & TykBatchRequest response object inconsistent

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1519]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The response object from `TykMakeHttpRequest` and `TykBatchRequest` differ in that `TykMakeHttpRequest`'s response object's headers are in a property called `Headers` but in `TykBatchRequest` the response is called `headers`.  This applies to all properties.

**What is the expected behavior?**

All response object properties should be consistently named 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

all

**Comment by asoorm** [comment]
I'm not certain we can change this without breaking backwards compatibility. Any thoughts?

**Comment by buger** [comment]
We can support both formats for some time, and remove the lower case version in 3.0 or similar.

**Comment by buger** [comment]
Released as part of 2.7
