### ISSUE TITLE
Requesting the notion of "Applications" within the portal

### ISSUE THREAD

**Issue by billxinli** [TykTechnologies/tyk#1525]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
API consumers are consuming Policies in the portal. Keys are tied to the policy.

**What is the expected behavior?**
Ideally, the following behavior should be accomplished:

✔️ As a consumer, I can sign up for the portal 
- As a consumer, I can register an application in the portal
- As a consumer, I can create a key (Application API Key) for the application that I registered in the portal
- As a consumer, I can subscribe to policies for the application
- As a consumer, I can use the Application API Key to access to all the APIs that is allowed under the policy, which this is subscribed to the application

This basically allows a third component (application) which is tied to the keys and policies to be defined in the system. Such that the consumer of the API (developer of third-party applications) can use a single key to subscribe to multiple policies (which has defined access roles to downstream APIs)

Then the API providers/Admins can approve the "subscription" event, rather than approving the request for keys in the dashboard

This allows the API consumer/3rd party developer to manage keys, access to policies. Rather than having the API provider to provide custom combination policies to the API consumers.

This basically follows how Google Developer Console provision keys.

You login as a consumer, create an application/project, then get a key, and finally activate/subscribe one or more Google APIs, then that key you've received can access to all the APIs that you've subscribed to.

**Comment by buger** [comment]
Hello! 

This is definitely on our radar, and the first step will be implementing support of applying multiple policies to the token, so each API will have own limits https://github.com/TykTechnologies/tyk/issues/1409. This is in our very close roadmap. 

Portal improvements will be the next step, and it still not clear how to implement this functionality and make it backward compatible. 

Thank you!

**Comment by christtyk** [comment]
@buger this looks like STC-11 to me. Let me know if a new issue needs creating.
