### ISSUE TITLE
Hybrid: deletes of API def in cloud, do not get pushed to gateways

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1530]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If I delete an API def at admin.cloud.tyk.io, the change does not get pushed to the gateways. Updates to existing api defs are pushed fine.

**What is the expected behavior?**

Deletes of API defs should get pushed to the gateways, the only way to effectively clear an api is to restart the gateway

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.5.2

**Comment by joshblakeley** [comment]
Not able to reproduce this locally @ilijabojanovic is this still an issue for you?

Reload in slave successful when I delete API, do you have any particular things like group ID's or segmentation that could affect it?

**Comment by ilijabojanovic** [comment]
Verified on mdcb and hybrid environments
