### ISSUE TITLE
feature: ability to use unique alias instead of policy id in jwt claims

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1531]
Feature

At present, I am required to use a policy_id in a `pol` claim within the JWT token. I then need to configure my IDP to attach this policy id to the claims of the JWT.

The problem is that if I have multiple policies, the policy_id is difficult to track/identify/understand within the IDP and manually referencing/checking up against Tyk's policies.

When creating a policy within Tyk, in addition to receiving a policy id, I would like the ability to specify a unique alias to identify the policy.

As such, irrespective of the generated policy id, I could use the alias within the IDP.

This would also assist with CI/CD, because I would not need to contact Tyk to figure out the generated policy id in order to setup JWT with my IDP.

**Comment by buger** [comment]
This is related to oAuth scopes support as well, when we will need to do the mapping between scope name and policy id, and after multiple policies will get merged.

**Comment by letzya** [comment]
https://github.com/TykTechnologies/tyk/issues/1834 that's the one
