### ISSUE TITLE
Body transform plugin not working

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#1535]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Body transform plugin does not affect request. But using 'test' function in Dashboard UI with the same input does work.

Example:

Set up an API targeting `http://httpbin.org` and use the endpoint designer to add the transform plugin to `/test`.

Using input:
```
    {
        "value1": "value-1",
        "value2": "value-2",
        "value_list": [
            "one",
            "two",
            "three"
        ]
    }
```

With template for transform plugin:
```
{
    "value1": "{{.value2}}",
    "value2": "{{.value1}}",
    "transformed_list": [
        {{range $index, $element := .value_list}}
            {{if $index}}
            , "{{$element}}"
            {{else}}
                    "{{$element}}"
            {{end}}
        {{end}}
    ]
}
```

Request does not get transformed when POSTing to /post. This is the (partial) result:

```
...
"data": "    {\n        \"value1\": \"value-1\",\n        \"value2\": \"value-2\",\n        \"value_list\": [\n            \"one\",\n            \"two\",\n            \"three\"\n        ]\n    }",
...
```

But works ok when testing in Dashboard UI endpoint designer:

```
{
    "value1": "value-2",
    "value2": "value-1",
    "transformed_list": [          
            "one"
            , "two"
            , "three"
    ]
}
```

**What is the expected behavior?**

For POST to http://httpbin.org/post to return 

```
{
    "value1": "value-2",
    "value2": "value-1",
    "transformed_list": [          
            "one"
            , "two"
            , "three"
    ]
}
```

as the `data` property in response, when using process described previously.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See process above.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.5.3

**Comment by buger** [comment]
@davegarvey just to clarify are you talking about request body transform or response body transform?

**Comment by davegarvey** [comment]
@buger it's for the request

**Comment by davegarvey** [comment]
Having gone back to look at this, I can confirm it is working ok. I misconfigured something!
