### ISSUE TITLE
SSL certificate pinning support

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1537]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Right now Tyk relies on system-level verification of server certificates, and right now the only way to control it is either use it or disable verification using `proxy_ssl_insecure_skip_verify`.

Certificate pinning is a technique which allows to bypass system level certificate check avoiding checking certificate root and etc, in exchange to directly checking server certificate fingerprint against whitelisted value. 
**What is the expected behavior?**
Similar to how we specify client upstream certificates, it should be possible to specify allowed **server** certificates. 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.5

**Comment by buger** [comment]
Here is the example of extending Dialer object to support pinning: https://medium.com/@zmanian/server-public-key-pinning-in-go-7a57bbe39438

**Comment by letzya** [comment]
We were asked to start with pinning with subjectPublicKeyInfo

**Comment by letzya** [comment]
`pinset`- `If more than one certificate or public key is acceptable, then the program holds a pinset`

**Comment by buger** [comment]
For the docs:

Extracting public certificate from SSL protected domain:
> openssl s_client -connect the.host.name:443 | openssl x509 -pubkey -noout

Gettig public key from existing certificate
> openssl x509 -pubkey -noout -in cert.pem  > pubkey.pem

**Comment by ilijabojanovic** [comment]
Verified
