### ISSUE TITLE
Authorized and keyless on same base URI but different paths not working

### ISSUE THREAD

**Issue by tandonraghav** [TykTechnologies/tyk#155]
In the previous version I was able to achieve Authorized and keyless authentication on different path with same base URI.

Listen path - /charge/v1 -- Authorized (key)
Listen Path - /charge/v1/notify - Keyless

But the same thing is not working in the current release 1.9. Can you please let me know what configuration is changed or how can i achieve this??

**Comment by lonelycode** [comment]
Are they on the same domain? It could be an ordering issue

**Comment by tandonraghav** [comment]
Yes both are same domain...actually localhost...but ordering how can i
maintain in tyk?

**Comment by mNantern** [comment]
Any news about that issue ? 

Because when you put a keyless in /users and an Authorized in /users/protected everyone can call /users/protected without security.

Seems really bad, no ?

**Comment by lonelycode** [comment]
What version are you using? Listen paths are sorted by size these days.

**Comment by mNantern** [comment]
tyk.linux.amd64-2.2.0.0

To be more clear I have a keyless API with only a listen_path:

```
"use_keyless": true,
...
"listen_path": "/mobile/v1/users"
```

And another one with whitelist:

```
    "auth": {
        "auth_header_name": "Authorization"
    },
...
   "white_list": [
                                {"path":"/users/peripherals","method_actions":{"GET":{"action":"no_action"}}},
                        ],
...
"listen_path": "/mobile/v1/",

```

In that case I can call /mobile/v1/users/peripherals without authorization

**Comment by lonelycode** [comment]
Hmmm, might be because it's keyless.

Why not use an ignored path for the auth endpoint?

**Comment by mNantern** [comment]
I have a 403 Forbidden when calling `GET /mobile/v1/users/peripherals` with the following:

```
    "auth": {
        "auth_header_name": "Authorization"
    },

"extended_paths": {
                    "ignored": [{"path":"/users","method_actions":{"POST":{"action":"no_action"}}}],
                    "white_list": [
                                {"path":"/users/peripherals","method_actions":{"GET":{"action":"no_action"}}},
                                ],
                    "black_list": []
                } 
...
 "listen_path": "/mobile/v1/",
```

**Comment by lonelycode** [comment]
It needs to be in your white-list too I think.

**Comment by mNantern** [comment]
The one that I'm trying to call (`/mobile/v1/users/peripherals`) is already in my whitelist but I have a 403:

```
curl --include -H "Authorization: Bearer 6185b0cd-7181-4222-821d-5979aee136e9" 'http://localhost:8082/mobile/v1/users/peripherals'
HTTP/1.1 403 Forbidden
Content-Type: application/json
X-Generator: tyk.io
Date: Tue, 30 Aug 2016 16:14:16 GMT
Content-Length: 50

{
    "error": "Requested endpoint is forbidden"
}
```

I can call `POST /mobile/v1/users` without authentication (and without adding it to the whitelist):

```
curl --include -X POST 'http://localhost:8082/mobile/v1/users'
HTTP/1.1 500 Internal Server Error
Content-Type: application/json;charset=UTF-8
Date: Tue, 30 Aug 2016 16:14:07 GMT
POSC_TRANSACTION_ID: TID=02b788ef-0d1d-4d3e-84df-d025e9b98b17
Server: Apache-Coyote/1.1
Vary: Accept-Encoding
X-Ratelimit-Limit: 0
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 0
Content-Length: 182

{
  "errorCode" : "[160830-18:14:08][TID=02b788ef-0d1d-4d3e-84df-d025e9b98b17]HttpMediaTypeNotSupported",
  "errorMessage" : "Content type 'application/octet-stream' not supported"
}
```

**Comment by mNantern** [comment]
So there are 2 issues here:

1. The one originally reported by tandonraghav, that still exists in tyk 2.2
2. Another one: if you have an "ignored" path then the white_list is not working anymore.

Do you want me to open an new issue for n°2 ?

**Comment by lonelycode** [comment]
Yeah, we'll take a look  at it... thanks 👍
