### ISSUE TITLE
Add option to ignore kid header in JWT validation

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1551]
**Do you want to request a *feature* or report a *bug*?**
feature, customer request: https://community.tyk.io/t/beginner-tyk-cloud-keycloak-kid-header/2472
**What is the current behavior?**
For JWT validation, "sub" claim will only be used for ID if the "kid" header is empty
https://github.com/TykTechnologies/tyk/blob/master/mw_jwt.go#L106
**What is the expected behavior?**
Add a config option to ignore the "kid" header if present use "sub" header instead. Required when JWT provider already uses kid header for its own purpose

**Comment by neterium** [comment]
Just FYI, Keycloak is an example of provider using a kid header in its generated JWT access tokens

**Comment by neterium** [comment]
Have to agree Buger :).
But if Tyk delegates the JWT generation to a 3rd party IDP (which is good practice I presume), it also has to accept that the kid header is already used to store a 3rd party identifier (which is also good practice then). Definitely a blocking issue for me :(.

**Comment by buger** [comment]
Added new `jwt_skip_kid` API definition boolean field to ignore kid sub.
