### ISSUE TITLE
JWT's with existing sub claim cannot access new APIs added to the policy

### ISSUE THREAD

**Issue by LuanvP** [TykTechnologies/tyk#1552]
**Do you want to request a *feature* or report a *bug*?**
Bug, related https://github.com/TykTechnologies/tyk/issues/1379

**What is the current behavior?**
JWT's with a sub claim that has been used before cannot access new APIs added to the policy they reference. They can continue to access old APIs, and if the sub claim is changed they can access the new APIs on the policy.

**What is the expected behavior?**
JWT should have access to the new API added to the policy

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Create API with JWT validation
- Add API to policy
- Call API with new JWT referencing that policy
- Create new API with JWT validation and add to policy
- Call new API with JWT using same "sub" claim as before
- Returns: 
{
“error”: “Access to this API has been disallowed”
}

**Comment by ilijabojanovic** [comment]
@LuanvP Do you have partitioned policy ? Please try with enforced access rights

**Comment by LuanvP** [comment]
@ilijabojanovic Yes with enforced access rights it works. Still a bug? Or expected behaviour?

**Comment by ilijabojanovic** [comment]
@LuanvP That is currently expected, let me discuss again with @lonelycode . In past release we changed UI for tokens attached to policy. E.g if you don't have anything selected for partitions on policy page, we will not enforce anything to tokens after we update policy e.g add new api definition.

**Comment by ilijabojanovic** [comment]
@LuanvP this is on master or stable?

**Comment by buger** [comment]
@ilijabojanovic aren't this is related to https://github.com/TykTechnologies/tyk/issues/1559 ?

**Comment by buger** [comment]
@LuanvP can you check if mitigation method described in #1559 helps with this JWT issue?

**Comment by dencoded** [comment]
@LuanvP @buger @ilijabojanovic after looking at last merges I believe this issue was fixed in fix provided for https://github.com/TykTechnologies/tyk/issues/1559

**Comment by dencoded** [comment]
Also, submitted PR https://github.com/TykTechnologies/tyk/pull/1572 with one more change not directly connected for this issue
