### ISSUE TITLE
A valid JWT token meet 403 error and cannot be authorized

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1553]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
A token itself is valid(totally sure), but when I access an API it got  403 error, and the logs in tyk_gateway looks like below.
```
tyk_gateway_1    | time="Mar 21 10:12:09" level=warning msg="JWT Invalid: Validation error. Jwt token validation failed with unknown error." 
tyk_gateway_1    | time="Mar 21 10:12:09" level=warning msg="Attempted access with invalid key." key="[JWT]" 
```
How ever, when I access the same endpoint with another already workable token to access the api, it of course get the 200 result. Then I changed back to previous token (which got 403 before), now it will get 200 result. 

It's quite wierd that the same token can be authorized as invalid first, then become valid which is the expected result, since the token is valid indeed.
  
**What is the expected behavior?**
The token can be authorized normally. I am just wondering why the same token get different behavior?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Steps see above. 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I am using tyk on-premise, and build with docker.
The current tyk_gateway version is v2.5.3

**Comment by hustshawn** [comment]
Since the token and behind key config have no problem. Is there any possible reason related to redis ? What the mechanism / process flow is?

**Comment by hustshawn** [comment]
It can also be reproduced with Tyk Cloud. As you can see from below code and logs, first one I generate a token and used it to call the API in Tyk Cloud API gateway, which I already configured the authentication. It will get 403 status.
```
python gen_token.py -env=uat -private_key=keys/private.pem  -client_id=i12345678 --test-api  -v

[INFO] - Access Token: 
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImkxMjM0NTY3OCJ9.eyJpc3MiOiJodHRwOi8vaWRwLXVhdC5pZnVuZC5jb20uaGsvIiwic3ViIjoiaTEyMzQ1Njc4IiwiaWF0IjoxNTIxNzA5NTE1LCJleHAiOjE1MjY4OTM1MTUsImF1ZCI6ImIyYiJ9.BiH0b_oLzWIqvMF8F2xfPDXwnBIqCiqtjzw3XzCjklHdXScN27m1gm2k3tK9hPEpNpEWknJUe8CneXBmalvnDOKqN0W8FyR5ats9wkAnrsto5NLeVPAWwhBlH_brsIkck5seCyAmp3rmTqKWNvEbfv8D1K1LX_Pd4u4FtJG3fI4Lb_BkhFz48sbTRP4rB0J7YgDoX6FCoiffAecR5aurLo7kLEz9dgD8irGG3a2VMh1cH0cPaEDyLQocY7D711_BtFiw_oEFGpUZ2c1MVB1nkBqCI6HHFpXI7ElWYZzXogz5vCWEZD39Z0H9H_tH6M8jOZ05A0uiEDnW1iIM-DkVvw

[INFO] - Requesting API to test token: https://lion-finance-hk.cloud.tyk.io/test/
[DEBUG] - Elapsed: 1.0
[INFO] - Status code: 403, Response: {
    "error": "Key not authorised"
}

[DEBUG] - Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImkxMjM0NTY3OCJ9.eyJpc3MiOiJodHRwOi8vaWRwLXVhdC5pZnVuZC5jb20uaGsvIiwic3ViIjoiaTEyMzQ1Njc4IiwiaWF0IjoxNTIxNzA5NTE1LCJleHAiOjE1MjY4OTM1MTUsImF1ZCI6ImIyYiJ9.BiH0b_oLzWIqvMF8F2xfPDXwnBIqCiqtjzw3XzCjklHdXScN27m1gm2k3tK9hPEpNpEWknJUe8CneXBmalvnDOKqN0W8FyR5ats9wkAnrsto5NLeVPAWwhBlH_brsIkck5seCyAmp3rmTqKWNvEbfv8D1K1LX_Pd4u4FtJG3fI4Lb_BkhFz48sbTRP4rB0J7YgDoX6FCoiffAecR5aurLo7kLEz9dgD8irGG3a2VMh1cH0cPaEDyLQocY7D711_BtFiw_oEFGpUZ2c1MVB1nkBqCI6HHFpXI7ElWYZzXogz5vCWEZD39Z0H9H_tH6M8jOZ05A0uiEDnW1iIM-DkVvw'}
```
However, when I use python requests to call the API with same token, it can pass the authentication.
```
root@b6028f0accfe:/workdir/utils# python
Python 3.6.1 (default, Jul  8 2017, 05:00:20) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
>>> url = 'https://lion-finance-hk.cloud.tyk.io/test/'
>>> headers = {"Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImkxMjM0NTY3OCJ9.eyJpc3MiOiJodHRwOi8vaWRwLXVhdC5pZnVuZC5jb20uaGsvIiwic3ViIjoiaTEyMzQ1Njc4IiwiaWF0IjoxNTIxNzA5NTE1LCJleHAiOjE1MjY4OTM1MTUsImF1ZCI6ImIyYiJ9.BiH0b_oLzWIqvMF8F2xfPDXwnBIqCiqtjzw3XzCjklHdXScN27m1gm2k3tK9hPEpNpEWknJUe8CneXBmalvnDOKqN0W8FyR5ats9wkAnrsto5NLeVPAWwhBlH_brsIkck5seCyAmp3rmTqKWNvEbfv8D1K1LX_Pd4u4FtJG3fI4Lb_BkhFz48sbTRP4rB0J7YgDoX6FCoiffAecR5aurLo7kLEz9dgD8irGG3a2VMh1cH0cPaEDyLQocY7D711_BtFiw_oEFGpUZ2c1MVB1nkBqCI6HHFpXI7ElWYZzXogz5vCWEZD39Z0H9H_tH6M8jOZ05A0uiEDnW1iIM-DkVvw"}
>>> 
>>> r = requests.get(url, headers=headers)

>>> print(r.status_code)
200
```

@lonelycode  @buger any idea about this ?

**Comment by buger** [comment]
Thank you for the debugging! Will check this today.

**Comment by hustshawn** [comment]
@buger Thanks. one more thing I noticed, as long as the token was valid ok, it will always pass in the future.

**Comment by hustshawn** [comment]
It feels like the token must be `activated` some way, and then workable. quite hard to understand what's going on underground.

**Comment by buger** [comment]
Are this tokens have the same or different `sub` ?

**Comment by hustshawn** [comment]
@buger  I do not quite understand what you mean `sub` same to what, in this case it same with kid. But `sub` should not be a matter that affect the token be valid or not.

**Comment by buger** [comment]
I see, the error itself coming somewhere from https://github.com/emanoelxavier/openid2go internals 🤔

**Comment by hustshawn** [comment]
@buger I have referred the issue to  https://github.com/emanoelxavier/openid2go . Hope someone in openid2go community can head out.

**Comment by buger** [comment]
openid2go itself does not show a custom error message, and in our fork, we can definitely extend it to get better error message https://github.com/emanoelxavier/openid2go/blob/99cabb451faff2d673301d6f9542ffd2184de280/openid/errors.go#L93

**Comment by hustshawn** [comment]
@buger Totally agree. The current error message is a bit confusing and may not realising what part is wrong.
