### ISSUE TITLE
Change policy on developers does not get picked up by slave gateways 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1554]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Developer subscribes to POLICY_1, his key works as expected.
An admin goes to dashboard>Portal management>developers and changes the policy to POLICY_2 which has different access.
Developer still has access to everything provided by POLICY_1 and nothing provided by POLICY_2
Make request in MASTER Gateway, nothing changes, still broken.
Go to key edit page, change policy to random policy and then back to POLICY_2
Everything works as expected, developer has access to everything provided by POLICY_2 and nothing POLICY_1.
**What is the expected behavior?**
When we update developer policy, selected policy should allow access to api's
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.5.3

**Comment by buger** [comment]
This happens only for "developers" or when you directly update key policy too?

**Comment by buger** [comment]
It actually happens for all key updates, not only related to policies. 

1) Keyspace changes get synced every 10 seconds
2) Once policy updated on dashboard we issue key space change event
3) One of the GWs receive it and delete key from redis, in theory flushing cache
4) When key is already deleted from redis, but still exist in memory cache in one of GWs, and you make request to this GW, it writes to redis “cached” key version
