### ISSUE TITLE
Dashboard: "Traffic activity by key" enhancements

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1556]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

"Traffic activity by key" shows nothing useful. In our session creations we set quotas, alias, tags.... none of this is viewable

**What is the expected behavior?**

This page should show actionable information. Right now I see a graph and the key hash.

This should show:

- key hash
- key alias
- tags
- all session meta-data 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.5.3

**Comment by bitsofinfo** [comment]
#1256

**Comment by bitsofinfo** [comment]
Note #1256 still does not seem to solve this, I take a hashed key that I see in the dashboard (1.6) from "activity by key", then go to "Keys" and put the hash into the search field, check the "this is a hashed key" and still get the error "Could not retrieve key detail" and "key doesn't exist"

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.
Thank you for supporting Tyk.
