### ISSUE TITLE
Allow max connection per host be greater then 100

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1560]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
While we allow control `MaxIdleConnsPerHost` using `max_idle_conns_per_host`, the top maximum `MaxIdleConns` is still 100, and not configurable. 

On high traffic environments, especially when upstream not that fast, this value can become a bottleneck. 
**What is the expected behavior?**
`MaxIdleConns` should be configurable via config
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.5

**Comment by dencoded** [comment]
also, while looking at performance I found that `"max_idle_connections_per_host"` doesn't have any default value so if it is not set explicitly in tyk.conf it will get http `Transport`'s default value which is `2`

also, we have that comment in https://github.com/TykTechnologies/tyk/blob/v2.6.1/reverse_proxy.go#L315 `// default is 100` which is not true, we don't set any default value (except pre-built docker images) - that was confusing to me while looking at code

so my suggestions are:

- document "max_idle_connections_per_host" and its benefits in docs and particularly in https://tyk.io/docs/deploy-tyk-premise-production/
- add `max_idle_conns_per_host` to out tyk.conf.example 
- don't set `MaxIdleConns` at all, leave it to be infinite, it won't grow to more than `max_idle_conns_per_host * upstreamHostsNumber` anyways
- set `MaxIdleConnsPerHost` to 100 explicitly if it wasn't set in config via `max_idle_conns_per_host`

**Comment by ilijabojanovic** [comment]
Verified
