### ISSUE TITLE
Cannot use context variable claims to access JWT token header claims.

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1563]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I am using OIDC, with JWT to access api. After api call passed the auth, tyk_gateway cannot extract the token claim in token header. eg. `kid` in my token 
```Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImkxMjM0NTY3ODAxIn0.eyJpc3MiOiJodHRwOi8vaWRwLXVhdC5pZnVuZC5jb20uaGsvIiwic3ViIjoiaTEyMzQ1Njc4MDEiLCJpYXQiOjE1MjE3OTM1MDcsImV4cCI6MTUzMTc5MzUwOCwiYXVkIjoiYjJiIn0.YOPiT4KHcRnwS6ZTtKutPsrRkSLRL_FtWYRE9vgDH-B_TQPABo4zophUvMV2wMZfESK_4KqsLKtLKz7dSM_yFmni66Ij9aUEs4991hc0u88OsXR6x5u35CWCmOnhXWFq2GMQZT79_QWC2Czr_lG0pUsbChWZKE6kLdSgQJEmfDB8IJqmyd9TGQvAn8HUPMtX3khusMXFf3AqSuU5YCvkPWS0MVzXpibCxSd0uVbRzRV-LrV4h5xf3FbCL7bXsLfXumYibtQDgFd4yPhsSM9rbJjO9ogrUPFy4rwwbvIiFcAMordOQb9iEeZgxuiPlkjVCvX7EnTEP9435eVbjcWFpVFcFDGyUZF56iozqP27I7XwINjAm5PBFM7FieayI9i5T_RU-dpFbqYoTwvQj-XNxRxYC9kH4qaebCRHGVcUGtiYMG9biG3Z7Obt1ym2FuM1oND9mLpCFxaC4j587iXRyycSzACpktLTlqFJoJYINLgS27JDRJ8fSjsj6Wp8-oW7mn1kERg2G0P4o83vONV6Vk-wxhkAQZVnUldsUNOPLEfxFB8V8oqUrAhogmi0uCAqWtbpUY6sdgnjHIaxG0rUvhgeEjVSBWI8Wz75MBGTSfQs7atS7EKUsf-kc8532MpQzGbkPQAROIXa6RUu2UHu7W2QUUxMcSpwtkoCTUsdM7I```

As can be find in doc, `jwt_claims_CLAIMNAME - If JWT tokens are being used, then each claim in the JWT is available in this format to the context processor.`, seems like not all claims are parsed, only the claims in the token body.

**What is the expected behavior?**
Can access the token header claim from context variable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create OIDC auth api, log the output from `jwt_claims_TOKEN_HEADER_CLAIM`.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
tyk  v2.5.3

**Comment by buger** [comment]
Fix should be included into 2.5.4 aimed to next week

**Comment by iamtour** [comment]
@buger In the same case of above, we also fail to get $tyk_context.jwt_claims_iat and $tyk_context.jwt_claims_exp, please advise, thanks.
