### ISSUE TITLE
[PUT] tyk/apis/ creates `.json`

### ISSUE THREAD

**Issue by johnjelinek** [TykTechnologies/tyk#157]
I don't think it should create a `.json` file if you PUT without providing an api-id to `tyk/apis/{api-id}`. If I look in `apps/` I see just a `.json` file (no filename, just file-extension).

**Comment by mvdan** [comment]
Thanks for reporting! Posting a fix soon.

**Comment by ilijabojanovic** [comment]
Verified @buger approved for merge

**Comment by mvdan** [comment]
Shouldn't comments like these go in the PR, to not bother the original poster?

**Comment by ilijabojanovic** [comment]
@mvdan yes, my mistake
