### ISSUE TITLE
Enhancement: Support Automatic Update of Geo-IP Database from within Tyk

### ISSUE THREAD

**Issue by ghost** [TykTechnologies/tyk#1574]
**Suggested enhancement:**

Support Automatic Update of Geo-IP Database used by the "Geographic Distribution activity report" from within Tyk.

The update URL should be configurable along with the update interval. The update routine could then use the path determined by the "geo_ip_db_path" parameter within the tyk.conf file to determine the destination location to place the new database.

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.
Thank you for supporting Tyk.
