### ISSUE TITLE
feature: configurable api upstream access via a proxy server

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1595]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
In highly-secure environments, where a gateway has no direct internet access, or needs to reverse-proxy to an external upstream endpoint, this is not possible unless the request is sent via a proxy-server.

By setting a system-level environment variable on the gateway machine, this should allow the gateway to use the proxy server for any HTTP requests: 

```
HTTP_PROXY=http://proxyIp:proxyPort
HTTPS_PROXY=https://proxyIp:proxyPort
```

Unfortunately, the downside to this, is that ALL traffic will be routed through that proxy server. This means that you will need to ensure that the dashboard, possibly redis also, is available via the proxy server, as well as all internal APIs.

Breaking this down further, it is be possible to tag APIs, where the upstream is external. That way, sharded gateways are the only gateways who need the above-mentioned environment variable. The dashboard will still need to be accessible via the proxy server however.

All of the above, is a workaround.

**What is the expected behavior?**
Given the above, it would be really useful to be able to configure a proxy-server on a per-api basis (within the api-definition).

This would allow multiple proxy servers to be used, depending on the api definition. 
We would not need to use above-mentioned environment variable either.
The gateway will also be able to talk to dashboard / other services as normal.

**Comment by buger** [comment]
Note that setting HTTP_PROXY affects only HTTP or HTTPS traffic, redis is not affected. But dashboard yes.

**Comment by asoorm** [comment]
Just thinking out loud here - will we need to support proxy auth?

https://tools.ietf.org/html/rfc7235#section-3.2
https://tools.ietf.org/html/rfc7235#section-4.3
https://tools.ietf.org/html/rfc7235#section-4.4

**Comment by matiasinsaurralde** [comment]
Sounds like an interesting feature, would it be helpful to use the `Proxy` field, from `http.Transport`? See [here](https://golang.org/pkg/net/http/#Transport).

**Comment by buger** [comment]
At the moment we can support only what Go stack supports. Note that for example for basic auth it is quite easy, by adding `Proxy-Authorization` header to your request, which can be added via endpoint designer.
