### ISSUE TITLE
Method transform not working when combined with URL rewrite

### ISSUE THREAD

**Issue by biancarosa** [TykTechnologies/tyk#1598]
**Do you want to request a *feature* or report a *bug*?**
I wanna report a bug.

**What is the current behavior?**
When I combine method transform + url rewrite, the method transform does not work.

**What is the expected behavior?**
The method transform is supposed to work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create a GET endpoint that rewrites to a another endpoint (listen to get and map to http://httpbin.org/post).
2. Add method transform from GET to POST.
3. Test - not working - method not allowed.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tested in Tyk Cloud (Dashboard v1.5.4) and locally with Tyk Dashboard 1.5.4.

**Comment by lonelycode** [comment]
You may need to put the method transform to trigger on the rewritten URL instead of the original one.

**Comment by biancarosa** [comment]
Thanks for the answer @lonelycode!

Apparently the issue wasn't really the combination of the two transformations. but the fact that I was redirecting to a URL that returned me a "Location" header and when the http client retried the request, it retried against the actual API Url and not through the gateway.

Example:

`curl http://tyk.gateway:8081/my-post-api/redirect-to?url=http://httpbin.org/post -v`

> GET /my-post-api/redirect-to?url=http://httpbin.org/post HTTP/1.1
> Host: tyk.gateway:8081
> User-Agent: curl/7.47.0
> Accept: */*
> HTTP/1.1 302 Found
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Origin: *
> Content-Length: 0
> Content-Type: text/html; charset=utf-8
> Date: Mon, 09 Apr 2018 20:46:15 GMT
> Location: http://httpbin.org/post
> Server: meinheld/0.6.1
> Via: 1.1 vegur
> X-Powered-By: Flask
> X-Processed-Time: 0
> X-Ratelimit-Limit: 0
> X-Ratelimit-Remaining: 0
> X-Ratelimit-Reset: 0
> Connection: close

`"method_transforms": [
  {
       "path": "redirect-to",
       "method": "GET",
      "to_method": "POST"
   }
 ]`

I'm gonna try the same request using JS, but apparently Postman/Insomnia clients use the Location header to make another request that doesn't hit the gateway and goes straight to httpbin/post, doing a GET request to a endpoint that only accepts POST requests.

**Comment by maciejwojciechowski** [comment]
verified

**Comment by anx-hnezbeda** [comment]
Issue is not fixed. Tested with 2.9.2.1 and 2.9.3-rc3 - https://hub.docker.com/r/tykio/tyk-gateway/tags


```
    "extended_paths": {
          "url_rewrites": [
            {
              "path": "/test-url",
              "method": "GET",
              "match_pattern": "/test-url",
              "rewrite_to": "https://webhook.site/aed905a7-3035-45ba-ad9a-11eaf424bf3f",
              "triggers": []
            }
          ],
          "method_transforms": [
            {
              "path": "/test-url",
              "method": "GET",
              "to_method": "POST"
            }
          ]
        },
```

**Comment by anx-hnezbeda** [comment]
It appears that this works as expected since 2.9.3
