### ISSUE TITLE
Cache conflicting with URL Rewritting

### ISSUE THREAD

**Issue by thomas-barthelemy** [TykTechnologies/tyk#160]
I have an endpoint looking like aaa/bbb that is called as aaa/bbb?c=d
This endpoint have 2 things enabled: URL rewriting `aaa/bbb?(.*)` => `ccc?ddd=eee&$1`

This works without issue, but if I add Caching, the URL Rewritting is not done anymore (end server receives a request on aaa/bbb).

**Comment by lonelycode** [comment]
Ok, thx for pointing out - I think its because we modify the opaque URL while the cache operates on the path. Might need to be bright in line.

**Comment by lonelycode** [comment]
Ah, on second look it's because the cache operates before the URL rewriter does (and effectively short circuits any further middleware ops), we need the cache and URL rewriter to be flipped around in terms of order of operation. Should be an easy fix :-)
