### ISSUE TITLE
Hash_keys: true to make 'keys' visible? and cannot find the previously created keys back if not copied the key to somewhere

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1603]
**Do you want to request a *feature* or report a *bug*?**
not even a bug, a tricky and terrible design
**What is the current behavior?**
even set to hash_keys: true as your dashboard tips indicated, the keys list not show!!!

**What is the expected behavior?**
Give me a way to list the keys!!! at least I can find the keys I created back
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
first, hash_keys: false in tyk.conf, create a key, you cannot find the key in dashboard, ... anyway OK.
then, updated hash_keys: true in tyk.conf, restart tyk, find keys in dashboard
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all latest docker images

**Comment by buger** [comment]
Hello! Well, you can't mix hashed and non-hashed keys. The whole idea of key hashing is to disallow lookups for user keys, even in cases when Redis or Gateway API is compromised.

If you want to migrate all your keys from non-hashed to the hashed environment, you first need export all your keys, turn on key hashing, and import previously exported keys. The other way migration is not supported for obvious reasons.

Hope it clarify things.
