### ISSUE TITLE
Even a deleted key still in effect? Then where the key exist? It cannot be found on both Redis and Mongo

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1604]
**Do you want to request a *feature* or report a *bug*?**
bug?
**What is the current behavior?**
Created a key to have rate limit to an API, after configuration , the rate limit in effect. But after I deleted the key, the effect still in effect even if I restart tyk, it's still in effect. 
However, I tried to find where the key exists, it cannot be found on both Redis and Mongo.
**What is the expected behavior?**
Give me a way, ether if the key deleted, the effect gone, or I can find where the key lives .
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
latest

**Comment by buger** [comment]
Hello! 

Can this issue be related to the previous ticket, which caused confusion when you switched from hashed to non-hashed version?

**Comment by hustshawn** [comment]
The problem is if I use FLUSHALL cleared the redis, the effect of the key still exist, but cannot find the key.

**Comment by buger** [comment]
Do you see this key in dashboard analytics? 

The only reason when key still can be there, is some in-memory cache which Tyk can hold for some time, but it should be flushed on process restart (and you already did it). 

Also when you say that key exists, what you mean here, how your API definition looks like (do you use multiple auth methods or similar), how is your key looks like?

Thank you.
