### ISSUE TITLE
Dashboard API Designer: Query string not allow in Uptime Test url

### ISSUE THREAD

**Issue by jussik** [TykTechnologies/tyk#1606]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**  
Adding an Uptime Test through the dashboard API designer does not allow query parameters in the url. It is possible to add the query parameter through the raw API definition without issue and have it function as expected, so it just looks like a UI bug in the designer.

**What is the expected behavior?**  
API designer should allow Uptime Test urls to contain query parameters.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  
In API designer:
- Uptime Tests tab
- Add new url
- Attempt to set url to "http://host/page?param"
- Causes the following error: "Please enter a valid URL value (i.e. http://)"

Setting the url to "http://host/page", however, is fine.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.6.0

**Comment by asoorm** [comment]
<img width="376" alt="screen shot 2018-05-15 at 14 53 14" src="https://user-images.githubusercontent.com/1465130/40060986-c6c066ee-584f-11e8-9a5f-93ef1856c6b4.png">

**Comment by ilijabojanovic** [comment]
Verified
