### ISSUE TITLE
Add target path when using service discovery

### ISSUE THREAD

**Issue by msheldonfl** [TykTechnologies/tyk#161]
Typically service registries will store and return the host address and port, but we need to proxy an api to a particular target path.  For example:

myapi.mytykserver.com/myapiresource/* > [discovered host]/api/*

There needs to be a way to append the literal string (example: "/api/") to the targets retrieved from service discovery.

**Comment by JosephEarl** [comment]
:+1: since it is possible to set target URLs that include a path, this is needed to use the same path when using service discovery.
