### ISSUE TITLE
Do not track plugin does not work as expected

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#1610]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we enable "Do not Track" plugin on endpoint designer, all analytics for endpoint is still recorded
**What is the expected behavior?**
When we enable "Do not Track" plugin on endpoint designer, all analytics for endpoint should be ignored.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api definition
2. On Endpoint designer add some endpoint and enable "Do Not Track" plugin
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master and stable

**Comment by asoorm** [comment]
This issue should have been fixed already. https://github.com/TykTechnologies/tyk/issues/1547

**Comment by ilijabojanovic** [comment]
Verified
