### ISSUE TITLE
Add ability toggle for "strip_listen_path" in the Dashboard

### ISSUE THREAD

**Issue by jjensen90** [TykTechnologies/tyk#162]
I spent awhile trying to figure out how to strip the listen path so it wasn't proxied all the way to the backend service, but I haven't found anywhere to do it in the dashboard. I had to create a Tyk API definition file and import it with `strip_listen_path` to true to get it to change. This was very confusing and it also seems that counterintuitive that `strip_listen_path` is `false` by default (all other API gateways I tested either offered the option to strip at the time of creation or defaulted to stripping it). It would be really great if there were a configuration option on the API config page in the Dashboard to choose whether to strip the path or not.

**Comment by ax-nathan** [comment]
+1 that having `strip_listen_path=false` as the default is counterintuitive and probably costing you adoption as it provides immediate frustration.

**Comment by ScottGuymer** [comment]
+1 I immediately struggled with this when testing tyk out for the first time.

Other than this im super impressed with the OOTB functionality.

**Comment by lonelycode** [comment]
This has now ben added in the next version of the dashboard.

**Comment by ScottGuymer** [comment]
When is this released?

**Comment by lonelycode** [comment]
Soon? :-) 

We're in the middle of quite a large overhaul, so it may be a while.
