### ISSUE TITLE
Add support for JWEs as authentication

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1621]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Tyk currently supports using JWTs for authentication on APIs. 

The JSON token is signed to verify it's author but has no encryption applied to it.

**What is the expected behavior?**

As part of the JWE spec https://www.rfc-editor.org/rfc/rfc7516.txt the JSON token can be signed and then encrypted to obsfucate it's contents.

**Comment by joshblakeley** [comment]
The approach for this either requires havign an additional middleware specifically for JWE as the current JWT library does not extend to token encryption.

Another option is to redesign the existing JWT middleware around another library such as https://github.com/square/go-jose which encompasses both specs. However, caution should be made to ensure this does not break back compatibility with existing tokens.

**Comment by rahulnike646** [comment]
Any updates on this?

**Comment by l3ender** [comment]
We would also be interested in this. Is it looking to be included in an upcoming release?

**Comment by bondhan** [comment]
Hi, is JWE supported by tyk?
