### ISSUE TITLE
Avoid/replace JSON serialization for sessions

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1623]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Currently when a session is created, we serialize the `SessionState` as JSON and store it on Redis. Using an alternative serialization method could improve Redis memory usage and also speed up read operations ([this article](http://adamnengland.com/2012/11/15/redis-performance-does-key-length-matter/) mentions that using smaller keys results in faster reads).
When a session is retrieved from Redis, we deserialize the object and so on.

**What is the expected behavior?**
It should be possible to switch the serialization format and get a better performance, also in combination with a fix for #1622.
I've been running an experiment on replacing JSON with Protocol Buffers (as we already have these definitions in place, we use them for rich plugins). This is how we currently store a session (note the key length):
<img width="886" alt="redis_key_json" src="https://user-images.githubusercontent.com/20110/39423998-ecb366f8-4c74-11e8-83fb-774f999ff55b.png">
This is after switching to PB (key length is around 4 times smaller):
<img width="881" alt="redis_key_pb" src="https://user-images.githubusercontent.com/20110/39424016-fd0565ec-4c74-11e8-9079-af410f301c6d.png">

I ran a few benchmarks disabling the local session cache.
Using PB:
```
% boom -H 'Authorization: 59f358a13565200001116d6f02c5e14d780847ad8e7161f35891aac5' -n 100 -c 2 http://localhost:8080/quickstart/
Summary:
  Total:	0.0408 secs
  Slowest:	0.0046 secs
  Fastest:	0.0005 secs
  Average:	0.0008 secs
  Requests/sec:	2451.8248
  Total data:	600 bytes
  Size/request:	6 bytes

Status code distribution:
  [200]	100 responses

Response time histogram:
  0.001 [1]	|
  0.001 [78]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.001 [13]	|∎∎∎∎∎∎
  0.002 [6]	|∎∎∎
  0.002 [0]	|
  0.003 [0]	|
  0.003 [0]	|
  0.003 [0]	|
  0.004 [0]	|
  0.004 [0]	|
  0.005 [2]	|∎

Latency distribution:
  10% in 0.0006 secs
  25% in 0.0006 secs
  50% in 0.0006 secs
  75% in 0.0008 secs
  90% in 0.0013 secs
  95% in 0.0014 secs
  99% in 0.0046 secs
```

Using JSON:
```
% boom -H 'Authorization: 59f358a13565200001116d6f1a460da9d96b444991bd85be7f4a1e47' -n 100 -c 2 http://localhost:8080/quickstart/
Summary:
  Total:	0.0537 secs
  Slowest:	0.0066 secs
  Fastest:	0.0006 secs
  Average:	0.0011 secs
  Requests/sec:	1861.7515
  Total data:	600 bytes
  Size/request:	6 bytes

Status code distribution:
  [200]	100 responses

Response time histogram:
  0.001 [1]	|
  0.001 [66]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.002 [29]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.002 [2]	|∎
  0.003 [0]	|
  0.004 [0]	|
  0.004 [0]	|
  0.005 [0]	|
  0.005 [0]	|
  0.006 [0]	|
  0.007 [2]	|∎

Latency distribution:
  10% in 0.0006 secs
  25% in 0.0007 secs
  50% in 0.0008 secs
  75% in 0.0013 secs
  90% in 0.0014 secs
  95% in 0.0017 secs
  99% in 0.0066 secs
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?** All

**Comment by asoorm** [comment]
`using smaller keys results in faster reads` makes sense. but in example provided above, we are not using smaller keys, but smaller values at the given key.

So the performance increase is more likely due to faster deserialisation of PB msg, and smaller payload being sent from redis to Tyk.

Few other considerations

* A tool for development / debug purposes to read / deserialize the pb msg.
* PB / JSON to be configurable, allowing users to select between the two
* So that non-destructive, pb encoded keys should have unique redis key prefix. e.g. `apikey-pb-XXXX`

**Comment by matiasinsaurralde** [comment]
> using smaller keys results in faster reads makes sense. but in example provided above, we are not using smaller keys, but smaller values at the given key.

Right, sorry for the confusion, the idea is to use PB for the reasons you've mentioned.

**Comment by matiasinsaurralde** [comment]
For reference, this branch modifies the session manager to use PB, I've tested it under a few scenarios and seems to work fine: https://github.com/matiasinsaurralde/tyk/tree/protobuf-sessions
