### ISSUE TITLE
feature: configurable HTTP header for API version expiry. With view to supporting Sunset header

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1626]
At present, we apply a custom expires header for when an API version expires. `X-Tyk-Api-Expires`.

```
X-Tyk-Api-Expires: Tue, 08 May 2018 00:00:00 UTC
```

There is an IETF draft Sunset HTTP response header field specifically for this purpose.

```
Sunset: Tue, 08 May 2018 00:00:00 UTC
```

https://tools.ietf.org/id/draft-wilde-sunset-header-03.html

**Comment by dret** [comment]
it's great to see this! please keep me updated on implementation, if that's ok for you. i'd like to start tracking implementations so that i can push the draft towards RFC status. also, if you have any comments or feedback, please feel free to raise them here: https://github.com/dret/I-D/issues

**Comment by dret** [comment]
the current draft is about to expire. i am submitting a new one this week. i am planning on linking to this issue in the implementation section of the draft. it is nothing formal (no obligation on your side), but simply a way to keep track of how and where the draft is being used. it helps with getting the draft adopted as a standard in the end. https://tools.ietf.org/html/draft-wilde-sunset-header-04#section-7

**Comment by buger** [comment]
@asoorm @dret so basically it is just about renaming our header, right?

**Comment by dret** [comment]
On 2018-05-07 14:42, Leonid Bugaev wrote:
> @asoorm <https://github.com/asoorm> @dret <https://github.com/dret> so 
> basically it is just about renaming our header, right?

that depends on how your header is defined and used. if it is defined in 
the very same way, then it may just be a renaming exercise.
