### ISSUE TITLE
feature: auto-populate json schema when importing from OAS

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1627]
Tyk can import API definitions from Open API Specs.
OAS can contain schema validation information.

There are converters available which are able to convert between OAS and JsonSchema.

As part of the OAS import, we could convert the OAS validation schema (if present) to a JsonSchema, and automatically enable that middleware within Tyk.

**Comment by philsturgeon** [comment]
Awesome! The package I mentioned to convert OpenAPI Schema Objects to JSON Schema Objects is https://github.com/mikunn/openapi-schema-to-json-schema
