### ISSUE TITLE
Missing documentation on /api/portal/policies API

### ISSUE THREAD

**Issue by veger** [TykTechnologies/tyk#163]
Hello,

I am trying to create policies dynamically and add users to them.
In the dashboard I can easily create a policy and assign it to a user (key). But doing this programmatically is quite hard as documentation on this matter seems to be missing.

The only thing I found on the existance of the /api/portal/policies API is http://support.tyk.io/support/solutions/articles/5000661922-can-i-create-a-policy-programatically-

When Googling on _tyk "/api/portal/policies"_ this was the only hit (besides some (old?) roadmap on trello.com)

The support page does not really explain how to use this API. I noticed that using GET on this URL indeed returns all policies. But (additional) information to assign a key to a policy, check if a key has a certain policy, etc. seems to be missing completely.

Regards,

**Comment by lonelycode** [comment]
We neglected to add this to the docs, I guess we should migrate it in from the knowledge base.

To add a policy to a key, simply use the keys API PUT:

https://tyk.io/advanced-api-v0-9/api-keys/#update-a-key:84dc085e9f591e43ce6b2a50cfcb1584

And add the `apply_policy_id` field with the policy ID (I can see it's missing from the object description in the docs, we need to add this), here's an up-to-date key object model (regular API docs):

https://tyk.io/v1.9/rest-api/api-key-management/#add-update-keys:62eb43c854cb923da811a9fa4c845be3

To check if a key has a policy, just GET the key, it's right there in the object. 

You're right though, the object model is a little out of date in the advanced docs :-/

If you see anything or want to add it, the docs are publicly available on GH to edit: https://github.com/lonelycode/tyk-io-site-content

**Comment by kohrVid** [comment]
Hi Maarten,

Fortunately, quite a lot has changed since this issue was raised over a year ago and our site now features documentation regarding the [management of policies using the Dashboard API](https://tyk.io/tyk-documentation/tyk-dashboard-api/token-policies/). Are you still having trouble with any of this or would it be all right if we closed this issue?

Kind regards,
Jess

**Comment by veger** [comment]
It is alright to close the issue, thanks
