### ISSUE TITLE
Endpoint Designer - Mock Response gets auto-created

### ISSUE THREAD

**Issue by znystr** [TykTechnologies/tyk#1630]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Unfortunately cannot figure out how to reproduce it now, but when we were editing an API, modifying things like paths in slug, white list, and/or url rewrites, with the UI or via the Raw API Definition page, a Mock Response piece was showing up in our POST section.  We had hit the X on the Mock Response to remove it, and then clicked Update.  It would seemingly be gone, only to show up again after we've edited one of the things listed.
Eventually we made removing Mock Response the only thing we updated, and after that the change stuck and Mock Response doesn't get recreated.
**What is the expected behavior?**
Mock Response not get created on its own (seemingly), and also that it stays deleted when we X it out.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Cannot reproduce currently...
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.6.1 - we're using Hybrid.

Thanks.

**Comment by znystr** [comment]
Ran into this again and figured out how to reproduce the auto Mock Response creation.

First I created a new API, then went to RAW API DEFINITION to edit 3 places, adding (.*) to the end of all 3:
1) "version_data" -> "versions" -> "Default" -> "extended_paths" -> "white_list": [ { "path": "/slug/\\d.\d/path(.*)"
2) "version_data" -> "versions" -> "Default" -> "url_rewrites": [ { "path": "/slug/\\d.\\d/path(.*)"
3) "version_data" -> "versions" -> "Default" -> "url_rewrites": [ { "match_pattern": "/slug/\\d.\\d/path(.*)"

After saving with Update, under Endpoint Designer my GET has the extra Mock Response plugin added to it.

When I exported the API with Mock Response and do a diff, I notice this section got updated from:
                            "method_actions": {
                                "GET": {
                                    "action": "no_action",
to
                            "method_actions": {
                                "GET": {
                                    "action": "reply",
                                    "code": 200,

(side note, "proxy" -> "transport": { "ssl_ciphers": null   also got updated from null to [] )

Attaching 2 files (switched from .json to .txt), the initial one and the export I made after making my changes.

Thanks.
[test_mock_response_init.txt](https://github.com/TykTechnologies/tyk/files/2031921/test_mock_response_init.txt)
[test_mock_response_post.txt](https://github.com/TykTechnologies/tyk/files/2031922/test_mock_response_post.txt)

**Comment by bitsofinfo** [comment]
Any update on this? major pain

**Comment by buger** [comment]
@znystr may I wonder why you adding *. to the end of url? From what I remember it should work like this without it. Also why you are using RAW API Editor for this? Can you confirm that when using UI there is no such bug?

**Comment by buger** [comment]
@lghiur seems like some UI bug, when `no_action` translated to `no_reply`.

**Comment by lghiur** [comment]
I have just raised a PR with a fix on this, will keep u posted when this will be released. 
Thank you for raising up this issue.

**Comment by ilijabojanovic** [comment]
Verified
