### ISSUE TITLE
Using tyk behind proxy

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#165]
I'm trying to set up tyk within Docker behind a proxy, but I don't know where to make the configuration changes.
Tyk must use proxy authentication if it wants to proxy other requests to the WWW.

If I try to create a key for example, I'll get: Failed to save new session object to Tyk: Failed to create key: Post http://ambassador_1:8080/tyk/keys/create: **dial tcp 172.17.0.2:8080: getsockopt: connection refused**

**Comment by lonelycode** [comment]
The ambassador error is telling - docker compose is not very consistent when assigning container names across versions and operating systems. 

Do a docker ps to see what docker containers are running and what ports, then rename them as appropriate in your compose yaml file.

Then you'll be able to create a key.

Tyk hasn't got any configuration params to work with another proxy.

**Comment by senj** [comment]
Ok that was great thank you!
But I think I have a real proxy-problem now   
http: proxy error: dial tcp 54.175.222.246:80: i/o timeout"

If I access the ip directly via browser, it works.

**Comment by lonelycode** [comment]
Can you access it directly from within the container?

**Comment by senj** [comment]
Ok I changed names of dashboard and gateway and the first error got solved.
Do I have to change the other names too? There is no nameing in docker-compose.yml (I'm using the quickstart one)

I tried accessing the address from within gateway and ambassador (which one do I have to use?) but in both cases: connection timeout.

**Comment by lonelycode** [comment]
No you shouldn't have to do anything else except make sure that the the ambassador is referencing the correct names for the dashboard and gateway and that the gateway and dashboard can see the ambassador (if it's name is different).

You will also have to change the portal data to make sure the proxies all work for the portal (if you are using it, this is set in the dashboard APIs list as per the docker setup guide).

I was asking, if you open a bash shell in the gateway docker container, can you ping / curl your API? It might be an issue with the networking setup of the containers themselves.

**Comment by senj** [comment]
1) Where do I see the references that ambassador has?
2) I changed the names in portal data.
3) Sorry if that wasn't clear, I tried curling my API and I got connection timeout.
My gateway container exposes ports 0.0.0.0:8080->8080/tcp, 0.0.0.0:80->8080/tcp, the ambassador container exposes none. (?)

**Comment by lonelycode** [comment]
1) In the compose.yml ambassador needs to point at the right containers, this line: `command: "-name tykquickstart_tyk_gateway_1 -name tykquickstart_tyk_dashboard_1"`

3) This error: `http: proxy error: dial tcp 54.175.222.246:80: i/o timeout` implies that the gateway (Tyk) cannot reach this IP address from within it's container. To test this theory, you should open a shell *in* the container to try the curl command to your *raw* api, not Tyk, this will emulate what Tyk trying to do, if you get a timeout from curl *within* the container, then the networking of docker is the problem. If not, then it's something else.

Finally, as I mentioned earlier: Tyk does *not* support proxy authentication on outbound requests. It assumes a clear route to the host.

**Comment by senj** [comment]
Yes this is what I've done.
If I curl from within the gateway container to my raw api, I'll get a timeout.
If I set ENV for http_proxy/https_proxy (although tyk won't work with those proxy settings) I recieve curl: (5) Could not resolve proxy: url of my proxy

**Comment by lonelycode** [comment]
There you have it, there's a problem with how your containers are configured. It's not a Tyk problem, docker can't see your API, in fact, applications in the container can't see the internet as a whole.

Not sure how to address that, as I've never seen it before, what OS/Docker environment are you running?

**Comment by senj** [comment]
Ok thank you for your help so this seems to be a firewall problem. I'll ping back if I got it solved. Thank you very much.
