### ISSUE TITLE
Target_url with Service Discovery

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#166]
Hello,

if I'm using Service Discovery to resolve my host and port, how do i define the target url?
Is it a relative path to the resolved host, or is there any placeholder I can set?

Greetings..

**Comment by lonelycode** [comment]
Take a look at the [tests](https://github.com/TykTechnologies/tyk/blob/master/service_discovery_test.go#L7), they provide the clearest examples of settings vs. SD return types. 

The target URL is assumed to be root at the moment (`/`), there's another ticket requesting being able to tag on a target URL to the discovered host.

Depending on your configuration you could have the SD system return a full set of target URLs with route info as a list, then you don't need to use the system's construction capabilities (which don't use a target route).

**Comment by senj** [comment]
Ok, nice!
