### ISSUE TITLE
Wrong Endpoints in Dashboard

### ISSUE THREAD

**Issue by ChGui** [TykTechnologies/tyk#167]
Hi,

I am currently doing some tests and there is something curious in the dashboard.
For a same url of my API, I have 2 endpoints in reporting: 1 for successful requests and 1 for requests in error:
Endpoint    Requests    Successful  Errors  Last Access
/api/device/TEST    1,804   0   1,804   23 minutes ago
/ws-test/api/device/TEST    210 210 0   21 minutes ago

As you can see, it is in fact the same url, just the main context is missing in case of error.
For information, Errors are mainly a rate limit exceeded.

Is there a problem in my configuration or a bug ?

Thanks,
Guillaume.

**Comment by lonelycode** [comment]
Do you have `strip_listen_path` enabled? It looks like the error reporter (it's a system error, not a proxy error), is using a different path, which is why you might be getting that.

**Comment by ChGui** [comment]
Yes, this parameter is set to true. 
Can I change it through the dashboard? Or Should I use the REST api?

For information, if I set /ws-test in listen path, I have now //api/... in errors entry points. :)

**Comment by lonelycode** [comment]
Set your listen path so it's like this: 

`/ws-test/`

And it will strip properly.

**Comment by ChGui** [comment]
I've tried several things, but except if I set listen_path to /, I always have curious pathes in case of error.

What I want to do is to listen /ws-test/ and redirect to http://ip:port/ws-test

With strip_listen_path:
- listen path set to /ws-test/ and target url to http://ip:port/ws-test
- endpoints=/ws-test/api/device/TEST for success and /api/device/TEST for errors

Without strip_listen_path:
- listen path set to /ws-test/ and target url to http://ip:port.
- endpoints=/ws-test/api/device/TEST for success and //ws-test/api/device/TEST for errors

**Comment by lonelycode** [comment]
That's going to cause problems, suggest you change the listen path to something else as I think the path stripping is malfunctioning because it doubles up

**Comment by kohrVid** [comment]
Hi Guillaume,

I'm sorry to hear that you were having trouble with this feature in the Tyk Dashboard last year. Did Martin's suggestion help at all? If so, would it be all right if we closed this issue on Github?

Kind regards,
Jess

**Comment by ChGui** [comment]
At this time, I was testing several API Management products. So no, I didn't succeed to do what I wanted and didn't play with Tyk since that time.

So you can close it if you think now it is working but I really think that there was a potential problem last year.
