### ISSUE TITLE
JWT validation error: Token is not valid yet - Unable to cope with distributed system clock skew

### ISSUE THREAD

**Issue by catdevnull** [TykTechnologies/tyk#1670]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

*JWT validation fails with error: JWT validation error: Token is not valid yet*.

Due to the nature of distrusted systems it is expected that despite best efforts you can end up in a situation with clock skew between the issuing party (An OpenID/OAuth provider) and the validating party (Tyk).

Currently Tyk does not allow for clock skew. This means that in certain circumstances Tyk can reject requests to API endpoints secured with JWT with the error Token is not valid yet. This occurs due to the clock on the Tyk server being behind the clock on the Identity Provider server.

It's worth pointing out that as we control both the Tyk Gateways and the Identity Provider we have all servers ntp sync'd from the same ntp server.

For us this issue is intermittent, and only present in API requests that have very low latency. We believe this is because the clock skew between servers is incredibly low (milliseconds) but still causing issues.

**What is the expected behavior?**

Standard practice is to allow for configurable allowable clockskew. For example the .NET framework JWT validation allows for a full 5 minutes of clock skew.

I can see from configuration that HMAC clock skew is already available however there is no setting for JWT clock skew.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1) Create a JWT token with a start time 1 second in the future
2) Attempt to access an endpoint on Tyk secured with JWT validation

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Will apply to all versions of Tyk

**Comment by buger** [comment]
Hi! I believe I managed to fix this issue https://github.com/TykTechnologies/tyk/commit/abb1b350b7dfdce52901e6e3f730a7fd899fd3f0

Added new API definition fields for granular JWT validation:
- `jwt_disable_issued_at_validation`
- `jwt_disable_expires_at_validation`
- `jwt_disable_not_before_validation`

Change should be available in upcoming patch release scheduled in 2 weeks.
