### ISSUE TITLE
bug: mutual-tls auth mode appends organization_id twice

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1685]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
mutual-tls auth mode appends organization_id twice. As such, when validating the token, when the correct token is used, we are unauthorized.

**What is the expected behavior?**
should be able to log-in

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

all

**Comment by ilijabojanovic** [comment]
Verified
