### ISSUE TITLE
Keycloak and Tyk API Gateway Integration

### ISSUE THREAD

**Issue by a-wakeel** [TykTechnologies/tyk#1691]
**Do you want to request a *feature* or report a *bug*?**
Might Not

**What is the current behavior?**
Don't Know

**What is the expected behavior?**
To authorize and authenticate clients from Keycloak server using Oauth 2.0
I want to integrate Keycloak as seperate Oauth 2.0 server to authenticate and authorize users/clients on my APIs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by lonelycode** [comment]
Keyclok OAuth 2.0 flow should work if you enable OpenID Connect and supply an ID token to Tyk (Tyk is OIDC compatible and OIDC sits on top of OAuth 2.0)

It would be better to post this to the community forum (community.tyk.io) as GH is only used by the team for big and feature tracking.
