### ISSUE TITLE
Proposal: Replace hash function and make it possible to extend

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1694]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The current hash function i prone to collisions, even though it is very fast.

**What is the expected behavior?**
We should:

1. Replace the hash function with Murmur2 (64-bit)
2. Ensure a way to transition from legacy tokens to new ones to ensure smooth upgrade
3. Make the token format extensible

### Proposal: New hash function: Murmur2

According to [this write up](https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed) Murmur3 is extremely fast because it operates on 4-byte chunks, however this also increases the chance of collisions and leads to the odd behaviour of being able to use a valid token + 3 arbitrary characters to gain API access when using standard bearer tokens.

the write up also concludes that while FNV-1a is probably the most popular fast hash to use because of good distribution, the author goes on to state tat Murmur2 is not only faster, but provides lower / equal collision protection.

I would also suggest we move from a 32-bit has to a 64-bit hash, as that decreases chances even further. The `github.com/aviddiviner/go-murmur` library implements [MurmurHash64A](https://github.com/aviddiviner/go-murmur/blob/master/murmur2.go#L67) and also [shows solid benchmarks](https://github.com/aviddiviner/go-murmur/blob/master/README.md).

Just to ensure 64a is in fact a variant of murmur2, ere's what wikipedia has to say about it:

> MurmurHash2
> The older MurmurHash2[8] yields a 32-bit or 64-bit value. Slower versions of MurmurHash2 are available for big-endian and aligned-only machines. The MurmurHash2A variant adds the Merkle–Damgård construction so that it can be called incrementally. **There are two variants which generate 64-bit values; MurmurHash64A, which is optimized for 64-bit processors**, and MurmurHash64B, for 32-bit ones. MurmurHash2-160 generates the 160-bit hash, and MurmurHash1 is obsolete.

(emphasis mine)

Based on the above, I would propose that we move to `MurmurHash64A` for our default hashing function.

### Proposal: Make our tokens easier to extend and index

Currently tokens generated by the dashboard are of the format: `OrgID+UUIDv4` (the UUID has it's dashes removed). These are provided in a raw format to the user.

For un-hashed installations, we make use of the prefix Org ID to allow listing of the keys that belong to a specific organisation, however, with a hashed key set, the OrgID is obfuscated and namespacing is no longer possible.

It would be good if we could change this scenario, and provide three things:

1. The capability to namespace hashed keys
2. The capability to encode more data into the tokens themselves
3. With the additional encoding, extend the capability of the hashed installation to make use of more hash types, perhaps (slower) cryptographic ones for hardened installations.

Before I start, here's the terminology I'm going to use:

- Token: This is the string provided to the end-user
- Key ID: this is an identifier of the token

I propose that we start providing base64-encoded tokens to end-users, as this is pretty much the standard industry practice. 

If we do provide base64 encoded tokens, then we can begin to pack more data into the token itself for the gateway to process, it also means we can introduce spacers, for example:

```
func generateKey(orgID string) string {
	// Create an ID
	keyID := strings.Replace(uuid.NewV4().String(), "-", "", -1)

	// Get the hash type, but default to mm64a
	hashEnum := GetConfiguredHash()

	// Encode the data into the token
	rawtoken := fmt.Sprintf("%s:%s:%s", orgID, keyID, hashEnum)

	// Return b64 version
	return base64.StdEncoding.EncodeToString([]byte(rawtoken))
}
```

This will add a step in the lookup process because we now need to decode all b64 encoded tokens, but this could potentially be mitigated by the in-memory cache, which can lookup the encoded token instead of unpacking it

To look up the data, we change how the actual key is stored in redis:

*`auth_manerag.go`*

```
// Encode eerything in a token object instead of just strings
type Token struct {
	OrgID    string
	KeyID    string
	HashEnum string
	Legacy   bool
}

// Generic unpacker that also spots legacy keys
func unpackKey(token string) (*Token, error) {
	rawToken, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		// Decode failed, must be legacy token
		return &Token{KeyID: token, Legacy: true}, nil
	}

	parts := strings.Split(string(rawToken), ":")
	if len(parts) != 3 {
		return nil, errors.New("invalid token encoding")
	}

	return &Token{
		OrgID:    parts[0],
		KeyID:    parts[1],
		HashEnum: parts[2],
	}, nil
}

// ModifiedKeyAuthorised checks if key exists and can be read into a user.SessionState object (NOTE: Has been renamed)
func (b *DefaultAuthorisationManager) ModifiedKeyAuthorised(inboundToken string) (user.SessionState, bool) {
	var newSession user.SessionState

        // Unpack everything before checking
	token, err := unpackKey(inboundToken)
	if err != nil {
		return newSession, false 
	}

	storageKey := inboundToken
	if !token.Legacy {
		hashedToken := storage.HashKey(token.KeyID)
		storageKey = fmt.Sprintf("%s:%s", token.OrgID, hashedToken)
	}

	jsonKeyVal, err := b.store.GetKey(storageKey)
	if err != nil {
		log.WithFields(logrus.Fields{
			"prefix":      "auth-mgr",
			"inbound-key": obfuscateKey(inboundToken),
			"err":         err,
		}).Warning("Key not found in storage engine")
		return newSession, false
	}

	if err := json.Unmarshal([]byte(jsonKeyVal), &newSession); err != nil {
		log.Error("Couldn't unmarshal session object: ", err)
		return newSession, false
	}

	newSession.SetFirstSeenHash()
	return newSession, true
}
```

Here we start storing key data as a struct, and we also re-shuffle the storage key to use a plaintext `OrgID` and a hashed `KeyID` for the lookup, this means we an start listing keys again, eent he hashed representation.

It *would* mean ensuring that what we store in context is the storageKey instead of just the has, and also that we ensure that the hashed KeyID is what is sent to Analytics so that all the lookups continue to work.

It does add an extra step, but potentially it would mean we can then add more hash functions to the core.

### Cons:

- More processing, all that b64 and string splitting adds cycles
- It will slow down Tyk for legacy users that are converting
- Keys have data in them (like JWTs), so we are leaking internal system data. However, I we're already doing that with our existing key structure, so It's not a downgrade, but it a continuation

Thoughts and opinions please?

**Comment by buger** [comment]
This makes a LOT sense to me, and nice progress from https://github.com/TykTechnologies/tyk/pull/1684

Exposing some of the data, like hash version, does not look harmful to me, and our project already open-sourced and hash functions are known from the start.
