### ISSUE TITLE
use SETEX when setting keys with expiration in Redis (if this command is available)

### ISSUE THREAD

**Issue by dencoded** [TykTechnologies/tyk#1706]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When we set key with expiration in Redis - we issue two commands `SET` and `EXPIRE` which is not atomic and takes two network roundtrips per one key set.

**What is the expected behavior?**
In case of Redis with version >=2 we need to use `SETEX` which is one network roundtrip per key set and atomic.

We could use command `INFO` to get Redis version when tyk starts and then set keys with `SETEX` or fall back to legacy logic for older versions of Redis.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

**Comment by buger** [comment]
Make sense! Do not think we should support versions < 2, since redis major version already 3.X
