### ISSUE TITLE
Gateway panic when hitting api with custom auth (plugin) mechanism enabled

### ISSUE THREAD

**Issue by a-wakeel** [TykTechnologies/tyk#1709]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
By using a python plugin (sample plugin in tyk repository) with custom auth mechanism on an API the gateway panic

**Here are the logs:**
`15:11:59 ubuntu.gluu.info tyk-python[13035]: 2018/05/17 15:11:59 http: panic serving [::1]:36844: runtime error: invalid memory address or nil pointer dereference
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: goroutine 11335 [running]:
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: net/http.(*conn).serve.func1(0xc4203921e0)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/net/http/server.go:1697 +0xd0
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: panic(0xd6a1e0, 0x16ac600)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/runtime/panic.go:491 +0x283
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: main.(*CoProcessor).Dispatch(0xc420048908, 0xc420871ec0, 0xc420871ec0, 0x2, 0xc42060a2c8)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /src/github.com/TykTechnologies/tyk/coprocess_native.go:49 +0xdc
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: main.(*CoProcessMiddleware).ProcessRequest(0xc420871040, 0x16e1e60, 0xc4204a07e0, 0xc420a7ab00, 0x0, 0x0, 0x1c, 0x7f5b9ae10038, 0x0)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /src/github.com/TykTechnologies/tyk/coprocess.go:263 +0x26e
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: main.createMiddleware.func1.1(0x16e1e60, 0xc4204a07e0, 0xc420a7ab00)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /src/github.com/TykTechnologies/tyk/middleware.go:84 +0x5a3
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: net/http.HandlerFunc.ServeHTTP(0xc420871500, 0x16e1e60, 0xc4204a07e0, 0xc420a7ab00)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/net/http/server.go:1918 +0x44
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4208efc80, 0x16e1e60, 0xc4204a07e0, 0xc420a7ab00)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: main.mainHandler.ServeHTTP(0x16e1e60, 0xc4204a07e0, 0xc420549800)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /src/github.com/TykTechnologies/tyk/main.go:1161 +0x73
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: main.(*mainHandler).ServeHTTP(0x17c3220, 0x16e1e60, 0xc4204a07e0, 0xc420549800)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         <autogenerated>:1 +0x52
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: net/http.serverHandler.ServeHTTP(0xc4204840d0, 0x16e1e60, 0xc4204a07e0, 0xc420549800)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/net/http/server.go:2619 +0xb4
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: net/http.(*conn).serve(0xc4203921e0, 0x16e2e20, 0xc420990dc0)
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/net/http/server.go:1801 +0x71d
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]: created by net/http.(*Server).Serve
مٓی 17 15:11:59 ubuntu.gluu.info tyk-python[13035]:         /usr/local/go/src/net/http/server.go:2720 +0x288`

**What is the expected behavior?**
The gateway should not panic and return expected result

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. setup the plugin from here (https://github.com/TykTechnologies/tyk-plugin-demo-python) and publish
2. Define an api with custom auth(plugin) mechanism
3. Start tyk-gateway-python, it will load the plugin successfully
4. Hit the api

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest version, don't know about the previous versions

**Comment by a-wakeel** [comment]
In addition to that i'm also getting this error before hitting the api:
`level=error msg="can't initialize a dispatcher"`

**Comment by matiasinsaurralde** [comment]
Hi, which Python version are you using?

**Comment by a-wakeel** [comment]
Its python 3.4.8

**Comment by matiasinsaurralde** [comment]
Are you running the Ubuntu version? Please share the output of this command, would be useful to diagnose the issue:
```
ldd /opt/tyk-gateway/tyk-python
```

**Comment by a-wakeel** [comment]
Yeah running it on ubuntu 16.04 and here is the output of the command:
`   linux-vdso.so.1 =>  (0x00007ffc0918a000)
    libpython3.4m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0 (0x00007f47a866a000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f47a844d000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f47a8083000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f47a7e5a000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f47a7c40000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f47a7a3c000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f47a7839000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f47a7530000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f47a8c3e000)`

**Comment by a-wakeel** [comment]
**Gateway Version:** v2.6.1 (for both tyk and tyk-python)

**Gateway logs after restarting the gateway:**
`11:23:48 ubuntu.gluu.info systemd[1]: Stopping Tyk API Gateway (Python Support)...
مٓی 18 11:23:48 ubuntu.gluu.info tyk-python[18448]: 2018/05/18 11:23:48 terminated
مٓی 18 11:23:48 ubuntu.gluu.info tyk-python[18448]: time="May 18 11:23:48" level=info msg="Stop signal received."
مٓی 18 11:23:48 ubuntu.gluu.info tyk-python[18448]: time="May 18 11:23:48" level=info msg="Stopping heartbeat..."
مٓی 18 11:23:50 ubuntu.gluu.info tyk-python[18448]: time="May 18 11:23:50" level=info msg="Stopped Heartbeat"
مٓی 18 11:23:50 ubuntu.gluu.info tyk-python[18448]: time="May 18 11:23:50" level=info msg=Terminating.
مٓی 18 11:23:51 ubuntu.gluu.info systemd[1]: Stopped Tyk API Gateway (Python Support).
مٓی 18 11:23:51 ubuntu.gluu.info systemd[1]: Started Tyk API Gateway (Python Support).
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Setting PYTHONPATH to 'coprocess/python:middleware/python:event_handlers:coprocess/python/proto:/opt/tyk-gateway/middleware/bundles/3c21b603380a496576f472074a03a4c7-bundle.zip:/opt/tyk-gateway/middleware/bundles/901b111584574f607e90366d37b98e19-bundle.zip:/opt/tyk-gateway/middleware/bundles/b3b9554bd37c4ce94c07d9cdb1d23f86-bundle.zip:/opt/tyk-gateway/middleware/bundles/fe4ff54e5a6b4906647e3a7ff25be8ae-bundle.zip'"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Initializing interpreter, Py_Initialize()"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=error msg="can't initialize a dispatcher"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Setting up analytics normaliser"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="PIDFile location set to: ./tyk-gateway.pid"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Initialising Tyk REST API Endpoints"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=warning msg="File descriptor limit 1024 too low for production use. Min 80000 recommended.\n\tThis could have a significant negative impact on performance.\n\tPlease refer to https://tyk.io/docs/deploy-tyk-premise-production/#file-handles for further guidance."
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Redis connection pools are ready after number of retires" currRetry=0
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Redis connection pools are ready"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="--> Standard listener (http)" port=":8080"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Setting up Server"
مٓی 18 11:23:51 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:51" level=info msg="Waiting for zeroconf signal..."
مٓی 18 11:23:52 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:52" level=warning msg="Insecure configuration detected (allowing)!"
مٓی 18 11:23:52 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:52" level=info msg="Hostname set with dashboard zeroconf signal"
مٓی 18 11:23:52 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:52" level=info msg="Registering node."
مٓی 18 11:23:52 ubuntu.gluu.info tyk-analytics[15858]: time="May 18 11:23:52" level=error msg="No nodes available"
مٓی 18 11:23:52 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:52" level=error msg="Response failed with code 404; retrying in 5s"
مٓی 18 11:23:57 ubuntu.gluu.info tyk-analytics[15858]: time="May 18 11:23:57" level=error msg="No nodes available"
مٓی 18 11:23:57 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:23:57" level=error msg="Response failed with code 404; retrying in 5s"
مٓی 18 11:24:01 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:01" level=info msg="Starting Poller"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Node registered" id=be99bf0d-e4e3-4bb7-456d-021aeed99bfe
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Gateway started (v2.6.1)"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Initialising distributed rate limiter"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="--> Listening on address: (open interface)"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="--> Listening on port: 8080"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="--> PID: 18470"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Loading policies"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Using Policies from Dashboard Service"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Mutex lock acquired... calling"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Calling dashboard service for policy list"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Starting gateway rate limiter notifications..."
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Processing policy list"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg="Policies found (1 total):"
مٓی 18 11:24:02 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:02" level=info msg=" - 5af4160ee224475e6a42f879"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Detected 2 APIs"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Preparing new router"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Initialising Tyk REST API Endpoints"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loading API configurations."
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Tracking hostname" api_name=test domain="(no host)"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Tracking hostname" api_name=xyz domain="(no host)"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loading API" api_name=xyz
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loading API" api_name=test
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loading existing bundle: bundle.zip"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="----> Loading bundle: bundle.zip"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="----> Using bundle: bundle.zip"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Checking security policy: Open" api_name=xyz
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loaded: xyz" api_id=dae0e07e01444c1562d67de846526fab org_id=5af1910be224471d7ccae5f7 server_name=-- user_id=-- user_ip=--
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Checking security policy: Open" api_name=test
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loaded: test" api_id=3c21b603380a496576f472074a03a4c7 org_id=5af1910be224471d7ccae5f7 server_name=-- user_id=-- user_ip=--
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Processed and listening on: /test/{rest:.*}"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Processed and listening on: /xyz/{rest:.*}"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Loading uptime tests..."
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="Initialised API Definitions"
مٓی 18 11:24:03 ubuntu.gluu.info tyk-python[18470]: time="May 18 11:24:03" level=info msg="API reload complete"
مٓی 18 11:24:05 ubuntu.gluu.info tyk-analytics[15858]: time="May 18 11:24:05" level=info msg="Sending config request for node: be99bf0d-e4e3-4bb7-456d-021aeed99bfe-ubuntu.gluu.info"
مٓی 18 11:24:05 ubuntu.gluu.info tyk-analytics[15858]: time="May 18 11:24:05" level=info msg="Got configuration for nodeID: be99bf0d-e4e3-4bb7-456d-021aeed99bfe|ubuntu.gluu.info"`

**Logs after hitting the api:**
`11:24:58 ubuntu.gluu.info tyk-python[18470]: 2018/05/18 11:24:58 http: panic serving [::1]:57656: runtime error: invalid memory address or nil pointer dereference
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: goroutine 6457 [running]:
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: net/http.(*conn).serve.func1(0xc420b26320)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/net/http/server.go:1697 +0xd0
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: panic(0xd6a1e0, 0x16ac600)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/runtime/panic.go:491 +0x283
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: main.(*CoProcessor).Dispatch(0xc420b19908, 0xc420a86cc0, 0xc420a86cc0, 0x2, 0xc420b5a3e8)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /src/github.com/TykTechnologies/tyk/coprocess_native.go:49 +0xdc
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: main.(*CoProcessMiddleware).ProcessRequest(0xc420a60000, 0x16e1e60, 0xc420b5e000, 0xc4205e7500, 0x0, 0x0, 0x1c, 0x7f55471447f8, 0x0)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /src/github.com/TykTechnologies/tyk/coprocess.go:263 +0x26e
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: main.createMiddleware.func1.1(0x16e1e60, 0xc420b5e000, 0xc4205e7500)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /src/github.com/TykTechnologies/tyk/middleware.go:84 +0x5a3
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: net/http.HandlerFunc.ServeHTTP(0xc420a60200, 0x16e1e60, 0xc420b5e000, 0xc4205e7500)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/net/http/server.go:1918 +0x44
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420867980, 0x16e1e60, 0xc420b5e000, 0xc4205e7500)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:150 +0xed
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: main.mainHandler.ServeHTTP(0x16e1e60, 0xc420b5e000, 0xc420b44100)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /src/github.com/TykTechnologies/tyk/main.go:1161 +0x73
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: main.(*mainHandler).ServeHTTP(0x17c3220, 0x16e1e60, 0xc420b5e000, 0xc420b44100)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         <autogenerated>:1 +0x52
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: net/http.serverHandler.ServeHTTP(0xc4205fc0d0, 0x16e1e60, 0xc420b5e000, 0xc420b44100)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/net/http/server.go:2619 +0xb4
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: net/http.(*conn).serve(0xc420b26320, 0x16e2e20, 0xc420879f40)
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/net/http/server.go:1801 +0x71d
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]: created by net/http.(*Server).Serve
مٓی 18 11:24:58 ubuntu.gluu.info tyk-python[18470]:         /usr/local/go/src/net/http/server.go:2720 +0x288`

**Comment by matiasinsaurralde** [comment]
Try using these settings in your `tyk.conf`:
```json
  "coprocess_options": {
    "enable_coprocess": true,
    "python_path_prefix": "/opt/tyk-gateway"
  },
```

**Comment by a-wakeel** [comment]
getting same error after making those changes

**Comment by matiasinsaurralde** [comment]
The log should print "python: Initializing dispatcher" if the Python setup is ok, did you install the required Python modules?

**Comment by a-wakeel** [comment]
The problem was resolved by reinstalling the gateway from start
