### ISSUE TITLE
scrambled detailed logging when client specify "Accept-Encoding" 

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1711]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Scrambled detailed logging
<img width="651" alt="image" src="https://user-images.githubusercontent.com/3155222/40248307-7080a0d0-5ac7-11e8-95a9-76b772279bb2.png">

That was after running it using postman. I run the request from curl and it got sorted. Can you or someone else explain what happened and how it’s related to the gzip encoding?

**From the Log Browser:**
> **request from postman**
_GET /posts/ HTTP/1.1
Host: tyk-gateway:8080
User-Agent: PostmanRuntime/7.1.1
Accept: */*
**Accept-Encoding: gzip, deflate**
Cache-Control: no-cache
Postman-Token: 108587cb-d947-4bbd-b196-70aa6562c172_

> **From curl**
_GET /posts/ HTTP/1.1
Host: tyk-gateway:8080
User-Agent: curl/7.54.0
Accept: */*_

**What is the expected behavior?**
Desplay the content similar to the respose I get on postman

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I used this a url which returns json in the body and among other headers these ones:

> Content-Encoding | gzip
Content-Type | application/json; charset=utf-8
Etag | ZZZZZZZZ
Transfer-Encoding | chunked

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tested on 2.6.1

**Comment by buger** [comment]
We should detect encoded bodies and handle re-endoding when writing analytics, like it was done for body transforms https://github.com/TykTechnologies/tyk/blob/master/res_handler_transform.go#L29:6

**Comment by letzya** [comment]
https://github.com/TykTechnologies/tyk/commit/1a08535917dbcb1f1a8c8c41431df19f43772113

**Comment by letzya** [comment]
@buger did you move it to OA? can we close this?
