### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [TykTechnologies/tyk#1713]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises 
Visual Communication Designer

**Comment by joshblakeley** [comment]
Hi we have our own in house graphics wizardess who does all the fantastic designs you see at www.tyk.io

Thank you for the offer and good luck with you projects!

Josh @ Tyk
