### ISSUE TITLE
Certificate pinning does not work if Proxy is used

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1717]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If upstream traffic passed through the Proxy, both `proxy.transport.proxy_url` or HTTP_PROXY env, certificate pinning stops working
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.6

**Comment by ilijabojanovic** [comment]
Verified
