### ISSUE TITLE
How to calculate Rate limiting period?

### ISSUE THREAD

**Issue by 1329555958** [TykTechnologies/tyk#172]
![image](https://cloud.githubusercontent.com/assets/3915919/12380766/c824f31a-bdb5-11e5-966a-01442c3a4b9d.png)

**Comment by lonelycode** [comment]
We have a new rate limited, it uses a sentinel to drop rate limit enforcement off thread, the sentinel times out based on the period value. 

This is fine for short periods, not for long ones.

The trade offs are: either process on-thread (in request) and decrease throughout overall, or do it with the sentinel to increase overall throughout and performance. 

The value of sentinel degredation is still up for grabs though.
