### ISSUE TITLE
Warn user when connection string is blank

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1731]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Some users do not fill in the connection string in their configs when connecting to the dashboard in on-prem Tyk. There is currently no clear warning that this will be a breaking issue for their setup.

**What is the expected behavior?**

If the user has ` "use_db_app_configs": true,` and a blank connection string the gateway will display a warning log message

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All Versions

**Comment by buger** [comment]
I think we should extend it even more. We introduced linter project some time ago, but the project was not that active in the last months. Right now it is a separate command, and user required to run it to validate config. I propose to include linter into tyk start flow: it should not prevent process starting if it found errors (so mistakes in schema won't cause outage), but it should print to ERR log all the issues. 

Regarding connection string, JSON schema we are using support dependencies and conditions, so it should be possible to write logic like:
```
if use_db_app_configs is true:
   connection_string != ""
```

http://www.tothenew.com/blog/using-dependencies-in-json-schema-version-draft-v4/
Also see `oneOf` and `allOf` keywords. 

Can you investigate this direction? It will be extremely helpful for debugging config issues.

**Comment by joshblakeley** [comment]
Love the idea, I'll look into it.
