### ISSUE TITLE
Whitelists let through unwhitelisted methods when used with other middleware

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1732]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. Create api with whitelisted GET endpoint
2. Send request with PUT and it will be rejected by Tyk
3. Add modify headers middleware to  same endpoint
4. Send PUT request again and it will hit the upstream.

**What is the expected behavior?**

Whitelisted endpoints should only allow through the specified http method

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See above.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.6.1

**Comment by bsingr** [comment]
Having the same problem here. The problem didn't exist in version `2.2.0.20`.

We wanted to upgrade from an older tyk version but now we are blocked because of that :(

**Comment by ilijabojanovic** [comment]
@buger approved for merge, please review code

**Comment by buger** [comment]
@ilijabojanovic fixed it, but a bit another way
