### ISSUE TITLE
Policy access rights do not apply to OIDC clients

### ISSUE THREAD

**Issue by masacc** [TykTechnologies/tyk#1737]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
1. When configuring OpenId Connect Authentication for an API, I add an issuer, a client ID and apply a existing policy with access rights to it. Everything is fine, I can reach the API.
2. Then I replace the policy applied to the client with another one. The new selected policy has access rights for another api which has a totally different path. 

I can still reach the API. I shouldn't.

**What is the expected behavior?**
When replacing the policy applied to the client (step 2), I shouldn't be able to reach the API. I should have a 403 forbidden response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See _What is the current behavior?_

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Gateway 2.6.1, Pump 0.5.2, Dashboard 1.6.1
Same issue with Gateway 2.5.1, Pump 0.5.1, Dashboard 1.5.1

**Comment by buger** [comment]
Thank you for the report. Can confirm the issue. We fixed similar in JWT middleware a while ago, should be a similar fix.

**Comment by masacc** [comment]
Hello, any idea of when it will be fixed ?

**Comment by letzya** [comment]
Per @buger question - Can you confirm it's still an issue with OIDC?
