### ISSUE TITLE
Expose Querystring parameters to JSVM middleware plugins

### ISSUE THREAD

**Issue by lancehunt** [TykTechnologies/tyk#174]
I need to be able to read & react to the querystring parameters within middleware.  However, they are not currently exposed (although you can set/delete them).  

It looks like the MiniRequestObject needs to be modified to expose a Params field in addition to Headers and URL:
https://github.com/TykTechnologies/tyk/blob/master/plugins.go#L88

Here is a serialized view of the current Request object.
```
[JSVM] [LOG]: request = {\"AddParams\":{},\"Body\":\"\",\"DeleteHeaders\":[],\"DeleteParams\”:[],
\"Headers\":{\"Accept\”:[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\”],
\"Accept-Encoding\":[\"gzip, deflate, sdch\”],
\"Accept-Language\":[\"en-US,en;q=0.8,da;q=0.6\”],
\"Cache-Control\":[\"max-age=0\”],
\"Connection\":[\"keep-alive\”],
\"Dnt\":[\"1\”],
\"Upgrade-Insecure-Requests\":[\"1\”],
\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36\"]},
\"SetHeaders\":{},
\"URL\":\”/myurl/“ }
```

**Comment by lancehunt** [comment]
FYI: I have a pull request incoming for this issue - just testing it.

**Comment by lonelycode** [comment]
Sweet :-)

**Comment by lonelycode** [comment]
Merge against develop though please :-) been a bit going on with JWT middleware.
