### ISSUE TITLE
How to export Tyk runtime logs to host machine file when using docker?

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#1748]
**Do you want to request a *feature* or report a *bug*?**
feature 
**What is the current behavior?**
Currently all logs are default docker stdout, can only be accessed by docker logs command.
**What is the expected behavior?**
All Tyk related containers (tyk_gateway, tyk_dashboard, .etc) logs that can be seen from docker logs can be exported to a log file in the host machine. Of course, I can use the redirection operator "> somelogfile.log", but it is not a convenient way to do so and can not even be archived when the log accumulate to some size.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all docker version

**Comment by buger** [comment]
Hi! In addition to STDOUT you can also send logs to various systems like Graylog, Logstash, or Syslog. See more details here https://tyk.io/docs/log-data/#aggregated-logs-with-syslog.
