### ISSUE TITLE
Enable API's to accept Auth tokens in both Querystring and Headers

### ISSUE THREAD

**Issue by lancehunt** [TykTechnologies/tyk#175]
Currently Auth tokens can be passed in Headers or via Querystring with the appropriate config enabled but not both for a single API definition.

Since the same API's are often consumed by both browser-based and mobile applications, its critical that both are supported simultaneously.

See the discussion at the bottom of this closed issue:
https://github.com/TykTechnologies/tyk/issues/44

**Comment by lonelycode** [comment]
This is now in the nightlies (it may even be in 2.0), but it's definetely done.
