### ISSUE TITLE
api rate-limit should run after token rate-limit

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1755]
**Do you want to request a *feature* or report a *bug*?**

enhancement

**What is the current behavior?**

api rate-limit runs before token rate-limit. As such, a single token sending requests at API rate limit (even though they have own rate limit) can negatively impact service availability for other tokens.

**What is the expected behavior?**

A single token going over own rate-limit should not impact other tokens.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All

**Comment by ilijabojanovic** [comment]
Verified @buger please merge on master and release-2.7 branch
