### ISSUE TITLE
JWT Authorization

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#176]
Hi,

The documentation about JWT seems to be very specific. I have the (Thinktecture) Identity Server issuing JWT tokens. My certificate uses signature algorithm sha1RSA (it's a windows pfx file).
There is also this header in my token:
"kid": "a3r...."

My flow would look like this:
Client <-  token -> Authorization Server
Client -- Auth: Bearer Token --> Tyk Gateway (check rate limiting, etc.)
Tyk -- Auth: Bearer Token --> API

All I can select in the Gateway options is JWT and RSA... ? Via the API the docu says I have to create some certs, but I want to use my exiting one.
I read about a key I have to create with the Tyk API to connect to a session? What do I have to do with this key? Seems to be not very user friendly.

Greetings..

**Comment by lonelycode** [comment]
Are you reporting a bug? The JWT implementation is specific to you generating your own JWTs, not 3rd parties and works as described in the docs.

For third party integration I suggest using Tyk Identity Broker.

There's centralised JWT on the way where you can use virtual tokens (see the community forum and other issues in this issue tracker) that are generated elsewhere.

**Comment by lonelycode** [comment]
Here's a similar discussion with Auth0 where the new centralised JWT handler is discussed:

https://community.tyk.io/t/tyk-io-auth0/325/2

And here it is on our roadmap:

https://trello.com/c/FNiyd5kP

**Comment by senj** [comment]
great, thank you
