### ISSUE TITLE
Enhance output from /hello health check endpoint

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#1763]
Currently the /hello endpoint returns a 200 code and some text, however some users may want to vary the return code or some or the body of the response.

We can make it so the /hello endpoint can accept a template which it can parse and return some non sensitive information such as hostname, port of the gateway and a custom response code or message.

**Comment by altaurog** [comment]
I’m getting 401 Unauthorized on `/hello`, and the following message in the logs:
```
[Jul 12 21:41:50]  WARN openid: JWT Invalid: Validation error. The 'Authorization' header was not found or was empty.
[Jul 12 21:41:50]  WARN openid: Attempted access with invalid key. key=[JWT]
```
We are using openid for auth on all our APIs.  Does that automatically apply to this endpoint also?

**Comment by altaurog** [comment]
here’s my tyk.conf:
```
{
  "listen_port": 8180,
  "secret": "TYK_SECRET",
  "app_path": "apps/",
  "template_path": "templates/",
  "middleware_path": "middleware/",
  "enable_jsvm": true,
  "python_path_prefix": "/opt/tyk-gateway",
  "enable_custom_domains": true,
  "control_api_hostname": "tyk.example.com",
  "hash_keys": true,
  "close_connections": true,
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 100
  },
  "policies": {
    "policy_source": "file",
    "policy_record_name": "policies/policies.json"
  },
  "health_check": {
    "enable_health_checks": false
  }
}
```

**Comment by marksou** [comment]
Returning the Gateway Version Number would be very useful.
