### ISSUE TITLE
categorize catalogues

### ISSUE THREAD

**Issue by timlansbergen** [TykTechnologies/tyk#1764]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
No category functionality is available in the tyk catalogue screen
**What is the expected behavior?**
I would like to have the same functionality as the current api categorize functionality for the catalogues in Tyk. These categories should be selectable in a combo box on the developer portal to reduce the amount of api's shown on the portal page.

**Comment by buger** [comment]
Hello! This definitely makes sense, however even right now, you can try to achieve this kind of functionality. 

You can configure Tyk dev portal using 2 ways: by using our built-in portal, or by building customer developer portal in the language of your choice https://tyk.io/docs/publish/customise/custom-developer-portal/

In both cases, you have the ability to modify templates, and implement logic you want using templating logic or maybe with help of small javascript. 

I will provide you an example on how to do such filtering using the built-in portal.
Catalog listing page template located at `portal/templates/catalogue.html` of your installation. 
On top of the page, you can define select element, which will show your API categories. And then in Javascript you will define the mapping between your categories and API names, and will conditionally hide/show APIs based on what currently selected. Here is example code:

```
<select id="categories" onchange="onCategoryChange">
   <option>Routes</option>
   <option>Maps</option>
</select>

<script src="text/javascript">
// Mapping between categories and 
var categories = {
    "Routes": ["Directions API", "Measurement API"],
    "Maps": ["Tiles API", "Geo API"]
};

function onCategoryChange(){
   // get selected 
   var category = document.getElementById("categories").value;
   var catalogueAPIs = categories[category];
   
   // DOM nodes of all API categories
   var apiElements = document.querySelectorAll(".col-md-4");
   // Hide DOM elements of APIs which do not match filter
   apiElements.forEach(function(el){
      var apiName = el.querySelector("h2").innerText;
      if (catalogueAPIs.indexOf(apiName) != -1) {
          // Show APIs which names match category
          el.style.display = "block";         
      } else {
          // Hide APIs which names not included into category
          el.style.display = "none";
      }
   })
}

// Apply our filter on page load
setTimeout(function(){
  onCategoryChange()
}, 0)
</script>
```

**Comment by timlansbergen** [comment]
Hi Buger,

Thanks for your reply. I have tested the javascript code but it looks like it cannot load the api data. I have executed the following steps to test this:
1. Copy catalogue.html in folder 'portal/templates/' to catalogue_new.html.
2. Change templatename to 'cataloguePageNew' by changing the first line to : {{ define "cataloguePageNew" }} {{ $org_id := .OrgId}} {{ template "header" .}}
3. Create a custom page template in tyk dashboard.
4. Go to the custom page which I just created. The page is able to load but the text 'It looks like there are no APIs in the Catalogue.' is presented. I would expect the api's in here.

In the steps above I did not yet include your javascript code because I first want to show you that it is not able to load the api data in a custom page template. Am I missing something?

We are currently using Tyk dashboard 1.6.2.

Kind regards,

Tim

**Comment by buger** [comment]
You can't create new files like this, you need to modify existing catalogue.html page, and just create backup of the original one.

**Comment by timlansbergen** [comment]
Hi Buger,

It works now. There is small bug in the code. I removed 'src="text/javascript"' part in the <script> tag.

Kind regards,

Tim

**Comment by buger** [comment]
Perfect!
