### ISSUE TITLE
No --debug mode in tyk-analytics (dashboard)

### ISSUE THREAD

**Issue by sitio** [TykTechnologies/tyk#1765]
**Do you want to request a *feature* or report a *bug*?**

This is either a defect in tyk-analytics or in the documentation.

**What is the current behavior?**

[The documentation](https://tyk.io/docs/log-data/) states that to activate debug-level logging to use the flag --debug. This works in gateway but not in analytics. 

`tyk-analytics: error: unknown long flag '--debug', try --help`

`root@tyk-dashboard-d449b86dc-c6mwc:/opt/tyk-dashboard# ./tyk-analytics --help-long
usage: tyk-analytics [<flags>]

Flags:
  -h, --help       Show context-sensitive help (also try --help-long and --help-man).
      --newuser    create a new user
      --neworg     create a new organisation
      --conf=CONF  load a named configuration file
      --dev        developer mode
      --speed      show page speed
      --version    Show application version.`

There is a --dev mode but I can't find a description of that in the documentation or in the community forums so it is unclear if that's the analytics version of --debug.

**What is the expected behavior?**

I would expect tyk-analytics to either support --debug or for the documentation to flag the difference between gateway and dashboard if --dev is the equivalent of --debug for dashboard.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Simply start tyk-analytics with the --debug flag. For example, if using k8s, do this:

`command: ["/opt/tyk-dashboard/tyk-analytics", "--conf=/etc/tyk-dashboard/tyk_analytics.conf", "--debug"]`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

This is v1.6.2 - I have never used a previous version so I cannot say if it existed prior to 1.6.2

**Comment by asoorm** [comment]
Thank you for reporting this. We will fix the docs / the dashboard.

In the meantime, you may specify log level by setting an environment variable when you start the dashboard service `TYK_LOGLEVEL=debug`.

**Comment by sitio** [comment]
Wow, thank you for the incredibly quick response. The env var will due well.

**Comment by joshblakeley** [comment]
No problem - if you want to talk to us at all about how you use case with Tyk then pop us an email at info@tyk.io

cheers
Josh
