### ISSUE TITLE
Setup.sh/bootstrap.sh creates new org every time you run it

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1767]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
This had happened to me in the beginning - we should improve our bootstrap script.
Setup.sh/bootsrap.sh creates new org every time you run it - and the users don't notice they have just created a new organisation. In this situation after they login, they won't see the apis on the dashboard although they are on mongoDB. Very frustrating.
 
**What is the expected behavior?**
That the script would be clearer in terms of user experience. 
The user should know if a new org got created while there's another one in the db (not everyone remember it's a multi tenancy platform)
The script should be re-runnable (there are lots of options for that).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Run the scripts 2-3 times

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.6.2 and previous
Repos:
tyk-pro-demo
Native versions

**Some possible solutions**
1. Maybe check if there's already an existing org and ask the user interactively (with -q option) whether they want to create a **new org**  or just a **new user** (since they lost the previous password) 
2. Create a new name per new org. Currently all orgs share the same name which makes it harder for users to even notice.
3. Improve the output the the end to something more eye catching:
**The new organization XXXX has been created for you**
or just **A new user has been created for you in orgid XXXX**
4. Maybe other people can suggest more options
5. Improve the error handling and return more meaningful errors (the script needs to be tested with various edge cases.

**Comment by lonelycode** [comment]
Suggest to put in 2.8 if we are code-freezing this week.

**Comment by letzya** [comment]
Output from "Improving On prem Installation" meeting 19June2018
- [ ] Write cli for bootstrap script
   - [ ] Interactive mode and non-interactive with flags
   - [ ] No more multiple orgs in this flow. Check for orgs 
         - If there's no org create org as usual and exit in case of an error. 
         - If there is org in mongo - ask the user if he wants to drop the db or exit

**Comment by matiasinsaurralde** [comment]
Would this be a CLI subcommand? That would be great

**Comment by buger** [comment]
@matiasinsaurralde yes, we thinking of rewriting bootstrap script from bash to Go

**Comment by a-nldisr** [comment]
Update: Running this script when you already setup an API will break the entire Tyk setup without a way to salvage it. To clarify: 
- Setup tyk, api's, set your portal. 
- Run the script again. 
- Old portal still works, but entire dashboard is now empty. 
- Recreate the api's, portal and catalogue. 
- Portal works again but catalogue and register get a 404/not found.

**Comment by joshblakeley** [comment]
You have most likely created multiple orgs by mistake - you can use the dashboard admin api to retrieve details of the orgs in your install.

We have deprecated the bootstrap script from the next release in favour of a CLI tool which will be safer to use.

**Comment by a-nldisr** [comment]
Another suggestion i have is: Please bind this endpoint to the loopback device, in its current setup you can use this endpoint remotely.

**Comment by joshblakeley** [comment]
Makes sense to make it configurable as some might want to include it in some remote build scripts for example

**Comment by asoorm** [comment]
Closing as bootstrap.sh is deprecated from 2.8. We recommend using the tyk-analytics cli to bootstrap the dashboard.
