### ISSUE TITLE
HandleAddOrUpdateApi create API spec to filesystem even use_db_app_configs is true

### ISSUE THREAD

**Issue by iwat** [TykTechnologies/tyk#177]
"HandleAddOrUpdateApi" does not respect "use_db_app_configs". Calling POST /tyk/apis/ will create files to configuration directory even use_db_app_configs is true. And no API is registered to MongoDB.

**Comment by lonelycode** [comment]
This is expected behavior, to write to DB use the advanced API, the gateway API does not write back to DB. its to ensure independence between the services.

**Comment by iwat** [comment]
If that's so, what is the proper way to add new API definition to a cluster of Tyk(s)?

**Comment by lonelycode** [comment]
Just use the dashboard API (aka Advanced API):

https://tyk.io/advanced-api-v0-9/api-definitions/#create-api-definition:cdac0ac5cf58124a5fc9102bcd4708e4

This will save to DB and signal cluster to hot reload

**Comment by iwat** [comment]
Thank you very much, it seems to be what I was looking for.

By the way, could you please provide a URL on how can I have that "Authorization" header?

**Comment by lonelycode** [comment]
Go to your dashboard -> Users -> Select a user (or create one for the app) -> The API Key is listed under the user profile

**Comment by iwat** [comment]
For an unknown reason, an access key of generated user from setup.sh (Docker) was not working. Resetting or creating a new user can solve the problem.

**Comment by lonelycode** [comment]
That can happen, sometimes the access key isn't saved properly and needs regenerating.

**Comment by lonelycode** [comment]
Not sure why that happens, it could be simply the key was lost in Redis when it restarted.

**Comment by iwat** [comment]
By the way, is it better if the gateway returns error on POST /tyk/apis/ when 'use_db_app_config' is true?

**Comment by lonelycode** [comment]
That is a fantastic idea :-)
