### ISSUE TITLE
Access certificate data inside plugins

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1772]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
At the moment Plugin can access only certificate fingerprint. In order to implement custom certificate authentification it is not enough, and having access to certificate DN is required. DN itself looks like ` CN=client1,OU=MyClients,O=MongoDB-Cluster,L=Austin,ST=TX,C=US` which is basically representation of certificate Subject fields.
**What is the expected behavior?**
We can add new plugin field, called `CertificateDN` which will expose this information.

**Comment by buger** [comment]
Should be streightforward in Go like this:

```
cert, err := x509.ParseCertificate(d)
fmt.Printf("%+v\n", cert.Subject.ToRDNSequence())
```

**Comment by buger** [comment]
Should be great if we can get access to DN inside advanced url rewriter too.

**Comment by maxtarasuik** [comment]
Looks awesome, I suspect this will be of more use when/if Mutual TLS works with a CA rather than individual certificates.
That way you can Authenticate with a CA, and Authorize users using this in a plugin (did I get your terminology right ?)

I should add I don't think you can Authenticate with only a DN, as anyone could sign a cert with "CN=client1,OU=MyClients,O=MongoDB-Cluster,L=Austin,ST=TX,C=US". 

 👍

**Comment by buger** [comment]
This functionality should extend request object to provide 2 things:
1) raw certificate information (can be accessed via req.TLS.PeerCertificates[...].Raw), so the plugin can do parsing and validation by itself
2) certificate meta (we already have helpers to extract it, see `CertificateMeta` in code).

Note that `req.TLS.PeerCertificates[...]` is an array, so both fields mentioned above also should be an arrays. 

For GRPC compatibility, the second field with meta can be a list of JSON strings.

**Comment by andyo-tyk** [comment]
I'm closing this because, whereas the PR linked above was never merged into a release, we hae subsequently developed support for Go Plugins; these have access to the request object and certificate
