### ISSUE TITLE
Tyk Dashboard - Notification web socket server does not honor TLS settings

### ISSUE THREAD

**Issue by ch0wnag3** [TykTechnologies/tyk#1773]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Despite specifying a `http_server_options.min_version` value of `770`, I am able to connect to the notification web socket server with TLS 1.0. The use of TLS 1.0 represents a PCI vulnerability.

**What is the expected behavior?**

The notification web socket server should honor the TLS setting specified in `http_server_options.min_version`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Enable TLS on Tyk Dashboard
2. Set `http_server_options.min_version` to `770`
3. Execute the following OpenSSL command: `openssl s_client -connect host:5000 -tls1`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Tyk Dashboard v2.5.3

**Comment by asoorm** [comment]
@ch0wnag3 Ticket for dashboard created internally and PR is in process of being reviewed.
