### ISSUE TITLE
authorize-client endpoint not working with "/" listen_path

### ISSUE THREAD

**Issue by richardolsson** [TykTechnologies/tyk#1780]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to POST to /tyk/oauth/authorize-client/ does not work, even though `listen_path` is /. Changing `listen_path` to /foo resolves the issue and the endpoint now starts working, at /foo/tyk/oauth/authorize-client/.

**What is the expected behavior?**
When `listen_path` is /, the path to authorize a client should be /tyk/oauth/authorize-client/.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Start up Tyk 2.6.2 using Docker
2. Create a new API with `listen_path` set to "/" and authorization set to Oauth 2.0
3. Try making a POST (e.g. using Curl) to _<tyk_gateway>_/tyk/oauth/authorize-client/ which will result in a 404

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This happened in 2.6.2. I had a much earlier version installed before and it was working there. Unfortunately I don't know which version, but it was from before the dashboard re-design.

For more info, see community discussion thread: https://community.tyk.io/t/oauth-authorizing-not-working-after-upgrade/2699/6

**Comment by letzya** [comment]
We should check if it also happens with batch request `/tyk/batch/`
