### ISSUE TITLE
support open paths for protected apis

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1788]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

If an API needs to have some paths protected, but allow others entry without auth, this currently may be achieved with custom middleware, or by creating multiple APIs in combination with re-write logic.

**What is the expected behavior?**

I should be able to protect an API, and also specify a whitelist of paths / enable within middleware specific paths which may be accessed keyless.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All

**Comment by lonelycode** [comment]
> I should be able to protect an API, and also specify a whitelist of paths / enable within middleware specific paths which may be accessed keyless.

That's what the ignore middleware is for, what else is required?

**Comment by asoorm** [comment]
I hunk I may have poorly specified the problem. Or forgot to include the key issue.

Because the ignore lists do not just affect auth. From my understanding, I cannot perform a body transform or header injection or use any other middleware on an ignored path.

**Comment by lonelycode** [comment]
Right, that makes more sense, so we need a no-auth endpoint check in the auth MW (all auth MW)

**Comment by buger** [comment]
I think we need update it to bug, and make ignore plugin work with rest of plugins.
