### ISSUE TITLE
OAuth2 spec or header transformation

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#179]
Hello,

I'm fighting to get the JWT Authorization to work and finally everything looks like it's working. The only issue left is that Tyk expect the token to be in the authorization header as-is, but the OAuth2 spec defines to send the token with "Bearer {token}".
Is it possible to inject a header transformation to send every routed request with Bearer {value of authorization header} ?

Greetings.

**Comment by lonelycode** [comment]
This is already in the Develop branch:

https://github.com/TykTechnologies/tyk/blob/develop/CHANGELOG.md

**Comment by lonelycode** [comment]
To do it dynamically you could use some Middleware JS.
