### ISSUE TITLE
Update documentation for redis SSL

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1790]
This documentation needs to be updated for `"use_ssl": true`

https://tyk.io/docs/configure/redis-cluster/

https://github.com/TykTechnologies/tyk/issues/1289

**Comment by asoorm** [comment]
@bitsofinfo thanks for reporting - https://github.com/TykTechnologies/tyk-docs/pull/474/files?w=1

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
Hi @bitsofinfo,
I'm closing this ticket as I believe we've addressed the issue you raised in the Tyk docs.
If we've missed something, please let me know and we'll get right on it.
Thanks for your help improving Tyk!
