### ISSUE TITLE
Using JWT Web Tokens require both kid and sub fields

### ISSUE THREAD

**Issue by dlord** [TykTechnologies/tyk#180]
I have been trying to switch our existing API's to use JWT Web Tokens. Based on the docs, you will need to provide the API key via the `kid` field in the header section of the token. If this is not available, it will then check the `sub` field in the claims section.

After several hours of testing, it turns out that you need `kid` AND `sub` fields. It cannot be one or the other.

I am using the Docker Quickstart to test this out.

**Comment by lonelycode** [comment]
Not sure how that is possible: 

https://github.com/TykTechnologies/tyk/blob/master/middleware_jwt.go#L91

Maybe the logic is wrong?

**Comment by lonelycode** [comment]
Can you provide a sample JWT that failed?

**Comment by dlord** [comment]
I setup my Tyk instance to proxy requests to `http://gurujsonrpc.appspot.com/guru`, for testing purposes. I am sending a JSON-RPC request.

Data:
```
{ "method" : "guru.test", "params" : [ "Guru" ], "id" : 123 }
```

This is the sample python code I use to generate the JWT:

```
import hmac, hashlib, base64, urllib, urllib2

secret = "mysharedsecret"

header = base64.b64encode("""
{
  "kid": "56a8bd44da435300010000015f5ed77440d145466ddd221f56f51c6c",
  "alg": "HS256",
  "typ": "JWT"
}
""").decode()

payload = base64.b64encode("""{ "sub": "56a8bd44da435300010000015f5ed77440d145466ddd221f56f51c6c", "method" : "guru.test", "params" : [ "Guru" ], "id" : 123 }""").decode()

message = header + "." + payload

signature = base64.b64encode(hmac.new(secret, message, hashlib.sha256).digest()).decode()

print(header + "." + payload + "." + signature)
```

Notice that I have to add both `kid` and `sub` for this to work.

Output JWT:

```
CnsKICAia2lkIjogIjU2YThiZDQ0ZGE0MzUzMDAwMTAwMDAwMTVmNWVkNzc0NDBkMTQ1NDY2ZGRkMjIxZjU2ZjUxYzZjIiwKICAiYWxnIjogIkhTMjU2IiwKICAidHlwIjogIkpXVCIKfQo=.eyAic3ViIjogIjU2YThiZDQ0ZGE0MzUzMDAwMTAwMDAwMTVmNWVkNzc0NDBkMTQ1NDY2ZGRkMjIxZjU2ZjUxYzZjIiwgIm1ldGhvZCIgOiAiZ3VydS50ZXN0IiwgInBhcmFtcyIgOiBbICJHdXJ1IiBdLCAiaWQiIDogMTIzIH0=.g1Eow1g5pu5VtU3Izbt2g0H6MZYTNftrdWBRcDgl7zc=
```

Test request using `curl`:

```
curl -v -H "Authorization: $(python jwttest.py)" -H "Content-Type: application/json-rpc" -d '{ "method" : "guru.test", "params" : [ "Guru" ], "id" : 123 }' "http://tyk.docker/guru-test-api/"
```

**Comment by lonelycode** [comment]
Right... so I ran your code, and you are correct, you need sub AND kid for the key to validate, you take either out, and you get an error.,

But did you look at the logs?

```
INFO[0690] Attempted JWT access with non-existent key.   key= key_present=false origin=62.232.114.250:57818 path=/jwt-hmac-2/get
ERRO[0690] Token validtion errored: illegal base64 data at input byte 26
```

Now if I use an online JWT builder such as [this one](http://jwtbuilder.jamiekurtz.com/) - it doesn't even allow me to set the KID header, so I just use the subject (which is required by the standard I believe) - but the tokens validate with a sub of my key ID.

Just because I'm paranoid I decoded the header of these and it's just:

```
{"typ":"JWT","alg":"HS256"}
```

So i have a feeling there's something off with the encoding of your token.

**Comment by dlord** [comment]
Thank you for pointing that out. After looking at the encoding in detail, it turns out that you need to perform a URL-safe base64 encoding. You can do this in python using `base64.urlsafe_b64encode()` instead of the usual `base64.b64encode()`

Thanks to that, it validates the token properly.

The resulting python code is as follows:

```
import hmac, hashlib, base64, urllib, urllib2

secret = "mysharedsecret"

header = base64.urlsafe_b64encode("""
{
  "kid": "56a8bd44da435300010000015f5ed77440d145466ddd221f56f51c6c",
  "alg": "HS256",
  "typ": "JWT"
}
""").decode()

payload = base64.urlsafe_b64encode("""{ "method" : "guru.test", "params" : [ "Guru" ], "id" : 123 }""").decode()

message = header + "." + payload

signature = base64.urlsafe_b64encode(hmac.new(secret, message, hashlib.sha256).digest()).decode()

print(header + "." + payload + "." + signature)
```
