### ISSUE TITLE
Gateway can't connect to dashboard using self-signed certificate

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1806]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If dashboard deployed using TLS with self-signed cert, gateway will be unable connect to the dashboard with an error saying that certificate verification failed. It works only if dashboard certificate manually added to OS trusted storage.
**What is the expected behavior?**
It should be possible specify an option to skip SSL verification for GW->Dash communication.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7 and earlier

**Comment by ilijabojanovic** [comment]
@buger please merge both PR's release-2.7 branch

**Comment by buger** [comment]
Re-opening, see PR comment.
