### ISSUE TITLE
Bug - Invalidate cache function does not work in Tyk Dashboard v1.6.2

### ISSUE THREAD

**Issue by ghost** [TykTechnologies/tyk#1807]
Bug - Invalidate cache function does not work in Tyk Dashboard v1.6.2

Current behaviour:
1) Edit an API
2) Navigate to Advanced Options tab
3) Ensure Caching middleware is enabled
4) Click "Invalidate Cache" button to invalidate the cache
5) Obtain an error message saying "Failed to Invalidate Cache for API."

Expected Behaviour
1) Edit an API
2) Navigate to Advanced Options tab
3) Ensure Caching middleware is enabled
4) Click "Invalidate Cache" button to invalidate the cache
5) Cache is invalidated successfully

This seems to affect Tyk Dashboard 1.6.2 but we have noticed it in 1.5.4 as well.

On further investigation in the Error console, we are seeing a 502 error - bad gateway and a textual response of "Not found"

Screenshots attached:

Dashboard UI

![image](https://user-images.githubusercontent.com/3499678/42312418-26b14536-8038-11e8-865e-e8e0377affd1.png)

Error in Debug console (Hostname obscured for security)

![image](https://user-images.githubusercontent.com/3499678/42312498-59f18ba4-8038-11e8-99e7-58a20e906efc.png)

**Comment by johncrocker** [comment]
Experimented a little replicating the request using a CURL script. It looks like the Rest API URL on this function is incorrectly coded in the dashboard. According to your documentation here 

https://tyk.io/docs/frequently-asked-questions/clear-api-cache/

The API should be DELETE http://<<hostname>>/**tyk**/cache/5aead9afe8a1350001de2c3b/ 

With the host being the Gateway

Not

DELETE http://<<hostname>>/**api**/cache/5aead9afe8a1350001de2c3b/ 

The URL referred to in the documentation seems to work

Please advise?

**Comment by johncrocker** [comment]
It also looks like there are issues around the Tyk gateway accepting the settings for the cache middleware. Even after disabling caching, we found that Tyk was persisting the cache of the API hence why we wanted to invalidate the cache!

**Comment by buger** [comment]
Hi! thank you for the report. Do you see anything in gateway logs when you receive this error?

**Comment by letzya** [comment]
@johncrocker About the documentation - that link shows REST api call to an endpoint on a Tyk Gateway, while the call you saw on the browser is to the dashboard which manage all the apis and trigger api call `/tyk/cache/` on the gateway.

**Comment by letzya** [comment]
Since it's 502 could you confirm that the gateway define in the field `tyk_api_config`, in tyk_analytics.conf  is running?

**Comment by johncrocker** [comment]
The gateway is running as defined in the configuration file, however do I need to also check if it is running from inside the Dashboard docker container to rule out any connection issues there?

**Comment by johncrocker** [comment]
@letzya  we have altered the configuration as suggested seperatley, however we ran into lots of gateway errors in the logs and rolled the change back.

**Comment by agata-wit** [comment]
As this issue has been raised long time ago I re-checked it in the latest release 3.2.1 and it no longer replicates.
![image](https://user-images.githubusercontent.com/85508803/125924929-2568fca5-efad-4ed4-a108-f8b0afb20a1f.png)

Dashboard calls the following endpoint: 
![image](https://user-images.githubusercontent.com/85508803/125925047-9152d333-98e9-4f2b-8ef9-3df92377a3d1.png)

Closing the issue as it's fixed.
