### ISSUE TITLE
Using SSL at Docker

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#181]
Hi,

if I'm using SSL in Docker, do I have to change something at the ambassador? change the host to https://ambassador or sth.?

SSL in config for tyk but not for tyk_analytics:
- portal works on https 
- test API "could not get any response"
- API dashboard works http

SSL in config for tyk_analytics but not for tyk:
- portal http and just a white page
- test API works on http
- API dashboard works https

SSL in config for both:
- portal https and just a white page
- test API could not get any response
- API dashbaord works https

I trust the certificates on my client but not in my container.. ?

Greetings..

**Comment by lonelycode** [comment]
I would suggest to not run the docker components together but split them out and use publicly addressable network IP's / hostnames to target them instead of plumbing the containers together through the ambassador proxy. They aren't really meant to be run together like they are in the quick start, that's a kludge to make it nice and easy to get started with.

Here's an idea, but I'm not sure exactly if it will work:

1. Put SSL certs for portal domain and for gateway in the tyk.conf since (in the quickstart), it is proxying the traffic to that component
2. For the dashboard, you just need the cert for the dashboard, and you'll need to explicitly set the port

If you are proxying the dash via the gateway too, then you could add the cert to the tyk.conf only as it will handle the offloading.

**Comment by JosephEarl** [comment]
For me I got this working by just configuring SSL in the gateway (with a wildcard cert for subdomains covering both the portal and dashboard), then proxying the dashboard through the gateway.

**Comment by JosephEarl** [comment]
@lonelycode Is there any way to redirect from http to https using the http_server_options ?

**Comment by lonelycode** [comment]
Nope, not yet. You can do it with third party DNS like Cloudflare or whacking a web server in front of Tyk.

**Comment by JosephEarl** [comment]
Actually I'm seeing an issue. Everything works except for requesting API keys (though creating them manually in the dashboard works).

<img width="974" alt="screen shot 2016-02-01 at 15 33 55" src="https://cloud.githubusercontent.com/assets/2513147/12722805/87532d80-c8fe-11e5-919a-49c674e27dc4.png">


When I request a new key through the portal I see the following:
```
tyk-dashboard_1 | time="2016-02-01T15:51:16Z" level=warning msg="Failed to retrieve object: not found" 
tyk-dashboard_1 | time="2016-02-01T15:51:16Z" level=error msg="No menus found" 
tyk-dashboard_1 | time="2016-02-01T15:51:16Z" level=error msg="Trying to create token from cvatalogue with no auth types! No supported auth types!" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=warning msg="Failed to retrieve object: not found" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=error msg="No menus found" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=error msg="Trying to create token from cvatalogue with no auth types! No supported auth types!" 
tyk-gateway_1   | 2016/02/01 15:51:21 http: TLS handshake error from 172.17.0.4:59002: tls: oversized record received with length 21536
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=error msg="Failed to create key: Post http://ambassador_1:8080/tyk/keys/create: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\\x16\"" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=warning msg="Failed create:Failed to create key: Post http://ambassador_1:8080/tyk/keys/create: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\\x16\"" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=error msg="Key creation failed! Failed to create key: Post http://ambassador_1:8080/tyk/keys/create: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\\x16\"" 
tyk-dashboard_1 | time="2016-02-01T15:51:21Z" level=error msg="Generation error: Failed to create key: Post http://ambassador_1:8080/tyk/keys/create: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\\x16\"" 
```

It seems to think the catalogue at first has no supported auth types, but the API is set to auth token. Then there is a lot of bad SSL responses.

**Comment by senj** [comment]
I'm seeing the same issue when trying to request a key.

**Comment by JosephEarl** [comment]
I tried setting the Host to https://ambassador_1 but of course my SSL certificate is not valid for that URL.
I will try generate an SSL cert to be used only for the ambassador URL, and use my cert for the dashboard and portal URLs.

**Comment by JosephEarl** [comment]
OK I got it working. I am serving all components from subdomains (e.g. dashboard.mydomain.com, portal.mydomain.com) using a wildcard SSL.

So I created a new DNS entry valid with that SSL certificate pointing to the machine running Docker (e.g. name it ambassador.mydomain.com) The reason for adding a new DNS entry is my Dashboard and Portal are bound to the others.

Then in my tyk_api_config I changed the host and port to be

```
"Host": "https://ambassador.mydomain.com",
"Port": "80"
```

The downside of this is not all traffic travels within the Docker network, but since it is protected with HTTPS it should be fine.

**Comment by JosephEarl** [comment]
I think it should be possible with just https://ambassador, if you change your SSL config to:

```
"http_server_options": {
    "use_ssl": true,
    "server_name": "*.lenioapp.com",
    "min_version": 2,
    "certificates": [
      {
        "domain_name": "mydomain.com",
        "cert_file": "/opt/tyk-gateway/ssl/mydomain.crt",
        "key_file": "/opt/tyk-gateway/ssl/mydomain.key"
      },
      {
        "domain_name": "*",
        "cert_file": "/opt/tyk-gateway/ssl/selfsigned.crt",
        "key_file": "/opt/tyk-gateway/ssl/selfsigned.key"
      }
    ]
  }
```

So a different SSL cert is used for the ambassador_1. Will give it a try later on.

**Comment by JosephEarl** [comment]
OK I got this working without having to leave the Docker network.

1. Generate a self signed cert for the CN ambassador_1

2. In your tyk-gateway.conf file add both your own cert and the self signed cert for ambassador_1

```
"http_server_options": {
    "use_ssl": true,
    "server_name": "*.mydomain.com",
    "min_version": 2,
    "certificates": [
      {
        "domain_name": "*.mydomain.com",
        "cert_file": "/opt/tyk-gateway/ssl/lenioapp.crt",
        "key_file": "/opt/tyk-gateway/ssl/lenioapp.key"
      },
      {
        "domain_name": "ambassador_1",
        "cert_file": "/opt/tyk-gateway/ssl/ambassador_1.crt",
        "key_file": "/opt/tyk-gateway/ssl/ambassador_1.key"
      }
    ]
  }
```

3. You will need to create a Dockerfile which extends tyk-dashboard and install the ambassador_1.crt as a trusted cert, you can do that with

```
ADD ambassador_1.crt /usr/local/share/ca-certificates/ambassador_1.crt

RUN update-ca-certificates
```

4. Change your Docker compose to use your custom version of tyk-dashboard with the SSL cert installed

**Comment by senj** [comment]
Great work, will try this tomorrow, thanks for sharing.

**Comment by yoanisgil** [comment]
Maybe I'm late to the discussion but I took a shortcut and configured a reverse proxy in front of the Dashboard/Gateway. The admin looks like this:

```
server {
    listen   443;

    ssl    on;
    ssl_certificate /etc/ssl/certs/domain-bundle.crt;
    ssl_certificate_key /etc/ssl/private/domain-private.key;

    server_domain dashboard-server;

    location / {
		proxy_pass http://tyk_dashboard:3000;
    }
}
```

and this is the config for  the gateway:

```
server {
    listen   443;

    ssl    on;
    ssl_certificate /etc/ssl/certs/movingwaldo.ca-bundle.crt;
    ssl_certificate_key /etc/ssl/private/movingwaldo.ca.key;

    server_name gateway-server

    location / {
		proxy_pass http://gateway:8080;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

the reverse proxy is also running on a container. I'm using this setup for our staging environment and it seems to do the job ;)

**Comment by senj** [comment]
As we also want an http cache in front of the gateway this seems to be a viable solution.

Can you please explain
```
 server_domain dashboard-server;
```
what is dashboard-server / gateway-server?

Are these wildcard certificates / are they in the trusted store?

Does this 
```
proxy_set_header Host $host; 
```
influences the routing at the gateway? i want to use path based routing.

Thanks ..

**Comment by JnMik** [comment]
proxy_set_header Host $host; tell the reverse-proxy to forward the client "Header: host" to the backend server

gateway-server and dashboard-server are only hostnames that Yoanis use on his machine, they are proxied to tyk_dashboard:3000 and gateway:8000 respectively.

**Comment by senj** [comment]
roger that. it's nice to have some more info on this topic now.

**Comment by yoanisgil** [comment]
@senj 

Yes, these are wildcard certificates. So for instance if you own *mydomain.com* for which you also have wildcard certificates, the configuration will look like this:

```
server {
    listen   443;

    ssl    on;
    ssl_certificate /etc/ssl/certs/mydomain.com-bundle.crt;
    ssl_certificate_key /etc/ssl/private/mydomain.com-private.key;

    server_domain admin.mydomain.com;

    location / {
        proxy_pass http://tyk_dashboard:3000;
    }
}

server {
    listen   443;

    ssl    on;
    ssl_certificate /etc/ssl/certs/mydomain.com-bundle.crt;
    ssl_certificate_key /etc/ssl/private/mydomain.com-private.key;

    server_name gateway.mydomain.com;

    location / {
        proxy_pass http://gateway:8080;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

You're not forced to use wildcard certificates, as they also cost a little more money, as long as they are valid for the domains declared Nginx's directive *server_name*. As for *proxy_pass* and *proxy_header* notice they are only preset for the gateway configuration, which is the one responsible for forwarding API calls. The reason I went for this is because I'm using the domain listen option when defining my API(s). I guess you can just remove those instructions if you're just using the listen paths option. 

Anyhow this is just my 2 cents on the subject.I find it a bit more easier to deal with and as you said you gain a lot by having Nginx taking care of performing SSL termination, cache, logging and all the cool stuff it comes with ;).

**Comment by senj** [comment]
Thanks for you configs, I got it working now! Just one more question, do you also proxy the portal? I tried with 
```
 server_name gateway.aldocker01.my-tts.net;

    location /portal-assets {
        proxy_pass http://10.66.1.60:3000/;
        proxy_pass_request_headers      on;
    }

    location / {
        proxy_pass http://10.66.1.60:8080/portal/;
        proxy_pass_request_headers      on;
        # proxy_set_header Host            $host;
        # proxy_set_header X-Forwarded-For $remote_addr;
    }
```

but the portal-assets part is wrong...

**Comment by yoanisgil** [comment]
@senj 

If you configure your gateway like this:

```
server {
    listen   443;

    ssl    on;
    ssl_certificate /etc/ssl/certs/mydomain.com-bundle.crt;
    ssl_certificate_key /etc/ssl/private/mydomain.com-private.key;

    server_name gateway.mydomain.com;

    location / {
        proxy_pass http://gateway:8080;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

then you should be able to see at https://gateway.mydomain.com/portal/ (do not forget the trailing slash ;)).

@lonelycode is this setup something you would recommend for production? One of the reasons I like this is because I'd love to have Tyk deploying in production using Docker. With the addition of multi host networking and the aid of Compose  I believe it should be quite easy to get Tyk up and running in production. What do you think?

**Comment by senj** [comment]
So you mean I don't have to proxy to /portal, /portal-assets etc, because the tyk gateway will handle this for me

**Comment by yoanisgil** [comment]
Yes. But make sure you followed the instructions here:

https://tyk.io/v1.9/setup/docker/

especially the part where you replace `localhost` by `ambassador_1 `;)

**Comment by senj** [comment]
If I try this I always get
http: proxy error: dial tcp 172.17.0.10:3001: getsockopt: connection refused
but only for /portal/, my other APIs are working.

**Comment by yoanisgil** [comment]
Weird .. @lonelycode any ideas? I followed the docker setup and everything worked as expected. Did you try starting over from scratch?

**Comment by lonelycode** [comment]
Sorry guys, no idea... internal docker compose wiring is plain weird. I'm a big fan of traditional networking :-)

**Comment by yoanisgil** [comment]
@senj it looks to me like one of the containers is not running. What does your config looks like? On which container do you see the error?

**Comment by senj** [comment]
After reading a lot of docker documentation, especially about networking, I think it's the best to remove the ambassador pattern completly and use user defined networks.
As I understood, this will remove the static (or legacy as the docs call it) linking completly and I can assign each container it's own IP address as lonelycode proposed (although it is a local one).
Because I also want to have multiple gateways in my dev environment (one for each developer) it is cleaner to separate each gateway in it's own network.
It seems there were a lot of network related changes on 1.9 / 1.10 so there is no need for ambassador anymore. I hope I can figure this out tomorrow.

**Comment by JosephEarl** [comment]
Yes - I did this locally with the 1.10 RC2 and it worked fine, was waiting for it to go gold before submitting a PR. Will submit one tomorrow.

**Comment by yoanisgil** [comment]
@JosephEarl the only problem I see with that is that users will be forced to use Docker >= 1.10 (which is quite recent BTW). Anyhow that might not be a concern on a development environment, but yet seems a bit restrictive. I still don't see what went wrong with @senj 's setup though it will be nice if we could reproduce his use case.

**Comment by lonelycode** [comment]
Yeah we had to put old compose configs in to handle naming conventions for previous versions before - not ideal.

... I think keeping things fresh is a good idea, but maybe try and make it reactive to the docker version somehow. 

We could split the repo into multiple directories named after the supported docker versions, with a different compose config for each docker version. 

The official docs then support latest, and then the read me in each folder can be up to date for legacy?

Just an idea...

**Comment by yoanisgil** [comment]
I think that might work. However it stills bug me why 1.9 won't work for @senj ...

**Comment by senj** [comment]
@JosephEarl any update on this?
I'm on 1.10 now and all the components are running, but I don't know what I should enter for
tyk_api_config => host

and in the API definition's target URLs at tyk dashboard.

I use the new -link feature so I can connect the components via alias (this works for redis_host) and put everything in my custom bridge-based network.

**Comment by JosephEarl** [comment]
@senj yes I submitted a PR to improve the quick start a few days ago https://github.com/lonelycode/tyk_quickstart/pull/3
