### ISSUE TITLE
Ability to set host header with TykMakeHttpRequest

### ISSUE THREAD

**Issue by altaurog** [TykTechnologies/tyk#1814]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
If I set `Host` header when making a request with TykMakeHttpRequest, it is ignored:
```
  var request = {
    Method: 'GET',
    Domain: 'http://localhost:34969',
    Resource: '/my/path',
    Headers: {
      'Host': 'myhost.domain.com',
    }
  }
  var res = TykMakeHttpRequest(JSON.stringify(request));
```
The request made looks like this:
```
GET /my/path HTTP/1.1
Host: localhost:34969
User-Agent: Go-http-client/1.1
Connection: close
Accept-Encoding: gzip
```

**What is the expected behavior?**
I would like to see the host header set appropriately:
```
GET /my/path HTTP/1.1
Host: myhost.domain.com
User-Agent: Go-http-client/1.1
Connection: close
Accept-Encoding: gzip
```
This would be really useful where upstream is an internal load balancer that routes requests by hostname.  The DNS entries point to tyk, so we need to be able to make a request using one name for DNS lookup and a separate name for the host header.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tried only on local build of master.

**Comment by joshblakeley** [comment]
Is this with `preserve_host_header` set to true in the api definition?

**Comment by altaurog** [comment]
@joshblakeley yes, for the same reason.

**Comment by altaurog** [comment]
Actually, it looks like this is due to [the behavior of the underling `net/http` lib](https://github.com/golang/go/issues/7682)

**Comment by joshblakeley** [comment]
Thanks, I think the fix is quite straightforward so will schedule it for a bugfix release soon hopefully.

**Comment by altaurog** [comment]
This fixed it for me:
```
diff --git a/mw_js_plugin.go b/mw_js_plugin.go
index 422468f5..1d0529be 100644
--- a/mw_js_plugin.go
+++ b/mw_js_plugin.go
@@ -491,7 +491,11 @@ func (j *JSVM) LoadTykJSApi() {
                }
 
                for k, v := range hro.Headers {
-                       r.Header.Set(k, v)
+                       if strings.ToLower(k) == "host" {
+                               r.Host = v
+                       } else {
+                               r.Header.Set(k, v)
+                       }
                }
                r.Close = true
```

**Comment by joshblakeley** [comment]
I just wrote the identical thing - do you want to push a PR?

**Comment by altaurog** [comment]
Better you do it.  I just needed to get this done, or I would have had to devise some complex workarounds.

**Comment by altaurog** [comment]
Anyways, you probably want to include a test, etc.

**Comment by joshblakeley** [comment]
No problem.

**Comment by altaurog** [comment]
Are there plans to merge a fix for this?
