### ISSUE TITLE
TLS upstream with `renegotiation` not supported

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1815]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Upstream server use TLS and configured to use renegotiation (re-establishing connection from time to time for security reasons), Tyk will fail with TLS error: "no renegotiation support". 
**What is the expected behavior?**
It should be supported, at least optionally.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7 and below

**Comment by buger** [comment]
By default Go client does not support it but can be optionally enabled https://golang.org/pkg/crypto/tls/#RenegotiationSupport

I wonder if we can enable it by default.

Way to overcome the issue will be disabling keep-alive connections.

**Comment by joshblakeley** [comment]
I think we can do this quite simply and make it configurable - so if something like `allow_SSL_renegotiation` is `true` we change the enumeration before first connection and it will be allowed.

The Go team really don't like allowing it from what i've read.

**Comment by afrizalchen** [comment]
@joshblakeley , I tried enabling `allow_SSL_renegotiation`. I'm still getting the same tls "no renegotiation support" error. I did restart the gateway :-). I've also enabled debug-logging,  however there's no additional information. Do you have other suggestion? Thanks.

**Comment by joshblakeley** [comment]
That won't work as there is no implementation for it in Tyk as of yet. What should work in the meantime is setting proxy_close_connections to true in tyk.conf

**Comment by afrizalchen** [comment]
@joshblakeley, apologize for putting the wrong information. What I meant is setting `proxy_close_connections` doesn't work for me. I was using version 2.6.2 then upgraded to 2.7.0.
Today I checkout the source code and added `transport.TLSClientConfig.Renegotiation = tls.RenegotiateFreelyAsClient` to httpTransport() of reverser_proxy.go. This works.

**Comment by joshblakeley** [comment]
Ok no problem. Yes that is expected with that change - it will very likely be included in our first 2.7 patch.
