### ISSUE TITLE
Better api security

### ISSUE THREAD

**Issue by altaurog** [TykTechnologies/tyk#1816]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I am not a security expert, but the security of tyk’s own REST api doesn’t inspire much confidence.  Here are the docs for the global `secret` setting.
> This should be changed as soon as Tyk is installed on the system. This value is used in every interaction with the Tyk REST API, it should be passed along as the X-Tyk-Authorization header in any requests made. Tyk assumes that you are sensible enough not to expose the management endpoints to the public and to keep this configuration value to yourself.

Given all the various methods tyk implements for auth, it is surprising that nothing more sophisticated is offered here.

**What is the expected behavior?**
It would be nice to have the same options here as on other apis, but barring that, it would seem to me that for better security
1. The config var should be a hash, not the secret itself
2. [Comparing the secret](https://github.com/TykTechnologies/tyk/blob/master/main.go#L401) should rather be [done in a way](https://golang.org/pkg/crypto/subtle/) that isn’t vulnerable to timing attacks.

Curious to know if any of tyk’s auth mechanisms have undergone security audit?

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
looking at master for first time.

**Comment by asoorm** [comment]
Thank you for your feedback. I think a docs update with clearer guidance on how to harden Tyk for production would be useful.

For example, the following config settings are available:

`control_api_hostname` The hostname to bind the admin control API.
`control_api_port` Allowing you to have the gateway api listen on a separate port to general API traffic, and hide it behind firewall if required.

Meaning that you do not have to expose the admin api at all.

**Comment by afrizalchen** [comment]
You could consider to allow any additional authentication like:
- IP Whitelisting
- MTLS
The endpoints already support these, why not apply them to the Tyk itself.

**Comment by asoorm** [comment]
@afrizalchen @altaurog The Control API supports MTLS already. https://tyk.io/docs/security/tls-and-ssl/mutual-tls/#gateway this feature works when control api is on it's own port/domain.

If you need to introduce IP whitelisting, blacklisting, other security for the control api, you could always configure Tyk to proxy to itself.
