### ISSUE TITLE
Allow multiple interactive documentations to be attached to an API

### ISSUE THREAD

**Issue by JosephEarl** [TykTechnologies/tyk#182]
I have 3 services, A, B and C running on separate instances each with it's own Swagger.

I can add 3 APIs to Tyk, then create an API catalogue that combines all 3, but I can only set one Swagger link.

The solution currently is to put each API in it's own catalogue, but ideally I would like to be able to host all docs in a single catalogue.

**Comment by lonelycode** [comment]
It depends on how you want to expose your API - the portal only exposes policies, not actual APIs, so you have 3 API's, that you want to grant access to via a single token for a developer. So you bundle all three APIs into a single Policy. So now your three services look like one single service to the public. 

Now your docs need to reflect that, so your 3 swagger docs should really be a single doc that describes your "public" API.

If you have three APIs that you want three sets of access too, then you want 3 swagger files, since you would have 1 token per API and they are all independent.

The balance we've struck is: Whatever sits behind Tyk can be an absolute mess of services, what you present to the public should be carefully controlled. Whether that is with blueprint or swagger, or even just markdown pages, but it needs to be controllable.

Will leave this open to see if there is more interest.

**Comment by JosephEarl** [comment]
If Tyk could help creating that single public Swagger by aggregating the individual Swagger docs for each service/endpoint that would be useful for me.

I'll do it manually for now, thanks!

**Comment by JosephEarl** [comment]
So I combined my Swagger files into one with a simple Ruby script and pasted that into the portal docs.
It loads fine - but the portal seems to be prepending a random listen path (from the APIs I attached to my policy, changes each time I refresh) so I end up with a double listen path `/listen-path1/listen-path2/` and the call fails.

**Comment by lonelycode** [comment]
We do a lot of hackery to overwrite and set the API domain, and swagger docs all contain root domain values. So there's a limit to what we can do there I'm afraid.

**Comment by lonelycode** [comment]
Can you share the JSON so we can look at it, maybe we can fix it in a future release.

**Comment by JosephEarl** [comment]
Attached is a zip containing the combined swagger and the individual swagger files. 
[swagger.zip](https://github.com/TykTechnologies/tyk/files/108688/swagger.zip)

In the combined swagger I prefixed each path with the listen-path of that API in Tyk.

**Comment by lonelycode** [comment]
Hmmm, that's 404ing.

I think you want to keep the listen_path out of the swagger doc as Tyk *should* add that for you (since it may change with your API def)

Can you re-up or do a GDrive link?

**Comment by JosephEarl** [comment]
I re-uploaded, should work now. How does Tyk know the listen path to add? - since the combined Swagger docs represent multiple Tyk APIs with different listen paths.

**Comment by lonelycode** [comment]
You've found a bug :-) We need to fix that...

**Comment by JosephEarl** [comment]
Maybe it's time I learned Go :smile: ...

**Comment by JosephEarl** [comment]
Also a catalogue could contain multiple APIs with different custom domains, in which case you can't really show a Swagger doc - so perhaps in that case it would just be better to disable the input and show a message explaining that in order to use Swagger all APIs must have the same domain.

**Comment by lonelycode** [comment]
:+1:

**Comment by JosephEarl** [comment]
Code used to combine the Swagger files is here: https://gist.github.com/JosephEarl/334ee0612decc3aaf4eb

**Comment by JosephEarl** [comment]
Another approach would be to let the user attach a Swagger document per API, rather than per catalogue, then the portal could combine them into one and add the listen paths itself.

**Comment by JosephEarl** [comment]
So I almost managed to work around it.

I changed my 4 individual APIs with listen paths to use private-gateway.domain.com
Then I set up another API to use public-gateway.domain.com with root listen path and point to private-gateway.domain.com

This works with no auth enabled when curling which is great!

I imported my combined Swagger and the URLs look correct, but I just see 
```
{
  "error": "no response from server"
}
```
in Swagger UI in the portal (curling the same URL shown in request URL works fine) :cry: 

My plan for enabling auth was: create a key that had access to the individual APIs that never expired, and set the main API to add this to the headers. Then secure access to the main with API.

However problem 2 is that I can't seem to manually create a key (in Keys) that has access to those individual APIs - I keep getting "Key not authorised". Maybe it's because I don't have a catalogue or policy with them in?

**Comment by lonelycode** [comment]
Did you look at the chrome dev tools network view? I bet it was a CORS failure.

Swagger gives terrible error messages, that's a canned response.

In your public API, enable CORS and especially options pass through so that the upstream service handles CORS.

**Comment by JosephEarl** [comment]
Will check that out. Got my auth working, seemed to just be cached keys or something.

**Comment by JosephEarl** [comment]
Checked the dev tools - it is a CORS issue. Thanks.

I enabled CORS on the public API in Tyk and added the portal domain as an allowed origin, but I'm not seeing it return the `Access-Control-Allow-Origin` header. I didn't enable options pass through because my upstream application doesn't actually handle CORS at this point.
