### ISSUE TITLE
Response body tranformation issue

### ISSUE THREAD

**Issue by Davissi** [TykTechnologies/tyk#1828]
**What is the current behavior?**
I am currently getting the below response whenever I query my endpoint

{
    "count": 1720256,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    }
}
**What is the expected behavior?**
I am trying to remove the "_shards" portion and only return the count. below is a screenshot of the endpoint designer

![image](https://user-images.githubusercontent.com/40687181/42865443-3cac572c-8a9c-11e8-9b28-ec5c4d900c97.png)

After I created the above endpoint, I am still getting the same response when I query the API. I am new to tyk so I may have created it wrongly. Appreciate if anyone can help with this.

Thank you!

**Comment by Davissi** [comment]
I realized that the issue was because the strip listen path checkbox was checked. Now it is able to detect the endpoint but not able to assign the value correctly

![image](https://user-images.githubusercontent.com/40687181/42866147-59d202be-8a9e-11e8-8daa-0edd1a49fdf4.png)

Thank you in advance

**Comment by asoorm** [comment]
Interesting, I may be wrong, but believe is still valid. `1.720256e+06` is just scientific notation for `1720256`.

Despite this, I need to check why it is converting after 7 digits.

Regarding your 2nd issue - this means that whatever your upstream returned from that endpoint, it doesn't contain a `count` object. so it indicates you may be hitting the wrong path.
