### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#183]
Hi, if I'm building a Tyk custom middleware or implementing an API for ex. generating endpoints automatically, how does the licensing work? Is it compatible with other licenses?

A more concrete example: I code a custom middleware and plan to release it under another open source license (MIT etc). Is it allowed?

**Comment by lonelycode** [comment]
This is the license for Tyk Gateway:

https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md

And here's the tldr :-)

https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

Of course we'd love to get a PR if your middleware is awesome :-)

**Comment by matiasinsaurralde** [comment]
Cool, thanks!
