### ISSUE TITLE
Feature Request: Caching independent of key

### ISSUE THREAD

**Issue by aaronhurley** [TykTechnologies/tyk#1831]
It would be useful for some apis, if responses could be cached independent of the authorisation key. This would be useful, when the information requested is not customer specific. It would be easy enough to test, with an api which simply returns the date and time.

**Comment by matiasinsaurralde** [comment]
Can you provide a more detailed sample scenario?
Have you checked our [caching documentation](https://tyk.io/docs/reduce-latency/caching/)?
