### ISSUE TITLE
Enable UI user to copy over endpoints from one version to another

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1832]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
When adding a new version of api, in the endpoint designer you'll get blank screen with zero endpoints.
In this situation even swagger import won't help since the other version has already all the Tyk's specific configurations.

**What is the expected behavior?**
To be able to copy the endpoints from another version or get it from the previous version as a base line to start working with.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The use case is when you have A LOT of endpoints with specific configurations, that have only slightly change from one version to the other, it would make sense for the users to get a copy of the current version as a baseline for the new version, instead of manually copy paste the specific lines in the api def
![image](https://user-images.githubusercontent.com/3155222/42899116-f7931f38-8abc-11e8-9a0d-c8a2d0ae2cc5.png)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Opened after 2.7 was released

**Comment by ConsM** [comment]
I believe this needs a bit of UX , @ViolaMarku 
So basically if i have 5 versions, i need to be able to copy the endpoints from on to an other
