### ISSUE TITLE
There is no way to access regexp group inside URL rewriter

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1833]
**Do you want to request a *feature* or report a *bug*?**
bug/feature
**What is the current behavior?**
Advanced URL rewriter allows you to define regexp matches against values, but at the moment you get only whole "matched" value, and if you are using groups, they basically useless.
**What is the expected behavior?**
At the moment Tyk define special `$tyk_context.trigger-{n}-{name}-{i}` https://tyk.io/docs/transform-traffic/url-rewriting/ context value which holds trigger matched string. I propose extend it, and define additional level, which allows you specify group index too `$tyk_context.trigger-{n}-{name}-{i}-{group}`

This is especially needed for handling SOAP based protocols, then you will be able to define body regexp like: `<wsdlsoap:address location="https://example.com/([^"]+)"``, and inside rewrite_to use it like: `$tyk_context.trigger-0-payload-1`, which will give us automatic mapping between SOAP actions and Tyk endpoints. 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7

**Comment by dskoval** [comment]
Interested to work on this
I propose following as implementation:
- `$tyk_context.trigger-{n}-payload` - correspond to first match (as current implementation)
- `$tyk_context.trigger-{n}-payload-{i}` - i'th regexp match (i starts from 0)
- `$tyk_context.trigger-{n}-payload-{i}-{g}` - g'th capturing group for i'th regexp match (g starts from 0)

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1973 was merged to `release-2.7` branch
<details><summary></summary>Created via API</details>

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1973 was merged to `release-2.8` branch
<details><summary></summary>Created via API</details>
