### ISSUE TITLE
apidef: support matching multiple methods / http verbs

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1835]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

 If I wish to blacklist a path across multiple methods, I need to specify a blacklist plugin on each method which I wish to blacklist.

| verb | path | plugin |
---------|------|------|
| POST | /products(.*) | blacklist |
| PUT | /products(.*) | blacklist |
| PATCH | /products(.*) | blacklist |
| DELETE | /products(.*) | blacklist |

**What is the expected behavior?**

For convenience and to improve UX, I should be able to apply plugins on a list of verbs

| verb | path | plugin |
---------|------|------|
| POST\|PUT\|PATCH\|DELETE | /products(.*) | blacklist |

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All

**Comment by buger** [comment]
As a more simple solution, which can be implemented right away, I would suggest implementing a wildcard option, which matches ALL methods.

**Comment by asoorm** [comment]
@buger as MVP - The `ALL` methods or `*` methods would not allow us to exclude specific http verbs.

e.g. if I wanted to blacklist all non `GET` requests to a specific path.

I know that this can be achieved at policy level, but it may be useful to do at the api definition level.
