### ISSUE TITLE
Have caching optionally take into account POST bodies

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1838]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Caching cannot take into account POST bodies

**What is the expected behavior?**

Caching should have an option to hash POST bodies and use that as part of cache key

Again an option, default behavior leave as is, but per api-def, a flag to permit this.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

We have requests where the URI/querystring does not change but the contents of the POST body do vary (not huge bodies, but small ones) where the params are in the body, not the URI.

We cannot cache this data.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.6.2+

**Comment by buger** [comment]
Right now it works like his:
1) Only safe methods can be cached
2) If you checked only "Enable caching", then endpoint will be cached only if you set "Cache" plugin to endpoint
3) If you check "Cache all safe requests" then it will cache all safe request by default, without needing step 2)

With this new functionality, if you set "Cache" plugin for POST endpoint, it will automatically understand it and will cache POST by the whole body.
Cache plugin for POST/PUT requests will have additional "cache key regexp" field, where you can optionally specify regexp to extract cache key from the body.

Note that even if you enable "Cache all safe requests", then POST request will not be automatically cached. You always had to explicitly set "Cache" plugin for them.

Assigning @komalsukhani for this ticket ^

**Comment by bitsofinfo** [comment]
I'm confused, so this is already functionality that is enabled? or no (per the assignment)

**Comment by komalsukhani** [comment]
@bitsofinfo It is under development.

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
not stale @buger
