### ISSUE TITLE
2.7.0 downloaded middleware bundles "no such file or directory"

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1839]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

In 2.6.2 the hybrid gateways load the configured bundle zip files from our bundle server fine and load them property. Bringing up a 2.7.0 gateway we see the bundles are downloaded and extracted under

middleware/bundles/[someguid]_[someguid]/[contents of zip file]

However the tyk gateway appears to be trying to load them from a different path....which fails

```
time="Jul 24 09:08:02" level=info msg="----> Loading bundle: myPlugin-something.zip"
time="Jul 24 09:08:02" level=info msg="----> Verifying bundle: myPlugin-something.zip"
time="Jul 24 09:08:02" level=info msg="----> Bundle is valid, adding to spec: myPlugin-something.zip"
time="Jul 24 09:08:02" level=info msg="----> Loading bundle: myPlugin-something.zip"
time="Jul 24 09:08:02" level=info msg="Loading JS File: /opt/tyk-gateway/middleware/bundles/06cb8cxxxxx-myPlugin-something.zip/myPlugin.js"
time="Jul 24 09:08:02" level=info msg="----> Verifying bundle: myPlugin-something.zip"
time="Jul 24 09:08:02" level=error msg="Failed to open JS middleware file: open /opt/tyk-gateway/middleware/bundles/06cb8c6daxxxxxx-myPlugin-something.zip/myPlugin.js: no such file or directory"
```

Shelling into the container, indeed these paths do not exist, the paths that DO exist are in a different format listed above. `middleware/bundles/[someguid]_[someguid]/[contents of zip file]`

**What is the expected behavior?**

Should work, without this none of our apis function as the plugins are needed

Looks like something changed in the way tyk WRITEs the bundles to disk, however the part that READS the bundles missed this change?

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.7.0

**Comment by matiasinsaurralde** [comment]
Can you share the manifest file you're using to build this bundle?
Thanks

**Comment by bitsofinfo** [comment]
pretty much like this, there are several diff ones, but they are all similar to this 

```
{
      "file_list": [
        "step1.js",
        "step2.js",
        "step3.js",
        "step4.js"
      ],
      "custom_middleware": {
        "pre": [
          {"name": "step1", "path":"step1.js"},
          {"name": "step2", "path":"step2.js"},
          {"name": "step3", "path":"step3.js"},
          {"name": "step4", "path":"step4.js"}
        ],
        "post": [],
        "driver": "otto"
      },
      "checksum": "",
      "signature": ""
}
```

**Comment by matiasinsaurralde** [comment]
@bitsofinfo Thanks, this will be useful for testing our patch

**Comment by bitsofinfo** [comment]
any eta on this?

**Comment by buger** [comment]
@bitsofinfo 2.7.1 release should happen next week
