### ISSUE TITLE
bundle_base_url & enable_bundle_downloader should support basic-auth

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#1842]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

no way to specify any security for `bundle_base_url`

**What is the expected behavior?**

Would be good to be able to specify basic auth or another custom header value to use when pulling bundle zips from this location (i.e. i'd like to use s3 for the zips and not wide open)

**Comment by bitsofinfo** [comment]
could this be sneaked into 2.7.1 please :)

**Comment by asoorm** [comment]
Hi there, instead of using the bundle downloader - would you be able to put the bundle manifest directly into the API definition?

e.g. for pre-hook as an example, in API definition add this object into `custom_middleware.pre` array:

```
"pre": [
        {
          "name": "somePreMiddleware",
          "path": "middleware/somePreMiddleware.js",
          "require_session": false
        }
      ]
```

**Comment by bitsofinfo** [comment]
sure, but our bundles are separate from our docker images, we need them to remain agnostic of them, the files need to come from somewhere and we don't want to bake the plugin js files into the container images

**Comment by asoorm** [comment]
my understanding is that 2.7.1 release is scheduled for next week and will be a patch-release. I think it's a bit late in day to include this feature request for next week.

Have you thought about signing the bundle with a private key? or is it just that the manifest itself needs to be secured entirely?

**Comment by buger** [comment]
@bitsofinfo just an idea, you can proxy bundle URL with Tyk itself, and instead of basic http auth, and api key protection via url, or similar.

**Comment by bitsofinfo** [comment]
yes, just too complicated, i need the actual endpoint secured, not a proxy (storing on s3 bucket w/ ba protection)

**Comment by bitsofinfo** [comment]
If the above works, then no need necessary, will need to try it

**Comment by asoorm** [comment]
@bitsofinfo Let me know how you get on.
