### ISSUE TITLE
feature: authentication data extraction for both XML & JSON body

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1855]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

At present, it is not directly possible to support payload auth, without custom middleware.

Use-Case: credentials are provided in the payload as follows:

```xml
<Credentials>
  <User>12345</User>
  <Password>XXXXX</Password>
</Credentials>
```

In order to support this, we currently require `pre` middleware to extract the username & password and inject it into an auth header to allow the gateway to handle the basic-auth

gist for pre-middleware example as follows: https://gist.github.com/asoorm/9fa08b9fac930a6efec6c6d227b415e7

**What is the expected behavior?**

This feature should not be limited to basic-auth, but for all auth. We should be able to extract via `xpath` or `jsonpath`

This pre-middleware could be run within default middleware and it's sole responsibility would be to extract the credentials from the payload and inject into appropriate header natively.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

All

**Comment by matiasinsaurralde** [comment]
The ID extractor has a XPath functionality that's able to extract credentials from this type of request bodies (only a single expression), however this is more complex because of the JSVM limitations. Mentioning this in case its interface is useful.

**Comment by buger** [comment]
I believe it should be part of basic auth middleware (and for example auth token middleware too, if the token should be extracted from the body).

**Comment by ilijabojanovic** [comment]
@buger I we tested this implementation all working as expected.

When we extract user and pass from payload in response headers we have this info:

`Www-Authenticate →Basic realm="Test"`

![Screen Shot 2019-04-01 at 5 36 07 PM](https://user-images.githubusercontent.com/8557292/55341091-4b87b500-54a6-11e9-8287-c54a4ebe5635.png)
