### ISSUE TITLE
feature: expose config_data to native plugins

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#1856]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

in order to access `config_data`, we need to create middleware / jsvm

**What is the expected behavior?**

I should be able to access `config_data` via native plugins - e.g. header injection / body transform. e.g. `$config_data` or have that `config_data` stored inside `$tyk_context`.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

all

**Comment by tomshy** [comment]
anything on this??

**Comment by asoorm** [comment]
not stale
