### ISSUE TITLE
Feature request: as a portal admin I would like to have API key request emails batched to avoid email overload

### ISSUE THREAD

**Issue by josephearl** [TykTechnologies/tyk#186]
As a portal admin I would like to receive an email when there is a new API key request to approve.

On high volume sites, I would like the ability to have a batch email once per day (at the start or end) with the number of outstanding requests so that my inbox does not get flooded.

On low volume sites, I would like the ability to have an email per key request.

**Comment by lonelycode** [comment]
Email notifications for this are already supported in the dashboard, [documented here](https://tyk.io/v1.9/configuration/dashboard-config/#email-backend:8f1ac6c580c2f6cd2c8954a33f3ca4d6), add appropriate settings to your org object:

```
event_options: {
    key_request_event: {
      webhook: "",
      email: "developer.support@email.com"
    }
  },
```

You'll also need: https://tyk.io/v1.9/configuration/dashboard-config/#email-backend:8f1ac6c580c2f6cd2c8954a33f3ca4d6

Batch emails are a good idea though.

**Comment by JosephEarl** [comment]
I missed that - was looking at the "Sending emails" section of the docs. Thanks looks like what I want!

**Comment by JosephEarl** [comment]
Sorry that first link didn't work - was the same as the second.

**Comment by lonelycode** [comment]
https://tyk.io/dashboard-v0-9/events/events-notifications/

That's the one...

**Comment by JosephEarl** [comment]
Great thanks. Quick q: can I remove the .txt email templates and just keep the .html ones if I want to send HTML email only?

**Comment by lonelycode** [comment]
Mandril needs both, but I've never actually received a txt one. 

You could try, it may crash.
