### ISSUE TITLE
Dashboard can't connect to Azure CosmosDB

### ISSUE THREAD

**Issue by Sarcouy** [TykTechnologies/tyk#1869]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Tyk dashboard can't connect to an Azure Cosmos DB whereas it is configured to use MongoDB API.
startup sequence looping and failing to reach server:
 tyk-analytics[6218]: time=“Aug 16 10:32:28” level=info msg="connecting to MongoDB: [tfex-cosmos-db-70176.documents.azure.com:10255]"
tyk-analytics[6218]: time=“Aug 16 10:32:39” level=fatal msg="Couldn’t establish a connection with Mongo: no reachable servers"

**What is the expected behavior?**
Tyk dashboard log in and start working properly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a CosmosDB on Azure that uses a MongoDB API.
Reference the connection string in the setup.sh =>
sudo /opt/tyk-dashboard/install/setup.sh --listenport=3000 --redishost=localhost --redisport=6379 --mongo=mongodb://tfex-cosmos-db-70176:bmvVV[...]J6H3A==@tfex-cosmos-db-70176.documents.azure.com:10255/tyk_analytics? --tyk_api_hostname=$HOSTNAME --tyk_node_hostname=http://localhost --tyk_node_port=8080 --portal_root=/portal --domain="127.0.0.1"

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard 1.7.0 and Dashboard 1.6.0 at least. I don't know for previous versions

**Comment by joshblakeley** [comment]
Hi it looks like there is a little more setup to do for the connection string to the DB as the cosmosDB instance is behind your azure account - see their docs here:


https://docs.microsoft.com/en-us/azure/cosmos-db/connect-mongodb-account#GetCustomConnection

**Comment by Sarcouy** [comment]
Right. 
I had to add : 
{
    "mongo_ssl_insecure_skip_verify": true,
    "mongo_use_ssl": true,
}

Now it works fine ! 

Thank you for help ! 


Thank you for making me double check

**Comment by letzya** [comment]
Problem solved
