### ISSUE TITLE
Body Transform does not match correctly with URL Rewrite

### ISSUE THREAD

**Issue by veger** [TykTechnologies/tyk#187]
Hello,

I am defining an API with a URL rewrite to match the API to an existing one and a Body Transform, in order to match the body response to the expected response of the (new) API.

The URL Rewrite is as follows

```
"url_rewrites": [
    {
    "path": "my_service/id/{id}",
    "method": "GET",
    "match_pattern": "state/id/(\d+)",
    "rewrite_to": "some/path/service?servicename=my_service&id=$1"
    }
],
```

So far so good, the request is properly redirected to the existing API.

Now I want to modify the body of the response (throwing away some 'internal' data):

```
"transform_response": [
    {
    "template_data": {
        "template_mode": "blob",
        "template_source": "some response in Base64 encoding"
    },
    "path":  "my_service/id/{id}",
    "method": "GET"
    }
],
```

Unfortunately, this transformation is not triggered when a request to `my_service/id/{id}` is done. Even though the path is exactly the same as for the URL rewrite.

I discovered that the transform is working when the URL Rewrite is removed. So that made me wonder whether I need to change to path to something the matches the rewritten URL, which seems the case as changing path to `some/path/service{questionmark}servicename=my_service&id={id}` is working!

I suppose this is a bug as such behavior seems weird, as I need a different path than the API defines in order to match the response??

**Comment by lonelycode** [comment]
What version are you running? The transforms happen before rewrites atm:

https://github.com/TykTechnologies/tyk/blob/master/main.go#L641

Which makes this behaviour difficult to explain ;-)

**Comment by veger** [comment]
Tyk gateway (and dashboard) installed as Ubuntu package. Version 1.9.1.1 (and 0.9.7.2 for dashboard)

**Comment by veger** [comment]
The body response transform also happens before the rewrite? As this transform needs to be executed after a response is received, and thus a rewrite is already done..? (I am quite new to golang, so I am not yet able to check the code at such detail level)

**Comment by lonelycode** [comment]
Ah, wait, f course, sorry - I read that as a *request* body transform. 

Right, if the response is being transformed then it will run after the rewrite, which would explain why you need to match a different URL.

I see the issue though, seems a little counter-intuitive to match two different paths in and out.

**Comment by veger** [comment]
Basically, I would expect to define an endpoint and have everything matching that one in a (sort of) session. So independent of modifications to the request, body or other data.

Is it possibility to change/fix Tyk in such a way? Or should I keep using my/the current work around?

**Comment by lonelycode** [comment]
Use the workaround, tracking number two paths and this kind of middleware interaction is a bigger task that isn't done lightly.
