### ISSUE TITLE
Rate limit don't work under high QPS 

### ISSUE THREAD

**Issue by buxingzhe** [TykTechnologies/tyk#1876]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Tyk uses a rolling window algorithm based on Redis commands like ZREMRANGEBYSCORE, ZRANGE, ZADD, EXPIRE. It always adds the new request track record first before rate limiting check.

**What is the expected behavior?**
When QPS is so high that it reaches the rate limit, then the incoming requests are rejected but these rejected requests are still counted(i.e. recorded) like normal requests in Redis. The problem is, from that point, all requests are rejected and can't recovering under high QPS.
The expected behavior should not counted the rejected requests when rate limit has reached.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Set rate limit as 5 requests/second
2. Send 10 requests/second against gateway continuously.
3. Gateway will reach rate limit and after that time, it won't service any request and always complains too many requests.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk 2.3+

**Comment by buger** [comment]
Hello! Thank you for the report.  You should also try using our in-memory rate limiter (which is actually turned on by default now), by ensuring that both `enable_sentinel_rate_limiter` and `enable_non_transactional_rate_limiter` are set to false

**Comment by buxingzhe** [comment]
Actually, we have tried the in-memory rate limiter, but it didn't fix the issue either.

**Comment by buxingzhe** [comment]
It seems working now with in-memory rate limiter. But we deploy gateway as a cluster, does in-memory rate limiter check the rate globally?

**Comment by buger** [comment]
Yes, it works across gateway cluster, since while it in-memory, multiple gateway instances constantly sync rate limits via Redis pub-sub mechanism.

**Comment by buxingzhe** [comment]
That's great, does it work in Tyk 2.3? Currently, we use Tyk 2.3

**Comment by buger** [comment]
DRL supported it from the start, so it should. But anyway, I would recommend updating to recent versions, since 2.3 version is not officially supported anymore.

Cheers.

**Comment by wlf061** [comment]
If we use DRL,  should we set the db_app_conf_options.node_is_segmented  to ture and set all nodes' db_app_conf_options.tags as the same?

**Comment by buger** [comment]
@wlf061 if you have setup with multiple gateway clusters, connected to the same redis, yes.

**Comment by utkarsh079** [comment]
I am seeing the same issue in kubernetes and have tried both the methods
https://github.com/TykTechnologies/tyk/issues/5919
