### ISSUE TITLE
What is the algorithm of the memory rate limiter?

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#1877]
For the memory rate limiter is a token bucket limiting algorithm or a leaky bucket limiting algorithm?

**Comment by buger** [comment]
Leaky bucket

**Comment by joshblakeley** [comment]
Its based on a leaky bucket algorithm.

**Comment by penhauer-xiao** [comment]
@joshblakeley  Is there support for the token bucket limiter algorithm?

**Comment by joshblakeley** [comment]
No we just implement leaky bucked for our distributed rate limiter currently.

**Comment by penhauer-xiao** [comment]
@joshblakeley  Thanks
