### ISSUE TITLE
Multiple issues with gateway config parser

### ISSUE THREAD

**Issue by pikeas** [TykTechnologies/tyk#1880]
I'm test driving Tyk (2.7.0) and in my first 10 minutes have already found four issues with how `tyk.conf` is parsed.

1) When `template_path` is omitted:

```
panic: html/template: pattern matches no files: `error*`

goroutine 1 [running]:
html/template.Must(0x0, 0x1012c80, 0xc420197c50, 0x1012c80)
	/usr/local/go/src/html/template/template.go:372 +0x54
main.setupGlobals()
	/src/github.com/TykTechnologies/tyk/main.go:170 +0x57e
main.initialiseSystem(0x0, 0xe60562)
	/src/github.com/TykTechnologies/tyk/main.go:809 +0x2e0
main.main()
	/src/github.com/TykTechnologies/tyk/main.go:892 +0x112
```

This should either use a default value for the path or throw a friendly error message.

2) When the conf file is malformed:

```
[Aug 21 21:43:10] FATAL main: Error initialising system: couldn't unmarshal config: invalid character '}' looking for beginning of object key string
```

This should be a friendlier error message (many people will be unfamiliar with the term "unmarshall") and include the line number where the parse error occurred.

3) When `storage.port` is omitted:

```
[Aug 21 21:52:56] ERROR Could not EXPIRE key: dial tcp: lookup redis on 127.0.0.11:53: no such host
```

This should use the default port (6379) or throw a config error.

4) Linter starts the service:

```
root@f89ea8704c81:/opt/tyk-gateway# ./tyk lint
found no issues in tyk.conf
[Aug 21 22:10:10]  INFO Connection dropped, reconnecting...
[Aug 21 22:10:10]  INFO main: PIDFile location set to: /var/run/tyk/tyk-gateway.pid
[Aug 21 22:10:10]  INFO main: Initialising Tyk REST API Endpoints
[Aug 21 22:10:10]  INFO host-check-mgr: Starting Poller
[Aug 21 22:10:10]  INFO Redis connection pools are ready after number of retires currRetry=0
[Aug 21 22:10:10]  INFO main: Redis connection pools are ready
[Aug 21 22:10:10]  INFO main: --> Standard listener (http) port=:0
[Aug 21 22:10:10]  INFO main: Setting up Server
[Aug 21 22:10:10]  INFO main: Gateway started (v2.7.0)
[Aug 21 22:10:10]  INFO main: Initialising distributed rate limiter
[Aug 21 22:10:10]  INFO main: --> Listening on address: (open interface)
[Aug 21 22:10:10]  INFO main: --> Listening on port: 0
[Aug 21 22:10:10]  INFO main: --> PID: 10
[Aug 21 22:10:10]  INFO Starting gateway rate limiter notifications...
[Aug 21 22:10:10]  INFO main: Loading policies
[Aug 21 22:10:10]  INFO main: Detected 0 APIs
[Aug 21 22:10:10]  WARN main: No API Definitions found, not reloading
```

The config linter should only, well, lint, it should not start the service.

Overall, this isn't a great first impression from a product that's meant to be prod-ready.

**Comment by matiasinsaurralde** [comment]
Hi, thanks for the feedback.
Also we suggest using the setup script, explained [here](https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/gateway/#set-up-tyk).

**Comment by joshblakeley** [comment]
I can't reproduce the panic when template path is omitted - we populate it with the default value if the field is empty or missing.

@pikeas what do you think is a friendlier term than unmarshal? :)

**Comment by asoorm** [comment]
I agree. Unmarshal is not a friendly term.

Simply “malformed config file” or “your Json config is invalid” or “cannot parse json config” messages are more friendly.

**Comment by pikeas** [comment]
@joshblakeley The panic happens every time with the following config file (assuming the given Redis instance is reachable):

```
{
    "storage": {
        "type": "redis",
        "host": "redis",
        "port": 6379
    }
}
