### ISSUE TITLE
Api SLA - if an API is not responding within certain time and after threshold of 80% an event is fired

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1891]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Not existing.  If an API is not responding within 300 but 500ms - if means there might be a problem with the backend service, but the dev op would not know until the requests actually fail ( circuit breaker tripped after certain number of failed requests)

**What is the expected behavior?**
If an API is not responding within 300 but 500ms - after threshold of 80% delayed requests a special event is fired (notifying the dev ops that the API might be busy and is getting overloaded).
It's basically merging uptime tests and circuit breaker.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7

**Comment by buger** [comment]
I think it also make sense to add option that circuit breaker will only generate "events" and will not actually break the execution. In this specific case only events are needed.

**Comment by letzya** [comment]
My thoughts exactly! If we do the same for uptime tests will it actually implement this feature?
