### ISSUE TITLE
Fail fast if a configuration error occurs on startup

### ISSUE THREAD

**Issue by sybrandy** [TykTechnologies/tyk#1892]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If there is an error with the tyk_analytics.conf file, and perhaps others (untested), the service continues to try to operate even though it will most likely fail.  In this case, it tried and failed to connect to Redis and since it was reporting the failures, it hid the fact a configuration error occurred.

**What is the expected behavior?**

The service should have stopped and reported the configuration error.  Since it would not have been able to obtain the correct information, it won't be able to operate correctly anyway, so it should just stop.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a new tyk_analytics.conf file, but remove a required comma from the end of a line, such as the license.
2. Attempt to start Tyk Dashboard using the malformed config file.
3. Observe the logs.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Tyk Dashboard 1.7.1 based on the Docker container tag.  Unknown if previous versions behaved differently.

**Comment by joshblakeley** [comment]
We have the `tyk lint` command in the gateway which can validate the config against a schema. It would be good to have a similar functionality in the the dashboard. I'll add it to our backlog.
Thanks, Josh

**Comment by sybrandy** [comment]
That's not a bad idea, but then you need to make sure that executing the lint command is part of the documentation for starting up the service.  Also, I'm running on premises with the container, so executing the lint command is not something I have control over.  Unless the container is modified to execute the lint command and fail before starting the service, I feel that this won't solve the problem.  If for any reason the config file changes and the service is restarted, you may still get a ton of errors hiding the real problem.

**Comment by joshblakeley** [comment]
It shouldnt be hard to initiate the linter via an env var passed to the container if need be - so thats an option.
