### ISSUE TITLE
Adding more than one Python file to manifest causes middleware initialisation error

### ISSUE THREAD

**Issue by benjaminsims** [TykTechnologies/tyk#1894]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Adding more than one Python file to the manifest.json will cause the error:

“Middleware initialization error: [Errno 2] No such file or directory: ‘/middleware.py’”.

**What is the expected behavior?**

Middleware should initialise normally.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Adding more than one Python file to the manifest.json is sufficient to trigger.

The bug is due to:

https://github.com/TykTechnologies/tyk/blob/dfd77e8e1c5bb271527a7654409027c94bea0eb1/coprocess/python/tyk/middleware.py#L31

This should be:

self.mw_path = os.path.join(self.module_path, "middleware.py")

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Tried on 2.7.0 and 2.7.1, affected both.

**Comment by joshblakeley** [comment]
Good spot! Thanks for raising the issue.
