### ISSUE TITLE
Possibility to configure Mutual TLS authentication without allowing to authenticate with API keys ("Auth Key")

### ISSUE THREAD

**Issue by eduard-fa** [TykTechnologies/tyk#1895]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Mutual TLS authentication configured according the [official documentation](https://tyk.io/docs/security/tls-and-ssl/mutual-tls/#a-name-authentication-a-authentication) leaves a possibility to user having a SSL certificate to supply an "Authorization" header with another user key and be identified as that another user

API definition:
```javascript
{
  "api_definition": {
    "base_identity_provided_by": "auth_token",
    ...
    "auth": {
      "auth_header_name": "Authorization",
      "use_param": false,
      "param_name": "",
      "use_cookie": false,
      "use_certificate": true,
      "cookie_name": ""
    },
    ...
    "client_certificates": [
      ...
    ],
    ...
    "use_mutual_tls_auth": true,
    ...
  },
  ...
}
```

**What is the expected behavior?**
The most valuable feature of Mutual TLS authentication is that secret key is not pre-shared with anyone and is known to nobody except the user. With current implementation, in addition to Mutual TLS auth, we allow to use an authentication with pre-shared key (Auth Token) which nullifies that valuable benefit of Mutual TLS.

It would be nice if there would be a possibility to explicitly configure to not to use HTTP header to read a key from and use certificate as key instead.

E.g. some additional `use_header: true/false` parameter, on the same manner as `use_param: true/false`.

Another option is to change an auth token middleware behaviour (https://github.com/TykTechnologies/tyk/blob/v2.7.1/mw_auth_key.go) so that the certificate would have a higher weight and would be checked before HTTP header

P.S.
Right now it is possible to supply an empty string as `auth_header_name` value, but Tyk Dashboard in such case automatically puts an "Authorization" string here, so, the editing of such definition via UI is not safe.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.6.3 and higher

P.S. I will gladly make a PR regarding this feature request, but I hope for a discussion to reveal a most suitable solution.

Thank you!

**Comment by buger** [comment]
As you mentioned it goes through auth options (headers, params, certs), one by one, and if multiple options specified it finds first that matched. A valid workaround here, will be specifying some invalid value to the header name, which never will be matched. 

If we talking about more UX friendly solution, it probably make more sense add new attribute to api definition (smth like "disable_auth_header": negative logic needed for backward compatibility), which will toggle header option. 

Does it makes sense?
