### ISSUE TITLE
Reverse proxy error handler does not respect enable_key_logging option

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1897]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the expected behavior?**
We recently fixed all places except for this one. It should print non obfuscated keys if `enable_key_logging` is turned on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Visible on upstream HTTP error

**Comment by ilijabojanovic** [comment]
Verified @buger please merge in to release-2.7 branch
