### ISSUE TITLE
How can I config /tyk-gateway/apps/ to point our url xx.xxx.xx.xx:8080

### ISSUE THREAD

**Issue by Sanpetch** [TykTechnologies/tyk#1902]
In  /tyk-gateway/apps/sample.json
  "name": "sample",
  "api_id": "1",
  "org_id": "default",
  "use_keyless": true,
  "auth": {
    "auth_header_name": ""
  },
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default",
        "expires": "3000-01-02 15:04",
        "use_extended_paths": true,
        "extended_paths": {
          "ignored": [],
          "white_list": [],
          "black_list": []
        }
      }
    }
  },
  "proxy": {
    "listen_path": "/abc/",
    "target_url": "xx.xxx.xx.xx",
    "listen_port":"8080",
    "strip_listen_path": true
  },
  "enable_batch_request_support": true
}

**Comment by asoorm** [comment]
You need to change the target URL `"target_url": "xx.xxx.xx.xx",` to something like `http://httpbin.org`.

The gateway will listen on the `listen_path` which you have as `abc` in your example e.g. as per your example: `http://gateway_url/abc/get` which would proxy to `http://httpbin.org/get`.

**Comment by Sanpetch** [comment]
And How about config port that I use ":8080"

**Comment by Sanpetch** [comment]
@asoorm

**Comment by Sanpetch** [comment]
In terminal :
 level=error msg="http: proxy error: unsupported protocol scheme \"\"" api_id=1 org_id=default server_name= user_id= user_ip=172.17.0.1 user_name=

**Comment by Sanpetch** [comment]
@asoorm And how about config port that I use ":8080"

**Comment by Sanpetch** [comment]
@asoorm And how about config port that I use ":8080"

**Comment by asoorm** [comment]
Change the target URL to include the port? `"target_url": "http://httpbin.org:8080"`?

**Comment by asoorm** [comment]
Can you curl your service directly?

https://youtu.be/YFU2HLeT0HY?t=6m

Short 15m video which should help you

**Comment by Sanpetch** [comment]
@asoorm 
I used curl but the result are the same

**Comment by Sanpetch** [comment]
@asoorm 
If I include the port to "target_url": "http://xx.xxx.xx.xx:8080" the return response in terminal 
ERROR main: couldn’t parse target URL: parse xx.xxx.xx.xx:8080: first path segment in URL cannot contain colon

**Comment by matiasinsaurralde** [comment]
Can you attach your API definition as a file?

**Comment by matiasinsaurralde** [comment]
@Sanpetch Thanks, just checked it. You should append `http://` or `https://` before the IP address.

**Comment by Sanpetch** [comment]
@matiasinsaurralde Thank you
