### ISSUE TITLE
tyk_quickstart repository does not exist

### ISSUE THREAD

**Issue by dtenenba** [TykTechnologies/tyk#1907]
**Do you want to request a *feature* or report a *bug*?**

Report a documentation bug.

**What is the current behavior?**

Cloning https://github.com/TykTechnologies/tyk_quickstart.git fails as the repo does not exist (or is not publicly accessible)

**What is the expected behavior?**

Cloning https://github.com/TykTechnologies/tyk_quickstart.git should work as this is what the documentation (https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/#step-2-get-the-quick-start-compose-files) says to do.

Note that I am stuck and cannot proceed with on-premises installation of Tyk, because this repository does not exist.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
git clone https://github.com/TykTechnologies/tyk_quickstart.git
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

N/A

**Comment by joshblakeley** [comment]
Hi The quickstart has been deprecated and the page you found is just an old cached page and is not in our docs anymore.

Please use the docker demo instead here: https://github.com/TykTechnologies/tyk-pro-docker-demo

**Comment by joshblakeley** [comment]
Thanks, we obviously missed that!

**Comment by dtenenba** [comment]
Thanks, can you point me towards the URL for the correct docs? I am finding a number of things in the older version that seem wrong, so would like to see the current version. Thanks.

**Comment by joshblakeley** [comment]
Depending on what you want to get spun up either use the readme on the docker pro demo for an all on one machine quick setup. Or we have our normal docker installation docs which is assuming a more prod-like setup https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/
