### ISSUE TITLE
Tyk gives a "TLS handshake error: no cipher suite supported by both client and server" error

### ISSUE THREAD

**Issue by EmielSchmeink** [TykTechnologies/tyk#1908]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The server gives a "TLS handshake error: no cipher suite supported by both client and server" error after updating to 2.7.1.

**What is the expected behavior?**
It should not give this error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The config was not altered after updating, nor where cipher suites specified before the update. I also tried adding some ciphers to the config, but this did not work.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.1, yes, did not come across this error in previous versions.

**Comment by buger** [comment]
Also to clarify, do you see this error between Client -> Tyk communication, or for Tyk->Upstream communication?

Additionally, can you do the following ciphers check against Tyk and Upstream https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers

Thank you.

**Comment by buger** [comment]
One more thing, can you clarify in which point of time this error happens? On startup or on request?

**Comment by EmielSchmeink** [comment]
Hi, sorry for the late reply. This happens on request, but when restarting the dashboard it automatically requests things from the gateway, so it gives an error. 
[tyk.txt](https://github.com/TykTechnologies/tyk/files/2387921/tyk.txt)
