### ISSUE TITLE
Make X-Generator header optional

### ISSUE THREAD

**Issue by richard-hulm** [TykTechnologies/tyk#193]
Hi All,

As seen in this line: https://github.com/TykTechnologies/tyk/blob/master/handler_error.go#L122

Any error response from Tyk will always have the header "tyk.io"

This is useful in development, so we can work out where the header is from, but not necessarily something we want to expose in production.

Would it be possible to have a configuration item which could turn this header off?

Cheers,

**Comment by richard-hulm** [comment]
Merged in #197

**Comment by l3ender** [comment]
I stumbled across this issue and related PR, but the documentation doesn't make any note of the tyk.conf setting for `hide_generator_header` or the `X-Generator` header in general. It would be nice to have it included in the doc for better visibility, at the very least in the https://tyk.io/docs/configure/tyk-gateway-configuration-options/ doc. @sedkis - probably applicable to hardening a system as well (preventing gateway information leakage).

**Comment by marksou** [comment]
@l3ender, I've added a docs pr - https://github.com/TykTechnologies/tyk-docs/pull/948 to address this.
