### ISSUE TITLE
Basic Auth does not work with new hashing algo

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1930]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When i create an API protected with basic auth, and use the new hashing mechanism, the username and password do not work when trying to access the API (using FF, haven't tested other browsers)

**What is the expected behavior?**
BA should work

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Create a new API and set it use Basic Auth
- Create a basic auth user/ password
- Access the API and try to authenticate

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.1

**Comment by dencoded** [comment]
closed in a favor of https://github.com/TykTechnologies/tyk-analytics/issues/976
