### ISSUE TITLE
When adding a new certificate to the gw or dashboard - allow adding alias to it

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1934]
**Do you want to request a *feature* or report a *bug*?**
Feature
This will make it easier for users to search certificates when they have a store with tens/hundreds of certs.

**What is the current behavior?**
You see the certificate IDs (hex encoded certificate SHA256 fingerprint), which is predictable but not easy to work with.

**What is the expected behavior?**
Add an option to give an alias to every certificate.
Allow searching by the alias as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.2 +

**Comment by Pinpin31** [comment]
Good idea :+1:

**Comment by Pinpin31** [comment]
I made an issue with the same problem to search keys #1285
