### ISSUE TITLE
Create API tutorial using rest API not seems to works with v1.9

### ISSUE THREAD

**Issue by testuser7777** [TykTechnologies/tyk#194]
I set up tyk gateway using the docker setup section of the web site.
Everything working fine when I do the first part of the "Set up your first API" tutorial.

The problem come when i'm trying to add an api using the rest api, i get the expected "success" message but the test api isn't loaded even after I call /tyk/reload/. 

The tyk.conf is the one coming out of the box:

{
    "listen_port": 8080,
    "secret": "352d20ee67be67f6340b4c0605b044b7",
    "template_path": "/opt/tyk-gateway/templates",
    "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
    "middleware_path": "/opt/tyk-gateway/middleware",
    "use_db_app_configs": true,
    "app_path": "/opt/tyk-gateway/apps/",
    "storage": {
        "type": "redis",
        "host": "redis",
        "port": 6379,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100
    },
    "enable_analytics": true,
    "analytics_config": {
        "type": "mongo",
        "csv_dir": "/tmp",
        "mongo_url": "mongodb://mongo:27017/tyk_analytics",
        "mongo_db_name": "tyk_analytics",
        "mongo_collection": "tyk_analytics",
        "purge_delay": 10,
        "ignored_ips": []
    },
    "health_check": {
        "enable_health_checks": true,
        "health_check_value_timeouts": 60
    },
    "optimisations_use_async_session_write": true,
    "allow_master_keys": false,
    "policies": {
        "policy_source": "mongo",
        "policy_record_name": "tyk_policies"
    },
    "hash_keys": true,
    "close_connections": true
}

This the curl script i used to add an api:

curl -H "x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7"\
 -s\
 -H "Content-Type: application/json"\
 -X POST\
 -d '{
    "name": "Test API",
    "slug": "test-api",
    "api_id": "1",
    "org_id": "56ba16b11f58a80001000001",
    "auth": {
        "auth_header_name": "Authorization"
    },
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "use_extended_paths": true
            }
        }
    },
    "proxy": {
        "listen_path": "/test-api/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true
    },
    "active": true,
    "domain": ""
 }'\
 http://www.tyk-portal-test.com:8080/tyk/apis/ | python -mjson.tool

The response i get:

{
    "action": "added",
    "key": "1",
    "status": "ok"
}

Reload script:
curl -H "x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7"\
 -s\
 -H "Content-Type: application/json"\
 http://www.tyk-portal-test.com:8080/tyk/reload/ | python -mjson.tool

Response i get:
{
    "error": "",
    "status": "ok"
}

I can't see the newly created API on the dashboard, the mongodb is empty but there is a 1.json in the apps/ folder in the file system of the gateway instance.

In the docker logs:

time="2016-02-09T16:51:23Z" level=info msg="Reload URL Structure - Scheduled"
time="2016-02-09T16:51:33Z" level=info msg="Detected 3 APIs"
time="2016-02-09T16:51:33Z" level=info msg="--> Loading API: Portal Assets"
time="2016-02-09T16:51:33Z" level=info msg="----> Tracking: www.tyk-portal-test.com"
time="2016-02-09T16:51:33Z" level=info msg="----> Checking security policy: Open"
time="2016-02-09T16:51:33Z" level=info msg="--> Loading API: Portal API"
time="2016-02-09T16:51:33Z" level=info msg="----> Tracking: www.tyk-portal-test.com"
time="2016-02-09T16:51:33Z" level=info msg="----> Checking security policy: Open"
time="2016-02-09T16:51:33Z" level=info msg="--> Loading API: Portal"
time="2016-02-09T16:51:33Z" level=info msg="----> Tracking: www.tyk-portal-test.com"
time="2016-02-09T16:51:33Z" level=info msg="----> Checking security policy: Open"
time="2016-02-09T16:51:33Z" level=info msg="Loading uptime tests..."
time="2016-02-09T16:51:33Z" level=info msg="Loaded 0 policies "
time="2016-02-09T16:51:33Z" level=info msg="API reload complete"

I was actually expecting this:

INFO[0912] Reload URL Structure - Scheduled
INFO[0922] Loading API Specification from test_apps/1.json
INFO[0922] Loading API Specification from test_apps/test_api.json
INFO[0922] Detected 1 APIs
INFO[0922] --> Loading API: Test API
INFO[0922] ----> Tracking: (no host)
INFO[0922] ----> Checking security policy: Token
INFO[0922] Loading uptime tests...
INFO[0922] API reload complete

Any idea ?

Thx

**Comment by lonelycode** [comment]
You are using a docker quickstart setup, which loads up the portal and dashboard, which means you have a dashboard based setup, so you need to use the advanced API to do what you are doing.

If you want to use gateway only you'll need to split out the docker container from the others in the quickstart, or install manually not using docker.

The tutorial here is for installations that aren't using dashboard (the CLI version), the docker quickstart assumes dashboard is being used.

**Comment by mheiber** [comment]
This was really painful. I'm having so much trouble getting started, because I used the Docker setup and nothing seems to work like in the documentation. It doesn't help that when I search the docs for stuff, it takes me to the "old" docs, then redirects me back to the start page of the new docs. Also, what's the "Advanced API"?

**Comment by mheiber** [comment]
what is the "advanced API"?

**Comment by lonelycode** [comment]
The advanced API is what is now called the dashboard API

**Comment by kohrVid** [comment]
Hi,

Did the suggestion that Martin made last year help at all? If so, would it be all right if we closed this issue on Github?

Kind regards,
Jess

**Comment by mheiber** [comment]
@kohrVid yes, @lonelycode 's suggestion was helpful, it's OK to close the issue.
Thank you!
