### ISSUE TITLE
Tyk not forwarding X-Request-Id HTTP header

### ISSUE THREAD

**Issue by AVerySimpleUser** [TykTechnologies/tyk#1945]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
X-Request-Id HTTP header name is not forwarded to the upstream API

**What is the expected behavior?**
The X-Request-Id HTTP header name should be forwarded to the upstream API

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Make a request to an API
2. Include the following HTTP headers:
a) X-Request-Id: 1234
b) X-Request-Id1: 5678
3. The HTTP header in 2.b) is received by the upstream API but not 2.a)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.3

**Comment by furkansenharputlu** [comment]
@AVerySimpleUser `X-Request-Id` is a special header.
See: https://stackoverflow.com/a/27174552/5183576

It is not about Tyk. I mean without Tyk, you will get the same result. You can try with:
a) X-Request-Id1
b) X-Request-Id2

and you will see it works.
