### ISSUE TITLE
How do you pronounce tyk?

### ISSUE THREAD

**Issue by dwijnand** [TykTechnologies/tyk#195]
Does it sound like "tick", "teak", or literally "tee why kay" or does it rhyme with "mike"?

**Comment by lonelycode** [comment]
It rhymes with Mike :-)

**Comment by dwijnand** [comment]
Thanks.

**Comment by shrikeh** [comment]
This is most annoying as someone swore blind to me that it was a Scandinavian pronunciation like "tuk". I even argued this pseudoscience on a call this morning

**Comment by james-tyk** [comment]
Words that rhyme with Tyk: bike, hike, like, mike, strike and psych

/taɪk/
