### ISSUE TITLE
Policies:write permission not working - User cannot create a policy

### ISSUE THREAD

**Issue by rajali** [TykTechnologies/tyk#1957]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
Non admin user with permissions as "policies":"write", cannot create a policy. Th rest call returns the response as:
"Not authorised - You do not have permission, please contact your administrator"

Also, the policies list item on the left is not visible in the dashboard UI.

**What is the expected behavior?**
The user with permission as "policies":"write", should be able to create policies through the rest call and should be able to view the policies from the Dashboard UI.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create User groups with permissions 
{"users": "write","portal":"write","certs":"write","policies":"write","hooks":"write","keys":"write","oauth":"write","apis":"write"}

2. Create a user with the above group
3. This user cannot see policy tab in the dashboard UI and also cannot call the dashboard REST API

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tried on:
tyk-gateway: v2.7.3
tyk-dashboard: v1.7.2

**Comment by ilijabojanovic** [comment]
@rajali Hi, thanks for reporting this issue. We are aware of this issue and we will fix this issue in next patch release

**Comment by rajali** [comment]
@ilijabojanovic , is this fixed in v2.7.4?

**Comment by rajali** [comment]
This is still an issue, is this in the roadmap of any upcoming releases?
