### ISSUE TITLE
Allow multiple query_endpoints for Service Discovery

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#196]
Hello,

I wonder if it's possible to set multiple endpoints for the query_endpoint on service discovery.
It's possible to use multiple Api Gateway, Services and Redis instances, but the connection Gateway <-> Service Discovery seems to be a single point of failure.

**Comment by lonelycode** [comment]
Hmmm, usually this kind of thing is resolved on the SD layer through DNS or some inherent feature for he SD system

**Comment by senj** [comment]
Ok thank you, DNS is an idea.
