### ISSUE TITLE
Potential condition where a failed API load wipes all loaded APIs out

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#1964]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
When a reload occurs, and there are 0 APIs returned, but there is a list of APIs loaded, it will remove all APIs. This is fine if it was intentional, but if it is an erroneous load then it could potentially cause all services to be downed.

The history of this issue is that we had in place a protection against a nil API list load, but the fix was then amended with the constraint to not be enabled when there are already APIs loaded, which undoes the reason for the original fix :-/

**What is the expected behavior?**
When 0 APIs are returned, do not reload. And find a different fix for #1035 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

TBC

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.5+

**Comment by bitsofinfo** [comment]
FYI i get APIs disappearing only on nodes that emit this log message: 

```"Failed decode: unexpected end of JSON input"```

**Comment by buger** [comment]
Should be solved with https://github.com/TykTechnologies/tyk/pull/1966 and will be part of 2.7.4 and 2.6.4
