### ISSUE TITLE
Extend gRPC settings

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#1971]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
When using gRPC plugins there's no way of specifying timeout or reconnection parameters, we use the gRPC package defaults.

**What is the expected behavior?**
It should be possible to adjust these parameters. We have a custom dialer that can be extended to achieve this.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
What other attributes except timeouts can be configurable?
