### ISSUE TITLE
Securing access to the micro services by making Tyk an OAuth2.0 client

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1978]
**Do you want to request a *feature* or report a *bug*?**
Feature
A client needs to have open APIs but still secure the access to the backend. An app could negotiate the access token and forward it to the backend but it makes sense that it should be centralised and resides inside the gw instead of having another app or service that does that, since it's repeated for all the api calls.

**What is the current behavior?**
The client needs to negotiate the access token (do the oauth flow) and send it via the gw to the backend or if they want Tyk to do OAuth flow, they need to write a plugin for it (post-auth or custom auth).

**What is the expected behavior?**
Make Tyk an OAuth client OOTB (without the need to write a plugin).
It can be used as auth mechanism. 

*When is it useful:*
 -  In case backend service requires access token from an Authorisation Server (AS).
 - Another way to secure the backend services (with or without mutual tls and cert pinning)
 - As stand-alone mechanism, if you want to keep your API open BUT still protect and secure your backend (maybe use it with chained auth methods)
- As stand-alone mechanism, if you want to  separate the frontend auth mechanism (maybe have client certificate) and still protect and secure your backend in another way
- This way might be preferred over mutual tls. Enterprise companies have raised concerned about clients/apps being able to bypass the gateway and about the burden of *managing certificates on each and every existing/new/upgrade microservice.*
 When securing the access to the backend with a temporary access token provided by an AS (such as Azure AD or any other AS) you offload the management of certificates from the backend service to the AS. At the moment, in case you have lots of micro-services, you need to have a service that would manage and distribute the Tyk-gateways’ certificates to all the micro-services. If Tyk will be able to get its own access token (and refresh it) it could save the clients building/running a certificate management and distribution service. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Among others, we need to think about:
1. Caching the access token
2. Revoking the access token
3. Which OAuth flow? we can start with client creds for simplicity.
4. Latency. If it’s done during the call to the backend then it could increase the latency, so maybe better to have it as a separate routine that updates the access token and during API call it's only being read from.
5. Where to add it:
  5.1 Add it as an auth method: this does not authenticate the user but the gw against the backend service so might not be the best place, but it would work nicely if we combine it with another auth method (keyless, basic or anything else) - this way we define the FE auth and the BE auth in one place.  Another issue, when it's configured on the API level is the need to repeat it (client_id and secret for instance) in all the APIs that are sharing the same AS and scopes.
 5.2 In the Advanced section of the API. Similar to 5.1. but here there's a clear separation between the FE authentication (client<-->tyk) and BE authentication (tyk<-->backend)
 5.3 As a config in tyk.io - this way all the APIs will be able to use the same access token base on the backend service or hostname.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.4

**Comment by JeffSBailey** [comment]
Is it fair to say that this is not currently supported?  I'm looking through the documentation but the functionality appears to be the same as when this issue was opened.
