### ISSUE TITLE
Add way to rename "/hello" endpoint

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#1981]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
At the moment we expose fixed “/hello” endpoint name for gateway/api health checks. 
It can cause issues from the security point of view since it exposes which Gateway is used to handle traffic. 
rename it to some secret URL.
**What is the expected behavior?**
It should be possible to rename default endpoint to something more secret.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
master

**Comment by ilijabojanovic** [comment]
Verified on 2.8 branch

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1982 was merged to `release-2.7` branch
<details><summary></summary>Created via API</details>

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1982 was merged to `release-2.8` branch
<details><summary></summary>Created via API</details>
