### ISSUE TITLE
Disabling a policy doesn't affect the key and api call still goes through

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1983]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Disabling a policy doesn't affect the key and api call still goes through.
Seems that the keys, which are attached to this policy, don't get deactivated after the policy was deactivated.

**What is the expected behavior?**
The inactive policy should be reflected in the key and the key should not be valid for the ACL of that policy unless the APIs were added separately to the key's ACL.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Create an api, a policy, a key and attach it to the policy. test the api.
- Disable the policy and test again - it works although it shouldn't.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.2

**Comment by dencoded** [comment]
@letzya unfortunately, I wasn't able to replicate this issue.

on both `master` and `v2.7.2`, after repeating your scenario I receive reply:

```
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Date: Mon, 19 Nov 2018 21:15:01 GMT
< Content-Length: 48
< 
{
    "error": "Key is inactive, please renew"
}
```

log entry in tyk looks like: `msg="Attempted access from inactive key."`

I see two options:
1. maybe, there were some other steps in your scenario, so I'd appreciate if you provide more details
2. make sure in your environment tyk gets correctly reloaded after policy update

**Comment by ilijabojanovic** [comment]
@dencoded After @letzya reported this issue i was able to reproduce issue for several minutes. 
This is what i saw in console:
```
[Nov 14 15:50:26] ERROR policy not found: “5bd82d719b7d7c0a17eece3d”
[Nov 14 15:50:26]  INFO Attempted access from expired key. key=5bd82c299b7d7c0873b203f1f6586e20d06b4e94a3c4e1e9218c6d2b origin=127.0.0.1 path=/api/ip
``` 
But i was able to reproduce only once, i we tried on 2.7, 2.8, 2.6 but without luck. I am still trying to reproduce this if i found steps i will provide here.
