### ISSUE TITLE
user.json file not found in Docker container when bootstrap.sh is run

### ISSUE THREAD

**Issue by flacito** [TykTechnologies/tyk#1984]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
running tyk in docker containers (dashboard, pump, gateway) and get all the way to the part where you run bootstrap.sh, but the boostrap fails

**What is the expected behavior?**
initial users should be created

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

## This is the bootstrap command that fails:
```
./boostrap-dashboard.sh localhost
Creating Organisation
{"Status":"OK","Message":"Org created","Meta":"5bf44837a7eab40001bf4638"}
ORGID: 5bf44837a7eab40001bf4638
Adding new user
{"Status":"Error","Message":"User object validation failed, most likely malformed input","Meta":null} {"Status":"Error","Message":"Request body is not valid","Meta":null}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 103 - line 2 column 1 (char 102 - 171)
USER AUTH:
{"Status":"Error","Message":"Authorization field empty","Meta":null}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'users'
NEW ID:
Setting password

DONE
====
Login at http://localhost:8000/
User: 3hzwxddkgj@default.com
Pass: test123
```

## This is in the dashboard container log:
```
tyk_dashboard.1.stz6sqiql76v@linuxkit-025000000001    | time="Nov 20 18:25:58" level=error msg="Validation Error:open /./schemas/user.json: no such file or directory"
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Only tried v1.7.3

**Comment by asoorm** [comment]
Could you confirm what your `home_dir` value is set to in your dashboard configs?

It should be something like: `"home_dir": "/opt/tyk-dashboard",` or if you are configuring via environment variables: `TYK_DB_HOMEDIR=/opt/tyk-dashboard`.

If this is not present, I think it defaults to root `/` to look for the schemas.

**Comment by flacito** [comment]
Not configuring via ENV.   I looked in tyk_analytics.conf and there is not such value.  I suppose I need it.  I copied the conf from the helps.   Should I add?

**Comment by flacito** [comment]
```
    environment:
      TYK_DB_HOMEDIR: /opt/tyk-dashboard
```
    environment:
      TYK_DB_HOMEDIR: /opt/tyk-dashboard
```

In my docker-compose file worked.  I'm up!    Is there a setting in the config JSON I can use?  (I ask not RTFM).

**Comment by asoorm** [comment]
https://tyk.io/docs/configure/tyk-dashboard-configuration-options/

> `home_dir`: The path to the home directory of Tyk Dashboard, this must be set in order for Portal templates and other files to be loadable. By default this is /opt/tyk-dashboard/.
