### ISSUE TITLE
During rewrites with dynamic values, if key not found, whole searched string get replaced with empty value

### ISSUE THREAD

**Issue by dskoval** [TykTechnologies/tyk#1989]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If I inject some variable (`$tyk_meta.key` or `$tyk_context.key`) and corresponding value not found in metadata (context) whole `rewrite_to` value replaced with empty string. As result, downstream call would be made to target_url specified in proxy section.
**What is the expected behavior?**
Replace only corresponding variable with empty string

Related to #1860 

Lines causing such behavior:
https://github.com/TykTechnologies/tyk/blob/d31e82a37f31c287859898c131ac0d2200632f03/mw_url_rewrite.go#L192-L194
https://github.com/TykTechnologies/tyk/blob/d31e82a37f31c287859898c131ac0d2200632f03/mw_url_rewrite.go#L217-L219
should be replaced with `in = strings.Replace(in, v[0], "", -1)`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
master

**Comment by dskoval** [comment]
One more note:
rewriter also replaces `$tyk_meta.### ` with corresponding values from session metadata. If session not present it will return url with `$tyk_meta.### ` variables in it. I think in such case all `$tyk_meta.### ` should be replaced with empty strings too.

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1993 was merged to `release-2.7` branch
<details><summary></summary>Created via API</details>

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/1993 was merged to `release-2.8` branch
<details><summary></summary>Created via API</details>
