### ISSUE TITLE
Basic auth password collision when caching turned on

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2003]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
At the moment basic auth middleware use murmur32 for caching the successful password attempts. This makes it vulnerable to the known bug, with 3-character range, which introduces hash collisions. Additionally, murmur32 length, make it too insecure for such usage.
**What is the expected behavior?**
The algorithm should be replaced by bug-free more secure versions like `murmur64`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All from 2.7

**Comment by ilijabojanovic** [comment]
Verified
