### ISSUE TITLE
Allow JWT auth method to verify the signature but not enforce the policy

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2009]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
In order to use this method, you must have permission to change the JWT and **inject** the policy id to it.
The problem is that JWTs are created and **signed** with a private key by the IdP, so injecting more info could be a problem to the API owner.

**What is the expected behavior?**
To be able to add a public key or shared key to the api def without choosing a specific policy.

Please note that this feature is not relevant to individual keys since in this case, you would need to update the JWT anyway.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7

**Comment by buger** [comment]
I think that a more generalized approach here will be adding "default policy" field to JWT configuration,  which will be used if JWT policy scope not set.

**Comment by letzya** [comment]
@buger Default policy can be a fallback with a conf fields `use_policy_fallback` to activate this fallback.

**Comment by letzya** [comment]
@buger While thinking where we should define this `default policy` it reminds me discussions we had about defining the triplet (ACL, rate limit, quota ) on the level of the api definition. If we do this for jwt maybe we can do this for other methods?

**Comment by letzya** [comment]
This is planned to be released on 2.8.2, ETA is around June 20th.
