### ISSUE TITLE
try/catch style logic for mongodb connection

### ISSUE THREAD

**Issue by unki2aut** [TykTechnologies/tyk#201]
Today i got the following error several times, which must not happen in production:
> Failure in user lookup: <user email>
> read tcp 172.17.0.6:47999-><compose.io-server-ip>:10117: read: connection reset by peer

Answer from the compose.io-support:
> You'll want to implement try/catch style logic that checks the veracity of a TCP connection fist, and then recovers and retries if there's a network error during the communication.

So this should be implemented to be production ready!

**Comment by lonelycode** [comment]
Thanks for the tip! Do we really need to make exclamations in a bug report?! It makes it so much better!

On a serious note, we already have try/catch style handlers for various mongo errors across all Tyk elements, for example, this is from Dashboard:

```go
func HandleStoreError(e error) {
	if strings.Contains(e.Error(), "EOF") {
		log.Info("Attempting to reconnect")
		Store.Connect()
		Store.db = Store.session.DB("")
		return
	}
	if strings.Contains(e.Error(), "Closed explicitly") {
		log.Info("Attempting to reconnect")
		Store.Connect()
		Store.db = Store.session.DB("")
		return
	}
}
```

And the gateway re-connects on purge, so it should be immune.

We've never come across a `reset by peer` error (and we use compose.io), so we'll add that in, cheers.

**Comment by lonelycode** [comment]
Fixed in develop, will be in next version.

**Comment by unki2aut** [comment]
Thx for the fast reply, but this is really important for us if we want to use tyk for our production system. :smile:

**Comment by lonelycode** [comment]
Tyk dashboard is proprietary, so you'll need to wait for the next version I'm afraid.
