### ISSUE TITLE
Oauth2 token generation url

### ISSUE THREAD

**Issue by amadeus-x1** [TykTechnologies/tyk#2012]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
tyk listens on **API_IDoauth/token**

**What is the expected behavior?**
tyk should listen on **API_ID/oauth/token**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create an api with listen_path without a trailing **/**, e.g., an api listening on /orders
For this api, tyk will end up listening on **ordersoauth/token** for token requests
[code](https://github.com/TykTechnologies/tyk/blob/master/main.go#L431)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Not sure. I am currently using 2.8, built from source.

**Comment by andyo-tyk** [comment]
This should no longer be an issue, however if you still see this issue with latest Tyk Gateway (4.x) please re-open the ticket and we will investigate again.

Thanks for your support.
