### ISSUE TITLE
Black/Whitelisting ?

### ISSUE THREAD

**Issue by senj** [TykTechnologies/tyk#202]
Hello,

I imported three endpoints from Swagger.
They were all marked as whitelisted.

For my understanding, if I whitelist all endpoints it should be good.
If only one one the endpoints is whitelisted, this will be the only available one.

If I blacklist an endpoint, this one is not reachable.
If I ignore an endpoint, access restrictions will be skipped.

When I try to reach my API this is the error:
```
403
{
  "error": "Requested endpoint is forbidden"
}
```

After deleting all endpoints it just works.
If I remove Whitelist from the endpoint, the whole endpoint gets deleted.

I read in the docs some of those options are deprecated?
Can someone explain a bit about whitelisting and why I get 403?

Thanks..

**Comment by lonelycode** [comment]
When you white list it becomes exclusive, the entire path structure becomes subject to white listing and all other path considerations are discarded. So you can't really mix.

I think you can still ignore paths, but that's it. Blacklists no longer apply.

They aren't deprecated, they have moved to the extended_paths section as this is more verbose and allows more features. The old paths sextion is deprecated.

**Comment by senj** [comment]
Mh ok but I don't mix it. This is my setup (auto-generated by importing swagger.json).:
![endpoints](https://cloud.githubusercontent.com/assets/5556013/13314136/ba0a859a-dba3-11e5-998e-ffd15ddaf2ea.PNG)

**Comment by lonelycode** [comment]
It could juet be bad matching, if your `listen_path` ends in a slash, then your URLs here should not start with one and vice versa.
