### ISSUE TITLE
Cannot access multi-cloud documentation 403 forbidden

### ISSUE THREAD

**Issue by MCyprien** [TykTechnologies/tyk#2020]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When going to the documentation at https://tyk.io/docs/ and clicking on getting started multi-cloud at https://tyk.io/docs/get-started/with-tyk-hybrid/, I get a 403 forbidden error.

**What is the expected behavior?**
I should be able to access documentation.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Go to the documentation page and click on getting started multi-cloud or got to https://tyk.io/docs/get-started/with-tyk-hybrid/

**Comment by marksou** [comment]
@MCyprien This link has now been updated to https://tyk.io/docs/get-started/with-tyk-multi-cloud/

**Comment by MCyprien** [comment]
@marksou thank for your fast answer, shouldn't the documentation root page be updated with that ?

**Comment by marksou** [comment]
@MCyprien Yes, I've updated the link on the docs root page.

**Comment by MCyprien** [comment]
Cool :) I will close this issue then thank you :)
