### ISSUE TITLE
Any process or Http endpoint to detect tyk-gateway process is ready to receive traffice?

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#2022]
Hi,

I am trying to deploy the tyk gateway on my kubernetes cluster. By default it's single noded, when I try to scale the tyk-gateway instance, it may take some time to get all the configuration(from redis connection or dashboard API definition) well but the pod itself is already in running state.

So is there any way to detect the tyk-gateway process is ready or how to know it's ready to receive traffic?  It can be a process or an Http endpoint if possible.

**Comment by matiasinsaurralde** [comment]
Hi, there's a related community forum post [here](https://community.tyk.io/t/gateway-health-check-endpoint/1727/15).

**Comment by hustshawn** [comment]
@matiasinsaurralde Got it. Thank you.
