### ISSUE TITLE
How to transform the API response body (for example, adding a field/removing a field from JSON)?

### ISSUE THREAD

**Issue by prasadus92** [TykTechnologies/tyk#203]
I gone through the documentation of Tyk. But not able to find a good explanation on how to transform the response body of an API. Can someone please help me with a link or a sample example?

Thanks in advance.

**Comment by JosephEarl** [comment]
You can do this with custom Tyk Middleware - https://tyk.io/v1.9/plugins/middleware-scripting/

**Comment by prasadus92** [comment]
Thank you.
