### ISSUE TITLE
security: issue gateway warning on boot if control port default

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2034]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

When the gateway starts up, the default control port `8080` is the same port which processes proxy traffic, meaning that it is public.

**What is the expected behavior?**

This is absolutely fine if properly secured, however a warning on boot suggesting to change the port for production usage along with a link to docs on how to achieve would be useful.

Checks could be placed in https://github.com/TykTechnologies/tyk/blob/master/checkup/checkup.go

**Comment by letzya** [comment]
plus add link to an FAQ page in the docs

**Comment by ilijabojanovic** [comment]
@buger merge in to release-2.8
