### ISSUE TITLE
Add way to get basic auth key by username when custom hashing algorithm used

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2038]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
With old key generation, algorithm user can just construct key by concatenating orgid and username, and what most importantly dashboard was able to make such an assumption when querying by username. With new hashing algorithms, dashboard can't query by username anymore. 
**What is the expected behavior?**
We need to modify Key API to allow querying by username, which will ensure that the right hashing algorithm is used. 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7

**Comment by ilijabojanovic** [comment]
See comment in https://github.com/TykTechnologies/tyk-analytics/issues/976
