### ISSUE TITLE
tyk features

### ISSUE THREAD

**Issue by umocolombo** [TykTechnologies/tyk#2043]
Hi guys!
I want realize sub requests to different microservices in one request to tyk

That i mean
1) I send into tyk one REST API request
2) tyk create one sub-request to first service and receive ansver
3) tyk  take information from first ansver and create second sub-request to second service.
4) Ansver from second service tyk transmit ME back.

Is it posible?

What this functions name?

**Comment by buger** [comment]
It is totally doable with Virtual Endpoint https://tyk.io/docs/compose-apis/virtual-endpoints/. In other words some small piece of JS code, where you can make HTTP requests and apply logic you want.
