### ISSUE TITLE
Mutual TLS does not fallback to HTTP check if API has custom domain

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2046]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Currently, Tyk fallbacks back to HTTP check in following cases:
- If one of API uses auth Key with certificate support
- If API domain is empty and mutual TLS auth is enabled (to support multiple APIs on the same domain but a different path)
**What is the expected behavior?**
If API has custom domain set and the client does not support SNI, HTTP fallback does not work

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All from 2.5

**Comment by mcandre** [comment]
Newbie here. Would it be insecure for a TLS connection to fall back to HTTP?

**Comment by buger** [comment]
In general, check on TLS level always more secure. But "true" mutual TLS in this case will require that each API have to be deployed to a separate domain. That's why we added HTTP fallback, which validates TLS certificate on HTTP level, but allows you to have multiple APIs with different client certificates on the same domain, just different listen paths.
