### ISSUE TITLE
auth: strip authorization data should also strip auth from cookie

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2047]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When you send auth via cookie value, there is no way to strip that cookie value from upstream request.

![screenshot 2019-01-07 at 16 33 00](https://user-images.githubusercontent.com/1465130/50780167-2108d000-129a-11e9-9a3a-9f3ef4e94f69.png)

apidef:

```
---snip---
"auth": {
      "auth_header_name": "Authorization",
      "use_certificate": false,
      "use_param": false,
      "param_name": "",
      "use_cookie": true,
      "cookie_name": ""
    }
---snip---
```

example curl
```
$ curl http://localhost:8080/httpbin/get --cookie 'Authorization=5bcef48a3f03d311ff27d1565cc4a06cd9044dca916c49f639778e61'
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Connection": "close",
    "Cookie": "Authorization=5bcef48a3f03d311ff27d1565cc4a06cd9044dca916c49f639778e61",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.61.0"
  },
  "origin": "127.0.0.1, 82.71.60.185",
  "url": "http://httpbin.org/get"
}
```

**What is the expected behavior?**

If stripping authorization data, then this should also be removed from cookie.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Master

**Comment by ilijabojanovic** [comment]
@furkansenharputlu pls merge this in to release-2.8 branch
