### ISSUE TITLE
WS-Federation authentication support

### ISSUE THREAD

**Issue by ivaningrooves** [TykTechnologies/tyk#206]
Hi, just wondering if there is currently (or going to be) support for WS-Federation authentication? I could not find any documentation or code here but a limited implementation exists: https://github.com/ma314smith/go-wsfed

**Comment by lonelycode** [comment]
Would happily consider it, it's not on the roadmap st the moment.

I think our understanding is a bit limited for WS federation though, do you have a clear use case / standard flow we could work with? It's definitely worth considering.

**Comment by ivaningrooves** [comment]
It took me a while to find out what flow we use. We use TinkTecture Identiy server v2 as ID and auth provider. I believe we use the flow below:

(2,3,4 are handled by Id. server)

1. Browser performs request to Api
2. No (or invalid) Cookie present and no "Bearer" in the Authorization header -> redirect to auth provider login page.
3. Enter credentials and submit.
4. If successful login -> load a page that automatically POSTs a hidden form back to the Api containing encrypted claims (permissions).
5. Api decrypts claims and sets up a secure Cookie session.

Tyk could deal with this much like the OAuth middleware? How about this?

1. Browser performs request to Tyk (e.g. `mytyk.io/myapi`)
2. The WSFed middleware checks for the Authorization and/or Cookie header -> redirect to auth provider login page if necessary.
3. The middleware checks for a receiving POST as result from a successful login -> decrypt and set Authorizaion and/or set or inject Cookie headers, redirect to `mytyk.io/myapi`

The Authorization and/or Cookie headers contain the Token *and* claims. The Id. server will have to perform a POST to `/tyk/keys/{{access_token}}` to create the token when login is successful. Then the middleware could decrypt and update the permissions for the key.

Does this make sense to you? Is a middleware the proper way to implement this?

**Comment by lonelycode** [comment]
You could do this with Golang middleware, but I don't feel this is a generic enough flow to warrant something to be added to Tyk itself unless it handled the federation flow for a bunch of other providers.

However, there is a project we recently released called the Tyk Identity Broker, which is easy to extend with plugable identity providers and is designed for stuff like this. It would be easier to modify than Tyk itself and there's less risk in forming and managing your customisations.

It would be easier to extend the TIB with the flow that you describe as it will take care of bridging the gap between Tyk and your IDM by generating tokens in exactly the mode you describe.

**Comment by ivaningrooves** [comment]
Thanks Martin, I will look into the TIB and see how easy I can extend it
with our flow. I was told our case is widely used in .NET land. You might
want to add a link to the TIB under the 'Custom Tokens' section in the
docs? Cheers, --Ivan

-- 
Ivan

**Comment by ivaningrooves** [comment]
I hope you don't mind me asking another question regarding the described flow. Our current API's expect the encrypted Cookie which contains the token as well as permissions (claims). I can see how the TIB proxies different ID providers and makes use of Tyk's oauth mechanism but how would I go about this Cookie? Can Tyk ignore the Cookie and maybe verify an additional Authorization header? ..and have the TIB set the Cookie initially?

**Comment by lonelycode** [comment]
You might need to write your own plugin, so your TIB plugin sets the cookie before the redirect, and then TIB generates an auth token or an oauth token for the ID, you can redirect the user with the token to your app, which can use the token to make requests and since the browser has been redirected, the claims are with the browser. Alternatively, use an alt header in Tyk for auth and put your claims in the auth header.

**Comment by ivaningrooves** [comment]
I believe my biggest problem in this is the encrypted Cookie. Yes, the TIB plugin can deal with it but the APIs we currently use depend on the Cookie (and only use the Cookie) I still would have to modify Tyk to be able to decrypt the cookie (and verify it) to determine the 'key'. What are your thoughts?

**Comment by lonelycode** [comment]
My thoughts: I think this is getting quite complicated, which is why there's no WS-Federation plugin for Tyk :-)

The cookie causes real problems, we have very little cookie support (they are not very RESTFul). You'll need to shoe-horn this into a custom version of Tyk to get this to work as a golang middleware if you want any speed.

**Comment by ivaningrooves** [comment]
Hah I agree :-) 

Would you consider merging a secure-cookie-support pull request with support for multiple types of authentication? Supporting secure cookies should be a handy feature (see: http://www.gorillatoolkit.org/pkg/securecookie) as well as being able to verify tokens in a multiple of header, query param and cookie.

Maybe instead of having the UseCookie and UseParam flags have string values for CookieName and ParamName? I could add the Cookie keys there as well? The Auth struct would become something like this:
```
Auth struct {
  AuthHeaderName       string
  CookieName           string
  CookieHashKey        []byte
  CookieBlockKey       []byte
  ParamName            string
}
```
I could keep the bools for backwards compatibility? The middleware would check the bools first, then the names and last the AuthHeaderName. In pseudo:
```
authValue := Headers.Get(config.AuthHeaderName)

paramName := config.ParamName
if config.UseParam || paramName != "" {
  authValue =  FormValue(paramName || config.AuthHeaderName)
}
cookieName = config.CookieName
if config.UseCookie || cookieName != "" {
  // decrypt if keys are set
  // etc.
}
```
What do you think? Would this impact performance too much?

**Comment by ivaningrooves** [comment]
I realize this requires changes in the dashboard as well, which is proprietary. I have made some changes already but it is kind of hard for me to test without a UI and I am reluctant to add unit tests without some assurance you would actually merge this in. Here are the changes, let me know what you think. https://github.com/ivaningrooves/tyk/commit/eb2244ddf637fba04b9f451c9d4f2234133464a7

PS. I don't mind making the changes to the UI as well but I guess you want to keep that in your house.

**Comment by lonelycode** [comment]
Would be happy to merge it in so long as all the existing tests pass and some new ones are added, our CI will take care of that :-) 

Your code would work instantly with file-based configs (no UI), also all our unit tests assume that there is no UI (Tyk operates just fine without one and is designed for the UI to be an add-on). 

This is also a feature people have been asking for (multiple auth location options) for a while, so it's definitely worth considering.

As for performance, those request copy operations are expensive, so we try to avoid them at all costs, if someone is using param and cookie they cause two request object copies to happen, which isn't ideal, but should be easy to fix (just re-use the existing copy if it has been already created).

Also, we'd need to go the bool route as we need to retain backwards compatibility where possible.

As for UI integration, we have v2.0 *very* close to roll-out, so depending on when this hits, and how robust tests are etc it *might* make it in, but no guarantees. However it would definitely make it into a future UI release.

**Comment by ivaningrooves** [comment]
Thanks Martin, I will look into file-based configs and add some tests.
