### ISSUE TITLE
When setting method transform+Body transform only method transform is applied

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2063]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When setting method transform+Body transform only method transform is applied. No body transform

**What is the expected behavior?**
Apply body transform as well

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Used petstore as my target url `https://petstore.swagger.io/v2/`
2. Added a new endpoint `/store/order` with GET
3. Create Body transform on response ` {{ .| jsonMarshal }}`
4. Created Method trans to POST
5. Sent this request:
```curl -X GET \
  http://www.tyk-gateway.com:8080/post-trans/store/order \
  -H 'Accept: application/xml' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": 111,
  "petId": 40,
  "quantity": 10,
  "shipDate": "2019-01-16T20:24:28.882Z",
  "status": "placed",
  "complete": false
}'```

Got an xml rather than json:
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Order>
    <complete>false</complete>
    <id>111</id>
    <petId>40</petId>
    <quantity>10</quantity>
    <shipDate>2019-01-16T20:24:28.882Z</shipDate>
    <status>placed</status>
</Order>```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.2

**Comment by davegarvey** [comment]
I can confirm this too.

I added a body transform to both request and response, and also a method transform to `POST`.

### API definition

    {
        "id": "5c12263b843a500001544dea",
        "name": "Demo",
        "slug": "demo",
        "api_id": "0bf080892a9b47a4796bc0add27dfbe2",
        "org_id": "580defdbe1d21e0001c67e5c",
        "use_keyless": true,
        "use_oauth2": false,
        "use_openid": false,
        "openid_options": {
            "providers": [],
            "segregate_by_client": false
        },
        "oauth_meta": {
            "allowed_access_types": [],
            "allowed_authorize_types": [],
            "auth_login_redirect": ""
        },
        "auth": {
            "use_param": false,
            "param_name": "",
            "use_cookie": false,
            "cookie_name": "",
            "auth_header_name": "Authorization",
            "use_certificate": false
        },
        "use_basic_auth": false,
        "basic_auth": {
            "disable_caching": false,
            "cache_ttl": 0
        },
        "use_mutual_tls_auth": false,
        "client_certificates": [],
        "upstream_certificates": {},
        "pinned_public_keys": {},
        "enable_jwt": false,
        "use_standard_auth": false,
        "enable_coprocess_auth": false,
        "jwt_signing_method": "",
        "jwt_source": "",
        "jwt_identity_base_field": "",
        "jwt_client_base_field": "",
        "jwt_policy_field_name": "",
        "jwt_disable_issued_at_validation": false,
        "jwt_disable_expires_at_validation": false,
        "jwt_disable_not_before_validation": false,
        "jwt_skip_kid": false,
        "notifications": {
            "shared_secret": "",
            "oauth_on_keychange_url": ""
        },
        "enable_signature_checking": false,
        "hmac_allowed_clock_skew": -1,
        "base_identity_provided_by": "",
        "definition": {
            "location": "header",
            "key": "x-api-version",
            "strip_path": false
        },
        "version_data": {
            "not_versioned": true,
            "default_version": "",
            "versions": {
                "Default": {
                    "name": "Default",
                    "expires": "",
                    "paths": {
                        "ignored": [],
                        "white_list": [],
                        "black_list": []
                    },
                    "use_extended_paths": true,
                    "extended_paths": {
                        "transform": [
                            {
                                "template_data": {
                                    "input_type": "json",
                                    "template_mode": "blob",
                                    "enable_session": false,
                                    "template_source": "ewogICAgInRyYW5zZm9ybWVkIjoie3suaGVsbG99fSIKfQ=="
                                },
                                "path": "post",
                                "method": "GET"
                            }
                        ],
                        "transform_response": [
                            {
                                "template_data": {
                                    "input_type": "json",
                                    "template_mode": "blob",
                                    "enable_session": false,
                                    "template_source": "ewogICAgInRyYW5zZm9ybWVkIjoie3suZGF0YX19Igp9"
                                },
                                "path": "post",
                                "method": "GET"
                            }
                        ],
                        "method_transforms": [
                            {
                                "path": "post",
                                "method": "GET",
                                "to_method": "POST"
                            }
                        ]
                    },
                    "global_headers": {},
                    "global_headers_remove": [],
                    "global_size_limit": 0,
                    "override_target": ""
                }
            }
        },
        "uptime_tests": {
            "check_list": [],
            "config": {
                "expire_utime_after": 0,
                "service_discovery": {
                    "use_discovery_service": false,
                    "query_endpoint": "",
                    "use_nested_query": false,
                    "parent_data_path": "",
                    "data_path": "",
                    "port_data_path": "",
                    "target_path": "",
                    "use_target_list": false,
                    "cache_timeout": 60,
                    "endpoint_returns_list": false
                },
                "recheck_wait": 0
            }
        },
        "proxy": {
            "preserve_host_header": false,
            "listen_path": "/0bf080892a9b47a4796bc0add27dfbe2/",
            "target_url": "http://httpbin.org/",
            "strip_listen_path": true,
            "enable_load_balancing": false,
            "target_list": [],
            "check_host_against_uptime_tests": false,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 0,
                "endpoint_returns_list": false
            },
            "transport": {
                "ssl_ciphers": [],
                "ssl_min_version": 0,
                "proxy_url": ""
            }
        },
        "disable_rate_limit": false,
        "disable_quota": false,
        "custom_middleware": {
            "pre": [],
            "post": [],
            "post_key_auth": [],
            "auth_check": {
                "name": "",
                "path": "",
                "require_session": false
            },
            "response": [],
            "driver": "",
            "id_extractor": {
                "extract_from": "",
                "extract_with": "",
                "extractor_config": {}
            }
        },
        "custom_middleware_bundle": "",
        "cache_options": {
            "cache_timeout": 60,
            "enable_cache": true,
            "cache_all_safe_requests": false,
            "cache_response_codes": [],
            "enable_upstream_cache_control": false,
            "cache_control_ttl_header": ""
        },
        "session_lifetime": 0,
        "active": true,
        "auth_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "session_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "event_handlers": {
            "events": {}
        },
        "enable_batch_request_support": false,
        "enable_ip_whitelisting": false,
        "allowed_ips": [],
        "enable_ip_blacklisting": false,
        "blacklisted_ips": [],
        "dont_set_quota_on_create": false,
        "expire_analytics_after": 0,
        "response_processors": [
            {
                "name": "response_body_transform",
                "options": {}
            }
        ],
        "CORS": {
            "enable": false,
            "allowed_origins": [],
            "allowed_methods": [],
            "allowed_headers": [],
            "exposed_headers": [],
            "allow_credentials": false,
            "max_age": 24,
            "options_passthrough": false,
            "debug": false
        },
        "domain": "",
        "do_not_track": false,
        "tags": [],
        "enable_context_vars": false,
        "config_data": {},
        "tag_headers": [],
        "global_rate_limit": {
            "rate": 0,
            "per": 0
        },
        "strip_auth_data": false
    }

### Curl

    curl -X GET \
    https://tyk.cloud.tyk.io/demo/post \
    -H 'Content-Type: application/json' \
    -H 'Postman-Token: 5064fd6a-a047-4ce9-8dd8-24d5e1129780' \
    -H 'cache-control: no-cache' \
    -d '{ "hello":"world" }'

### Response

    {
        "args": {},
        "data": "{\n    \"transformed\":\"world\"\n}",
        "files": {},
        "form": {},
        "headers": {
            "Accept": "*/*",
            "Accept-Encoding": "gzip, deflate",
            "Cache-Control": "no-cache",
            "Connection": "close",
            "Content-Length": "29",
            "Content-Type": "application/json",
            "Host": "httpbin.org",
            "Postman-Token": "e956e83f-6266-4b7d-a952-2a72246aaace",
            "User-Agent": "PostmanRuntime/7.4.0",
            "X-Amzn-Trace-Id": "Root=1-5c3fdb71-2dd24064d71ba8694388b317",
            "X-Scheme": "https"
        },
        "json": {
            "transformed": "world"
        },
        "origin": "115.42.172.138, 115.42.172.138, 172.30.2.211, 172.30.2.248, 52.71.254.156",
        "url": "http://httpbin.org/post"
    }

### Conclusion

I can see that the method transform worked (`GET` -> `POST`) and the data transformed (`"hello":"world"` -> `"transformed":"world"`), but the response does not transform as expected (large JSON response -> `"transformed":"{"transformed":"world"}"`).

If the method transform is removed and the API definition is updated to target the `POST` method of the `/post` path then both transforms are activated as expected.

**Comment by buger** [comment]
This is what was happening https://github.com/TykTechnologies/tyk/issues/2069
