### ISSUE TITLE
Security issue with HMAC

### ISSUE THREAD

**Issue by randaalex** [TykTechnologies/tyk#2066]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
tyk uses HMAC-SHA1 for signature requests

**What is the expected behavior?**
tyk shouldn't use HMAC-SHA1
According to golang documentation: `SHA-1 is cryptographically broken and should not be used for secure applications.` (https://golang.org/pkg/crypto/sha1/)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

**Comment by buger** [comment]
HMAC needs more attention indeed, created the following PR https://github.com/TykTechnologies/tyk/pull/2071 which adds support for `hmac-sha256`, `hmac-sha384` and `hmac-sha512` algorithm headers.

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/2071 was merged to `release-2.8` branch
<details><summary></summary>Created via API</details>

**Comment by buger** [comment]
https://github.com/TykTechnologies/tyk/pull/2071 was merged to `release-2.7` branch
<details><summary></summary>Created via API</details>
