### ISSUE TITLE
log: extend formatter to support custom error codes

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2074]
**Do you want to request a *feature* or report a *bug*?**

feature

extend the log formatter to support custom error codes & custom error messages.

`log.WithField("code", "tyk.apis.invalid_request").Error("client sent invalid request")`

With custom formatter, we can lookup the code `api.apis.invalid_request` and replace the `"client sent invalid request"` message with either a translation, or alternative text if exists.

**Comment by komalsukhani** [comment]
I am interested in developing this feature. I might some guidance.
How translation or alternative text will be provided for each request code?
Will there be some input file that needs to be parsed?

**Comment by buger** [comment]
@komalsukhani, in general, yes, there will be translations file. This feature is already in works by one of our members. Thank you for your help!
