### ISSUE TITLE
Default version not working for `Default`

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#2075]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
When using the default version feature and selecting `DEFAULT` as the default version, the version error response is received:

    {
        "error": "This API version does not seem to exist"
    }

**What is the expected behavior?**
The default version API response should be received.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Problem appears to be due to the version name starting with a capital letter i.e. If version name is `Default` the problem occurs, but if it is `default` it works ok. Works ok with numbers.

Update: In the default select dropdown, hyphens in version names appear to capitalise the following character, which then means that they don't get matched correct.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.7.3
Not aware if working in previous version.

**Comment by ilijabojanovic** [comment]
@davegarvey could you please attach video or api definition. I am not able to reproduce this issue on 1.7.4 version

**Comment by davegarvey** [comment]
Apologies, should have provided first time around:

    {
        "id": "5c47d3133465b40001a4d3f1",
        "name": "Versioned API",
        "slug": "versioned-api",
        "api_id": "787362a7531a4e5b7a33537298f79616",
        "org_id": "580defdbe1d21e0001c67e5c",
        "use_keyless": true,
        "use_oauth2": false,
        "use_openid": false,
        "openid_options": {
            "providers": [],
            "segregate_by_client": false
        },
        "oauth_meta": {
            "allowed_access_types": [],
            "allowed_authorize_types": [],
            "auth_login_redirect": ""
        },
        "auth": {
            "use_param": false,
            "param_name": "",
            "use_cookie": false,
            "cookie_name": "",
            "auth_header_name": "Authorization",
            "use_certificate": false
        },
        "use_basic_auth": false,
        "basic_auth": {
            "disable_caching": false,
            "cache_ttl": 0
        },
        "use_mutual_tls_auth": false,
        "client_certificates": [],
        "upstream_certificates": {},
        "pinned_public_keys": {},
        "enable_jwt": false,
        "use_standard_auth": false,
        "enable_coprocess_auth": false,
        "jwt_signing_method": "",
        "jwt_source": "",
        "jwt_identity_base_field": "",
        "jwt_client_base_field": "",
        "jwt_policy_field_name": "",
        "jwt_issued_at_validation_skew": 0,
        "jwt_expires_at_validation_skew": 0,
        "jwt_not_before_validation_skew": 0,
        "jwt_skip_kid": false,
        "notifications": {
            "shared_secret": "",
            "oauth_on_keychange_url": ""
        },
        "enable_signature_checking": false,
        "hmac_allowed_clock_skew": -1,
        "hmac_allowed_algorithms": [],
        "base_identity_provided_by": "",
        "definition": {
            "location": "header",
            "key": "x-api-version",
            "strip_path": false
        },
        "version_data": {
            "not_versioned": false,
            "default_version": "default",
            "versions": {
                "2": {
                    "name": "2",
                    "expires": "",
                    "paths": {
                        "ignored": [],
                        "white_list": [],
                        "black_list": []
                    },
                    "use_extended_paths": true,
                    "extended_paths": {},
                    "global_headers": {},
                    "global_headers_remove": [],
                    "global_size_limit": 0,
                    "override_target": ""
                },
                "Default": {
                    "name": "Default",
                    "expires": "",
                    "paths": {
                        "ignored": [],
                        "white_list": [],
                        "black_list": []
                    },
                    "use_extended_paths": true,
                    "extended_paths": {},
                    "global_headers": {},
                    "global_headers_remove": [],
                    "global_size_limit": 0,
                    "override_target": ""
                }
            }
        },
        "uptime_tests": {
            "check_list": [],
            "config": {
                "expire_utime_after": 0,
                "service_discovery": {
                    "use_discovery_service": false,
                    "query_endpoint": "",
                    "use_nested_query": false,
                    "parent_data_path": "",
                    "data_path": "",
                    "port_data_path": "",
                    "target_path": "",
                    "use_target_list": false,
                    "cache_timeout": 60,
                    "endpoint_returns_list": false
                },
                "recheck_wait": 0
            }
        },
        "proxy": {
            "preserve_host_header": false,
            "listen_path": "/787362a7531a4e5b7a33537298f79616/",
            "target_url": "http://httpbin.org/",
            "disable_strip_slash": false,
            "strip_listen_path": true,
            "enable_load_balancing": false,
            "target_list": [],
            "check_host_against_uptime_tests": false,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 0,
                "endpoint_returns_list": false
            },
            "transport": {
                "ssl_ciphers": [],
                "ssl_min_version": 0,
                "proxy_url": ""
            }
        },
        "disable_rate_limit": false,
        "disable_quota": false,
        "custom_middleware": {
            "pre": [],
            "post": [],
            "post_key_auth": [],
            "auth_check": {
                "name": "",
                "path": "",
                "require_session": false
            },
            "response": [],
            "driver": "",
            "id_extractor": {
                "extract_from": "",
                "extract_with": "",
                "extractor_config": {}
            }
        },
        "custom_middleware_bundle": "",
        "cache_options": {
            "cache_timeout": 60,
            "enable_cache": true,
            "cache_all_safe_requests": false,
            "cache_response_codes": [],
            "enable_upstream_cache_control": false,
            "cache_control_ttl_header": ""
        },
        "session_lifetime": 0,
        "active": true,
        "auth_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "session_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "event_handlers": {
            "events": {}
        },
        "enable_batch_request_support": false,
        "enable_ip_whitelisting": false,
        "allowed_ips": [],
        "enable_ip_blacklisting": false,
        "blacklisted_ips": [],
        "dont_set_quota_on_create": false,
        "expire_analytics_after": 0,
        "response_processors": [],
        "CORS": {
            "enable": false,
            "allowed_origins": [],
            "allowed_methods": [],
            "allowed_headers": [],
            "exposed_headers": [],
            "allow_credentials": false,
            "max_age": 24,
            "options_passthrough": false,
            "debug": false
        },
        "domain": "",
        "do_not_track": false,
        "tags": [],
        "enable_context_vars": false,
        "config_data": {},
        "tag_headers": [],
        "global_rate_limit": {
            "rate": 0,
            "per": 0
        },
        "strip_auth_data": false
    }

**Comment by davegarvey** [comment]
Recording:

![version-not-exist](https://user-images.githubusercontent.com/1711419/51579474-0706f880-1efc-11e9-9936-a31ebb9de0be.gif)

**Comment by davegarvey** [comment]
Have updated original comment to include hyphen issues on the same topic.
