### ISSUE TITLE
Gateway does not forward `proxy-authorization` header

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#2076]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Gateway does not forward `proxy-authorization` header to server when sent in request.

**What is the expected behavior?**
`proxy-authorization` header and value received by server when sent in request.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Send request similar to this to the `headers` endpoint of the HTTPbin service:

    curl -X GET \
    http://tyk-gateway.local:8080/httpbin/headers \
    -H 'Proxy-Authorization: 1' 
   
Response will not include the `proxy-authorization` header.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.7.3
Not aware if working in previous version.

**Comment by asoorm** [comment]
Looks like it is httpbin stripping this header

```
curl -X GET http://httpbin.org/headers -H 'Proxy-Authorization: 1'
{
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.61.0"
  }
}
```

**Comment by davegarvey** [comment]
I found some more info on this:

> This is expected. Per the HTTP/1.1 specification, the Proxy-Authenticate and Proxy-Authorization headers are defined as "hop-by-hop" headers. Per section 13.5.1:
> 
> Hop-by-hop headers, which are meaningful only for a single transport-level connection, and are not stored by caches or forwarded by proxies.
> 
> Because of this, pre-processing of the request will strip these headers and they will not be available during service processing policies.

**Comment by davegarvey** [comment]
`proxy-authorization` is expected to be removed as it is a 'hop-by-hop' header which is only valid for a single connection.
