### ISSUE TITLE
Request for xmlMarshal function in body transform

### ISSUE THREAD

**Issue by andrewscode** [TykTechnologies/tyk#2086]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
There is currently no way to escape xml outputs in a body transform

I have a Template:

`<test>{{ index . “test” }}</ test>`

And a json payload:

`{“test”: " < "}`

This outputs:

`<test> < </test>`
Which is clearly invalid xml.

**What is the expected behavior?**
To be able to escape xml output in a body transform.   jsonMarshal was added for json transforms,  a xmlMarshal is also needed

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by letzya** [comment]
Hopefully in the next 2.8.2 release
