### ISSUE TITLE
Custom Middleware Erased from Mongo

### ISSUE THREAD

**Issue by philipbjorge** [TykTechnologies/tyk#209]
Hey,
I've added custom middleware directly to my API document stored in the mongodb tyk_apis collection.
This works great, except whenever I update my API via the dashboard this information is erased.
Is this a known issue?

I see that you can leverage directory-based middleware here https://tyk.io/v1.9/plugins/tyk-middleware-directories/
But that seems less than ideal since you have to deploy these files to all of your running tyk nodes, correct?

This isn't a terrible deploy step, but are there plans to improve support in the dashboard?

**Comment by lonelycode** [comment]
No, directory based middleware was created for this very purpose. We don't want dashboard users guessing where files are located on servers.

**Comment by philipbjorge** [comment]
Alright, that's not a terrible deployment step and we'll live with it :).
Is middleware supported at all on the tyk cloud offering?

Related, there's a typo in the docs -- `-------- pst/` should be post.

**Comment by lonelycode** [comment]
Thx, we're overhauling docs so that will be handled in the sweep.
