### ISSUE TITLE
Url Rewrite doesn't work with full hostname

### ISSUE THREAD

**Issue by andrewscode** [TykTechnologies/tyk#2092]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Create an API with Target URL: http://www.test.com
Listen path: /test

Create Endpoint Path  /test/two
Add URL Rewrite:
Match Pattern:  /test/two
Rewrite to:  http://www.google.com

Sending a request to {gateway}/test/two  will pull from http://www.test.com 

**What is the expected behavior?**
The above should pull from google.com

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This worked in 2.7.4 and was broken with the latest release 2.7.5

**Comment by andrewscode** [comment]
> {
  "api_model": {},
  "api_definition": {
    "api_id": "5e0f9b307db148d57d48399258e146f4",
    "jwt_issued_at_validation_skew": 0,
    "upstream_certificates": {},
    "use_keyless": true,
    "enable_coprocess_auth": false,
    "custom_middleware": {
      "pre": [],
      "post": [],
      "post_key_auth": [],
      "auth_check": {
        "name": "",
        "path": "",
        "require_session": false
      },
      "response": [],
      "driver": "",
      "id_extractor": {
        "extract_from": "",
        "extract_with": "",
        "extractor_config": {}
      }
    },
    "disable_quota": false,
    "custom_middleware_bundle": "",
    "cache_options": {
      "cache_timeout": 60,
      "enable_cache": false,
      "cache_all_safe_requests": false,
      "cache_response_codes": [],
      "enable_upstream_cache_control": false,
      "cache_control_ttl_header": ""
    },
    "enable_ip_blacklisting": false,
    "tag_headers": [],
    "pinned_public_keys": {},
    "expire_analytics_after": 0,
    "domain": "",
    "openid_options": {
      "providers": [],
      "segregate_by_client": false
    },
    "active": true,
    "jwt_expires_at_validation_skew": 0,
    "config_data": {},
    "notifications": {
      "shared_secret": "",
      "oauth_on_keychange_url": ""
    },
    "auth": {
      "auth_header_name": "",
      "use_certificate": false
    },
    "check_host_against_uptime_tests": false,
    "auth_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "blacklisted_ips": [],
    "hmac_allowed_clock_skew": -1,
    "dont_set_quota_on_create": false,
    "uptime_tests": {
      "check_list": [],
      "config": {
        "expire_utime_after": 0,
        "service_discovery": {
          "use_discovery_service": false,
          "query_endpoint": "",
          "use_nested_query": false,
          "parent_data_path": "",
          "data_path": "",
          "cache_timeout": 60
        },
        "recheck_wait": 0
      }
    },
    "enable_jwt": false,
    "do_not_track": false,
    "name": "Test",
    "slug": "test",
    "oauth_meta": {
      "allowed_access_types": [],
      "allowed_authorize_types": [],
      "auth_login_redirect": ""
    },
    "CORS": {
      "enable": false,
      "max_age": 24,
      "allow_credentials": false,
      "exposed_headers": [],
      "allowed_headers": [],
      "options_passthrough": false,
      "debug": false,
      "allowed_origins": [],
      "allowed_methods": []
    },
    "event_handlers": {
      "events": {}
    },
    "proxy": {
      "target_url": "http://www.test.com",
      "endpoint_returns_list": false,
      "cache_timeout": 0,
      "parent_data_path": "",
      "service_discovery": {
        "endpoint_returns_list": false,
        "cache_timeout": 0,
        "parent_data_path": "",
        "query_endpoint": "",
        "use_discovery_service": false,
        "target_path": "",
        "use_target_list": false,
        "use_nested_query": false,
        "data_path": "",
        "port_data_path": ""
      },
      "check_host_against_uptime_tests": false,
      "transport": {
        "ssl_ciphers": [],
        "ssl_min_version": 0,
        "proxy_url": ""
      },
      "target_list": [],
      "query_endpoint": "",
      "use_discovery_service": false,
      "_sd_show_port_path": false,
      "preserve_host_header": false,
      "use_target_list": false,
      "strip_listen_path": false,
      "use_nested_query": false,
      "data_path": "",
      "port_data_path": "",
      "enable_load_balancing": false,
      "listen_path": "/test",
      "disable_strip_slash": false
    },
    "client_certificates": [],
    "use_basic_auth": false,
    "version_data": {
      "not_versioned": true,
      "default_version": "",
      "versions": {
        "Default": {
          "name": "Default",
          "expires": "",
          "paths": {
            "ignored": [],
            "white_list": [],
            "black_list": []
          },
          "use_extended_paths": true,
          "global_headers": {},
          "global_headers_remove": [],
          "global_size_limit": 0,
          "override_target": "",
          "extended_paths": {
            "url_rewrites": [
              {
                "path": "/test/two",
                "method": "GET",
                "match_pattern": "/test/two",
                "rewrite_to": "http://www.google.com",
                "triggers": [],
                "MatchRegexp": null
              }
            ],
            "track_endpoints": [
              {
                "path": "/test/two",
                "method": "GET"
              }
            ]
          }
        }
      }
    },
    "use_standard_auth": false,
    "session_lifetime": 0,
    "hmac_allowed_algorithms": [],
    "disable_rate_limit": false,
    "definition": {
      "location": "header",
      "key": "x-api-version",
      "strip_path": false
    },
    "use_oauth2": false,
    "jwt_not_before_validation_skew": 0,
    "allowed_ips": [],
    "org_id": "5bf43f83335a5d43d577a82e",
    "enable_ip_whitelisting": false,
    "global_rate_limit": {
      "rate": 0,
      "per": 0
    },
    "enable_context_vars": true,
    "tags": [],
    "basic_auth": {
      "disable_caching": false,
      "cache_ttl": 0
    },
    "session_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "strip_auth_data": false,
    "id": "5c50c442335a5d3331e7490a",
    "certificates": [],
    "enable_signature_checking": false,
    "use_openid": false,
    "jwt_skip_kid": false,
    "enable_batch_request_support": false,
    "response_processors": [
      {
        "name": "header_injector",
        "options": {}
      },
      {
        "name": "response_body_transform",
        "options": {}
      }
    ],
    "use_mutual_tls_auth": false
  },
  "hook_references": [],
  "is_site": false,
  "sort_by": 0
}

**Comment by ilijabojanovic** [comment]
@andrewscode Hi, we are not able to reproduce issue with attached api definition.  Could you please attach yours tyk configuration?

Also when we trigger `GET` call to {gateway_url)/test/test/two we are getting google page in response

**Comment by andrewscode** [comment]
See attached.
[tyk.zip](https://github.com/TykTechnologies/tyk/files/2814090/tyk.zip)

We had to downgrade back to 2.7.4 since the upgrade caused most of our API's to break.

**Comment by andrewscode** [comment]
Just upgraded to Tyk 2.7.6 and had the exact same issue with that api

**Comment by andrewscode** [comment]
To Summarize:

2.7.4:   google.com is fetched  (correct)
2.7.5:   microsoft.com is fetched  (bad)
2.7.6:   microsoft.com is fetched  (bad0

**Comment by ilijabojanovic** [comment]
@andrewscode thank you for feedback, we are still investigating yours issue, since we where not able to reproduce.

**Comment by ilijabojanovic** [comment]
@andrewscode in yours api definition we have this:
`"listen_path": "/test",` that means gateway listen on `{gateway_url}/test` and endpoint which you wish to rewrite is `{gateway_url}/{listen_path}/test/two` which give us `{gateway_url}/test/test/two`

**Comment by ilijabojanovic** [comment]
@andrewscode when we fixed this bug https://github.com/TykTechnologies/tyk/issues/2067 that change introduced breaking on yours api definitions.

**Comment by andrewscode** [comment]
Ok,  I can just update my api's then.    This change probably makes more sense anyway.

Thanks

**Comment by ilijabojanovic** [comment]
@andrewscode yes, since endpoint url rewrite plugin works per api definition, there is no need to add listen_path in url rewrite for matching.
