### ISSUE TITLE
Add new endpoint to edit oauth-client

### ISSUE THREAD

**Issue by dencoded** [TykTechnologies/tyk#2094]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
It is not possible to edit oauth-client info at the moment.
**What is the expected behavior?**
We need to add new endpoint to edit oauth-client. Also,  add new field to oauth-client to store "title" , allow to edit "title", "redirect_uri" and "policy_id" fields. Also, we need to decide what to do with issued tokens after policy_id changed as it might provide different access. Probably just delete non expired tokens issued for that oauth-client.

This is in scope of https://github.com/TykTechnologies/product/issues/19

**Comment by ilijabojanovic** [comment]
Verified
