### ISSUE TITLE
Allow use Dashboard SSO API for cloud/multi-cloud

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2103]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
At the moment SSO API works requires using Admin API. And Admin API not available for multi-cloud/cloud Tyk offering
**What is the expected behavior?**
Expose the same API to regular API, working on the organization level.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.X

**Comment by letzya** [comment]
and also update TIB to use this endpoint

**Comment by buger** [comment]
@furkansenharputlu  TIB task https://github.com/TykTechnologies/tyk-identity-broker/issues/55
