### ISSUE TITLE
XML schema validation for requests

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#2113]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
XML validation is not possible out-of-the-box

**What is the expected behavior?**
Similar to the existing 'Validate JSON' plugin. Allow user to select a 'Validate XML' plugin for an endpoint. When selected, the plugin would provide ability to select an HTTP response code to return when the validation fails, and provide the XML schema to match the request against.

Suggest using standard W3C (XSD) approach, as this appears to be [supported in golang](https://godoc.org/github.com/lestrrat/go-libxml2/xsd).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
n/a

**Comment by matiasinsaurralde** [comment]
We should also evaluate [packages](https://github.com/search?l=Go&o=desc&q=xsd&s=stars&type=Repositories) ([go-xsd](https://github.com/metaleap/go-xsd)?) that are purely written in Go (`go-libxml2` will introduce a `libxml2` link/requirement). Last time I checked this was around 3 years ago and couldn't find a good replacement.

**Comment by buger** [comment]
Yes, it can be a blocker, unless we can reliably statically link it. And so far this list does not looks that promising :(

**Comment by komalsukhani** [comment]
I have checked available Go packages. All of the viable options are just wrapper around `libxml2`.

**Comment by letzya** [comment]
:(

**Comment by letzya** [comment]
+1 client

**Comment by matiasinsaurralde** [comment]
> I have checked available Go packages. All of the viable options are just wrapper around `libxml2`.

From what I've explored it seems the alternatives remain the same, [xgen](https://github.com/xuri/xgen) looks promising.

**Comment by sedkis** [comment]
WAF plugin will do this using ModSecurity as JS plugin in Tyk:
https://www.youtube.com/watch?v=6j6h2LDslSs&t=256s

**Comment by Lvceo** [comment]
+1 client VTB (Russian bank) wants it too.
In both ways, request & response validation, plus using an XSD file.

**Comment by educroquet** [comment]
+1
