### ISSUE TITLE
Support looping to another api

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2120]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
In 2.8 we add support for looping, by introducing special "tyk://" urls. And as host it currently supports "self", which means the same API.
**What is the expected behavior?**
It would be nice if we could target another API, so I can build really complex pipelines.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by ilijabojanovic** [comment]
Verified
