### ISSUE TITLE
"Uncaught TypeError: arcs[idx] is not a function" if chaning default search parameters in API Activity Dashboard 

### ISSUE THREAD

**Issue by edgarskrauklis** [TykTechnologies/tyk#2135]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

under API Activity Dashboard when changing date range from default to smaller (one day) or also when changing to smaller one + period changed from daily to hourly charts doesn't loads fully and isn't possible to see information about latency/calls per hour or per day.

**What is the expected behavior?**

charts should load in the same way as under fresh f5 reload (when it opens with default search parametrs). and it is possible to see information on chart about latency, api call numbers

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1.under api activity dashboard press f5 to refresh page. - in result chart have grid lines and is possible to get information about trafic by moving mouse cursor on chart. by default chart is displayed for date range: 17.feb.2019-25.feb.2019, period: daily.
2.if change from from date 17.feb.2019 -> 24.feb.2019 and press search button - then chart isn't loaded fully - missing grid.

my guess is that it started only when some api returned http 50x error. i'm ussing for trial TYK product only few days and it happened only starting from today when i made setup for "api passthrough"and endpoint tracking. In result pie chart in api activity dashboard had two type erors - 40x and 50x. maybe it is somehow related.

in console logs is javascript error. (attached console log file)
[192.168.1.152-1551031113447.log](https://github.com/TykTechnologies/tyk/files/2898204/192.168.1.152-1551031113447.log)
[tyk_activity_dashboard_bug.zip](https://github.com/TykTechnologies/tyk/files/2898205/tyk_activity_dashboard_bug.zip)

*in zip is windows step recorder result
*also made flv file - uploaded to onedrive
https://1drv.ms/u/s!Av2ltWfLBQZQg69g_kYWHQi9-SqGtA 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

about previous versions hard to say - currently investigating which egateway api could use for projects. TYK product used for several days only - checking functionality/posibilities.
dashboard version: Dashboard (v1.7.5)

**Comment by buger** [comment]
@lghiur ^

**Comment by buger** [comment]
Thank you for reporting!

**Comment by buger** [comment]
This is a known bug, should be fixed in upcoming 2.8 release.
