### ISSUE TITLE
UDP support of Logstash Connector is broken

### ISSUE THREAD

**Issue by zeldal** [TykTechnologies/tyk#2136]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
https://github.com/netbrain/goautosocket does not support UDP protocol for Logstash

**What is the expected behavior?**
UDP support for Logstash Connector

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
tyk-gateway 2.7.6 contains https://github.com/TykTechnologies/tyk/issues/1968 https://github.com/TykTechnologies/tyk/pull/1969 which disables UDP support for Logstash Connector by moving "github.com/bshuster-repo/logrus-logstash-hook to github.com/netbrain/goautosocket.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
v2.7.6 is affected. v2.7.4 is working

**Comment by buger** [comment]
The fix, in this case, will be disabling new `gas` "reconnect" functionality if transport is UDP, e.g. back to previous behavior.
