### ISSUE TITLE
Does tyk gateway work on Rasbian OS?

### ISSUE THREAD

**Issue by l0oky** [TykTechnologies/tyk#214]
I want to make a small home gateway on _Raspberry Pi_. I've heard It has some software limitations due to Its _ARM Cortex_ set of instructions on _Raspbian_ (OS based on _Debian_ for _Raspberry Pi_)..

Has anyone tried running `tyk-gateway` on _Rasbian_? Is It worth trying?
Thank you :)

**Comment by lonelycode** [comment]
We've successfully tested Tyk on Scaleway's ARM infrastructure, there's no reason Tyk wouldn't work for Raspberry Pi, and it would make full use of its multiple cores.

The only problem would be Redis, which needs a lot of RAM, so that would need to live elsewhere.

**Comment by l0oky** [comment]
If I may ask, what's the minimum memory required? Redis uses ~200 MB of memory at 1 Million keys according to [this article](http://redis.io/topics/faq).

**Comment by lonelycode** [comment]
Well, Tyk uses Redis as the primary key store and rate limiter bucket store, so there's quite a lot of interaction between the two.

Tyk uses as much RAM as it needs depending on traffic and the number of objects in memory so it grows and shrinks.

Redis, if misconfigured could be volatile and start ejecting keys if you aren't careful, which could cause key owners to no longer have access :-)

If you are recording analytics, then expect more RAM usage. Though if you are doing that, do not expect to be able to run the dashboard as that also requires MongoDB.

When we did our Scaleway tests, we had Tyk Gateway and Redis separate, and Mongo and Dashboard separate. 

I'm not saying that it wont work - it will - but you'll need to be careful about RAM as the process could be killed if you run out of memory. You also need to consider that your 1GB or RAM will also have to hold the Linux distro, and some of that RAM is reserved for the GPU on the RPi.
