### ISSUE TITLE
support bool jwt claims

### ISSUE THREAD

**Issue by altaurog** [TykTechnologies/tyk#2140]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
with the following in my app config:
```
  "version_data": {
    "not_versioned": false,
    "default_version": "v1",
    "versions": {
      "v1": {
        "name": "v1",
        "use_extended_paths": false,
        "global_headers": {
          "X-Username": "$tyk_context.jwt_claims_sub",
          "X-Extra-Features": "$tyk_context.jwt_claims_extf"
        }
      }
    }
  },
```
if `extf` claim is a boolean, tyk logs following error message and sends empty header:
```
time="Feb 26 15:26:24" level=error msg="Context variable type is not supported: bool" 
```

**What is the expected behavior?**
header should be set to `true` or `false` appropriately

The following patch works for me.  My inclination is headers set to jwt_claims should just use straight json encoding, but this isn’t compatible with current behavior (see #1802, for example).
```
diff --git a/mw_url_rewrite.go b/mw_url_rewrite.go
index b43798a4..f3ac443b 100644
--- a/mw_url_rewrite.go
+++ b/mw_url_rewrite.go
@@ -220,6 +220,12 @@ func replaceTykVariables(r *http.Request, in string, escape bool) string {
 func valToStr(v interface{}) string {
 	s := ""
 	switch x := v.(type) {
+	case bool:
+		if x {
+			s = "true"
+		} else {
+			s = "false"
+		}
 	case string:
 		s = x
 	case float64:
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
version from #1802

**Comment by buger** [comment]
I believe it should be already fixed in recent versions

**Comment by altaurog** [comment]
@buger what version?  It doesn’t look to me like `bool` is supported on master:
https://github.com/TykTechnologies/tyk/blob/master/mw_url_rewrite.go#L228

**Comment by altaurog** [comment]
still an issue in tyk 2.7.7
