### ISSUE TITLE
Dashbord can't save my service discovery setting?

### ISSUE THREAD

**Issue by tokingHong** [TykTechnologies/tyk#2146]
![image](https://user-images.githubusercontent.com/39825820/53546554-a48ec100-3b67-11e9-966b-87d5485cb6f8.png)

When I updated this api,and it lost after I fresh the page???like I never set this even the page notice that I have change api successfully.And in database,it shows 
![image](https://user-images.githubusercontent.com/39825820/53546820-53cb9800-3b68-11e9-92ef-d9899203bde3.png)

And when I use service discovery,what should I set in this?
![image](https://user-images.githubusercontent.com/39825820/53546838-63e37780-3b68-11e9-9cf6-cc25d5bf6e24.png)

**Comment by buger** [comment]
Can you clarify which version of dashboard do you use?

**Comment by tokingHong** [comment]
> Can you clarify which version of dashboard do you use?

v1.7.5  and v1.7.3 has the same problom.  1.7.5 run in docker
![image](https://user-images.githubusercontent.com/39825820/53547369-cf7a1480-3b69-11e9-9a9f-959205466927.png)

**Comment by tokingHong** [comment]
![image](https://user-images.githubusercontent.com/39825820/53548575-c5a5e080-3b6c-11e9-8c5d-c991bcb30241.png)
console print

**Comment by tokingHong** [comment]
![image](https://user-images.githubusercontent.com/39825820/53616854-88e6f180-3c1f-11e9-8f97-ac336a7d6835.png)
this resource matters？ @lghiur

**Comment by lghiur** [comment]
Hi @tokingHong, thanks for raising this up, a fix has been found and it will go out in the next patch release (ETA 2-3 weeks)

**Comment by ilijabojanovic** [comment]
Issue is fixed and included in release 1.7.6

**Comment by tokingHong** [comment]
@ilijabojanovic Thanks，When will the docker version be updated?
