### ISSUE TITLE
As a dashboard user I want to be able to stop other users from using my gateway

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2149]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I need to be able to stop other users (my colleagues from other teams for instance, or maybe use of common tags, such as `test`, by other teams) from using my gateway.

I can do sharding but anyone can create apis with my gateway's tagging.
To prevent this, at the moment, I can only to manage it outside tyk (i.e. email everyone not to use tag XYZ and maybe add another layer to api crwation/update to verify the api definition, using Jenkins for instance.

**What is the expected behavior?**
I want the dashboard to manage the access to the gateway.
Since an api is owned by a user/s (or group/s) the gateway will load only apis for that user.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.6

**Comment by buger** [comment]
Placeholder for things needs to be done:
- [ ] Use API key/OrgID for on-premise Gateway during dashboard initialization, similar to RPC mode.
- [ ] Add "new" dashboard API to fetch configurations, similar to our `/system` APIs (and add a way to disable or some restrict /systems API)
- [ ] Allow whitelist allowed domains in gateway config

**Comment by letzya** [comment]
:(

**Comment by agata-wit** [comment]
@letzya I would like to catch up with you on this to get more detail. Looks like a good idea for an enhancement and I want to make sure I understand the functionality fully. I'll set a quick catch up for us.

**Comment by letzya** [comment]
FYI, OPA could probably help here. Not OOTB solution but at least it can reject api def creation/update with certain tags that can be define in the config section or in the `additional_permissions` field find a wa

**Comment by letzya** [comment]
@sedkis do you know if we have users that are interested in this kind of capability?

**Comment by letzya** [comment]
We solved this in mdcb with ownership
