### ISSUE TITLE
Create API tutorial using API not seems to works with v1.9 in docker

### ISSUE THREAD

**Issue by gavinzhou** [TykTechnologies/tyk#215]
I use [lonelycode/tyk_quickstart](https://github.com/lonelycode/tyk_quickstart) create tyk in docker.

I created api key use dashboard by tutorial.

```
curl -s -H "Authorization: null" http://127.0.0.1/test-api/get|jq
{
  "error": "Authorization field missing"
}
```

I get new key
```
Success
New key created: 56e53cb57c1ab400010000018c13e7164e4c485f52d4496bcb9f2024
```

```
curl -s -H "Authorization: 56e53cb57c1ab400010000018c13e7164e4c485f52d4496bcb9f2024" http://127.0.0.1/test-api/get|jq
{
  "error": "Authorization field missing"
}
```
I get docker log
```
docker logs -f f2e69387a450
time="2016-03-13T10:32:58Z" level=info msg="Attempted access with malformed header, no auth header found." origin="172.17.0.1:60537" path="/test-api/get"
```

**Comment by lonelycode** [comment]
What did you call your authorisation header? That error is not about the key, but the header itself.

Also, did you [follow this guide](https://tyk.io/v1.9/setup/docker/)?

**Comment by lonelycode** [comment]
Closing because this isn't a bug. Please use & search the community forum for this kind of thing.
