### ISSUE TITLE
No Rate Limiting

### ISSUE THREAD

**Issue by ghost** [TykTechnologies/tyk#2152]
Hi Team,
While testing  I found a vulnerability in your site.

Bug Name : No Rate Limiting on Password Reset

Vulnerable Link : https://cloud.tyk.io/reset

Description:-Attacker can send "Unlimited email on user's account"

Browsers Verified In:- [Mozilla Firefox ] & [Burp Suite Software]

Steps To Reproduce:

1:-In this Attack First open Mozilla Firefox And visit (https://cloud.tyk.io/reset)

2:-Now Click On My Account And then Forgot Password And type Your Email-id

3:-Before Clicking Submit You Should Add The Proxy And Now Click Submit And Catch The Request In Burp Suite.

4:-Now open Your Burp suite and right Click and Click Send to Intruder Then Select the Email And Click Add Then Go to Payloads And load The Email Text File Then Click Start Attack.

6:-Now Check Your Email .

7:-I found many email.

PFA

Regards,
Pranshu

**Comment by PranshuTheHacker** [comment]
is this how your bug bounty works, for 1 year there was no reply and now without any decision report is closed?

**Comment by letzya** [comment]
@ghost reopen the issue. sorry for that

**Comment by agata-wit** [comment]
@buger @matiasinsaurralde is this still possible to replicate? Have you looked at it lately?

**Comment by andyo-tyk** [comment]
Tyk has an active bug bounty programme on Zerocopter, which is the best place to report any similar issues you might find.

This reported issue should no longer be a concern and is not present in the current Tyk Cloud deployment.
