### ISSUE TITLE
Basic and OAuth2 authentication flows

### ISSUE THREAD

**Issue by lomori** [TykTechnologies/tyk#216]
Not sure if this is the appropriate place for questions like this. If not please point us to the right place. We are yet another company evaluating TYK and have been trying to understand its core architecture. It would be great to get more info on the following points:
1) Plugin mechanism: those seem to be geared towards small extensions to the existing functionality. So let's say we want to implement another log service that fits our very specific needs. Should we do it in JavaScript or Go?
2) Access Control -> Basic Authentication: TYK documents seems to indicate that passwords are defined with the API. Is this right? What if we want like LDAP?
3) Would you have samples of Access Control using OAUTH2 where the Identity Provider is independent of TYK?
4) The Dashboard seems to be extremely sensitive to the address it's being access (localhost, 127.0.0.1, machine IP, machine name). Is this by design? It's causing some problems to us due to our network environment: multiple network interfaces thus multiple IPs, in some cases multiple network names. 

Regards,
Luiz

**Comment by lonelycode** [comment]
The best place for this question would be on the [community forum](https://community.tyk.io), but I'll answer these here to prevent duplication:

> 1) Plugin mechanism: those seem to be geared towards small extensions to the existing functionality. So let's say we want to implement another log service that fits our very specific needs. Should we do it in JavaScript or Go?

You would want to do this in go, the logger we use is pluggable so extending it is very simple. We have also externalised our time-series analytics pump mechanism to a third-party service which is very small and easy to customise (Tyk Pump)

> 2) Access Control -> Basic Authentication: TYK documents seems to indicate that passwords are defined with the API. Is this right? What if we want like LDAP?

Take a look at the [Tyk Identity Broker](https://github.com/TykTechnologies/tyk-identity-broker/wiki) to handle integrations with IDM's - it's a pluggable open source project that handles integration with the Tyk Component structure.

> 3) Would you have samples of Access Control using OAUTH2 where the Identity Provider is independent of TYK?

There's some examples in TIB, we've managed to get it working with OAuth providers like Auth0 with no modification. There's not example, but it was discussed in the community form.

> 4) The Dashboard seems to be extremely sensitive to the address it's being access (localhost, 127.0.0.1, machine IP, machine name). Is this by design? It's causing some problems to us due to our network environment: multiple network interfaces thus multiple IPs, in some cases multiple network names.

You can force the dashboard to bind to a specific domain name or host name, it's covered in the configuration docs. As part of tyhe latest versions we removed a dependency on NginX to handle domains, that is all internalised now, so yes, binding to domains is sensitive if misconfigured

**Comment by lomori** [comment]
4) I followed the setup instructions. If the domain name is "forced" there then that's what I got. Have you tried that with the latest version of TYK? In any case. how can make it more generic?

**Comment by lonelycode** [comment]
@lomori You switch off the domain binding in the dashboard configuration:

https://tyk.io/v1.9/configuration/dashboard-config/#enable-host-names:8f1ac6c580c2f6cd2c8954a33f3ca4d6

I think for the default setup instructions this is all enabled because of the portal. You can;t have one without the other.

**Comment by lomori** [comment]
Yes, some light, finally I can access the dashboard outside my VM...
