### ISSUE TITLE
As a developer in the portal I want to register my 3rd party client_id for an OIDC protected api

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2173]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Not supported in the developer portal

**What is the expected behavior?**
Self-service for APIs with oidc authentication. A developer should be able to register his 3rd party client_id (from Okta or ping for instance) and not ask a dashboard admin to onboard it for him.

Requires also updating the developer portal UI and possibly the dashboard api screen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.7.6

**Comment by RichiCoder1** [comment]
Supporting https://developer.okta.com/docs/reference/api/oauth-clients/#getting-started would be a great extension of this.
