### ISSUE TITLE
Url rewrite does not rewrite properly when port is included in hostname

### ISSUE THREAD

**Issue by andrewscode** [TykTechnologies/tyk#2183]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using rewrite to a url with a port (http://google.com:8080/notbeinghit),  tyk will not attempt to hit google but instead go locally at /notbeinghit

**What is the expected behavior?**
http://google.com:8080/notbeinghit   should be hit

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Simply create an endpoint that uses url rewrite to a url with a port.
http://google.com:8080/notbeinghit

When the api is requested, it will try to hit "/notbeinghit" locally

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7.6
[tyk-local.txt](https://github.com/TykTechnologies/tyk/files/3019938/tyk-local.txt)

**Comment by ilijabojanovic** [comment]
Hi @andrewscode, we are not able to reproduce issue with provided api definition. Could you please attach yours gateway configuration?

**Comment by furkansenharputlu** [comment]
Hi @andrewscode, I couldn't understand what `but instead go locally at /notbeinghit` exactly means. Can you please also run gateway in debug mode(`--debug`) and share the logs when you make a request to that URL? The part that I need is something like that:

```[Apr  1 08:30:38] DEBUG Rewriter active
[Apr  1 08:30:38] DEBUG /test/port
[Apr  1 08:30:38] DEBUG Inbound path: /test/port
[Apr  1 08:30:38] DEBUG Rewriter checking matches, len is: 1
[Apr  1 08:30:38] DEBUG [/port: ]
[Apr  1 08:30:38] DEBUG []
[Apr  1 08:30:38] DEBUG URL Re-written from: /test/port
[Apr  1 08:30:38] DEBUG URL Re-written to: http://google.com:8080/notbeinghit
[Apr  1 08:30:38] DEBUG Detected a host rewrite in pattern!
[Apr  1 08:30:38] DEBUG Finished api_id=9c7300e7d73243e04e96a634c65e0002 api_name=test code=200 mw=URLRewriteMiddleware ns=323171 org_id=5ca198ddbca82a034d45819e origin=127.0.0.1 path=/test/port
[Apr  1 08:30:38] DEBUG Started proxy
[Apr  1 08:30:38] DEBUG Stripping: /test/
[Apr  1 08:30:38] DEBUG Upstream Path is: /notbeinghit
[Apr  1 08:30:38] DEBUG UPSTREAM REQUEST URL: http://google.com:8080/notbeinghit
[Apr  1 08:30:38] DEBUG Detected host rewrite, notifying director
[Apr  1 08:30:38] DEBUG Detected host rewrite, overriding target
[Apr  1 08:30:38] DEBUG Outbound Request: http://google.com:8080/notbeinghit
````

**Comment by andrewscode** [comment]
I think after more testing it's working correctly,  it's actually the tyk logs are confusing as it appears in the logs that the gateway is connecting to itself instead of the external site.

I'll do some more validation and get back to you.

**Comment by andrewscode** [comment]
Ok, so I think what is confusing us is the logs.

In the log browser when posting to <ourdomain>/test/port:

POST /notbeinghit HTTP/1.1
Host: <our domain>

When in reality, the logs should show the host as google.com or the POST path should be the original path.   From the logs it looks as if it's connecting back to our server instead of the intended host.

**Comment by furkansenharputlu** [comment]
@andrewscode Yes, you're right, Thank you for reporting! I will work on adding new `Host` field in Log Browser.
