### ISSUE TITLE
multiple Access-Control-Allow-Origin response headers

### ISSUE THREAD

**Issue by altaurog** [TykTechnologies/tyk#2199]
**Do you want to request a *feature* or report a *bug*?**
arguably a bug

**What is the current behavior?**
With `"CORS": {"enable": true}`, can get multiple `Access-Control-Allow-Origin` headers, which violates CORS standard and [causes request to fail in the browser](https://www.w3.org/TR/cors/#resource-sharing-check):
> If the response includes zero or more than one Access-Control-Allow-Origin header values, return fail and terminate this algorithm.

**What is the expected behavior?**
tyk should return exactly one `Access-Control-Allow-Origin` header, no matter what.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Include something like the following in tyk api definition and point to an API that supports CORS:
```json
  "CORS": {
    "enable": true,
    "debug": false,
    "allowed_origins": ["*"],
    "allowed_methods": ["GET"],
    "allowed_headers": ["accept", "authorization", "content-type"],
    "exposed_headers": [],
    "allow_credentials": false,
    "max_age": 24,
    "options_passthrough": false
  }
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions I have tried, including `2.7` and `v2.7.7` tags

**Comment by altaurog** [comment]
This might be relevant: https://github.com/rs/cors/issues/45

**Comment by matiasinsaurralde** [comment]
@altaurog Thanks for reporting the issue, I've been able to reproduce it with the configuration you've shared:
```
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: test.com
< Access-Control-Allow-Origin: test.com
< Content-Type: application/json
< Date: Sun, 07 Apr 2019 14:53:38 GMT
< Server: nginx
< Vary: Origin
< X-Ratelimit-Limit: 0
< X-Ratelimit-Remaining: 0
< X-Ratelimit-Reset: 0
< Content-Length: 164
```
We'll investigate potential solutions for this.

**Comment by altaurog** [comment]
Now this is interesting.  I disabled CORS on the upstream API and I am still getting duplicate ACAO headers from tyk.

**Comment by altaurog** [comment]
If a virtual endpoint adds the ACAO header, that also results in a duplicate.

**Comment by ilijabojanovic** [comment]
@buger please merge in to release-2.8
