### ISSUE TITLE
gRPC fails when sending large messages

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2203]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using a gRPC plugin and sending a message that's larger than 4 MB, the request fails.
4 MB is the default value for maximum length as mentioned [here](https://github.com/googleapis/google-cloud-node/issues/1991).

**What is the expected behavior?**
It should be possible to configure this parameter.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
All
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by buger** [comment]
There was additional PR which fix small issue https://github.com/TykTechnologies/tyk/pull/2855

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic I have created this test program that you could use, instructions in the README:
https://github.com/matiasinsaurralde/grpc-large-msg
