### ISSUE TITLE
Api definitions with custom domain should be loaded first

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2206]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we have api definition with custom domain, api def is loaded per alphabet 
**What is the expected behavior?**
Api definitions with custom domains should be loaded first
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api-oauth2/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api-basic/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api-token/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api-oauth/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api-mtls/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /search/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: api.tyk-test.com/node2/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /mtls/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /test/{rest:.*}
[Apr 12 00:02:04]  INFO main: Processed and listening on: /api/{rest:.*}
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master/2.8

**Comment by joshblakeley** [comment]
Does this order actually matter?

**Comment by carlosjgp** [comment]
I'm interested in this issue since I'm going to start using Tyk.

Why does the order matters and how is the outcome different when the order changes?
Can you provide more details or an example @ilijabojanovic, please ?
