### ISSUE TITLE
occurence of listen_path is removed from re-written url

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2211]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If `strip_listen_path` is enabled and rewrite plugin rewrites to URL that contains the same keyword as the `listen_path`, the occurrence of this word is removed from the URL.

**What is the expected behavior?**
occurence of `listen_path` keyword shouldn't be removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create an API with listen_path `/myapi/`
2. Enable Strip Listen Path option
2. Create an endpoint `/anything`
3. Create URL-Rewrite plugin for `/anything` with matchPattern `/anything/(.*)` and rewrite path `http:/httpbin.org/anything/$1`

Make a call  to `https://tyk-gateway:8181/myapi/anything/a/myapi/b/c`

Instead of calling `/anything/a/myapi/b/c`, `/anything/ab/c` upstream path will get called.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
master/release2.7

**Comment by ilijabojanovic** [comment]
Verified @buger please merge in to release-1.8

**Comment by buger** [comment]
^ done
