### ISSUE TITLE
2.6.4 to 2.7.7: "Can't retrieve key quota" error="key not found" 

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#2221]
I'm migrating some traffic that is currently directed to gateways running 2.6.4 to gateways running 2.7.7. 

There have been no changes to any api definitions.

Traffic hitting the 2.7.7 gateways generates a ton of error messages like this:

```
"Can't retrieve key quota" error="key not found" key="****XX0=" status=ok 
```

These messages do not appear on the 2.6.4 gateways.

What does this mean exactly? Is this some incompatibility between sessions potentially generated in 2.6.4 to 2.7.7?

**Comment by buger** [comment]
Hi! I assume it does not affect functionality? 

In general, this looks like a change in logging, which end up to be too verbose. 
Currently, it looks like a message which gets thrown on "first" quota check for a new key.

**Comment by bitsofinfo** [comment]
it appears to be its unclear based on this message if its constantly creating new keys or still properly re-using them.

**Comment by bitsofinfo** [comment]
Please just clarify if this is simply a new extra log messages through a pre-existing (2.6.x) codepath or something new functionality wise; have an upgrade in hold status due to this.

**Comment by buger** [comment]
I can confirm it is a new log line, and it should not affect functionality.
