### ISSUE TITLE
The [DisableVirtualPathBlobs] on the https://tyk.io/docs/configure/tyk-gateway-configuration-options/ 

### ISSUE THREAD

**Issue by Liam-Wang** [TykTechnologies/tyk#2222]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
If you do not wish for virtual path JavaScript code that is loaded from the dashboard to run on virtual endpoints in the node,
	set this value to **false** and the code will not be loaded into the VM when the API definition initialises.
	This is useful for systems where you want to avoid having third-party code run.
**What is the expected behavior?**
If you do not wish for virtual path JavaScript code that is loaded from the dashboard to run on virtual endpoints in the node,
	set this value to **true** and the code will not be loaded into the VM when the API definition initialises.
	This is useful for systems where you want to avoid having third-party code run.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by furkansenharputlu** [comment]
Hi @Liam-Wang, Thanks for reporting! I'll fix it.
