### ISSUE TITLE
500 error when updating Admin user through Dashboard admin API

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2223]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
- `500` error response from the Dashboard API
- The user is not being updated

**What is the expected behavior?**
`200` and the user is updated with the new fields

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Using Admin API...
- Create organisation (`curl -XPOST...`)
- Create Admin user for that organisation (`curl -XPOST...`)
- Login into the Dashboard UI and change a field (`last_name` in my case)
- Update the user to the initial values using the same payload as the original `POST` request (`curl -XPUT...`)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
`v2.7.6`

**Comment by adelowo** [comment]
What is the response you received?

Can you also verify you have Redis up and running?

**Comment by carlosjgp** [comment]
Mongo and Redis are working other API calls work.

These are the messages from the resonse and Dashboard logs

```
{"Status":"Error","Message":"Could not update API session when update user","Meta":null}
```

```
time="Apr 23 15:33:02" level=warning msg="Login opened from: zzzz" 
time="Apr 23 15:33:05" level=warning msg="User pasword is empty! Please reset!" 
time="Apr 23 15:33:05" level=info msg="New user session created" 
time="Apr 23 15:33:05" level=warning msg="Login opened from: zzzz" 
time="Apr 23 15:33:05" level=warning msg="Flushing previous user sessions for (xxx@yyyy.com)" 
time="Apr 23 15:33:05" level=warning msg="Successful login (xxx@yyyy.com) from: 172.22.22.131:34070" 
time="Apr 23 15:33:05" level=warning msg="CreateSession got an empty session ID" error="empty session ID" sessionID= 
time="Apr 23 15:33:05" level=error msg="UpdateAPISession failed in AdminUpdateUser" error="empty session ID" 
```

**Comment by ConsM** [comment]
@carlosjgp can you reset the user key and try updating again ?
You'd need a PUT to `/api/users/{user-id}/actions/key/reset`

**Comment by carlosjgp** [comment]
@ConsM That endpoint is not documented

https://tyk.io/docs/tyk-dashboard-api/users/

Which are the expected headers and payload if any?
Can you update the documentation with those details, please?

**Comment by ConsM** [comment]
@carlosjgp i'll make sure it will get documented.
The payload should be `{"userId":"{USER-ID}"}`, if authorised you should then get a response:
`User session renewed`

**Comment by carlosjgp** [comment]
I'm not using that endpoint anymore (update user). And I've updated my Gateway and Dashboard versions to `v2.8.0` and `v1.8.0` so I can't provide more details sorry
