### ISSUE TITLE
User with the same email for the same organisation can be created

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2224]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Multiple users can be created with the same email for the same organisation

**What is the expected behavior?**
Error when trying to use the same email address to create a user using the same email as one already in use
- `400` response from the API with a descriptive message
- Error message on the UI

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create multiple users with the same email and same or different password

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
`v2.7.6`

**Comment by adelowo** [comment]
This has been fixed already and will be available in the next release, 2.8 .
