### ISSUE TITLE
Redis logs not working

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2225]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Dashboard Redis log functionality stopped working.
Looking at the code it requires non-empty "org_id" attached to every log message, which seems to broke with logger refactoring made in 2.7 release.
**What is the expected behavior?**
Should display logs.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Standard on-premise setup on 2.7
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by furkansenharputlu** [comment]
@buger This seems working for me. I tried with `2.7` and master. Both works in my local.

**Comment by a-nldisr** [comment]
@furkansenharputlu please see ticket 3347 for more info

**Comment by a-nldisr** [comment]
@furkansenharputlu Sorry, the message stays the same. No matter how long i wait: ```
No gateway logs to display, please wait a few seconds for events to populate. If events are still not showing, check `use_redis_log` is set to `true` in tyk.conf.```

**Comment by furkansenharputlu** [comment]
@a-nldisr I want to see your Network. Can you please do the following steps and take a screenshot for us?

Steps:
1. Open Dashboard in Chrome
2. Open inspect screen(`F12`)
3. In inspect screen go to `Network` tab 
4. Pick `XHR` filter
5. Refresh the page
6. Take a screenshot

The result should be like this: 
![Ekran Resmi 2019-05-10 17 35 27](https://user-images.githubusercontent.com/25665432/57535584-362a6400-734b-11e9-98f3-e5f30974e291.png)

**Comment by a-nldisr** [comment]
Please see the attached screenshot to the ticket.
I see that there is a request made to port 5000, this while we forced all traffic to use https in our dashboard and gateway configurations.

**Comment by a-nldisr** [comment]
@furkansenharputlu @buger We now have version 2.8.1 running and 1.8.1 with the same issue.

**Comment by christtyk** [comment]
Fixed in 2.9.3
