### ISSUE TITLE
`event_trigers_defunct` has typo

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#2228]
**Do you want to request a *feature* or report a *bug*?**
typo

**What is the current behavior?**
`event_trigers_defunct` has typo

**What is the expected behavior?**
`event_triggers_defunct`should also be supported and documentation should be changed. The old version should stay to maintain backward compatibility.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions

**Comment by ilijabojanovic** [comment]
@buger merge in to release-2.8 branch
