### ISSUE TITLE
Some tutorial/help issues

### ISSUE THREAD

**Issue by veger** [TykTechnologies/tyk#223]
I have 2 issues related to the tutorial for new users:
1. When I setup the Tyk (from scratch, which we do often/sometimes during development) the tutorial is shown again. This is annoying, cannot turn it off for all tutorials at once? (Luckily we can click on the x to abort/skip the current tutorial).
2. When we import our API definitions programmaticall and I directly go to 'edit API' (e.g. to fix something), the 'API tutorial' kicks in. But step 5/5 is not shown (screen is completely grayed), probably because the 'Save' button is not available.
   This results in a 'deadlock' as it is impossible to click on anything, and a refresh (F5) is required. Now one _must_ abort the tutorial in order to prevent this issue.

**Comment by mvdan** [comment]
Answer to the first, courtesy of @ConsM: https://community.tyk.io/t/is-there-any-way-to-disable-the-onboarding-popups/672/4

**Comment by mvdan** [comment]
@veger is the second issue still present on the latest version?

**Comment by veger** [comment]
No idea, we are not able to update to the to Tyk 2.x...

**Comment by mvdan** [comment]
I'm going to close this then, as we don't offer support for older versions at the moment.

Out of curiosity, what keeps you from updating?

**Comment by veger** [comment]
Time & money (for Dashboard) at our side, and we are not too happy with the product (stability, insights/logging, features)

**Comment by mvdan** [comment]
If you have any issues with 2.3.x, feel free to reach out :)
