### ISSUE TITLE
Dashboard: Meaning of "admin_secret" in conf

### ISSUE THREAD

**Issue by byrnedo** [TykTechnologies/tyk#224]
Hi, can't seem to find any documentation on what 'admin_secret' does in the dashboard conf?

**Comment by lonelycode** [comment]
Tyk Dashboard has a bootstrap API, this secret is for the bootstrap API, these call do things like: Create new organisations, create super users etc. See the Advanced API documentation for more on these endpoints.

**Comment by byrnedo** [comment]
Thanks!

**Comment by carlosjgp** [comment]
The documentation about this field is still missing on the website :(

https://tyk.io/docs/configure/tyk-dashboard-configuration-options/

Such an important field should be well documented. I've raised a [PR](https://github.com/TykTechnologies/tyk-docs/pull/706)
