### ISSUE TITLE
Should escape JWT claims containing non-alphanum characters

### ISSUE THREAD

**Issue by ryan-ju** [TykTechnologies/tyk#2242]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
If the JWT claim key has non-alpha-numeric key, it's not handled correctly.

E.g, this key `$tyk_context.jwt_claims_http://my.com/permissions` creates value `://my.com/permissions` instead of the actual value of the claim.

The reason for this is some auth providers (e.g., Auth0) does not allow user to create non-namespaced claims, and they also enforce a format on the claim key, as documented: https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims#custom-claims

**What is the expected behavior?**

Should return the actual value of the claim for non-alpha-numeric claim keys.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

The current Tyk cloud (don't know which version it is).

**Comment by joshblakeley** [comment]
Hi

Where are you calling the context variable? I just did a quick and dirty test with injecting the JWT claims into headers etc using the example you provided above and it deals with the key formatting correctly.

cheers
