### ISSUE TITLE
Imported Swagger endpoints not tracked

### ISSUE THREAD

**Issue by garyamorris** [TykTechnologies/tyk#2243]
BUG

Currently when importing an api definition using swagger json, the endpoints which have a tracking plugin attached are not tracked. 

The endpoints should appear in the Endpoint popularity page, however they do not. 

Run the tyk-pro-docker-demo. 
Goto apis
Import api using a swagger json
Call the api
Check the endpoint popularity tab 

I'm currently using the latest version of the tyk-pro-docker-demo. If I remove the endpoint definition and add the endpoint manually, the endpoint is now tracked.

**Comment by garyamorris** [comment]
I've investigated further and I think its case sensitivity, my apis are imported with capitalisation. Is this correct behaviour?

**Comment by carlosjgp** [comment]
@garyamorris I had problems in the past when the API slug/path contain capital letters using Tyk Gateway

Tyk could manage this more gracefully since [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) states that it's equivalent to the lowercase version

**Comment by letzya** [comment]
@carlosjgp please check this https://github.com/TykTechnologies/tyk/issues/284#issuecomment-239119876
We lowercase the url
