### ISSUE TITLE
Can't list hashed tokens on the Dashboard UI or REST API

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2245]
**Do you want to request a *feature* or report a *bug*?**
Bug
Undocumented configuration

**What is the current behavior?**
Error display on the UI
`Could not retrieve key detail`

Error response on the API
`{"Status":"Error","Message":"Could not retrieve keys","Meta":null}`

Logs
```
time="May  1 12:19:58" level=warning msg="Login opened from: 172.22.20.185:39062" 
time="May  1 12:20:00" level=error msg="API Request failed: {\"status\":\"error\",\"message\":\"Hashed key listing is disabled in config (enable_hashed_keys_listing)\"}\n" 
time="May  1 12:20:00" level=error msg="Key request failed" 
time="May  1 12:20:03" level=warning msg="Login opened from: 
```

**What is the expected behavior?**
Hashed tokens can be managed through UI or API

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Try to list hashed keys through the Dashboard API or UI

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard: `v1.8.0`

**Comment by buger** [comment]
Have you tried to set `enable_hashed_keys_listing` as suggested by log message?

**Comment by carlosjgp** [comment]
Yes, but still the same error.

But I might have set it on the wrong hierarchy inside the configuration file, I just set it as

```
...
    "use_sentry": false,
    "enable_master_keys": false,
    "enable_hashed_keys_listing": true,
...
```

**Comment by buger** [comment]
Note that you should enable the same option on gateway side too (same name), maybe it is the reason.

**Comment by carlosjgp** [comment]
Enabling the field in both components allowed me to use `/api/apis/{api-id}/keys` endpoint to find out the keys ids (?) which can be found through the UI but not search based on user

FYI: https://github.com/TykTechnologies/tyk/issues/2273

The UI is now showing
```
Set enable_update_key_by_hash to true in analytics.conf, to allow updates.
Set enable_delete_key_by_hash to true in analytics.conf, to allow deletion.
```
More undocumented fields. I raised another issue to address this https://github.com/TykTechnologies/tyk/issues/2272


I can't find tokens based on the user with the following error on Gateway

```
time="May 10 08:39:19" level=debug msg="Received DRL data: {tyk-gateway-bbd4fc86f-h2k89 0999f5fe-2bcc-43f2-56d1-b517c736b227 1 0 }" 
time="May 10 08:39:19" level=debug msg="[Active Nodes]: 1 [Token Bucket Value]: 100 [Current Load p/s]: 1 [Current Load]: 0.000000" 
time="May 10 08:39:20" level=debug msg="Getting exp for key: analytics-tyk-system-analytics" 
time="May 10 08:39:21" level=debug msg="[STORE] Getting WAS: 5ccc0ea3d924a500014f73c9carlos.penalver@mydomain.com" 
time="May 10 08:39:21" level=debug msg="[STORE] Getting: apikey-11b9122f" 
time="May 10 08:39:21" level=debug msg="Error trying to get value:redigo: nil returned" 
time="May 10 08:39:21" level=debug msg="Could not get session detail, key not found" err="key not found" inbound-key="****.com" 
time="May 10 08:39:21" level=debug msg="Getting exp for key: analytics-tyk-system-analytics" 
time="May 10 08:39:21" level=debug msg="Sending notification{NoticeGatewayDRLNotification {\"HostName\":\"tyk-gateway-bbd4fc86f-h2k89\",\"ID\":\"0999f5fe-2bcc-43f2-56d1-b517c736b227\",\"LoadPerSec\":1,\"Percentage\":0,\"TagHash\":\"\"} }"
```
