### ISSUE TITLE
Tyk Dashboard UI shows wrong version

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2247]
**Do you want to request a *feature* or report a *bug*?**
BUGish

**What is the current behavior?**
Dashboard version displayed on the UI is not aligned with the version running
`Dashboard (v1.7.6)`

**What is the expected behavior?**
Dashboard version displayed is the same as version running

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
run Tyk Dashboard as described on 
`tyk-pro-docker-demo` repo

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk dashboard `v1.8.0`

**Comment by letzya** [comment]
Your docker might be caching the container even though you have seen it getting downloaded so important to do "rm" (to removes stopped service containers) as follows: 
> docker-compose stop 
> docker-compose rm -f 
> docker-compose pull
> docker-compose up -d

Could you please try and let me know?

**Comment by carlosjgp** [comment]
Fixed since a new docker image has been released
https://hub.docker.com/r/tykio/tyk-dashboard/tags `v1.8.0.1`

**Comment by carlosjgp** [comment]
The `docker-compose` demo is now broken by the way...
https://github.com/TykTechnologies/tyk-pro-docker-demo/issues/20
