### ISSUE TITLE
Stripping listen paths does not work if listen path contains regexp

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2249]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If I define listen path like `/{_:.*}/listen`, it works as expected, except stripping listen paths. 
At the moment it can strip only "static" values, and not handle regexps. 
**What is the expected behavior?**
It should detect if regexp is defined, and strip the path using regexp.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All till 2.8

**Comment by oluwaseyeayinla** [comment]
This was fixed in Tyk 4.0.3
