### ISSUE TITLE
Create MongoDB index automatically

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2253]
**Do you want to request a *feature* or report a *bug*?**
Feature

Reduce management and setup complexity

Mongo Go client allows it
https://github.com/mongodb/mongo-go-driver/blob/a082699dc8a65f4ea6485b7a7765554ea6ff83db/mongo/options/indexoptions.go#L19

**What is the current behavior?**
Manual interaction with MongoDB to create an Index
https://tyk.io/docs/analyse/capping-analytics-data-storage/#step-1-add-the-index-to-mongodb

**What is the expected behavior?**
Tyk to manage its own DB on Mongo

**Comment by letzya** [comment]
Hi,
I think we need to discuss this feature request a bit more. As you saw in the docs there's another option for capping, based on size and we want to give users the flexibility to choose since you shouldn't set both (you'll get an error in mongo).
Tyk is responsible to actually create the field _expireAt_ and calculates its value.
You can configure the time that Tyk calculated for this field as explained [here](https://tyk.io/docs/analyse/capping-analytics-data-storage/#step-2-create-an-organisation-quota)
What do you think? do you have another suggestion?

**Comment by carlosjgp** [comment]
As a Tyk user, I'll like not to have to interact with MongoDB at that level.

I suggest a statistic curator/downsampler component in charge of managing the `tyk_analytics` MongoDB collection that would be able to configure MongoDB and change seamlessly from time capping to size capping.

On the other hand, Tyk pump already can extract those metrics to Prometheus or InfluxDB which are quite popular metric management systems which implement those features already.

Configuring those pumps to "clean" after themselves they have pushed the metrics into these other systems could be another option

**Comment by asoorm** [comment]
@carlosjgp By default, we enable indexes on analytics collections: https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L210-L249

A decision was made a while back to not make potentially destructive / dangerous changes to existing MongoDB collections. By capping your collections, this means that Tyk is potentially deleting your data.

As such, for a fresh installation, Tyk-Pump automatically creates capped collections with sensible defaults, but will never actively delete your analytics data. You can also configure this inside the pump.conf

https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L124-L185

https://tyk.io/docs/deploy-tyk-premise-production/#capping-analytics-data

Typically, Prometheus / Influx / Elastic search is used for longer term storage, and smaller capped collections are used within Tyk/Mongo for fast viewing & debugging within the dashboard.

**Comment by letzya** [comment]
@carlosjgp are you okay with Ahmet's response?
