### ISSUE TITLE
Update Gateway `analytics_config` documentation and Architecture diagram

### ISSUE THREAD

**Issue by carlosjgp** [TykTechnologies/tyk#2254]
**Do you want to request a *feature* or report a *bug*?**
bug
Documentation

**What is the current behavior?**
Incomplete

**What is the expected behavior?**
Accurate

Documentation
https://tyk.io/docs/configure/tyk-gateway-configuration-options/#a-name-enable-analytics-a-enable-analytics

Architecture diagram
https://tyk.io/docs/concepts/tyk-components/gateway/

Tyk Gateway configuration has a section which looks like this
```
"analytics_config": {
    "type": "mongo",
    "csv_dir": "/tmp",
    "mongo_url": "mongodb://mongodb-0:27017,mongodb-1:27017,mongodb-2:27017/tyk_analytics?replicaSet=rs0",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
},
```

From...
https://github.com/TykTechnologies/tyk-pro-docker-demo/blob/master/confs/tyk.conf#L39-L51
https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-pro/configs/tyk_mgmt.conf#L27-L35

**Comment by letzya** [comment]
This should actually have been opened on our tyk-docs repo.

Tyk gw does not talk to mongo at all. It gets all the configurations from the dashboard (making an api call to the dashboard) .
This is a legacy configuration that slipped in. Thank you for raising that. We will fix the links you have shared with us.
