### ISSUE TITLE
Error creating API Key

### ISSUE THREAD

**Issue by previ** [TykTechnologies/tyk#226]
When creating a new API Key from the Dasjboard, with the following parameters:
- Enforce HMAC request signing UNCHECKED
- Basic Authentication UNCHECKED
- JSON Web Token UNCHECKED
- Policy: <policy defined>
- Rate limit 1000/second
- Expires in 1hr
- Max Quota: -1

I get the following error message in the Dashboard:
> Failed to save new session object to Tyk: Failed to create key: Post http://gateway:8080/tyk/keys/create: dial tcp: lookup gateway on 127.0.0.11:53: server misbehaving

**Comment by lonelycode** [comment]
I meant the QuickStart repo ;-)

**Comment by previ** [comment]
Oops, sorry! :-)
