### ISSUE TITLE
`X-RateLimit-Remaining` header does not work when using rate limits per API

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2261]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`X-RateLimit-Remaining` should show rate limit left for the current API. At the moment, when separate rate limits used, it does not work. 
**What is the expected behavior?**
When accessing individual APIs it should show rate limit only for specific API
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by ilijabojanovic** [comment]
@buger please merge in to release-2.8

**Comment by buger** [comment]
done ^
