### ISSUE TITLE
Log browser not displaying any data when "detailed logging" is enabled and traffic is high

### ISSUE THREAD

**Issue by ViolaMarku** [TykTechnologies/tyk#2265]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After enabling detailed logging (https://tyk.io/docs/analyse/log-browser/#on-premises-installations-option) for Log browser, the Log browser displays no data/is empty. It is suspected the size of the data set is too large and it is causing the bug. 
**What is the expected behavior?**
The log browser should be displaying all traffic data. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Enable detailed logging and test with large data set.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by letzya** [comment]
Setup mistake. closing
