### ISSUE TITLE
Dashboard should be able to provide a list of all my current keys

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2279]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
- ~~Key listing on the gateway is possible only if the keys are not hashed.~~ Possible directly with the gateway by setting `"enable_hashed_keys_listing": true,` in tyk.conf.
- Even if you enabled key listing on both dashboard and gateway we list keys under apis, users need to fetch all the apis and then call /keys per api. 
- We provide keys listing in the analytics. As such, admins need to wait until the keys are being used before they can see the keys on the system. 

**What is the expected behavior?**
We should add the ability to see the keys as soon as they get created since we have this info already. It will be very powerful from the dashboard users perspective.
Since we have this info why not create an appropriate endpoint?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by letzya** [comment]
A workaround to this could be using Tyk's events. https://tyk.io/docs/tyk-developer-portal/portal-events-notifications/#extra-dashboard-and-portal-events

**Comment by buger** [comment]
We need to add `enable_hashed_keys_listing` to the dashboard. And in current interaction, we should clearly say, that it will not work in a multi-tenant environment (since we can't really scan each key for the matching orgID)

**Comment by ilijabojanovic** [comment]
@buger @sredxny 

On latest release-1.10 branch

When we enable key list, we where able to see list of tokens on system, but if we use pagination, pagination does not work and also we have console errors 

Video:
![pagination](https://user-images.githubusercontent.com/8557292/79255197-2c2bb200-7e86-11ea-8179-39dd3f8b0fd9.gif)


Errors:
```
[Apr 14 19:26:58] ERROR HttpJsonDataSource.Resolve.client.Do error=Get http://www.tyk-test.com:3000/api/portal/policies/search?policy_ids={{ flattenIDs .object.apply_policies }}: dial tcp: lookup www.tyk-test.com: no such host
[Apr 14 19:26:58] ERROR HttpJsonDataSource.Resolve.client.Do error=Get http://www.tyk-test.com:3000/api/portal/policies/search?policy_ids={{ flattenIDs .object.apply_policies }}: dial tcp: lookup www.tyk-test.com: no such host
[Apr 14 19:26:58] ERROR HttpJsonDataSource.Resolve.client.Do error=Get http://www.tyk-test.com:3000/api/keys/detailed/?p=1&q=: dial tcp: lookup www.tyk-test.com: no such host
[Apr 14 19:26:58] ERROR HttpJsonDataSource.Resolve.client.Do error=Get http://www.tyk-test.com:3000/api/keys/detailed/?p=1&q=: dial tcp: lookup www.tyk-test.com: no such host
```

**Comment by lghiur** [comment]
@jay-deshmukh can u please check the above

**Comment by ilijabojanovic** [comment]
Verified. Other issues will be handled in separate tasks
