### ISSUE TITLE
Portal: Multiple ajax calls to retrieve Swagger json in docs page.

### ISSUE THREAD

**Issue by byrnedo** [TykTechnologies/tyk#228]
When I go to my developer portal documentation for an api, I'm seeing 36 calls to retrieve the swagger json from `public/apis/<id>/documentation/raw`.

They all return 200 and the correct json. Weird.

**Comment by lonelycode** [comment]
How odd, have you modified the template in any way?

**Comment by byrnedo** [comment]
No, not manually. I see that in the js script on the page that it has the url as so: 
```
var url = window.location.search.match(/url=([^&]+)/);
		if (url && url.length > 1) {
			url = decodeURIComponent(url[1]);
		} else {
			
			url = "\/portal\/apis/56fa50d0e3db830009000001/documentation/raw";
			
			
		}
```
It's hardly the backslashes?

**Comment by lonelycode** [comment]
I doubt it... SwaggerUI does the downloading, so it's a little out of our hands. Looking at some other docs it does make a bunch of requests. Might need to update the dep (eek).

**Comment by lonelycode** [comment]
Either that or make sure the resource gets cached.

**Comment by byrnedo** [comment]
I only noticed it once I had a slow connection to my server, usually the docs pagers are a tad slow but usable, this time it took quite a while. I ran json lint on the payload and it was fine too.

**Comment by lonelycode** [comment]
Ok, will take a look at it - not ideal.
