### ISSUE TITLE
ReturnOverrides does not work for response code > 400

### ISSUE THREAD

**Issue by ryan-ju** [TykTechnologies/tyk#2282]
**Do you want to request a *feature* or report a *bug*?**
Looks like a bug to me, don't know if it's designed this way

**What is the current behavior?**
If I use `ReturnOverrides` with `status` > 400 (let's say 401), then the `headers` and `error` overrides are ignored.

**What is the expected behavior?**
`headers` and `error` in `ReturnOverrides` should be used no matter what the response code is.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This is the code causing the issue:
https://github.com/matiasinsaurralde/tyk/blob/master/coprocess.go#L293

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by matiasinsaurralde** [comment]
The comment about headers is right, we need to enhance that.
Could you share a snippet of the middleware code that's using `return_overrides`?

**Comment by matiasinsaurralde** [comment]
Have issued a fix (#2283)

The following snippet now sends the header:
```python
from tyk.decorators import *
from gateway import TykGateway as tyk

@Hook
def MyHook(request, session, spec):
  request.object.return_overrides.response_code = 401
  request.object.return_overrides.response_error = "test"
  request.object.return_overrides.headers["test-header"] = "test-value"
  return request, session
```

**Comment by ryan-ju** [comment]
@matiasinsaurralde thanks for the quick response and fix.  

I realised that I can use error templates to customise the body, so this will solve the issued I have.

**Comment by paulmangam** [comment]
Is request.object.return_overrides.headers working for setting headers for upstream request? I set it in the block marked for "auth_check" and it does not set the header. 

---------------
Manifest.json:
---------------
{
  "file_list": [
    "external-token-check.py"
  ],
  "custom_middleware": {
    "auth_check": {
      "name": "ExternalTokenValidatorMiddleware"
    },
    "driver": "python"
  },
  "checksum": "",
  "signature": ""
}

---------------------------
external-token-check.py:
---------------------------
from tyk.decorators import *
from gateway import TykGateway as tyk

import json
import requests

@Hook
def ExternalTokenValidatorMiddleware(request, session, metadata, spec):

    token = request.get_header('Authorization')

    if token is None:
        return request, session

    targetUrl = 'https://test.salesforce.com/services/oauth2/token?grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion='+token

    try:
        r = requests.post(targetUrl, headers={'Authorization': token})

        if r.status_code > 299:
            tyk.log("The authentication failed","info")
            request.object.return_overrides.response_code = 401
            request.object.return_overrides.response_error = 'Not authorized by Auth Server'
            return request, session, metadata
    except Exception as e:
        tyk.log("An error occured:"+e,"info")
        return request, session, metadata

    data = r.text
    data = json.loads(data)
    access_token = data["access_token"]
    tyk.log("The authentication was successful! access_token: "+access_token,"info")
    session.rate = 1000.0
    session.per = 1.0
    metadata["token"] = "47a0c79c427728b3df4af62b9228c8ae"

    request.object.return_overrides.headers["Authorization"] = "Bearer "+access_token
    #session.headers.update({'Authorization': 'Bearer '+access_token'})

    return request, session, metadata

**Comment by matiasinsaurralde** [comment]
@paulmangam `ReturnOverrides` won't modify the upstream request object, it's intended for scenarios where you plan to avoid sending the request to upstream and instead reply to the client directly, mostly used for handling plugin errors.
To view/attach a header to the upstream request you may use `get_header`/`set_header` (like in [this sample](https://tyk.io/docs/plugins/rich-plugins/python/custom-auth-python-tutorial/#contents-of-middlewarepy)).
For more advanced fields check our [data structures page](https://tyk.io/docs/plugins/rich-plugins/rich-plugins-data-structures/#minirequestobject-coprocess_mini_request_objectproto), in the context of the Python hook, `request.object` has the `MiniRequestObject` data structure. Note that all the field are autogenerated by the Protocol Buffers tool.

**Comment by paulmangam** [comment]
@matiasinsaurralde  thanks for the quick reply!
request.get_header() works well! But request.set_header() gives out errors, object has no attribute: 

level=error msg="Hook 'ExternalTokenValidatorMiddleware' returned an error: 'TykCoProcessRequest' object has no attribute 'set_header'" prefix=python

 level=error msg="Hook 'ExternalTokenValidatorMiddleware' returned an error: 'TykCoProcessRequest' object has no attribute 'set_headers'" prefix=python

**Comment by matiasinsaurralde** [comment]
@paulmangam Sorry, it's `add_header`!

**Comment by paulmangam** [comment]
Works like a charm! Thank you!
