### ISSUE TITLE
Creating Catalogue entry via TYK Dashboard API

### ISSUE THREAD

**Issue by jeryini** [TykTechnologies/tyk#2285]
**Do you want to request a *feature* or report a *bug*?**
Probably a feature, though it might even be a bug.

**What is the current behavior?**
According to [official docs for Tyk Dashboard API](https://tyk.io/docs/tyk-dashboard-api/), programmatically creating resources can be done using api endpoint, e.g. `/api/portal/policies/`. I've successfully created a Policy resource like that.

**What is the expected behavior?**
I couldn't find in the documentation endpoint for creating Catalogue entry. Nevertheless the following call successfully returns existing catalogues:
```curl --header "Authorization: ---" /api/portal/catalogue/ 2>&1```

Therefore I expect that POST request to that endpoint would create a Catalogue resource, but that doesn't happen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I've tried with the following data:
```
{
            "name": "Developer tier",
            "short_description": "Testing developer tier",
            "long_description": "Testing developer tier using policies..",
            "show": true,
            "version":"v2",
            "config":{
                "require_key_approval": true,
                "redirect_on_key_request": true,
                "redirect_to": "/portal/payments/",
                "override": true
            }
        }
```
I even get back status OK and 200 code in the logs, but the actual resource does not get created.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Docker image: `tykio/tyk-dashboard:latest`
Tyk dashboard version: `Dashboard (v1.7.6)`

**Comment by jeryini** [comment]
Ok, I did a little bit of investigation on actual dashboard with inspection tool what is called when you create Catalogue entry via GUI. So they actually do a PUT request, I've managed to create it programmatically like that:
```
curl \
    -X PUT \
    --silent \
    --header "Authorization: ---" \
    --header "Content-Type:application/json" \
    --data '
        {
            "id": "---",
            "org_id": "---",
            "apis": [{
                "name": "Developer tier",
                "policy_id": "5cd8f356e92b8200015f09fa",
                "short_description": "Testing developer tier",
                "long_description": "Testing developer tier using policies.",
                "show": true,
                "version":"v2",
                "config":{
                    "require_key_approval": true,
                    "redirect_on_key_request": true,
                    "redirect_to": "portal/payments/",
                    "override": true
                }
            }]
        }' \
    api/portal/catalogue/ 2>&1
```

**Comment by s-schumann** [comment]
Has this issue been solved? The documentation refers (still) to a POST, but I still see the same behavior.
