### ISSUE TITLE
Revoking developer key doesn't delete cache

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#2293]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a user key is revoked, it continues to work until cache expires

**What is the expected behavior?**
Revoking operation should flush cache.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Set `"disable_cached_session_state": false` in `tyk.conf`
2. Create a developer key
3. Make a request with that key
4. Revoke the key
5. Make another request in 10 secs.(Should fail but success)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master

**Comment by ilijabojanovic** [comment]
Verified
