### ISSUE TITLE
middleware: automatic retry on upstream failure

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2296]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

upstream errors are transparently returned to the client. This leaves the client to manually retry if necessary.

**What is the expected behavior?**

For temporary failures - e.g. network issues, the gateway could retry automatically on behalf of the client if the endpoint has been configured to do so.

Example endpoint configuration
```
{
  "retry_on": "5\d{2}",
  "max_retries": 2
}
```

`retry_on` - a regexp specifying that if the response status code is 5xx then retry will be initiated
`max_attempts` - stops Tyk from hammering the upstream.

Plugin could be usable in conjunction with https://tyk.io/docs/ensure-high-availability/circuit-breakers/ and https://tyk.io/docs/ensure-high-availability/enforced-timeouts/

**Comment by buger** [comment]
We already have the same functionality call "throttling", added as part of 2.8
It automatically retries the request in case of rate limit error. 

I see this feature as an extension of throttling.

Also, note that at the moment throttling configured on policy/key level, so can be enabled on per-user level.
