### ISSUE TITLE
Cannot start tyk_quickstart (docker)

### ISSUE THREAD

**Issue by magnusja** [TykTechnologies/tyk#231]
Hey guys I am trying to get the tyk_quickstart (docker) (https://tyk.io/docs/tyk-api-gateway-v-2-0/installation-options-setup/docker/) working. When I am running docker-compose up I am constantly getting the following error:

```
Status: Downloaded newer image for tykio/tyk-dashboard:latest
Creating tykquickstart_tyk_dashboard_1
ERROR: Cannot start container 2145fb3daee9da3f911eeab017194e5e875d71220d7d6049aa39616cc6fd2714: [9] System error: not a directory
```

**Comment by lonelycode** [comment]
What version of docker are you running?

**Comment by mjdev** [comment]
Ms-MBP-2:ansible mep$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

**Comment by lonelycode** [comment]
How odd, That's the version we've tested against, although we're running in Kitematic, are you using native OSX Docker (Beta)?

**Comment by mjdev** [comment]
I am using boot2docker with virtualbox via docker toolbox / quickstart terminal

````Ms-MBP-2:ansible mep$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: XRLZ:5GFM:RFDH:P5Q2:ISZN:JQ5T:ZB6A:FVOK:A62Y:O56C:RV3Y:AOHG
Debug mode (server): true
 File Descriptors: 28
 Goroutines: 42
 System Time: 2016-04-04T15:40:24.183203551Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mjdev
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by lonelycode** [comment]
The container doesn't do anything unique, "Not a directory" seems to indicate one of the mounts is failing, can you ls -al the ty_quickstart folder?

**Comment by mjdev** [comment]
Sure:

```
Ms-MBP-2:infrastructure mep$ cd tyk_quickstart/
total 32
drwxr-xr-x  13 mep  staff   442B Apr  4 15:56 .git/
-rw-r--r--   1 mep  staff   2.0K Apr  4 15:56 README.md
-rw-r--r--   1 mep  staff   931B Apr  4 15:56 docker-compose-pre-1.9.yml
-rw-r--r--   1 mep  staff   1.1K Apr  4 16:45 docker-compose.yml
-rw-r--r--   1 mep  staff   792B Apr  4 15:56 pump.conf
-rwxr-xr-x   1 mep  staff   6.7K Apr  4 15:56 setup.sh
-rw-r--r--   1 mep  staff   1.5K Apr  4 15:56 tyk.conf
-rw-r--r--   1 mep  staff   2.5K Apr  4 16:37 tyk_analytics.conf
```

I also tried removing the volume mount for the dashboard in the compose file with no luck.

**Comment by lonelycode** [comment]
I think this is similar to your problem:

http://www.davidgarcia.es/solved-cannot-start-a-container-system-error-not-a-directory-docker-compose/

**Comment by mjdev** [comment]
@lonelycode Had a look at it, and my VM has access to /Users.

**Comment by lonelycode** [comment]
I see, I'm a bit stumped here, because it's definetely a permissions issue in the VM or file system - we've tested this in Kitematic and native linux docker server and it's working just fine.

**Comment by JosephEarl** [comment]
What `docker-compose` version are you running @mjdev ?

**Comment by matiasinsaurralde** [comment]
Hi, I'm trying to run Tyk 2 with docker/tyk_quickstart, I've replaced the license & I'm getting this error:

```
# docker-compose up -d
Unsupported config option for services service: 'tyk_mongo'
```
Any clue? I thought Mongo wasn't used anymore

Thanks!

**Comment by lonelycode** [comment]
@matiasinsaurralde What docker version are you running?

**Comment by matiasinsaurralde** [comment]
@lonelycode 
```
docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```
