### ISSUE TITLE
Can't create oAuth API which has access to multiple APIs

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2314]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
In 2.7 it was allowed
**What is the expected behavior?**
Make it work
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a policy which has multiple APIs, and try to create a client, you will get error.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by ilijabojanovic** [comment]
Verified
