### ISSUE TITLE
How can I share API Definitions between Tyk nodes

### ISSUE THREAD

**Issue by creamer** [TykTechnologies/tyk#232]
in multiple Tyk nodes
How can I share API Definitions between Tyk nodes?
I think.. I should store API Definitions to Redis or Mongo DB.

Sorry, my english is so bad :(

**Comment by lonelycode** [comment]
Use Tyk Pro if you want to use a DB based approach (dashboard) or you'll need to sync the apps and policies folders between your instances of you are going file based.

**Comment by creamer** [comment]
Thank you. :+1:
