### ISSUE TITLE
Oauth policy does not update access rights for token

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2320]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When we update policy which contains oauth apis with new api definition, those changes are not propagated to token
**What is the expected behavior?**
When we update policy access rights, token should have access to those api's
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create api1 with oauth protection 
2. Create policy and attach api1
3. Expose that policy on developer portal and create oauth client
4. Generate oauth token
5. Trigger call to /api1
6. Create api2 with oauth protection and attach that api on same policy which has /api1
7. Trigger call to /api2

Actual:
Same token will not have access to /api2

Expected:
Token should have access to /api2

Here is log from gateway:

```
[May 29 18:32:21]  INFO Getting client ID:73a84269f47f4b24bb4dfa52fc428f15
[May 29 18:32:21] ERROR Failure retreiving client ID key "oauth-clientid.73a84269f47f4b24bb4dfa52fc428f15": key not found
[May 29 18:32:21]  WARN Attempted access for deleted OAuth client. api_id=ed7e0f5e19f344bb6cdd49eb6c6ae3c1 api_name=api-outh5 key=eyJvcmciOiI1Y2E0OTBkYTk2MzNkNzA1ZTk1ODZlNWEiLCJpZCI6IjczNjdhNGE3OWI3YjRlMjM5MThkNjI2ZTZkNDkwMWViIiwiaCI6Im11cm11cjY0In0= mw=Oauth2KeyExists oauthClientID=73a84269f47f4b24bb4dfa52fc428f15 org_id=5ca490da9633d705e9586e5a origin=127.0.0.1 path=/api-outh5/get
```
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master/Release-2.8 
Note: This issue is not visible on release-2.7

**Comment by buger** [comment]
Fixed by https://github.com/TykTechnologies/tyk-analytics/pull/1338
