### ISSUE TITLE
open source gateway plateform selection comparison

### ISSUE THREAD

**Issue by cmdares** [TykTechnologies/tyk#2325]
Open Source Gateway selection is currently under way.
Preliminary selection with tyk.io and  gravitee-io.
How about comparison of two platforms In order to more accurately analyze the time when their own platform building methods.
My backend app api use springcloud with swagger.
Assessment point:
1.Performance
2.Custom plug-in
4.Security policy
5.Monitor
6.Convenience
7. support both rest api and webpage proxy

**Comment by asoorm** [comment]
@cmdares I dont know about gravitee. If you do some evaluation between the two - I would be interested in seeing your results.

I can however speak for Tyk.

- Performance
Tyk is very fast. https://tyk.io/blog/performance-tuning-your-tyk-api-gateway/

6400 requests per second, 4.2ms 95th %ile latency, 60% consumed CPU, 2-vCPU DO Droplet

- Custom Plugin
Tyk can be customised with Python, Lua, Javascript, or any language which supports gRPC. But Tyk ships with most of the plugins you will need - so very few of our customers ever need to write plugins. They typically use Tyk out-of-the-box for cross cutting concerns, and only typically use custom plugins for business-logic workarounds / use-cases.

- Security policy
Bearer Token, Basic Auth, HMAC, JWT, OAuth2, OIDC, Client Certificates, Custom Auth via plugin

- Monitor
Native integrations with DataDog, Splunk, ElasticSearch, Influx, StatsD, NewRelic, MongoDB and others

- Convenience
Tyk is very easy to work with. https://www.youtube.com/watch?v=W_QSVvDeLaw

- Both rest api and webpage proxy
Tyk should be able to do this.
