### ISSUE TITLE
Reject request in middleware

### ISSUE THREAD

**Issue by dhjf** [TykTechnologies/tyk#233]
I cannot find any documentation/examples of how to this, so I'll ask here:
In a middleware script, is it possible to send back a response to the client (e.g. HTTP 401), such that the request never reaches the backend service? An example would be a validation script.

**Comment by lonelycode** [comment]
Yup, in the returned object in the middleware JS, you can add a ReturnOverrides object:

https://github.com/TykTechnologies/tyk/blob/master/plugins.go#L21

that contains a response code, if this response code is non-0, the middleware will throw an error which then breaks the chain and stops the request reaching the back end:

https://github.com/TykTechnologies/tyk/blob/master/plugins.go#L194

**Comment by dhjf** [comment]
Alright - I will try to make that work. Thanks!

**Comment by dhjf** [comment]
I had to upgrade to v2.0, but now it works like a charm :+1:
