### ISSUE TITLE
Fix whitelist plugin to ignore case of url

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2330]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If you whitelist "GetUser" path, whitelist plugin will accept only lowercase user requests "getuser". 
**What is the expected behavior?**
Expected behavior: If "/getuser" whitelisted, all of the following URLs should work:
"/getUser", "/GetUser", "/getuser", and so on.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by letzya** [comment]
@buger Does it makes sense to add checkbox for ignoring case distinction option?

**Comment by furkansenharputlu** [comment]
@buger HTTP URLs are case-sensitive for the path. So I think expected behavior should be exact match between whitelisted endpoint and requested endpoint such as: `GetUser`<->`GetUser` and `getuser` <-> `getuser`. See: https://stackoverflow.com/a/21001644/5183576

Wdyt ?

**Comment by ilijabojanovic** [comment]
@buger @furkansenharputlu 

On latest master. Example cases from task working, but only if we have only one endpoint. If we have two or more endpoints with similar name, this fix doesn't work.

This is example:
![Screen Shot 2019-06-26 at 12 21 04 PM](https://user-images.githubusercontent.com/8557292/60172496-140e7780-980d-11e9-85e5-c3a0d876b777.png)


In this case white list only working for `/GetUser` and `/GetOrg` others like `/getuser`, `/getorg`, `/Getuser` ... will not work

**Comment by furkansenharputlu** [comment]
After the fix, whitelist, blacklist match works as case-sensitive. Also, there is a ticket about this. We say it will be case-insensitive in documentation but it doesn't work for the current released versions. If we release my fix and change the doc as case-sensitive, everything will be fine I think. See the ticket: https://support.tyk.io/a/tickets/4023

**Comment by furkansenharputlu** [comment]
@buger @ilijabojanovic 
https://github.com/TykTechnologies/tyk-docs/commit/40b15d1c16b6153e7c6e73817724672f68db9ad4

The documentation is updated so I think the issue is resolved.

**Comment by furkansenharputlu** [comment]
Added case ignoring option with the PR: https://github.com/TykTechnologies/tyk/pull/2668
It need FE job as well. FE issue: https://github.com/TykTechnologies/tyk-analytics-ui/issues/1573

**Comment by maciejwojciechowski** [comment]
verified
