### ISSUE TITLE
r.db.DoPipeline undefined

### ISSUE THREAD

**Issue by ivaningrooves** [TykTechnologies/tyk#234]
Building a fresh clone of master gives me the following error:

    # github.com/TykTechnologies/tyk
    ./redis_cluster_handler.go:702: r.db.DoPipeline undefined (type *rediscluster.RedisCluster has no field or method DoPipeline)
    ./redis_cluster_handler.go:702: not enough arguments in call to redis.Values

To reproduce:
 1. Remove `$GOPATH/src/github.com/TykTechnologies/tyk`
 2. Run `go get github.com/TykTechnologies/tyk`

I must be missing something somewhere..

**Comment by lonelycode** [comment]
You will need to update the redigocluster dependency, we maintain our own fork.

I think 

go get -u github.com/lonelycode/redigocluster 

should do it.

**Comment by ivaningrooves** [comment]
Thank you, this did the trick:

    go get -u github.com/lonelycode/redigocluster/rediscluster

**Comment by lonelycode** [comment]
Ah yes, was doing it from memory...
