### ISSUE TITLE
Swagger documentation disapears on catalogue edit

### ISSUE THREAD

**Issue by zvyn** [TykTechnologies/tyk#2348]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

The swagger documentetion is empty after I edit a catalogue entry using https://admin.cloud.tyk.io/#/portal/catalogue. (Edit: the error message is  "No operations defined in spec!" in the developer portal, and /raw is empty.)

**What is the expected behavior?**

The swagger documentation remains unchanged unless I explicitly delete (and/or re-upload) it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create entry in API catalogue via https://admin.cloud.tyk.io/#/portal/catalogue
2. Upload swagger documentation, and update (everything works as expected so far, i.e. I can browse the documentation on the developer portal)
3. Go to https://admin.cloud.tyk.io/#/portal/catalogue and edit the previously created entry (e.g. change the short description)
4. Click Update in the upper right corner
5. Try to access the documentation

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

I am using the cloud install on https://admin.cloud.tyk.io. I recently started testing Tyk so I do not know whether this is a new issue or not.

**Comment by asoorm** [comment]
Confirmed issue

**Comment by zvyn** [comment]
This issue still exists and it renders the whole functionality for adding documentation useless.

**Comment by letzya** [comment]
Works for me. maybe we forgot to update this issue? @lghiur ?

**Comment by letzya** [comment]
Can't find the fix but no longer an issue
