### ISSUE TITLE
Feature Request - Enable Updating Redirect URI of OAuth Client

### ISSUE THREAD

**Issue by nazarhussain** [TykTechnologies/tyk#235]
Hello, 

I need to ask a feature request to enable Updating Redirect URI on OAuth Clients. Its a required feature in a production and real environment.  

Popular services like facebook and google allow us to update redirect URIs. Google also allow to add multiple redirect URIs. 

That would be a good enhancement in Tyk.

**Comment by lonelycode** [comment]
Noted, will add it to roadmap - part of our drive in the next version is better OAuth
