### ISSUE TITLE
Nested map fields in a struct of a config file cannot be mapped to environment variables

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2352]
**Do you want to request a *feature* or report a *bug*?**
bug/feature

**What is the current behavior?**
For instance, currently, email_backend.settings cannot be mapped to an env var and it's a feature requested by a few clients.
Has an impact on docker users etc
We need to update the docs as well

    "email_backend": {
        "enable_email_notifications": true,
        "code": "",
        "settings": {
            "SMTPAddress": "smtp.gmail.com:587",
            "SMTPPassword": "tmarankpwrkserny",
            "SMTPUsername": "yaara@tyk.io"
        },
        "default_from_email": "yaara-noreply@tyk.io",
        "default_from_name": "Tyk Dashboard Administrator",
        "dashboard_hostname": "www.tyk-dashboard.com"
    },
**What is the expected behavior?**
To be able to map any type of setting from xyz.conf in tyk to an env var

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just try to set it.

Tried TYK_DB_EMAILBACKEND_SETTINGS_CLIENTKEY and TYK_DB_EMAILBACKEND_SETTINGS="..." and TYK_DB_EMAILBACKEND_SETTINGS.SMTPADDRESS
None have worked.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8.1

**Comment by gernest** [comment]
@letzya maps should be defined in this format 
```
TYK_DB_EMAILBACKEND_SETTINGS="SMTPUsername:XXX,SMTPPassword:XXX,SMTPAddress:email-smtp.eu-west-1.amazonaws.com,SMTPPort:587"
```

see https://github.com/TykTechnologies/tyk-analytics/pull/1331 for clarification about special characters in map env var definition.

**Comment by hinorashi** [comment]
> @letzya maps should be defined in this format
> 
> ```
> TYK_DB_EMAILBACKEND_SETTINGS="SMTPUsername:XXX,SMTPPassword:XXX,SMTPAddress:email-smtp.eu-west-1.amazonaws.com,SMTPPort:587"
> ```
> 
> see [TykTechnologies/tyk-analytics#1331](https://github.com/TykTechnologies/tyk-analytics/pull/1331) for clarification about special characters in map env var definition.

this is not working with v3.0.4, it yelled out that `SMTPAddress` lacks of port address, due to `SMTPPort` is not recognized.
