### ISSUE TITLE
404 Error from the gateway is not parsed correctly on the dashboared 

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2353]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If you set up a control port different to the listen port and you call to the gateway on one of it's api endpoints you get body _404 page not found_ with _Content-Type →text/plain; charset=utf-8_
The problem is that the code is trying to unmarshal it and we end up with an unclear json error.

**What is the expected behavior?**
Parse the response correctly and/or return json as the response (with there's an accept header) so the error message is more accurate and clear to the users.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Define the control port different to the listen port
2. Run any endpoint directly against the gateway to see it's not working: _curl -X GET http://www.tyk-gateway.com:**8080**/tyk/keys  -H 'x-tyk-authorization: fdggffhfsfsr'_ 
3. Run the same via the dashboard and you will get: 

> Failed to save new session object to Tyk: Failed to unmarshal error: invalid character 'p' after top-level value

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
1.8.1

**Comment by SamTheisens** [comment]
What would be helpful I think, is if there were something like a health overview in the portal. It could verify some essential functionality like: are the API endpoints reachable, are the control endpoints reachable, is redis up and running, etc.
This would make it immediately obvious if something is misconfigured or not running as it should.
