### ISSUE TITLE
Calling admin/users/ returns Not Found 

### ISSUE THREAD

**Issue by madsj** [TykTechnologies/tyk#236]
I have a problem calling

GET /admin/users/ HTTP/1.1
Host: localhost:3000
admin-auth: 12345

If I call using curl like so
curl --header "admin-auth: 12345" http://192.168.99.100:3000/admin/users/

I am getting Not found in return. I am able creating a new user by posting to /admin/users/. But I would like to list all users created. So my admin-auth are set correctly to 12345. Can you help me clarify what I am doing wrong?

**Comment by lonelycode** [comment]
There is no list users endpoint AFAIK for the admin API, you need to use the standard Dashboard API.

**Comment by madsj** [comment]
Thanks for the fast reply. I can also see that you also have updated the api documentation.

So just it clarify are there any possibilities for admin-auth to list users per organisation?

I would like to create a script that are able to find a specific user by his name and then afterwards use this users access_key in the authorization header.

**Comment by lonelycode** [comment]
Ok, so there's three levels at play:

- Admin API: Bootstrap an Organisation / User that belongs to that Org OR create an unbounded user
- Dashboard API (unbounded user) - if a user is created in the admin API that has no OrgID attached to them, they have read access to everything across orgs, so if you use an unbounded user auth token with the dashboard API, you can list all users
- Bounded user - Works within the bounds of an organisation

So, in this case, lets assume you have a multi-tenant (multiple orgs) install:

1. Use Admin API to create a **temporary** unbounded user (no org ID in user record)
2. Use unbounded user key to list users - find the one you are looking for
3. Grab that users access key and use that to perform operations within their org
4. Remove the unbounded user with the Admin API

You basically de-escalate

**Comment by madsj** [comment]
I will have a try. Thanks for the fast reply
