### ISSUE TITLE
Tyk sends the x-forwarded headers (x-forwarded-host, x-forwarded-prefix and x-forwarded-proto) to the upstream service

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2363]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the expected behavior?**

Tyk to send x-forwarded headers to upstream service

**Comment by FAntonescu** [comment]
It would be nice to have a flag in the API specification enabling the forwarding of the mentioned headers.
