### ISSUE TITLE
Issue in analytics for requests which were canceled by clients or had internal issues like DNS failures

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2365]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If we do a call to Auth protected API, and during this call request fails with either DNS or context canceled error, analytics record for such request will not contain API key details.
**What is the expected behavior?**
It should log API key
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.7

**Comment by lonelycode** [comment]
Not a regression, not a security issue, not causing a fire - doesn't belong in a patch.
