### ISSUE TITLE
If response generated by Tyk via plugin it does not included into detailed recording

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2367]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If the detailed recording is turned on, e.g. we should track request/response, and we have a response generated by Tyk (via plugin, virtual endpoint, or similar), a response not tracked in detailed logging.
**What is the expected behavior?**
The response should be tracked
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by matiasinsaurralde** [comment]
I guess this is covered by #2387?

**Comment by matiasinsaurralde** [comment]
The PR for this was already merged: https://github.com/TykTechnologies/tyk/pull/2387
