### ISSUE TITLE
[TT-2393] - Data expiration inside OrgId ignored on failed cache lookups

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2370]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If [Time based capping](https://tyk.io/docs/analyse/capping-analytics-data-storage/#a-name-time-based-cap-a-time-based-cap) enabled, in some cases, you can see analytics records with default `604800` expiration, rather then what specified in organization object.
**What is the expected behavior?**
It should always use value from org object.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See above
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8

**Comment by buger** [comment]
I think I found the issue in this code block https://github.com/TykTechnologies/tyk/blob/33e50b442ef2e3259a0ddd47519bd68262c51ae8/gateway/middleware.go#L211-L224

Organization objects are cached in memory to reduce Redis lookups.
At the moment if org record not found in cache, we set default expiration. 
But cache can be empty because record just expired, and at the time while gw updating org cache in background, all your requests will get default expiration (even if org exists).

There are 2 ways to fix it: 
1) Replace the asynchronious cache update with blocking mutex based approach, and library like https://godoc.org/golang.org/x/sync/singleflight. Potentially can cause side effects on latency.
2) Update org object cache in the background, before cache eviction happened. E.g. have some goroutine which periodically fetches info about all know org objects. This should not affect latency.

**Comment by lonelycode** [comment]
This isn't a regression, it's been like this forever, it's also not a security issue, and it also isn't causing a fire in the client's environment. IMO this shouldn't go into a patch.

**Comment by letzya** [comment]
Still happening in minor scale. Could only be reproduced if setting in tyk.conf `"enforce_org_quotas": false,`

Should be change this to info for visibility? `t.Logger().Debug("no cached entry found, returning 7 days")` https://github.com/TykTechnologies/tyk/blob/f61f66fad7621318fdde06ddf6bfbd592559bf73/gateway/middleware.go#L261

**Comment by andyo-tyk** [comment]
Closing as fixed by https://github.com/TykTechnologies/tyk/pull/2463
