### ISSUE TITLE
Content-type header is not set while sending request to webhook

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2371]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Content-Type header is not set while sending request to Webhooks

**What is the expected behavior?**
Header should be set to application/json

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
master

**Comment by letzya** [comment]
@komalsukhani what happens when we don't send it? I tested webhooks and they work. Is this a specific vendor?

**Comment by buger** [comment]
It depends on receiver side. If it has automatic content type detection and parsing, like Rails, it will broke without header.

**Comment by letzya** [comment]
@buger please see my comment in the code about the json content-type
