### ISSUE TITLE
Allow SSE (Server Sent events) and event streaming via the gateway

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2386]
**Do you want to request a *feature* or report a *bug*?**
Feature
https://en.wikipedia.org/wiki/Server-sent_events

**What is the current behaviour?**
Currently, when fronting SSE with Tyk Gateway, it seems to block the response to the client till you kill the server and all the events get flushed.
The reason it happens is that Tyk is waiting to consume the whole body (for request and response) so technically the gateway will not get the response (and forward it to the client) till timeout or till you kill the server.

One solution would be to use `flush_interval: 10 ` in `tyk.conf` that might work but you need to know the level of granularity you want and be careful with it. If SSE events are sent faster then 1s or the clients need to receive the events with smaller time precision it can be an issue.
Note that this setting is on the gateway level (since it's in tyk.conf) so if you don't want it to be applied to all the APIs you need to shard your gateways for those APIs.
Also - this has not been fully tested for high throughput.

**What is the expected behaviour?**
Per @buger [suggestion](https://github.com/TykTechnologies/tyk/issues/2386)
The gateway should be able to recognise the header `'Content-Type: text/event-stream'` and forward the events to the client as soon as they received from the server. This is a real-time solution rather than async/independent one with flushing the responses on another routine.
> curl http://www.tyk-gateway.com:8081/event-ticks/  -H 'Content-Type: text/event-stream'

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8.2

**Comment by jacostasym** [comment]
Here is an interesting discussion about SSE support in Nginx: https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

What is interesting is that Nginx allows the upstream service to determine when to buffer response data, so it is not a configuration option in Nginx but a header returned by the upstream, that disables buffering:

Content-Type: text/event-stream;
Cache-Control: no-cache;
X-Accel-Buffering: no;

This is specific to Nginx but could be adopted by Tyk as well.

**Comment by buger** [comment]
As an alternative to header, we can think about implementing it as a "plugin" which you can enable for a specific endpoint, which disables buffering. 

@jacostasym what do you think?

**Comment by zcmack** [comment]
Was this support removed from ^2.9.0? I don't see `gateway/handlers_websocket.go` included in the codebase anymore. wondering if it was removed in lieu of a proper solution, but I can't seem to find anything in the documentation about SSE.

**Comment by jeffrngu** [comment]
@letzya @buger This feature no longer works in Tyk GW v.2.9.4-1. I opened https://github.com/TykTechnologies/tyk/issues/3256 to track the issue. Please have a look. Thanks!
