### ISSUE TITLE
Unable to save "Deny" Permissions Tyk Dashboard 1.0

### ISSUE THREAD

**Issue by philipbjorge** [TykTechnologies/tyk#240]
From the user edit screen if I try to deny access to a tyk dashboard feature, upon saving the radio button in the deny column will remain blank and that user can still access the particular dashboard feature.

**Comment by lonelycode** [comment]
Denying access to a feature is the absence of read or write permissions, so it not 'saving' is ok (but not ideal UI granted.

Are you editing the currently logged in user? The user must log in again for the settings to take effect.

**Comment by philipbjorge** [comment]
Confirmed that this does work after logging out.
Thanks
