### ISSUE TITLE
Health Check endpoint to the dashboard

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2411]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
You can use any other endpoint in the dashboard such as `/api/apis`.

**What is the expected behavior?**
...however, using an endpoint in the dashboard would **pollute** the metrics of what endpoint gets called often.  Would rather have one that does not show up in our dashboards. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.8.3

**Comment by christtyk** [comment]
Need to to stay open, client request

**Comment by ilijabojanovic** [comment]
Implemented in 2.10
