### ISSUE TITLE
[TT-2390] - Multiple policies in OIDC/JWT auth method need validation upon create/update of the apidef not when calling it

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2414]
**Do you want to request a *feature* or report a *bug*?**
Bug/feature
Not sure.

**What is the current behavior?**
You get an error on conflicts with multiple policies when actually calling the api. This is because the for OIDC and JWT we create an internal session object on the first time we get the jwt unlike Tyk's auth token that gets created before the api is used.

**What is the expected behavior?**
Get an error when defining multiple policies in the auth method of the api definition, when creating/updating the api using the `/apis` endpoint.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Define conflicting policies and use the id_token to call the api.

1. create `api1` with jwt auth
2. create policy1 with `api1` in the acl
3. create policy2 with `api1` (the same api) in the acl
4. define mapping in the api1 definition:
   `"jwt_scope_to_policy_mapping": {"policy1": policy1-id, "policy2": policy2-id }`
5. Create jwt with the clame: `"scope": "policy1 policy2"`
6. You'll get 403 and error in the log `"cannot apply multiple policies if any are non-partitioned"`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
master unreleased 2.9

**Comment by letzya** [comment]
@buger

**Comment by letzya** [comment]
still valid

**Comment by andyo-tyk** [comment]
Closing this ticket, as it's tracked elsewhere
