### ISSUE TITLE
‘CustomKeyCheck’ object has no attribute ‘arg_count’

### ISSUE THREAD

**Issue by pretecd** [TykTechnologies/tyk#2416]
Hi all!
I'm trying to write a python plugin that replaces the key verification done by Tyk with a custom one (essentially pass the token below the chain if there is one).

Following [this](https://github.com/TykTechnologies/tyk/blob/master/coprocess/python/README.md#authenticating-an-api-with-python) example, I wrote it, but I always get

> Hook 'MyAuthMiddleware' returned an error: 'CustomKeyCheck' object has no attribute 'arg_count'

when an API is called.
The manifest.json is simply:

```
    {
      "file_list": [
    "middleware.py"
      ],
      "custom_middleware": {
    "auth_check": {
      "name": "MyAuthMiddleware"
    },
    "driver": "python"
      }
    }
```

If, instead, I use the `@Hook` decorator then I don't have this issue, but the key verification fails.
Finally, I've this issue also with the `@Pre` decorator.

**Comment by buger** [comment]
Ensure that you are using Python 3.4 or 3.6, and the latest stable version of protobuf packages.

**Comment by CDPrete** [comment]
shouldn't those be provided already as part of the Docker image?

**Comment by buger** [comment]
I think this is an issue with the doc you used. Try this one https://tyk.io/docs/customise-tyk/plugins/rich-plugins/python/custom-auth-python-tutorial/

It should be `@Hook` instead of `@CustomKeyCheck`

**Comment by buger** [comment]
Fixed docs issue

**Comment by CDPrete** [comment]
Sorry for opening this again, but if I follow that other guide, then I get that the key is invalid although my token is invalid.
It's like the token is still validated against the registered API keys (if any). Is there any way to avoid this and have then full control over the validation?

**Comment by buger** [comment]
Have you set your API auth method to "custom auth"? 
Do you have anything in logs when log_level set to "debug"?

**Comment by CDPrete** [comment]
Yes, I was using the custom auth.
I can set the log level to debug and let you know.
