### ISSUE TITLE
swagger import fails with json unmarshal error

### ISSUE THREAD

**Issue by bboozzoo** [TykTechnologies/tyk#242]
Swagger import has ill defined structure of `path` element.

The code https://github.com/TykTechnologies/tyk/blob/master/swagger.go#L61 defines a map of `map[string]PathMethodObject` assuming that every entry under `<path>` has a leaf node mappable to `PathMethodObject`. The assumption is not true. According to swagger spec of `pathItemObject` http://swagger.io/specification/#pathItemObject only `get`, `put`, `post`, `delete`, `options`, `head`, `patch`, have a `OperationObject` node (that roughly maps to `PathMethodObject` in the code).  Having `parameters`, or custom fields will trigger an unmarshaller error.

**Comment by lonelycode** [comment]
Care to supply a pull request?

Thanks.

**Comment by bboozzoo** [comment]
Why not, seems like an easy fix.
