### ISSUE TITLE
Body Transform Plugin doesn't work when Validate JSON plugin is enabled when tested inside API DEBUGGER

### ISSUE THREAD

**Issue by victordas** [TykTechnologies/tyk#2425]
Bug in API DEBUGGER

**Tyk 1.8.2, Tyk Cloud**
I’m using the following plugins for an endpoint.
Body Transform
Track Endpoint
URL Rewrite
Validate JSON.

Current Behavior: 
I am able to get correct response from Postman.
But Bad Request received by the Server in API DEBUGGER.
It works on both Postman and Debugger if I remove Validate JSON.

Expected Behavior:
I should be able to get correct response from Postman.
I should be able to get correct response from API DEBUGGER.

[Schema Definition File Download](https://drive.google.com/open?id=1X0wMCMWSYDrv7R0gTsYVZiBeMKfbg0e7)

**Comment by ilijabojanovic** [comment]
Hi @victordas thank for reporting this issue, could you please attach api definition here in ticket

**Comment by victordas** [comment]
@ilijabojanovic Do you definition including authorization info. In that case it won't be possible.

**Comment by letzya** [comment]
No it doesn't include authorization info. You can go export it from the UI when you are on the API  screen(or copy from the `raw api definition` or use the rest endpoint and call /api/apis/{api-id} )

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/3155222/61796097-a6aa3280-ae1c-11e9-97a3-57e428bb202b.png">

**Comment by victordas** [comment]
Done.

**Comment by victordas** [comment]
Thanks for resolving, Is it possible to get installation patch ?

**Comment by buger** [comment]
Should be released as patch in next 2 weeks.
