### ISSUE TITLE
Erroneous validation of API keys for similar values

### ISSUE THREAD

**Issue by anicolas** [TykTechnologies/tyk#2432]
**Branch/Environment/Version**

- Branch/Version: Stable (`1.8.3`)
- Environment: All

**Describe the bug**

Is is possible to call an API with an "API Key" authentication method with an invalid (but close to a valid one) API token.

**Reproduction steps**

1. Create an API Token

For example:

```
5d3965b6f059f700017d29354436f30dcbff4b39aa4d8de2cee0cd49
```

2. Create an API

Example listen path `/httpbin`

3. Set authentication method as "Auth Token", and (for example), define the auth header name as `X-Api-Key`.

4. Call the API with the auth token

```
curl -i -X GET -H "X-Api-Key:5d3965b6f059f700017d29354436f30dcbff4b39aa4d8de2cee0cd49" http://<tyk_url>/httpbin/get
```

=> You get a `200` response

Then, make the same call, but add a random letter at the end of the API Token (e.g. `z`)

```
curl -i -X GET -H "X-Api-Key:5d3965b6f059f700017d29354436f30dcbff4b39aa4d8de2cee0cd49z" http://<tyk_url>/httpbin/get
```

**Actual behavior**

Although the token is not valid, you get a `200` response.

It seems that I'm able to add up to two characters to the token, if I try to add more the request is rightfully rejected with a `403` status code.

**Expected behavior**

The request with an invalid token should have been rejected with a `403` status code.

**Comment by buger** [comment]
This is a known bug when using hashed keys. The issue will be fixed if you set "hash_key_function" to "murmur64".

**Comment by anicolas** [comment]
Hi,

Thank you for your response.

Do you have a link to the existing bug?

In my opinion this is a pretty significant issue, and Tyk default configuration should prevent this.
