### ISSUE TITLE
Support Zookeeper as a Service Discovery source

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2438]
**Is your feature request related to a problem? Please describe.**
As reported by a user:
"Tyk supports service discovery through configuration servers such as etcd or eureka, in fact, any service that returns a JSON object can be used with the service discovery module.
But zookeeper doesn't expose JSON endpoints.

**Describe the solution you'd like**
Can Tyk support it ootb? if not, can you advise me how to do that?

**Describe alternatives you've considered**
The user looked into using custom Java connector to handle zookeeper service discovery.

**Additional context**
In Tyk we have a suggestion for a workaround - need to document it.

**Comment by letzya** [comment]
Maybe our latest change in SD will help?

**Comment by sedkis** [comment]
https://github.com/TykTechnologies/tyk-docs/pull/876
