### ISSUE TITLE
Feature Request: Organisation Rate Limits

### ISSUE THREAD

**Issue by philipbjorge** [TykTechnologies/tyk#244]
It [looks to me](https://github.com/TykTechnologies/tyk/blob/2f7be404dfe11108a85b5ce8172a971460ef0d8e/middleware_organisation_activity.go#L75) like this can be added without any performance impact.

Would you be interested in a PR?

**Comment by lonelycode** [comment]
Related to #241 - but this should be cool - want to give it a shot? (Develop branch of poss)?
