### ISSUE TITLE
tyk panic after reload，invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lcx102737** [TykTechnologies/tyk#2442]
**Branch/Envrionment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
version :2.8.2

**Describe the bug**
tyk panic after reload

**Reproduction steps**
reload tyk

**Logs (debug mode or log file):**
2019/07/28 03:15:47 http: panic serving 10.115.1.130:39338: runtime error: invalid memory address or nil pointer dereference
goroutine 286595944 [running]:
net/http.(*conn).serve.func1(0xc01109c320)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xe675a0, 0x1ab17a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Route).Match(0x0, 0xc02b11c000, 0xc0317e8570, 0x0)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/route.go:52 +0x26
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).Match(0xc03e6b6180, 0xc02b11c000, 0xc0317e8570, 0x1)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:81 +0x7f
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc03e6b6180, 0x12312a0, 0xc00042c000, 0xc02b11c000)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:133 +0x84
main.mainHandler.ServeHTTP(0x12312a0, 0xc00042c000, 0xc02b11c000)
	/src/github.com/TykTechnologies/tyk/main.go:1211 +0x82
net/http.serverHandler.ServeHTTP(0xc0008061a0, 0x12312a0, 0xc00042c000, 0xc02b11c000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc01109c320, 0x1234ee0, 0xc04749f100)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
2019/07/28 03:16:27 http: panic serving 10.115.1.130:40522: runtime error: invalid memory address or nil pointer dereference
goroutine 286611674 [running]:
net/http.(*conn).serve.func1(0xc03fd66fa0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xe675a0, 0x1ab17a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Route).Match(0x0, 0xc046698000, 0xc030f4a960, 0x0)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/route.go:52 +0x26
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).Match(0xc03e6b6180, 0xc046698000, 0xc030f4a960, 0x1)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:81 +0x7f
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc03e6b6180, 0x12312a0, 0xc049142d20, 0xc046698000)
	/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:133 +0x84
main.mainHandler.ServeHTTP(0x12312a0, 0xc049142d20, 0xc046698000)
	/src/github.com/TykTechnologies/tyk/main.go:1211 +0x82
net/http.serverHandler.ServeHTTP(0xc0008061a0, 0x12312a0, 0xc049142d20, 0xc046698000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc03fd66fa0, 0x1234ee0, 0xc04226ac80)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by gernest** [comment]
@lcx102737 it will be nice if you say what you were doing when you observed this behaviour. On reproduction steps you just dumped the logs, how can I reproduce this?

**Comment by lcx102737** [comment]
Although it has occurred several times, there are no clear steps to reproduce the problem.From the log, only analysis r * Route is nil

**Comment by gernest** [comment]
@lcx102737 I'm sorry I won't be able to help you if I can't reproduce the issue.
