### ISSUE TITLE
Self Signed Certs not being retrieved correctly

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2459]
Self-signed certificates uploaded in Tyk Dashboard cannot be retrieved for viewing correctly. The current workaround is to remove the Org ID from the URL manually and leave only the certificate ID.
See attached "Certificate_not_correctly_retrieved.mp4".
Ticket attachments :

Certificate_not_correctly_retrieved.mp4
3747

**Comment by jay-deshmukh** [comment]
@christtyk , cannot see `Certificate_not_correctly_retrieved.mp4`

**Comment by christtyk** [comment]
@jay-deshmukh I'll Slack you

**Comment by ilijabojanovic** [comment]
Verified

**Comment by ilijabojanovic** [comment]
@lghiur @jay-deshmukh 
For some reason this issue is still visible on latest release-1.9 branch

![video](https://user-images.githubusercontent.com/8557292/66926725-cec9bc00-f02e-11e9-82bd-2c6b0d050fbd.gif)

**Comment by maciejwojciechowski** [comment]
verified in 2.9, fixed
