### ISSUE TITLE
[TT-359] Allow users update the secret of oauth client

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2460]
Is there a way to rotate the password(secret) of the client_id , without changing the client_id itself ?

I have seen https://tyk.io/docs/security/your-apis/oauth-2-0/ and couldnt see an option, so thought to check with your team. 

- [x] Add gateway API
- [ ] Add Dashboard API
- [ ] Add Dashboard Portal API

**Comment by adelowo** [comment]
@buger This seems like a relatively easy fix. Do we want a new endpoint for secret rotation or can make use of what currently exists - just allowing for the secret update?

**Comment by buger** [comment]
Gateway part is done, now require changing the dashboard and portal APIs to support that (modified description a bit)

**Comment by buger** [comment]
Not stale, in fact almost done.

**Comment by letzya** [comment]
https://tyktech.atlassian.net/browse/TT-359

**Comment by andyo-tyk** [comment]
Closing this ticket, as it's tracked elsewhere
