### ISSUE TITLE
From dashboard can't create keys

### ISSUE THREAD

**Issue by swan-go** [TykTechnologies/tyk#247]
I have been create app name is aaa-api from dashboard-->System management-->Apis, create it is ok,  **and then I look at apps directory from tyk_gateway docker, and did not find**,  and the  88888.json is created by curl command line, over the whole test everything is OK.

When Add Key, the error is: Failed to save new session object to Tyk: **Failed to create key: Post http://tyk_gateway:8080/tyk/keys/create: EOF**

$git:(master)(/home/docker/tyk_quickstart/install/apps) ll                                                                                                                                                                        
-rw-r--r-- 1 root root 3767 Apr 21 00:13 88888.json
-rw-r--r-- 1 root root  825 Apr 20 22:19 app_sample.json

![image](https://cloud.githubusercontent.com/assets/6280121/14702907/a4bbe3a6-07df-11e6-92a6-ad8e0400f77e.png)

![image](https://cloud.githubusercontent.com/assets/6280121/14702915/b6cf6158-07df-11e6-8f95-cfba6373a9c7.png)

![image](https://cloud.githubusercontent.com/assets/6280121/14703261/9e64546e-07e1-11e6-8c2c-f26e445cb416.png)

**create key is error:**

![image](https://cloud.githubusercontent.com/assets/6280121/14702958/e014aa8c-07df-11e6-86ac-b4c74d51c6ad.png)
![image](https://cloud.githubusercontent.com/assets/6280121/14702972/ecd3ea26-07df-11e6-9dca-d258d3f38b5c.png)

![image](https://cloud.githubusercontent.com/assets/6280121/14702992/10a65e48-07e0-11e6-9094-a817b7533c36.png)

**Comment by lonelycode** [comment]
The dashboard can't see the gateway, that's where keys get generated. This is probably yet *anotgher* bug with docker networking.

**Comment by swan-go** [comment]
I have been test from chrome, it show : {"status":"error","error":"Forbidden"}  
![image](https://cloud.githubusercontent.com/assets/6280121/14703432/60f25f9e-07e2-11e6-9cf4-40cd9b984453.png)

And from tyk_dashboard docker, I test it by command: curl http://10.200.152.96:8080/tyk/keys/create, it return as bleow:
{"status":"error","error":"Forbidden"}  

so to prove that docker networking is good.

**Comment by lonelycode** [comment]
Odd, what is the output of the gateway container?

**Comment by swan-go** [comment]
I have check log from tyk_gateway container, I judge not seem to have any relevant log output, I log level is debug,  as bleow:

> time="Apr 20 17:43:57" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:57" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:57" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:58" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:43:58" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:43:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:58" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:43:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:08" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:18" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:28" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:38" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:48" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:44:58" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:44:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:08" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:18" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:28" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:38" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:48" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:45:58" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:45:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:08" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:08" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:18" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:18" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:28" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:28" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:38" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:38" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:48" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:48" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="[STORE] Getting WAS: PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="[STORE] Getting: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Primary instance set, I am master" 
time="Apr 20 17:46:58" level=debug msg="[STORE] SET Raw key is: PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="[STORE] Setting key: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID" 
time="Apr 20 17:46:58" level=debug msg="Input key was: host-checker:PollerActiveInstanceID"

**Comment by lonelycode** [comment]
You won't need debug output. Unauthorised API access is always logged, so if things are working as expected then you would see your test requests in the log as warnings.

You will also errors caused by a failure to respond to the dashboard. So this debug output isn't helpful. Can you switch it off, then just try to create a key - you need to watch the logs of both systems to see what the error is.

**Comment by swan-go** [comment]
Ok, I have been retest it,  After when I create api name is aaa-api, the log as bleow:

time="Apr 20 17:57:51" level=info msg="Connection dropped, connecting.." 
time="Apr 20 17:57:51" level=warning msg="Cache purging is no longer part of Tyk Gateway, please use Tyk-Pump." 
time="Apr 20 17:57:51" level=info msg="Starting Poller" 
time="Apr 20 17:57:51" level=info msg="Setting up Server" 
time="Apr 20 17:57:51" level=info msg="--> Standard listener (http)" 
time="Apr 20 17:57:51" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 17:57:51" level=info msg="Detected 1 APIs" 
time="Apr 20 17:57:51" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 17:57:51" level=info msg="----> Tracking: (no host)" 
time="Apr 20 17:57:51" level=info msg="----> Checking security policy: Token" 
time="Apr 20 17:57:51" level=info msg="Loading uptime tests..." 
time="Apr 20 17:57:52" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 17:57:52" level=info msg="Gateway started (v2.0.0.0)" 
time="Apr 20 17:57:52" level=info msg="--> Listening on port: 8080" 
time="Apr 20 17:58:10" level=info msg="Reloading endpoints" 
time="Apr 20 17:58:10" level=info msg="Reloading endpoints" 
time="Apr 20 17:58:10" level=info msg="Reloading endpoints" 
time="Apr 20 17:58:20" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 17:58:20" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 17:58:20" level=info msg="Detected 1 APIs" 
time="Apr 20 17:58:20" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 17:58:20" level=info msg="----> Tracking: (no host)" 
time="Apr 20 17:58:20" level=info msg="----> Checking security policy: Token" 
time="Apr 20 17:58:20" level=info msg="Loading uptime tests..." 
time="Apr 20 17:58:20" level=info msg="API reload complete" 
time="Apr 20 17:58:41" level=info msg="Reloading endpoints"

**Comment by lonelycode** [comment]
> time="Apr 20 17:58:20" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 

Looks like your setup is configured to get API Definitions from disk and not the dashboard service

**Comment by swan-go** [comment]
ohh, thanks,  but another error when Add keys, the new log as bleow:

time="Apr 20 17:58:51" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 17:58:51" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 17:58:51" level=info msg="Detected 1 APIs" 
time="Apr 20 17:58:51" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 17:58:51" level=info msg="----> Tracking: (no host)" 
time="Apr 20 17:58:51" level=info msg="----> Checking security policy: Token" 
time="Apr 20 17:58:51" level=info msg="Loading uptime tests..." 
time="Apr 20 17:58:51" level=info msg="API reload complete" 
time="Apr 20 18:01:29" level=info msg="Reset quota for key." inbound-key=5717c3323841c900010000013b9d872f88934b826d64c9b763aa8adf key=quota-6dca4fd4 
2016/04/20 18:01:29 http: panic serving 10.0.2.2:61863: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc820542680)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xc55920, 0xc820010090)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.createKeyHandler(0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/api.go:1316 +0x141b
main.CheckIsAPIOwner.func1(0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc820438550, 0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820335c20, 0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc82056c630, 0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8200a3780, 0x7feb61656ff8, 0xc8200720d0, 0xc8203680e0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820542680)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by lonelycode** [comment]
Yeah - that's ugly. But if the API is not loaded, *and* we're not in DB mode *and* the dashboard is trying to create a keey for non-existent API, I don't expect the app to react well, considering it is an unstable configuration.

**Comment by swan-go** [comment]
All config is default from tyk_quickstart docker :)

**Comment by lonelycode** [comment]
Ummm, doubt it, the default in the quickstart is to use the dashboard: 

https://github.com/lonelycode/tyk_quickstart/blob/master/tyk.conf#L8

So something changed the configuration to stop it from loading from the dashboard. The quickstart *mounts* a valid config from the repo: 

https://github.com/lonelycode/tyk_quickstart/blob/master/docker-compose.yml#L44

**Comment by swan-go** [comment]
Ok,  I  download the  tyk_quickstart docker, the I have been modify it form db, then retest it,  the log as bleow:

time="Apr 20 18:12:39" level=info msg="Connection dropped, connecting.." 
time="Apr 20 18:12:39" level=warning msg="Cache purging is no longer part of Tyk Gateway, please use Tyk-Pump." 
time="Apr 20 18:12:39" level=info msg="Starting Poller" 
time="Apr 20 18:12:39" level=info msg="Setting up Server" 
time="Apr 20 18:12:39" level=info msg="--> Standard listener (http)" 
time="Apr 20 18:12:39" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 18:12:39" level=info msg="Detected 1 APIs" 
time="Apr 20 18:12:39" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 18:12:39" level=info msg="----> Tracking: (no host)" 
time="Apr 20 18:12:39" level=info msg="----> Checking security policy: Token" 
time="Apr 20 18:12:39" level=info msg="Loading uptime tests..." 
time="Apr 20 18:12:39" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 18:12:39" level=info msg="Gateway started (v2.0.0.0)" 
time="Apr 20 18:12:39" level=info msg="--> Listening on port: 8080" 
time="Apr 20 18:13:34" level=info msg="Reloading endpoints" 
time="Apr 20 18:13:34" level=info msg="Reloading endpoints" 
time="Apr 20 18:13:34" level=info msg="Reloading endpoints" 
time="Apr 20 18:13:44" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 18:13:44" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 18:13:44" level=info msg="Detected 1 APIs" 
time="Apr 20 18:13:44" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 18:13:44" level=info msg="----> Tracking: (no host)" 
time="Apr 20 18:13:44" level=info msg="----> Checking security policy: Token" 
time="Apr 20 18:13:44" level=info msg="Loading uptime tests..." 
time="Apr 20 18:13:44" level=info msg="API reload complete" 
time="Apr 20 18:14:02" level=info msg="Reloading endpoints" 
time="Apr 20 18:14:12" level=error msg="Failed to decode body: json: cannot unmarshal string into Go value of type []main.Policy" 
time="Apr 20 18:14:12" level=info msg="Loading API Specification from /opt/tyk-gateway/apps/app_sample.json" 
time="Apr 20 18:14:12" level=info msg="Detected 1 APIs" 
time="Apr 20 18:14:12" level=info msg="--> Loading API: Tyk Test API" 
time="Apr 20 18:14:12" level=info msg="----> Tracking: (no host)" 
time="Apr 20 18:14:12" level=info msg="----> Checking security policy: Token" 
time="Apr 20 18:14:12" level=info msg="Loading uptime tests..." 
time="Apr 20 18:14:12" level=info msg="API reload complete" 
time="Apr 20 18:14:32" level=info msg="Reset quota for key." inbound-key=5717c6cecd5e5f0001000001ddd70435742a470a440a66bf0205febe key=quota-540d4200 
2016/04/20 18:14:32 http: panic serving 10.0.2.2:62318: runtime error: invalid memory address or nil pointer dereference
goroutine 114 [running]:
net/http.(*conn).serve.func1(0xc82055c000)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xc55920, 0xc820010090)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.createKeyHandler(0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/home/tyk/go/src/github.com/lonelycode/tyk/api.go:1316 +0x141b
main.CheckIsAPIOwner.func1(0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/home/tyk/go/src/github.com/lonelycode/tyk/middleware_api_security_handler.go:24 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc8202c0970, 0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820245860, 0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/home/tyk/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc8202a4a80, 0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201e4580, 0x7fd7be97fe68, 0xc82006a0d0, 0xc820346a80)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82055c000)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by lonelycode** [comment]
How are you starting the containers? You need to start it with compose. It's still using the file-based config.

**Comment by swan-go** [comment]
sorry,  I have been redownload, and clear it, and retest, it is ok,  thanks :) :) :)
