### ISSUE TITLE
Environment Migration with Context Variable

### ISSUE THREAD

**Issue by svnarasimha** [TykTechnologies/tyk#2476]
Hi - When we migrate from Development to QA to UAT to PROD; the target URLs have to be changed manually based on the environments. It is huge efforts if you are introducing the Gateways for the first time in an Organization....let us say, we have to migrate 100 services. 
The Suggestion is, we can have a context variable for the environment where the Developer can change only in 1 place instead 100 services while migrating to higher environments.

As an example : If we have Dev Target URL as https://development.petstore.com/; PROD as https://prod.petstore.com/; introduce context variable as https://{{ContextVariable}}.petstore.com/

Regards
Narasimha

**Comment by buger** [comment]
Right, we do some work in this direction so you can set some variables for outside like Vault, or Consul https://github.com/TykTechnologies/tyk/pull/2465

I believe we can also add gateway config values, environment variables support too.

**Comment by andrey-hohlov** [comment]
Hi, @buger 
What do you think, when can we get an update with this feature? 
I'm choosing a gateway for my pet project, tried Tyk and have stuck with this problem (need to have ENV variables in API definition).

**Comment by adelowo** [comment]
Hi @andrey-hohlov that PR has added support for environment variables and gateway config values.

**Comment by andrey-hohlov** [comment]
Hi, @adelowo it's great! I just want to know when it will be merged and a version with these features will be released :)
