### ISSUE TITLE
custom_middleware path is absolute 

### ISSUE THREAD

**Issue by martinboy** [TykTechnologies/tyk#248]
When loading file-based API the middleware path in custom_middleware section is not working correctly. 
Here is my API configuration 

```
"custom_middleware" : {
        "pre" : [ ],
        "post" : [
            {
                "name": "sampleMiddleware",
                "path": "middleware/sampleMiddleware.js",
                "require_session": false
            }
        ],
        "response" : [ ]
    },
```

I have tried to set 'path' as described in documentation https://tyk.io/docs/tyk-api-gateway-v-2-0/javascript-plugins/middleware-scripting but with no luck. I have seen an error in the log file

```
ERROR jsvm: Failed to load Middleware JS: open middleware/sampleMiddleware.js: no such file or directory
```

I have also tried 'sampleMiddleware.js' path assuming that the following setting from tyk.conf file is used

```
"middleware_path": "/opt/tyk-gateway/middleware"
```

The only working solution I found when i set the path to the absolute '/opt/tyk-gateway/middleware/sampleMiddleware.js'

I mean it is wrong and confusing scenario.

**Comment by lonelycode** [comment]
Thanks for raising, it's a very valid point and we'll look at making no sure that config option is clearer

**Comment by lonelycode** [comment]
To add to this, the middleware path is used for folder-based plugin loading (no need to edit the API Definition) while the path in the middleware section of the API Def is for explicit loading.

But it still needs to be made clearer.
