### ISSUE TITLE
/tyk/keys is not returning all the keys, if redis cluster mode is enabled

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2497]
**Branch/Environment/Version**
master

**Describe the bug**
Key listing api `tyk/keys` is not returning all the keys stored in redis cluster. It is fetching keys from single node, instead of fetching from all the nodes of the cluster

**Reproduction steps**

1. Create redis cluster with 3 master and 3 slave nodes.
2. Connect gateway to redis cluster
3. Create key with id `l7xxcfcb9079118c4358b45b4db203699601`
4. Call `/tyk/keys` endpoint. 

The key will not be listed in the response

**Actual behavior**
l7xxcfcb9079118c4358b45b4db203699601 is not listed in response of  `/tyk/keys` endpoint

**Expected behavior**
l7xxcfcb9079118c4358b45b4db203699601 should be returned in `/tyk/keys` response

**Comment by buger** [comment]
@komalsukhani we should update all components using redis.
