### ISSUE TITLE
JSVM authentication broken when using bundles

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2512]
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: On-prem

**Describe the bug**
I've been testing JSVM authentication with a bundle, seems that `DynamicMiddleware` doesn't get initialized with the right flag, when using an authentication hook: https://github.com/TykTechnologies/tyk/blob/master/gateway/middleware.go#L63

In `api_loader.go` we have the following code:
```go
		if ottoAuth {
			logger.Info("----> Checking security policy: JS Plugin")

			authArray = append(authArray, createDynamicMiddleware(mwAuthCheckFunc.Name, true, false, baseMid))
		}
```

This call will always initialize `DynamicMiddleware` with `Auth` set to `false`. To fix this we could extend `createDynamicMiddleware` and add an argument. After a quick test, I've found that this fixes the issue.
[bundle.zip](https://github.com/TykTechnologies/tyk/files/3623811/bundle.zip)

**Reproduction steps**

1. Configure an API with the following settings:

```js
    "custom_middleware_bundle": "bundle.zip",
    "enable_coprocess_auth": true,
```
2. Serve the attached bundle (`bundle.zip`).

**Actual behavior**
The middleware gets called but the user receives the following error:

```sh
% curl localhost:8080/quickstart/ -H 'Authorization: foobar'
{
    "error": "Session state is missing or unset! Please make sure that auth headers are properly applied"
}
```

**Expected behavior**
When sending `foobar`, the authentication should be successful.

**Comment by buger** [comment]
It is not related to 2.9, lets move to one of patch releases. 

@matiasinsaurralde pls write a tests using bundles and auth (we already have similar examples, check `TestTykMakeHTTPRequest`)

**Comment by educroquet** [comment]
Hi, I'd like also to be able to do a JSVM plugin for Custom Auth, but it is not possible in 2.9.3.2 due to this never set `DynamicMiddleware.Auth` property in source code.

I've managed to activate it by modifying  2.9.3.2 source code like this :
- `gateway/middleware.go` : add a `func createDynamicAuthMiddleware`  that is setting the `DynamicMiddleware.Auth` property to true

```
// ERWAN: allow Auth JS Mdw
func createDynamicAuthMiddleware(name string, baseMid BaseMiddleware) func(http.Handler) http.Handler {
  dMiddleware := &DynamicMiddleware{
     BaseMiddleware:      baseMid,
     MiddlewareClassName: name,
     Pre:                 true,
     UseSession:          false,
     Auth:		  true, // ERWAN
  }
  return createMiddleware(dMiddleware)
}
```

- `gateway/api_loader.go` : call `createDynamicAuthMiddleware` instead of `createDynamicMiddleware`

```
if ottoAuth {
   logger.Info("----> Checking security policy: JS Plugin")
   //authArray = append(authArray, createDynamicMiddleware(mwAuthCheckFunc.Name, true, false, baseMid)) // ERWAN
   authArray = append(authArray, createDynamicAuthMiddleware(mwAuthCheckFunc.Name, baseMid)) // ERWAN
}
```

Then I've made a auth.js plugin as :

```
log("====> JS Auth initialising");
var myAuthCheck = new TykJS.TykMiddleware.NewMiddleware({});
myAuthCheck.NewProcessRequest(function(request, session, spec) {
   ...
   return {Request: request, Session: my_session, AuthValue: my_session_key}
})
log("====> JS Auth initialised on 'myAuthCheck' variable")
```

And declared it within an API Definition as:

```
...
    "use_keyless": false,
    "enable_coprocess_auth": true,
    "custom_middleware": {
        "driver": "otto",
        "auth_check": {
            "name": "myAuthCheck",
            "path": "middleware/auth.js"
        }
    },
...
```
