### ISSUE TITLE
gRPC uses full URI and not Path

### ISSUE THREAD

**Issue by alephnull** [TykTechnologies/tyk#2513]
**Branch/Environment/Version**
- Branch/Version: 2.8.4
- Environment: MDCB/on-prem

**Describe the bug**
Previously (in 2.8.3), the gRPC plugin returned just the path as `r.URL.String()`. This has become `r.URL.Path` in 2.8.4. 

Investigating further, it looks like the change was introduced from in branch release-2.8.1. release-2.8 has the older code.

**Reproduction steps**
1. Setup a gRPC API.
2. Observe the `uri` parameter in the response.

**Actual behavior**
url: "/api/path/only?query=params" 

**Expected behavior**
url: "/api/path/only"

**Comment by matiasinsaurralde** [comment]
**Quick note on the bug description:** looks like it's actually the opposite, at least, when looking at the code, we find `r.URL.Path` in [`2.8.3`](https://github.com/TykTechnologies/tyk/blob/v2.8.3/coprocess.go#L85) and `r.URL.String()` in [`2.8.4`](https://github.com/TykTechnologies/tyk/blob/v2.8.4/coprocess.go#L86).
I guess `r.URL.String()` is fine (in this scenario the user can parse the full URL and extract specific parameters)!

**Comment by buger** [comment]
Not a bug
