### ISSUE TITLE
Key is visible in logs when session is recreated

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2520]
**Branch/Environment/Version**
- Branch/Version: All
- Environment: All

**Describe the bug**
I don't have much context on the scenario of this bug, but seems that [middleware.go](https://github.com/TykTechnologies/tyk/blob/master/gateway/middleware.go#L588) doesn't obfuscate the key when logging "Recreating session for key".

**Expected behavior**
My guess is that we should modify this to use [`enable_key_logging`](https://tyk.io/docs/configure/tyk-gateway-configuration-options/#a-name-enable-key-logging-a-enable-key-logging) and `obfuscateKey` function.

**Comment by ilijabojanovic** [comment]
Verified
