### ISSUE TITLE
Add token user as header

### ISSUE THREAD

**Issue by byrnedo** [TykTechnologies/tyk#256]
Is there any way to add the developer username (if there is one) for a given token when it's being proxied to the upstream?

I'm thinking in the upstream api's config in the add header section if there was any kind of templating there for a context object?

**Comment by lonelycode** [comment]
When a token is generated for a dashboard user, the following is added to the token metadata:

- `tyk_key_request_fields` - The field set that was defined when the user submitted the key request
- `tyk_user_fields` - The fields that are part of the user account (the custom fields)
- `tyk_developer_id` - The internal dev ID of the user that you can use as a REST lookup

You could use the `$tyk_meta.tyk_developer_id` reserved field to inject into a header to get identifying data for a user?

**Comment by byrnedo** [comment]
Ok great, so just a case of using that `$tyk_meta.tyk_developer_id` directly in the header value in the dashboard?

**Comment by lonelycode** [comment]
Yep, that should do it - so long as the token was created by the portal, the field should exist.

**Comment by byrnedo** [comment]
Worked fine, thanks again!
