### ISSUE TITLE
Tyk Dashboard with symfony

### ISSUE THREAD

**Issue by NadaBen** [TykTechnologies/tyk#257]
Helloo; I'm coding an api with symfony2, i want to know how  can i integrate the tyk dashboard in my project ? i did not find any tuto or documentation ,

**Comment by lonelycode** [comment]
How exactly do you see this nntegration working?

**Comment by NadaBen** [comment]
is the dashboard will be integrated in a bundle, how to do that ?

**Comment by lonelycode** [comment]
I have no experience with Symfony, or PHP I'm afraid :-) so "a bundle" doesn't mean much.

What are you trying to achieve?

**Comment by NadaBen** [comment]
I want to develop a dashboard for the admin of my api and an other for users, i do not know if can add tyk dashboard with symfony to realize that

**Comment by lonelycode** [comment]
Well you can use Tyk Dashboard to administer your APIs that are *managed* by Tyk, I.e. That are using the Tyk API gateway, but not to manage your actual application.

**Comment by NadaBen** [comment]
so, can i let tyk api gateway manage my actual api ?

**Comment by lonelycode** [comment]
That's kind of what it's for ;-) 

But seriously - it depends what you are looking for. Tyk can do a lot of stuff, like rate limiting, quotas, access control etc. as well as http transforms and analytics gathering.

Suggest you take a look at the site (https://Tyk.io) for a feature list to see if it's what you need

**Comment by NadaBen** [comment]
Okey Thank you
