### ISSUE TITLE
Odd behaviour in auth mechanism

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2577]
**Customer Request** <br/><br/>We are currently defining one of our API’s and noticed a weird behaviour with the following steps:<br/><br/>- Set auth to multiple auth mechanisms, checked auth token and mutual tls with auth token as the base identity.<br/>- Tested the api without certs and it fails which is normal<br/>- But then switched back to just auth token and then I receive an error with the following text even though I send the right token<br/>  "Session state is missing or unset! Please make sure that auth headers are properly applied”<br/>- However now if I keep multiple auth mechanisms and only select auth token, it works as expected and passes the authentication, so it seems as if going back to just authentication token seems to have something broken in it when previously set to multiple mechanisms.<br/><br/>We need to use both and have it setup with both now anyways so it is not blocking us but may be an issue for others or in the future.Denis Zaytsev

**Comment by letzya** [comment]
@christtyk which version please

**Comment by christtyk** [comment]
tyk-dashboard:
1.8.5-1
tyk-pump: 0.7.2-1
tyk-gateway: 2.8.4-1

**Comment by furkansenharputlu** [comment]
@ilijabojanovic I couldn't reproduce it. Would you please confirm ?

**Comment by buger** [comment]
@dencoded can you record your screen?

**Comment by maciejwojciechowski** [comment]
I am not able to reproduce it on 1.8 or 1.9 release branches.

**Comment by maciejwojciechowski** [comment]
also tried with packages with exact same gw, dash, pump versions and cannot replicate it.
