### ISSUE TITLE
Go plugins: Plugin update causing issues during gateway release

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2578]
**Branch/Environment/Version**
- Branch/Version: Release-2.9
- Environment: All

**Describe the bug**
Related to: https://github.com/TykTechnologies/tyk/issues/2558

When we update bundle in api definition, gateway errors on file update

**Reproduction steps**
1. Add api with go bundle (e.g bundle-go-pre.zip)
2. Save api 
3. Generate some traffic to that api
4. On api definition, update bundle file (e.g bundle-go-post.zip)
5. Save api definition

**Actual behavior**
During gateway reload we have errors in console.  Only way to see consume new plugin is to restart gateway

**Expected behavior**
New bundle should be loaded in gateway

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
```
[Sep 30 11:34:46]  INFO main: API bind on custom port:0
[Sep 30 11:34:46]  INFO main: ----> Fetching Bundle: bundle-go-pre.zip
[Sep 30 11:34:46]  INFO main: ----> Loading bundle: bundle-go-pre.zip
[Sep 30 11:34:46]  INFO main: ----> Verifying bundle: bundle-go-pre.zip
[Sep 30 11:34:46]  INFO main: ----> Bundle is valid, adding to spec: bundle-go-pre.zip
[Sep 30 11:34:46]  INFO Checking security policy: Open api_id=8750c05eff91473f414cdace513e789c api_name=go org_id=5d84baee9633d70782364f08
[Sep 30 11:34:46] ERROR Could not load Go-plugin error=plugin.Open("middleware/bundles/8750c05eff91473f414cdace513e789c_0f584241a46bd022d0dec6f944b2f6b6/SendCurrentTime"): plugin already loaded mwPath=middleware/bundles/8750c05eff91473f414cdace513e789c_0f584241a46bd022d0dec6f944b2f6b6/SendCurrentTime.so mwSymbolName=SendCurrentTime
[Sep 30 11:34:46]  INFO gateway: API Loaded api_id=8750c05eff91473f414cdace513e789c api_name=go org_id=5d84baee9633d70782364f08 server_name=-- user_id=-- user_ip=--
[Sep 30 11:34:46]  INFO host-check-mgr: Loading uptime tests...
[Sep 30 11:34:46]  INFO main: Initialised API Definitions
[Sep 30 11:34:46]  INFO main: API reload complete
[Sep 30 11:34:46]  INFO main: reload: complete
[Sep 30 11:34:46]  INFO main: Initiating coprocess reload
[Sep 30 11:34:46]  INFO coprocess: Reloading middlewares
```
**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by buger** [comment]
This actually covered in docs. 
The main idea here that you have to update `so` file name, or restart gateway.
