### ISSUE TITLE
Ignore plugin can't be used with URL rewriting

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2579]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB]

**Describe the bug**
The main purpose of "ignore" plugin is to bypass authentification, however, it also bypass lot of other middlewares like URL rewrite. 

**Reproduction steps**
- Add endpoint with URL rewrite and Ignore plugins
- URL rewrite won't work

**Comment by ilijabojanovic** [comment]
@buger https://tyk.io/docs/transform-traffic/endpoint-designer/
Few times i saw that, but when i checked doc's...

```
Ignore
Adding a path to an ignored list means that the path will not be processed for authentication data. This plugin can be very useful if you have a non-secure endpoint (such as a ping) that you don’t need secured.

NOTE: Adding a path to an ignore list will bypass all other configuration settings.
```

**Comment by buger** [comment]
Yeah, but this is just to "protect" us from this confusions.
However, it does not makes much sense.
