### ISSUE TITLE
JWT auth can't be combined with Auth token 

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2580]
**Branch/Environment/Version**
master/2.9

**Describe the bug**
The goal is to perform JWT validation and log user using standard auth token.

JWT authentification use auth.Header value to determine HTTP header name. 
Auth token middleware use exactly the same field to the same purpose.
So you can't have multiple auth mode using both, because you can't set them to read multiple headers. 

**Expected behavior**
It should be possible to set distinct headers for both MWs. We should add a separate header field for JWT middleware.
Also for Oidc, oauth, a certificate authorization.

**Comment by letzya** [comment]
BTW @buger did you think about the flow - with JWT one of the actions is "applyPolicy" and we verify it against a policy regardless of the session key we are saving. What do you do with multiple auth methods of auth token + jwt and when you choose Auth token for the `base_identity_provided_by`.
With basic auth +auth token there's no such issue.

**Comment by ilijabojanovic** [comment]
Blocker https://github.com/TykTechnologies/tyk/issues/2695

**Comment by maciejwojciechowski** [comment]
basic scenario JWT + AuthToken verified
