### ISSUE TITLE
The policy and key limit rules, priorities?

### ISSUE THREAD

**Issue by swan-go** [TykTechnologies/tyk#261]
A policy can correspond to more than one key, the policy and key has request limit and quota limit; At this point the policy rules came into force, the key limit is invalid, which means the policy covers the key limit rules?

**Comment by lonelycode** [comment]
The policy overwrites the key limit rules, it basically sets the new maximums and ACL as soon as the key shows up, every time the key shows up. 

So it's either the policies maximums or the keys limit but never both.

In the next version we are including a way to have partial policies (partitioned policies we are calling them) hat only apply to portions of a key.
