### ISSUE TITLE
[TT-2382] - setting ENV variable for tyk_api_config.Secret in Dashboard does not work

### ISSUE THREAD

**Issue by kgathi2** [TykTechnologies/tyk#2614]
Tyk Dashboard 1.8.5

**Describe the bug**
Setting ENV Variable `TYK_DB_TYKAPICONFIG_SECRET` does not pick up as Docs suggest.
Also `TYK_DB_SHAREDNODESECRET` does not work as suggested in Docs. In this case `TYK_DB_NODESECRET` does. 

**Actual behavior**
Uses default configs in tyk_analytics.conf

**Expected behavior**
Should override settings in tyk_analytics.conf

**Comment by l3ender** [comment]
We're also facing this issue--very frustrating/annoying that the behavior for a few select keys is different than the doc. Expected behavior would be that all config values are handled with the same name conversion pattern from json->env var.

**Comment by sedkis** [comment]
This makes complete sense.  

In order to fix it we'd probably have to break backwards compatibility, or use some other work around where newField inherits oldField, and newField adheres to the standard.

In the meantime, we're updating the Docs asap so as to note the exceptions

**Comment by l3ender** [comment]
Just thinking out loud--wouldn't it be possible to have the new (correct) environment variable supported, with fallback support for the (deprecated) old format? That would allow for it to be a non-breaking change.

**Comment by sedkis** [comment]
right, that's what I was hinting at here:

> newField inherits oldField

you just put it more eloquently

**Comment by l3ender** [comment]
Not stale.

**Comment by hinorashi** [comment]
any update guys, I'm using tyk dashboard v3.1.1 now and the docs seems to be not yet updated:
https://tyk.io/docs/tyk-configuration-reference/tyk-dashboard-configuration-options/
🐧

**Comment by hinorashi** [comment]
> Tyk Dashboard 1.8.5
> 
> **Describe the bug**
> Setting ENV Variable `TYK_DB_TYKAPICONFIG_SECRET` does not pick up as Docs suggest.
> Also `TYK_DB_SHAREDNODESECRET` does not work as suggested in Docs. In this case `TYK_DB_NODESECRET` does.
> 
> **Actual behavior**
> Uses default configs in tyk_analytics.conf
> 
> **Expected behavior**
> Should override settings in tyk_analytics.conf

For `TYK_DB_TYKAPICONFIG_SECRET` you could try `TYK_DB_TYKAPI_SECRET` (along with `TYK_DB_TYKAPI_HOST` and `TYK_DB_TYKAPI_PORT`)

I'm not sure about `TYK_DB_SHAREDNODESECRET` either :crab:

**Comment by sedkis** [comment]
Hi folks - the docs are now auto-generated, so no more human errors for issues like these.
