### ISSUE TITLE
URLRewriteMiddleware modifies the original request

### ISSUE THREAD

**Issue by gernest** [TykTechnologies/tyk#2618]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB]

**Describe the bug**
The `URLRewriteMiddleware` modifies the original request, this is a source of bugs, because the request object is a fact, and if new information needs to be added there `Context` for it.

I came across this while debugging an issue with url rewriting feature.

**Comment by SebHoules** [comment]
This issue prevent us for transform Soap APIs to Rest, because `methodTransform ` can't be executed
