### ISSUE TITLE
[TT-2379] - On Cloud allow user to update portal page templates

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2622]
**Is your feature request related to a problem? Please describe.**
User on cloud would like to make custom templates for their portal

**Describe the solution you'd like**
Ability to upload html templates on cloud

**Describe alternatives you've considered**
User currently using CMS

**Additional context**
Ticket from customer, not a feature causing fires. Let me know.

**Comment by christtyk** [comment]
For client - keep open

**Comment by andyo-tyk** [comment]
This is not a feature we will be developing for the Tyk Classic Portal.
