### ISSUE TITLE
[TT-2376] - Policy Scheduling

### ISSUE THREAD

**Issue by tamaraevans** [TykTechnologies/tyk#2627]
**Is your feature request related to a problem? Please describe.**
At the moment we have to use versioning to achieve set times for Policies to accessible. 

**Describe the solution you'd like**
It would be great to be able to automate the scheduling of Policies ie some organisations only want to give access during working hours etc

**Comment by ViolaMarku** [comment]
@tamaraevans could you please give some info on company requesting this, frequency etc? Thanks :)

**Comment by tamaraevans** [comment]
this has come up again :)

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and we will ensure this is considered when we next look at this part of the code; I am closing the request here due to the age.
