### ISSUE TITLE
Failed to create Key on tyk

### ISSUE THREAD

**Issue by susanlie** [TykTechnologies/tyk#264]
Dear all,

I was follow the all instruction on 
https://tyk.io/docs/tyk-api-gateway-v-2-0/tutorials/set-up-your-first-api-pro-edition/
i have created the 'Test API' dan when i must create the key, i have error on dashboard.
The Error like this :
Failed to save new session object to Tyk: Failed to create key: Post http://tyk_gateway:8080/tyk/keys/create: EOF

Can u help please 🙏

**Comment by susanlie** [comment]
i hope the @lonelycode dan help me 😄

**Comment by lonelycode** [comment]
I'd suggest looking at our support forum where these kinds of questions have been asked loads of times, this isn't a code issue or a bug report so GH isn't the best place for this. 

FWIW it looks like you have misconfigured your dashboard and it can't resolve your gateway.

**Comment by susanlie** [comment]
thx for the respon, i have googling, but i have not found any solution, and i have configured from the first step, every step succesfully, except step to create a key, and just give me message 'failed'

**Comment by lonelycode** [comment]
> FWIW it looks like you have misconfigured your dashboard and it can't resolve your gateway.

**Comment by susanlie** [comment]
how to check the misconfigured on my dashboard? because i have follow the instruction from the first, and everything is fine.

**Comment by susanlie** [comment]
i have follow the instruction, everything is fine


developers-MacBook-Pro:tyk_quickstart developer$ curl -H "Authorization: null" http://192.168.99.100:8080/test-api/get
{
    "error": "Key not authorised"
}developers-MacBook-Pro:tyk_quickstart developer$ curl -H "Authorization: null" ttp://192.168.99.100/test-api/get
{
    "error": "Key not authorised"
}

and the next step is create a "Key"

**Comment by lonelycode** [comment]
Ok, so that tutorial assuems that you are not using the docker quickstart, the docker quickstart is a whole different ballgame.

When you ran [this](https://tyk.io/docs/tyk-api-gateway-v-2-0/installation-options-setup/docker/), did everything work as expected?

you'll need to examine your docker logs output and the compose network to see if everything is working, it looks to me like the compose script did not build the DNS properly. This happens a lot, because docker insists on changing it's behaviour across versions and platforms.

try and find out what the hostnames are internally of the various hosts and the adjust your configuration accordingly.

**Comment by susanlie** [comment]
i have run on docker quickstart terminal, 

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

developers-MacBook-Pro:~ developer$ cd kalibataCamp/belajarTykIo/tyk_quickstart/
developers-MacBook-Pro:tyk_quickstart developer$ docker-compose up -d --force-recreate
Recreating tykquickstart_tyk_mongo_1
Recreating tykquickstart_tyk_redis_1
Recreating tykquickstart_tyk_dashboard_1
Recreating tykquickstart_tyk_gateway_1
Recreating tykquickstart_tyk_pump_1
developers-MacBook-Pro:tyk_quickstart developer$ ./setup.sh
Detected a Docker VM...
Using 192.168.99.100 as Tyk host address.
If this is wrong, please specify the instance IP address (e.g. ./setup.sh 192.168.1.1)
Creating Organisation
ORG ID: 5768edaf44e2370001000001
Adding new user
USER AUTH: 634e328e259840185f4f4559235126eb
USER ID: 5768edaf5aab11b58453795e
Setting password
Setting up the portal domain
Setting up the Portal catalogue
Setting target URL for Portal APIs
Creating the Portal Home page

DONE
====
Login at http://192.168.99.100:3000/
Username: test10522@test.com
Password: test123
Portal: http://www.tyk-portal-test.com/portal/

**Comment by lonelycode** [comment]
This issue is addressed in develop, however invalid APIs will still be bounced.
