### ISSUE TITLE
Python inspect module changes

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2640]
**Branch/Environment/Version**
- Branch/Version: All
- Environment: On-prem

**Describe the bug**
The [`inspect` module ](https://docs.python.org/3/library/inspect.html#inspect.stack) has changed its syntax after Python 3.4.x/3.5x. We use `inspect.stack` for handling local imports in plugins (see #2402).

When using these versions, the following issue may occur:
```
AttributeError: 'tuple' object has no attribute 'function'
```

We should add fallback logic to support this.

**Reproduction steps**
- Setup Python 3.4.9 or 3.5.6.
- Create a Python plugin bundle.
- Setup an API and start or reload the gateway.

**Actual behavior**
Python plugin initialization fails with `inspect.stack` related errors.

**Expected behavior**
The custom loader should have a fallback for this scenario.

**Comment by buger** [comment]
@matiasinsaurralde not sure if I understand the implication of this.

Does it mean that our plugins are broken on this envs?

**Comment by matiasinsaurralde** [comment]
@buger it seems to happen under specific scenarios in previous Python 3.4.x/3.5.x versions, I'm setting up environments to reproduce it. This is not ready for merge yet.
See the note [here](https://docs.python.org/3/library/inspect.html#inspect.stack), seems it was a breaking change 😞

**Comment by matiasinsaurralde** [comment]
I have updated this PR after several tests with Python 3.5.x/3.4.x/3.5.x. A fallback wasn't the best solution, instead we can rely on tuple indexes, they're available in versions that support named attributes too 🙌

**Comment by matiasinsaurralde** [comment]
Attached bundle for tests:
[inspectbundle.zip](https://github.com/TykTechnologies/tyk/files/3887808/inspectbundle.zip)

**Comment by ilijabojanovic** [comment]
@matiasinsaurralde 

I we tried on latest release-2.9 branch with python 3.6.8 installed 

i have this error:

```
[Nov 26 14:08:42]  INFO main: API bind on custom port:0
[Nov 26 14:08:42]  INFO main: ----> Fetching Bundle: inspectbundle.zip
[Nov 26 14:08:42]  INFO main: ----> Loading bundle: inspectbundle.zip
[Nov 26 14:08:42]  INFO main: ----> Verifying bundle: inspectbundle.zip
[Nov 26 14:08:42]  INFO main: ----> Bundle is valid, adding to spec: inspectbundle.zip
[Nov 26 14:08:42]  INFO coprocess: Python version '3.6' loaded
[Nov 26 14:08:42]  INFO python: Initializing dispatcher
[Nov 26 14:08:42]  INFO coprocess: Python dispatcher was initialized
[Nov 26 14:08:42]  INFO Checking security policy: Token api_id=af297065f17846815d03f18b1a22b1af api_name=test org_id=5dcaa92a9633d70d2397e557
[Nov 26 14:08:42]  INFO python: Loading module: 'af297065f17846815d03f18b1a22b1af_8f74f8ced5259fe4725e0c4238b94d15'
[Nov 26 14:08:42]  INFO gateway: API Loaded api_id=af297065f17846815d03f18b1a22b1af api_name=test org_id=5dcaa92a9633d70d2397e557 server_name=-- user_id=-- user_ip=--
[Nov 26 14:08:42]  INFO main: API bind on custom port:0
[Nov 26 14:08:42]  INFO Checking security policy: Open api_id=492ff5dcf86e400a62d3137a55458ca7 api_name=open org_id=5dcaa92a9633d70d2397e557
[Nov 26 14:08:42]  INFO gateway: API Loaded api_id=492ff5dcf86e400a62d3137a55458ca7 api_name=open org_id=5dcaa92a9633d70d2397e557 server_name=-- user_id=-- user_ip=--
[Nov 26 14:08:42]  INFO host-check-mgr: Loading uptime tests...
[Nov 26 14:08:42]  INFO main: Initialised API Definitions
[Nov 26 14:08:42]  INFO main: API reload complete
[Nov 26 14:08:42]  INFO main: reload: complete
[Nov 26 14:08:42]  INFO main: Initiating coprocess reload
[Nov 26 14:08:42]  INFO coprocess: Reloading middlewares
middleware.py is loaded!
[Nov 26 14:08:42] ERROR python: Middleware initialization error: module 'abc' has no attribute 'xyz'
[Nov 26 14:08:47] ERROR python: PyObjectCallObject failed
[Nov 26 14:08:47] ERROR Dispatch error api_id=af297065f17846815d03f18b1a22b1af api_name=test error=PyObjectCallObject failed mw=CoProcessMiddleware org_id=5dcaa92a9633d70d2397e557 origin=127.0.0.1 path=/test/get
[Nov 26 14:08:48] ERROR python: PyObjectCallObject failed
[Nov 26 14:08:48] ERROR Dispatch error api_id=af297065f17846815d03f18b1a22b1af api_name=test error=PyObjectCallObject failed mw=CoProcessMiddleware org_id=5dcaa92a9633d70d2397e557 origin=127.0.0.1 path=/test/get
```

**Comment by matiasinsaurralde** [comment]
Hi, this error is caused because the `abc` module exists in some Python installations, I've attached another sample that doesn't trigger the conflict, this should work fine.
[inspectbundle2.zip](https://github.com/TykTechnologies/tyk/files/3898023/inspectbundle2.zip)
