### ISSUE TITLE
I found a bug, to modify policy max quota  from 5000000 to 10, the quota_remaining is bigger 10

### ISSUE THREAD

**Issue by swan-go** [TykTechnologies/tyk#265]
curl -H "Authorization: xxxxxx" 127.0.0.1:10081/test-api/tyk/rate-limits/
`{"quota":{"quota_max":10,"quota_remaining":4999965,"quota_renews":1497170057},"rate_limit":{"requests":5,"per_unit":60}}`

**Comment by lonelycode** [comment]
You have to reset the quota too, there's a query param for that

**Comment by swan-go** [comment]
ok, thanks
