### ISSUE TITLE
Customize Tyk Auth Error Response Messages

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk#2652]
**Is your feature request related to a problem? Please describe.**
As a user of a front-end application, I am frustrated because when not logged in or using the wrong credentials, I don't get enough information in the error response from the API Gateway.

**Describe the solution you'd like**
As an API Owner, I'd like to be able to customize the error messages that Tyk will send.  I'd like to customize both the Body as well as the Headers.

scenario 1)
IE if my Auth field is missing, I want to redirect to my login screen
modify response code: from 401 to 302
**and/or** enter a URL redirect

scenario 2)
IE if my AUTH field is missing, I want to change the body from:
```javascript
{
"error": "Authorization field missing"
}
```
to:
```javascript
{
"error": "You're not logged in. Please try again."
}
```

I'd like to edit this via the Dashboard.  I'm not sure if this is best implemented at an API or Global level.

**Comment by l3ender** [comment]
For scenario 1, it'd be nice to be able to change the response code without adding a redirect.

**Comment by sedkis** [comment]
I agree - what I would hope to see is full customization =
1 input for response code
1 input for response body

**Comment by l3ender** [comment]
Is this now able to be accomplished with https://github.com/TykTechnologies/tyk/issues/2693 and https://github.com/TykTechnologies/tyk/pull/2815 (released in 2.9.3)?

If so, how can I change the error message for authentication errors (e.g. auth is configured for an API and no auth is provided by client)?

**Comment by sedkis** [comment]
Not exactly @l3ender, 
those other PRs let you manually override the response in middleware.  This Ticket is more about overriding the global error response, for example when a user hits an API and receives an authentication failure.  Does that make sense?

**Comment by l3ender** [comment]
Yes, thanks. Will continue to watch for this one to get implemented.

**Comment by letzya** [comment]
FYI @educroquet

**Comment by sedkis** [comment]
@l3ender  Partially implemented here:
https://github.com/TykTechnologies/tyk/issues/2652

**Comment by buger** [comment]
Also docs: https://tyk.io/docs/tyk-configuration-reference/tyk-gateway-configuration-options/#override_messages

**Comment by sedkis** [comment]
You can do it via:
https://tyk.io/docs/advanced-configuration/error-templates/

Example in tyk-demo
