### ISSUE TITLE
Dashboard RBAC via TIB (LDAP)

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk#2653]
Hello,

As a tyk dashboard admin user, I’d like to have the possibility to use sso via tib and ldap and make usage of my Active Directory groups membership so I can control the access to the dashboard (read, write the dashboard sections like certificates, users, groups....) example: if I’m a member of the ad group “api” I will just have access to the api section in the dashboard.

The group configuration could be passed via profiles.json (tib) 

Cc: @letzya 

Cheers, B.

**Comment by asoorm** [comment]
not stale

**Comment by letzya** [comment]
Added here https://github.com/TykTechnologies/tyk-identity-broker/pull/90 - https://github.com/TykTechnologies/tyk-identity-broker#user-group-id-support
