### ISSUE TITLE
API: creating a key request requires creation date

### ISSUE THREAD

**Issue by chlab** [TykTechnologies/tyk#266]
When POSTing to `/api/portal/requests` I have to supply a `date_created` field for it to be set correctly. Sending this:

```
{
"by_user": "xyz",
"for_plan": "abc"
}
```

results in a key request with:

> Submitted: 2015 years ago (0001/01/01 01:00)

Also, I can send a time in the future here as well, which will show up in the dashboard as "in 5 hours (2016/06/22 16:35)".

Also, quick question: I have to send my API requests as raw JSON data. Is there a reason why they can't be sent as form-data?

**Comment by lonelycode** [comment]
Nice catch, thanks for letting us know. 

> Also, quick question: I have to send my API requests as raw JSON data. Is there a reason why they can't be sent as form-data?

It's a JSON API, there is no support at all for form data and it's unlikely there ever will be.

**Comment by chlab** [comment]
Fair enough, makes sense :)

**Comment by mvdan** [comment]
@chlab since this concerns the dashboard, which isn't open source at the moment, I've moved this issue to its private repo. Closing this now, but we'll update this issue once it's fixed there.

Thanks!
