### ISSUE TITLE
Email used for SSO to dev portal should not be case sensitive

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2671]
Internal ticket: https://github.com/TykTechnologies/tyk-analytics/issues/1616

Branch/Environment

    Branch: [e.g. Master/Release/Stable/Feature branch]
    1.9
    Environment: [e.g. On-prem/Hybrid/MDCB]
    On prem

Describe the bug
From Bruno/IBM:
so, the db.getCollection('portal_developers') is case sensitive in this field sso_key
xxx
3 users
maybe it is better if u do in the code like lower case all strings and then save it

Reproduction steps

    set ldap profile in profile.json in tib for sso to the portal
    sso to the portal
    logout
    sso to the portal with the same email just change one letter to capital
    Try also from a different browser

Actual behavior
The dash should is case sensitive and can't find the existing user if one of the letters has changed to lower/upper case and as such creates a new user.

Expected behavior
The dash should be case insensitive and find the existing user rather than creating a new user per case
Screenshots/Video
There's a vid on the ticket

Browser/Os (please complete the following information):

    firefox and chrome

Additional context
The API used by tib: /api/portal/developers/ssokey

**Comment by christtyk** [comment]
need to keep open, effecting multiple users

**Comment by christtyk** [comment]
bump

**Comment by tbuchaillot** [comment]
PR: https://github.com/TykTechnologies/tyk-analytics/pull/2027

**Comment by andyo-tyk** [comment]
This was fixed in Tyk 3.0.2 / Tyk 3.1.1
