### ISSUE TITLE
tyk-python has been deprecated, provide backward compatibility

### ISSUE THREAD

**Issue by alephnull** [TykTechnologies/tyk#2675]
**Branch/Environment/Version: 2.9.1**
- Branch/Version: Release
- Environment: On-prem

**Describe the bug**
Prior to 2.9.1, we provided a `tyk-python` that supported Python plugins. This is no longer required as Tyk supports an external Python for plugins. 

Provide a backward compatibility layer to support calls to `tyk-python`.

**Logs (debug mode or log file):**
```
Log from console or from log file.
./entrypoint.sh: line 31: ./tyk-python: No such file or directory
                Command :   docker run -d \
 --name tyk_gateway_enhanced \
 --network tyk \
 -p 8080:8080 \
 -v $(pwd)/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf \
 -v $(pwd)/apps:/opt/tyk-gateway/apps \
   ssd-docker.apro.nbnco.net.au/tykio/enhanced-tyk-gateway:19.12.1
```

**Comment by excieve** [comment]
I think this issue belongs to https://github.com/TykTechnologies/tyk-gateway-docker/ (and its hybrid variant).

It should be enough to work around this in the `entrypoint.sh` by simply replacing `-python` with `` in the `$TYKLANG` var here:
https://github.com/TykTechnologies/tyk-gateway-docker/blob/master/entrypoint.sh#L27
