### ISSUE TITLE
Oauth /oauth/authorize-client returns invalid redirect_uri

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2679]
**Branch/Environment/Version**
master

**Describe the bug**
`/oauth/authorize-client` endpoint replaces `&` character with it's unicode character while returning redirect_uri

**Reproduction steps**

1. Import [APIDef](https://github.com/TykTechnologies/tyk/files/3867978/APIDef.txt)
2. Create oauth client
3. Send below curl command 
``` curl -X POST 'http://localhost:8181/test/tyk/oauth/authorize-client/?response_type=token&client_id={CLIENT_ID}&redirect_uri=http://httpbin.org' -H 'x-tyk-authorization: {TYK_SECRET}' ```

**Note**: Replace `CLIENT_ID` with clientID generated in step 2, and `TYK_SECRET` with your secret.

**Actual behavior**
redirect_uri will contain unicode of & instead of actual character.

**Expected behavior**
redirect_uri should not contain unicode

**Comment by maciejwojciechowski** [comment]
verified, current response looks like this

`{"access_token":"5dfa54d8fe238f624dc5c35590ba38fd9a764f90a40d8a2ef1c71af8","expires_in":3600,"redirect_to":"https://url.org#access_token=5dfa54d8fe238f624dc5c35590ba38fd9a764f90a40d8a2ef1c71af8&expires_in=3600&token_type=bearer","token_type":"bearer"}`
