### ISSUE TITLE
Remove dependency on Redis

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2681]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to proxy Redis though the Tyk because Tyk depends on the Redis itself. 

**Describe the solution you'd like**
It should be possible to start the gateway without Redis. 
In this case, all the functionality which depends on it, like Rate limits and quotas should be disabled. It also should handle the case when Redis connection not yet available, but specified in the config. In this case, the functionality should "auto-enable" once Redis is UP. 

It may require updating mechanisms on how the dashboard notifies Gateway about API and policy changes. The proposed solution for each gateway is to do polling and use HTTP cache headers (like E-Tag) to check if new changes are available.

**Comment by ilijabojanovic** [comment]
Verified

**Comment by letzya** [comment]
+1 from another client. They prefer not to use redis in testing env.

**Comment by buger** [comment]
@letzya how they going to test without Redis? It is possible only if they do not need Auth, and rates/quotas.
