### ISSUE TITLE
[TT-2371] - Allow Hybrid users to set slug as an empty string

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2683]
Client ticket 4154

Currently hybrid customers cannot define an empty API slug, when they are trying to use a custom domain the slug is appending at the end.

**Comment by christtyk** [comment]
Would like to keep open, client request

**Comment by christtyk** [comment]
bump

**Comment by andyo-tyk** [comment]
The slug parameter is applicable only to the legacy Tyk Cloud, we do not have plans to develop this capability on that platform, so I am closing this issue.
