### ISSUE TITLE
Allow redirecting to Tyk API using API name when looping

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#2686]
**Is your feature request related to a problem? Please describe.**

Currently in the case of redirecting internally to another tyk api we do it by targeting `tyk://{APIID}/path`

This works fine but apiid is not a human readable format and using api names as an alias for the apiid would be much more useable.

**Describe the solution you'd like**

If i have an internal api called `internalAPI1` i should be able to loop back to it using URL rewrites by targeting `tyk://internalAPI1/path`

**Comment by buger** [comment]
It actually already supported, this function https://github.com/TykTechnologies/tyk/blob/master/gateway/api_loader.go#L558

If it's not, probably some bug.

**Comment by joshblakeley** [comment]
I'll retest but i definitely could not get it to work earlier - do we have a unit test case for it?

**Comment by joshblakeley** [comment]
Tested and working fine on 2.9.1 branch so closing this
