### ISSUE TITLE
Make ReturnOverrides more flexible when returning errors

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2693]
**Is your feature request related to a problem? Please describe.**

1. Currently when using rich plugins, it's possible to override the response by using `ReturnOverrides`, this structure takes two parameters: HTTP status code and body.

2. When the HTTP status code is higher than 400 and a body like "test" is used, the generated response body looks like this: `{"error": "test"}`.

3. It would be more flexible if we can allow the user to fully customize this behavior in error scenarios. We could keep the current functionality by default (and for compatibility purposes) and introduce a flag like `disable_json_error` or a similar name.
When this flag is set to true, with the same parameters specified in 2) we would get response body like "test".

4. This could be useful for cases where it's required to fully customize the error output.
When using status codes lower than 400 we don't really add any JSON wrapper, so the user already has full flexibility in this case. 

**Describe the solution you'd like**
The easiest solution would be to add a flag to the `ReturnOverrides` data structure. This will help us with compatibility too.

**Comment by sedkis** [comment]
What about also letting us choose the return Code?

**Comment by buger** [comment]
It is already possible and part of  `ReturnOverrides` structure

**Comment by furkansenharputlu** [comment]
Fixed by https://github.com/TykTechnologies/tyk/pull/2731

**Comment by buger** [comment]
I added one more fix to this, details inside this PR https://github.com/TykTechnologies/tyk/pull/2815
