### ISSUE TITLE
Gateway does not trigger quota email notifications

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2694]
**Branch/Environment/Version**
- Branch/Version: Release-2.9
- Environment: All

**Describe the bug**
Related to:
https://github.com/TykTechnologies/tyk-analytics/issues/1013

On release 2.8.x we added feature which triggers email notification to developer if quota usage reach defied values in gateway config. On release 2.9 that feature does not work 

**Reproduction steps**
1. In gateway config set monitor options:
```
"monitor": {
        "enable_trigger_monitors": true,
        "configuration": {
            "method": "POST",
            "target_path": "",
            "template_path": "./templates/monitor_template.json",
            "header_map": null,
            "event_timeout": 0
        },
        "global_trigger_limit": 50,
        "monitor_user_keys": true,
        "monitor_org_keys": true
```
2. Add protected api
3. Create policy with some quota and add protected api
4. As portal developer request access to that api and generate token
5. Generate traffic to protected api with that token

**Actual behavior**
Email is not triggered to portal developer email.

**Expected behavior**
If we reach 50% of quota we should got email.

**Screenshots/Video**
We should got this email:
<img width="841" alt="Screenshot 2019-11-25 at 22 43 22" src="https://user-images.githubusercontent.com/8557292/69580950-de490700-0fd5-11ea-9c6d-90072ffd4956.png">

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by furkansenharputlu** [comment]
**NOTE:** I tried with `2.9`, it is working in my local. We had a call with @ilijabojanovic, he and @maciejwojciechowski will try this again.

**Comment by maciejwojciechowski** [comment]
It's also working on my local with basic setup.

**Comment by ilijabojanovic** [comment]
Not bug
