### ISSUE TITLE
Importing Swagger spec through Tyk REST API - more documentation needed

### ISSUE THREAD

**Issue by fecanen** [TykTechnologies/tyk#270]
When looking into automatically importing swagger-spec files into Tyk we found that beyond the API:s specified on this page

https://tyk.io/docs/tyk-dashboard-v1-0/dashboard-api/api-definitions/

 we could send REST API calls to the Tyk path api/import/swagger for importing swagger-spec-files. Could you please extend your documentation regarding this to avoid future confusion?

**Comment by mvdan** [comment]
We have updated and improved the page, and posted it to the new docs site: https://tyk.io/docs/configure/import-apis/

Thanks for the patience!
