### ISSUE TITLE
Tyk API allows key request for invalid policy

### ISSUE THREAD

**Issue by chlab** [TykTechnologies/tyk#272]
When I send a key request for an invalid policy, the key request is still created, but cannot be approved.

```
POST https://admin.cloud.tyk.io/api/portal/requests

{
    "by_user": "<a-user-id>",
    "for_plan": "asdfasdf",
    "date_created": "2016-07-15T12:18:16+00:00"
}

>>>

{
  "Status": "OK",
  "Message": "5788b8748d416e0001000071",
  "Meta": null
}
```

Not really a problem for me but maybe something you want to catch.

Cheers

**Comment by lonelycode** [comment]
Thanks for the heads up! We'll log it and see if we can't do something about that :-)

**Comment by dividinglimits** [comment]
What am I missing here @lonelycode? The reporter mentions using "for_plan" in the request, but that's not defined within the API context document found at https://tyk.io/docs/tyk-api-gateway-v-2-0/api-management/api-definition-objects/

**Comment by lonelycode** [comment]
@dividinglimits The docs are a little out of date, we're in the middle of a re-write. the `for_plan` key request setting is part of a v2 portal catalogue object key request.

**Comment by mvdan** [comment]
As with #266, I've moved this to the dashboard private repo.

Thanks!
