### ISSUE TITLE
Wrong meta data set when creating OAuth access token/code

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2724]
**Branch/Environment/Version**
- master

**Describe the bug**
When request is sent to `/tyk/oauth/authorize-client/` with key_rules parameter, instead of using meta data of `key_rules` argument, meta data of OAuth client is used while generating token. 

**Reproduction steps**

1. Create API with OAuth2 auth type
2. Create Oauth Client with some custom metadata
3. Send request to `/{ListenPath}/tyk/oauth/authorize-client` with key_rules parameter. 

**Actual behavior**
Instead of setting meta data from `key_rules`, meta_data of OAuth client is set in the generated Access token. If meta data is not set for OAuth client, it works correctly.

**Expected behavior**
meta_data of `key_rules` argument should be used.

**Comment by christtyk** [comment]
ssg

**Comment by matiasinsaurralde** [comment]
I've been looking into this, when metadata is set in `key_values` but the OAuth client doesn't specify any metadata, the following access token key is created in Redis:
`
"{\"Client\":{\"id\":\"1009314367d843d7badb9b2dd2e43878\",\"secret\":\"NTkxNzVmNzgtMDg0Mi00MTFhLTlmNzgtMjA0MmUwYTMyZGE4\",\"redirecturi\":\"http://localhost/redirect\",\"meta_data\":{},\"policyid\":\"5e4b0d054ea46153f0bcfd5b\",\"description\":\"\"},\"AccessToken\":\"5a79019d4ea461cdd0c77480a740d914247e4e5aa266bd99c1d59f85\",\"RefreshToken\":\"\",\"ExpiresIn\":3600,\"Scope\":\"\",\"RedirectUri\":\"http://localhost/redirect\",\"CreatedAt\":\"2020-02-18T00:47:55.362826+02:00\",\"UserData\":\"{\\\"org_id\\\":\\\"5a79019d4ea461cdd0c77480\\\", \\\"api_id\\\": \\\"e5e4ad3169c548464fecad51d8f30a9f\\\", \\\"meta_data\\\": {\\\"validkey\\\": \\\"somevalue\\\"}}\"}"
`
From our discussion with @komalsukhani we expect `meta_data` under `Client` to be populated in this scenario.

**Comment by matiasinsaurralde** [comment]
An update on this: I've been able to adjust the way we store access tokens in order to include the proper metadata. However the load method, called `LoadAccess` will need to be tweaked too, as we use `osin.Client` which doesn't include any metadata field. This structure is used when the access token is read from Redis, the simplest fix would be something like this, in the `osin` repo:
```diff
--- a/vendor/github.com/lonelycode/osin/client.go
+++ b/vendor/github.com/lonelycode/osin/client.go
@@ -24,6 +24,7 @@ type DefaultClient struct {
        Secret      string
        RedirectUri string
        UserData    interface{} `json:",omitempty"`
+       MetaData interface{} `json:"meta_data,omitempty"`
 }
```

**Comment by maciejwojciechowski** [comment]
verified
