### ISSUE TITLE
connection leak when gateway TLS enabled

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2739]
**Branch/Environment/Version**

all

**Describe the bug**

When gateway TLS is enabled `http_server_options.use_ssl: true`, and a hot-reload is triggered - There is a connection leak.

**Reproduction steps**

Start a gateway with TLS enabled

`go install && tyk 2>&1 >/dev/null | grep "API reload complete"`
`watch 'lsof -c tyk | wc -l'`
`for i in {1..100}; do curl https://localhost:8080/tyk/reload -H 'x-tyk-authorization: foo' -tlsv1.3 -k; sleep 1; done;`

**Actual behavior**

The watcher will show a connection leak at a rate of 1 per hot reload.

**Expected behavior**

Connections should be re-used

**Additional context**

When hot reloading, the gateway sends a request to the Dashboard service to obtain the latest policies.

For every call, the gateway initialises a new client, but we don't re-use the transport - we create a new one each time.

https://github.com/TykTechnologies/tyk/blob/master/gateway/dashboard_register.go#L44-L59

Transport should be re-used, rather than a new one created each time.

https://github.com/golang/go/blob/master/src/net/http/transport.go#L63-L69

**Comment by buger** [comment]
You probably mean when dashboard TLS enabled?

**Comment by asoorm** [comment]
no - gateway tls

**Comment by asoorm** [comment]
not stale

**Comment by asoorm** [comment]
Actually, it looks like this issue has been fixed in master and release 2.9. @ilijabojanovic @buger  to confirm. As I can't find matching PR or alternative issue.

**Comment by christtyk** [comment]
@ilijabojanovic can you confirm?

**Comment by christtyk** [comment]
@ilijabojanovic @maciejwojciechowski I need to go back to a client on this one, can you confirm if it's fixed or not pls?

**Comment by ilijabojanovic** [comment]
@christtyk This issue was fixed as part of https://github.com/TykTechnologies/tyk/issues/2831
