### ISSUE TITLE
[TT-2362] - Add environment wide Global header Injection

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk#2740]
**Is your feature request related to a problem? Please describe.**
When Tyk is acting as an ingress, similar to nginx, I want to be able to inject headers at a global level, instead of per API level.

**Describe the solution you'd like**
I want a solution that allows me to inject headers globally, across all requests that traverse through Tyk

**Comment by Bouwdie** [comment]
Related to: https://github.com/TykTechnologies/tyk/issues/2453

**Comment by sedkis** [comment]
I'm not sure that it is.  I believe #2453 refers to API level header response modification, where as this refers to across all of Tyk

**Comment by sedkis** [comment]
Not stale

**Comment by andyo-tyk** [comment]
Closing as this is not currently on our roadmap, but we may return to it later if there is renewed interest from users.
