### ISSUE TITLE
[TT-2361 ] - Global Level Custom Middleware

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk#2741]
**Is your feature request related to a problem? Please describe.**
- If I want to insert global level behaviour, such as #2740, then I can write my own custom middleware and inject it into Tyk.

I would want this at both the request/response level.

**Describe the solution you'd like**
A middleware that will get run as part of every request that comes into Tyk

**Comment by Bouwdie** [comment]
I think this would be massively powerful for companies that have global policies that need to be applied to all traffic in and out of their environments. Security header best-practices as defined in OWASP: https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers are great candidates to solve on a global level. :taco:

**Comment by sedkis** [comment]
I'm wondering also if it would make sense to have the same level of customization with current middleware as to where to place it.

Global middleware injection that will get run in the pre, post, or post-auth.
Global custom auth middleware also makes sense to me

**Comment by sedkis** [comment]
This is a very powerful value add

**Comment by andyo-tyk** [comment]
We don't have support for global custom middleware as described, however with plugin bundles (https://tyk.io/docs/plugins/how-to-serve-plugins/plugin-bundles/) you can easily share custom middleware (plugins) across your APIs.
