### ISSUE TITLE
Use headers to be part of the cache key

### ISSUE THREAD

**Issue by DimaNevelev** [TykTechnologies/tyk#2753]
**Is your feature request related to a problem? Please describe.**
We are working in a multi-tenancy environment. The tenant is defined by a custom header.
We want the ability to manage the cache per tenant.

**Describe the solution you'd like**
We would like to have a field per API that can be populated by header names.
The headers values should be part of the cache key so in case of changed value a new cache key will be generated.

**Describe alternatives you've considered**
None

**Additional context**
Nope

**Comment by ilijabojanovic** [comment]
@buger 
On latest release-1.9 branch

On endpoint designer we can only enable cache `get` method, if we add `post` or `put` dashboard api returning error:

```
[Mar  5 11:17:02] ERROR Couldn't unmarshal API data: json: cannot unmarshal object into Go struct field ExtendedPathsSet.api_definition.version_data.versions.extended_paths.cache of type string
```

Video:
![cache](https://user-images.githubusercontent.com/8557292/75973443-7314a800-5ed5-11ea-9c55-4bc9a83687e8.gif)

**Comment by DimaNevelev** [comment]
@ilijabojanovic and @buger ,
I seem to me that this is somthing related to the dashboard, i.e. I can't help you with this. 
Am I right?

**Comment by buger** [comment]
@ilijabojanovic can't replicate it. So far works for me. Also, your video does not show error as well. 
If you still can replicate it, pick me for a call.

**Comment by ilijabojanovic** [comment]
Done
