### ISSUE TITLE
UX: Enhancements to the Tyk Gateway Admin API

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2758]
Given I have a keyless API definition, And I want to protect it with an Auth-Token:

From
```
{
  "name": "httpbin",
  "api_id": "httpbin",
  "use_keyless": true,
  "active": true,
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default"
      }
    }
  },
  "proxy": {
    "listen_path": "/httpbin",
    "target_url": "http://httpbin.org/",
    "strip_listen_path": true
  }
}
```

To
```
{
  "name": "httpbin",
  "api_id": "httpbin",
  "use_keyless": false, <--------------------- FIELD CHANGED
  "auth": { <--------------------------------- OBJECT INSERTED
      "auth_header_name": "Authorization"
  }
  "active": true,
  "version_data": {
    "not_versioned": true,
    "versions": {
      "Default": {
        "name": "Default"
      }
    }
  },
  "proxy": {
    "listen_path": "/httpbin",
    "target_url": "http://httpbin.org/",
    "strip_listen_path": true
  }
}
```

The steps I would need to take are as follows:

1. I would currently need to GET the API definition
2. I would need to modify the API definition as per above
3. I would need to PUT the api definition back
4. I would need to hot reload the gateway

Steps 1, 2 & 3 This can be significantly simplified to a single step by accepting a PATCH request

```
curl http://localhost:8080/tyk/apis/httpbin -H 'x-tyk-authorization: foo' -X PATCH '{"use_keyless":false,"auth":{"auth_header_name":"Authorization"}}'
```

I am now able to update the specific fields which I want to from that API definition object.

To simplify this even further, If we make the API definition RESTful:

1. `curl http://localhost:8080/tyk/apis/httpbin -H 'x-tyk-authorization: foo' -X PATCH -d '{"use_keyless":false}'`
2. `curl http://localhost:8080/tyk/apis/httpbin/auth -H 'x-tyk-authorization: foo' -X POST -d '{"auth_header_name":"Authorization"}'`
3. Hot Reload

We can further simplify by accepting form data content type

1. `curl http://localhost:8080/tyk/apis/httpbin -H 'x-tyk-authorization: foo' -X PATCH -F use_keyless=false`

2-a. `curl http://localhost:8080/tyk/apis/httpbin/auth -H 'x-tyk-authorization: foo' -X PATCH -F auth_header_name=Authorization`

or 2-b. `curl http://localhost:8080/tyk/apis/httpbin -H 'x-tyk-authorization: foo' -X PATCH -F auth.auth_header_name=Authorization`

3. Hot Reload

**Comment by lonelycode** [comment]
Like this, but needs to be part of a design thinking proposal and capability where we are looking at the entire API. Starting at the solution end here :-)
