### ISSUE TITLE
Extend advanced cache to all of the methods

### ISSUE THREAD

**Issue by DimaNevelev** [TykTechnologies/tyk#2763]
**Is your feature request related to a problem? Please describe.**
We are doing authorization in each microservice.
We want to reduce the noise created by unauthorized requests by caching them in the gateway layer for all of the methods, not only for safe requests.

**Describe the solution you'd like**
We want the ability to cache all the methods, not only safe.
We also want to have CacheOnlyResponseCodes field per method. It should override the main cache configuration.

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by buger** [comment]
So, we have 3 changes in this ticket:
- cache plugin on API level has new cache_by_headers field, to use header values as part of cache key
- now you can configure cache_response_codes on cache plugin level, in addition to api level
- fixed bug when “CacheAllSafeRequests” is set, but method is “PUT” (it will allow caching it now). Before this PR, only “POST” request was considered as dangerous action, now all except HEAD/GET/OPTIONS.
