### ISSUE TITLE
Add url rewrite domain trigger

### ISSUE THREAD

**Issue by DimaNevelev** [TykTechnologies/tyk#2771]
**Is your feature request related to a problem? Please describe.**
We are using multiple domains and we want to use the domain in our target path.
For example:
We want the url http://SOME-UUID.domain.com to be redircted to http://internal-domain.com/SOME-UUID.
A trigger seems like a good way acchive this behavior (a very similar behavior is the context trigger).
Here is an desired trigger: 
```
{ 
  "path":"/",
  "method":"GET",
  "match_pattern":"/",
  "rewrite_to":"",
  "triggers":[ 
    { 
      "on":"all",
      "options":{ 
        "domain_matches":{ 
          "match_rx":"(.*).domain.com",
          "reverse":false
        }
      },
      "rewrite_to":"http://internal-domain.com/$tyk_context.trigger-0-domain-0-0"
    }
  ],
  "MatchRegexp":null
}
```

**Comment by buger** [comment]
I think you can already do the similar thing with $tyk_context.header_Host variable. 
Can you check that?

**Comment by DimaNevelev** [comment]
$tyk_context.headers_Host will provide you the full host. 
We have a use-case where only part of the host is needed.
I used this in the tests: the host header is "127.0.0.1:RANDOM_PORT" I removed the port using the following trigger:
```
[{
	"path": "/",
	"method": "GET",
	"match_pattern": "/",
	"rewrite_to": "",
	"triggers": [{
		"on": "all",
		"options": {
			"domain_matches": {
				"match_rx": "((.*):.*)",
				"reverse": false
				}
			},
			"rewrite_to": "/$tyk_context.trigger-0-domain-0-1/new_url"
		}
	],
	"MatchRegexp": null
}]
```
and now the uri will always be "/127.0.0.1/new_url"

**Comment by christtyk** [comment]
Thanks Dima, we'll check it out

**Comment by DimaNevelev** [comment]
BTW, I did a PR for this...
https://github.com/TykTechnologies/tyk/pull/2772
