### ISSUE TITLE
SSL Cert: Validate hostname against Common Name

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2774]
**Is your feature request related to a problem? Please describe.**
While validating hostname, Go now ignores the Common Name if is a SAN is found. But according to RFC, Common Name should be used for host name validation if SAN is not set to domain name.

**Describe the solution you'd like**
Provide a option to validate hostname against Common Name instead of SAN field.

**Comment by furkansenharputlu** [comment]
Fixed by #2644
