### ISSUE TITLE
Request signing middleware does not strip listen path 

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2779]
**Branch/Environment/Version**
- Branch/Version: master/release-2.9

**Describe the bug**
When we sign a request to the upstream, we must use the exact final path/method. 
However, right now, if Tyk API has listen path, it does not get stripped out, so request signature is generated with "ListenPath + Path", while it should be "Path" (only if "Strip listen path" is turned on).

Currently, there is a workaround if you are using URL rewrite, it uses the right path. And current tests are passing only because they use URL rewrite.

**Reproduction steps**
Create API with non-empty listen path, enable request signing (no matter if HMAC or RSA). Sent request to the upstream, and see gateway debug logs for  "Generated sig string: ..." message. Signature in the gateway will contain listen path, even if listen path stripping is enabled.

**Comment by christtyk** [comment]
@buger do we intend to add to .3?

**Comment by maciejwojciechowski** [comment]
verified

**Comment by buger** [comment]
We found a bug when listen path contains a trailing slash, it removes slash prefix from the signing URL.
