### ISSUE TITLE
[TT-1963] - Disabling a policy disables the key - issue with multiple policies for a key

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2784]
**Branch/Environment/Version**

all

**Describe the bug**

A key has access to 2 policies.
Deactivate one policy, and access to the other policy is also disabled.

https://github.com/TykTechnologies/tyk/blob/master/gateway/middleware.go#L468-L472

**Expected behavior**

Disabling one policy, should not completely disable the session token, only access to the services protected by the policy. especially if more than one policy is applied to the key.

**Comment by asoorm** [comment]
bump

**Comment by christtyk** [comment]
do you know if it's still valid @asoorm

**Comment by andyo-tyk** [comment]
This will be fixed in Tyk 5.0.4 and 5.1.1.
