### ISSUE TITLE
JWKs URL is assumed to be a PEM file

### ISSUE THREAD

**Issue by alephnull** [TykTechnologies/tyk#2790]
**Branch/Environment/Version**
- Branch/Version: 2.9.2
- Environment: On-prem

**Describe the bug**
When attempting to setup JWK as per https://tyk.io/docs/security/your-apis/json-web-tokens/#option-3-dynamic-public-key-rotation-using-jwks, it is not clear where the URL is to be supplied in the UI.

Once the URL is made available in base64 form in `jwt_source`, the behaviour is to assume it is a PEM file even when it is DER. See https://community.tyk.io/t/jwt-jwks-error-key-must-be-pem-encoded-pkcs1-or-pkcs8-private-key/3150 for more details.

**Comment by christtyk** [comment]
Need to keep open, effecting multiple users.

**Comment by maciejwojciechowski** [comment]
verified points 2 and 3
for 3 - we are missing UI changes. I created ticket https://github.com/TykTechnologies/tyk-analytics-ui/issues/1842
