### ISSUE TITLE
[TT-1964] - Show API Quota usage in the developer portal

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2792]
**Is your feature request related to a problem? Please describe.**
A clients API customer is unable to see what % of their quota is used in the UI, only via response headers. The dashboard tends to be used by business users who won't see response headers so aren't seeing this information. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/51364553/71992595-85ec6280-322d-11ea-9754-9aebab768718.png)

**Describe alternatives you've considered**
Using the response headers, but not suitable for business users.

**Comment by christtyk** [comment]
not stale

**Comment by andyo-tyk** [comment]
Closing - we have no plan to develop this feature further.
