### ISSUE TITLE
[TT-1968] - Allow configure HTTP signature middleware header

### ISSUE THREAD

**Issue by vesko-tyk** [TykTechnologies/tyk#2796]
**Branch/Environment/Version**
- Branch/Version: 2.9.2
- Environment: On-prem

**Describe the bug**
At the moment we support HTTP signature to the upstream, so it can be validated if request is sent from Tyk or not and right now it's with fixed header name: Authorization.
This is causing issues when using JWT auth method in conjunction with HTTP Signature, so to solve this we should make possible to configure header name for http signature middleware.

**Comment by andyo-tyk** [comment]
Closing as this is a feature request, not a bug.
