### ISSUE TITLE
Alternative analytics data store

### ISSUE THREAD

**Issue by krystalcode** [TykTechnologies/tyk#280]
I'm interested in exploring Tyk. I understand that it requires Mongo for its analytics and dashboard components. I'm already storing various monitoring and analytics data in Elastic Search and I would rather have API gateway's data sent there as well.

I read that it is actually possible to deploy Tyk without Mongo (losing the analytics and dashboard components).

1. I am wondering if there is a guide on how to do that e.g. is it a matter of configuration or is there something else I need to do for disabling analytics?

2. What is the best way to retrieve analytics and send them to Elastic Search? Do I need to write a plugin (https://tyk.io/docs/tyk-api-gateway-v-2-0/javascript-plugins/) and does the JavaScript plugin system support what is needed to retrieve logs? Or can I retrieve logs from files on the disk?

**Comment by matiasinsaurralde** [comment]
1. When you perform a standard Tyk Community Edition setup, you only need Redis, check [this guide](https://tyk.io/docs/tyk-api-gateway-v-2-0/installation-options-setup/install-tyk-on-ubuntu/).

2. Have you read about Tyk-Pump? It could be useful for what you're trying to achieve, please read [here](https://tyk.io/docs/tyk-pump/). Also, there's a sample showing [ElasticSearch pump setup](https://tyk.io/docs/tyk-pump/configuration/).

Regards!

**Comment by krystalcode** [comment]
Thank you for the response, these docs seem to be what I was looking for!
