### ISSUE TITLE
Redis-cluster: Edit/Update oauth client duplicates oauth client in redis

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2804]
**Branch/Environment/Version**
- Branch/Version: Master/Release-2.9
- Environment: All

**Describe the bug**
When gateway is connected to redis cluster, edit or update of oauth client duplicates entry redis database

**Reproduction steps**

1. Start gateway in redis cluster mode
2. Over dashboard create api with oauth auth
3. Create oauth client
4. Open auth client page and add new metadata filed or update policy
5. Click update

**Actual behavior**
We have two oauth clients on page and also in database

**Expected behavior**
Edit or update existing oauth client should not create new entry in database

**Screenshots/Video**
<img width="1895" alt="Screenshot 2020-01-15 at 14 07 09" src="https://user-images.githubusercontent.com/8557292/72436278-5ba42300-37a0-11ea-85c8-107f10cfc3ef.png">

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by maciejwojciechowski** [comment]
verified
