### ISSUE TITLE
tyk target url in the https when do I have to do is cacert???????

### ISSUE THREAD

**Issue by onimusa81** [TykTechnologies/tyk#282]
target : curl -X POST -u "admin:admin" --cacert cert.cer https://localhost

tyk : ???????? curl -X POST -u "admin:admin" --cacert cert.cer http://tyk.apigateway????????

What should I do?

**Comment by james-tyk** [comment]
Hi @onimusa81 - you can get support and advice on tyk from the community at https://community.tyk.io/

We like to keep Github as the place for contributing to the project or reporting bugs. For everything else we have the community forums and the documentation at tyk.io

Hope that helps.
