### ISSUE TITLE
[TT-1972] - Inefficient Cross-Site Request Forgery Protection

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2828]
**Branch/Environment/Version**
On-Prem 2.9

The Portal application's implementation of Cross-Site Request Forgery (CSRF) protection was incomplete. CSRF can allow an attacker to perform actions as another user by enticing them to access a malicious link. For example, an attacker would be able to leverage this vulnerability to change the victim’s password (see finding 22946-2-07 Account Password Change Does Not Verify User Authenticity). Although the application implemented tokens to prevent CSRF, these did not provide efficient protection as they are stored within the browser cookies. This means that the CSRF tokens are sent with every request, and thus provide no additional protection. Furthermore, the application uses a single CSRF token for the duration of the user's session.

Potential Solution:

CSRF token should be sent from the front end each time, and should be publicly available. The key here is to verify that CSRF token generated by server side is the same as sent by the client. We can think about moving CSRF token to HTTP Only cookie.  Regarding the save value, we can definitely generate unique token on each page reload.

**Comment by christtyk** [comment]
@buger client is asking us to propose a different solution as they feel it doesn't represent a fix, can you review and suggest at all?

**Comment by christtyk** [comment]
bump

**Comment by andyo-tyk** [comment]
Closing as stale - please reopen if this is still a concern in latest Tyk.
