### ISSUE TITLE
Misuse of singleflight in RedisCacheMiddleware

### ISSUE THREAD

**Issue by gernest** [TykTechnologies/tyk#2838]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB]

**Describe the bug**
In . `RedisCacheMiddleware` we have this code snippet for retrieving  cached keys

```
		retBlob, err = m.CacheStore.GetKey(key)
		v, sfErr, _ := m.singleFlight.Do(key, func() (interface{}, error) {
			return m.CacheStore.GetKey(key)
		})
		retBlob = v.(string)
		err = sfErr
```

The  line 
```
		retBlob, err = m.CacheStore.GetKey(key)
```

doesn't make any sense to be there as it destroys the whole purpose of single flight. This will result in hitting redis on every call.

*Reproduction steps**
n/a

**Actual behavior**
Uses both, direct call and singleflight to retrieve the same key

**Expected behavior**
Only using single flight

**Screenshots/Video**
n/a
**Logs (debug mode or log file):**
n/a
**Configuration (tyk config file):**
n/a
**Additional context**
n/a

**Comment by ilijabojanovic** [comment]
Verified
