### ISSUE TITLE
Logs spamming with oAuth2 API

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2854]
**Branch/Environment/Version**
- Branch/Version: master/release-2.9

**Describe the bug**
If you create API with oAuth mode set, on every token generation, you will get 4 log lines during few seconds, like this:
> Request failed, trying again in 10s. Error was: ..
> Request failed, trying again in 10s. Error was: ..
> Request failed, trying again in 10s. Error was: ..
> Too many notification attempts, aborting.

In fact, it generates so many logs that our Sentry is overflown. 

For oAuth flow we have notifications functionality, which is optional, but allows you to send webhook once token is generated. See here https://tyk.io/docs/basic-config-and-security/security/your-apis/oauth-2-0/#notifications

It is configured by setting the following section to API definition:
```json
"notifications": {
    "oauth_on_keychange_url": "...",
    "shared_secret": "secret"
}
```

The issue itself happens that we try to make http requests even if oauth_on_keychange_url is not set.

**Expected behavior**
If oauth_on_keychange_url empty (default), do not run notifications.

**Comment by ilijabojanovic** [comment]
Verified
