### ISSUE TITLE
Tyk gateway/node crashing - "Fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by viklas** [TykTechnologies/tyk#287]
I've run into a problem with the latest release (v2.2) which seems to be related with handling of some requests, specifically where the OpenID Connect authorization token is invalid. Not sure how to reproduce the problem exactly, but have seen it a lot in the last few days. Note, this is happening by accident...some bad front-end code in a dev environment is issuing calls to the API before the authentication (via Auth0) has completed....that will be fixed soon but thought I should raise the issue anyway, given it crashes the app.

Output from the docker container is in this gist: https://gist.github.com/viklas/c4b1f17138b9b4cbe4c82a08d4e40c02

The error being reported in the log is "fatal error: concurrent map writes". 

Overcoming this at the moment by starting the docker container again (container stops when app crashes).

**Comment by lonelycode** [comment]
We literally pushed a patch for this release today so if you update your docker container or update your install you'll find that the concurrency issues are gone and we've also fixed a JWK cache back-fill bug.

**Comment by lonelycode** [comment]
(V2.2.0.3 to be exact)

**Comment by viklas** [comment]
Awesome...love your work Martin! I'll grab the latest version and confirm that my crap code is no longer breaking your awesome app.

**Comment by viklas** [comment]
Can confirm, fix seems to have stabilised it. Can't seem to crash it now. I'll re-open the issue if I run into the same problem again. Thanks again for being so responsive!
