### ISSUE TITLE
[TT-1977] - Prepare for TLSv1.3 by default in Go 1.13

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk#2886]
TLSv1.3 support is introduced in Go 1.12 as opt-in, but is an opt-out in Go 1.13, being enabled by default. In Go 1.14 this can't be opted out at all. Tests are currently failing when executed with Go 1.13.

According to [release notes](https://golang.org/doc/go1.12#tls_1_3), there are several issues that affect the gateway currently:

> Note that even though TLS 1.3 is backwards compatible with previous versions, certain legacy systems might not work correctly when attempting to negotiate it. RSA certificate keys too small to be secure (including 512-bit keys) will not work with TLS 1.3.

Our tests [are currently using 512-bit keys](https://github.com/TykTechnologies/tyk/blob/89c4ad4b366dfb562148141c91db6d7ceb133f29/gateway/cert_test.go#L31), this will need to be changed to at least 1024 bit. This also needs to be mentioned in the release notes once we start building official binaries with Go 1.13.

> TLS 1.3 cipher suites are not configurable. All supported cipher suites are safe, and if PreferServerCipherSuites is set in Config the preference order is based on the available hardware. 

There are tests that check whether configured cipher suites have any effect on the choice of them in the handshake. This needs to be limited by TLSv1.2 max version in the test client.

Release notes and documentation needs to mention that [the relevant option](https://github.com/TykTechnologies/tyk/blob/89c4ad4b366dfb562148141c91db6d7ceb133f29/config/config.go#L195) has no effect starting with TLSv1.3 (which will be negotiated if client supports it).

> In TLS 1.3 the client is the last one to speak in the handshake, so if it causes an error to occur on the server, it will be returned on the client by the first Read, not by Handshake. For example, that will be the case if the server rejects the client certificate. Similarly, session tickets are now post-handshake messages, so are only received by the client upon its first Read.

This could potentially be an issue too, where gateway is a client to an upstream or in tests while handling errors. Needs to be checked.

TLSv1.3 support can be disabled at runtime with `GODEBUG="tls13=0"` env var (but probably shouldn't be unless there's a compatibility issue in a specific use case).

**Comment by excieve** [comment]
Not stale.

**Comment by excieve** [comment]
@buger @gregdelhon Doesn't look like this has been migrated to Jira, but it's really important.

**Comment by christtyk** [comment]
@excieve is it still valid? I can move to jira now

**Comment by excieve** [comment]
@christtyk I believe this is going with Go 1.15 builds starting in version 3.2.0. So this should wrap into the relevant Jira ticket if there is one.

**Comment by buger** [comment]
Default should be 1.2, and thats how it is implemented in current Tyk implementation. 
1.3 is not compatible with 1.2 in many ways. The major differences is that almost every enterprise using TLS have a list of whitelisted TLS ciphers, and in 1.3 there is no way to whitelist them: it automatically picks list of most secure ciphers. I do not know enterprises from our clients where 1.3 is allowed.

**Comment by excieve** [comment]
@buger This ticket was about 1.3 support being enabled by default starting with Go 1.13 and Tyk failing tests on that. I suppose since we're able to build with Go 1.15 now this shouldn't be an issue anymore?

**Comment by buger** [comment]
Yes, it is fixed
