### ISSUE TITLE
Should API configuration tags be added to the analitics tags?

### ISSUE THREAD

**Issue by Roberttmoon** [TykTechnologies/tyk#2890]
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: all

**Describe the bug**
To be honest I don't know if this is a bug or an implementation detail that was not documented.

In the full configuration for a proxy there is a `[]strings` for tags as is documented [here](https://tyk.io/docs/tyk-rest-api/api-definition-objects/). These tags are not appended to Tags on the analytics struct. Whether the tags are intentionally left out of the analytics or not, I feel that the tags documentation should mention this. I also believe that it would be incredibly useful to be able to add user configured Tags to each proxy.

**Actual behavior**
The user configured tags from the API config are not added to the analytics struct. Also, it seems like the API config tags are never used in the code.

**Expected behavior**
Tags on the Proxy Definition propagate to the analytics.

**Additional context**
It looks like this problem could be solved by adding the following line to the instantiation of the [analytics struct](https://github.com/TykTechnologies/tyk/blob/master/gateway/proxy_muxer.go#L212-L225):
```
record := AnalyticsRecord{
	Network:      spec.network.Flush(),
	Day:          t.Day(),
	Month:        t.Month(),
	Year:         t.Year(),
	Hour:         t.Hour(),
	ResponseCode: -1,
	TimeStamp:    t,
	APIName:      spec.Name,
	APIID:        spec.APIID,
	OrgID:        spec.OrgID,
	// use the tags from the proxy config
	Tags:         spec.Tags,
}
```

**Comment by sedkis** [comment]
These are not tags in the analytics sense.  They are segment tags that tell Tyk which gateways to load the proxy def on.

Though you can add tags at the key level which will in fact get transferred to the analytics.

**Comment by Roberttmoon** [comment]
Is there any reason to keep the Tag in the API definition then? they don't seem to be used anywhere in the code base and can lead to this confusion in the future?

**Comment by sedkis** [comment]
The `tag` in API Definition is used for sharding not for analytics.  Read more here:
https://tyk.io/docs/advanced-configuration/manage-multiple-environments/#a-namewhat-is-api-shardinga-what-is-api-sharding-

What you're looking for, analytics tags, are here:
https://tyk.io/docs/basic-config-and-security/security/security-policies/policies-guide/
or at the key level.  Look for "tags".  

I can see why it's easy to confuse the two.  I will now close the ticket.
