### ISSUE TITLE
Python issues in 2.9

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2894]
**Branch/Environment/Version**
- Branch/Version: 2.9
- Environment: All

**Describe the bug**
When using Python 2.9 with the dynamic Python loader, memory usage increases quite fast. A potential issue is that the refcount isn't properly handled in the `Dispatch` method.

**Reproduction steps**

1. Setup an API with the following Python middleware:

```python
from tyk.decorators import *
import gc
@Hook
def myhook(request, session, spec):
  gc.collect()
  print(len(gc.get_objects()))
  return request, session
```

2. The above will force the GC collection and print the number of objects which is expected to increase substantially over time without proper refcount management. This happened in 2.8 and was fixed in #1886. 

**Expected behavior**
The refcount handlers should be added, just like #1886. The main difference is that we use our own bindings in 2.9.

**Logs (debug mode or log file):**
This is what the test plugin output looks like:

```
myhook called
29631
myhook called
29631
myhook called
29632
myhook called
29633
myhook called
29634
myhook called
29635
myhook called
29636
myhook called
29637
myhook called
29638
myhook called
29639
myhook called
29640
myhook called
29641
```

**Comment by ilijabojanovic** [comment]
Original issue is fixed and delivered. New improvements are moved in separate ticket and we will handle them in release 2.10 #2917
