### ISSUE TITLE
Allow configure whitelist/blacklist ignore option on global and API level.

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2897]
**Branch/Environment/Version**
- Branch/Version: 2.9

**Describe the bug**
When we introduced "ignore" option for whitelist/blacklist plugin, we actually broke compatibility with previous versions. These plugins now started respecting the case by default (while previously it was not the case). https://github.com/TykTechnologies/tyk/pull/2339/files

We need a way to make it behave like previously, by adding `ignore` param on the API and Global levels (tyk.conf)

**Comment by sedkis** [comment]
I think all our plugins need to be run on global level.  We need to expose the current plugin functionality at the API level at the Gateway level, and then we have access to everything.  Of course some things may not make sense, such as validate JSON or mock response for example.  

But it would be very good for Tyk to be able to "inject header" at global level.   That would allow me to use it as a reverse proxy ingress more easily.

**Comment by maciejwojciechowski** [comment]
can we also please fix this - in raw def this new options is always `false` no matter on BE response

![image](https://user-images.githubusercontent.com/39672152/76399300-aeecb900-637e-11ea-9ed5-854b959b51b0.png)

**Comment by furkansenharputlu** [comment]
@maciejwojciechowski we confirmed with @jay-deshmukh that this is a FE issue. He will fix it and commit to 1.9 and 1.10 branches.

**Comment by jay-deshmukh** [comment]
@maciejwojciechowski @furkansenharputlu fixed and committed to 1.9 and 1.10

**Comment by marksou** [comment]
So the behaviour we document here (for example) - https://tyk.io/docs/advanced-configuration/transform-traffic/endpoint-designer/#case-sensitivity will be the opposite of what it is currently?

**Comment by furkansenharputlu** [comment]
@marksou No, it will not be the opposite. However, there are new levels to ignore case.
1. Global config level, `ignore_endpoint_case`: if it is true all endpoints in all APIs will ignore case no matter value of the ignore parameters on API level or endpoint level
2. API level, `ignore_endpoint_case`: if it is true all endpoints in a specific API will ignore case no matter the value of the ignore param on endpoint level
3. Endpoint level, `ignore_case`: if it is set to true, case will be ignored for only that endpoint.

Rephrasing from bottom to top, 3 is important if 1 and 2 are not set. 2 is important if 1 is not set.

**Comment by ilijabojanovic** [comment]
Verified and covered with tests
