### ISSUE TITLE
[TT-1978] - Support context variables in method transform plugin

### ISSUE THREAD

**Issue by gathuku** [TykTechnologies/tyk#2899]
**Is your feature request related to a problem? Please describe.**
One cannot be able to access context variables in method transform plugin.

**Describe the solution you'd like**
I want to be able to access context variables in method transform 
example
```
  "method_transforms": [
              {
                "path": "/",
                "method": "POST",
                "to_method": "$tyk_context.headers_X_Dev_Method"
              }
           ]
```

**Additional context**
As in the docs only three plugins are supported 
https://tyk.io/docs/getting-started/key-concepts/context-variables/#plugins-that-can-use-context-variables

**Comment by christtyk** [comment]
Thanks for the enhancement request, we'll check it out!

**Comment by andyo-tyk** [comment]
There are a number of enhancements that we would like to make to Tyk's already flexible custom middleware capability; this suggestion is definitely on the list but there is no plan at this stage to implement it, so I will close the ticket.
