### ISSUE TITLE
Can't see stats in API Activity Dashboard graph 

### ISSUE THREAD

**Issue by rcsousa** [TykTechnologies/tyk#29]
Hello , Maybe something I'm doing wrong, but I've just installed tyk version 1.2.1 and dashboard 0.8 on a ubuntu 14.04. Everything seems to be working correctly as I verify the proxy is working correctly ( I can reach my endpoint through tyk) and I can also login the dashboard without problems. I have configured tyk to use use_db_app_configs and managed to create the API from the console.

So far so good. tyk starts ok I think: 
# Tyk.io Gateway API v1.2.1

Copyright Jively Ltd. 2014
http://www.tyk.io

INFO[0000] No configuration file defined, will try to use default (./tyk.conf) 
INFO[0000] Setting up analytics DB connection  
INFO[0000] Using MongoDB cache purge  
INFO[0000] Connecting to redis on: localhost:6379  
DEBU[0000] Enabling debug-level output  
Listening on port:     8080

INFO[0000] Listening on [::]:8080  
INFO[0000] Using App Configuration from Mongo DB  
DEBU[0000] INITIALISING EVENT HANDLERS  
INFO[0000] Loading API configurations.  
INFO[0000] Loading API Spec for: rcsousa  
INFO[0000] Connecting to redis on: localhost:6379  
INFO[0000] Connecting to redis on: localhost:6379  
INFO[0010] Not connected to analytics store, connecting... 
DEBU[0112] Setting key: analytics-2014122516-422c9f6e-fddd-439f-73d0-43099ea0d014 
DEBU[0122] Setting key: analytics-2014122516-bccee697-89cb-4941-4786-8c5155761bfb 
DEBU[0133] Setting key: analytics-2014122516-1ca6b565-2576-40dd-44ab-d6c85c66276d 
DEBU[0308] Setting key: analytics-2014122516-4f021902-85ff-4852-4577-9fa88a81cc54 
DEBU[0827] Setting key: analytics-2014122516-524f35a2-f0ae-4d07-485e-5be3d4e36578 
DEBU[0846] Setting key: analytics-2014122516-c455b1b3-2e55-4adf-5b2b-f321c7db7a95 
DEBU[0975] Setting key: analytics-2014122516-1396192c-c8ac-4688-6fb0-4a363d4536e7 
DEBU[1058] Setting key: analytics-2014122516-cc3781a2-cc65-4f35-7207-662d413d951a 
DEBU[1073] Setting key: analytics-2014122516-0f6d9753-58ad-47f6-657d-e28ef383c467 
DEBU[1269] Setting key: analytics-2014122516-7fbe5842-4505-4fcf-5b77-7afff22cbf84

and as you can see, statistics are being correctly add to the Mongodb collection.

> show dbs
> local   0.03125GB
> test    (empty)
> tyk_analytics   0.0625GB
> use tyk_analytics
> switched to db tyk_analytics
> show collections
> system.indexes
> tyk_analytics
> tyk_analytics_users
> tyk_apis
> tyk_organisations
> db.tyk_analytics.count()
> 31
> db.tyk_analytics.findOne()
> {
>     "_id" : ObjectId("549c30c5e3eb809beead5f13"),
>     "method" : "GET",
>     "path" : "",
>     "contentlength" : NumberLong(0),
>     "useragent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
>     "day" : 25,
>     "month" : 12,
>     "year" : 2014,
>     "hour" : 15,
>     "responsecode" : 200,
>     "apikey" : "",
>     "timestamp" : ISODate("2014-12-25T15:44:02.614Z"),
>     "apiversion" : "Non Versioned",
>     "apiname" : "rcsousa API",
>     "apiid" : "1",
>     "orgid" : "default",
>     "oauthid" : ""
> }

Although everything seems to be ok.. I can't see any changes in the dashboard ... It's like there's no data to display 

Kind regards, 

Ricardo

**Comment by toringe** [comment]
Hi. I'm having a similar issue. Using Tyk 1.5.1, Tyk Analytics 0.9.3 and Mongo 3.0.1. Analytics data are stored in mongo, but I get only an empty graph on the dashboard. And it's still empty even after 24 hours.

    DEBU[165806] Setting key: analytics-201531914-8888f7b6-82e9-46e6-5146-11229d015b2f 

    > db.tyk_analytic.count()
    154

Any clues?

**Comment by lonelycode** [comment]
Hi,

I think it's because the collection is called `tyk_analytic` and not `tyk_analytics`, you may ned to rename it in Mongo (and change it in your `tyk.conf`). The analytics collection is fixed in the dashboard, but changeable in the gateway (in case you want to store it elsewhere and not use the dashboard).

**Comment by toringe** [comment]
My configuration already uses `tyk_ analytic` for collection name.

**tyk.conf**:
```
  "analytics_config": {
    "type": "mongo",
    "csv_dir": "/tmp",
    "mongo_url": "mongodb://localhost/tyk_analytics",
    "mongo_db_name": "tyk_analytics",
    "mongo_collection": "tyk_analytic",
    "purge_delay": 10,
    "ignored_ips": []
  },
```

And in mongo:
```
> show collections
system.indexes
tyk_analytic
tyk_analytics_users
tyk_apis
tyk_organisations
```

But I too noticed the *analytics* in the debug output. So this name is the collection not the db name?

**Comment by lonelycode** [comment]
Hi Tor, yes, and it is wrong, it needs to be `tyk_analytics` (see the plural?), if you rename the collection in mongo and change it in tyk.conf (and reload), it should work.

**Comment by toringe** [comment]
Ah, now it works! Thank you!

**Comment by mingfang** [comment]
what exactly is the proper configuration?
The documentation says analytics_config.mongo_db_name is "not used".
Perhaps the default should be filled in instead of blanks.

**Comment by lonelycode** [comment]
It isn't used, the collection and URL are the important bits

```
"type": "mongo",
"mongo_url": "mongodb://HOST:PORT/tyk_analytics",
"mongo_db_name": "tyk_analytics",
"mongo_collection": "tyk_analytics",
"purge_delay": 10,
```

I would diverge from this.

**Comment by Romain1204** [comment]
Hello,
I started redis/mongo/gateway/dashboard on my server. I don't have any error in my log files. I configure one API using the dashboard and when I run curl commands on my gateway, the target url responds OK. But on my dashboard, I can't see any data (graph is replaced by a "No data to display" message). 

My mongo config is the following one:
`
"analytics_config": {
    "type": "mongo",
    "pool_size": 100,
    "csv_dir": "/tmp",
    "mongo_url": "mongodb://mongo:27017/tyk_analytics",
    "mongo_db_name": "tyk_analytics",
    "mongo_collection": "tyk_analytics",
    "purge_delay": 100,
    "ignored_ips": [],
    "enable_detailed_recording": true,
    "enable_geo_ip": false,
    "geo_ip_db_path": "",
    "normalise_urls": {
          "enabled": true,
          "normalise_uuids": true,
          "normalise_numbers": true,
          "custom_patterns": []
      }
  }`

But when I inspect the content of my tyk_analytics db :
`> show dbs
admin          0.000GB
local          0.000GB
tyk_analytics  0.000GB
> use tyk_analytics
switched to db tyk_analytics
> show collections
tyk_apis
tyk_organisations
tyk_analytics_users
`
I have no tyk_analytics collection. I think that my gateway is not able to write in the mongo db or write data into another db. it's weird because I have any error messages in logs. Please have you some idea about this problem ?

**Comment by ConsM** [comment]
Hi @Romain1204 , is your Pump running ? If you need any further assistance please open a new topic on https://community.tyk.io/ and include your `tyk.conf`, `analytics.conf` and `pump.conf`

**Comment by Romain1204** [comment]
hmmm. No. I don't install the pump component. I try to run the following tutorial : https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/
And as I understand, this page does not deal with the pump. But OK, I will install it. Thanks for this quick reply.

**Comment by buger** [comment]
If you are using https://github.com/TykTechnologies/tyk_quickstart and docker-compose, it should use and start pump for you, when you run `docker-compose up`

**Comment by Romain1204** [comment]
OK. It's better. I launch a tyk-pump container. Now in my mongo db, I have a tyk_analytics collection. And when I run queries to my gateway, lines are added in the tyk_analytics collection. But I still not have result in dashboard.
