### ISSUE TITLE
Make auth error codes configurable on API and Global levels

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#2900]
**Branch/Environment/Version**
- Branch/Version: 2.9

**Describe the bug**
At the moment all Tyk middlewares return code 403 in case if the token has expired. 
While some RFC for expired tokens expect it to be 401. Specifically oAuth one. 

We need a way to make it configurable without breaking backward compatibility.

**Comment by sedkis** [comment]
This is amazing feature!!  is how-to usage documented anywhere in tyk-docs repo?

**Comment by buger** [comment]
For now it is only for one specific purpose, but in future, plan is to spread it across all Tyk errors and log messages.

**Comment by maciejwojciechowski** [comment]
verified
