### ISSUE TITLE
oAuth token generation stops working if listen path contains trailing slash

### ISSUE THREAD

**Issue by n2linux** [TykTechnologies/tyk#2902]
**Branch/Environment**
- Environment: On-prem

**Describe the bug**
oAuth token generation stops working if listen path contains trailing slash

**Reproduction steps**
See customer support ticket for reproduction steps and error output

**Actual behavior**
If listen path contains a trailing slash, the oAuth token generation fails

**Expected behavior**
With the listen path trailing slash present, the token generation should succeed.

**Additional context**
From support ticket 4974

**Comment by christtyk** [comment]
@buger this one for c1 I think

**Comment by christtyk** [comment]
Closed - fixed in 2.9.4
