### ISSUE TITLE
Cannot change "expires" date of an Access Token

### ISSUE THREAD

**Issue by mNantern** [TykTechnologies/tyk#291]
I have defined the property `"oauth_token_expire": 172800` and I want to create an Access Token with an extended lifespan.

So when I call `/authorize-client/` I set the property expires:

```
curl -v -X POST http://localhost:8082/hub/v2/tyk/oauth/authorize-client/ -H "x-tyk-authorization: 352d20ee67be67f6341b4c0605b044b8" -H "Content-Type: application/x-www-form-urlencoded" -d 'response_type=token&client_id=4e04d215-c0a4-40a4-89b6-1520d7119980&key_rules={ "allowance": 1000, "rate": 1000, "per": 1, "expires": 1458669677, "quota_max": -1, "access_rights": { "openApi": {} }, "org_id": "" }&redirect_uri=http://client-app.com/oauth-redirect/'
```

But it's not working:

```
curl -v -X POST http://localhost:8082/hub/v2/tyk/oauth/authorize-client/ -H "x-tyk-authorization: 352d20ee67be67f6341b4c0605b044b8" -H "Content-Type: application/x-www-form-urlencoded" -d 'response_type=token&client_id=4e04d215-c0a4-40a4-89b6-1520d7119980&key_rules={ "allowance": 1000, "rate": 1000, "per": 1, "expires": 1458669677, "quota_max": -1, "access_rights": { "openApi": {} }, "org_id": "" }&redirect_uri=http://client-app.com/oauth-redirect/'
* About to connect() to localhost port 8082 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8082 (#0)
> POST /hub/v2/tyk/oauth/authorize-client/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8082
> Accept: */*
> x-tyk-authorization: 352d20ee67be67f6341b4c0605b044b8
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 263
> 
* upload completely sent off: 263 out of 263 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Fri, 02 Sep 2016 07:14:53 GMT
< Content-Length: 239
< 
* Connection #0 to host localhost left intact
{"access_token":"b1ae4843893d47eb72782f473857d331","expires_in":172800,"redirect_to":"http://client-app.com/oauth-redirect/#access_token=b1ae4843893d47eb72782f473857d331\u0026expires_in=172800\u0026token_type=bearer","token_type":"bearer"}
```

**Comment by lonelycode** [comment]
OAuth token expiry is set in the config unfortunately:

https://github.com/TykTechnologies/tyk/blob/master/config.go#L95

**Comment by mNantern** [comment]
Is it something planned for a future release of Tyk ?

Is it hard to implement that ? (I don't know Go but I can try)

**Comment by lonelycode** [comment]
It's not planned at the moment - but this setting handles the *TTL* of the key. 

If you set the '"expires": 1458669677' section of the `key_rules`, the token (should) return an error if it expires. Because that middleware is independent of the oauth validation checker.

The timestamp `1458669677` converts to March 22nd:

    ~ $ date -d @1458669677
    Tue Mar 22 14:01:17 EDT 2016

So if you used that token, it would actually be bounced. But the expires_in is the TTL of the key lifetime, so what Tyk cares about when it is using the key is the expires metadata timestamp.

Or does the token, when actually used, not respect the expires date?

**Comment by mNantern** [comment]
I didn't actually use the key it was just a test to see if I can dynamically change the `expires_in` of an OAuth access_token.

It looks like it's not possible at the moment.

What do you think of adding a new section in key_rules to specify the oauth access token expires_in ?

**Comment by lonelycode** [comment]
I think more sensibly the system should use the expires field of the key rules or the base policy, the key-rules section is a session object template, it doesn't make sense to add a new field to it.

**Comment by lonelycode** [comment]
The thing is - it *does work*, just the value that comes back regarding expires_in is incorrect.

**Comment by letzya** [comment]
@joshblakeley @buger why was this closed? since it's a dup?
