### ISSUE TITLE
[TT-388] Hostname Load

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2915]
The "Nodes and Licenses" screen in the Dashboard doesn't display the data that is useful to us for management of the nodes.

We'd like to see what shards, tags and loaded APIs are associated with each host.

There doesn't seem to be a way of listing the APIs that a host has loaded at the moment so we don't know where resources are deployed.

User needs to be able to see what resources are deployed, and where.

**Comment by christtyk** [comment]
bump

**Comment by andyo-tyk** [comment]
This feature enhancement was raised by Tyk and is tracked internally.
