### ISSUE TITLE
Cannot install tyk with docker-compose 1.8.0

### ISSUE THREAD

**Issue by dangxunb** [TykTechnologies/tyk#292]
Command and error message:

```
$ docker-compose up -d --force-recreate
Removing tykquickstart_tyk_dashboard_1
Removing tykquickstart_tyk_gateway_1
Removing tykquickstart_tyk_pump_1
Recreating d71643277f5d_tykquickstart_tyk_pump_1
Recreating d3370c515147_tykquickstart_tyk_gateway_1
Recreating d462d8e76619_tykquickstart_tyk_dashboard_1
Recreating tykquickstart_tyk_redis_1
Recreating tykquickstart_tyk_mongo_1

ERROR: for tyk_dashboard  Cannot start service tyk_dashboard: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/6528d2819aa92f795747eec9ff91b2a675adca657acef6eaec6eb98fe51f9157/opt/tyk-dashboard/tyk_analytics.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/6528d2819aa92f795747eec9ff91b2a675adca657acef6eaec6eb98fe51f9157" caused "not a directory"

ERROR: for tyk_gateway  Cannot start service tyk_gateway: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/006a5471aafe5628c317e2ffaca9cbccff7166875d834e0318e368c6b50176d7/opt/tyk-gateway/tyk.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/006a5471aafe5628c317e2ffaca9cbccff7166875d834e0318e368c6b50176d7" caused "not a directory"

ERROR: for tyk_pump  Cannot start service tyk_pump: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/fbcddc2ec13cd4c98cec5311b2dc4bf691ea047c73e42aa2c2315ff9987c8e7b/opt/tyk-pump/pump.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/fbcddc2ec13cd4c98cec5311b2dc4bf691ea047c73e42aa2c2315ff9987c8e7b" caused "not a directory"
ERROR: Encountered errors while bringing up the project.
```

Environment Info:
- OS: Windows 10 64 bit
- Docker version: 1.12.0
- docker-compose version: 1.8.0
- Tyk version: latest.

**Comment by kohrVid** [comment]
Hi,

Apologies for the delayed response. I'm really sorry you had trouble installing Tyk with Docker last year - are you still unable to do this? If you're using Docker Toolbox to install this, it may be worth switching to [Docker for Windows](https://docs.docker.com/docker-for-windows/) as many of our users have been successful using this tool when installing our Docker images. 

Apart from that, it may be worth speaking to the Docker team about this error message as it does look like it could be related to an [issue](https://github.com/docker/docker/issues/21702) that was posted on the Docker repo in the past.

Kind regards,
Jess @ Tyk

**Comment by mvdan** [comment]
@dangxunb I'm closing this issue now - if you're still having the same problem or would like any more help, feel free to reopen with more information.

Thanks.
