### ISSUE TITLE
DRL / Redis Algorithm Switcher

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk#2928]
**Branch/Environment/Version**

master

**Describe the bug**

https://github.com/TykTechnologies/tyk/blob/master/gateway/session_manager.go#L245-L255

```
if n <= 1 || n*c > rate {
				// If we have 1 server, there is no need to strain redis at all the leaky
				// bucket algorithm will suffice.
				if l.limitDRL(currentSession, key, rateScope, apiLimit, dryRun) {
					return sessionFailRateLimit
				}
			} else {
				if l.limitRedis(currentSession, key, rateScope, store, globalConf, apiLimit, dryRun) {
					return sessionFailRateLimit
				}
			}
```

With a high rate-limit, the RedisLimiter is run, rather than the DRL.

**Reproduction steps**

1. 2xGateways
2. DRL Threshold 5
2. Set Rate-Limit for API to 20 rps.

Because RL (20 rps) > 10 (2 * 5), we expect the DRL to run.

```
n <= 1 === FALSE
```

```
n*c > rate === FALSE
2 * 5 > 20 === FALSE
```

As such, the `limitRedis` code runs, not the `limitDRL`.

**Expected behavior**

In this scenario, limitDRL should run.

```
Expected outputs.

1 Gateway = limitRedis

2 Gateways, c = 5
 limitRedis <= rate 10 > limitDRL
2 Gateways, c = 10
 limitRedis <= rate 20 > limitDRL

3 Gateways, c = 5
  limitRedis <= rate 15 > limitDRL
3 Gateways, c = 10
  limitRedis <= rate 30 > limitDRL

5 Gateways, c = 5
 limitRedis <= rate 25 > limitDRL
5 Gateways, c = 10
 limitRedis <= rate 50 > limitDRL

8 Gateways, c = 5
 limitRedis <= rate 40 > limitDRL
8 Gateways, c = 10
 limitRedis <= rate 80 > limitDRL

13 Gateways, c = 5
 limitRedis <= rate 65 > limitDRL
13 Gateways, c = 10
 limitRedis <= rate 130 > limitDRL

21 Gateways, c = 5
 limitRedis <= rate 105 > limitDRL
21 Gateways, c = 10
 limitRedis <= rate 210 > limitDRL
```

**Screenshots/Video**

<img width="519" alt="Screenshot 2020-03-15 at 17 51 28" src="https://user-images.githubusercontent.com/1465130/76699175-a3cebb80-66e5-11ea-83a0-d9b17cbf1c5a.png">

**Impact**

High RL keys will experience significantly high latency - due to synchronising with Redis for every request.

**Comment by sedkis** [comment]
Thank-you for creating.  Agree with all the above except this
> 1 Gateway = limitRedis
I believe 1 gateway = limitDRL.

**Comment by gernest** [comment]
@asoorm @sedkis @buger 

 We are probably debating on which default value of threshold works best. A higher value will suffice when dealing with high rps/relative to number of gateways.

For example if we have threshold of 50, then for 2 gateways with 20rps
```
(50*2) > 20 ==TRUE
```
Then we we will be using DRL then.

We wanted to make this configurable, so our clients can choose what they want avoiding covering infinity scenarios.

I don't see a bug, I see misconception of the use of threshold, `It is not a constant` It can be configured. So use a higher number when you have higher rps relative to the number of gateways.

The only change we can make here is probably agree on a default value that will be good enough.

I'm still thinking(investigating) about this, but that is my opinion for now..

**Comment by sedkis** [comment]
@gernest,
Your understanding is incorrect.  The problem isn't the DRL threshold default value.  The problem is that the logic chooses DRL when the Rate limit is lower than the threshold, when it is supposed to choose higher.

If the rate limit is higher than threshold multiplied by server, we want it to go for DRL because it is more performant.  Whereas, if the rate limit is LOWER than the threshhold, we want it to choose limitRedis because it is more accurate.

It is doing the opposite.  The flow chart has the correct condition

if 
> n * c > rate == false, choose limitDRL
the tyk gw is doing

if 
> n* c > rate == true, choose limitDRL
we want the opposite here.

**Comment by ilijabojanovic** [comment]
Verified
