### ISSUE TITLE
We should embed some of our amazing mascot branding in the code

### ISSUE THREAD

**Issue by jlucktay** [TykTechnologies/tyk#2930]
**Is your feature request related to a problem? Please describe.**
Per [this Slack thread](https://tyktech.slack.com/archives/CKJM7HK0W/p1584383928024000) we should embed an ASCII rendition of our mascot somewhere in the gateway.

**Describe the solution you'd like**
Have [this ASCII-fied image](https://asciify.me/uploads/5e70b1da92acc) from our branding library be returned from an arbitrary endpoint, e.g. `/mascot` or `/logo` or maybe include it with the existing `/hello` or `/health` endpoints.

**Describe alternatives you've considered**
Outputting ASCII art (especially with this large size) to stdout/stderr would make a mess of the logs, so it definitely shouldn't go there.

**Additional context**
🤩 ![image](https://user-images.githubusercontent.com/460028/76852482-523c4300-6843-11ea-911a-f34849023387.png) 🤩

**Comment by buger** [comment]
```
                  ╲╲╲╲╲╲
                  ╲╲╲╲╲╲╲╲╲
           *******╲╲╲╲╲╲╲╲╲╲╲
          **********╲╲╲╲╲╲╲╲╲╲
       ***************╲╲╲╲╲╲╲╲╲╲
     ******************╲╲╲╲╲╲╲╲╲
    ********************╲╲╲╲╲╲╲╲╲
   ***********************╲╲╲╲╲╲╲╲
  *************************** ╲╲╲╲╲╲
  ****************************    ╲╲╲
  *****      *******      ****     _______      _        _
  ******      *****      *****    |__   __|    | |      (_)
  ****************************       | | _   _ | | __    _   ___
  *****************************      | || | | || |/ /   | | / _ \
  ******************************     | || |_| ||   <  _ | || (_) |
 ********************************    |_| \__, ||_|\_\(_)|_| \___/
*********************************         __/ |
***  ************* *********  ****       |___/
      *********************
        *****************
         ******* ******
           ***** *****
          ****** ******
```

**Comment by jlucktay** [comment]
![No you don't](https://i.imgur.com/RFNLPLq.gif)

**Comment by christtyk** [comment]
Do we need to add this to jira @jlucktay or does it just need a merge?

**Comment by jlucktay** [comment]
> Do we need to add this to jira @jlucktay or does it just need a merge?

There was some [security chat on the PR](https://github.com/TykTechnologies/tyk/pull/3188#issuecomment-783447240) that should be addressed before merging.
