### ISSUE TITLE
[TT-1952] Latency 0 issue with Virtual Endpoint

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#2931]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master]
- Environment: [e.g. On-prem]

**Describe the bug**
When you define a virtual endpoint, latency of a request to the endpoint is recorded as 0 in log browser

**Reproduction steps**

1. Create an API
2. Create a virtual endpoint
3. Make a request in that endpoint with `TykBatchRequest`
4. Make a request to the virtual endpoint created above
5. Go to log browser and see latency is 0 for the virtual endpoint

**Actual behavior**
Latency of a request to the virtual endpoint is 0.

**Expected behavior**
Latency of a request to the virtual endpoint should be different than 0.

**Comment by andyo-tyk** [comment]
This was fixed in Tyk 4.0.10 (LTS) and Tyk 4.3.1.
