### ISSUE TITLE
Does On Premise Community Edition (CE) + Redis cluster support Gateway cluster?

### ISSUE THREAD

**Issue by foobargeez** [TykTechnologies/tyk#294]
Hello,
Our requirement is to run an API gateway cluster and we are looking at Tyk.  Does Tyk On Premise CE with Redis cluster as backend let us run Tyk API gateway cluster?  I ask because https://tyk.io/compare-api-management-platforms/ indicates that the on prem CE license allows to manage a _single_ API gateway node and a on prem CE Pro license will allow to manage _two_ API gateway nodes but there is no explicit mention of a feasibility of running a cluster, so I wanted to get clarified.

Thanks in advance!

**Comment by mvdan** [comment]
Hi @foobargeez,

Please use the community forum for questions, as this issue tracker is for bugs and feature requests.

Thanks!
