### ISSUE TITLE
[TT-392] Extend JSVM logging options

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#2946]
**Is your feature request related to a problem? Please describe.**
When using JS plugins we provide two logging functions: `log` and `rawlog`.
Currently `log` uses the `info` log level by default. It could be useful to extend this function to allow JS plugins to use different log levels.
As another related enhancement we could consider adding a function to enable/disable all JSVM logging.

**Comment by andyo-tyk** [comment]
This is noted as a suggestion for future evolution of logging, but no time frame can be given. Closing as "won't do for now".
