### ISSUE TITLE
getIdentityFromToken is called twice for individual secrets

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2947]
https://github.com/TykTechnologies/tyk/blob/3c1600047c50d6e3e4fadfe4f7db976347bdf499/gateway/mw_jwt.go#L606

`getSecretToVerifySignature` in line 606 calls `tykId, err := k.getIdentityFromToken(token)` then a few lines later we call `return k.processOneToOneTokenMap(r, token)` which inside is also calling `k.getIdentityFromToken`

Haven't found it if it's causing an issue or not

**Comment by andyo-tyk** [comment]
This doesn't seem to be causing any issues so I am closing this. It is noted for future refactoring of the code in this area.
