### ISSUE TITLE
Admin dashboard in Tyk cloud freezes/becomes unresponsive on both Chrome and Safari

### ISSUE THREAD

**Issue by ryanwalls** [TykTechnologies/tyk#295]
I don't know what the root cause is, but the admin UI is basically unusable for me.  Have tried restarting the browser.  Tried on other browsers such as Safari.  Etc.

I'm suspicious that my imported, fairly large, API is causing problems.

**Comment by lonelycode** [comment]
It most likely is the large API - there's performance issues in the API designer with very large swagger definitions... 

We're working on addressing it, could you share your browser version / OS?

**Comment by ryanwalls** [comment]
Chrome Version 52.0.2743.116 (64-bit)
OS X 10.11.6 (15G31)

**Comment by awishformore** [comment]
I experience the same issue. Any updates?

**Comment by lonelycode** [comment]
This should be addressed in cloud, on-Prem will be released soon which fixes this

**Comment by awishformore** [comment]
Thank you for the update. Could you qualify `soon`? ;)
