### ISSUE TITLE
custom go plugin middleware does not fire events

### ISSUE THREAD

**Issue by larxxor** [TykTechnologies/tyk#2954]
**Branch/Environment/Version**
- Branch/Version: Master

**Describe the bug**
When authenticating using go plugin, AuthFailure event is never triggered.

**Reproduction steps**

1. In API create webhook on auth failure 
2. Provoke authentication failure in a custom Go plugin
3. Observe that webhook is not run

**Actual behavior**
Log error with generic message : "Failed to process request with Go-plugin middleware func"

**Expected behavior**
FireEvent on EventAuthFailure

The go plugin is called from gateway/mw_go_plugin.go
The code has no implementation of events. This could easily be added, maybe like this  : 

`
if rw.statusCodeSent >= http.StatusForbidden {

			m.logger.WithError(err).Error("Authentication error in Go-plugin middleware func")

			m.Base().FireEvent(EventAuthFailure, EventMetaDefault {
				EventMetaDefault: EventMetaDefault{Message: "Auth Failure", OriginatingRequest: EncodeRequestToEvent(r)},
			})

		} else if rw.statusCodeSent >= http.StatusBadRequest {
			// base middleware will report this error to analytics if needed
			respCode = rw.statusCodeSent
			err = fmt.Errorf("plugin function sent error response code: %d", rw.statusCodeSent)
			m.logger.WithError(err).Error("Failed to process request with Go-plugin middleware func")
		} else {
			// record 2XX to analytics
			m.successHandler.RecordHit(r, Latency{Total: int64(ms)}, rw.statusCodeSent, rw.getHttpResponse(r))

			// no need to continue passing this request down to reverse proxy
			respCode = mwStatusRespond
		}`

**Comment by larxxor** [comment]
Code ready for PR : 
https://github.com/TykTechnologies/tyk/compare/master...larxxor:patch-1?expand=1

**Comment by matiasinsaurralde** [comment]
@larxxor Looks good, you could send a PR.

**Comment by larxxor** [comment]
PR created here : https://github.com/TykTechnologies/tyk/pull/2988

**Comment by larxxor** [comment]
The PR is ready for merge, needs someone to do it.
