### ISSUE TITLE
[TT-1982] - "Filter by api name" matches only the api contains the exact string 

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#2959]
**Branch/Environment/Version**
- Branch/Version: 2.9.3.1
- Environment: On prem and cloud

**Describe the bug**
API filter in the apis screen does only exact match of the string so filtering by "test" would return apis called "test" or "test 123" but not "test123" - it's confusing for the users that expect to get also apis that starts with test or contain test.

**Reproduction steps**

1. Add api named **test1** and save
2. In the text box under `FILTER BY API NAME:` type **test**
3. You get empty result (since it's doing exact string match) 
4. Add an api called **test 1** (this time with a space between test and "1")
5. In the text box under `FILTER BY API NAME:` type **test** again
6. You'll get only the api created in step 4

**Actual behavior**
You get empty result in the list of apis

**Expected behavior**
You should get all the apis that starts with "test" or contains "test" not only that are called "test" since it'll be only one.

If we fix it - need to test also categories

**Additional context**
[Internal](https://github.com/TykTechnologies/tyk-analytics/issues/1353) 
https://github.com/TykTechnologies/tyk-analytics/issues/1445

**Comment by letzya** [comment]
For the time being this is not a high priority. Text search is not so trivial and has lots edge cases.

**Comment by andyo-tyk** [comment]
Cannot reproduce in Tyk 5.0
