### ISSUE TITLE
Bug: if value of key  in meta data is null , gateway fails

### ISSUE THREAD

**Issue by kalyankuramana** [TykTechnologies/tyk#296]
if any key in meta data has null value and that key is used in header transformation (i.e $tyk_meta) , gateway generates a http panic error

**Comment by mvdan** [comment]
@kalyankuramana could you provide complete steps to reproduce, please? (given the latest gateway release running)

**Comment by mvdan** [comment]
Closing this for now. Please reopen if the issue persists on the current stable version.
