### ISSUE TITLE
[TT-1955] UseCertificate field is used even if AuthToken is disable

### ISSUE THREAD

**Issue by komalsukhani** [TykTechnologies/tyk#2972]
**Branch/Environment/Version**
v2.9.3

**Describe the bug**
UseCertificate field is checked even if AuthToken is disabled

**Reproduction steps**

1. Create API with Auth token authentication mode and enable client certificate field.
2. Create Key for API
3. Update API Authentication Mode from AuthToken to MutualTLS
4. Send the request to the API using key created in Step 2. 

**Actual behavior**
Request returns back correct response

**Expected behavior**
Request should fail with `Authorization field missing` error

**Comment by letzya** [comment]
Also if we do thee other way around -  
1. set “mtls” and save - check the filed is false 
2. change to “auth token+enable client cert” 
3. check the filed is still false
