### ISSUE TITLE
Hybrid: Reset quota does not work for token with multiple policies

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#2973]
**Branch/Environment/Version**
- Branch/Version: Stable/Master/Release-1.9
- Environment: All

**Describe the bug**
Quota reset does not work on tokens with multiple policies applied

**Reproduction steps**
1. Crate api1
2. Create api2
3. Create policy1 with 200 quota and add api1
4. Create policy2 without limits and add api2
5. Token and assign policy1 and policy2
6. Use that token on slaved gateway

**Actual behavior**
When we reset quotas, quota remains the same, also we don't have `X-Ratelimit-Reset` header value

**Expected behavior**
When we reset quota for token, those actions must be propagated on slaved gateway and redis

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by andyo-tyk** [comment]
Closing this as no longer an issue
