### ISSUE TITLE
Feature request: Show warning to user in dashboard if changing a policy that has existing users

### ISSUE THREAD

**Issue by ryanwalls** [TykTechnologies/tyk#298]
I'm using Tyk Cloud.  My account is `3dsim.cloud.tyk.io`.  

On API 57e53aca201ad30001000014, client id `https://workflow-qa.3dsim.com` is matched with policy 57e53daf9b111c000100000b.  

In reality, the policy that is actually being enforced is 57dd90449d0210000100003a.  

I believe the steps I took to get to this state are as follows:
1.  Create new api that is set to use connectid for auth.
2.  Add client with id `https://workflow-qa.3dsim.com` and associate with policy 57dd90449d0210000100003a.
3.  Save
4.  Delete the client that was just added
5.  Save
6.  Add the client back using same id `https://workflow-qa.3dsim.com` and associate with policy 57e53daf9b111c000100000b.  
7.  Save

**Comment by lonelycode** [comment]
Hi Ryan, did you generate a new JWT for a new `sub`? If not, the policy will not have been updated on the underlying bearer identity, you will need to delete the underlying token to apply a new policy to it.

**Comment by ryanwalls** [comment]
I'm using Auth0 to generate JWTs.  

Here are my claims

```
{
  "iss": "https://3dsim.auth0.com/",
  "sub": "PV2AvGcMjOFErV6QposKnfrUdt8yPuHI@clients",
  "aud": "https://workflow-qa.3dsim.com",
  "exp": 1474728993,
  "iat": 1474642593,
  "scope": "write:workflows read:workflows"
}
```

The `sub` has not changed.  I could delete the client in Auth0 and create a new one to get a new sub...  not ideal though as I'll have to update client id's and secrets in a few places.

**Comment by lonelycode** [comment]
The case here is that Tyk has generated an internal representation for this identity (sub), and this identity has the matched policy ID set. Changing the policy ID it at the client level will not affect an *existing* user (a sub that Tyk has seen before), changing the policy itself will though. 

See [this documentation article](https://tyk.io/tyk-documentation/security/your-apis/openid-connect/), in particular step 8.

What has happened is that your JWT has generated an internal representation and Tyk will not update the policy based on the client, but you can update the policy on the internal representation (to get this, inject a header with the value of `$tyk_meta.TykJWTSessionID` and edit this token).

I hope that makes sense.

**Comment by ryanwalls** [comment]
That makes sense.  I still feel this is a bug.  This was several hours to track down what was happening.  Seems like at a minimum Tyk could throw a warning/error if someone tries to add a new client id/policy combination that already has an existing internal representation.

**Comment by lonelycode** [comment]
There is a case for that, though this behaviour has nothing to do with the client / policy, if you change the client and policy combo then any *new* bearers will be affected, just not existing ones. We'll add this to the docs to make it clearer.

**Comment by ryanwalls** [comment]
What you are explaining doesn't seem to apply to the new client credentials flow for auth0.  Which is what I'm using.  

In this flow, there is only one client, that authenticates as itself.  These are the claims:
```
{
  "iss": "https://3dsim.auth0.com/",
  "sub": "PV2AvGcMjOFErV6QposKnfrUdt8yPuHI@clients",
  "aud": "https://workflow-qa.3dsim.com",
  "exp": 1474728993,
  "iat": 1474642593,
  "scope": "write:workflows read:workflows"
}
```

Note that the `sub` is really a "client id".  The `aud` is just the api to use.  So once the internal representation is set in tyk (based on the `sub`), then a new policy will never be used unless I delete the underlying representation or delete the Auth0 client.  

In the user flow, this makes sense though.  Each `sub` would be a different user.  As in this example claim:
```
{
  "iss": "https://3dsim.auth0.com/",
  "sub": "auth0|57da6d5d22fd54ba32c7ab9e",
  "aud": "xK8mAP7LbZpcDuOsCIJ3sacHELEuJ4RV",
  "exp": 1474681825,
  "iat": 1474645825
}
```
So yeah, new users would get the new policy.  

So perhaps I should create a new issue for supporting client credential flow?

**Comment by lonelycode** [comment]
Ah, I was assuming you were using it for users, which is the OIDC use case we've designed for. You can raise a feature request on our community forum :-)

**Comment by ryanwalls** [comment]
Still feel even for the user flow that a warning could pop up when you change the policy for a client.  Could say something like "Existing users detected for this client.  These users will continue to use the old policy."

**Comment by lonelycode** [comment]
👍
