### ISSUE TITLE
[TT-376 & TT-7195] Swagger import whitelisting + payload verification improvement

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#2999]
"The import of the JSON swagger does not entail the activation of white listing + payload verification automatically."

The customer requests a way of doing this automatically.

Related ticket: https://support.tyk.io/a/tickets/5142

**Comment by letzya** [comment]
- Check path param = block API call if there is a bad format of the value of path param 
- Check - query url = block API call if there is a bad format of value or if the parameter is unknown - Validate JSON = support the same format values as Swagger

**Comment by letzya** [comment]
OAS3.0 https://swagger.io/docs/specification/data-models/keywords/

**Comment by letzya** [comment]
Looks like a regression because it used to whitelist before.

**Comment by educroquet** [comment]
I did create a ticket with more details : #3164, missed this one, sorry

**Comment by andyo-tyk** [comment]
There are two parts to this issue:
1) activation of allow-listing (whitelisting) on API import
2) activation of payload verification on API import

The first was released in Tyk 4.1; the second is expected in Tyk 5.0.

Note that both features will relate only to the import of OAS APIs.

**Comment by andyo-tyk** [comment]
This is fixed in Tyk 5.0; please see the release notes [here](https://tyk.io/docs/release-notes/version-5.0/).

Thank you for your support of Tyk!
