### ISSUE TITLE
Tyk cloud log browser does not show request/response

### ISSUE THREAD

**Issue by ryanwalls** [TykTechnologies/tyk#300]
All logs in our cloud account show empty requests and responses.

![image](https://cloud.githubusercontent.com/assets/842653/19134627/5b1d8b26-8b1c-11e6-9edf-f946db5d073d.png)

**Comment by matiasinsaurralde** [comment]
Hi Ryan, detailed request logging is not available in Tyk Cloud, you may find more about this [here](https://tyk.io/tyk-documentation/analyse/log-browser/).

**Comment by ryanwalls** [comment]
@matiasinsaurralde Thanks.  Makes sense.

**Comment by ryanwalls** [comment]
@matiasinsaurralde Might want to disable that view in tyk cloud and/or put some help text above those boxes.  Would save issues like this. :)

**Comment by matiasinsaurralde** [comment]
@ryanwalls Sure, thanks for the suggestion!

**Comment by mhrabapayu** [comment]
@ryanwalls Hi Ryan, sorry for kicking the dead horse - but is detailed request/response logging on your roadmap for Tyk Cloud? I just checked your trello board and couldn't find that specific topic.

**Comment by lonelycode** [comment]
@mhrabapayu it isn't on our roadmap for the near future
