### ISSUE TITLE
Health check: Status report is returned in plain text

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#3005]
**Branch/Environment/Version**
- Branch/Version: Master/Release-2.10
- Environment: All

**Describe the bug**
Health check endpoint should return response json not plain text

**Reproduction steps**

1. Send request to `{gateway_url}/hello

**Actual behavior**
Gateway returns status in plain text

```
{"status":"pass","version":"v2.9.3","description":"Tyk GW","details":{"dashboard":{"status":"pass","componentType":"system","time":"2020-04-09T11:04:20+02:00"},"redis":{"status":"pass","componentType":"datastore","time":"2020-04-09T11:04:20+02:00"}}}
```

**Expected behavior**
Gateway should return json formatted body. We should return proper `Content-Type` in response headers

**Screenshots/Video**
![check](https://user-images.githubusercontent.com/8557292/78877907-d56f4400-7a51-11ea-9108-842574bf0376.gif)

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by buger** [comment]
So basically it missing application/json content type header?

**Comment by ilijabojanovic** [comment]
@buger yes

**Comment by asoorm** [comment]
```
curl -s -i localhost:8080/hello
HTTP/1.1 200 OK
Date: Thu, 09 Apr 2020 09:10:49 GMT
Content-Length: 251
Content-Type: text/plain; charset=utf-8 <------------------

{"status":"pass","version":"v2.9.3","description":"Tyk GW","details":{"dashboard":{"status":"pass","componentType":"system","time":"2020-04-09T10:10:43+01:00"},"redis":{"status":"pass","componentType":"datastore","time":"2020-04-09T10:10:43+01:00"}}}
```

**Comment by adelowo** [comment]
@buger Will fix right away

**Comment by ilijabojanovic** [comment]
Verified
