### ISSUE TITLE
Where to get the develop roadmap

### ISSUE THREAD

**Issue by imjoey** [TykTechnologies/tyk#3007]
**Branch/Environment/Version**
- Branch/Version: Master

**Describe the bug**
The project **TykTechnologies/tyk-roadmap** seems gone, which leads to `404` when accessing *https://github.com/TykTechnologies/tyk-roadmap* in the **Roadmap** section in README.

**Actual behavior**
The link returns to `404` error.

**Expected behavior**
The Roadmap section could show the roadmap details.

Much appreciated.

**Comment by glymehrvrd** [comment]
met the same problem

**Comment by christtyk** [comment]
Hi folks, we don't have an open roadmap at the moment apologies, we should have removed this from the readme. I'll ask for it to be updated.

**Comment by imjoey** [comment]
Hi @christtyk , thanks for the update.
