### ISSUE TITLE
Detailed logging: Enable/disable logging for token is not propagated on slave/hybrid

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#3009]
**Branch/Environment/Version**
- Branch/Version: Master/Release-2.10
- Environment: MDCB

**Describe the bug**
When we enable key logging everything working on master and slave gateway, when we disable logging change isn't propagated on slave gateway.

**Reproduction steps**

1. Start MDCB environment 
2. Generate token and enable logging 
3. Generate some traffic over slave gateway
4. Disable logging on token level
5. Send traffic to slave gateway

**Actual behavior**
Logging remains enabled on slave gateway

**Expected behavior**
Logging should be disabled and we should propagate all changes on slave gateways

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by sredxny** [comment]
I was able to replicate this, it only happens when we save changes with "update without quota reset"

**Comment by sredxny** [comment]
@ilijabojanovic also, can you share which screen logs are you still seeing? as I understand this value is to dump or not the responses into analytics. Currently the logs that I see when we record detailed logs are the logs printed when the records are purged to analytics, do you mean that you still see these lines?

**Comment by ilijabojanovic** [comment]
On latest release-2.10 branch and master sink i can't replicate issue anymore
