### ISSUE TITLE
Dashboard still not connecting to MongoDB right after installation

### ISSUE THREAD

**Issue by TristanCP** [TykTechnologies/tyk#301]
This issue is not yet solved :
https://github.com/TykTechnologies/tyk/issues/92

The default tyk_analytics.conf still contains "localhost" and not "127.0.0.1" and I guess the "golang bug" is still there since I've just met this very strange problem.

**Comment by lonelycode** [comment]
The default tyk_analytics.conf isn't to be used, the templates that are in the data folder are the ones used by the setup script.

We'all look at updating the default file that gets packaged.

**Comment by mvdan** [comment]
@lonelycode was this done? If not, shouldn't this be moved to the correct repo?

**Comment by lonelycode** [comment]
Sample in the repo is ` "mongo_url": "mongodb://localhost/tyk_analytics`

So it's done
