### ISSUE TITLE
Unlimited quota and rate-limiting are not inherited from policy to key properly

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#3013]
**Branch/Environment/Version**
- Branch/Version: Master

**Describe the bug**
Unlimited quota and rate limiting are not inherited from policy to key

**Reproduction steps**

1. Create a policy with unlimited quota and rate-limit
2. Create key by applying the policy created in the first step
3. See quota and rate not unlimited checked

**Actual behavior**
Unlimited quota and rate limiting are not inherited.

**Expected behavior**
They should be inherited properly

**Comment by ilijabojanovic** [comment]
Verified
