### ISSUE TITLE
HTTP/1.1 504 Gateway Time-out

### ISSUE THREAD

**Issue by kamoljan** [TykTechnologies/tyk#302]
Hi guys!

We are facing gateway timeouts from AWS ALB for requests that take more than 10 seconds to complete where In the ALB we have set it as 60 seconds. 
Please find the response as shown below.

```
URL://https://tyk.XXX.com/hello-world
Response headers:
HTTP/1.1 504 Gateway Time-out
Server: awselb/2.0
```

Also, we were not able to use [enforced-timeouts](https://tyk.io/docs/tyk-v2-2-documentation-components/enforced-timeouts/) due to our TyK gateway containers are not restarting while accessing the APIs (that's another issue).

With that, how can we configure TyK gateway's timeout (Keep-Alive)?
Or it would be great if you guys can help us finding the root cause.

Thanks in Advance
Kamol

**Comment by lonelycode** [comment]
Hi Kamol,

Is this an on-premise or a hybrid setup with Tyk Cloud?

The [default timeout in Tyk is set to 30s](https://github.com/TykTechnologies/tyk/blob/master/tyk_reverse_proxy_clone.go#L299), the 10s timeout is specifically for TLS negotiation.

The enforced timeout feature *should* override this and it is by far the best way to extend the timeout in the gateway, I don't think there's another way to configure this value.

Alternatively, you could try and drop https in your target to see if that improves things...

Does the gateway provide any logs that you can share when the timeout kicks in?

M.

**Comment by kamoljan** [comment]
@lonelycode 

It is a hybrid setup.
We don't have https in our target, only http.
We are not getting any logs from TyK gateways during this timeout.

Any idea?

k

**Comment by lonelycode** [comment]
Interesting, if the gateway were causing the timeout as part of the proxy then it would return an error, both to the client and to the log.

This could mean that Tyk is not reachable from your ELB? Can yu target the gateway(a) directly to test?

**Comment by kamoljan** [comment]
@lonelycode 
Ok, we are targeting directly TyK gateways without ALB(ELB).
It looks like TyK gateway (docker) runs 80 % very fast but, 20% request very slow...

Maybe we are getting too many concurrent connections?
What is a TyK gateway default limitation (number open connections, concurrent connections, memory, CPU, etc)?

**Comment by lonelycode** [comment]
@kamoljan Tyk is meant to run on multi-core boxes, and should on a 2GB/2-Core VM handle about ~1,000 requests per second. 

What kind of spec are you running the container on? Also redis can become a bottleneck if the box is not large enough and can't handle the high connection volume.

**Comment by kamoljan** [comment]
@lonelycode looks like it was this issue https://github.com/microservices-today/IaC-dcos/issues/118 related to CoreOS iptables. After dropping CoreOS iptables it works perfectly fine.
