### ISSUE TITLE
[TT-1986] - Cache frequently used keys

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3021]
**Is your feature request related to a problem? Please describe.**

Seeing performance issues tied to Redis clusters.

**Describe the solution you'd like**

Cache frequently used keys, so that we don't need to wait for Redis so often. Are we already doing this?

**Describe alternatives you've considered**

Implement RAFT in Tyk server and provide example Kibernetes configurations persisting data in S3 buckets, so that Redis is no longer needed.

**Comment by andyo-tyk** [comment]
Closing as not planned.
