### ISSUE TITLE
OIDC fails with Auth0

### ISSUE THREAD

**Issue by maciejwojciechowski** [TykTechnologies/tyk#3030]
**Branch/Environment/Version**
- Branch/Version: release-2.9
- Environment: on prem/saas

**Describe the bug**
Calling OIDC protected API fails when using Auth0. 
The problem is with go-jose library 2.5.0 which was used in release-2.9
On master (where we use older version of that lib) everything works fine.

**Reproduction steps**
Follow this video to create OIDC api using Auth0
https://www.youtube.com/watch?v=rBg_lT3PbiY

**Actual behavior**
api call fails with the following error
```
[Apr 20 12:20:44]  WARN JWT Invalid api_id=43996f5680fe49f84e03dde1bd348b05 api_name=oidc error=Validation error. Validation error. Failure while decoding the jwk retrieved from the endpoint https://dev-4y98pfvu.eu.auth0.com/.well-known/jwks.json: square/go-jose: invalid JWK, x5t header is of incorrect size mw=OpenIDMW org_id=5e9d673a9858dc219653db83 origin=127.0.0.1 path=/oidc/get
[Apr 20 12:20:44]  WARN Attempted access with invalid key. api_id=43996f5680fe49f84e03dde1bd348b05 api_name=oidc key=****JWT] mw=OpenIDMW org_id=5e9d673a9858dc219653db83 origin=127.0.0.1 path=/oidc/get
^C2020/04/20 12:20:48 interrupt
```

**Expected behavior**
No issues, should be possible to use Api no problems with Auth0

**Comment by buger** [comment]
Fixed by https://github.com/TykTechnologies/tyk/pull/3031

**Comment by ilijabojanovic** [comment]
Verified and covered with tests
