### ISSUE TITLE
Key get expired when updated

### ISSUE THREAD

**Issue by sredxny** [TykTechnologies/tyk#3038]
**Branch/Environment/Version**
- Branch/Version: Master/Release2.10
- Environment: Hybrid/MDCB

**Describe the bug**
When we update a key which expiry was set by a policy then the key get automatically expired

**Reproduction steps**

1. Create policy and set any expiry different than "Do not expire" 
2. Create a Key applying this policy
3. Use the key
4. Update the key (something simple as alias will work)
5. Try to use the key

**Actual behavior**
Key get immediately expired

**Expected behavior**
If the key is still alive we should be allowed to use it

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
Verified
