### ISSUE TITLE
Avoiding load-balancer panics, pending 2.2.0.4 release

### ISSUE THREAD

**Issue by poblish** [TykTechnologies/tyk#304]
We've been examining a stacktrace we've seen in gateway 2.2.0 that crashes at https://github.com/TykTechnologies/tyk/blob/v2.2/tyk_reverse_proxy_clone.go#L60 with `interface conversion: interface {} is []string, not *[]string`.

I've noticed the patch for 2.2.0.4 - https://github.com/TykTechnologies/tyk/commit/3f2201415cb41f5477b143924479c690db88cda9 - that looks likely to fix our problem.

My question is: do you have a story or explanation for that fix, as we've been scratching our heads to work out why it only happens for one of our APIs - or even better, a workaround we can try prior to the next binary release?

**Comment by lonelycode** [comment]
Have you tried the latest version? We are on v2.2.0.28 I think at the moment in our package cloud - we fixed most of the LB issues and SD issues around .14->.20.

The LB system was completely replaced in this version with a more resilient data structure.
