### ISSUE TITLE
[TT-130] Message integrity with HMAC signing

### ISSUE THREAD

**Issue by alephnull** [TykTechnologies/tyk#3040]
**Branch/Environment/Version**
- Branch/Version: 2.9.4
- Environment: on-prem

**Describe the bug**
Using [HMAC signing](https://tyk.io/docs/basic-config-and-security/security/authentication-authorization/hmac-signatures/) for message integrity does not work as the body is never checked against the signature.

**Reproduction steps**

1. Create an API with HMAC signing
1. Add a header `digest` that contains the hash of the body
1. This header is part of the HMAC verification
1. Make a request with a changed message body but keeping digest the same

**Actual behavior**
The request succeeds

**Expected behavior**
The request should fail as the hash of the body no longer matches the digest.

**Sample requests**
```shellsession
 curl --location --request POST 'http://x.x.x.x/test/post' \
--header 'Authorization: Signature keyId="5e86aae0be1ed10a3d804ab76905244945b240218107dcfec112b4de",algorithm="hmac-sha256",headers="x-test-1 date digest",signature="WQoi6DgsCVtxB2q08GOxmb4w0RIVjPnWhmAKeofVJrc%3D"' \
--header 'x-test-1: hello' \
--header 'Date: Wed, 15 Apr 2020 06:33:35 IST' \
--header 'Digest: SHA-256=N9AWI4rQYKOxhQZEiYiGphh9PjJMz89aZjGCPnZXNDc%3D' \
--header 'Content-Type: application/json' \
--data-raw '{
    "args": {
        "123": "trekjb"
    }
}'
```
Changed payload
```shellsession
curl --location --request POST 'https://x.x.x.x/test/post' \
--header 'Authorization: Signature keyId="5e86aae0be1ed10a3d804ab76905244945b240218107dcfec112b4de",algorithm="hmac-sha256",headers="x-test-1 date digest",signature="WQoi6DgsCVtxB2q08GOxmb4w0RIVjPnWhmAKeofVJrc%3D"' \
--header 'x-test-1: hello' \
--header 'Date: Wed, 15 Apr 2020 06:33:35 IST' \
--header 'Digest: SHA-256=N9AWI4rQYKOxhQZEiYiGphh9PjJMz89aZjGCPnZXNDc%3D' \
--header 'Content-Type: application/json' \
--data-raw '{
    "args": {
        "123": "changedPayload"
    }
}'
```

**Additional context**
From https://github.com/TykTechnologies/tyk/blob/v2.9.4/gateway/mw_http_signature_validation.go#L76
it appears that the body is never checked.
The goal is to have a check on message integrity. If there is some other way of implementing it, it would help.

**Comment by andyo-tyk** [comment]
Tyk has never supported HMAC signature of the request body. This is a feature request. We do not plan to implement this feature - we believe that HMAC is not heavily used and there does not seem to be significant demand so I will close the ticket.
