### ISSUE TITLE
Auth mode JWT empty policies not working when using Tyk CE

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk#3042]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
All
- Environment: [e.g. On-prem/Hybrid/MDCB]
All

**Describe the bug**
When using the auth mode JWT and do not configure any default policy so the array     "jwt_default_policies": [] is empty the Tyk CE fails complaining that we must have a policy configured. This is not totally true because we can have dynamic policies been passed by Policy Field Name "pol" for example. 

**Reproduction steps**
Explained in "describe the bug"

**Actual behavior**
this error -> [Apr 19 15:43:28] ERROR Could not find a valid policy to apply to this token! api_id=XXXX api_name=XXXX-api mw=JWTMiddleware org_id= origin=172.23.0.1 path=/XXXX/BBBB

**Expected behavior**
This is a valid scenario because we can have dynamic policies ID passed via JWT tokens issued by 3th parties. Therefore, the polices id should be derived by the Jwt claims. in this example or print screen shared is the claim ‘pol’ 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/908425/80013415-26aa1980-84cf-11ea-9d5f-7c611e2c68d6.png)
This is a valid configuration where the default policy is empty ^

**Logs (debug mode or log file):**
N/A
**Configuration (tyk config file):**
N/A
**Additional context**
N/A

FYI, as discussed, @letzya @asoorm

**Comment by letzya** [comment]
@bmonteiro thanks for submitting the bug. I’m still checking it. Can I confirm it works for you on prem or hybrid? (It works for me). I need to check the code again and test with CE as I’m not sure when looking  in the code why it works for on prem and not CE

**Comment by letzya** [comment]
@bmonteiro I just tested tyk CE with ` "jwt_default_policies": [],` - if works well with our master when running directly from source but not as a docker. I really don't understand why...  
My api def and policy: https://gist.github.com/letzya/bc52cabca6da5d611863d3ef284afda1
How do you run tyk?

**Comment by letzya** [comment]
Ok I can confirm that after exporting the api def and using it in tyk ce everything works as expected. I will however submit  PR to add more info in to the errors in the log
