### ISSUE TITLE
[TT-1989] - Exponential backoff for storage.IsConnected

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3046]
**Is your feature request related to a problem? Please describe.**

In the event of a Redis unavailability, storage.IsConnected spams messages linearly, which can make capacity problems worse.

**Describe the solution you'd like**

Backoff retries exponentially, such as doubling the sleep value each successive attempt.

**Describe alternatives you've considered**

Another strategy would be to expose waitStorageRetriesInterval as a configuration parameter. That would add yet another knob for DevOps to manage, compared to a self-tuning exponential backoff.

**Comment by andyo-tyk** [comment]
Closing as this is not currently on our roadmap, but we may return to it later if there is renewed interest from users.
