### ISSUE TITLE
MDCB: Gateway can't sync data from mdcb

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#3051]
**Branch/Environment/Version**
- Branch/Version: Master/Release-2.10
- Environment: MDCB

**Describe the bug**
When we start gateway which has redis on non standard port, gateway is not able to sync data from mdcb due error

**Reproduction steps**
1. Start redis on port 6380
2. Add redis port in gateway config 
3. Start gateway in mdcb mode

**Actual behavior**
If redis is on non standard port we have errors in console

**Expected behavior**
We should always sync data from mdcb

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
```
➜  tyk git:(release-2.10) ✗ ./tyk --port 8183 --conf=./tyk_sink.conf
[Apr 28 10:57:50]  INFO main: Tyk API Gateway v2.10
[Apr 28 10:57:50]  WARN checkup: Insecure configuration allowed config.allow_insecure_configs=true
[Apr 28 10:57:50]  WARN checkup: File descriptor limit 256 is too low for production use. A minimum of 80000 is recommended.
	This could have a significant negative impact on performance.
	Please refer to the following link for further guidance:
		https://tyk.io/docs/deploy-tyk-premise-production/#file-handles--file-descriptors
[Apr 28 10:57:50]  WARN checkup: Default secret should be changed for production. config.secret=352d20ee67be67f6340b4c0605b044b7
[Apr 28 10:57:50]  WARN checkup: AnalyticsConfig.PoolSize unset. Defaulting to number of available CPUs runtime.NumCPU=16
[Apr 28 10:57:50]  WARN checkup: AnalyticsConfig.RecordsBufferSize < minimum - Overriding minRecordsBufferSize=1000
[Apr 28 10:57:50]  INFO host-check-mgr: Starting Poller
[Apr 28 10:57:50] ERROR Failed to init GeoIP Database: open ./GeoLite2-City.mmdb: no such file or directory
[Apr 28 10:57:50] ERROR RPC client is not connected, use Connect method 1st
[Apr 28 10:57:50]  INFO RPC Analytics client using singleton
[Apr 28 10:57:50]  INFO main: Setting up analytics normaliser
[Apr 28 10:57:50]  INFO main: PIDFile location set to: ./tyk-gateway.pid
[Apr 28 10:57:50]  WARN main: The control_api_port should be changed for production
[Apr 28 10:57:50]  INFO Setting new RPC connection!
[Apr 28 10:57:50]  INFO RPC: Starting keyspace poller
[Apr 28 10:57:50]  INFO main: Initialising Tyk REST API Endpoints
[Apr 28 10:57:50]  INFO RPC Conn Mgr: [RPC Conn Mgr] Starting keepalive watcher...
[Apr 28 10:57:50]  INFO --> [REDIS] Creating single-node client
[Apr 28 10:57:50]  INFO main: Node is slaved, REST API minimised
[Apr 28 10:57:50]  INFO main: --> Using TLS (https)
[Apr 28 10:57:50]  WARN main: Starting HTTP server on:[::]:8183
[Apr 28 10:57:50]  INFO main: Initialising distributed rate limiter
[Apr 28 10:57:50]  INFO main: Tyk Gateway started (v2.10)
[Apr 28 10:57:50]  INFO main: --> Listening on address: (open interface)
[Apr 28 10:57:50]  INFO main: --> Listening on port: 8183
[Apr 28 10:57:50]  INFO main: --> PID: 1773
[Apr 28 10:57:50]  INFO main: Loading policies
[Apr 28 10:57:50]  INFO Starting gateway rate limiter notifications...
[Apr 28 10:57:50]  INFO Storing RPC policies backup
[Apr 28 10:57:50]  INFO --> Connecting to DB
[Apr 28 10:57:50]  INFO --> Connected to DB
[Apr 28 10:57:50]  INFO main: Policies found (0 total):
[Apr 28 10:57:50] ERROR main: Error during syncing policies:Failed to store node backup: storage: Redis is either down or ws not configured
[Apr 28 10:57:50]  INFO --> [REDIS] Creating single-node client
^C2020/04/28 10:57:53 interrupt
[Apr 28 10:57:53]  INFO main: Stop signal received.
[Apr 28 10:57:53]  INFO main: Terminating.
```

```
[Apr 28 10:57:50] ERROR main: Error during syncing policies:Failed to store node backup: storage: Redis is either down or ws not configured
```
**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
NOTE: Seems this fix caused this regression: https://github.com/TykTechnologies/tyk/pull/3019

**Comment by sredxny** [comment]
I could not reproduce the error even with the database backup provided by Ilija, @spetrunin you were ble to reproduce it, rigth?

**Comment by sredxny** [comment]
I tried to replicate this issue again and did not get the error. Next I detail what was done:

**Versions:**
Gateway: release-2.10
Sink: v1.7.0 / Master
Dashboard: release-1.10
Mongo: 4.2.2
Redis: 5.0.7

**Steps**
- Created new instance of mongo, in port `27018` and updated dashboard config file and sink config file.
- Created 2 new instances of redis in port 7000 and 7777. Updated slaved gw config file to use redis on 7777 and master gw, dashboard and sink in redis port 7000
- Restored DB with backup provided by Ilija
- Started dashboard, Master GW, sink, slave GW (slave synchronized correctly)
- Turn off sink
- Turn on sink... (slave connected correctly to rpc)
- Turn off dashboard
- Turn on dashboard
- Turn off slaved gw
- Turn on slaved gw (syncs correctly)

Checking the code, the error `ERROR main: Error during syncing policies:Failed to store node backup: storage: Redis is either down or ws not configured` is showed up when slave cannot connect to redis, so, I think we should check that

**Comment by ilijabojanovic** [comment]
This issue can't be reproduced on several environments
