### ISSUE TITLE
[TT-1992] - tyk lint gives schema.json: no such file or directory

### ISSUE THREAD

**Issue by JvGinkel** [TykTechnologies/tyk#3054]
**Branch/Environment/Version**
- Branch/Version: 2.9.4.1
- Environment: On-prem

**Describe the bug**
After upgrading to 2.9.4.1 the `./tyk lint` command produce the following error:

```shell
./tyk lint
tyk: error: open cli/linter/schema.json: no such file or directory, try --help
```

**Comment by hbirkdale** [comment]
I'm getting this in OSS as well on V3.2.1

**Comment by andyo-tyk** [comment]
This is not reproduced in Tyk 5.0, closing as fixed.
