### ISSUE TITLE
can't load package: package github.com/TykTechnologies/tyk: C source files not allowed when not using cgo or SWIG: coprocess_python_api.c sds.c

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#306]
for branch develop, to go build, the error as below: may be use cgo, how to compile it? 

can't load package: package github.com/TykTechnologies/tyk: C source files not allowed when not using cgo or SWIG: coprocess_python_api.c sds.c

**Comment by matiasinsaurralde** [comment]
Hi, which Go version are you using, and what command are you using to build Tyk?

**Comment by penhauer-xiao** [comment]
Go 1.7.3

**Comment by matiasinsaurralde** [comment]
Are you using an updated version of the repo?

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde  The  same issues on today by follow command :)
$ git clone -b develop https://github.com/TykTechnologies/tyk.git
$ cd tyk
$ glide init
$  glide update
$ go build
can't load package: package github.com/TykTechnologies/tyk: C source files not allowed when not using cgo or SWIG: coprocess_python_api.c sds.c

**Comment by matiasinsaurralde** [comment]
Hi, these files are ignored by the Go compiler, because they use a special build tag.
This error could happen if the build tags are not set, can you run `head coprocess_python_api.c` and share the output?

I'm not able to reproduce this issue, tested it with Go 1.7 (darwin/amd64) and Go 1.6.2 (linux/amd64).

Have you tried building without `glide`? Not sure if it affects the build process.

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde   
$git:(develop) head coprocess_python_api.c                                                                                                                                         
coprocess/python/tyk/gateway.c

Without use glide,  the same issues,  So what build tags to set ?

**Comment by matiasinsaurralde** [comment]
Ah, it's a symbolic link, so can you run `head coprocess/python/tyk/gateway.c` and share the output again?

The compiler should ignore it, when no build tag is set, e.g. `go build`.

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde  The output as below:
$ head coprocess/python/tyk/gateway.c
// +build coprocess
// +build python

/* Generated by Cython 0.24.1 */

/* BEGIN: Cython Metadata
{
    "distutils": {
        "depends": []
    },

**Comment by matiasinsaurralde** [comment]
I suggest checking [this thread](http://stackoverflow.com/questions/32115229/go-1-5-error-imports-runtime-c-source-files-not-allowed-when-not-using-cgo), or [this one](http://stackoverflow.com/questions/27772831/golang-c-source-files-not-allowed-when-not-using-cgo).
Perhaps a `GOROOT` pointing to a wrong place?

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde   I am sure the GOROOT is right,  The latest GOROOT match with Go1.7.3

**Comment by penhauer-xiao** [comment]
:)  This issue can't sink

**Comment by lonelycode** [comment]
Can you confirm what `go version` outputs? 

Our CI (Travis) builds this repo just fine so this is a local issue with your setup.

**Comment by penhauer-xiao** [comment]
@lonelycode 
The same issues, in Go 1.7.3 and Go1.6.2

$git:(develop) go build

can't load package: package github.com/TykTechnologies/tyk: C source files not allowed when not using cgo or SWIG: coprocess_python_api.c sds.c

**Comment by penhauer-xiao** [comment]
For this issues, may be sink forever and always.  :)

**Comment by kohrVid** [comment]
Hi Kent,

Apologies for not following up on this issue for a while. Were you ever able to build Tyk from the source files in the end? If so, would it be all right if we closed this issue in Github? If not, could you please confirm as to whether you're using the most up-to-date version of the Tyk repo and that you're still trying to build with version 1.7 of Go without Glide?

Kind regards,
Jess @ Tyk

**Comment by penhauer-xiao** [comment]
I have been update the most up-to-date version of the Tyk repo,  it is ok, thanks.
