### ISSUE TITLE
[TT-1994] - Enhancement: Note Go version in --version report

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3064]
**Is your feature request related to a problem? Please describe.**

When troubleshooting problems, it is helpful to know the version of Go that was used to build tyk.

**Describe the solution you'd like**

Inject Go version information into the binary and emit this as part of the `tyk --version` output.

**Describe alternatives you've considered**

Painstakingly examining CI pipelines against Docker image hashes and VCS hashes.

**Comment by christtyk** [comment]
Thanks for the request! Will review and see what we can do

**Comment by andyo-tyk** [comment]
We have reviewed this suggestion and concluded that we won't be implementing it. Changes to the Go version used to compile each Tyk component are noted in the Release Notes. This isn't ideal, so we will look to improve the sign-posting of Go version used for each version of each component. Thank you for raising the issue and for supporting Tyk!
