### ISSUE TITLE
TT-2 Gateway should record response payload also case of an error 

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3070]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB]
On prem, 2.9.4

**Describe the bug**
If there was an error (in tyk or upstream), tyk does not record the payload

From the client:
When an upstream backend replies something, a 4xx/5xx error or 2xx response, we can capture the response body clearly in the Logs Brower UI and via Pump.

But when it is Tyk.io that replies a 4xx error directly to the client, then the response body send by Tyk.io to the client does not show in logs: in either in the Logs Browser UI or via Pump feeding our own ELK instance.
**It appears that such a response message also does not appear in the file logs from the Gateways.**

We need to be able to capture in some logs the response message that Tyk.io sent to our external clients, or at least some information of same value, so we can take appropriate support actions toward them. 
Doesn't make sense that the caller will have more information than the dashboard user that views the analytics

**Reproduction steps**

1. Turn on detailed recording in tyk.conf and maybe sure the pump is running
2. Create an API with authentication
3. Call the API without authorization header and get an error
4. For completeness also make a valid call with the API key
5. Check the "log browser" in the dashboard and see that the payload in the response is missing. Screengrab attached

**Actual behavior**
No payload recording in the analytics in case of an error in the upstream or tyk

**Expected behavior**
Do the same as we do for regular calls - record the response. 

**Screenshots/Video**
The error response as seen by the caller:
![image](https://user-images.githubusercontent.com/3155222/81209817-e6679280-8fc8-11ea-81f9-dc38d76d9b79.png)

The missing payload recording in case of an error
![image](https://user-images.githubusercontent.com/3155222/81209886-0008da00-8fc9-11ea-860a-af13b1439fce.png)

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by letzya** [comment]
When fixing this as part of detailed_record, would be good to resolve #2495 to get control and be able to log only responses body and not the requests.

**Comment by rewsmith** [comment]
KNMI interested in this capability also, but would prefer to only log responses in the case of errors, as described in #2495 linked to above by @letzya.  They will be streaming large response data sets and wouldn't want to record that for 200 responses.

**Comment by letzya** [comment]
Expected release: 3.0.2
