### ISSUE TITLE
Key Quota Exceed event not fired by Monitor

### ISSUE THREAD

**Issue by gernest** [TykTechnologies/tyk#3078]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB]

**Describe the bug**
after key quota limit exceeded no event is fired by the monitor

**Reproduction steps**
TDB

**Actual behavior**
`"Quota trigger reached"` event is not fired

**Expected behavior**

`"Quota trigger reached"` event should be fired

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
Verified on release-2.9 branch
