### ISSUE TITLE
Using tyk via go import

### ISSUE THREAD

**Issue by abeMedia** [TykTechnologies/tyk#308]
I was wondering whether it's possible to also use Tyk as a library in go, setting the apps, configuration & policy details in the "master application". This would allow shipping APIs with the gateway already built-in as a single binary.

**Comment by lonelycode** [comment]
Nice idea - would require a pretty serious refactor though :-/

**Comment by abeMedia** [comment]
I guessed as much... Not to worry.
PS.: Thanks for my tyk swag! :)

**Comment by reza-ebrahimi** [comment]
After around 7 years, raising this up, Is it possible to use tyk as a library?
