### ISSUE TITLE
[TT-369] gRPC coprocess requests don't include valid :authority header

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk#3082]
**Branch/Environment/Version**
- Branch/Version: v2.9.3 of gateway, v1.9.3 of dashboard
- Environment: onprem (pro)

**Describe the bug**
Requests from Tyk sent to custom gRPC middleware plugin are considered invalid HTTP/2 as they do not include a valid `:authority` header.

**Reproduction steps**
Add gRPC plugin/middleware and reference from API. Initiate API call that will cause Tyk to dispatch a gRPC request to middleware.

**Actual behavior**
`:authority` header exists but has no value and the HTTP/2 (gRPC) request is considered invalid.

**Expected behavior**
`:authority` header should be populated with the correct host of the destination server so that HTTP/2 (gRPC) requests are valid.

**Screenshots**
Here is a screenshot of a Wireshark capture showing the HTTP/2 headers:
![image](https://user-images.githubusercontent.com/2243641/81741470-3bd9ee80-9464-11ea-965e-79f95bd1e5f4.png)

**Additional context**
We are trying to load balance gRPC requests with an HTTP/2 load balancer in our environment. We observed that the load balancer is dropping the gRPC requests (RST_STREAM). When we initiated dialog with the load balancer vendor, we were informed that the HTTP/2 request is invalid because of the `:authority` header.

Checking the RFC for HTTP/2, it appears indeed that the gRPC request should have this header if it is going to be considered valid. See https://tools.ietf.org/html/rfc7540#section-8.1.2.3.

**Comment by sedkis** [comment]
Can you inject a header via "modify headers" plugin to fix this?

**Comment by l3ender** [comment]
> Can you inject a header via "modify headers" plugin to fix this?

Tyk does not support proxying APIs that are gRPC (HTTP/2) - see https://github.com/TykTechnologies/tyk/issues/718.

**Comment by matiasinsaurralde** [comment]
Hi! Are you using UNIX sockets for the gRPC connection? We're investigating this issue and it could be helpful to know this.

**Comment by l3ender** [comment]
> Are you using UNIX sockets for the gRPC connection?

I'm not quite positive I understand the question. The gRPC connection is initiated by Tyk and received by our load balancer. I'm unsure of how the load balancer (Citrix Netscaler/ADC) establishes/maintains connections, but I believe it is built on a system running FreeBSD.

If desired, I can privately provide a network trace of the request/response between Tyk and the load balancer.

**Comment by matiasinsaurralde** [comment]
> > Are you using UNIX sockets for the gRPC connection?
> 
> I'm not quite positive I understand the question. The gRPC connection is initiated by Tyk and received by our load balancer. I'm unsure of how the load balancer (Citrix Netscaler/ADC) establishes/maintains connections, but I believe it is built on a system running FreeBSD.
> 
> If desired, I can privately provide a network trace of the request/response between Tyk and the load balancer.

When setting the gRPC server URL in `tyk.conf`, it's actually possible to use the `unix://` URL scheme so that the gRPC server connection is done using UNIX sockets (it was implemented [here](https://github.com/stepancheg/grpc-rust/pull/130)). It could be useful to clarify this as I've found related issues in the gRPC Go implementation. If you could confirm the type of URL that's being used in the `coprocess_grpc_server`parameter (`tyk.conf`), it could be useful for our investigation.
Feel free to share a network trace, my e-mail address is `matias AT tyk DOT io` 👍

**Comment by l3ender** [comment]
Thanks for the detail--I wasn't aware of using that protocol for gRPC. We are using TCP, like so:
```
TYK_GW_COPROCESSOPTIONS_COPROCESSGRPCSERVER="tcp://grpc.server.hostname:1234"
```

I also emailed you the trace. Thanks!

**Comment by joshblakeley** [comment]
> > Can you inject a header via "modify headers" plugin to fix this?
> 
> Tyk does not support proxying APIs that are gRPC (HTTP/2) - see #718.

Just to note here that we do support proxying gRPC APIs in the Gateway.

**Comment by matiasinsaurralde** [comment]
> Thanks for the detail--I wasn't aware of the other protocol for gRPC.
> 
> But we are using TCP, like so:
> 
> ```
> TYK_GW_COPROCESSOPTIONS_COPROCESSGRPCSERVER="tcp://grpc.server.hostname:1234"
> ```
> 
> I also emailed you the trace. Thanks!

Thanks, got it

**Comment by l3ender** [comment]
> Just to note here that we do support proxying gRPC APIs in the Gateway.

@joshblakeley I could be wrong, but it only supports gRPC proxying as pass-through/TCP, correct? With TCP proxying I don't think you'd be able to use any rewrite plugins to inspect the gRPC request and perform logic on it.

**Comment by joshblakeley** [comment]
> > Just to note here that we do support proxying gRPC APIs in the Gateway.
> 
> @joshblakeley I could be wrong, but it only supports gRPC proxying as pass-through/TCP, correct? With TCP proxying I don't think you'd be able to use any rewrite plugins to inspect the gRPC request and perform logic on it.

If you treat gRPC as POST requests over HTTP2 then you can do AuthN, rate limiting etc using headers so that give a bit more control. The limitation is you cant inspect the serialised body without the appropriate protocol buffers. 

More advanced functionality is on our radar currently. It would be good to know what you would value as a killer feature set.

**Comment by l3ender** [comment]
> More advanced functionality is on our radar currently. It would be good to know what you would value as a killer feature set.

Versioning and rewrite ability (based on values both in HTTP/2 headers and in protobuf) would probably be what we'd initially use the most.

**Comment by andyo-tyk** [comment]
Hi @l3ender,

Better late than never (?) we've implemented a change for the original request (adding the :authority header) and will be releasing in our upcoming 5.1 feature release and the next LTS patches.

Thank you for your patience and for supporting Tyk!
