### ISSUE TITLE
[TT-1995] - Set a non-zero default max request size, for better out of the box defensive posture

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3088]
The default max request size is unlimited, which risks the system be taken down by large HTTP requests. What do you think about a default like 1 MiB?

**Comment by andyo-tyk** [comment]
Whilst we haven't implemented this, there is facility to set request size limits per endpoint or globally per API as documented here: https://tyk.io/docs/basic-config-and-security/control-limit-traffic/request-size-limits/

We would not want to set an arbitrary maximum, however could consider a configuration option.

Given the existing flexibility, setting a configurable platform-wide size limit is not high on the priority list - though we may introduce something when next we are looking at the relevant section of the code.
