### ISSUE TITLE
The rate limit may not work 

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#310]
For develop branch,
Rate limit may not work When set to 1 limit per 100 seconds, in fact, the speed limit does not work.

**Comment by penhauer-xiao** [comment]
I have check you code,  may be package leakybucket.Storage  have issue.  :)

**Comment by lonelycode** [comment]
Or you've misconfigured your build - Tyk has 4 different rate limiters that are activated by different configurations. See the example config in the data directory for one that enables the leaky bucket.

**Comment by penhauer-xiao** [comment]
OK, Thanks @lonelycode
