### ISSUE TITLE
OpenTracing configuration can't be set via ENV variables

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#3104]
**Branch/Environment/Version**
- Branch/Version: master
- Environment: on-prem

**Describe the bug**
OpenTracing configuration can't be set via ENV variables which complicate docker setup a lot.

Tracing functionality configured using nested maps, and at the moment our library which used for reading the ENVs do not support such data structures.

**Reproduction steps**
You can set `TYK_GW_TRACING_ENABLED` and `TYK_GW_TRACING_NAME`, but not options `TYK_GW_TRACING_OPTIONS_REPORTER_URL`.

**Expected behavior**
All configuration should be possible to set via ENV variables.

**Comment by ilijabojanovic** [comment]
Verified
