### ISSUE TITLE
[Story] Decide on internal api logic

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#3107]
As a dashboard user I want it to have a clear overview over the Datasources (and their differences) so I know how I can configure them.

**Acceptance criteria**
-> Normalize list of data sources. (Tyk Rest can be HTTP, and Tyk GQL can be GQL)

-> adjust the UI so the user can see the difference from an UX perspective but behind the scenes same datasources are being used.

**Comment by christtyk** [comment]
@furkansenharputlu shall we close? Looks like you've tackled in 3.2
