### ISSUE TITLE
JWT payload decoding with b64dec fails

### ISSUE THREAD

**Issue by amanjeev** [TykTechnologies/tyk#3108]
**Branch/Environment/Version**
- Version: 2.9.4.1
- Environment: On-prem

**Describe the bug**
Consider this line in the middleware -
```js
var decodedPayload = JSON.parse(b64dec(tokenPayload));
```
The `tokenPayload` is the payload of a JWT that is being looked into for `exp` field. This fails because the token has an underscore (_) in it. This underscore comes from the fact that the user's lastname has "č". This underscore is an issue with the function `b64dec` as this is not URL decode.

**Reproduction steps**

1. Setup Tyk with a default API
2. Create a user with name with "č" in it or any other character that produced an underscore.
3. Setup a middleware that parses the OIDC JWT using a function like 
```js
function isTokenExpired(idToken) {
    var tokenPayload = idToken.split(".")[1]
    log(tokenPayload);
     
    var padding = tokenPayload.length % 4
    log(padding);
    if (padding != 0) {
        _.times((4 - padding), function() {
            tokenPayload += "="
        })
    }

    log(tokenPayload);
    
    var decodedPayload = JSON.parse(b64dec(tokenPayload));
    var tokenExpires = decodedPayload["exp"]
    var sysTime = (new Date).getTime()/1000 | 0;

    return sysTime>tokenExpires
}
```
4. Visit the URL of your API 

**Actual behavior**
Throws error 
```
level=error msg="Failed to base64 decode" error="illegal base64 data at input byte 538" prefix=jsvm 
```

**Expected behavior**
Expect to decode base64 urlencoded JWT.

**Additional context**
A possible solution is to add [two new JS functions here](https://github.com/TykTechnologies/tyk/blob/3fd28201758b5e3c0d8254103bad8f5097062405/gateway/mw_js_plugin.go#L407) that make use of `base64.URLEncoding.DecodeString(in)` and its counterpart. Perhaps can be called `urlb64dec` and `urlb64enc`?

You can see the [go playground link for additional example](https://play.golang.org/p/RjvtVJ9Of1H).

**Comment by buger** [comment]
You can try to use some native library to mitigate the issue https://github.com/beatgammit/base64-js/blob/master/index.js
(or use smth like python middleware).

Additionally, note that JWT claims are available as part of request context https://tyk.io/docs/getting-started/key-concepts/context-variables/, and you can use them in URL or Body rewrites.

**Comment by buger** [comment]
If you need to access this value inside JS you can try the following trick:
1) Add global header with the JWT value you want, like: `X-JWT-Name: $tyk_context.jwt_claims_Name`, and inside the JS middleware just read value from this header.

**Comment by amanjeev** [comment]
Sorry for the long pause, @buger! thank you for your suggestions. I do not think moving to Python is feasible. I was wondering if using Go is possible at this point to write middleware. 

Meanwhile, I will try reading the claims from the request context.

**Comment by amanjeev** [comment]
A minor question: Can the JSVM middlware we have right now (including Virtual endpoints), be converted to Go plugins?

**Comment by andyo-tyk** [comment]
Hi @amanjeev,

I'm reviewing old Github issues and found this one and spotted your last question is unanswered.

We don't have any tool to perform automatic conversion of your JSVM middleware to Go plugins (though perhaps Chat GPT could help set you in the right direction?) - however anything you can create in JS _can_ be implemented in Go.

We will be supporting per-endpoint Go Plugins from our upcoming Tyk 5.0 release - these are equivalent to Virtual Endpoints.

I hope this helps.

Thank you for your support for Tyk!
