### ISSUE TITLE
Why add an API or policy that takes 10 seconds to take effect?

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#311]
I have a question, why add an API or policy that takes 10 seconds to take effect? 
Can not be effective immediately? 
Or do it take effect within 1 second? Thank you

**Comment by lonelycode** [comment]
We don't use GitHub for a Q&A - only bugs - please use the community forum for questions.

The answer is that if you have multiple users changing apis or updating things in the dashboard then you get manybrelod requests in tandem, having a delay allows us to "store up" reloads (e.g. a use might update an API, realise they made a mistake, and then update again - with the delay we avoid reloading twice

**Comment by penhauer-xiao** [comment]
I know, Q&A will use the community forum for questions.
OK, you answer is very nice, i see.
