### ISSUE TITLE
HTTP request signing does not work with query params

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#3113]
**Branch/Environment/Version**
- Branch/Version: 2.9
- Environment: on-prem

**Describe the bug**
At the moment we use path without query params, but RFC states that query params are the part of URL https://tools.ietf.org/id/draft-cavage-http-signatures-10.html#canonicalization
**Reproduction steps**
1) Enable HTTP signature by setting:
```
 "request_signing": {
  "is_enabled": true,
  "secret": "<some_secret>",
  "algorithm": "hmac-sha256"
  "key": "<any-id>"
}
```
2) Sent the the request to the upstream, with URL containing query params
3) Signature string will be based on path value without query

**Actual behavior**
With query params signature always fail

**Expected behavior**
It should respect query params

**Comment by ilijabojanovic** [comment]
Verified
