### ISSUE TITLE
[TT-750] Allow Windows native run for testing

### ISSUE THREAD

**Issue by educroquet** [TykTechnologies/tyk#3116]
Under some corporate situations, it is more practical to be able to run Tyk natively on a Windows workstation for local testing.

Enabling WSL or some kind of VirtualBox, or getting hand on a genuine Linux machine may be cumbersome for just such quick local testing needs.

It'll be great to have some kind of config to build and then run Tyk GW natively on Windows.

I've managed to get a Windows native REDIS binary from MS Open Tech : https://github.com/ServiceStack/redis-windows/raw/master/downloads/redis-latest.zip

I've managed to run 2.9.3.2 with following source code modifications, by mainly disabling code lines :
- `checkup/checkup.go` : 
  - disable `syscall`  import
  - disable the whole content of func `fileDescriptors`
- `gateway/redis_signal_handle_config.go` : 
  - disable `syscall` import
  - disable `syscall.kill SIGUSR2`
- `gateway/proxy_muxer.go` : 
  - disable `again` import
  - disable all lines using `again` 
  - disable the `listenAddress` var in `swap()` as not used
- `gateway/server.go` : 
  - disable `log/syslog`, `logrus_syslog` and `again` imports
  - disable content of `if UseSysLog` in `setupLogger`
  - disable `onFork`
  - disable lines using `again` 
  - in `Start()` : replace `again.Wait()` by `b1 := make([]byte,1) ; os.Stdin.Read(b1)`
  - in `Start()` : if not using REDIS : disable `storage.IsConnected` check

Maybe some sustainable way will be to have Windows mocks of `syscall`, `syslog`, `logrus_syslog`, `again` and switch on them at build time, so no source code lines needs to be modified.

**Comment by educroquet** [comment]
May it be related to https://github.com/TykTechnologies/tyk/issues/3036 ?

**Comment by letzya** [comment]
Hi @educroquet - if you are able to submit a PR we will accept it.

**Comment by educroquet** [comment]
Hi @letzya , thanks for the proposal but making an acceptable PR (without just hard coded disabled code lines) is not possible for me currently.
And I guess there is low need from Tyk's users for such feature.
I may try later on if I get some opportunity.

**Comment by andyo-tyk** [comment]
We don't currently have plans to support Windows native running for Tyk, though the interest is noted, so I will close this ticket.

If this is still of specific interest, please reopen and we can review our customer research.
