### ISSUE TITLE
Log Browser sometimes shows Request/Response bodies unrelated to current log

### ISSUE THREAD

**Issue by educroquet** [TykTechnologies/tyk#3118]
**Branch/Environment/Version**
- Branch/Version: Release 2.9.3
- Environment: On-prem

**Describe the bug**
Log Browser sometimes shows Request/Response bodies that do not match the log information. It is not systematic but is seen often enough to be an usability issue.

**Screenshots**
Here are two examples:

![image](https://user-images.githubusercontent.com/65402192/83546441-f6f42580-a500-11ea-9eed-1c7b47dc32b4.png)

![image](https://user-images.githubusercontent.com/65402192/83545916-33735180-a500-11ea-9d91-fc08e76cc2d0.png)

**Comment by buger** [comment]
Fixed in 2.9.4.1

Thank you for reporting!
