### ISSUE TITLE
TT-630: Provide non root installation procedure from a tarball

### ISSUE THREAD

**Issue by educroquet** [TykTechnologies/tyk#3119]
Installing Tyk components from rpm/deb binaries packages forces the usage of a root installation / execution, which is not the expected one under some DevSecOps context, where Docker is also not an option.

We'd like to have the Tyk binaries (intel) provided as basic tarball files (.tgz, or any commonly supported zip like archives) and with installation scripts that can be executed by a non-root user. 

We have managed to extract the binaries from the current RPM file and to do a non-root installation of Tyk GW within a user home, but this is still very manual and error prone, so we would prefer to rely on official tarball files and an official procedure from Tyk.io documentation site.

**Comment by letzya** [comment]
Grafana example: 
https://grafana.com/grafana/download/6.6.2?platform=linux
`wget https://dl.grafana.com/oss/release/grafana-6.6.2.linux-amd64.tar.gz `

**Comment by alephnull** [comment]
We provided tarballs on the github release page for a while but stopped when we stopped making automated github releases.
We still build tarballs via goreleaser but have no public place for them. If a home can be made for tarballs, tarballs can be posted there.

**Comment by andyo-tyk** [comment]
Closing this as "won't do"; if you still need this then please comment and we can look further into the options.
