### ISSUE TITLE
ERROR main: Duplicate listen path found, skipping. API ID: 93956c2e9ce811e6a0fe080027b4ee30

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#312]
Why different users (different organizations) to create two APIs, when their Listen path is the same, it will report the following error:

[Oct 28 16:42:44] ERROR main: Duplicate listen path found, skipping. API ID: 93956c2e9ce811e6a0fe080027b4ee30 
[Oct 28 16:42:44]  WARN main: ----> Skipped! 
[Oct 28 16:42:44]  INFO main: --> Loading API: yyyyyy 
[Oct 28 16:42:44] ERROR main: Duplicate listen path found, skipping. API ID: 790c42119cea11e6a0fe080027b4ee30 
[Oct 28 16:42:44]  WARN main: ----> Skipped!

**Comment by lonelycode** [comment]
Because you can only have one listennpath per API - again this is a question for our community forum.

You can share listen paths across different domains, so they can be the same so long as the custom domain is different.

**Comment by penhauer-xiao** [comment]
Oh, this question for  community forum as also, I know

You mean that the Listen Path is the same case, Custom Domain (do not include 'http: //' or 'https: //') can be filled differently for different users (different organizations)

**Comment by lonelycode** [comment]
That is correct... if the domains are different then there is no listener clash.

**Comment by penhauer-xiao** [comment]
Thanks very much @lonelycode

**Comment by penhauer-xiao** [comment]
@lonelycode 
The same issue as following when the domains are different. :)

[Oct 28 18:03:01] ERROR main: Duplicate listen path found, skipping. API ID: aff8ccba9cf511e6a0fe080027b4ee30  
[Oct 28 18:03:01]  WARN main: ----> Skipped!

**Comment by penhauer-xiao** [comment]
I know, I must to config enable_custom_domains is true  :)
