### ISSUE TITLE
[TT-393] Be able to augment/merge Swagger/OAI definitions into existing Tyk APIs rather than replace through import

### ISSUE THREAD

**Issue by chris-fewtrell** [TykTechnologies/tyk#3121]
**Is your feature request related to a problem? Please describe.**
Wish to evolve an API Definition through use of managed OAI/Swagger definitions which are developed externally to Tyk

**Describe the solution you'd like**
Be able to import an initial API definition using a Swagger/OAI definition as is presently possible, but after initial creation be able to "augment" or "merge" another Swagger/OAI Definition atop the existing Tyk API.

As an example, a pre-existing Tyk API exists that requires authorization key, and is defined with the endpoints.

```
/some-service/users
/some-service/users/authorize
```

In addition the /users/authorize endpoint has the Ingore middleware applied so it so it can be used keyless.

API developer wishes to create a new path by augmenting the API with an updated Swagger definition that has the defined endpoints:

```
/some-service/users
/some-service/users/authorize
/some-service/users/operate
```

When merging this into the existing Tyk API, the users and /some-service/user/authorize endpoints are ignored leaving them defined as-is in Tyk (meaning the Ignore middleware is still configured against /some-service/users/authorize), but adds a new endpoint for /some-service/users/operate defined.

Use of a separate endpoint from the pre-existing /api/import/swagger endpoint.

**Describe alternatives you've considered**
Use of tyk-sync and what would need to be a selection of custom written scripts to convert OAI/Swagger to Tyk API Definitions and then perform a suitable JSON merge, and then use tyk-sync to push updated definition into Dashboard/Gateway. Is somewhat more convoluted with more moving parts and less desirable.

**Additional context**
Taken from Ticket 10419

**Comment by bmonteiro** [comment]
@chris-fewtrell thx!
