### ISSUE TITLE
Tyk consumes the entire system memory after running for two days, the system becomes too slow

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#314]
Perhaps this issue is more appropriate in Github submission?

When the Tyk run for two days, it is the entire system memory is consumed, and the system becomes very slow, can not be used normally, the shell terminal input command for a long time to execute; Tyk consumes 92.2 percent of the system

As of Tyk 2.2

```
$ ps auxw|head -1;ps auxw|sort -rn -k4|head -2
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     32522  9.2 92.2 26406296 6449248 ?    Sl   Oct28 356:07 /opt/tyk-gateway/tyk --conf=/etc/tyk-gateway/tyk.conf
root     32504  1.9  1.0 630568 72576 ?        Sl   Oct28  74:50 /opt/tyk-pump/tyk-pump -c=/etc/tyk-pump/tyk_pump.conf
```

**Comment by james-tyk** [comment]
Hi

This looks like a configuration issue - first post questions in community.tyk.io so you can work with people to troubleshoot and establish whether its a configuration issue or a bug.

If a bug is identified, then use github, but otherwise community.tyk.io is the place to start

Thanks


James

**Comment by penhauer-xiao** [comment]
@james-tyk  
OK
