### ISSUE TITLE
Dashboard playground doesn't work for proxy mode GraphQL api

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#3155]
<img width="611" alt="Screenshot 2020-06-17 at 15 44 50" src="https://user-images.githubusercontent.com/25665432/84918000-bda6e280-b0c8-11ea-929c-24a07abc5511.png">

<img width="795" alt="Screenshot 2020-06-17 at 15 46 26" src="https://user-images.githubusercontent.com/25665432/84918053-d0211c00-b0c8-11ea-9f7d-d9f189b6c357.png">

**Comment by ilijabojanovic** [comment]
Verified
