### ISSUE TITLE
[TT-1996] - Option to log, normalize URIs with extra slashes, without presenting 3xx redirects

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3159]
**Is your feature request related to a problem? Please describe.**

I have a need to normalize URIs that exhibit redundant forward slashes, in the non-URI-encoded section of the path. It would be great to have an option to mention observances of this in the logs, while still presenting a normal, non-redirect response to the user.

**Describe alternatives you've considered**

Writing an alternative to Tyk with more control over how URIs are normalized.

**Comment by andyo-tyk** [comment]
I'm closing this as "won't fix" as we've not had subsequent requests for this feature and the use case is not clear.

If this is still a requirement, please comment and we can discuss the driver behind your request and work out what we can do to improve the behaviour of Tyk.

Thanks for supporting Tyk.
