### ISSUE TITLE
Clear cache?

### ISSUE THREAD

**Issue by bityardigans** [TykTechnologies/tyk#316]
Is there anyway to clear caching? We had it enabled then disabled it but keep receiving random cached 404s (we had a prior issue that resulted in 404s for the request in question and they got cached).

**Comment by lonelycode** [comment]
https://github.com/TykTechnologies/tyk/blob/master/CHANGELOG.md

See the third bullet point - this let's you clear cache.

You can also set what status codes to cache in your API definition

**Comment by bityardigans** [comment]
I seem to not be able to find this particular endpoint; calls to it result in a 404...we are running the current version and everything else seems to work...am I missing something?

**Comment by lonelycode** [comment]
V2.2.0.28?

**Comment by bityardigans** [comment]
That is a great question. I thought so but looking at the packagecloud repo now we are not so sure. Let me have our ops guy do an update and I will let you know.

**Comment by bityardigans** [comment]
Confirmed- we are on 2.2.0.28

**Comment by lonelycode** [comment]
You are calling the gateway API right? Not the dashboard API.

**Comment by bityardigans** [comment]
I am- but that appears to be cached as well? Basically we lost an elastic IP today and had to reallocate; it thru tyk for a loop and now we cannot seem to get out of the intermittent 404s- the underlying api's tyk is pointing to are working fine we just keep getting served up 404s randomly when it didn't happen prior until the elastic IP snafu. 

I still cannot hit the endpoint; i get a {"status":"error","error":"Forbidden"} OR a 404, basically alternating every few hits. I am passing the x-tyk-authorization header w/ the api key...is this the only way to clear the cache?

**Comment by lonelycode** [comment]
If it were cached (????) then you would see a header that states its cached specifically by tyk: `X-Tyk-Cached-Reponse` - it's very unlikely unless you have Tyk proxying itself.

If you are getting intermittent 404s, are you running a load balancer in front of Tyk? If so, are all the attached instances running the same application with the same configuration?

The forbidden error is promising.

If you have ssh access to the gateway boxes you can just run the curl command against local host. You might just have the wrong secret.

**Comment by bityardigans** [comment]
So we do not see the header; Its just very bizarre and it all started when amazon deleted an assigned elastic IP for some idiotic reason. We are starting to suspect the whole install may have somehow gotten fubar, specifically the elastic load balancer we use to route traffic. Ill keep you posted- you have been exceptionally helpful by the way ;)

**Comment by bityardigans** [comment]
SUCCESS! totally the ELBs fault. Thanks again...
