### ISSUE TITLE
Filtering by Api version isn't possible on Activity by Api page

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3160]
**Branch/Environment/Version**
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
2.9.4, 3.0

- Environment: [e.g. On-prem/Hybrid/MDCB]
On prem and cloud

**Describe the bug**
When inside "endpoint analytics" and inside Activity for Endpoint, I try to Filter By Version but it doesn't display any data.

**Reproduction steps**

Reproduction steps:

Create api definition with 3 versions
Generate traffic for all versions of that api
Log on dashboard
Go to Activity by Api page
Select that api definition

**Actual behavior**
In versions drop menu we don't have all versions of that api. Since /api/versions endpoint does not return correct data. Same issue is visible on API Activity Dashboard page.

**Expected behavior**
See filtering by version

**Screenshots/Video**
https://youtu.be/HyXOF8W6alk

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by bmonteiro** [comment]
@letzya thx!

**Comment by christtyk** [comment]
Note on Jira TT-95 = solved.
