### ISSUE TITLE
[TT-400] Do not track MW for an endpoint does not stop Tyk from collecting analytics for the call

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3161]
**Branch/Environment/Version**
3.0
- Environment: [e.g. On-prem/Hybrid/MDCB]
cloud, on prem

**Describe the bug**
Per video - even if you set "do not track" the endpoint, you can still see it in aggregated analytics and the log browser.
 
**Reproduction steps**
https://tyk.io/docs/advanced-configuration/transform-traffic/endpoint-designer/#do-not-track-endpoint

1. add endpoint 
2.choose "do not track"
3. Make an API call to the endpoint
4. Check the log browser
5. Check the activity per API and see the counter has been incremented 

**Actual behavior**

It’s important for users that need to skip  endpoints (for instance a special endpoint used by a 3rd party product to do heathcheck)

**Expected behavior**

Per docs - ignore any record of the call. 

**Screenshots/Video**

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by sedkis** [comment]
Confirmed. Work around possible by using the Endpoint Designer
<img width="573" alt="image" src="https://user-images.githubusercontent.com/8964621/85561823-eca5e280-b5f9-11ea-9526-dff3f814c738.png">

**Comment by letzya** [comment]
The workaround is difficult in case you have health check endpoint per API since it means double the number of API just for this and also a lot of work to create those temporary API definitions.

**Comment by sedkis** [comment]
Confirmed

**Comment by letzya** [comment]
https://tyktech.atlassian.net/browse/TT-400

**Comment by letzya** [comment]
The bug was fixed and is due for the next release.
