### ISSUE TITLE
API calls takes longer in slaved gw when MDCB is down and analytics are enabled

### ISSUE THREAD

**Issue by sredxny** [TykTechnologies/tyk#3162]
**Branch/Environment/Version**
- Branch/Version:  Master
- Environment: MDCB

**Describe the bug**
In a MDCB environment when we have set `"enable_analytics": true` the response of the request for any API gets affected and increased when MDCB is down.

**Reproduction steps**

1. Execute Tyk in MDCB environment
2. In the config file for the slave gateway set `enable_analytics` to true
3. Register an API
4. Consume API in slave (and check the time taken to get a response)
5. Shut down tyk-sink (MDCB)
6. Consume again the API (and check again the time taken, it was increased)

**Actual behavior**
Api response time gets increased when MDCB is down and `enable_analytics` is true

**Expected behavior**
The response time should not be affected, or at least it should not take that longer.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**
It was tested using an hybrid pump as well as RPC, the result was the same.

**Comment by christtyk** [comment]
@sredxny was this merged/moved to jira/can we close?

**Comment by christtyk** [comment]
released 3.2
