### ISSUE TITLE
[TT-376 & TT-7195] Validate the url and input payload as per Swagger/OAS spec

### ISSUE THREAD

**Issue by educroquet** [TykTechnologies/tyk#3164]
**Is your feature request related to a problem? Please describe.**
Currently the swagger import is only activating the analytics by using the specified verb-paths in swagger, but it does not activate any request validation. As Swagger/OAS has become the de-facto standard to describe REST/JSON APIs, this is a feature available in various API Gateway solutions and that is often requested when using an API Gateway to securely expose APIs to internet.

**Describe the solution you'd like**
The swagger import, with some options, should generate a Tyk API Definition from a Swagger 2 or OAS3 json specification file, that :
- ensure that the url is properly matched and not mistaken with wrong path :
  - eg: if spec contains paths `/items/{id}` and `/items/default`, `/items/default` must match first
  - {x} placeholders must not be empty, especially ending one : transform as internal regexp `([^/]+)`
  - path is  matched to the end : add a `$` at the end of regexp
- verify the type/format of the url path params
- verify the url query params and their type/format
- ensure that required query params are present
- validate the json input payload
- ensure that optional or OAS3 nullable json fields are not rejected if present with a null value (also for enums)
- ensure that required fields are present, and without the null value
- reject the call in case of unknown path/query param or json field, and if value type/format is invalid
- consider unknown fields are rejected if additionalProperties field is missing in object schema
- support same type/format as in Swagger/OAS, noticeably : date, uuid, int32, int64, double, byte
- show a warning on import in case of unsupported type/format

**Describe alternatives you've considered**
We have implemented in javascript a mapper from swagger 2 and oas 3 to Tyk definition, but we do not wish to maintain it. And as of today it cannot fully validate the url, nor fully the payload depending on needed type formats, due to lack of related Tyk features.

**Additional context**
Apart from the swagger importer, this requires also enhancements on the white_list and validate_json plugins, or some new one.

**Comment by educroquet** [comment]
Mmmh, I should instead have add a comment in #2999 ...

**Comment by andyo-tyk** [comment]
Hi,

Per the comment added to issue [2999](https://github.com/TykTechnologies/tyk/issues/2999), we will complete the OAS API import functionality in the upcoming Tyk 5.0 release.

Thanks for your patience with this.

**Comment by andyo-tyk** [comment]
This is fixed in Tyk 5.0; please see the release notes [here](https://tyk.io/docs/release-notes/version-5.0/).

Thank you for your support of Tyk!
