### ISSUE TITLE
[TT-157] Reset Quota not working on Hybrid Gateway

### ISSUE THREAD

**Issue by rewsmith** [TykTechnologies/tyk#3165]
**Branch/Environment/Version**
- Branch/Version: 2.9
- Environment: Hybrid

**Describe the bug**
On the Dashboard portal developer page there is an option to `Reset Quota` for any keys they have currently.  For hybrid gateways this does not reset the quota.

**Reproduction steps**

1. In the Dashboard create a new key (Portal Management -> Developers -> <Developer-name> -> New Key
2. Select a policy with a low quota (e.g. 10 requests per hour)
3. Request key
4. Exhaust the quota by sending multiple requests until `Quota Exceeded` error observed
5. From same Developer page in Dashboard, select `Reset Quota` from Keys Options dropdown
6. Send request again

**Actual behavior**
Still see `Quota Exceeded` error

**Expected behavior**
After a reset the quota should be reset and requests should return success response.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by ilijabojanovic** [comment]
This is the issue with Org metadata. On org obj we are missing `hashed_key` event. 
https://github.com/TykTechnologies/tyk-cloud/issues/92

**Comment by andyo-tyk** [comment]
This issue is not reproducible on current Tyk, so I will close this as fixed.
