### ISSUE TITLE
For speed limit, if every 60 seconds is set to 30, how to get the current real-time speed limit? By api call? How?

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#317]
as title

**Comment by james-tyk** [comment]
Hi

As a support request, this should be posted to community.tyk.io - we try to keep Github for engineering topics.

Please post it there and someone will get back to you.

**Comment by penhauer-xiao** [comment]
Sorry, I have been forgot, Thanks @james-tyk, I will post this topic to the community.tyk.io.
