### ISSUE TITLE
For REST api, if graphql execution mode is set to executionEngine, it fails

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/tyk#3172]
Master, 2.10

Steps to reproduce:
1. Create a REST api
2. Go to raw api definition
3. Set `"execution_mode": "executionEngine"`

**Actual Behavior**
This will error.

**Expected Behavior**
If graphql is not enabled, execution mode shouldn't be cared.

**Comment by ilijabojanovic** [comment]
Verified
