### ISSUE TITLE
[TT-1999] - Better status code on Redis disconnect

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3178]
**Is your feature request related to a problem? Please describe.**

When Redis experiences an outage, then Tyk calls are met with 403's, which isn't actually the case. The user is supplying valid credentials, it's just that:

A) Tyk doesn't cache these
B) Tyk depends on an external storage resource which is unavailable

**Describe the solution you'd like**

In the event that Redis is down, any failed authentication requests should respond with HTTP status code 5xx, e.g. 500, in order to assist users and operators with diagnosing the problem more quickly.

**Describe alternatives you've considered**

nginx+

**Additional context**

Some paranoid users might suggest that 500 gives "too much" information to attackers, but I think if Redis is down, it's much more likely a safety issue than a DoS attack. The one bit of information leaked, that the Tyk server experienced a problem, doesn't give attackers any actionable information. But it gives server maintainers a faster root cause analysis.

**Comment by andyo-tyk** [comment]
Closing as this is not currently on our roadmap, but we may return to it later if there is renewed interest from users.
