### ISSUE TITLE
lonelycode/logrus-graylog-hook/graylog_hook.go:87: too few values in struct initializer

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#318]
$ tyk/vendor/github.com/lonelycode/logrus-graylog-hook
vendor/github.com/lonelycode/logrus-graylog-hook/graylog_hook.go:87: too few values in struct initializer
$ tyk/vendor/rsc.io/letsencrypt/vendor/github.com/xenolf/lego/acme
vendor/rsc.io/letsencrypt/vendor/github.com/xenolf/lego/acme/messages.go:33: undefined: jose.JsonWebKey

Package logrus have been update,    missing param Buffer

`type Entry struct {
	Logger *Logger

	// Contains all the fields set by the user.
	Data Fields

	// Time at which the log entry was created
	Time time.Time

	// Level the log entry was logged at: Debug, Info, Warn, Error, Fatal or Panic
	Level Level

	// Message passed to Debug, Info, Warn, Error, Fatal or Panic
	Message string

	// When formatter is called in entry.log(), an Buffer may be set to entry
	Buffer *bytes.Buffer
}` 

issue 2:    gopkg.in/square/go-jose.v1, The field JsonWebKey,  May bee have been removed

**Comment by matiasinsaurralde** [comment]
Hi, have you updated all these packages using `go get -u`?
When do you get these errors, is it when building `develop`?

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde    Yes,   This version is develop,  I have bee check, Tyk code is too old for package lonelycode/logrus-graylog-hook

**Comment by penhauer-xiao** [comment]
@matiasinsaurralde  The package Jose  and logrus  have been update, so the Tyk couldn't compile.

**Comment by lonelycode** [comment]
@penhauer-xiao I just tried to replicate this by *deleting* logrus and re-getting it, and also `go get -u` on the graylog hook (which is my fork, and I know I haven't broken it). Tyk compiles fine.

I know you are using glide and doing all sorts of wierd things with the vendoring - we ship with the venored libs we want to track in the repo, if you have changed that, you may have broken your own build

Our CI tool, which build from develop and pull all deps every build, [build fine too](https://travis-ci.org/TykTechnologies/tyk).
