### ISSUE TITLE
[TT-1950] Allow Developer to see key stats in the dev portal

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#3181]
Currently developers can't see their key stats in the portal dashboard. Could we include some graph/reporting to give developers insight on their key usage. 

Client request - have mentioned upcoming shaping of dev portal.

**Comment by Chris-vincic** [comment]
At the moment, developers can see the key stats, but only if the API is published through the portal.

But some APIs are not to be published (ie public) ; which do not mean that their use is not to be tracked by the developer.

If only the stats of API in the catalog can be seen from the devs, one solution could be to be able to set some APIs as hidden/private in the catalog: they would not appear when looking at the catalog, but their stats would then appear in the developer dashboard.

**Comment by andyo-tyk** [comment]
This will not be implemented for the Classic Developer Portal, but is supported in the Enterprise Developer Portal
