### ISSUE TITLE
[TT-399] Improved Endpoint stats

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#3189]
At the moment, it is not possible when looking at an endpoint stats to see which keys are using it (the most).
Reciprocally, when looking at a key, one can not see which endpoints it uses the most.

Can we break down end point statistics to a more granular level for users within the UI?

Client request.

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and will be considered as we evolve the Dashboard experience.
Thank you for supporting Tyk.
