### ISSUE TITLE
[TT-405] Make sure that the path based quota's are selected over the generic quota's when combining multiple Catalogue entries in a single API key

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#3191]
You can enable 'subscribing to multiple APIs with a single key' - this is leading to some quota issues for users who are using a single key for multiple APIs. 

Tested:

- One entry with restrictive quotas and access to all paths of the API
- Two entries with path specific quotas which are more generous and which only give access to a specific path via path-based permissions

Noticed that when I use one API key for these three Catalogue entries, the most restrictive quota's are applied for each path, even when the path based policy gives a higher quota for a certain path.

--

Issue only found as user wants to allow developers to use multiple APIs with the same key, and this functionality is the workaround for it at the moment - might be another FR.

**Comment by andyo-tyk** [comment]
Closing as stale
