### ISSUE TITLE
Ability to access using the wrong secret key

### ISSUE THREAD

**Issue by dunebuggie** [TykTechnologies/tyk#3192]
**Describe the bug**
Tried to create a secret key, but when trying to access the service (proxy) if the secret is `1mysecretkey`, the API validated `1mysecretkeyXX` where XX could be anything. 

**Actual behavior**
It’s accepting anything up to 3 characters after the actual key. If `1mysecretkey` is the actual key, then `1mysecretkey123` works but `1mysecretkey1234` doesn't.

**Expected behavior**
Anything apart from the actual key shouldn't be accepted.

**Comment by sreekanthgs** [comment]
Can also confirm this. Have tried and same was the result.

**Comment by sreekanthgs** [comment]
A similar behavior was seen for basic auth password as well. Any reason for such?

**Comment by sedkis** [comment]
This is due to the default hashing function (Murmer32).  As a result, the new default hashing function is now Murmer64, which is a stronger level hash, which prevents this from happening.

**Comment by sreekanthgs** [comment]
> This is due to the default hashing function (Murmer32). As a result, the new default hashing function is now Murmer64, which is a stronger level hash, which prevents this from happening.

Thank you for the update. Has this change gone into a release yet? The latest stable from Docker Hub still has this issue.

**Comment by sedkis** [comment]
> > This is due to the default hashing function (Murmer32). As a result, the new default hashing function is now Murmer64, which is a stronger level hash, which prevents this from happening.
> 
> Thank you for the update. Has this change gone into a release yet? The latest stable from Docker Hub still has this issue.

Murmer32 is default because it is a good balance between performance and security.  You can change this in the `tyk.conf` file anytime.

You can read more about [that here.](https://tyk.io/docs/basic-config-and-security/security/#custom-key-hash-algorithms)

**Comment by sreekanthgs** [comment]
Thank you for the update.
