### ISSUE TITLE
Go Custom Middleware API in addition to JS Custom Middleware API

### ISSUE THREAD

**Issue by mheiber** [TykTechnologies/tyk#320]
Writing plugins for custom middleware in Go could improve throughput by removing the need to deserialize / serialize to/from JSON.

It looks like this wouldn't require many changes to: https://github.com/TykTechnologies/tyk/blob/976ddd8b72bd60c8be682e494b78955c57da10d1/plugins.go to allow for plugins to be written in Go.

The part I'm not sure about is how to load plugins written in Go without rebuilding Tyk from source. Is this possible?

**Comment by lonelycode** [comment]
We're looking into Go plugins for Tyk, but it will be dependent on v1.8 of Go as that introduces dynamic linking.

For v2.3 (released this/next week), there is a major update regarding plugins.

**Comment by mheiber** [comment]
@lonelycode thanks for this information—can you advise on where I can see what these updates are regarding plugins? Is there a repo for the v2.3 documentation?
