### ISSUE TITLE
[TT-2000] - Default hash algorithm to SHA256 for FIPS compliance

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3204]
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf

**Comment by buger** [comment]
Hi! Can you add a bit more context to it? 
With Tyk default algorithm is fast murmur64 but optionally you can set sha256, so if you need to pass verification it should be enough. 

Am I missing anything?

**Comment by mcandre** [comment]
My performance tests don't show much of a measurable time difference between them. And murmur32, the default configuration value, has a nasty habit of implicitly truncating hashes when validating, which can be hazardous.

**Comment by andyo-tyk** [comment]
Closing this ticket, as FIPS compliance is being actively discussed in https://github.com/TykTechnologies/tyk/issues/4559
