### ISSUE TITLE
[TT-2001] - Memoized API key hashing

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3205]
**Is your feature request related to a problem? Please describe.**

Hashing API keys uses an amount of CPU per request, that adds a measurable latency in high-volume traffic.

**Describe the solution you'd like**

Cache frequently used API keys in a configurable, fixed size hashmap, to offset performance loss of different hash implementations.

**Describe alternatives you've considered**

Buying Cray servers

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap and we will ensure this is considered when we next look at this part of the code; I am closing the request here due to the age.
