### ISSUE TITLE
Sometines API-s with custom header returned 404 error

### ISSUE THREAD

**Issue by nguyenhuuloc304** [TykTechnologies/tyk#3207]
**Branch/Environment/Version**
We are using TYK v1.7.0 on Docker

**Describe the bug**
We added one more header to API-s named **customerName** and in Tyk we configured CORS options for **Enable CORS** and **Allow credentials**. We also add to **Allowed header** for header **customerName** (camelCase).  But sometimes various API-s returned 404 error, sometimes not and not all of API-s faced this error. When we are facing this error, we added another header **customername** (lower case) to  **Allowed header**. Then the issue was solved. 

But when we reupload TYK definitions again with both **customerName** (camelCase) &  **customername** (lower case) for **Allowed header**. We encountered the same 404 error. So we removed the header **customerName** (camelCase).
The issue was solved.

Then we reupload TYK definitions again with **only** **customername** (lower case) for **Allowed header**. 404 error happened again, and we had to add **customerName** (camelCase). Then it was resolved.

This problem are in all our Environments. But once resolved, the problem doesn't reoccur until the TYK definitions are reuploaded.

I know we used an old version 1.7. But not sure in the latest version, we resolved this issue? then we can convince our boss to approve upgrading to newest version.

If anyone used to encounter this problem. could you help to advise how to fix it. Thank you in advance.

**Comment by christtyk** [comment]
Hey @nguyenhuuloc304 is this still a problem for you? As you're on an old version we'll need to investigate a bit so send an email to support@tyk.io if it's still a problem and we can support there
