### ISSUE TITLE
[TT-2002] - Faster failover for Redis connections

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3209]
**Is your feature request related to a problem? Please describe.**

In the event of Redis primary role shuffling, detect this situation faster, so that no Tyk queries fail during the transition.

**Describe the solution you'd like**

For example, shorten any timeouts / retry loops / DNS caches involved.

**Comment by andyo-tyk** [comment]
Thanks for your suggestion; this is logged as an area to investigate on our performance improvement roadmap.
I am closing the request here due to the age.

Thank you for supporting Tyk.
