### ISSUE TITLE
[TT-425] Enhanced endpoint statistics 

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#3216]
**Is your feature request related to a problem? Please describe.**
At the moment, endpoint statistics do not support the declared versions.
For example, v1/res1 and v2/res1 statistics appear on the same 'res1' entry if the version is not specified in the endpoint declaration, version that has already been set in the dedicated tab and selected.
It does not allow to follow api version usage, especially the progress of an api version migration.

**Describe the solution you'd like**
Endpoint statistics should display the various endpoint versions, and the stats browsing should allow to drill down from API -> versions -> endpoint statistics -> metrics (hits, and upstream latency and errors too).

Metrics are a really important matter in API Mngmt, serving various objectives :
- client contract follow up
- global usage
- api version migration
- ...

I do understand that when launching a new APIM it is not the most important feature, but those stats are needed and maybe it is time for some sensible enhancements for this part of the product.

**Comment by agata-wit** [comment]
Hey @christtyk I'll include this one as part of our squad discussion on Endpoint designer UX as part of a larger discussion on how we can provide best experience around endpoints in general. I'll keep you posted.

**Comment by andyo-tyk** [comment]
Thank you for the suggestion.

This idea sits in a larger piece of work that we are considering regarding Tyk Dashboard's analytics capability; unfortunately I don't have a timescale for that so will close this as "not currently planned". 

We are fixing an issue in Tyk 5.1 (and our June LTS patches) whereby it was not possible to filter API analytics by version, though this won't give you the entirety of this enhancement request.

**Comment by Chris-vincic** [comment]
Hello,

I hope that you will consider this feature request in a close version: we have several API versioned, and at the moment we can not track if old ones are still used when migrating.

We are still in v4, but if at least the version filter does work, it would be an acceptable mitigation even if I believe considering v1/res and v2/res to be the same endpoint is false.

Best regards
