### ISSUE TITLE
Document db: Api listing does not work

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3228]
**Do you want to request a *feature* or report a *bug*?**
A bug reported in the [dashboard repo](https://github.com/TykTechnologies/tyk-analytics/issues/2032)

**Branch/Environment**
- Branch: Master/Stable 3.0
- Environment: All

**Describe the bug**
On latest release 3.0 api listing does not work if database is document db. On Mongo db's everything working as expected.

**Reproduction steps**
1. Setup document db in tyk_analytics 
2. Start dashboard
3. Log in on dashboard and go to api's page

**Actual behavior**
We have console errors and page is blank.

```
[Jul 22 12:50:01]  INFO ui-notifications: Client added clientsNum=1 orgID=5e5e31d59633d70782bfac6e
[Jul 22 12:50:02] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:02] ERROR option collation is currently not supported.
[Jul 22 12:50:02] ERROR Could not get API Defintitions for Org
[Jul 22 12:50:04] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:04] ERROR option collation is currently not supported.
[Jul 22 12:50:04] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:04] ERROR option collation is currently not supported.
[Jul 22 12:50:04] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:04] ERROR option collation is currently not supported.
[Jul 22 12:50:04] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:04] ERROR option collation is currently not supported.
[Jul 22 12:50:16] ERROR Failed to get certificates: Get https://www.tyk-test.com:8181/tyk/certs/?org_id=5e5e31d59633d70782bfac6e: dial tcp 127.0.0.1:8181: connect: connection refused
[Jul 22 12:50:18] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:18] ERROR option collation is currently not supported.
[Jul 22 12:50:19] ERROR Something went wrong, couldn't get Api list org_id=5e5e31d59633d70782bfac6e
[Jul 22 12:50:19] ERROR option collation is currently not supported.
```

**Expected behavior**
Api listing should work on document db's.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Browser/Os (please complete the following information):**
 - OS: All

**Additional context**

**Comment by s-schumann** [comment]
Hi
Does v3.0.1 officially close this bug? The release notes at https://github.com/TykTechnologies/tyk/releases/tag/v3.0.1 would indicate it but I cannot find any update on the ticket.
Thanks.
Sebastian

**Comment by s-schumann** [comment]
Seems to work on v3.0.1. Would be good if the issues would be updated in a timely manner.
Sebastian
