### ISSUE TITLE
Panic for V2.2.0.4

### ISSUE THREAD

**Issue by laruel** [TykTechnologies/tyk#323]
time="Dec 17 01:53:24" level=info msg="Detected 4 APIs" 
fatal error: concurrent map read and map write

goroutine 3080356 [running]:
runtime.throw(0xc50fba, 0x21)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:566 +0x95 fp=0xc4209d1600 sp=0xc4209d15e0
runtime.mapaccess2_faststr(0xb6e4e0, 0xc42083e240, 0xc420871b0b, 0xd, 0x0, 0xd6a908)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4209d1660 sp=0xc4209d1600
github.com/robertkrimen/otto.objectDefineOwnProperty(0xc4204678c0, 0xc420871b0b, 0xd, 0xc2b620, 0xc4205ebe20, 0x48, 0xc4205ebe00, 0xc4209d19f8)
        /Users/xkemi/work/go/src/github.com/robertkrimen/otto/object_class.go:319 +0x6d fp=0xc4209d1968 sp=0xc4209d1660
github.com/robertkrimen/otto.(*_object).defineOwnProperty(0xc4204678c0, 0xc420871b0b, 0xd, 0xc2b620, 0xc4205ebe20, 0x48, 0x877d00, 0xc4204678c0)

**Comment by lonelycode** [comment]
Have you tried using v2.3? Or maybe the later builds of 2.2?

**Comment by laruel** [comment]
I checked V2.2.04 and  added code to api_definition_manager.go
compiled
```
func (a *APISpec) getVersionFromRequest(r *http.Request) string {
        if a.APIDefinition.VersionDefinition.Location == "header" {
                versionHeaderVal := r.Header.Get(a.APIDefinition.VersionDefinition.Key)
                if versionHeaderVal != "" {
                        return versionHeaderVal
                }else{
----------------
                        log.Info("request host:",r.Host)
                        if strings.Contains(r.Host,"xkemi") || strings.Contains(r.Host,"10.170.139.240"){
                                return "V1.6.3"
                        }
----------------
                }

                return ""

        }
```

**Comment by lonelycode** [comment]
The older v2.2 patches had a bug which caused this panic so you *really should work against the v2.2 branch as it is patched, up to date and stable*

Though v2.3 is even more stable, so that's your best bet - your code isn't what's breaking here, it's a bug in the version you are running

**Comment by laruel** [comment]
Thanks
