### ISSUE TITLE
[TT-2004] - Don't revert to murmur

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3233]
When the configuration specifies an invalid hash algorithm name, please don't quietly revert to a (non-cryptographic) algorithm. I think it's better to "fail loudly", with a clear error message that the requested algorithm is not known.

**Comment by andyo-tyk** [comment]
Thank you for this suggestion; it is logged in our product roadmap and we will look at it when we consider improvements in this area; I am closing the request here due to the age.

Thank you for supporting Tyk.
