### ISSUE TITLE
[TT-2005] - Don't leak any portion of API keys in logs

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3236]
I put forth that obfuscateKey should be a constant string (e.g. "****"), with not one bit of the key leaked. This marginally effects debugging, but significantly raises the security of the user's credentials.

**Comment by andyo-tyk** [comment]
Thank you for this suggestion; it is logged in our product roadmap and we will look at it when we consider improvements in this area; I am closing the request here due to the age.

Thank you for supporting Tyk.
