### ISSUE TITLE
[TT-2006] - Phase out support for short keys

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3237]
Tyk allows for really short keys.

```code
func obfuscateKey(keyName string) string {
	if config.Global().EnableKeyLogging {
		return keyName
	}

	if len(keyName) > 4 {
		return "****" + keyName[len(keyName)-4:]
	}
	return "--"
}
```

When the service is configured to require API keys, they should be of a reasonably sufficient length to prevent brute force attacks, especially advanced persistent threats. 4 doesn't cut it.

In fact, Tyk allows for `minLength = 3`.

If the user presents a dictionary word or common phrase for a key, then the last four bytes may give away the entire key.

"????COLA"

Let's not play Wheel of Fortune with our secrets.

Some services may disable authentication entirely in Tyk, and that's okay. But if you're going to have a key, it should be a good one.

There's an argument to be made for flexibility, allowing administrators to set the desired policy. Or education. That "long" is too subjective, where do we draw the line? I don't buy it. A short key has no place in production.

**Comment by andyo-tyk** [comment]
Thank you for this suggestion; it is logged in our product roadmap and we will look at it when we consider improvements in this area; I am closing the request here due to the age.

Thank you for supporting Tyk.
