### ISSUE TITLE
Feature Request - Dashboard users password reset/change

### ISSUE THREAD

**Issue by JayCeeJr** [TykTechnologies/tyk#324]
It would be nice for dashboard users to have the ability to change their password, and a password recovery option.

**Comment by matiasinsaurralde** [comment]
Hi, as an administrator, you may change/reset passwords from the "System Management" / "Users" page!

**Comment by mvdan** [comment]
@JayCeeJr did you try @matiasinsaurralde's suggestion above?

**Comment by JayCeeJr** [comment]
I am able to change the user's password, But ideally I would like the user's to manage their own passwords.

**Comment by buger** [comment]
@JayCeeJr in latest release this is how it works. Users can change their own password. Admins by default now can't reset passwords of users unless they have a special permission, which can be set using Admin API like this `curl -X PUT -H "admin-auth: <your secret>" http://<dashboard>/admin/users/:userId/actions/allow_reset_passwords`
