### ISSUE TITLE
Question: Are API ID's and/or names mandatory?

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3245]
Are both ID and name required for configuring Tyk entities? Or could the ID serve as the sole primary key?

**Comment by agata-wit** [comment]
Hi @mcandre 
I am not entirely sure if by saying ID you mean "id" or "api_id" but I'll try to answer including both just to be safe.

`id`: This is only used in the MongoDB context and bears no actual relation to the identity of the API
`name`: Human readable name of the API. It is used for identification purposes but does not act as an index
`api_id`: The identifier for the API This should be unique, but can actually be any kind of string. For single-instance setups this can probably be set to 1. It is recommended to make this a UUID. The `api_id` is used when querying the Tyk REST API for configuration details

Both 'name' and 'api_id' are mandatory attributes and are needed to set up an API in Tyk.
