### ISSUE TITLE
Multiple custom domains

### ISSUE THREAD

**Issue by bityardigans** [TykTechnologies/tyk#325]
We have 1 set of api's with custom domain set to api.<domain>/<listen path> - we want to clone those apis and route to api-dev.<domain>/<listen path>. From what I have seen and read in the docs, that should not be an issue; however when we tried it, it seems that tyk is only every responding to requests to the initial api.<domain>/<listen path> and returning 404s for all requests to api-dev.<domain>/<listen path>...

is this doable or do we have to have a completely separate server? we are not doing any domain filtering and dns is resolving correctly...we are on 2.3

**Comment by lonelycode** [comment]
Is custom domains enabled in Your Tyk.conf?

**Comment by bityardigans** [comment]
it is- and it is working with the first one we set up; ie added to the first set of api's. Flash forward a couple of months and we wanted to change our dev test process to use a gateway as well and decided to just clone the existing apis, change their custom domain and where they proxy to expecting it to work. Opening the cloned api's shows the correct custom domain; tyk just constantly returns a 404 to the new domain :(

**Comment by lonelycode** [comment]
Just to confirm:

- You have one API set up with custom domain `api.domain.com` with the listen path set to `/` and a target that might be `http://example.com`
- You have another API set up with `api-dev.domain.com` with the listen path set to `/` and a target that might be `http://httpbin.com`

And you find when sending a request to `api.*` it works, but api-dev.* is 404ing?

The first thing to do is check your gateway log output, it should lok something like this if you have your domains set up correctly:

```
[Dec 22 11:50:07]  INFO main: Detected 2 APIs
[Dec 22 11:50:07]  INFO main: Preparing new router
[Dec 22 11:50:07]  INFO main: Initialising Tyk REST API Endpoints
[Dec 22 11:50:07]  INFO main: Loading API configurations.
[Dec 22 11:50:07]  INFO main: Tracking hostname api_name=Open 2 domain=api-dev.custom-domain.domain.com
[Dec 22 11:50:07]  INFO main: Tracking hostname api_name=Open domain=api.custom-domain.domain.com
[Dec 22 11:50:07]  INFO main: Custom Domain set. api_name=Open 2 domain=api-dev.custom-domain.domain.com
[Dec 22 11:50:07]  INFO main: Loading API api_name=Open 2
[Dec 22 11:50:07]  INFO main: Checking security policy: Token api_name=Open 2
[Dec 22 11:50:07]  INFO gateway: Loaded: Open 2 api_id=6e6ccaaac6b240d97a3ff9dfc6e546dc org_id=53ac07777cbb8c2d53000002 server_name=-- user_id=-- user_ip=--
[Dec 22 11:50:07]  INFO main: Custom Domain set. api_name=Open domain=api.custom-domain.domain.com
[Dec 22 11:50:07]  INFO main: Loading API api_name=Open
[Dec 22 11:50:07]  INFO main: Checking security policy: Open api_name=Open
[Dec 22 11:50:07]  INFO gateway: Loaded: Open api_id=54b3b420f4384e557d2ac163d0c040c8 org_id=53ac07777cbb8c2d53000002 server_name=-- user_id=-- user_ip=--
[Dec 22 11:50:08]  INFO main: Processed and listening on: /{rest:.*}
[Dec 22 11:50:08]  INFO main: Processed and listening on: /{rest:.*}
[Dec 22 11:50:08]  INFO main: Initialised API Definitions
[Dec 22 11:50:08]  INFO main: API reload complete
```

(I actually just tested this in the latest release and it does in fact work, we have the custom domain set as a wildcard A record to point at our gateway.)

**Comment by bityardigans** [comment]
Restarting the service fixed it. Awesome- thanks again ;)
