### ISSUE TITLE
Inconsistency between "whitelist" and "json validation" plugin configuration

### ISSUE THREAD

**Issue by n2linux** [TykTechnologies/tyk#3253]
**Branch/Environment/Version** 
Branch/Version: 2.9.4+
Environment: Onprem

**Describe the bug** 
A customer reports that there is some inconsistency between "whitelist" and "json validation" plugin configuration and display

The whitelist plugin configuration is "relative" to the whole path while the json validation configuration is not.

In order to configure, e.g. "/tickets/1234/events", the following relative path is necessary:

"whitelist": `^/tickets/[0-9]+/events$`
"validate json": `^/[0-9]+/events$`

**Reproduction steps** 
1. Download the API definition from the support ticket
2. Import the API 

or 

1. Create two separate endpoints, one using Whitelist plugin, one using Validate JSON plugin
2. Observe that the relative path needs to be different in each plugin in order for the call to the endpoint to work

**Actual behavior** 
Plugins both work, but must be configured differently, which leads to confusion

**Expected behavior** 
The configuration should be the same across all plugins

**Configuration (tyk config file):** 
API definition is included on the support ticket

**Additional context** 
Reported by customer in support ticket [10893](https://tyksupport.zendesk.com/agent/tickets/10893)

**Comment by christtyk** [comment]
Internal issue created
