### ISSUE TITLE
SSE flow broken in v.2.9.4-1

### ISSUE THREAD

**Issue by jeffrngu** [TykTechnologies/tyk#3256]
**Branch/Environment/Version**
- Environment: 
Tyk GW CE 2.9.4-1
SSE server
curl command

**Describe the bug**
The Server Send Event (SSE) support from Tyk GW CE is broken in version 2.9.4-1. This feature was working in version 2.8.1-1.
Always receive error message "internal error: 101 switching protocols response with non-writable body" when attempting to connect to SSE server via Tyk GW.

**Reproduction steps**

1/- Deploy an SSE server or use a test SSE server such as https://github.com/kljensen/golang-html5-sse-example
2/- Deploy Tyk GW CE 2.9.4-1
3/- Define a test API endpoint as open api (no auth required) which routes the request to the SSE server
Listenpath: /sse-test
Target: the SSE server
4/- From the Tyk container, run the following command to receive SSE update from the SSE server
curl -iL -H "Accept: text/event-stream" "http://localhost:8080/sse-test/events/"

**Actual behavior**
Connection upgrade failed and the following response is observed:

HTTP/1.1 500 Internal Server Error
Content-Type: application/json
X-Generator: tyk.io
Date: Tue, 04 Aug 2020 23:50:15 GMT
Content-Length: 90
Connection: close

{
    "error": "internal error: 101 switching protocols response with non-writable body"
}

**Expected behavior**
Connection is internally upgraded by Tyk GW and the curl command blocks on SSE update from the SSE server

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by matiasinsaurralde** [comment]
Have you tried the settings suggested in [3214](https://github.com/TykTechnologies/tyk/issues/3214#issuecomment-668969402)?

**Comment by jeffrngu** [comment]
@matiasinsaurralde yes, I've tried the above scenario with enable_websockets set to false and the SSE flow works. However, now SSE cannot work without WebSocket being disabled. Is there a plan to address this so that both can be enabled at the same time?

**Comment by matiasinsaurralde** [comment]
@jeffrngu That's great. I will discuss the scenario with the team and reach you back.
