### ISSUE TITLE
Non-expiring keys are deleted when session_lifetime is set

### ISSUE THREAD

**Issue by n2linux** [TykTechnologies/tyk#3258]
**Branch/Environment/Version**
- Branch/Version: 2.9.3+
- Environment: On prem, SaaS
**Describe the bug**
When an API has `session_lifetime` set to a non-zero number, it deletes keys that are explicitly set not to expire. It is my assumption that the `session_lifetime` value should not override individual key expiration. If this value is meant to override an individual key's expiration, we should document this behavior because it can cause confusion.

**Reproduction steps**

1. Set `session_lifetime` in API definition to some amount, e.g. 180, for a 3 min TTL
2. Create a new key with access to the API, and make sure the key expiration is set to 'Do not expire key'
3. Make API calls with the key and observe that the calls stop working after 3 min
4. Query the dashboard or Redis for the key and see that it has been deleted

(You can also observe that the key TTL changes if you check the key in Redis)

**Actual behavior**
The key is deleted according to the value of `session_lifetime`, despite it being explicitly set not to expire.

**Expected behavior**
The key should not expire and should not be deleted from Redis.

**Additional context**
Raised by a customer in support ticket #10869.

**Comment by christtyk** [comment]
Internal issue opened.
