### ISSUE TITLE
CORS pre flight requests will take on non 200 status

### ISSUE THREAD

**Issue by dkoston** [TykTechnologies/tyk#326]
Unfortunately most consumers of CORS (browsers, fetch(), etc) do not handle a non-200 preflight response effectively. They essentially strip out the status code and respond with a simple error (see code below).

As such, we are not able to tell the difference between a 403 preflight and a 401, 409, etc in the browser.

Can you please adjust Tyk to send back a 200 from the preflight and reserve the failure code for the non-preflight response.

Thanks!

function handleErrors(response) {
    if (!response.ok) {
        console.log(response)
    }
    return response;
}

fetch("http://httpstat.us/403")
    .then(handleErrors)
    .then(function(response) {
        console.log("ok");
    }).catch(function(error) {
        console.log('there was an error');
        console.log('but I don\'t have access to the status code');
        console.log('So how can my application know what to do?');
        console.log('Should I send the HTTP request again?');
        console.log('Maybe my cookie is expired so I need to log in?');
        console.log('Why don\'t I have access to response.statusCode?');
        console.log(error);
    });

**Comment by lonelycode** [comment]
Is your app handling CORS or are you deferring it to Tyk? If CORS is handled upstream, then Tyk just passes the request right through:

https://github.com/TykTechnologies/tyk/blob/master/middleware.go#L57

If Tyk is handling preflight, we use [this library](https://github.com/rs/cors) to handle CORS, which looks like it sends a 200 OK if it is handling the pre-flight and the pre-flight is in order (https://github.com/rs/cors/blob/master/cors.go#L182).

How is CORS configured?

**Comment by dkoston** [comment]
Ah, good call. This is actually using passthroufh and our app is to blame. Thanks for the quickl reply Martin.
