### ISSUE TITLE
[TT-2010] - Replace ... .BLOCKED mutexes with atomic INCR, DECR operations

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3260]
**Is your feature request related to a problem? Please describe.**

Reduce the need for extraneous Redis keys.

**Describe the solution you'd like**

Replace mutex Redis keys on rate limiting counters with the Redis built-in commands `INCR`, `DECR`.

**Comment by andyo-tyk** [comment]
Thank you for this suggestion, I will pass it on to the engineering teams for consideration in their coding approach.

Thanks again for your support of Tyk.
