### ISSUE TITLE
Headers get transformed before Pre Middleware

### ISSUE THREAD

**Issue by roberterdin** [TykTechnologies/tyk#327]
In a JS middleware, the following happens

A curl to an arbitrary API like this:  `curl -X GET -H "X-API-KEY: some-key" "http://tyk-url.com/some/api"`

leads to the following in the middleware when logging like `log("Headers: " + JSON.stringify(request.Headers));`
```
{\"Accept\":[\"*/*\"],
\"User-Agent\":[\"curl/7.43.0\"],
\"X-Api-Key\":[\"some-key\"]}
```

As you can see, the header value `X-API-KEY` gets transformed to `X-Api-Key`. I don't know if this is expected behaviour but it's certainly a bit weird.

**Comment by lonelycode** [comment]
Headers are case insensitive: 

http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

And different parsers will interpret headers differently (some all upper, some Sentence case;.
