### ISSUE TITLE
http streaming broken, tyk closes connection

### ISSUE THREAD

**Issue by dzinevich** [TykTechnologies/tyk#3270]
**Branch/Environment/Version**
- Branch/Version: release 2.7.7, 2.8, 2.9
- Environment: On-prem

**Describe the bug**
HTTP streaming is broken.
I didn't manage to get it working with 2.9 at all
and for older versions it works ONLY if i have "override_defaults": false
yes, it looks irrational, but I've spent a lot of times experimenting with config file and mostly by accident discovered
that changing only one setting makes it work again.

with "override_defaults": true I'm always getting 
`[2020-08-07 10:33:28 +0000] ERROR: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''`
from my python code. same error is happening for 2.9 with any settings combination.

**Reproduction steps**
Unfortunately I do not have public endpoint to share, but there's a piece of code:

> requests.get(url, params=params, auth=("user", "pass"), stream=True, headers={'Accept': 'text/csv'})

stream=True is key here.
query need to be long running, in my case it returns hundreds of megabytes. fails approx in 1-2 min.

**Actual behavior**
Connections is being dropped by TYK

**Expected behavior**
Connection should remain alive until last chunk will be transferred.

**Configuration (tyk config file):**

> {
  "listen_address": "",
  "listen_port": 8080,
  "secret": "secret",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "max_idle_connections_per_host": 500,
  "storage": {
    "type": "redis",
    "enable_cluster": true,
    "hosts": {
      "localhost": "6379"
    },
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  },
  "enable_analytics": true,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "http_server_options": {
    "skip_url_cleaning": true,
    "override_defaults": true
  },
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/opt/tyk-gateway/policies/policies.json"
  },
  "hash_keys": true,
  "suppress_redis_signal_reload": false,
  "close_connections": false,
  "proxy_close_connections": false,
  "enable_sentinel_rate_limiter": false,
  "enforce_org_quotas": false,
  "enforce_org_data_detail_logging": false,
  "experimental_process_org_off_thread": true,
  "coprocess_options": {
    "enable_coprocess": true,
    "coprocess_grpc_server": "tcp://127.0.0.1:5555"
  }
}

**Additional context**
For now as workaround I end up removing "override_defaults", however in versions prior to 2.9 this breaks "skip_url_cleaning", which we luckily do not need right now but we'll need it in future.

**Comment by matiasinsaurralde** [comment]
Hi, this could be related to the HTTP timeout settings, you could try the following block:
```json
    "http_server_options": {
        "override_defaults": true,
        "read_timeout": 60,
        "write_timeout": 60,
        "use_ssl": false,
        "use_ssl_le": false,
        "ssl_insecure_skip_verify": false,
        "enable_websockets": false,
        "certificates": null,
        "ssl_certificates": null,
        "server_name": "",
        "min_version": 0,
        "flush_interval": 1,
        "skip_url_cleaning": false,
        "skip_target_path_escaping": false,
        "ssl_ciphers": null
    }
```
It could be useful to try different timeout values as well as a low flush interval setting.
