### ISSUE TITLE
enable_hashed_keys_listing doesn't exist in tyk.conf and appears non-functional if added.

### ISSUE THREAD

**Issue by JavaBloxx** [TykTechnologies/tyk#3272]
The documents all mention a value in tyk.conf named `enable_hashed_keys_listing` that is supposed to be disabled by default. I want to enable this for demo purposes.

However, the value doesn't actually exist in the `tyk.conf` file pulled from github and the documentation doesn't mention where the key/value should be added.

I attempted a fresh tyk container adding `enable_hashed_keys_listing: true` to the root json object in `tyk.conf`, but it had no impact. All hashed key listings are still disabled.

**Comment by gernest** [comment]
@JavaBloxx did you also set `hash_keys` to `true`? 

>but it had no impact. All hashed key listings are still disabled.

Can you please expand more on this? What are you trying to do(expect)  and what are you observing( an error or something) that will be very helpful.
