### ISSUE TITLE
[TT-342]: Redis Sentinel Auth Not Working

### ISSUE THREAD

**Issue by calabdean** [TykTechnologies/tyk#3286]
**Branch/Environment/Version**
- Branch/Version: 3.0.0
- Environment: rhel7 rpm install

**Describe the bug**
The redis sentinel connectivity works fine however the authorization component towards redis sentinel is not working. After inspecting your vendor folder, the redis-go library has not been updated in 9 months. Specifically the code at https://github.com/TykTechnologies/tyk/blob/8615cf3005b20cdc25844ffea4c705ee6243a915/vendor/github.com/go-redis/redis/sentinel.go#L247 does not include the auth related username/password required for sentinel with auth turned on - however the more recent code at https://github.com/go-redis/redis/blob/master/sentinel.go#L349 clearly includes the auth related parameters. As such i would hope the issue would be resolved by updating your source in the vendor folder to solve the problem

**Reproduction steps**
connect tyk 3.0.0 to a sentinel with authorization turned on, configure it for auth, watch it fail and report "redis: 2020/08/21 16:19:24 sentinel.go:287: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required."

**Actual behavior**
configured storage section of tyk.conf as below:
  "storage": {
    "type": "redis",
    "addrs": [
        "xxxxxx:26379",
        "xxxxxx:26379",
        "xxxxxx:26379"
    ],
    "master_name": "mymaster",
    "username": "default",
    "password": "xxxxxx",
    "database": 1,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  }
Note that the master "mymaster" is configured correctly and auth in sentinel is working as per below:
[root@xxxx ~]# redis-cli -p 26379
127.0.0.1:26379> auth sitRedisSentinel
OK
127.0.0.1:26379> sentinel get-master-addr-by-name mymaster
1) "xxxxxx"
2) "6379"

Then when starting tyk i get many messages stating "redis: 2020/08/21 16:19:24 sentinel.go:287: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required." as the auth configuration is not propagating into the redis-go driver as the version is old and doesn't include that

**Expected behavior**
I would expect that given the above configuration that i would be able to connect to sentinel with user/password as per the configuration

**Logs (debug mode or log file):**
see attached log file
[auth-fail-sentinel.log](https://github.com/TykTechnologies/tyk/files/5108168/auth-fail-sentinel.log)

**Configuration (tyk config file):**
see attached config
[tykconf.txt](https://github.com/TykTechnologies/tyk/files/5108186/tykconf.txt)

**Additional context**
Without this support, using sentinel for a HA redis setup leaves you with no authorization into your redis service which is not ideal - please let me know if you can fix this in a release quickly by updating the vendor file and redis driver used

**Comment by calabdean** [comment]
Please note that i have seen the same issue in tyk-pump 1.0.1 in the same environment

**Comment by buger** [comment]
Thank you for reporting! We are investigating.

**Comment by letzya** [comment]
https://tyktech.atlassian.net/browse/TT-342

**Comment by nerdydread** [comment]
Fixed in in 3.0.2 release.
