### ISSUE TITLE
Tyk v3 can't connect to Redis

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3293]
**Branch/Environment/Version**
- Branch/Version: v3.0.0
- Environment: community

**Describe the bug**

When I upgrade from v2.9.4.1 to v3.0.0, then Tyk fails to connect to Redis.

**Reproduction steps**

1. `sudo tyk`

**Actual behavior**

Tyk fails to connect to Redis.

**Expected behavior**

Tyk connects to Redis.

Is there an upgrade document that explains new Redis connection configuration parameters? I'm running on localhost:6379, the standard hostport.

**Comment by joshblakeley** [comment]
Hi

This is definitely working fine and sounds more like a support issue. If you are using OSS Tyk please use our community forum at https://community.tyk.io/ for any issues with your setup you are having. 

We would rather keep GH for genuine bugs (In which case we would appreciate a LOT more detail) or well thought out feature requests ideally again with a lot of detail and a user focussed story around why it should be implemented.

Thanks!
