### ISSUE TITLE
Tests are too chatty

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#330]
By default, the tests should not write anything to stderr unless anything went wrong. This is far from the truth right now.

If this is needed for CI or anything else, it should be behind a custom flag like `-test.log` or https://golang.org/pkg/testing/#Verbose.

```
 $ go test
THIS IS THE TEST SETUP INIT
[Jan 11 11:08:23] ERROR Couldn't load configuration file
[Jan 11 11:08:23] ERROR open /etc/tyk/tyk.conf: no such file or directory
[Jan 11 11:08:23]  INFO Writing a default file to ./tyk.conf
[Jan 11 11:08:23] ERROR Failed to process environment variables: specification must be a struct pointer
[Jan 11 11:08:23]  INFO Loading default configuration...
[Jan 11 11:08:23]  INFO Connection dropped, connecting..
[Jan 11 11:08:23]  INFO main: PIDFile location set to: /var/run/tyk-gateway.pid
[Jan 11 11:08:23] ERROR main: Failed to write PIDFile: error opening pidfile /var/run/tyk-gateway.pid: open /var/run/tyk-gateway.pid642434050: permission denied
[Jan 11 11:08:23] ERROR Failed ot get host pid: open /var/run/tyk-gateway.pid: no such file or directory
[Jan 11 11:08:23] ERROR Instrumentation is enabled, but no connectionstring set for statsd
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  INFO main: Initialising Tyk REST API Endpoints
[Jan 11 11:08:23]  INFO main: Loading API configurations.
[Jan 11 11:08:23]  INFO main: Tracking hostname api_name=Tyk Test API ONE domain=(no host)
[Jan 11 11:08:23]  INFO main: Loading API api_name=Tyk Test API ONE
[Jan 11 11:08:23]  INFO main: Checking security policy: Token api_name=Tyk Test API ONE
[Jan 11 11:08:24] ERROR Could not EXPIRE key: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:24]  INFO host-check-mgr: Starting Poller
[Jan 11 11:08:24]  INFO main: Processed and listening on: /v1{rest:.*}
[Jan 11 11:08:24]  INFO host-check-mgr: Loading uptime tests...
[Jan 11 11:08:24]  INFO main: Initialised API Definitions
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:24] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
[Jan 11 11:08:25]  INFO main: Initialising Tyk REST API Endpoints
[Jan 11 11:08:25]  INFO main: Loading API configurations.
[...]
```

**Comment by buger** [comment]
Based on log messages I assume Tyk use kind of log package with different verbose levels, I'm sure there is configuration option which can control verbosity level.

**Comment by lonelycode** [comment]
We use logrus, in fact we use a [forked version of logrus](https://github.com/TykTechnologies/logrus), and logging is shared with this module: [tykcommon-logger](https://github.com/TykTechnologies/tykcommon-logger)

**Comment by mvdan** [comment]
Running `go test` by default now outputs a screen of output. Still a lot IMO, but much better than before.

@buger proposed something that I like: logs should always be shut off, except if a test fails in which case they should be printed. Only the logs from that failed test should be printed.

This is easy to do if tests aren't parallel. We simply have to set the log output to a buffer, and print it if the test in question fails.

It's trickier with parallel tests. The same method to capture the log output for a certain test won't work since they would all write to the log concurrently.

This has to be possible somehow though, and the package `testing` seems to already capture stdout/stderr on a per-test basis, which has to still work with parallel tests.

@buger @lonelycode would you be OK with this method? Then I would make Travis also use this, and the travis build logs would get a lot shorter (as long as nothing fails).

**Comment by buger** [comment]
👍

**Comment by mvdan** [comment]
I forgot something - are logs outside of a test useful? For example, what about logs from the startup (`TestMain`) or logs from tests that ran in parallel with the one that failed?

If either or both of those matter, perhaps it's better to just print the entire log on any failure.

**Comment by buger** [comment]
> print the entire log on any failure.
works for me

**Comment by lonelycode** [comment]
What @buger said - dump the logs on failure.

**Comment by mvdan** [comment]
All the logs, or just the logs from each failed test? That's the question :)

**Comment by lonelycode** [comment]
What's the simplest and fastest thing to do?

**Comment by mvdan** [comment]
All the logs, since it doesn't require splitting output per test. I'll do that then.
