### ISSUE TITLE
Tests report errors that aren't actually errors

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#331]
See https://travis-ci.org/TykTechnologies/tyk/builds/190905477 for example. Errors should make tests fail. If the tests succeed, the errors should not be there.

Either way, this is confusing.

Related to #330.

**Comment by buger** [comment]
Well it depends on the test, sometimes error is actually expected test outcome. Need to check every test.

**Comment by mvdan** [comment]
If it is, the log error line should not be shown to the user (at least by default).

**Comment by mvdan** [comment]
Now that we hide error logs by default, this is no longer a problem. Perhaps there would be a way to mute "expected errors" if you will, but I don't think we should do that since they aren't bothering us right now.
