### ISSUE TITLE
[TT-2014] - Tags not compatible with go mod for plugin import

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3318]
The structure of Tyk tagged release versions do not appear to be very compatible with `go mod`, when writing Go Tyk plugins and attempting to pin the Tyk library version in the plugin's `go.mod` file.

For example, attempts to pin at `v2.9.4.1` and then running `go mod download`, result in the pin being reset to 2.9.5-0...+incompatible.

I'm not certain if this is due to the use of a fourth decimal section (... `.1`), or perhaps the missing import path version section per Go module standards. Or some oddity with VCS. But for whatever reason, this ref is unusable in `go.mod` files.

As a workaround, I am using git submodules instead of Go modules, which faithfully preserve the exact `v2.9.4.1` checkout that my plugin requires to successfully load.

**Comment by Moses-oyedeji** [comment]
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
Closed due to lack of activity; issue will be reviewed during ongoing product development.

**Comment by FireBurn** [comment]
Will it though?
