### ISSUE TITLE
[TT-2016] - auth hook loading empty path ("") instead of the configured plugin file path

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3322]
I can trigger Go plugin hooks with some of the available lifecycle phases. But when I try to use the `auth` hook, then Tyk complains at load time:

```
ERROR Could not load Go-plugin error=plugin.Open(""): realpath failed mwPath= mwSymbolName=
```

Do auth hooks use a different plugin interface compared to the rest of the hooks?

Any restrictions on which hooks are available among the different Tyk priced and zero priced plans?

**Comment by sedkis** [comment]
Just ran into this to.  Not sure on the solution, but to answer this question:
> Any restrictions on which hooks are available among the different Tyk priced and zero priced plans?
No.  All of the plugins run in the Gateway, which is completely OSS. Start here:
https://tyk.io/docs/plugins/supported-languages/

**Comment by gregdelhon** [comment]
@mcandre let us know if this solves your issue
