### ISSUE TITLE
[TT-1946] Phase out uint context keys for string context keys

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3328]
String keys are able to query API Definition context data for Tyk plugin requests, more reliably than uint iota context keys. Suggest to deprecate uint keys and adopt string keys for this reason.

This partially helps to resolve https://github.com/TykTechnologies/tyk/issues/3320

**Comment by Moses-oyedeji** [comment]
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
Closed due to lack of activity; suggestion will be considered during ongoing product development.
