### ISSUE TITLE
[TT-640] Show certificate information instead of certificate ID's

### ISSUE THREAD

**Issue by Marcv89** [TykTechnologies/tyk#3330]
The certificate overview in Tyk dashboard shows only the certificate ID of each certificate. It's very difficult to find a specific certificate when you have more then 50 of them. It would be much easier to show some information of the certificate itself, like CN, expiry date, CA and if it's a public certificate or private key. It would also be helpful to search a certificate based on the CN or sort certificates based on expiry date.

Same goes for API's with mutual TLS as authentication mode. Selecting certificates based on the CN would be more logic instead of the ID.

**Comment by Moses-oyedeji** [comment]
@Marcv89 Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
This was added in Tyk 4.1.

I'm sorry we somehow missed updating this ticket.

Thanks for your support and contributions to Tyk!
