### ISSUE TITLE
[TT-671] Cannot send mails via Dashboard 3.0.1 using SES

### ISSUE THREAD

**Issue by s-schumann** [TykTechnologies/tyk#3333]
**Branch/Environment/Version**
- Branch/Version: 3.0.1 Dashboard (same issue found on 1.9.4.3)
- Environment: On-prem AWS

**Describe the bug**
Cannot send E-mail via Dashboard deployed on AWS when configuring via environment variables.

**Reproduction steps**

1. Configure env vars
2. Start Dashboard
3. Try to send E-mail

**Actual behavior**
No E-mail is sent.

**Expected behavior**
An E-mail is sent via SES.

**Logs (debug mode or log file):**
```
level=info msg="Email sending (AmazonSES)"
level=error msg="Amazon SES error: Post email.eu-central-1.amazonaws.com: unsupported protocol scheme \"\""
level=error msg="Response: "http error: Post email.eu-central-1.amazonaws.com: unsupported protocol scheme ""
```

**Configuration (tyk config file):**
```
     {
        "name": "TYK_DB_EMAILBACKEND_CODE",
        "value": "amazonses"
      },
      {
        "name": "TYK_DB_EMAILBACKEND_SETTINGS",
        "value": "Endpoint:email.eu-central-1.amazonaws.com,AccessKeyId:XYZ,SecretAccessKey:ABC"
      },
```

**Additional context**

**Comment by s-schumann** [comment]
Any update on this? It's blocking my move to v3... Thanks. Sebastian

**Comment by buger** [comment]
Hi! Have you tried adding protocol to the endpoint?
Like this:
```
      {
        "name": "TYK_DB_EMAILBACKEND_SETTINGS",
        "value": "Endpoint:https://email.eu-central-1.amazonaws.com,AccessKeyId:XYZ,SecretAccessKey:ABC"
      },
```

**Comment by s-schumann** [comment]
Hi @buger 

It's not working, tried with 3.1.0 now.

For SES I tried it as you suggested:
```
      {
        "name": "TYK_DB_EMAILBACKEND_CODE",
        "value": "amazonses"
      },
      {
        "name": "TYK_DB_EMAILBACKEND_SETTINGS",
        "value": "Endpoint:https://email.eu-central-1.amazonaws.com,AccessKeyId:xxx,SecretAccessKey:yyy"
      },
```

This throws the error message right when starting up:
```
time="Nov 13 01:22:12" level=error msg="Failed to process environment variables after config file load" error="envconfig.Process: assigning TYK_DB_EMAILBACKEND_SETTINGS to Settings: converting 'Endpoint:https://email.eu-central-1.amazonaws.com,AccessKeyId:xxx,SecretAccessKey:yyy' to type map[string]string. details: invalid map item: "Endpoint:https://email.eu-central-1.amazonaws.com""
```

It starts well with 
```
      {
        "name": "TYK_DB_EMAILBACKEND_CODE",
        "value": "amazonses"
      },
      {
        "name": "TYK_DB_EMAILBACKEND_SETTINGS",
        "value": "Endpoint:email.eu-central-1.amazonaws.com,AccessKeyId:xxx,SecretAccessKey:yyy"
      },
```
 
but then - when sending - throws the error as written in my initial post.

For completeness sake, I also tried:
```
      {
        "name": "TYK_DB_EMAILBACKEND_CODE",
        "value": "smtp"
      },
      {
        "name": "TYK_DB_EMAILBACKEND_SETTINGS",
        "value": "SMTPUsername:xxx,SMTPPassword:yyy,SMTPAddress:email-smtp.eu-central-1.amazonaws.com,SMTPPort:587"
      },
```

This throws the error message right when starting up:
```
2020-11-13T02:15:05.862+01:00 time="Nov 13 01:15:05" level=info msg="initializing SMTP email driver"
2020-11-13T02:15:05.863+01:00 time="Nov 13 01:15:05" level=error msg="Email driver initialisation failed" error="address email-smtp.eu-central-1.amazonaws.com: missing port in address"
```

So for me, SES does not work with your suggestion, and an alternative via SMTP neither (as also commented in #2905).

Any further ideas? Am still blocked for 3.1.0 :( 

Thank you.

Best regards
Sebastian

**Comment by hinorashi** [comment]
same here, I just follow the docs: https://tyk.io/docs/configure/outbound-email-configuration/
```
TYK_DB_EMAILBACKEND_SETTINGS="SMTPUsername:me@email.com,SMTPPassword:password,SMTPAddress:smtpout.secureserver.net:465"
```
but the part `SMTPAddress:smtpout.secureserver.net:465` seems to be invalid due to the second colon at SMTP port, maybe tyk could separate it into 2 key `SMTPHost` and `SMTPPort`.

**Comment by andyo-tyk** [comment]
Closing as stale - if you are still having an issue with latest Tyk, please feel free to reopen.
