### ISSUE TITLE
[TT-774] gateway not reporting any data to jaeger

### ISSUE THREAD

**Issue by tedbjorklund** [TykTechnologies/tyk#3338]
**Branch/Environment/Version**
- Branch/Version: v2.9.4.2, v2.9.4.3, v2.9.4.4, v2.9.4.5, v3.0.1
- Environment: community edition, docker

**Describe the bug**
Tyk gateway no longer reporting any tracing data to jaeger. Tracing configured in tyk.conf, was previously working in v2.9.4.1. No changes were made to tracing config. Downgrade to v2.9.4.1 resumes data being sent.

**Reproduction steps**

1. Configure tracing via tyk.conf
2. Proxy api request 
3. Check jaeger search for data being reported

tracing config from tyk.conf
```
  "tracing": {
    "enabled": true,
    "name": "jaeger",
    "options": {
      "baggage_restrictions": null,
      "disabled": false,
      "headers": null,
      "reporter": {
        "BufferFlushInterval": 0,
        "collectorEndpoint": "",
        "localAgentHostPort": "jaeger-agent.tracing.svc.cluster.local:6831",
        "logSpans": false,
        "password": "",
        "queueSize": 0,
        "user": ""
      },
      "rpc_metrics": false,
      "sampler": {
        "maxOperations": 0,
        "param": 1,
        "samplingRefreshInterval": 0,
        "samplingServerURL": "",
        "type": "const"
      },
      "serviceName": "tyk-gateway",
      "tags": null,
      "throttler": null
    }
  }
```

**Actual behavior**
No tracing data being reported to jaeger. Error messages being reported in logs:
```
2020/09/28 14:32:57 [ERROR] trace:  error when flushing the buffer: write udp 127.0.0.1:51769->127.0.0.1:6831: write: connection refused
```
A DNS resolution of the jaeger URL in the kubernetes pod results in the correct service IP address. 

We also attempted to configure jaeger via env vars per https://github.com/TykTechnologies/tyk/pull/3112, but no change was observed. 

**Expected behavior**
Tracing data being reported to jaeger for proxied requests.

**Logs (debug mode or log file):**
Errors being observed related to flushing the buffer, as seen above. No other pertinent messages observed.

**Configuration (tyk config file):**
```
{
  "listen_port": 8080,
  "secret": "352d20ee67be67f6340b4c0605b044b7",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "timeout": 10,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000,
    "use_ssl": true
  },
  "enable_analytics": true,
  "analytics_config": {
    "type": "",
    "ignored_ips": []
  },
  "dns_cache": {
    "enabled": false,
    "ttl": 3600,
    "check_interval": 60
  },
  "optimisations_use_async_session_write": true,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file"
  },
  "hash_keys": true,
  "suppress_redis_signal_reload": false,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 500,
  "allow_insecure_configs": true,
  "local_session_cache": {
    "disable_cached_session_state": false
  },
  "http_server_options": {
    "skip_url_cleaning": true,
    "enable_websockets": true,
    "certificates": [
        {
          "domain_name": "*",
          "cert_file": "/path/to/server.crt",
          "key_file": "/path/to/server.key"
        }
    ]
  },
  "tracing": {
    "enabled": true,
    "name": "jaeger",
    "options": {
      "baggage_restrictions": null,
      "disabled": false,
      "headers": null,
      "reporter": {
        "BufferFlushInterval": 0,
        "collectorEndpoint": "",
        "localAgentHostPort": "jaeger-agent.kube-system.svc.cluster.local:6831",
        "logSpans": false,
        "password": "",
        "queueSize": 0,
        "user": ""
      },
      "rpc_metrics": false,
      "sampler": {
        "maxOperations": 0,
        "param": 1,
        "samplingRefreshInterval": 0,
        "samplingServerURL": "",
        "type": "const"
      },
      "serviceName": "tyk-gateway",
      "tags": null,
      "throttler": null
    }
  }
}
```

**Additional context**
We observe this behavior beginning with the merge of https://github.com/TykTechnologies/tyk/pull/3112. All subsequent version tags after v2.9.4.1 do not work. We also tried v3.0.1 and observed the same behavior. 

If https://github.com/TykTechnologies/tyk/pull/3112 is reverted and the gateway built without that code, tracing starts working again (if configured via tyk.conf, obviously). We attempted this locally as a troubleshooting step, and observed it correct the problem with both v2.9.4.3, and v3.0.1. We did not try other versions.

**Comment by gernest** [comment]
Hi @tedbjorklund based on the error `127.0.0.1:51769->127.0.0.1:6831` seems to point that  `jaeger-agent.kube-system.svc.cluster.local` is resolving to `127.0.0.1` can you try to log in into the `tyk` container and check if you can talk to `jaeger-agent.kube-system.svc.cluster.local:6831` do this inside the container.

Seems like a dns resolution thing

**Comment by gernest** [comment]
from the error `127.0.0.1:51769->127.0.0.1:6831`  `jaeger-agent.kube-system.svc.cluster.local` is resolving to  `127.0.0.1` is that correct IP? if not maybe its dns resolution issue.

**Comment by tedbjorklund** [comment]
As I stated in my original post: 

```
A DNS resolution of the jaeger URL in the kubernetes pod results in the correct service IP address.
```

**Comment by gregdelhon** [comment]
Thanks for raising @tedbjorklund - we will look into it and get back to you when we have updates.
