### ISSUE TITLE
go test -v reports tests not found

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3339]
The contributing doc recommends running `go test -v`:

https://github.com/TykTechnologies/tyk/blob/master/CONTRIBUTING.md

However, in practice this actually skips all the tests, since the ...`_test.go` files are not presented at top-level but are nested further down.

Would you recommend running `go test ./...` instead?

**Comment by lghiur** [comment]
Thanks @mcandre for raising it up, we created a story internally but we don't have yet any ETA for solving this. Meanwhile please use `go test ./...` as you've already figured it out.

**Comment by andyo-tyk** [comment]
Thanks for your patience, we are reviewing the documentation accordingly, so as not to send users in the wrong direction.
