### ISSUE TITLE
Too many files in the root dir

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#334]
There are too many files in the root directory. This means that visiting github.com/TykTechnologies/tyk is a bad experience, since:

* One has to scroll way down to see the README content
* Important files such as `.travis.yml`, `Makefile` or `main.go` are hard to find

Having so many go files in a single directory is also pretty bad as far as development goes, as it's hard to keep track and they won't fit in a single screen when listing them.

I suggest that we either merge some files or that we move some to separate packages. Ideally, if the root package is to be the executable, it should be fairly small. Luckily enough, since we're not exporting any identifiers from this package, moving things out of it is doable and won't break anything.

**Comment by matiasinsaurralde** [comment]
I think that organizing everything in separate packages is very interesting, if we do it at some point we should also consider the idea of having a "pluggable" Tyk gateway.

**Comment by mvdan** [comment]
I do agree that we need more packages. Some projects use way too many packages, though. I suggest we split up the current one into 2 or 3, and then see if we need to split further.

If we start exposing parts of Tyk as a library, then we have the issue of backwards compat. So we should be really sure about what to expose. Until then, we are free to keep things in the main package or in `internal/...`.

**Comment by mvdan** [comment]
Looking at the files, two easy candidates come to mind:

* `middleware*.go`
* `coprocess_*.go`

**Comment by lonelycode** [comment]
I can see this as a positive move, but we don't want to lose momentum because of refactor - small incremental updates to this issue should help

**Comment by mvdan** [comment]
Yeah, this is low priority. At the same time I'd like to see the low-hanging fruit happen sooner than later, as this disorganization slows things down a bit.

**Comment by abeMedia** [comment]
Breaking tyk up into libraries also brings it a little closer to being able to wrap it within a binary as mentioned in #308 
Ideally I think the main package should be very small, using internal library for most operations. This not only makes it easier to understand the code but also makes it more pluggable.

**Comment by mvdan** [comment]
Agreed. One step at a time, though. You could say this issue is a dependency of yours.

**Comment by mvdan** [comment]
FWIW, down from 148 to 138, both including directories. We haven't started splitting the main package into multiple ones.

**Comment by mvdan** [comment]
@matiasinsaurralde thoughts on moving all of the coprocess stuff to `tyk/coprocess`? I guess what's already in that package can stay there.

**Comment by matiasinsaurralde** [comment]
@mvdan Yes, we should find a place for the `coprocess` files in the root as well.

**Comment by mvdan** [comment]
What do you think about moving `coprocess*.go` to the `tyk/coprocess` package, then?

**Comment by matiasinsaurralde** [comment]
It should be ok, the `coprocess` code essentially exposes a middleware, so if you're planning to have a directory for middlewares, it would make more sense to move it right there.
`CreateCoProcessMiddleware` is called when the middleware chain is prepared, and after this the standard Tyk middleware calls are made (like `ProcessRequest`), as part of `CoProcessMiddleware`.

**Comment by matiasinsaurralde** [comment]
Also, separating this part of the code will make it easier to write the tests we're missing for Python, Lua builds.

**Comment by mvdan** [comment]
awesome, will do a PR soon

**Comment by mvdan** [comment]
As good as it will get without refactoring the main packages into multiple packages, which will happen at some point in 2.5.
