### ISSUE TITLE
[TT-2017] - go unit tests are actually integration tests

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3340]
The presence of Python-dependent tests breaks the standard `go test` pattern. Especially when performed remotely (`go test github.com/TykTechnologies/tyk/...`) on fresh development boxes, or when done within vendored dependencies on fresh Go containers.

Consider moving some of the unit tests around Python and such, into either pure Go unit tests with no external dependencies, or else something like gucumber, which safely models integration tests.

Related to https://github.com/TykTechnologies/tyk/issues/3339

**Comment by andyo-tyk** [comment]
Thanks for the suggestion, closing this issue now.
