### ISSUE TITLE
Update Python

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3341]
The version of Python used by Tyk 2.9.4.3 is Python 3.5.

Python 3.5 is past its end of life for support, such as security updates.

https://www.python.org/downloads/

Python 3.5 does not always appear in modern OS package releases, such as Alpine:

https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.6

**Comment by alephnull** [comment]
Since 2.9, we have used the python that is in Debian stable at the time of building the image. 3.0 has python 3.7, iirc.

**Comment by mcandre** [comment]
In that case, please update the system to target Python 3.7. Many entries in the Tyk 2.9 series continue to fail unless Python is held back to v3.5.

**Comment by alephnull** [comment]
https://github.com/TykTechnologies/tyk-gateway-docker/blob/2de4c75e2729d6516e68c4a176ea11f936b8b93d/Dockerfile#L17 indicates that are using 3.7 explicitly. In which install media are you seeing a different python?
