### ISSUE TITLE
Update Go version

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3343]
Please update the Go version to keep up with security timelines.

https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance

Note that the current Docker build environment is also behind in security patch levels within the 1.12 series.

https://github.com/TykTechnologies/tyk-build-env/blob/master/Dockerfile#L16

https://golang.org/doc/devel/release.html#go1.12.minor

**Comment by diegobernardes** [comment]
I'm not from the Tyk team but I know that there are some blocking issues to upgrade the Go version like this one: https://github.com/TykTechnologies/tyk/issues/2886

I'm using Tyk with the latest Go version, but I'm building from source.

**Comment by christtyk** [comment]
We're just about to move to a newer version
