### ISSUE TITLE
TT-506: As a devops, in the case that  aggregated analytic document hit the max size I want pump/mdcb to self-heal this situation

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3346]
**Is your feature request related to a problem? Please describe.**

Sometimes the aggregated analytics document grows due to the usage of tags in all the APIs.

Writing this data to mongo by MDCB/pump should be self-healed and in case we hit the max size (currently 16MB) mdcb/pump should handle the issue. There could be many ways to handle this in UX friendly way.  For example, to split the write to a few documents and/or send an event to the DevOps to reconsider changing the aggregation to a shorter period.

ATM we can do aggregations per hour or per **minute** and it seems like a big jump between the two. Would be good to add a field with the number of minutes instead of `store_analytics_per_minute` that is only true/false. This way as part of the self-healing the pump/mdcb can change slowly from 60 min to 30 to 10...

Better user experience and avoiding problems especially with enterprises that have massive traffic.

Another issue is that the size of the collections grows at a faster pace since we create a document every minute and a client reported that it makes backup to S3 harder.

**Comment by agata-wit** [comment]
@letzya this has now been included in the larger activity around continuous integration. Will keep you posted!
