### ISSUE TITLE
[TT-1773] Option to skip logging non-2xx plugin responses

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3347]
The vast majority of the time, unsuccessful HTTP responses are triggered by a separate Web application. Please provide an option to skip logging non-2xx responses from Tyk plugins, in order to reduce noise in the Tyk logs that obfuscates more critical gateway events.

**Comment by Moses-oyedeji** [comment]
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
Closed due to lack of activity; issue will be reviewed during ongoing product development.
