### ISSUE TITLE
[TT-1947] Untracked dependencies in v2.9.4.3

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3349]
The golang.org/x/text/encoding dependency is missing from the vendor directory in 2.9.4.3:

https://github.com/TykTechnologies/tyk/tree/v2.9.4.3/vendor/golang.org/x

**Comment by Moses-oyedeji** [comment]
@mcandre Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by christtyk** [comment]
Closing as 2.9.4.3 is essentially out of support. IF still an issue in new versions please report.
