### ISSUE TITLE
Rework version branches as tags

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#335]
We should also have a stable tag format, such as `vX.Y.Z`.

I bet there are also releases that never got marked as neither a branch nor a tag. Perhaps we could script it with the changes to `version.go`.

CC @TykTechnologies/engineering

**Comment by mvdan** [comment]
@buger is there a plan to do this? If we don't care about having old versions as tags, we should just remove old version branches.

**Comment by buger** [comment]
Just to clarify, you are talking about old branches like 1.7.2 and etc, right? 

Are tags going to work as expected with patch release branches like 2.3.2 which have own commit history, and sometimes unique commits? I'm not sure that tags will work here without branches.

**Comment by mvdan** [comment]
> Just to clarify, you are talking about old branches like 1.7.2 and etc, right?

Yes. All of https://github.com/TykTechnologies/tyk/branches/stale, pretty much.

> Are tags going to work as expected with patch release branches like 2.3.2 which have own commit history, and sometimes unique commits?

Yes. Tags are the exact same as branches - they are just references to commits. Git will not "throw away" a commit unless it's pointed to.

The only difference between a branch and a tag is that the former is easier to update and it's used for rolling things, whereas the latter is meant for static things. But you could use any for either purpose.

**Comment by mvdan** [comment]
To clarify the last point, once we drop support for 2.3.x, we can simply remove `release-2.3` and all the `v2.3.*` tags will keep on working just fine.

**Comment by buger** [comment]
If so, I'm totally ok with this approach.
