### ISSUE TITLE
WARN pub-sub: Reconnecting storage: Redis is either down or ws not configured

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3352]
Tyk v3.0.1 reports `WARN pub-sub: Reconnecting storage: Redis is either down or ws not configured` on launch, where Redis appeared to be operating normally with previous versions.

**Comment by gernest** [comment]
This is okay behaviour. Redis might be operating normally but we might not have establish the connection yet. This should go away after a successful connection was established.

**Comment by priyanshu-delhivery** [comment]
the issue persist and no connection with redis is established

**Comment by mgara** [comment]
Hello,
This seems closed but is there any possible reason ? is the Redis cluster is a requirement ? Can I just run the tyk with a single redis instance ?  
thanks.
