### ISSUE TITLE
[TT-1751]Print name of plugin file on launch

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3354]
Printing the handle is somewhat helpful, but any plugins that happen to use the same entrypoint name may be confused during debugging. Please also print the filename of the plugin, such as "bubbler.so"

**Comment by christtyk** [comment]
Added to our product backlog

**Comment by andyo-tyk** [comment]
Closed due to lack of activity; request will be considered during ongoing product development.
