### ISSUE TITLE
[TT-1750] API definition errors ignored re: plugin configuration

### ISSUE THREAD

**Issue by mcandre** [TykTechnologies/tyk#3355]
The gateway logs a message for bad symbols in plugins loaded from API definition .JSON files at launch. However, gateway execution continues with no way to signal to Kubernetes probes, DevOps, etc., that a critical problem has occurred.

```console
$ tyk
[Oct 06 15:10:56] ERROR Could not load Go-plugin error=plugin: symbol NoSuchHandler not found in plugin plugin/unnamed-4b5771d7cd0b073f659944a2294260b549539fb6 mwPath=/test.so mwSymbolName=NoSuchHandler
[Oct 06 15:10:56]  INFO main: Initialised API Definitions
[Oct 06 15:10:56]  INFO main: API reload complete
...
```

That's problem number one. Better to abort when such file-based launch errors occur.

Worse than that, when API definitions are updated live via Tyk admin endpoints, any errors in plugin symbol names are treated as if the entire plugin configuration had been omitted. This means that any security or authentication plugins are simply *ignored*, and the resulting live proxy may skip its own PRE HTTP flow step.

Perhaps the reload endpoint, or the API definition update endpoint, or both, might fail to inform the administrator that plugin symbols are invalid. Need to confirm this.

**Comment by christtyk** [comment]
Thnks @mcandre - investigating

**Comment by gregdelhon** [comment]
@mcandre what signal would you expect?

**Comment by andyo-tyk** [comment]
Closed due to lack of activity; issue will be reviewed during ongoing product development.
