### ISSUE TITLE
Feature request: lint configuration 

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#336]
Tyk has many configuration options, it's really easy to break an install if they are incorrect. It would be great if Tyk had a configuration test or validation option.

**Comment by mvdan** [comment]
There are various layers of checks that come to mind - how deep should we go?

* parse errors (invalid configs)
* valid configs that would make tyk just error and exit
* valid configs that definitely look wrong or would do confusing things

**Comment by abeMedia** [comment]
Could be specified as jsonschema and validated with a library like https://github.com/xeipuuv/gojsonschema

**Comment by lonelycode** [comment]
Schema is a good start, I think this could be done incrementally in terms of complexity. From experience we know that some users have problems installing Tyk because they missed an option or they've actually just configured something wrong (like a connection string).

So maybe we do it in bits:

- v1: Check the config against a schema to make sure no basic errors have been made
- v2: Check for common screw ups in known configuration topologies, e.g. if db based config is enabled, that the dashboard connection string is enabled in all the right places.
- v3: Sanity check some of the values, so for example: Is redis reachable and does it accept writes? Is The dashboard reachable and responding? etc.

**Comment by mvdan** [comment]
@lonelycode your layered approach sounds fine. I'll develop v1 and send a PR soon.

As far as I know this would be the first tyk tool we develop. I would say a subcommand like `tyk lint` would be the best option, since we'll probably add more. We don't want to pollute the `PATH` with tons of `tyk-*` binaries, each statically linking most of Tyk.

My proposal for testing is a series of config inputs (structs) with the expected warnings, if any. This is assuming that there are already tests in place for loading a config struct from a file (plain text).

Should we get @ilijabojanovic involved in this, since it's the design stage of a new feature?

**Comment by buger** [comment]
@mvdan don't you think it make sense to include lint functionality to tyk-cli project?

**Comment by mvdan** [comment]
It lints the server config, not the client config, so I don't see why it should go in the client.

**Comment by lonelycode** [comment]
This is definitely for Tyk gateway - it's like `nginx -t`

This will need def need @ilijabojanovic input

**Comment by mvdan** [comment]
Okay, I'll wait for ilija to give input on my implementation proposal above.

@lonelycode thoughts on a subcommand versus an option? I'm inclined for the former, but perhaps you want to avoid subcommands.

**Comment by lonelycode** [comment]
subcommand might be more scalable

**Comment by mvdan** [comment]
Yeah, definitely. I also prefer them because otherwise they get mixed with options that just modify how the daemon works, instead of running something completely different in its place.

**Comment by ilijabojanovic** [comment]
This is Gateway enhancement. I agree with @mvdan @lonelycode proposals. i will try to summarize feature request.

**Summary:**
Build Gateway tool for configuration lint checking.
v1: Check the config against a schema to make sure no basic errors have been made. 
Command should prevent gateway start with bad configuration file. During config parse if we have error we should throw readable error message in console and stop Gateway startup. 

Task list:
- [ ] Create tyk-lint subcommand 
- [ ] Command should execute during gateway setup or any changes on configuration file
- [ ] After configuration check we should have output message e.g "Configuration loaded"
- [ ] If we have some errors during configuration parse we should have output message e.g "Configuration check failed"

Test checklist:
- [ ] Test Gateway installation with valid configuration file
- [ ] Test Gateway installation with invalid configuration file
- [ ] Install Gateway with valid configuration and modify configuration with valid configuration
- [ ] Install Gateway with valid configuration and modify configuration with invalid configuration
- [ ] Upgrade Gateway with valid configuration and modify configuration with invalid configuration

**Comment by mvdan** [comment]
> Create tyk-lint subcommand

I assume you mean `tyk lint` here.

> Command should execute during gateway setup or any changes on configuration file

I assume you mean "user should execute it when...". This will not run automatically as part of tyk.

> After configuration check we should have output message e.g "Configuration loaded"
> If we have some errors during configuration parse we should have output message e.g "Configuration check failed"

I don't understand these. As with all linters, it should print warnings and exit with a non-zero code if there are any warnings, and print nothing and exit with a zero code if there were none.

> Test checklist:

Your tests involve instlaling and upgrading the gateway. How is that relevant? Lint is only affected by config files.

Also, what do you mean by "invalid configuration"? As explained above in v1/v2/v3, there are different levels for what a config can be correct or not.

**Comment by lonelycode** [comment]
> Your tests involve installing and upgrading the gateway. How is that relevant? Lint is only affected by config files.

To properly test, you start from a clean slate, so installation is part of that in order to remove externalities, it's an extreme setup and teardown. The checklist is for @ilijabojanovic here :-)

> Also, what do you mean by "invalid configuration"? As explained above in v1/v2/v3, there are different levels for how a config can be correct or not.

It's in the summary:

> v1: Check the config against a schema to make sure no basic errors have been made.

**Comment by mvdan** [comment]
> The checklist is for @ilijabojanovic here :-)

Ah, thought it was directed at me for the unit tests.

**Comment by ilijabojanovic** [comment]
@lonelycode @mvdan idea of my summary comment is to give example how we should define feature, since we must avoid comments driven development :)

**Comment by mvdan** [comment]
Note to self - sometimes the gateway config along with an API definition can be misconfigured, meaning that things break. The current lint scope concerns just the gateway config, so once that is working well perhaps we can look into linting the API definitions along with it too.

**Comment by buger** [comment]
The initial version should at least check that:
1. Require attributes not missing
2. There are no misspelled fields
3. Fields has the right format

Error messages should be human-friendly, and clearly, state what happened and how to fix it. 

In future, it will be great to have additional, pre-configured schemes for hybrid, community, and mdcb setups. So I can run smth like: `tyk lint ./tyk.conf --mode hybrid`

In addition, if we go with JSON schema, it allows defining field descriptions, which means we can generate dynamic help for any field or group of fields. For example running smth like `tyk help slave_options` will tell you that it is used only with RPC, and will show the list of sub-options, each described.

**Comment by buger** [comment]
In addition to above. JSON schema allows define dependencies, so, for example, we can define that `use_db_app_configs` should be set to false if `slave_options.use_rpc` is true. 

```
{
    "type": "object",
    "properties": {
        "play": {
            "type": "boolean"
        },
        "play-options": {
            "type": "string"
        }
    },
    "dependencies": {
        "slave-options": {
            "properties": {
                "play": {
                     "enum": [false]
                }
            }
        }
    }
}
```

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configuration linter](https://trello.com/c/Mpg3Od5L/462-configuration-linter)

**Comment by mvdan** [comment]
@buger @lonelycode v1 is pretty much done. Any ideas of what else could be written in the next week for 2.4?

Also, any suggestions as to what could go in v2? Surely we have many examples from the support tickets that resulted in bad config files.

**Comment by buger** [comment]
@mvdan for v1 looks good! 

For v2, as mentioned previously, I would like to see environment specific checks: hybrid, community, dashboard, performance focused, python plugin and etc. And for sure extending linter to the rest of our products.

**Comment by mvdan** [comment]
I am moving this to 2.5 then. If there are any useful v2 features that we want to include in 2.4.x, we can always cherry-pick as needed.

**Comment by joshblakeley** [comment]
I'll be taking this on so would be good to have a chat @mvdan at some point next week over requirements and best approach to take.
