### ISSUE TITLE
[TT-1737] Expose less information at the health endpoint

### ISSUE THREAD

**Issue by diegobernardes** [TykTechnologies/tyk#3361]
**Describe the solution you'd like**
This is the response of the health endpoint: 
```json
{
    "description": "Tyk GW",
    "details": {
        "redis": {
            "componentType": "datastore",
            "status": "pass",
            "time": "2020-10-14T12:21:04Z"
        }
    },
    "status": "pass",
    "version": "v3.0.1"
}
```

We're exposing way too much unnecessary information like that our API gateway is Tyk, it's running on the version `v3.0.1` and it uses Redis.

**Describe alternatives you've considered**
By default expose just the necessary fields:
```
{
    "status": "pass"
}
```

If the request is made using the `x-tyk-authorization` then the full response can be returned.

**Comment by diegobernardes** [comment]
This may not be compliant with the health endpoint RFC but at the same time, I don't think those values should be exposed by default.

**Comment by bitsofinfo** [comment]
agreed

**Comment by buger** [comment]
Hi! In general, there are two solutions to solve this issue.

1) Change health check endpoint name to some unique value using `health_check_endpoint_name` option. 
2) Move all the administrative API from public network to internal network by setting either `control_api_hostname` or `control_api_port` (or both). 

As mentioned above health check endpoint use RFC standard https://tools.ietf.org/html/draft-inadarei-api-health-check-05 which will help you with proxy/lb integration in long run, and helps you debug gateway issues. 

To me, it makes more sense to improve documentation, and maybe default config, to use custom control port API.

Do you think it makes sense?

**Comment by diegobernardes** [comment]
> Change health check endpoint name to some unique value using health_check_endpoint_name option.

This sounds more like a hack than an actual solution for me.

> Move all the administrative API from public network to internal network by setting either control_api_hostname or control_api_port (or both).

I don't see how this helps. At least on my tests, the health endpoint is exposed at the `listen_address` and `listen_port`.

---
I don't think any of the proposed options are good enough. If there is no plan from the Tyk team on improving this, please, close the issue.

On my side, I disabled the health endpoint and created a static config at Tyk to always return 200 on a `/health` endpoint without a body. The extra information on the health check may be ok if Tyk is exposed to the internal network, but our Tyk instance is user-facing.

**Comment by buger** [comment]
Hi! 

I can actually confirm that current behavior can be considered as a bug. In a sense that health check not gets moved to control API :(. Worth noticing that moving Control API on a separate port still good practice. I will create a separate ticket for that. 

Would solving this issue resolve this ticket in your view?
Or basically, you want an option to help "old" health format check just returning empty body?

Just from a high-level point health checks used by load balancers and another monitoring software, and indeed not supposed to be exposed to the outside world, so moving them to a separate port makes sense. 

I'm just trying not to patch the issue, but find a general solution which can work for all installation types. Ideally based on your feedback :)

**Comment by diegobernardes** [comment]
Moving the health endpoint to the control port solves the problem in my opinion.

**Comment by christtyk** [comment]
This is still in the backlog. It’s a valid request but can be mitigated with a workaround of setting an API on the gateway with a mock endpoint that returns anything you'd like and it will still be a valid health check because it will only be loaded if the gateway is up and alive. 

We'll keep this in consideration for a future release so the workaround doesn't have to be deployed and keep this ticket updated.

**Comment by buger** [comment]
Was fixed quite long ago by this PR https://github.com/TykTechnologies/tyk/pull/3434
