### ISSUE TITLE
Completely independent binary

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#339]
As far as I can tell, the templates work from paths relative to the current working directory. We should look into bundling them into the binary itself, perhaps something like https://github.com/jteeuwen/go-bindata. This probably warrants some investigation to find out what package would work best for us.

Are there any other assets or files that are needed on disk for tyk to work properly? I think configs aren't, since they can be given via environment variables too.

**Comment by lonelycode** [comment]
The templates are meant to be user editable, so they get budked along with a bunch of other stuff. We use go bindata for the dashboard assets actually.

**Comment by matiasinsaurralde** [comment]
👆 
I think the templates should be editable and accessible just like the main configuration files.

**Comment by mvdan** [comment]
Ah, that makes sense. Thanks for the explanation.
