### ISSUE TITLE
URL parameters that contain http:// as a field group (even url encoded) are misinterpreted when the proxy URL is reconstructed.

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#340]
The issue appears to be related to a "uri" as a path parameter which results in a path parameter of `http://somedomain.com/123123` to be converted into `http:/somedomain.com/12312` (leading double slash trimmed to one slash).

**Comment by mvdan** [comment]
This stinks of `path.Join`.

**Comment by lonelycode** [comment]
Matias already found a fix, it's got to do with the `DefaultServeMux`

**Comment by lonelycode** [comment]
This issue is related to #410 and need revising so re-opening.
