### ISSUE TITLE
Is this free?

### ISSUE THREAD

**Issue by AdityaAnand1** [TykTechnologies/tyk#3401]
I don't see any pricing information, implications for the non-MIT/Apache license or pricing plans for the tyk cloud.

Is this free for self-hosting? What about the AWS marketplace products, are those free or do they require a license?

What are the differences between the community and non-community(?) "editions"? Is the Admin GUI included in the community edition?

Would be great if there was some clarity on this either in the repo or the landing page 😄

**Comment by buger** [comment]
Hi! 

The gateway itself is a fully open-source product and free to use, including production installations. 

Admin GUI is not included in the community version, so you have to deal with plain files when configuring APIs and Policies.
But if you are using k8s, you can get the help of k8s and our operator project  https://github.com/TykTechnologies/tyk-operator to manage configurations in a unified way. 

As for AWS marketplace, these options assume our commercial on-prem installation, e.g. require dashboard. 

Here you can check pricing https://tyk.io/price-comparison/

Cheers!
