### ISSUE TITLE
v2.9.4.7: no docker image for hybrid?

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#3404]
Please push tags for all the missing releases in https://hub.docker.com/r/tykio/tyk-hybrid-docker/tags

**Comment by alephnull** [comment]
[v2.9.4.7](https://hub.docker.com/layers/tykio/tyk-hybrid-docker/v2.9.4.7/images/sha256-2732db2748d08af97f8c446d5b6aacf4e83226cc8cd4a94bdaa91b50972f27ff?context=explore) was pushed yesterday. I'll close this and use #3405 to track automation.
