### ISSUE TITLE
[TT-4087] Possible memory leak or non present cleanup

### ISSUE THREAD

**Issue by diegobernardes** [TykTechnologies/tyk#3420]
**Branch/Environment/Version**
- Branch/Version: 3.1.0
- Environment: On-prem

**Describe the bug**
![image](https://user-images.githubusercontent.com/14483/101374637-52371400-38a6-11eb-907a-1c9cccf1cab1.png)

Y-axis is % of memory used at the Docker container. The memory usage is simply way too strange. It increases rapidly and it does not return to any healthy level after it. One of the containers jumped from 27% to 99% of memory utilization.

If I do a restart of the containers they simply stay on a healthy level once again with around 20-30% memory utilization with the same throughput.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Additional context**
Compiled with Go 1.15.6

**Comment by buger** [comment]
Hi! 

Thank you a lot for reporting! 

How many APIs do you have? 
Does it memory of the gateway or the dashboard? 
Can you attach tyk.conf and gateway logs? (feel free to send them to support@tyk.io if there is smth confidential).

**Comment by diegobernardes** [comment]
Hi,

It's the gateway. I'll send the information to support@tyk.io.
