### ISSUE TITLE
[TT-1523]How do I change the loading order of api definition files?

### ISSUE THREAD

**Issue by haoyuanli** [TykTechnologies/tyk#3432]
**Is your feature request related to a problem? Please describe.**
I have one api definition's listen path `/`, one is `/v2/api/apples`, i want the `/v2/api/apples` to load before `/` 

the reason is, if it loads after, then tyk routes request to the api def with `/`

**Describe the solution you'd like**
Allow the more specific path to be loaded first

**Describe alternatives you've considered**
none

**Additional context**
none

thjanks

**Comment by Moses-oyedeji** [comment]
@haoyuanli  Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by buger** [comment]
In general, it looks like an issue which was solved in current gw versions. 
Can you try with latest Tyk?
