### ISSUE TITLE
request help: how to set tyk to make it only use two cpu cores

### ISSUE THREAD

**Issue by idbeta** [TykTechnologies/tyk#3433]
My server is 16 cores but it has other applications, so I want to allocate only four cpu cores to tyk-community-edition. What should I do? I have searched the document but can not find a solution.

**Comment by buger** [comment]
Hi! You should try this Linux tooling https://unix.stackexchange.com/questions/23106/how-to-limit-a-process-to-one-cpu-core-in-linux

**Comment by idbeta** [comment]
> Hi! You should try this Linux tooling https://unix.stackexchange.com/questions/23106/how-to-limit-a-process-to-one-cpu-core-in-linux

Thank you for your reply so quickly. I have another question, my env is ubuntu18, where can I get the logs? It was not found in neither `/var/log/ ` nor `/var/log/upstart`.

**Comment by buger** [comment]
Most likely it is systemd, so you will need smth like: `journalctl -u tyk-gateway`

**Comment by idbeta** [comment]
> Most likely it is systemd, so you will need smth like: `journalctl -u tyk-gateway`

Thanks!
