### ISSUE TITLE
Track coverage on Github

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#349]
At least via a README badge. Perhaps use something like https://coveralls.io/, which also integrates with PRs. Can even be set up to mark PRs as red if the coverage drops by more than a treshold (e.g. `0.1%`).

There's also Codecov: https://codecov.io/

Not sure which of the two we should use, as long as both support these important features.

**Comment by buger** [comment]
I assume that currently we have really love code coverage level, adding public badge will have negative effect :)

**Comment by mvdan** [comment]
I tend to be more positive - it would put pressure on us to increase it faster :)

The badges don't usually turn green until you have high numbers like 80% or 90% anyway, so if our tactic was to wait for a full green we might have to wait a long time.

**Comment by lonelycode** [comment]
> The badges don't usually turn green until you have high numbers like 80% or 90% anyway, so if our tactic was to wait for a full green we might have to wait a long time.

Then it defeats the purpose, either badge because high coverage has been achieved or don't, it;s like showing a low food hygiene rating.

**Comment by mvdan** [comment]
Okay then, let's keep it to ourselves and reconsider once the badge changes colour.

Using one of these services would still be useful for PRs and to keep track of the coverage over time, though.

**Comment by mvdan** [comment]
Wait, why is this closed? Even if we agree on not having badges, integrating one of those services with our PRs will still be useful.

**Comment by buger** [comment]
Ah, I thought it was only related to the public badge. Well sure, feel free to configure coverall.io send message to our Slack (let's start with free account for main Tyk repo).

**Comment by mvdan** [comment]
I think it should be configured to post comments to PRs. I don't think wiring it up to Slack directly would be particularly useful.

**Comment by mvdan** [comment]
Now done and working.
