### ISSUE TITLE
Non-UTF8 in request bodies is broken when using a JS plugin

### ISSUE THREAD

**Issue by xagaba** [TykTechnologies/tyk#351]
Uploading multi-part/form binary data via the gateway causes file corruption.

Regular text files work correctly, but binary ones (like images) get corrupted (size increment).

As a sample this is before Tyk

```
    -----------------------------1664174991698023324981845245
    Content-Disposition: form-data; name="file"; filename="mz1N2xGt_400x400.jpeg"
    Content-Type: application/octet-stream

    <FF><D8><FF><E0>^@^PJFIF^@^A^A^@^@^A^@^A^@^@<FF><E2>^B<A0>ICC_PROFILE^@^A^A^@^@^B<90>lcms^D0^@^@mntrRGB XYZ ^G<DF>^@^B^@@
    ^@'^@9acspAPPL^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@<F6><D6>^@^A^@^@^@^@<D3>-lcms^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
    [para^@^@^@^@^@^C^@^@^@^Bff^@^@<F2><A7>^@^@^MY^@^@^S<D0>^@^@
```

and this after Tyk

```
    -----------------------------16059868141680811620898218070
    Content-Disposition: form-data; name="file"; filename="mz1N2xGt_400x400.jpeg"
    Content-Type: application/octet-stream

    <EF><BF><BD><EF><BF><BD><EF><BF><BD><EF><BF><BD>^@^PJFIF^@^A^A^@^@^A^@^A^@^@<EF><BF><BD><EF><BF><BD>^B<EF><BF><BD>ICC_PROFILE^@^A^A^@^@^B<EF><BF><BD>lcms^D0^@
    ^@'^@9acspAPPL^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@<EF><BF><BD><EF><BF><BD>^@^A^@^@^@^@<EF><BF><BD>-lcms^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
    [para^@^@^@^@^@^C^@^@^@^Bff^@^@<EF><BF><BD><EF><BF><BD>^@^@^MY^@^@^S<EF><BF><BD>^@^@
    [para^@^@^@^@^@^C^@^@^@^Bff^@^@<EF><BF><BD><EF><BF><BD>^@^@^MY^@^@^S<EF><BF><BD>^@^@
```

Relevant Community Forum Discussion:  https://community.tyk.io/t/uploaded-binary-file-thouth-tyk-corrupted-mangled/989

``

**Comment by lonelycode** [comment]
(editing issue because it needs more detail in the issue)

**Comment by mvdan** [comment]
See above, it happens with `application/octet-stream` too.

**Comment by mvdan** [comment]
I'm having difficulties reproducing this issue.

I set up a very simple Go HTTP server that just dumps info about the request body. I set up a Tyk API that just points to it (modifying `target_url` in `apps/app_sample.json`). Then I hit both with `curl` like:

```
# Through Tyk
curl -v -F 'file=@a.jpg;type=application/octet-stream' http://localhost:8080/tyk-api-test/
# Directly to the simple Go server
curl -v -F 'file=@a.jpg;type=application/octet-stream' http://localhost:8081/
```

The JPEG file is intact in both cases. I tried this in master first, then in our 2.3 branch. I also tried a large (~10MB) JPEG file.

@xagaba Are you still experiencing the issue? If so, could you provide more info like what Tyk gateway version you're running when you see this?

If you could provide an API definition that reproduces this, that would be wonderful. Any pointers towards reproducing this issue would help.

**Comment by mvdan** [comment]
Regarding the API definition, I'm especially interested in whether you're using any plugins or middleware. Those can move the request body around, so that could be the cause.

**Comment by mvdan** [comment]
Update; I was able to reproduce a broken body with a JS plugin that didn't modify the body. @xagaba could you confirm you were using a JS plugin?

**Comment by xagaba** [comment]
Yes we are using a custom middleware to update the session.expires time
every call.

var refreshJobs = new TykJS.TykMiddleware.NewMiddleware({});

refreshJobs.NewProcessRequest(function(request, session) {
    if (session.expires > 0){
        session.expires = ((Date.now() / 1000) | 0) + 1800;
        TykSetKeyData(request.Headers["Authjobs"], JSON.stringify(session),
1);
    }
    return refreshJobs.ReturnData(request);
});

log("refreshJobs POST middleware initialised");

I hope this can help !

Xavier

El dia 5 maig 2017 3:39 p. m., "Daniel Martí" <notifications@github.com> va
escriure:

Update; I was able to reproduce a broken body with a JS plugin that didn't
modify the body. @xagaba <https://github.com/xagaba> could you confirm you
were using a JS plugin?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TykTechnologies/tyk/issues/351#issuecomment-299467133>,
or mute the thread

**Comment by mvdan** [comment]
Great, thanks for confirming. This is definitely how we send the request data (including the body) to plugins.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix binary and UTF-8 support in JSVM](https://trello.com/c/vkh4RA3S/459-fix-binary-and-utf-8-support-in-jsvm)
