### ISSUE TITLE
[TT-2216] - Suport passing custom signature in a query parameter

### ISSUE THREAD

**Issue by gmaiztegi** [TykTechnologies/tyk#3511]
**Is your feature request related to a problem? Please describe.**
Tyk supports [custom signature validation](https://github.com/TykTechnologies/tyk/pull/2171), which is great, but I am currently managing a migration from Mashery that puts the signature in a query parameter, which is currently not supported.

**Describe the solution you'd like**
I would like to be able to pass the signature in a query parameter, just like we can pass authentication tokens there.

**Describe alternatives you've considered**
Not really.

**Additional context**
Working on a PR right now.

**Comment by n2linux** [comment]
@gmaiztegi Thanks so much for creating this issue and working on a PR! 🥇 

We will get someone assigned to review everything and will be in touch.
