### ISSUE TITLE
plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin

### ISSUE THREAD

**Issue by zj611** [TykTechnologies/tyk#3516]
**errors in building goplogin**
i used the docker to build the goplugin, and then volume it to the tyk container. When run the container, the error occurs, as show below.

`"Could not load Go-plugin" error="plugin.Open("./middleware/bundles/plugins"): plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin" mwPath="./middleware/bundles/plugins.so" mwSymbolName=MyPluginHmacCheck"`

The building image and tyk image i used are ‘**tykio/tyk-plugin-compiler:v3.0.4**’ and '**tykio/tyk-gateway:v3.0.4**', respectively. Both are downloaded from the dockerhub officially.

My question is, is the version of package github.com/TykTechnologies/tyk/goplugin of **tykio/tyk-plugin-compiler:v3.0.4** different from that of **tykio/tyk-gateway:v3.0.4**？

**Comment by zj611** [comment]
in other way of questioning,  as for custom plugin building, can i use the func from the  package of github.com/TykTechnologies/tyk/goplugin?

**Comment by alephnull** [comment]
Hey @zj611 thanks for reporting this! Could you attach a log of how you are building the plugin with the commands used and the output from the commands? Also, is it possible to share your plugin code?
Did you have this plugin working in any version of the gateway?

**Comment by zj611** [comment]
@alephnull Thanks for your reply!
In our teamwork, we plan to build a custom plugin(hmac or rsa) using GO. The problem we come across  for  plugin building is how to load secret key, such as hmac secret, from in-memory cache or redis DB. 

Firstly, we tried to use the "BaseMiddleware" in custom plugin code,  as show below. 
`type MyHTTPSignatureValidationMiddlewareHmac struct {
	BaseMiddleware
	lowercasePattern *regexp.Regexp
}`

The target we did this is to imitate the "mw_http_signature_validation.go", located in gateway package, and load the session from in-memory cache or redis DB. However, the errors occur like this.


`tyk-gateway_1  | time="Apr 08 10:08:55" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/middleware/bundles/plugins"): plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin" mwPath="/opt/tyk-gateway/middleware/bundles/plugins.so" mwSymbolName=MyPluginAuthCheck
tyk-gateway_1  | time="Apr 08 10:08:55" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/middleware/bundles/plugins.so"): plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin (previous failure)" mwPath="/opt/tyk-gateway/middleware/bundles/plugins.so" mwSymbolName=MyPluginRsaCheck
tyk-gateway_1  | time="Apr 08 10:08:55" level=info msg="API Loaded" api_id=huawei-rsa api_name="Tyk Te11" org_id=default9 prefix=gateway server_name=-- user_id=-- user_ip=--
tyk-gateway_1  | time="Apr 08 10:08:55" level=info msg="API bind on custom port:0" prefix=main
tyk-gateway_1  | time="Apr 08 10:08:55" level=info msg="Initializing HealthChecker"
tyk-gateway_1  | time="Apr 08 10:08:55" level=info msg="Checking security policy: Open" api_id=huawei api_name="Tyk Te11" org_id=default9
tyk-gateway_1  | time="Apr 08 10:08:55" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/middleware/bundles/plugins.so"): plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin (previous failure)" mwPath="/opt/tyk-gateway/middleware/bundles/plugins.so" mwSymbolName=MyPluginAuthCheck
tyk-gateway_1  | time="Apr 08 10:08:55" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/middleware/bundles/plugins.so"): plugin was built with a different version of package github.com/TykTechnologies/tyk/goplugin (previous failure)" mwPath="/opt/tyk-gateway/middleware/bundles/plugins.so" mwSymbolName=MyPluginHmacCheck
`

As for tutorial case in github [https://github.com/TykTechnologies/custom-plugins/blob/master/plugins/go-auth-multiple_hook_example/main.go#L135](url), in Line 84, how did the auth key "abc" loaded from the redis DB?
`// ------------------------------------------------------------------
// Custom auth plugin code:

func getSessionByKey(key string) *user.SessionState {
	// here goes our logic to check if passed API key is valid and appropriate key session can be retrieved

	// perform auth (only one token "abc" is allowed)
	// Here you add code to query your database
	if key != "abc" {
		return nil
	}

	// return session
	return &user.SessionState{
		OrgID: "default",
		Alias: "abc-session",
	}
}`

**Comment by buger** [comment]
Can you post some minimal plugin implementation here, so we can replicate locally? 

Thanks!
