### ISSUE TITLE
GeoIP Failure (not recorded): ipAddress passed to Lookup cannot be nil

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#352]
In some cases when GeoIP is enabled in the gateway, if the IP is nil or not extracted properly, the gateway will throw this useless error.

**Comment by mvdan** [comment]
@lonelycode what should happen then, if we get an IP that can't be parsed properly? A warning?

**Comment by lonelycode** [comment]
Maybe, or nothing... if't a heal;thcheck it could flood the logs, sh*t happens

**Comment by mvdan** [comment]
I can fix this very easily, but I'm struggling with the test. Basically, `analytics.GeoIPDB` isn't set up in the tests.

@lonelycode should I init it in the tests somehow (any hints?), make a test without that part (which would do very little, really) or not do a test at all?

**Comment by lonelycode** [comment]
@mvdan To init it would require the presence of a MaxMind DB :-/ Which I don;t want to include with the source. This may need to be manual

**Comment by mvdan** [comment]
@lonelycode how about checking in a small, test database like https://github.com/maxmind/MaxMind-DB/blob/master/test-data/MaxMind-DB-test-ipv4-24.mmdb? That way we can have GeoIP enabled in all the tests.

**Comment by lonelycode** [comment]
I'm ok with it

**Comment by mvdan** [comment]
I didn't mean to "fix" this with the commit above, it said "in preparation to fix #n". My wording triggered the github hook, though.
