### ISSUE TITLE
/opt/tyk-gateway/apps is a file inside the container not a folder

### ISSUE THREAD

**Issue by sigiyoti** [TykTechnologies/tyk#3521]
**Branch/Environment/Version**
- Branch/Version: latest
- Environment: docker
**Describe the bug**
I normally mount the proxy configs in the `/opt/tyk-gateway/apps` folder but as of today, the apps folder seems to be a file  with a test configuration inside the container. This causes errors in docker when I try to mount the apps folder.

**Reproduction steps**

1. `docker run tykio/tyk-gateway:latest`
2. `docker exec -it <tyk_container_id> bash`
3. `cat /opt/tyk-gateway/apps` inside the tyk-gateway container

**Actual behavior**
```
# cat /opt/tyk-gateway/apps
{
    "name": "Tyk Test API",
    "api_id": "1",
    "org_id": "default",
    "definition": {
        "location": "header",
        "key": "version"
    },
    "auth": {
        "auth_header_name": "authorization"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "3000-01-02 15:04",
                "use_extended_paths": true,
                "extended_paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                }
            }
        }
    },
    "proxy": {
        "listen_path": "/tyk-api-test/",
        "target_url": "http://httpbin.org",
        "strip_listen_path": true
    },
    "enable_batch_request_support": true
}
```

5. Run`docker run --rm  -v "<my_folder>:/opt/tyk-gateway/apps"  tykio/tyk-gateway:latest` 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "<redacted>" to rootfs at "/var/lib/docker/overlay2/f01384ff309ef0bf42f57f0f0a03710ce511967175090d0781fad3a9f11685ea/merged/opt/tyk/apps" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

**Expected behavior**
For apps to be a folder containing my configs

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**

**Comment by alephnull** [comment]
I can reproduce this with v2.9.5-rc1 which uses goreleaser. Need to investigate what is going on.

**Comment by sigiyoti** [comment]
All good now.
