### ISSUE TITLE
/opt/tyk-gateway/apps is a file inside the container not a folder

### ISSUE THREAD

**Issue by cverdela** [TykTechnologies/tyk#3534]
https://github.com/TykTechnologies/tyk/issues/3521

docker hub :
tykio/tyk-gateway:v3.0.5
tykio/tyk-gateway:v3.0

whick version of tykio/tyk-gateway  should I use?

**Comment by Moses-oyedeji** [comment]
@cverdela Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed and we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
This was fixed in Tyk 3.0.5 / Tyk 3.2.0
