### ISSUE TITLE
As a user I should be able to change the port for the API in the Gateway 

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#354]
As a user I should be able to change the port for the API in the Gateway so it does not affect general usage or expose the API to the public

**Comment by buger** [comment]
Does it mean that you want a way to specify port per API in API Specification object, or we talking about changing "listen_port" on the fly?

**Comment by lonelycode** [comment]
This should be clearer, my apologies:

The Gateway exposes an administrative API under `/tyk` that is protected by a single hard-coded secret. This would leave the endpoint open to abuse by an external user brute-forcing it. If I can change the port of all the functions associated with the `/tyk` API endpoints so they listen on a different port, then they are not exposed when the gateway is run behind a load balancer that enforces a port-forwarding policy.

This same issue can affect dashboards that are exposing the developer portal.
