### ISSUE TITLE
As a user I should be able to assign multiple policies to a token as a list

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#355]
I should be able to add multiple policy IDs to a token, if they are present, then their partitions are evaluated. If they have overlapping partitions, where it is possible, they should be merged, e.g. if the ACLs are enforced on both, they should be extended to be an aggregate ACL.

I should be able to set these in the dashboard.

**Comment by davegarvey** [comment]
Will this work for JWTs too?

**Comment by lonelycode** [comment]
Good point - it will need to

**Comment by lghiur** [comment]
This is still work in progress, but I want to ask for your opinion on the UI changes I'm thinking to do for this issue and also the data that are sent to the server:

I have transformed the **apply_policy_id** key to **apply_policies**, and it's an array of values now:

```
{
	"last_check": 0,
	"allowance": 1000,
	"rate": 1000,
	"per": 60,
	"expires": 1500646501,
	"quota_max": -1,
	"quota_renews": 1500646507,
	"quota_remaining": -1,
	"quota_renewal_rate": 3600,
	"access_rights": {
		"81ee8208e9a14bab72f796437eceb814": {
			"api_name": "test",
			"api_id": "81ee8208e9a14bab72f796437eceb814",
			"versions": ["Default"],
			"allowed_urls": []
		},
		"c48ef437cc86468c65b85c61e3b8208b": {
			"api_name": "ddd",
			"api_id": "c48ef437cc86468c65b85c61e3b8208b",
			"versions": ["Default"],
			"allowed_urls": []
		}
	},
	"apply_policies": [
	  "59672779fa4387000129507d",
	  "53222349fa4387004324324e",
	  "543534s9fa4387004324324d"
	],
	"tags": [],
	"jwt_data": {
		"secret": ""
	},
	"meta_data": {},
	"alias": ""
}
```
In the UI we will drop the dropdown and add a List component instead, and also I've added a warning message that shows all the partition conflicts between policies:

<img width="856" alt="screen shot 2017-07-21 at 4 14 29 pm" src="https://user-images.githubusercontent.com/6229829/28465175-82f01dba-6e30-11e7-97bc-3f77d2889e32.png">

@lonelycode @buger are you ok with these changes?

**Comment by tumluliu** [comment]
very glad to see there is new progress on this issue. nice job @lghiur 
looking forward to having this feature in the next release because it's sooo necessary. 
only with is feature, it's able to define the matrix policies

**Comment by lonelycode** [comment]
@lghiur 
> I have transformed the `apply_policy_id` key to `apply_policies`, and it's an array of values now:

This would break backwards compatibility in the API :-/ So it will need to be a new field.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple policies per token](https://trello.com/c/9MVuOlkW/427-multiple-policies-per-token)

**Comment by ilijabojanovic** [comment]
@mvdan @lghiur 

**Branches:**
Gateway: PR/1016
Dashboard API: PR/397
Dashboard UI: PR/138

Reproduction steps:
1. Create API definition
2. Create Policy
3. Attach policy on portal
4. Register new developer over portal and request key

Actual:
When developer got key that key doesn't have properties from policy enabled for portal. Rate and Quota are not enabled for that key

Policy:
```
{
    "_id" : ObjectId("59c0cf3148e7d101d7e80185"),
    "org_id" : "59bfa529dfd25101d2b88ef2",
    "rate" : 4000.0,
    "per" : 60.0,
    "quota_max" : NumberLong(-1),
    "quota_renewal_rate" : NumberLong(3600),
    "access_rights" : {
        "d23d337a6a2f4f455eab146191dc9ea7" : {
            "apiname" : "test",
            "apiid" : "d23d337a6a2f4f455eab146191dc9ea7",
            "versions" : [ 
                "Default"
            ],
            "allowed_urls" : []
        }
    },
    "hmac_enabled" : false,
    "active" : true,
    "name" : "polisa",
    "is_inactive" : false,
    "date_created" : Date(-62135596800000),
    "tags" : [],
    "key_expires_in" : NumberLong(21600),
    "partitions" : {
        "quota" : false,
        "rate_limit" : false,
        "acl" : false
    },
    "last_updated" : "1505808178"
}
```
Developer key:
```
{
	"last_check": 0,
	"allowance": 0,
	"rate": 0,
	"per": 0,
	"expires": 1505829836,
	"quota_max": 0,
	"quota_renews": 1505808236,
	"quota_remaining": 0,
	"quota_renewal_rate": 0,
	"access_rights": {
		"d23d337a6a2f4f455eab146191dc9ea7": {
			"api_name": "test",
			"api_id": "d23d337a6a2f4f455eab146191dc9ea7",
			"versions": ["Default"],
			"allowed_urls": []
		}
	},
	"org_id": "59bfa529dfd25101d2b88ef2",
	"oauth_client_id": "",
	"oauth_keys": null,
	"basic_auth_data": {
		"password": "",
		"hash_type": ""
	},
	"jwt_data": {
		"secret": ""
	},
	"hmac_enabled": false,
	"hmac_string": "",
	"is_inactive": false,
	"apply_policy_id": "59c0cf3148e7d101d7e80185",
	"apply_policies": null,
	"data_expires": 0,
	"monitor": {
		"trigger_limits": null
	},
	"enable_detail_recording": false,
	"meta_data": {
		"tyk_developer_id": "59c0cf6948e7d101d7e80186",
		"tyk_key_request_fields": {},
		"tyk_user_fields": {}
	},
	"tags": null,
	"alias": "dev@test.com",
	"last_updated": "1505808236",
	"id_extractor_deadline": 0,
	"session_lifetime": 0
}
```
