### ISSUE TITLE
Dynamic Client Registration {"error":"invalid_client_metadata","error_description":"'grant_types' must contain 'implicit' when 'response_types' contains 'id_token'."}

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk#3561]
Hi @asoorm , @letzya ,

It looks like the DCR docs are missing "implicit" in grant_types like below:

`POST request Data->  ..."grant_types": [
     "authorization_code",
     "refresh_token", 
     "implicit"
  ],...`

Tested with Okta and without "implicit" there is an error:

`dashboard-tyk-pro-694d7b84f4-lqjhc dashboard-tyk-pro time="May 21 14:51:15" level=error msg="Failed to register DCR client:oauth2: cannot register client: 400 Bad Request
dashboard-tyk-pro-694d7b84f4-lqjhc dashboard-tyk-pro Response: {"error":"invalid_client_metadata","error_description":"'grant_types' must contain 'implicit' when 'response_types' contains 'token'. 'grant_types' must contain 'authorization_code' when 'application_type' is 'web'."}"
dashboard-tyk-pro-694d7b84f4-lqjhc dashboard-tyk-pro time="May 21 14:51:15" level=error msg="Generation error: oauth2: cannot register client: 400 Bad Request
dashboard-tyk-pro-694d7b84f4-lqjhc dashboard-tyk-pro Response: {"error":"invalid_client_metadata","error_description":"'grant_types' must contain 'implicit' when 'response_types' contains 'token'. 'grant_types' must contain 'authorization_code' when 'application_type' is 'web'."}"`

In the Okta UI it is also clear that it is needed:
![Screenshot 2021-05-21 at 18 17 52](https://user-images.githubusercontent.com/908425/119168198-f2ea4c00-ba60-11eb-9523-8f9e026d663b.png)

![Screenshot 2021-05-21 at 18 17 46](https://user-images.githubusercontent.com/908425/119168209-f67dd300-ba60-11eb-9b4b-33148c2c341a.png)

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/908425/119185112-a3af1600-ba76-11eb-85e8-257a349b7944.png">

Maybe just updating the DOCS here https://tyk.io/docs/tyk-developer-portal/okta-dcr/ working example ^

**Comment by Moses-oyedeji** [comment]
@bmonteiro Thanks for contacting Tyk!
We apologize for the delayed response. The issue is currently being reviewed we will keep you updated as soon as we can

**Comment by andyo-tyk** [comment]
Thank you, we have corrected this in the Tyk docs.
