### ISSUE TITLE
[TT-2579] Users cannot overwrite HTTP code 404 error response while 401 and 403 are possible

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3566]
Tested on on prem

**Describe the bug**
The error templates overwrite only tyk http error codes that are under a specific api, I guess that since 404 shows there's no such API, it has a different handler and as such not being overwritten.
[Requested by a user from the community ](https://community.tyk.io/t/404-error-template/3662/3)

**Reproduction steps**

1. Create an error template under the template directory and name it as error_{{http-error-code}}. Create file for 404 and for 403 errors. For example:
```
$ cat tyk-gateway/templates/error_403.json
{
    "customErrorTemplate": "This is a custom error response template for HTTP 403 responses using JSON",
    "error": "{{.Message}}"
}
```
You can check the [docs](https://tyk.io/docs/advanced-configuration/error-templates/) for it.
2. Try 

**Actual behavior**
As seen in the screenshot, it works for 403 and returns a custom error but not for 401:

**403:**
$ curl http://tyk-gateway.localhost:8080/httpcodes/ip -H "Authorization: dddd"
{
    "customErrorTemplate": "This is a custom error response template for HTTP 403 responses using JSON",
    "error": "Access to this API has been disallowed"
}
**404:**
$ curl http://tyk-gateway.localhost:8080/bla/ip
Not Found

**Expected behavior**
We should be able to overwrite also 404 errors 

**Screenshots/Video**
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/3155222/119852285-11d85a80-bf07-11eb-8dbf-f2a774448079.png">

**Comment by andyo-tyk** [comment]
This is considered a limitation by design rather than a bug; we will update the documentation to clarify that 404 error response cannot be overwritten.
