### ISSUE TITLE
Active flag of API definition not working as expected

### ISSUE THREAD

**Issue by tobiasb** [TykTechnologies/tyk#3570]
**Branch/Environment/Version**
- Branch/Version: 3.0.1
- Environment: On-prem

**Describe the bug**
The `active` flag in the API definition might not be doing what the documentation says it should do.

**Reproduction steps**
With this API definition:

```
{
    "name": "test",
    "slug": "test",
    "use_keyless": true,
    "api_id": "1",
    "org_id": "default",
    "definition": {
        "location": "header",
        "key": "version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "3000-01-01 00:00",
                "use_extended_paths": true,
                "extended_paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                }
            }
        }
    },
    "proxy": {
        "listen_path": "/echo",
        "target_url": "http://echo"
    },
    "active": false
}
```

Because of the `"active": false` I expect requests to `http://localhost:8080/echo` to not get proxied to the `target_url`. According to the [documentation](https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/other-root-objects/)

> active: If set to false means that on start, restart or reload, the API will be ignored and all paths and routes for that API will cease to be proxied. Any keys assigned to it will still exist, though they will not be let through for that particular API.

Am I understanding the purpose of that field wrong?

**Actual behavior**
Requests get proxied to the `target_url` 

**Configuration (tyk config file):**

```
{
  "listen_port": 8080,
  "secret": ".....",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "127.0.0.1",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000
  },
  "enable_analytics": false,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "optimisations_use_async_session_write": true,
  "enable_non_transactional_rate_limiter": true,
  "enable_sentinel_rate_limiter": false,
  "enable_redis_rolling_limiter": false,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/opt/tyk-gateway/policies/policies.json"
  },
  "hash_keys": true,
  "close_connections": false,
  "http_server_options": {
    "enable_websockets": true
  },
  "allow_insecure_configs": true,
  "coprocess_options": {
    "enable_coprocess": true,
    "coprocess_grpc_server": "",
    "python_path_prefix": "/opt/tyk-gateway"
  },
  "enable_bundle_downloader": true,
  "bundle_base_url": "http://127.0.0.1:8888",
  "global_session_lifetime": 100,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 500,
  "log_level": "info",
  "proxy_default_timeout": 60
}
```

**Comment by christtyk** [comment]
@buger can you confirm expected behavior and I'll add to backlog if valid

**Comment by joshblakeley** [comment]
Active flags only work when there is a dashboard so if this is just the OSS Gateway this is expected.

**Comment by tobiasb** [comment]
Understood, thanks for clarifying. I'd suggest updating the documentation to reflect that. https://github.com/TykTechnologies/tyk-docs/pull/1689. But also, if there is a flag and it's part of the API definition, why not enforce it at the Gateway level?

**Comment by joshblakeley** [comment]
Thanks @tobiasb i'm pretty sure this is literally the only API def config that isn't enforced at the gateway level. I can speculate a bit and say it was probably because it was added around the time of the Dashboards inception way way back when the wider API management platform piece was developed. 

Most users would handle this type of api def activation in gateway only setups in their gitops anyway we tend to find.

**Comment by tobiasb** [comment]
I see. We ended up just removing the API definition json in certain deployments and that works well too. Maybe just update the documentation then I'd suggest.

Thanks for the quick response and thanks for working on Tyk!

**Comment by agata-wit** [comment]
Docs are now updated to reflect this information clearly.
