### ISSUE TITLE
Cannot import ctx/user packages in a Golang plugin

### ISSUE THREAD

**Issue by alexlemaire** [TykTechnologies/tyk#3597]
**Describe the bug**
When creating a Golang plugin and trying to import `ctx` and `user` packages, I'm receiving the following error:
```
        github.com/TykTechnologies/tyk/user imports
        github.com/TykTechnologies/tyk/log imports
        github.com/hashicorp/terraform/flatmap: module github.com/hashicorp/terraform@latest found (v1.0.1), but does not contain package github.com/hashicorp/terraform/flatmap
```
After investigating, it seems that the [latest published](https://pkg.go.dev/search?q=tyk) version for Tyk's Go module is `2.9.5+incompatible` in which `log/log.go` still imports `github.com/hashicorp/terraform/flatmap` while it was changed in [this commit](https://github.com/TykTechnologies/tyk/commit/07cfe566eb25f385176b56aca1823f2734770afb)

**Reproduction steps**

1. Open up a terminal
2. `mkdir plugin-bug`
3. `cd plugin-bug`
4. `go mod init example.com/plugin-bug`
5. `touch main.go`
6. edit `main.go` adding the following:
```go
package main

import (
	"github.com/TykTechnologies/tyk/ctx"
	"github.com/TykTechnologies/tyk/user"
)

func main() {}
```
7. run `go mod tidy` and the error mentioned above should appear

**Expected behavior**
`go` should have been able to download the module along with all packages included inside and should have edited `mod.go` properly.

Thanks in advance for your help!

**Comment by alexlemaire** [comment]
Noteworthy: this doesn't seem to happen when compiling using `docker run --rm -v `pwd`:/plugin-source tykio/tyk-plugin-compiler:v3.0.4 my-post-plugin.so`. Only when running `go mod tidy`

**Comment by buger** [comment]
Hi! 

We are aware of the issue, and will try to fix in next patch.
The issue is that in past versions we depend on vendor folder, and after switch to go modules it got more complicated.

**Comment by Darkweak** [comment]
It seems there is a quick fix @alexlemaire 
```
replace github.com/hashicorp/terraform v1.0.1 => github.com/hashicorp/terraform v0.14.11
```

**Comment by alexlemaire** [comment]
Good workaround until the actual fix comes in, worked for me! Thanks @Darkweak
