### ISSUE TITLE
Compile and test all build tag combinations on CI

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#360]
`coprocess` and `python`, for example - it will require installing certain python things, so it's not trivial.

Right now we only build without tags and with `coprocess`.

**Comment by mvdan** [comment]
See comments in https://github.com/TykTechnologies/tyk/pull/359#issuecomment-272921556

**Comment by mvdan** [comment]
This is more subtle than I thought. Turns out our CI line `go test -tags coprocess` is wrong, because:

* It doesn't actually build the whole package/executable. `go instlal -tags coprocess` fails, yet the test binary builds fine.
* `-tags coprocess` isn't enough. It seems like another tag is needed, like `-tags coprocess,python`.

@matiasinsaurralde @lonelycode what was the logic behind the use of `-tags coprocess` in the old `.travis.yml` then? Was it simply wrong?

What are all the possible combinations? As far as I can tell, they should be `coprocess,grpc`, `coprocess,lua` and `coprocess,python`.

**Comment by mvdan** [comment]
Also, what's the logic behind having some of the tests under the `coprocess` build tag?

**Comment by lonelycode** [comment]
We can't build a binary that handles all three plugin targets (grpc, Python, lua) - that's the combos

The tests for CP don't target the plugin langs, but do activate the CP logic as part of the middleware chain, which some tests hit, but which is absent in vanilla.

Vanilla only handles ecmascript, which is a different MW

So in short, half the tag set kicks off some general CP tests, there are no tests for actual targets.

So for now just running the high level tests will handle an integration scenario, but won't test or compile against the bindings.

This means we need to actually build the coprocessor targets to make sure the code is sane, tests need to come separately.

**Comment by lonelycode** [comment]
@matias can explain when yu meet him next week.

**Comment by mvdan** [comment]
Okay, so for example for `coprocess,python`, we don't need any python stuff to run the tests since they're just `coprocess`, but we do need them to compile since that will also build the python-specific Go files that require the extra dependencies.

This finally makes sense, thanks.
