### ISSUE TITLE
Unable to load a go-plugin - ("Could not load Go-plugin")

### ISSUE THREAD

**Issue by darkweak** [TykTechnologies/tyk#3605]
Hello, I'm trying to run an under-development plugin and when I'm trying to load it as go-plugin I'm getting the following error : 
```
Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/middleware/souin-plugin"): plugin was built with a different version of package go.uber.org/zap/buffer" mwPath="/opt/tyk-gateway/middleware/souin-plugin.so" mwSymbolName=SouinRequestHandler
```

I think I'm missing something. I saw @letzya already answer to a similar issue (https://community.tyk.io/t/compiling-go-plugin/3834/15). I'm currently using the `tyk-gateway-docker:v3.2.1` stack and I build the `.so` file with the container `tykio/tyk-plugin-compiler:v3.2.1`.

Thanks for your answer.

**Comment by christtyk** [comment]
Hey @Darkweak - you're not missing anything, we've got a small issue with the compiler for this release at the moment. We're working to resolve it asap. 

It should be working in 3.1 versions for now if you're just testing some stuff out, will let you know when the latest is ready.

**Comment by alephnull** [comment]
In 3.2.1, we started using go modules and bumped the go build version to 1.15.8 from 1.12. 

If you don't require 3.2.1, I would suggest you use v3.1.2 until this stabilises and there are numerous subtleties with modules and plugins in go.

**Comment by Darkweak** [comment]
The plugin doesn't compile when I try to compile with the `v3.1.2`, it throws errors in the following packages `vendor/go.uber.org/atomic` `vendor/github.com/uber/jaeger-client-go/thrift` `vendor/github.com/mattn/go-isatty` `vendor/github.com/sirupsen/logrus`.

**Comment by buger** [comment]
Can you show exact errors? Maybe it’s because of package versions and incompatibility to use them with Go version provided in compiler? If so try using older package versions

**Comment by Darkweak** [comment]
Here is my go mod file (I obviously ran `go mod tidy && go mod download && go mod vendor`)
```
module github.com/darkweak/souin/plugins/tyk

go 1.15

require (
	github.com/HdrHistogram/hdrhistogram-go v1.1.0 // indirect
	github.com/TykTechnologies/gojsonschema v0.0.0-20170222154038-dcb3e4bb7990 // indirect
	github.com/TykTechnologies/tyk v2.9.5+incompatible
	github.com/clbanning/mxj v1.8.4 // indirect
	github.com/darkweak/souin v1.5.2
	github.com/franela/goblin v0.0.0-20210519012713-85d372ac71e2 // indirect
	github.com/franela/goreq v0.0.0-20171204163338-bcd34c9993f8 // indirect
	github.com/hashicorp/terraform v1.0.1 // indirect
	github.com/kelseyhightower/envconfig v1.4.0 // indirect
	github.com/lonelycode/go-uuid v0.0.0-20141202165402-ed3ca8a15a93 // indirect
	github.com/lonelycode/osin v0.0.0-20160423095202-da239c9dacb6 // indirect
	github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d // indirect
	github.com/opentracing/opentracing-go v1.2.0 // indirect
	github.com/pmylund/go-cache v2.1.0+incompatible // indirect
	github.com/uber/jaeger-client-go v2.29.1+incompatible // indirect
	github.com/uber/jaeger-lib v2.4.1+incompatible // indirect
	github.com/x-cray/logrus-prefixed-formatter v0.5.2 // indirect
	github.com/xeipuuv/gojsonschema v1.2.0 // indirect
	gopkg.in/mgo.v2 v2.0.0-20190816093944-a6b53ec6cb22 // indirect
)

replace github.com/hashicorp/terraform v1.0.1 => github.com/hashicorp/terraform v0.14.11
```

And here is the stacktrace https://pastebin.com/NrdYYgrV

**Comment by Darkweak** [comment]
Update: https://github.com/TykTechnologies/tyk/releases/tag/v3.2.2-rc1 resolves the encountered issues, thanks a lot! 🎉

**Comment by Ruto8** [comment]
This is also a blocker for our team, we're encountering the exact same issue as @Darkweak.

@buger could we kindly ask to publish the debian package as well for v3.2.2-rc1?

**Comment by buger** [comment]
@Darkweak be aware that it is not fully went through the QA. We are planning to release it in a week. 
@Ruto8 you can find it in our unstable package repo https://packagecloud.io/tyk/tyk-gateway-unstable

**Comment by Ruto8** [comment]
> @Ruto8 you can find it in our unstable package repo https://packagecloud.io/tyk/tyk-gateway-unstable

Sorry to bother you again, but I can't find this new version of the package in this repo. I sorted by "most recent" and the latest unstable version is from 2 days ago. I initially thought it might be just missing in the UI, but I'm not able to download it.

Also, thanks for fixing it and providing us with an ETA, much appreciated.

**Comment by orangedeng** [comment]
Hi, I encounter the same issue with different package. Here is the error:

```
time="Sep 10 02:08:49" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/go-plugins/translate"): plugin was built with a different version of package github.com/TykTechnologies/tyk/regexp" mwPath="/opt/tyk-gateway/go-plugins/translate.so" mwSymbolName=ParseResponse
```

Although I fix it by build my plugin with vendor the right TYK package and build it in `golang:1.15.8` image. Here is my go.mod and the way I built the plugin

```go.mod
module <module-name>

go 1.15

replace github.com/jensneuse/graphql-go-tools => github.com/TykTechnologies/graphql-go-tools v1.6.2-0.20210324124350-140640759f4b

require (
	github.com/TykTechnologies/tyk v1.9.2-0.20210519212022-74a6e02b3642
	github.com/stoewer/go-strcase v1.2.0
)

```

```bash
docker run --rm -it -v `pwd`:/path/to/source golang:1.15.8
cd /path/to/source
go build -buildmode=plugin -o translate.so
```

But I still got following error when loading my plugin:

```
time="Sep 10 02:25:08" level=error msg="Could not load Go-plugin" error="plugin.Open("/opt/tyk-gateway/go-plugins/translate"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader" mwPath="/opt/tyk-gateway/go-plugins/translate.so" mwSymbolName=ParseResponse
```

**Comment by darkweak** [comment]
Hello @orangedeng, you have to build using the `tyk-builder` container
(you can get inspiration from the docker-compose file https://github.com/darkweak/souin/blob/master/plugins/tyk/docker-compose.yml.test).

**Comment by JalinWang** [comment]
I just follow the docs but it takes me half an hour to find this issue :(
https://tyk.io/docs/plugins/supported-languages/golang/

![image](https://user-images.githubusercontent.com/20621784/178677734-d7626156-c698-478b-ad54-be78a0391c30.png)

Will it be better if you can update the docs or add some notes?
