### ISSUE TITLE
[TT-2808]Allow access to individual path parts in context variables

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk#3606]
**Is your feature request related to a problem? Please describe.**

I have a request like `/customers/se0001/v2.0/organisation` that I want to route to an api and set the se0001 part as an header dynamically.

The current way path parts context variable works is we get a string output as `customers,se0001,v2.0,organisation`

**Describe the solution you'd like**

Instead of a string put the values in an array we can then call with something like `$tyk_context.path_parts[1]` which would result in `se0001` being injected in a header value for example.

**Describe alternatives you've considered**

This can be done in something like a virtual endpoint but that adds latency and isnt a nice native solution to this.

**Additional context**

Specifically brought up by a presale client.

**Comment by andyo-tyk** [comment]
This is logged on our product roadmap; I am closing the request here due to the age.
I will update this ticket as and when we implement something.
