### ISSUE TITLE
Remove the test dependency on redis

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#361]
Seems like the easiest way would be to use https://github.com/alicebob/miniredis, proposed by @buger.

If that doesn't work for us, perhaps we could mock it ourselves at a higher level.

**Comment by matiasinsaurralde** [comment]
@lonelycode There was a plan to remove Redis, right? This is related!

**Comment by mvdan** [comment]
Ah, yes, I remember him mentioning it. If the plan is to remove Redis in the short term, perhaps we could skip this altogether since it would go away entirely.

**Comment by lonelycode** [comment]
It's something I'd like to achieve *in 2017*, so we should still solve this, and we may leave redis as an option for users that do not want to take the cluster option and all the downsides that comes with.

**Comment by mvdan** [comment]
Sounds good. We should do this soon, then.

**Comment by mvdan** [comment]
redis_cluster_handler.go:82:I have a patch for this that works, but can't submit because it depends on #386.
