### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#362]
I expect many of the tests could be run in parallel. This would speed up the whole test suite, which is currently a bit slow.

This would also help us find race bugs and other kinds of issues that won't arise for as long as the tests run sequentially. This won't work well with all the log messages (#330), so we first need to get rid of those.

**Comment by buger** [comment]
I think this is related to #361. If Redis directly used in tests, there is high chance that one of them re-use same keys.

**Comment by mvdan** [comment]
That's a good point. There probably will be more issues since tests have always been run sequentially - temporary files, used ports, global variables...

**Comment by mvdan** [comment]
The tests pass after 40s on my laptop, with none of my CPU cores ever going past 5% use. 40s is way too long for me to quickly iterate. I think this is pretty high priority, as I'd rather not waste my time.

**Comment by lonelycode** [comment]
The tests should be ok to run in any order, however they have always run sequentially. Since they ised to run on an instance with a standing redis DB, "duplication" of data shouldn;t be an issue. You may get other problems with port bindings though.

Has anyone actually tried running in parallel?

**Comment by mvdan** [comment]
Nope, but it's on my list lf things to do soon. Would self-assign but can't anymore :)

**Comment by lonelycode** [comment]
As you wish.... ;-)

**Comment by mvdan** [comment]
As it turns out, quite a lot of tests modify global state (like the global `config`). Ideally this wouldn't be true, but it's unrealistic to refactor everything to remove global state just so we can run every test in parallel.

A good part of the tests don't modify global state though, and would likely still work in parallel. Keeping this issue open to track those.

**Comment by mvdan** [comment]
After removing lots of network use from the tests, the total test time is down from ~4s to ~2s. I think that's acceptable for now, and it's no longer high priority to make lots of tests parallel.

Not a fan of umbrella issues with non-specific goals, so going to close this.
