### ISSUE TITLE
What exactly does /tyk/reload/ reload?

### ISSUE THREAD

**Issue by haoyuanli** [TykTechnologies/tyk#3620]
Just a noob question, what exactly the hot reload reload? I know it reloads the API definitions, does it reload the policies.json? Does it reload the tyk.conf changes?

Perhaps we could be more clear in the documentation on this

Best

**Comment by n2linux** [comment]
👋 Hi @haoyuanli, and thanks for asking this question. 

A hot reload will reload all the API definitions and policies, but won't apply any changes made to the gateway configuration (tyk.conf).

**Comment by haoyuanli** [comment]
Thanks,  what about middleware?
Best
