### ISSUE TITLE
[TT-2381] Apikey for 504 errors

### ISSUE THREAD

**Issue by Zavierazo** [TykTechnologies/tyk#3633]
**Do you want to request a *feature* or report a *bug*?**

When we have 504 errors, we do not know which apikey corresponds to or the origin of the error. Need to have atleast the apiKey, although it would be nice to have more information about the source of the error.

**What is the current behavior?**

{
   "alias":"",
   "api_id":"xxxxxxxxxx",
   "api_key":"",
   "api_name":"api",
   "api_version":"Non Versioned",
   "content_length":11483,
   "host":"xxxxxxxx.service",
   "ip_address":"xxxxxxxxxx",
   "method":"POST",
   "oauth_id":"",
   "org_id":"xxxxxxxxxx",
   "path":"/test",
   "raw_path":"/test",
   "raw_request":"",
   "raw_response":"",
   "request_time_ms":0,
   "response_code":504,
   "timestamp":"2021-07-29T08:24:39.921524947+02:00",
   "user_agent":"Go-http-client/1.1"
}

**What is the expected behavior?**

{
   "alias":"",
   "api_id":"xxxxxxxxxx",
   "api_key":"APIKEY of the client",
   "api_name":"api",
   "api_version":"Non Versioned",
   "content_length":11483,
   "host":"xxxxxxxx.service",
   "ip_address":"xxxxxxxxxx",
   "method":"POST",
   "oauth_id":"",
   "org_id":"xxxxxxxxxx",
   "path":"/test",
   "raw_path":"/test",
   "raw_request":"",
   "raw_response":"",
   "request_time_ms":0,
   "response_code":504,
   "timestamp":"2021-07-29T08:24:39.921524947+02:00",
   "user_agent":"Go-http-client/1.1"
}
Also extra info about the error. This was already requested on https://github.com/TykTechnologies/tyk/issues/2615

**Comment by agata-wit** [comment]
Hi @Zavierazo thank you for the suggestion to make Tyk a little bit better. We will take a look at both tickets you opened and see what we could do around that and when. I'll get back to you with an update.

**Comment by andyo-tyk** [comment]
Hi @Zavierazo,
Sorry for the lack of update here in Github, but as you're hopefully aware we are looking after this request and others elsewhere, with the support of your Account Manager.
I'd like to close the issue here, as we're tracking elsewhere and looking to streamline our communication with you.
If you'd prefer that I re-open the ticket, please just comment and I can do so.
Thanks for your support.
