### ISSUE TITLE
update api with swagger file

### ISSUE THREAD

**Issue by drmaples** [TykTechnologies/tyk#365]
It is awesome that you can import an api from a swagger file. Once the api is created, there does not seem to be a way to update all the endpoints with a new swagger file. Having to tweak things via the "Endpoint Designer" is error prone.

It would be nice to just manage a swagger.json file, upload it, and have Tyk add/update/replace endpoints based on whats in the swagger file.

**Comment by gwshaw** [comment]
👍  We base our pipeline development off Swagger. As devs add/change endpoints, they update the Swagger for the service and then build routing and deploy that through the CI pipeline. CI uploads and deploys the changes through gateway APIs (we are using Apigee right now) and the changes go live.

**Comment by nickReyn** [comment]
We're planning to release this in v2.6 in the next 6-8 weeks. Thanks for the patience and the great suggestion 👍
