### ISSUE TITLE
Federation support: upstream SDL fetching

### ISSUE THREAD

**Issue by Tomsons** [TykTechnologies/tyk#3651]
**Is your feature request related to a problem? Please describe.**
Are there any plan to support fetching the subgraphs SDL in supergraph mode and set the merged_sdl property according to all defined subgraphs?

**Describe the solution you'd like**
I thought about something, maybe less complex than [this one](https://github.com/jensneuse/graphql-go-tools/blob/master/examples/federation/gateway/datasource_poller.go)

**Describe alternatives you've considered**
Apollo federation gateway that does it out of the box

**Comment by agata-wit** [comment]
@Tomsons thanks for reaching out to us with your enhancement request. We are still developing our federation offering and will look at your request closely. I'll get back to you once we make a decision.

**Comment by myworkfoce** [comment]
Any updates related to this issue?
