### ISSUE TITLE
CORS worked incorrectly

### ISSUE THREAD

**Issue by nguyenhuuloc304** [TykTechnologies/tyk#3657]
**Branch/Environment/Version**
- Branch/Version: Tyk gateway 2.6.2/ Tyk Dashboard 1.7.0
- Environment: Docker

**Describe the bug**
I have two APIs belong to same Service (I named Product Service). I configured this service on TYK dashboard. I have set **Allowed Origin** for some domains. E.g. DomainA.com, DomainB.com and DomainC.com and select for **Enable CORS**, **Allow credentials**
![image](https://user-images.githubusercontent.com/21157325/131501426-33f82dba-38ba-4118-ba02-30b9aa3e9a27.png)

When I call to the API-s via Tyk:
API1: **TykGateway/ProductApi/ap1** 
With header **Origin**: **DomainB.com**
**the API is failed.** 

**But api2 worked normally,**
API2: **TykGateway/ProductApi/ap2** 
With header **Origin**: **DomainB.com**

After that, I changed origin header to DomainA.com when calling the APIs. Both API-s worked fine.

Then I tried to remove **DomainB.com** from **Allowed Origin** configuration in TYK dashboard. Now, API 1 worked with header **Origin**: **DomainB.com**

And one more thing so weird that I checked Log Browser of Dashboard. I see API1 has Status Code 200. However, it is failed on Browsers and Postman
![image](https://user-images.githubusercontent.com/21157325/131504324-1e1d53fc-2dfd-4165-8e2d-8f73b4b97732.png)

Does anyone encountered this issue before? Anybody can give me some solutions? Thank you.

**Comment by agata-wit** [comment]
@nguyenhuuloc304 I noticed you are using quite old versions of Tyk Gateway and Tyk Dashboard. There have been many improvements made in gateway since v2.6.2, around CORS as well. 
Unfortunately we no longer support those older versions. I would advise you to switch to one of the latest releases like 3.2 for example, and see if your issue replicates there as well - which it shouldn't.

**Comment by agata-wit** [comment]
@nguyenhuuloc304 I'll close this for now. If you see similar issues with any of the supported versions please feel free to reopen.
