### ISSUE TITLE
tykcommon.HostList contains sync.RWMutex and is copied often

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#368]
This makes go vet very angry, as locks (`sync.RWMutex` in this case) should never be copied implicitly.

Filing a bug instead of fixing it because it's in tykcommon, a few nested levels deep, and not sure what the correct thing to do is. Possible fixes that come to mind:

* Remove the mutex from `HostList` somehow
* Remove `HostList` from one of the parent structs, such as `APIDefinition`
* Avoid copying any of these structs in this codebase

#346 depends on this.

**Comment by lonelycode** [comment]
`HostList` is used extensively in the service discovery system, it *must* be thread safe and the list can change at any time.

I'd say keep the mutex but find where it's being copied, and make that just a pointer reference to be swapped around. 

This code is known to be a bit buggy, if the mutex is being copied all over the shop it might actually explain why some users report random nil pointer dereference panics during SD switchovers.

**Comment by mvdan** [comment]
@lonelycode so which should be a pointer, `APIDefinition` or the `HostList` inside `APIDefinition`?

> if the mutex is being copied all over the shop it might actually explain why some users report random nil pointer dereference panics

Unless the mutex isn't actually used in between copies, or the copies don't happen in practice, this is bound to produce some sort of bug. Can't hurt to fix anyway.

**Comment by lonelycode** [comment]
API Defintions are huge, so they should always be pointers (and I think they are IIRC, went through a refactor a ways back to make sure it wasn;t copied too often).

Hostlist is dynamic and shared across proxies requests (it must be up to date for any single configuration), so it too should be a pointer

**Comment by lonelycode** [comment]
> Unless the mutex isn't actually used in between copies, or the copies don't happen in practice, this is bound to produce some sort of bug. Can't hurt to fix anyway.

Yes I think we should fix it.

**Comment by mvdan** [comment]
> API Defintions are huge, so they should always be pointers (and I think they are IIRC, went through a refactor a ways back to make sure it wasn;t copied too often).
> 
> Hostlist is dynamic and shared across proxies requests (it must be up to date for any single configuration), so it too should be a pointer

Ah, thanks for the pointers. PR incoming soon.

**Comment by mvdan** [comment]
Now fixed, see commits above.
