### ISSUE TITLE
Multiple cosmosdbs created with same name under one account while exporting data from one collection to other in same database

### ISSUE THREAD

**Issue by Mastanvali0223** [TykTechnologies/tyk#3699]
@azurecosmos
We use Microsoft provided tool to take backup of the collection in same database with different collection name Eg: collection_bkp. But this time the export has created a new DB with same name , which is unusual and never allowed. We can't have 2 databases with same name under one account.tried in another account creating another database with same name.documentdb data migration tool is not checking case sensitivity but cosmos checking case sensitivity.

**Comment by andyo-tyk** [comment]
Hi,

We've not been able to reproduce this, so I will close this ticket.

If you still have this issue and are able to provide more detail, please do not hesitate to re-open the ticket.

Thank you for supporting Tyk!
