### ISSUE TITLE
Tests leave apps/1.json behind

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#370]
Not sure what solution is best:

* Not using such a file for the tests
* Cleaning up the file in the tests (even if they fail)
* Adding it to `.gitignore`

CC @lonelycode @buger

**Comment by mvdan** [comment]
Same for `tyk.conf`. This one is in the gitignore. I don't like how it's left in the root of the repo, though.

**Comment by lonelycode** [comment]
We need to have a default conf somewhere that "just works", so might need to leave that, or put it in a folder and change the default load location.

The JSON file is a gateway API test, the test should delete the file (using the API).

**Comment by buger** [comment]
@lonelycode tyk-develop-env can be a good place

**Comment by lonelycode** [comment]
@buger it's for people who build the repo and run locally - tyk develop env is internal only :-)

**Comment by mvdan** [comment]
@lonelycode should `tyk.conf` be deleted too?

Also, why is `1.json` being written to disk at all? It's not useful for the tests since they run fine in parallel. Perhaps we could disable writing to disk entirely?

**Comment by lonelycode** [comment]
If we're not shipping a working conf file with the source (so it works with go build), then yes, but IMO we should have a working reference config somewhere.

the apps/1.json can be deleted, unless it;s another demo, in which case we should move that.

**Comment by mvdan** [comment]
@lonelycode we're talking about the files that the tests generate and are not checked into git. I think you got confused with the files we do check into git?

**Comment by lonelycode** [comment]
They should probably be cleaned up then...

The `1.json` file may be an API test, the gateway API flushes API definitions to disc if you use it to save them
