### ISSUE TITLE
Creating API using `/tyk/apis` should not require trailing slash

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#372]
When I try to send API definition to "/tyk/apis" endpoint it returns 404 HTTP error.
Right now you have to add trailing slash "/tyk/apis/" to make it work.

**Comment by lonelycode** [comment]
👍 But must still support the slash because we have legacy clients that use it.

**Comment by mvdan** [comment]
We should also support stuff like `//tyk//apis///`. Most routers have support for removing extra slashes.

**Comment by lonelycode** [comment]
Tyk Gateway uses some pretty old-school variable extraction. There should be a separate issue to move all API URL variables to a router.

**Comment by mvdan** [comment]
(to clarify anyone not following why this was re-opened - the fix didn't actually work and the test didn't actually test the muxer setup)
