### ISSUE TITLE
Deploy tyk via k8s

### ISSUE THREAD

**Issue by zj611** [TykTechnologies/tyk#3740]
Our team deploy tyk via k8s using deployment resource. One of the bigger issues encountered was the data synchronization between different pods.

For example, if we adjust the app (api1.json) via pod_1, also we call the /tyk/reload to reload the api infos to memory, and then the new api1.json is in effect for the coming request. However, the pod_2 is still remain the old api1.json in its memory, so the new adjusted api1.json is not in effect for the coming request hit by pod_2.

How to solve this problem of data synchronization, thanks a lot.

**Comment by sedkis** [comment]
Hey! @zj611 

Unfortunately this is is one of the limitations with Tyk OSS.  Your options are
1) use a [licensed Tyk](https://tyk.io/docs/tyk-on-premises/licensing/) install, which syncs and manages 1-n Tyk gateways
2) Build your own synchronization in CICD etc.

In either direction, it won't solve the sync issue, however I suggest you take a look at [Tyk Operator](https://github.com/TykTechnologies/tyk-operator) as a means for managing your API definitions + policies in k8s primitives (CRDs)

Sorry we can't be more helpful.

Cheers
