### ISSUE TITLE
Endpoint Designer does not allow . in at least request header names

### ISSUE THREAD

**Issue by gwshaw** [TykTechnologies/tyk#375]
**Bug**
Endpoint designer will not save if a modify-header request header defined with a period in the name, e.g: `X-WF.Api-Secret`. Periods are allowed characters in header names.

https://tools.ietf.org/html/rfc2616#page-31 defines a field name as a token.
https://tools.ietf.org/html/rfc2616#page-16 defines a token as:
```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```
and https://tools.ietf.org/html/rfc2616#page-16 defines CHAR and CTL
```
       CHAR           = <any US-ASCII character (octets 0 - 127)>
       CTL            = <any US-ASCII control character
                        (octets 0 - 31) and DEL (127)>
```
Note that a period is not a disallowed character.

**What is the current behavior?**
Clicking update returns the error 'Failed to update Org object to DB'

**What is the expected behavior?**
Successful update.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a request header with a period in the name as above.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Current community cloud version.

While I can work around the problem by exporting, editing and reimporting the Api Definition, the problem prevents saving any edits in the dashboard after that change is made.

**Comment by buger** [comment]
Thank you for a such detailed description! Looking into it.

**Comment by buger** [comment]
I just checked, and it is tricky. The database we using for dashboard do not allow "dots" in key names, and the header name used as a key...  Fixing this bug will require touching all parts of the system.

We've put this issue to our backlog, but I do not have any release date yet.

Thank you!
