### ISSUE TITLE
[TT-4056] Pass raw response to transform response template when body de-derialization fails

### ISSUE THREAD

**Issue by Bouwdie** [TykTechnologies/tyk#3766]
**Is your feature request related to a problem? Please describe.**
When json or xml coding fails the response is not available in the template. I have a legacy API that returns errors as a plain string, which makes me lose the message.

**Describe the solution you'd like**
If the de-serialization fails, I would like the raw response body to be available in the template so i can still act on it.

**Describe alternatives you've considered**

**Additional context**
This will be backwards breaking if introduced without a feature flag.

**Comment by andyo-tyk** [comment]
Closing as this is not currently on our roadmap, but we may return to it later if there is renewed interest from users.
