### ISSUE TITLE
[TT-4276] Allow configuring High Security configuration property of the New Relic agent

### ISSUE THREAD

**Issue by LowCostCustoms** [TykTechnologies/tyk#3788]
**Is your feature request related to a problem? Please describe.**

So far only NewRelic license key and application name are configurable. However the rest of the configuration properties are set to their default values. Unfortunately for me, that means that I can't publish data to NewRelic if high security is configured for my organization.

**Describe the solution you'd like**

Make HighSecurity property of the NewRelic Agent configurable.

**Describe alternatives you've considered**

I tried to hardcode the configuration property to solve the problem.

**Additional context**

In my case hardcoding `cfg.HighSecurity = true` in `gateway/newrelic.go:21` helped to solve the newrelic connection issue.

**Comment by andyo-tyk** [comment]
Thank you for raising this request.

The future for observability with Tyk is [OpenTelemetry](https://tyk.io/docs/advanced-configuration/distributed-tracing/newrelic/), so at this stage we do not plan to extend the support for other distributed tracing solutions.

If you are able to hard code the HighSecurity parameter in your instance of Tyk, then I recommend that you do so as it is not in the Tyk roadmap at this time to make this a configurable option.
