### ISSUE TITLE
Error with session in Go auth plugin

### ISSUE THREAD

**Issue by achojoao** [TykTechnologies/tyk#3791]
**Branch/Environment/Version**
- Branch/Version: v3.2.2

**Describe the bug**
I have developed a Golang plugin that I use at the auth_check step and it seems that the session is removed afterwards.

**Reproduction steps**
Steps to reproduce the behaviour:

1. Create a Go plugin with this function:

```
func CheckAuthentication(rw http.ResponseWriter, r *http.Request) {
	logger.Error("CheckAuthentication")
	logger.Error(ctx.GetSession(r))
	logger.Error(ctx.GetAuthToken(r))
	accessToken := r.Header.Get(headers.Authorization)
	session := &user.SessionState{
		KeyID: accessToken,
		MetaData: map[string]interface{}{
			"token": accessToken,
		},
	}
	logger.Error("CheckAuthentication 1")
	ctx.SetSession(r, session, true)
	logger.Error("CheckAuthentication 2")
	logger.Error(ctx.GetAuthToken(r))
}
```

2. Compile the plugin

`docker run --rm -v `pwd`:/plugin-source tykio/tyk-plugin-compiler:v3.2.2 keycloak.so`

3. Add the plugin to the app definition

```
"custom_middleware": {
        "pre": [],
        "auth_check": {
            "name": "CheckAuthentication",
            "path": "./plugins/keycloak/keycloak.so"
        },
}
```
4. Perform a request for the URL proxied in the app definition.

**Actual behaviour**
The plugin gets called, but I always get the error:

`
{
    "error": "Session state is missing or unset! Please make sure that auth headers are properly applied"
}
`

**Expected behaviour**
I expected the request to go through the chain of middleware and eventually be proxied  as specified in the app definition.

**Logs (debug mode or log file):**
time="Dec 16 16:26:04" level=error msg=CheckAuthentication
time="Dec 16 16:26:04" level=error msg="<nil>"
time="Dec 16 16:26:04" level=error 
time="Dec 16 16:26:04" level=error msg="CheckAuthentication 1"
time="Dec 16 16:26:04" level=error msg="CheckAuthentication 2"
time="Dec 16 16:26:04" level=error msg="Bearer eyJhbGciOiJSUzI1NiI.......BLABLABLA"

**Additional context**

- I had a similar plugin perfectly working on Tyk v2.9.2, but now the signature of SetSession has changed.
- Similar error reported in #3627 
- This error also reported by me in https://community.tyk.io/t/error-setting-session-in-go-auth-plugin/5103

**Comment by buger** [comment]
Hi! It is a know 3.2.2 issue, 3.0.8 LTS version (and 3.1.X) should work find in this case.

Sorry for the late response!

**Comment by achojoao** [comment]
Thanks @buger , I'll try previous versions, but, any idea when the fix will be available?

**Comment by ghillbrook-godaddy** [comment]
@buger will this be fixed in a 3.2.3 release or similar? Or will it be fixed as part of 4?

**Comment by alephnull** [comment]
https://github.com/TykTechnologies/tyk-docs/pull/1821 should help. Perhaps even https://github.com/TykTechnologies/tyk-docs/pull/1837 and https://github.com/TykTechnologies/tyk-docs/pull/1824

**Comment by thangntt** [comment]
> Hi @buger. I'm trying to test if the 4.0.0 release has fixed this issue as I can't find it in the release notes, but there is no documentation about how to initialize the plugin for 4.0.0 version at https://tyk.io/docs/plugins/supported-languages/golang/#initialize-plugin. Did you fix this issue or we must use a previous version?

I tried v4.0.0. it worked
