### ISSUE TITLE
To download the tyk, it is time out. 

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#384]
The vender directory is too large, the download will timeout, the proposed version of the management tools through glide(https://github.com/Masterminds/glide), it's great, believe me, I visited.

**Comment by mvdan** [comment]
What exactly did you run?

Tools like glide will still vendor. Even if they used something like git submodules, you would still have to download everything all the same. I don't understand what your suggestion here is.

**Comment by buger** [comment]
@penhauer-xiao probably mean that if you are using smth like glide, you do not have to store vendor folder in GitHub. As a downside, you will have to run initial Glide command to download all the vendor dependencies on the first run.

**Comment by mvdan** [comment]
Then you depend on third-party git repos not disappearing or doing silly things like force-pushing. Which can be an okay thing to assume, but it's not as stable as what we currently have so the decision shouldn't be taken lightly.

Also note that we can't rewrite the git history, so the repo won't get smaller unless you do a shallow clone.

cc @lonelycode

**Comment by buger** [comment]
Yes, that's true if we are talking about our CI, package-cloud and rest of automated stuff. Which probably was the reason why we started using vendoring. GitHub recently fails quite a lot.

Personally, I did not experience timeouts yet.

**Comment by penhauer-xiao** [comment]
@buger  Glide a cache; do not worry about each download, people cooperation, it is too great, is currently I used the best tool; others tyk cloning down, just glide install, ok; believe me.

**Comment by penhauer-xiao** [comment]
@buger  When using the glide version management tool, You do not need to upload the vendor directory, The vender directory is too large.

**Comment by lonelycode** [comment]
We ideally want to avoid third party initialisation and any dependency on the goodwill of others, it puts the build at risk and adds another barrier to adoption for contributors.

It's also an extreme optimisation: some users are experiencing timeouts from girhub: change the entire vendoring system.

Closing this for now.
