### ISSUE TITLE
load balance by weight

### ISSUE THREAD

**Issue by zj611** [TykTechnologies/tyk#3846]
We learned from the official documentation that tyk has a load balancing function, as shown in italics below. However, this method only provides target_lists, and requests each target in a polling method. Does tyk provide a weight-based method for requesting targets? For example, in a way like nginx.

_proxy.enable_load_balancing: Set this value to true to have a Tyk node distribute traffic across a list of servers. **Required: ** You must fill in the target_list section._

_proxy.target_list: A list of upstream targets (can be one or many hosts)._

    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/",
        "target_url": "",
        "strip_listen_path": true,
        "enable_load_balancing": true,
        "target_list": ["http://a.com","http://b.com"],

**Comment by buger** [comment]
Hi! 

Yes, but its not that obvious.
When you do it though the UI you can control url weight, but the only thing it does it duplicates urls in the urls list. 
So if your target urls array looks like: [a, a, a, b] - a url will have weight 3 and b 1.

Hope it makes sense!

**Comment by zj611** [comment]
All right, thanks for your reply @buger.
The method you mentioned is exactly our current practice, in order to achieve weight-based load balancing.
