### ISSUE TITLE
[TT-4667] Wrong config fields were added to tyk.conf example files

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#3906]
The following fields were added to the files tyk.conf , tyk.conf.example and maybe more in tyk repo and same for to tyk-gateway-docker 

```
"type": "csv",
"csv_dir": "/tmp",
"mongo_url": "",
"mongo_db_name": "",
"mongo_collection": "",
"purge_delay": -1,
```

1. `type` - can be either `rpc` or `anything else`. Better to put an empty string""
2. `csv_dir` and `mongo_*` - don’t exists (probably were copied from the pump by mistake)
3. `purge_delay` - doesn’t exists (probably were copied from the pump by mistake). Should be `purge_interval` - 

It’s important to first remove this just to avoid confusion for our users.

**Comment by andyo-tyk** [comment]
This is in the process of being resolved, and is tracked internally, so I'll close this ticket due to the age.
