### ISSUE TITLE
Enable rate limiting by IP Address

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#393]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the expected behavior?**
As a user I should be able to set CIDR IP address patterns in place of auth tokens and apply ACL, Rate limits and Quotas (session objects) to requests matching those IP addresses.

**Comment by penhauer-xiao** [comment]
Great, I also feel the current tyk rate limit is too single, IP rate limiting and API rate limiting are particularly good features;   my own branch has implemented the API rate limiting feature and is validating it.

**Comment by lonelycode** [comment]
Can you share the API rate limiting feature? It's a roadmap feature we're looking at ;-)

**Comment by penhauer-xiao** [comment]
@lonelycode  Okay, I'm sure everything is ok and share it again. Thank you.
