### ISSUE TITLE
Issue when trying to apply plugin to another endpoint - plugin already loaded

### ISSUE THREAD

**Issue by certinoaaron** [TykTechnologies/tyk#3972]
**Branch/Version:**  Gateway v3.0.8 
**Environment:** On-Prem

**Describe the bug**
When trying to apply a native golang plugin to another api endpoint it fails and the gateway logs show the following. 

<img width="882" alt="Screenshot 2022-03-30 at 15 39 51" src="https://user-images.githubusercontent.com/91699864/160861794-dca440d8-ccb6-4e83-a9ea-8f0c90ece0fb.png">

 Just to clarify that it works only if you apply the plugin to a single endpoint

**Actual behavior**
fails to load plugin to another endpoint

**Expected behavior**
To apply the same plugin to multiple endpoints

**Comment by buger** [comment]
Hello! 

I'm pretty sure this issue should be solved with 3.0.10

Thanks!
