### ISSUE TITLE
Auth via querystring no longer works in v2.3.2

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#406]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I create an API that uses both header and querystring locations for tokens, I receive an "authorization field missing" error:

`GET https://server/test-api/get?auth=xxxxx`

Response:

```
{
    "error": "Authorization field missing"
}
```

**What is the expected behavior?**

The API should respond if the key is valid.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Use the [API Definition linked here](https://gist.github.com/lonelycode/d430ba7e2aa72fe6d81c753f85c967e8)
2. Generate an auth token that has access to this API
2. Make a request to the API with the auth token in the querystring: `https://server/test-api/get?auth=xxxxx`

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

v2.3.2 pre-release

**Comment by buger** [comment]
Neither I or @ilijabojanovic can't replicate this bug. Both param and header auth works as expected. 

Can it be that you mistyped api_key or similar?

**Comment by lonelycode** [comment]
Closing because magic seems to have resolved it, or I'm an eejit.

**Comment by mvdan** [comment]
I didn't introduce a bug after all. Huzzah!
