### ISSUE TITLE
Create Policy endpoint in 4.1-rc12 gives read-only filesystem error in K8s

### ISSUE THREAD

**Issue by brahama** [TykTechnologies/tyk#4139]
**Branch/Environment/Version**
- Branch/Version: 4.1.0-rc12
- Environment: OSS K8s Image

**Describe the bug**
When using create policy endpoint API it shows an error and in the GW logs you can see

```
time="Jun 18 22:13:23" level=error msg="Failed to create file! - open 61771aa34fb23a000178d4df.json: read-only file system"
```

Cheers!

**Comment by buger** [comment]
Hi! I guess it kind of expected, since in OSS version both API and Policy are files. 
You should get same error for API endpoint in this case. 
So you either mount some volume, make it writable and etc.
