### ISSUE TITLE
Use more error returns instead of logs

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#414]
A lot of the code in the gateway reports errors in the log and returns nil or empty values. This makes writing code somewhat faster, but has several disadvantages:

* Unit testing is impossible. How does the test know if the function encountered an error?
* Calling function can't know if there was an error either, especially if a nil/zero return value could be an OK thing to return.
* Any func that uses a global logger is not suitable for an importable package. Blocker for #308.

I propose we start removing logs in small functions we want to add unit tests for. Making an importable package completely free of logs is also desirable, but would be a major rewrite. Better to get to that once we have good unit test coverage.

cc @lonelycode @buger

**Comment by buger** [comment]
I assume that we should keep logs and improve error codes.

**Comment by mvdan** [comment]
If we keep the logs, all the disadvantages listed there don't improve. What do you mean by `error codes`?

**Comment by buger** [comment]
> Any func that uses a global logger is not suitable for an importable package. Blocker for #308.

I do not think we going to work on it in near future (year). Do not think we should plan for this use case at all, at least now.

By error codes, I mean making functions to return proper error messages, instead of just boolean variables or nil values.

We need logs we currently have, not only for internal debugging but for our customers too. Instead of removing them, we should try move logs out of functions, to the places where they get called - based on returned error, or its absence.

**Comment by mvdan** [comment]
> I do not think we going to work on it in near future (year). Do not think we should plan for this use case at all, at least now.

This is what I said in the original issue :)

> By error codes, I mean making functions to return proper error objects/messages, instead of just boolean variables or nil values.

> We need logs we currently have, not only for internal debugging but for our customers too. Instead of removing them, we should try move logs out of functions, to the places where they get called - based on returned error, or its absence.

Yes, of course. When I said removing logs, I meant moving them out to their parent funcs. The more funcs we have that just return errors, the better.

**Comment by buger** [comment]
👍

**Comment by mvdan** [comment]
Then again, keeping this issue open doesn't help much. Hard to tell when this will be "done" and it's not a priority.

cc @matiasinsaurralde
