### ISSUE TITLE
How to make Tyk as the "origin of the request"?

### ISSUE THREAD

**Issue by rahulbaid** [TykTechnologies/tyk#4142]
* I have deployed Tyk on AWS account A. I have bunch of internal APIs in an AWS account B, where I have whitelisted the NAT gateway IP of AWS account A, so that I can make requests from account A to account B. 
* I am trying to expose the internal APIs through Tyk Gateway. 
* Tyk is proxying (or redirecting) my HTTP requests correctly as a traditional API gateway should. But it is setting the “X-Forwarded-For” as my local IP from where I am making the requests from, which results in the internal API rejecting the request with a HTTP 403 Forbidden error. 

I have already tried stripping `X-Forwarded-For` headers in the API definition (`global_headers_remove`) but it seems like Tyk adds that header later on. I have tried using a virtual endpoint and `TykMakeHttpRequest` method. 

In a sense, how do I make Tyk as the “origin of the request”?

Open to suggestions on how to make this work.

**Comment by vverbani** [comment]
Hi @rahulbaid,

Thank you for submitting this. I would have suggested/ expected the `global_headers_remove` to work in this case. I'll relay this to our internal engineering team for a solution.
