### ISSUE TITLE
Ability to globally disable detailed logging

### ISSUE THREAD

**Issue by jvisker** [TykTechnologies/tyk#4149]
**Is your feature request related to a problem? Please describe.**
From a security perspective it is concerning that detailed logging can be turned on so easily. Especially if we don't want it on ever.

**Describe the solution you'd like**
Add a new config parameter that will allow us to disable detailed logging globally.

**Describe alternatives you've considered**
We can just try to make sure that is never enabled on any of the APIs.

**Comment by zalbiraw** [comment]
Hello @jvisker that can definitely be done.

You can turn off detailed logging on [gateway level](https://tyk.io/docs/tyk-oss-gateway/configuration/#analytics_configenable_detailed_recording), [globally in Tyk Pump](https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables/#omit_detailed_recording) or per [pump](https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables/#pumpsmongoomit_detailed_recording). 

Hope this helps!

**Comment by jvisker** [comment]
You can turn it off on the pumps, but not at the gateway. On the gateway that flag controls the global default but still allows it to be overridden at the api and session level. I wouldn't want it to be overridden in this scenario.

**Comment by zalbiraw** [comment]
Ah gotcha!

**Comment by andyo-tyk** [comment]
The future of Tyk's analytics logging (as part of Observability) lies with Open Telemetry. We won't be implementing this suggestion as-is, however the additional flexibility that will be introduced with Open Telemetry should, I believe, meet your needs.
