### ISSUE TITLE
[TT-6093]Headers removed during coprocess "response" middleware are not deleted for response sent to client

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk#4192]
**Branch/Environment/Version**
- master / 4.0.3
- Environment: on-prem

**Describe the bug**
When using a coprocess middleware for the "response" hook, Tyk does not delete headers which have been removed from the response object during response middleware.

**Reproduction steps**

1. Add API which uses plugin bundle for coprocess response middleware.
2. From middleware, remove headers from response object.

**Actual behavior**
Tyk should remove headers from the response prior to returning it to the client. New headers can be added to the response object from middleware, but headers are not removed.

**Expected behavior**
Tyk should remove headers from the response prior to returning it to the client.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
n/a

**Configuration (tyk config file):**
n/a

**Additional context**
See following files using a Java-based gRPC middleware example:
* [TykDefinition.json.txt](https://github.com/TykTechnologies/tyk/files/9141451/TykDefinition.json.txt)
* [gateway-response-1.0.zip](https://github.com/TykTechnologies/tyk/files/9141455/gateway-response-1.0.zip)
* [PluginDispatcher.java.txt](https://github.com/TykTechnologies/tyk/files/9141453/PluginDispatcher.java.txt)

**Comment by ashaparulkar** [comment]
Hello @l3ender,

Thanks for raising this issue.
We have raised internal ticket to review and fix this issue.

**Comment by sredxny** [comment]
@buger it works as expected. tested manually using a grpc plugin developed in node js
