### ISSUE TITLE
Add default user agent config option

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#422]
**Do you want to request a *feature* or report a *bug*?**
Enhancement
**What is the current behaviour?**
If the User Agent header is deleted in an API endpoint, the default User Agent set by the "net/http" package in Go ("Go-http-client/1.1") is added instead which can cause issues for users with strict security settings, &c. The existing work-around for users is to simultaneously remove and add the header in the endpoint.
**What is the expected behaviour?**
Some users expect to the deleted header to stay deleted. The Gateway should at least override the default the string with an empty string if one isn't set by the user. 
**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The current behaviour is the default behaviour.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions are affected as this behaviour is caused by the "net/http" package

**Comment by buger** [comment]
User-Agent header is a special case, and `net/http` logic is that if the header is not set, it sets the default value, unless it set to empty value. In our case, the proper fix will be check if "User-Agent" header in headers that needs to be removed, and internally "add" empty header.

**Comment by buger** [comment]
Worth noticing this issue was discovered when working on following support request https://support.tyk.io/helpdesk/tickets/744

The customer also asked if we can add an option to not add default user-agent header. So basically if we see that incoming request has no "User-Agent" header, we should set it internally to the empty value.

**Comment by lonelycode** [comment]
We might just want to add an option: `force_user_agent_string: "foo"` to the config, that will override it. If it is blank, we leave it as is?

**Comment by buger** [comment]
It is not about forcing (it can be done using existing dashboard/tyk config). It is about not adding it by default. So a customer may send User-Agent header, and it will be forwarded to the API, or he may not send any User-Agent and our gateway will not add default Go header.

**Comment by lonelycode** [comment]
> It is not about forcing (it can be done using existing dashboard/tyk config). 

Yes it can, but you need to do it on an API by API basis, which is not practical for users that are managing 100's of APIs (many are). So forcing it means that you could actually then create firewall rules that allow the gateway-sourced requests through.

> So a customer may send User-Agent header, and it will be forwarded to the API, or he may not send any User-Agent and our gateway will not add default Go header.

Good point, we should also be able to `"allow_empty_user_agent": true`, that can cover this case.

**Comment by buger** [comment]
This feature request was part of a deeper problem, and we may fix it more conveniently. 
The user wanted to remove default User-Agent not because it just was there, but because his system administrator disabled standard Go UA for security reason (probably protection against scrapping).

So maybe instead of all these options, we discuss above, make sense add "default_user_agent: <string>", which kinda solve all the requests.

**Comment by lonelycode** [comment]
> So maybe instead of all these options, we discuss above, make sense add "default_user_agent: ", which kinda solve all the requests.

sgtm

**Comment by catdevnull** [comment]
Thanks for your work on this. Looking forward to it in the next version.

**Comment by mvdan** [comment]
@ilijabojanovic please unassign yourself when adding the "QA ready" label, to make it clearer that it's up for grabs to implement.

**Comment by mvdan** [comment]
By the way, should this setting default to empty string (no defualt user-agent string) or to something that says Tyk/Go? I assume our default is one that says Go now, as that's the `net/http` default unless you do otherwise.

**Comment by catdevnull** [comment]
Personally I'd say default to Tyk/x.x.x (where x.x.x is the gateway version) as the User Agent string if the default isn't set.

The default Go user agent string potentially causes confusion downstream, a Tyk specific one would be much more obvious to identity in downstream Web Application Firewalls and the like.

**Comment by mvdan** [comment]
To clarify, we've decided to set the default user agent in the Tyk reverse proxy to `Tyk/VERSION`, like `Tyk/v2.3.7`. This default will not be set if an user agent was set by the client, even if it was empty.

We haven't added an option to change when the user agent is set and the user agent string itself. We haven't seen a user specifically ask for these two things. If anyone would find either useful, please speak up or open a separate issue.
