### ISSUE TITLE
[TT-6288] Rollbar integration

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [TykTechnologies/tyk#4229]
**Is your feature request related to a problem? Please describe.**
We want to have a way to monitor Tyk errors using an external monitoring tool like Rollbar

**Describe the solution you'd like**
We'd like to have env vars to configure Rollbar monitoring

**Describe alternatives you've considered**

**Additional context**

**Comment by mhuaco** [comment]
Hello and Welcome! Thank you for submitting the enhancement request. I have raised an internal ticket with our engineers to review, and although we currently do not have Rollbar as an option, we have other monitoring/ data logging tools you can try. 

For example, Splunk might be an alternative, which you would have the option to configure using env vars.

Here is some info on Supported Backends:
https://tyk.io/docs/tyk-stack/tyk-pump/other-data-stores/
https://github.com/TykTechnologies/tyk-pump

Thanks again! We'll update you as soon we get some feedback regarding Rollbar.

**Comment by ca-simone-chiorazzo** [comment]
Hi @mhuaco , thanks for the info. Did you have any update from the engineering team about this?

We saw that you support Splunk, but we'd like to stick to Rollbar to keep centralized management for error tracking.

Thanks in advance,
Simone

**Comment by christtyk** [comment]
@andyo-tyk I'm not sure if your current work on integrations would cover this request?

In general, we don't have any other demand for a Rollbar integration so it's not a huge priority for our development team at this point in time - we'd happily accept a PR if you want to contribute though :)

**Comment by andyo-tyk** [comment]
It looks like Rollbar requires the instrumentation of Tyk with its own SDK, rather than supporting Open Telemetry signals, so I think it would be a separate integration, unfortunately.

We are inclined towards vendor neutral standards as we develop the observability capability of Tyk, but as @christtyk has said above, we're very open to community PRs.

**Comment by buger** [comment]
Btw, it is possible to use Sentry for the use-case you describe https://tyk.io/docs/tyk-oss-gateway/configuration/#use_sentry, so if you going to do the PR, it can be inspiration in terms of implementation.

**Comment by andyo-tyk** [comment]
We don't have plans to implement Rollbar support for the forseeable future, as we are looking towards Open Telemetry for our future Observability strategy.
