### ISSUE TITLE
[TT-6145]Older version of goverify doesn't support PKCS#8 private keys and PKCS#1 public keys

### ISSUE THREAD

**Issue by patriziobrunops** [TykTechnologies/tyk#4293]
**Branch/Environment/Version**
- Branch/Version: master
- Environment: *

**Describe the bug**
Tyk uses an older version `goverify` to load private and public keys to sign and verify golang plugin bundles. That version of `goverify` supported only PKCS#1 private keys and PKCS#8 public keys, forcing users to generate the sign key-pair in a format and than convert it in a different format.

**Reproduction steps**
- **Scenario A:**
  1. generate a public key-pair and store it in PKCS#8 format
  2. configure `tyk.conf` to use the public key
  3. sign a plugin bundle with the private key

- **Scenario B:**
  1. generate a public key-pair and store it in PKCS#1 format
  2. configure `tyk.conf` to use the public key
  3. tsign a plugin bundle with the private key

**Actual behavior**
- Scenario A will fail when attempting to sign the plugin with the error message `tyk: error: ssh: unsupported key type "PRIVATE KEY", try --help`.
- Scenario B will fail when tyk-gateway will try to load the public key.

**Expected behavior**
Generate a key-pair in either PKCS#1 or PKCS#8 - the latter is preferable as it contains metadata about the key, algorithm, key-size, et; while PKCS#1 is just the key in text format.

**Comment by pagemag** [comment]
Hi @patriziobrunops , 
Thanks for posting this issue and for the PR you mentioned. Our engineering team are currently reviewing and discussing this fix.

**Comment by patriziobrunops** [comment]
Fixed by #4226
