### ISSUE TITLE
Improve csv purger

### ISSUE THREAD

**Issue by mNantern** [TykTechnologies/tyk#43]
We would like to do analytics but without MongoDB.

Unfortunately, CSV export is a little poor. Is it possible to dump the same value in CSV as in MongoDB ?

**Comment by mNantern** [comment]
Something new on that ?

How can I help ?

**Comment by lonelycode** [comment]
Hi, If you're up for it, the CSV purger is here:

https://github.com/lonelycode/tyk/blob/master/analytics.go#L125

As you can see two things need doing, the headers need expanding and the puurge map lower down needs to use the hole object (https://github.com/lonelycode/tyk/blob/master/analytics.go#L15). 

Trickiest thing would be to make sure values are converted properly.

:-)

**Comment by JosephEarl** [comment]
I think this can be closed now. The CSV pump with Tyk 2.0 writes out the whole struct - https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/csv.go.
