### ISSUE TITLE
API object validation fails when updating a Swagger document

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#430]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
API object validation fails when updating a listen path for an API imported via a Swagger document because the `API slug` field is empty during an update.

**What is the expected behaviour?**
It should be possible to update an API

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Import a swagger definition file via the REST API
2. Send a PUT request updating the imported API's listen-path

At this point, the response should contain an "API object validation failure" message.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This issue has been reported in v2.3 of the Gateway

**Comment by buger** [comment]
Closing in favor of https://github.com/TykTechnologies/tyk-analytics/issues/52
