### ISSUE TITLE
Feature Request: include expiry date meta-data in header

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#437]
As an API consumer, if I make a request for an API which has an expiry date, the response will include the expiry date as meta data in the header.

**Comment by mvdan** [comment]
@davegarvey were you thinking a custom header, or reusing an existing one like [cache-control](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#cache-control)?

The problem with cache-control is that it might get clients to cache API responses, which I assume we don't want.

/cc @buger

**Comment by davegarvey** [comment]
This would be a custom header e.g. `x-api-expires`. The value of which is the datetime of the API expiry.

**Comment by mvdan** [comment]
Do we have any naming scheme for these? Most are `x-tyk-*`, but some aren't like `x-ratelimit-limit`. I can't see any `x-api-*` uses yet.

**Comment by davegarvey** [comment]
I'm not aware of a naming scheme, but I think it's best to include `tyk` in there as you suggest, so `x-tyk-api-expires`.

**Comment by mvdan** [comment]
Note to self: use RFC1123 for the time format, as described in the HTTP/1.1 RFC:

> HTTP/1.1 clients and servers that parse the date value MUST accept all three formats (for compatibility with HTTP/1.0), though they MUST only generate the RFC 1123 format for representing HTTP-date values in header fields.
