### ISSUE TITLE
endpoint designer changes removes default jwt policy

### ISSUE THREAD

**Issue by availitynick** [TykTechnologies/tyk#4378]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Making changes in the endpoint designer intermittently removes the default jwt policy

**What is the expected behavior?**
Default jwt policy should not be modified when making changes in the endpoint designer

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create API with JWT authentication
Select a default JWT policy
Save API
Make any change in the endpoint designer (I was specifically making adv url rewrite changes)
Save API
Check that the default JWT policy is now empty
Might need to repeat once more since it seem to happen every other time to me.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
4.0.8-1

**Comment by sedkis** [comment]
Closing for same as https://github.com/TykTechnologies/tyk/issues/4379
