### ISSUE TITLE
DCR not working when approving key requests

### ISSUE THREAD

**Issue by availitynick** [TykTechnologies/tyk#4379]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If a catalogue has manual access approval, once the key request is approved, the DCR request is never sent to the IDP.

**What is the expected behavior?**
Once the key request is manually approved, a DCR request should be sent to the IDP to retrieve the client id/secret.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Setup DCR & manual access approval in portal management settings
Create API protected by JWT
Create Policy & Catalogue
create new client in classic portal
Approve key request in dashboard

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
4.0.8

**Comment by sedkis** [comment]
@availitynick  - apols for lack of response on your two open issues.  This repo is for open source Gateway.  These issues are for the closed-source product, and should be flagged via support team.  However these have already been actioned.  Thanks!
