### ISSUE TITLE
proposal: rethink logging

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#442]
Right now we use a global logger object for all of our log calls. This has several disadvantages (from easiest to hardest to fix):

* It is weirdly difficult to remove all logging - right now we have to redirect the logger to `ioutil.Discard`, which isn't exactly free
* If tyk is ever to be used as an importable package (library), this will not integrate with the caller's logging
* When tests are run in parallel, it's very hard (impossible?) to tell what log lines originate from what test

There is an ongoing discussion about logging standarization, which might be relevant: https://groups.google.com/forum/#!topic/golang-dev/F3l9Iz1JX4g

There are lots of people in the Go community who hate global package-level loggers. I don't know what the alternative to it is, though, besides just removing all logging.

**Comment by mvdan** [comment]
Note that the first two could be fixed by making the global `var log` an interface, replaceable with a stub (to remove all logging) or another package's logging system.

The problem with the latter is that the interfaces probably won't match, hence the standardization discussion.

**Comment by mvdan** [comment]
@buger also suggested that, to fix the third one, we could use "goroutine IDs". Unfortunately, this is advised against since people could abuse it to have "thread-local storage", which doesn't make sense in Go. I'd like to avoid implementing this in a hacky way.

**Comment by lonelycode** [comment]
> If tyk is ever to be used as an importable package (library), this will not integrate with the caller's logging

This isn't a design goal at the moment, so would suggest this is premature optimisation.

I don't think we're going to be switching out logging frameworks any time soon (i.e. `logrus` is probably here to stay for the foreseeable future).

The interface route is probably the best path to take, but I would just standardise on `logrus`, that makes the interface easier, and we should only focus on compatibility within Tyk code.

If the global `log` variable is set to an interface, and then initialised by `init()` then we can basically use the fact `logrus` is hook-driven to write a new hook that just works for the tests. Hooks are pretty easy to write.

To fix the third issue of knowing what to log, can we have two behaviours:

1. All tests: no logs 
2. Single test run: show logs

If tests fail in parallel, then we can always just run the failed test with a flag to get the logs output?

**Comment by mvdan** [comment]
> This isn't a design goal at the moment, so would suggest this is premature optimisation.

I realise it's not a blocker in the short term, which is why it doesn't have a milestone. I don't see why that's reason to ignore it, though.

> The interface route is probably the best path to take, but I would just standardise on logrus, that makes the interface easier, and we should only focus on compatibility within Tyk code.

Yes, that's the first step that we could take.

> If tests fail in parallel, then we can always just run the failed test with a flag to get the logs output?

This won't work if the test is flaky (hard to reproduce) or if it failed because of it running in parallel.

We figured out a short-term solution with @buger, which consists of Travis running tests twice:

* sequentially with full logging
* in parallel with `-race` and no logging

This still doesn't fix the problem above, but it's better than having mixed up logs because of parallel tests. It will be configurable via `TYK_LOGLEVEL` in any case.

**Comment by lonelycode** [comment]
sgtm.

Importable package thing - still think it's not relevant.

**Comment by mvdan** [comment]
Would you rather close this once the interface is done and keep track of all stuff relevant to the importable package in that issue?

**Comment by lonelycode** [comment]
Let's separate them out :-)
