### ISSUE TITLE
cannot have go-plugin bundles with support for v4.0.x and >=v4.1 

### ISSUE THREAD

**Issue by patriziobrunops** [TykTechnologies/tyk#4447]
I need to publish bundles containing go-plugins that support tyk-gateway v4.0 and >=v4.1. I'm currently running tyk-gateway 4.0.9 and I plan to update to v4.2.4. I have dozens of API definitions that use go-plugins for authorization. To prevent downtime, I need a plugin bundle that is compatible with all versions of Tyk.

Tyk >=v4.1 already supports plugin versioning in such a way that if the plain plugin name is not available, the versioned one is going to be used. v4.0.9 doesn't support such a behaviour and if the plain plugin name is not available, it simply fails.

**What is the current behavior?**
Currently, Tyk >=v4.1 supports plugin bundles compatible with multiple versions. So, once updated to v4.2.4 I'll be able to run such bundles. But in order to do that I need to allow some downtime when I update the gateway. The steps to update are as follows:
- build a new plugin bundle with plugins compatible with v4.2.4
- update the gateway to v4.2.4, during this phase my api-definition will be unable to run the authorization plugin, blocking my users
- change all of my api-definitions to use the new bundle

**What is the expected behavior?**
Build a bundle with plugins for v4.0.9 and v4.2.4 and when I update the gateway there's no downtime.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

**Comment by andyo-tyk** [comment]
Hi @patriziobrunops,

Sorry, closing this ticket was missed: we applied a solution for this in 4.3.2 (as discussed in your PR which you linked to this issue).

This is included from Tyk 4.3.2 onwards (and so is supported in current Tyk 5.x versions).
