### ISSUE TITLE
Extend token tags with policy tags instead of overwriting

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#447]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Tags on a policy will overwrite tags on a token, meaning custom individualised tags are lost 

**What is the expected behavior?**
That tags that are included in a policy extend a token's tag set (and by proxy appear in the analytics data set). 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
Enhancement with no assignee by the time of the feature freeze, so moving to 2.5 for now.
