### ISSUE TITLE
Bundle download doesn't support growing back-off

### ISSUE THREAD

**Issue by patriziobrunops** [TykTechnologies/tyk#4481]
**Branch/Environment/Version**
- master

**Describe the bug**
When a plugin bundle download fails there's no back-off before subsequent attempts. Also, after 4 attempts in a space of a few milliseconds, no further attempts are made

**Reproduction steps**

1. Configure Tyk to `enable_bundle_downloader` and set `bundle_base_url`
2. Don't publish the bundle at the expected location
3. Add api requesting a specific middleware bundle

**Actual behavior**
Tyk-gateway tries to download the bundle 4 times in the space of 4 milliseconds.

**Expected behavior**
Tyk-gateway wait increasing period of times between the 4 attempts.

**Logs (debug mode or log file):**
```
    "textPayload": "time=\"Nov 20 16:45:09\" level=error msg=\"Couldn't load bundle\" error=\"Couldn't fetch bundle: Get \"http://localhost:8083/dojotykenvoyauthplugin-0.1.77.zip\": dial tcp 127.0.0.1:8083: connect: connection refused\"\n",

```

**Comment by andyo-tyk** [comment]
Thank you for the contribution, @patriziobrunops.

We implemented a solution based on your suggestion in Tyk 4.3.2 / Tyk 4.0.11 (LTS).

**Comment by patriziobruno** [comment]
#4537
