### ISSUE TITLE
tyk-2.9.1: Incorrect version number

### ISSUE THREAD

**Issue by cherishman2005** [TykTechnologies/tyk#4499]
tyk-2.9.1 version is incorrect

![image](https://user-images.githubusercontent.com/17688273/206174214-4bd73045-f5d1-46fd-8bed-7d695286944e.png)

```
# ./tyk --version
v3.0.0
```

https://github.com/TykTechnologies/tyk/blob/2.9.1/gateway/version.go

**Comment by oluwaseyeayinla** [comment]
Fixed. Thanks for spotting
