### ISSUE TITLE
Self-contained gateway benchmarks from real usage data

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#453]
Benchmarks would be useful to know if certain changes noticeably affect performance on the gateway. The problem with hand-written benchmarks is that they would be tailored to very specific functionalities, which might not affect real-world usage at all.

A more interesting benchmark would be at a higher level, firing up the gateway and throwing lots of real-world traffic at it to measure its throughtput.

@buger's https://github.com/buger/goreplay could be useful here.

**Comment by buger** [comment]
I'm not sure what kind of traffic we can record without breaking our NDA, but I assume that it should be possible for our "pure" cloud users (excluding Hyrbrid).

**Comment by mvdan** [comment]
By "real-world" I meant that it reflects what parts of the gateway are used in what proportions. The actual data doesn't have to be real. It's just about keeping the load in the right places.

**Comment by buger** [comment]
I was talking in the context of `goreplay` because it requires your to record live traffic.

**Comment by lonelycode** [comment]
> @buger's https://github.com/buger/goreplay could be useful here.

While it's a very cool application, we can't use our client's traffic for testing, it's their traffic, not ours - we're a proxy and we make guarantees that we store nothing, it ensures compliance across a whole host of potential legal issues. So this is out

Benchmarks that we need would be against each middleware component, especially the auth ones so we can see potential for optimisation. If I look at our instrumentation on cloud for middleware latency, there's a few that could use work. 

The other thing is handling large service installs, so thousands of APIs across many tenants - this is more of a hot-reload speed issue, but important in our cloud and for our larger users.

**Comment by mvdan** [comment]
I agree that separate benchmarks will be useful to prove optimizations. I'm just worried that we would optimize irrelevant stuff if we don't have a global view of where the time is spent.

If you can capture cpu/mem profiles of our cloud, that should be enough to know what requires our attention.

**Comment by lonelycode** [comment]
> If you can capture cpu/mem profiles of our cloud, that should be enough to know what requires our attention.

Would rather not, we autoscale and the environments are constantly being rebuilt/destroyed. I do think benchmarks for the middleware would be fine.

**Comment by mvdan** [comment]
Is there really no way to know what takes most of our resources? Without it, it's very likely that we'll be doing premature optimization in unimportant parts of the gateway.

**Comment by lonelycode** [comment]
We do have data in our statsd dashboard that gives us some indication, but it's on live throughput and not all users use the same components, so it's non-representative sampling.

**Comment by mvdan** [comment]
@lonelycode @buger so to summarize, should we abandon the possibility of a high-level benchmark that throws "realistic" traffic at the gateway and instead focus on lower-level benchmarks, like the one I added that adds a lot of APIs?

**Comment by buger** [comment]
I do not think this is completely true, we just replace it by synthetic traffic which we try to make similar to production as much as possible, maybe multiple profiles. Worth noticing that @ilijabojanovic was planning to implement some of this.

**Comment by mvdan** [comment]
That was my thinking too, but the discussion and silence made me think that we weren't going to do it :) Wanted to make sure it was on the roadmap if we were to keep the issue open.

**Comment by lonelycode** [comment]
I'd say we push this to the load testing stage where we test the integrated components under realistic conditions. We can build a profile of popular middleware from our statsd dashboard and from anecdotal data via the forum.
