### ISSUE TITLE
[TT-7393] Issue Redis Commands from Plugins

### ISSUE THREAD

**Issue by stewartlord** [TykTechnologies/tyk#4545]
**Is your feature request related to a problem? Please describe.**
Unable to directly issue commands to Redis from plugins

**Describe the solution you'd like**
Direct access to the Redis Universal Client

**Describe alternatives you've considered**
Attempted to use the `go:linkname` hack, but that fails to build due to symbols being unavailable.

**Additional context**
Evaluating Tyk at GitHub

**Comment by andyo-tyk** [comment]
Thank you for your contribution to Tyk!

Per the discussion on your PR, we're taking storage management in a different direction, so I'll close this as "won't do".

We really appreciate you taking the time to make the suggestion and welcome any further ideas you have.

Thank you again.
