### ISSUE TITLE
TYK 3.1.2 to 3.1.3 - transport connection broken: too many transfer encodings:

### ISSUE THREAD

**Issue by Quentinvarquet** [TykTechnologies/tyk#4616]
**Branch/Environment/Version** : 3.1.3
- Branch/Version: [e.g. Master/Release/Stable/Feature branch]
- Environment: [e.g. On-prem/Hybrid/MDCB] : open source 

**Describe the bug**
Hello, i upgraded tyk gateway from version 3.1.2 to 3.1.3. I did not see any changed in your changelog but now everytime i will an api, i have this error : 

`time="Jan 05 14:25:08" level=error msg="http: proxy error: net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]" api_id=openApi api_name="api_oauth_v2_oauth2" mw=ReverseProxy org_id= prefix=proxy server_name="destination.build:8080" user_id="****60ef" user_ip="192.168.1.1, 192.168.10.1, 192.168.1.244" user_name=`

If I downgrade to the version 3.1.2, everything is working well

**Actual behavior**
error : transport connection broken: too many transfer encodings:

**Expected behavior**
My api should answer without any problem

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
```
{
  "listen_port": 8082,
  "secret": "*******************************",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/usr/tyk/js/tyk.js",
  "use_db_app_configs": false,
  "app_path": "/usr/tyk/apps",
  "middleware_path": "/usr/tyk/middleware",
  "http_server_options": {
  "read_timeout": 3600,
  "write_timeout": 3600
  },
  "storage": {
    "type": "redis",
    "enable_cluster": true,
    "hosts": {
      "192.168.10.151": "6379",
"192.168.10.250": "6379",
"192.168.10.191": "6379",
"192.168.10.216": "6379",
"192.168.10.231": "6379",
"192.168.10.173": "6379"
    },
    "username": "",
    "password": "",
    "database": 0,
    "optimisation_max_idle": 2000,
    "optimisation_max_active":3000
  },
  "policies": {
    "policy_source": "file",
    "policy_record_name": "/usr/tyk/policies/policies.json"
  },
  "enable_analytics": true,
  "analytics_config": {
    "type": "csv",
    "csv_dir": "/tmp",
    "mongo_url": "",
    "mongo_db_name": "",
    "mongo_collection": "",
    "purge_delay": -1,
    "ignored_ips": []
  },
  "health_check": {
    "enable_health_checks": true,
    "health_check_value_timeouts": 60
  },
  "pid_file_location": "/usr/tyk/tyk-gateway.pid",
  "optimisations_use_async_session_write": true,
  "enable_jsvm": true,
  "jsvm_timeout": 5,
  "oauth_token_expire": 3600,
  "oauth_refresh_token_expire": 36288000,
  "allow_insecure_configs": true,
  "close_connections": true,
  "global_session_lifetime": 36288000
}
```

**Comment by oluwaseyeayinla** [comment]
@Quentinvarquet Sorry for the late response. Have you tried checking if the LTS or the latest version of 4 fixes the issue?

**Comment by oluwaseyeayinla** [comment]
There isn't much change between v3.1.2 and v3.1.3. There was a Redis expiration change but I don't think it affects this issue.
 
Looking further into the error message revealed there might have been a Golang version change. Based on this link https://community.pivotal.io/s/article/Application-Chunked-Error?language=en_US, the reason the error is occurring is that v3.1.3 was built with Golang 1.15.

> Before Golang 1.15, duplicated transfer-encoding headers or headers with two values were permitted by Golang's proxy roundTrip. However, starting in Golang 1.15, the implementation is more strict

**Comment by Quentinvarquet** [comment]
Hello, I will have a look ! Thank you for your answer
