### ISSUE TITLE
Reconsider the redis test dependency

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#469]
See https://github.com/TykTechnologies/tyk/pull/465#issuecomment-277032009.

Miniredis doesn't support pub/sub but we need it. It's a limitation deep in its stack though, so unlikely to be in our power to fix it in the short term.

Giving up on pub/sub isn't an option either, at least not until we do away with Redis. But that won't happen for at least a few months yet.

What options do we have, besides undoing my commit that adds miniredis and depending on redis again?

cc @TykTechnologies/engineering

**Comment by matiasinsaurralde** [comment]
We could continue using Redis and prepare a fix to support pubsub on miniredis, even if it's limited.

**Comment by mvdan** [comment]
The discussion at https://github.com/alicebob/miniredis/issues/1 tells me that this wouldn't be easy. If anyone wants to have a go at it they're welcome to, but I don't think we should hold up new tests like your PR until we have it working.

**Comment by buger** [comment]
What about trying https://github.com/rafaeljusto/redigomock ?

**Comment by lonelycode** [comment]
Most CI tools support redis as a service - it's only for local dev where it's annoying. Instead of miniredis we should just `FLUSHAL` during teardown.

**Comment by mvdan** [comment]
I want to avoid mocking libraries as that would be quite a lot of work to integrate. The advantage of miniredis is that it was a drop-in replacement.

> it's only for local dev where it's annoying

Yep, this is about making our lives easier when running the tests locally. @lonelycode you said Redis was going to be replaced, but you also said something like it would still stick around. Is it always going to be needed for the tests?

> Instead of miniredis we should just FLUSHAL during teardown.

I assume this is to clean up. That doesn't seem to have affected us at all while we used the real redis, though.

**Comment by buger** [comment]
> That doesn't seem to have affected us at all while we used the real redis, though.
This does not matter for Travis, because on each run it have clean state, but matter for local testing.

As an alternative, we may try make `RedisClusterStorageManager` interface, and for the tests write own implementation (which in most cases will just proxy original calls), which mock pubsub internally using channels.

**Comment by mvdan** [comment]
> This does not matter for Travis, because on each run it have clean state, but matter for local testing.

That's what I meant - I fire up Redis in the morning and keep it up. So it should have been affecting me.

> As an alternative, we may try make RedisClusterStorageManager interface, and for the tests write own implementation (which in most cases will just proxy original calls), which mock pubsub internally using channels.

You mean implementing pub/sub on top of miniredis? This could work.

I'd only do this if we'll definitely need redis in the tests in the long run, though. If it can be removed sometime this year, perhaps it's better to just deal with the real redis for a few months.

**Comment by buger** [comment]
Well in short term we can just rollback Redis, it is quite simple change.

**Comment by mvdan** [comment]
Yeah, that depends on whether we're blocking @matiasinsaurralde, which I guess we are.

**Comment by mvdan** [comment]
If anyone wants to tackle re-adding something like miniredis instead of a full redis, feel free to reopen this issue and submit a PR. As said above, that would require some work to add pub/sub support, at least.

I'm going to close this for now as we do need pub/sub and running a full redis service is bearable.
