### ISSUE TITLE
Sloppy error handling in handler_websocket.go

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#471]
@lonelycode could you please clarify this? (in a func that returns an error)

```
errc := make(chan error, 2)
cp := func(dst io.Writer, src io.Reader) {
        _, err := io.Copy(dst, src)
        errc <- err
}
go cp(d, nc)
go cp(nc, d)

<-errc

return nil, nil
```

Should we ignore errors, or should we treat them? Right now they're ignored, but the code seems like a broken attempt at handling them.

**Comment by lonelycode** [comment]
We should handle errors, even if it just outputting them, if they are not being handled then that was an oversight when we put the functionality in.

**Comment by mvdan** [comment]
Cool, thanks for confirming.
