### ISSUE TITLE
Add access to API Definition in gRPC plugins (especially the listening path)

### ISSUE THREAD

**Issue by jvisker** [TykTechnologies/tyk#4745]
**Is your feature request related to a problem? Please describe.**
There is not an easy to way to access the API Definition in a gRPC plugin. The `Spec` is the closest thing and it only sends the API's ID [here](https://github.com/TykTechnologies/tyk/blob/4835ec7e8f0b5d3c35f7f66b1308342b24e3f50c/gateway/coprocess.go#L140-L144): 

**Describe the solution you'd like**
Add the API Definition (or at least the listening path) to the information sent to gRPC plugins (really all coprocess plugins).

**Describe alternatives you've considered**
We currently use the Golang plugin which allows you to easily access the API Definition. With gRPC the plugin could also make a call to the Tyk instance to get the API Definition, but that seems very inefficient.

**Comment by buger** [comment]
Since it is external service, my recommendation here would pipe it with Gateway API. 
Since you own codebase, you can not just fetch API definition via API but also easily cache it.

**Comment by buger** [comment]
Since it is external service, my recommendation here would pipe it with Gateway API. E.g. fetch API definition via API and cache inside plugin.

**Comment by jvisker** [comment]
That's certainly possible, but not convenient. It is also possibly not consistent with the config data being sent.

**Comment by andyo-tyk** [comment]
Thanks for your idea for a way to improve Tyk.

Per @buger's suggestion, there's a way to get the result you want, but I agree it's not necessarly elegant.

I've logged your idea and if we can we will look to improve the experience when next we are working on this area of the product capability - in which case I will make sure to update you via this issue - however at this point in time I will close the issue.

If you feel this shouldn't be closed, then please don't hesitate to add a further comment.

Thank you again for supporting Tyk!
