### ISSUE TITLE
Body Transformation issue in API clients

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#477]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When body transformation is added to the response of a GET request, a "Could not get any response" error is returned to API testing tools (e.g., Postman or Insomnia). This appears to have been caused by the use of headers like `Transfer-Encoding: chunked` or `Content-Encoding: gzip` in uncompressed responses that are sent by Tyk.

**What is the expected behaviour?**
Instead of producing the error, requests sent to Tyk should return the expected response. 

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create an API and open the edit page in the Dashboard
2. In the Endpoint Designer, add an endpoint that uses the GET method and select "Body Transform"
3. Select "JSON" as the Input Type
4. Add the input for the request as a JSON string.
5. Add the expected JSON response to the "Template" field (e.g., `{ "foo": "bar" }`)
6. Save the API
7. Make a request to the desired endpoint in an API testing tool

At this point, the user should receive an error stating that the client was unable to obtain a response. By contrast, a cURLl request made to  the endpoint should return the JSON response defined in the Endpoint Designer.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions appear to be affected. The existing work-arounds are to either remove the `accept-encoding` header in Postman or to use Middleware as an alternative to body transformation.

**Comment by mvdan** [comment]
I don't know if I'll be able to get to this for 2.4 - already have four unstarted 2.4 issues that need doing.

**Comment by mvdan** [comment]
Yeah, no time for this in 2.4 I'm afraid. Moving to 2.5 for now.

**Comment by joshblakeley** [comment]
Fixed by https://github.com/TykTechnologies/tyk/pull/1529
