### ISSUE TITLE
First and last character of authorization key are not checked

### ISSUE THREAD

**Issue by wtfloris** [TykTechnologies/tyk#4816]
**Branch/Environment/Version**
- Branch/Version: Docker latest (a13aff4403b5) and v5.0rc40 (d620f4ccb1bd)
- Environment: self hosted

**Describe the bug**
Removing or modifying the first or last character (or both) of the authorization token is still seen as a valid authorization token.

**Reproduction steps**

1. Create simple API, key and policy as described in the [self-hosted documentation](https://tyk.io/docs/getting-started/create-api/).
2. Disable "use_keyless" in default API configuration, only allowing API access with a valid key.
3. Do a request with an Authorization header, and remove or modify either the first, last or both the first and last character of the key:

1: Regular request: 
```
# curl -IL -H "Authorization: Bearer 16ef96dfe225d748398aea642e81ec7ae" localhost:8080/hello-world/get
HTTP/1.1 200 OK
```

2: Modified valid request (first and last character omitted): 
```
# curl -IL -H "Authorization: Bearer 6ef96dfe225d748398aea642e81ec7a" localhost:8080/hello-world/get
HTTP/1.1 200 OK
```

3: Modified invalid request (first two characters omitted):
```
# curl -IL -H "Authorization: Bearer ef96dfe225d748398aea642e81ec7ae" localhost:8080/hello-world/get
HTTP/1.1 403 Forbidden
```

**Actual behavior**
A request with a partially valid key is answered as if the key were valid (case 2).

**Expected behavior**
A request should be rejected (with a 403) if the key is incomplete (case 3).

**Logs (debug mode or log file):**
Only case 3 is logged as an `Attempted access with non-existent key`.

**Configuration (tyk config file):**
Default configuration as generated by following the documentation, with one modification:

```
apps/Hello-World.json:
"use_keyless": false,
```

**Additional context**
Not a massive security concern, but it seems like some string indexing is done at some point in the authorization flow where there is an off-by-one error. This seems like it should be an easy fix for someone who speaks Go (which is not me).

I have no experience with Tyk, I just came across this issue while doing some testing. Couldn't find an existing bug report, so hope this helps!

**Comment by oluwaseyeayinla** [comment]
@wtfloris What's your hash function? 

There is a similar issue with using murmur3 as pointed out here https://github.com/TykTechnologies/tyk/issues/2963

**Comment by andyo-tyk** [comment]
@wtfloris do you still have this issue? Did you try with murmur64?

**Comment by wtfloris** [comment]
Sorry @oluwaseyeayinla, I seem to have missed your question back in March. I don't recall setting a hash function anywhere, so I'm assuming this was with all the default settings.

I haven't worked with Tyk in a while so I can't say if the issue is still present (or try with another hash function) right now.

**Comment by andyo-tyk** [comment]
Hi @wtfloris,

Thanks for coming back to me so quickly - I think, given you're no longer blocked by this issue (and we believe it was a known issue with murmur3) I will close it.

Thank you for trying Tyk!
