### ISSUE TITLE
[TT-8297] Enforced Timeout do not work as expected

### ISSUE THREAD

**Issue by ignashkins** [TykTechnologies/tyk#4831]
**Branch/Environment/Version**
- Branch/Version: master
- Environment: all

**Describe the bug**
[This code](https://github.com/TykTechnologies/tyk/blob/master/gateway/reverse_proxy.go#L1266) does not provide individual timeouts for each endpoint.
If MaxConnTime == 0, the transport below when using other endpoints will not be created and the timeout remains the same.

If MaxConnTime is set greater than 0, my guess is that the number of connections will increase, which will affect processing speed.

And it is not clear how it will work with http2...

**Reproduction steps**
1. Add API
2. Add hard_timeouts to extended_paths for multiple endpoints.
3. Execute http requests.

**Actual behavior**
The timeout will be chosen depending on the first called endpoint

**Expected behavior**
A different timeout will be worked for each endpoint

**Configuration (tyk config file):**
tyk.example.conf

**Comment by SDkie** [comment]
If I add timeout for only `GET` method, I see that timeout is also added for other methods like `PUT` and `POST`
<img width="1207" alt="Screenshot 2023-03-12 at 4 19 53 PM" src="https://user-images.githubusercontent.com/1321321/224539862-6300264a-de94-481e-af13-e9db25f98b59.png">

**Comment by SDkie** [comment]
@ignashkins is correct [this](https://github.com/TykTechnologies/tyk/blob/master/gateway/reverse_proxy.go#L1266) code is preventing re-creation of `HTTPTransport`. Because of which the timeout of the first called endpoint is used for all the matching endpoints called later. 

Actually the code structure is allowing to have only one HTTPTransport for all the matching endpoints. But each endpoint might have a different timeout.

**Comment by andyo-tyk** [comment]
Hi @ignashkins 
I just spotted we hadn't replied on this issue - I'm sorry for the delay.

We are actively looking at this one at the moment, aiming to address it in an upcoming patch.
I will update you here when I have a confirmed release version.

Thanks for supporting Tyk!

**Comment by andyo-tyk** [comment]
Hi @ignashkins 

I can confirm that we will be fixing this issue in the Tyk 5.0.7 patch, which is planned for October.

Thanks for supporting Tyk!

**Comment by ignashkins** [comment]
@andyo-tyk 

Good day!  
Is there a solution to the problem at the moment?  
Thank you.
