### ISSUE TITLE
JWT Token IAT tolerance

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#487]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behaviour?**
Tyk currently rejects a JWT if its Issued-At or Expiry date is within 30 seconds of an Single Sign-On server's time as it doesn't set a tolerance for SSO servers that run at different speeds.
**What is the expected behaviour?**
Tyk shouldn't reject tokens if their IAT or EXP is within 30 seconds of the server's respective times.
**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This would affect all previous versions of Tyk as this functionality has yet to be implemented.

**Comment by mvdan** [comment]
Enhancement with no assignee by the time of the feature freeze, so moving to 2.5 for now.
