### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#500]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
There is no way to know Tyk version without actually running it (which is have lot of downsides)
**What is the expected behavior?**
When I run `tyk --version` it just prints current version and exit

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

Worth noticing that this change should be done Dashboard, Pump and Sink projects

**Comment by mvdan** [comment]
> Worth noticing that this change should be done Dashboard, Pump and Sink projects

Would it not be easier to open separate issues? This one will be closed as soon as it's done in the gateway.

**Comment by buger** [comment]
It is definitely should be done like this; I just wanted quickly describe the bug while I remember it. 

Will leave it to the person who starts working on this task: please create separate issues like proposed above.

**Comment by buger** [comment]
Worth noticing that it will be nice to have a way for Dashboard to know this values. For Tyk Gateway having special API request, and for Pump writing special mongodb record.

**Comment by joshblakeley** [comment]
Closing here as this feature already exists in gateway and dashboard, new issue opened in pump [#51](https://github.com/TykTechnologies/tyk-pump/issues/51) for pump implementation
