### ISSUE TITLE
Should recognize ./tyk.conf by default if configuration option not specified

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#501]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
By default, it searches configuration at `/etc/tyk/tyk.conf` location, and if it is not found, it sets default one, and writes it to `./tyk.conf`. If there is already `tyk.conf` in current directory, it will overwrite it :(

**What is the expected behavior?**
If there is local tyk.conf, it should not override it, and should actually use it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create local `tyk.conf` with some custom configuration. Run `tyk` without `--conf` option. `tyk.conf` will be overridden with default config.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

The proper fix will be searching tyk.conf in multiple locations.

**Comment by mvdan** [comment]
This should be done in a way that makes it easy to add paths to the list to search for. For example, we might want to add `~/.config/tyk/tyk.conf` in the future.

**Comment by lonelycode** [comment]
Also `/etc/tyk/tyk.conf` because our package installer overwrites local ones atm.
