### ISSUE TITLE
Enhance coprocess-related errors

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#504]
**Do you want to request a feature or report a bug?**
Feature/enhancement

**What is the current behavior?**
When a user enables the coprocess authentication mechanism and the CP feature isn't enabled or the build isn't a CP build, the authentication doesn't work but no error message is logged for the user.

**What is the expected behavior?**
I'm thinking that we should add more log messages for this kind of situations. Example: when CP authentication is enabled for an API but it's not enabled, we log an explicit message like: "CP Auth is enabled but your build doesn't support this.".

**Comment by nickReyn** [comment]
@matiasinsaurralde what's the status of this please?

**Comment by lonelycode** [comment]
@nickReyn / @matiasinsaurralde If no code has been done against this ticket yet, let's drop it from the 2.4 milestone and move it to 2.4.1

**Comment by buger** [comment]
@matiasinsaurralde bump

**Comment by matiasinsaurralde** [comment]
This was an idea for a small enhancement, we could cover this on #1260 as this PR also modifies some of the rich plugins related Go code, what do you think?
