### ISSUE TITLE
Handle API reloads in a single goroutine

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#506]
See https://github.com/TykTechnologies/tyk/issues/496#issuecomment-279342688.

Our current handling of hot reloads (API reloads) is racy because it concerns multiple goroutines and a global bool that isn't protected by any sort of lock.

I propose that a single goroutine is responsible for it, receiving jobs (e.g. reload requests) via a channel.

**Comment by mvdan** [comment]
@lonelycode @buger it just occurred to me - all sorts of API endpoint changes should be done in such a single goroutine. This would also affect `loadApps`, for example. Do we ever want the muxer to be modified concurrently by two goroutines? I think not.

In any case, step 1 is reloads.

**Comment by lonelycode** [comment]
> Do we ever want the muxer to be modified concurrently by two goroutines? I think not.

No I don't think so, one routine to rule them all...

**Comment by ilijabojanovic** [comment]
Verified and looks good on release-2.3 branch
