### ISSUE TITLE
Ensure that RPC loader returns an object, not nil

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#510]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If the RPC API Definition loader has a disconnect event, it can return a nil object which fails up the chain and causes a runtime panic

**What is the expected behavior?**
The RPC loader should return an empty object

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Not easily reproducible, it requires longitudinal monitoring of a live process against MDCB.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Hybrid / RPC mode of all gateways

**Comment by buger** [comment]
Can you add full backtrace?

**Comment by lonelycode** [comment]
This is all we got:

```
time="Feb 13 17:41:41" level=warning msg="Handler seems to have disconnected, attempting reconnect"
time="Feb 13 17:41:51" level=warning msg="Handler seems to have disconnected, attempting reconnect"
time="Feb 13 17:41:59" level=warning msg="RPC Handler: GetApiDefinitions() returned nil, returning empty string"
time="Feb 13 17:41:59" level=info msg="Storing RPC backup"
time="Feb 13 17:41:59" level=info msg="--> Connecting to DB"
time="Feb 13 17:41:59" level=info msg="--> Connected to DB"
time="Feb 13 17:41:59" level=error msg="Failed decode: unexpected end of JSON input"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x465aea]
```

**Comment by buger** [comment]
Yep, same one as I saw.
