### ISSUE TITLE
[TT-9231] Modified response body with go plugin responses >= 400

### ISSUE THREAD

**Issue by PatrickTaibel** [TykTechnologies/tyk#5141]
**Branch/Environment/Version**
- Branch/Version: 5.0.2, master
- Environment: On-Prem

**Describe the bug**
The change of #4922 causes Tyk to always send an error message to the client when an error within a go plugin occurs. In case the error is caused by a sent status code >= 400 by the plugin itself this is not desiderable as it will append the Tyk error message to an already existing response from the plugin.

**Reproduction steps**
1. Create a go request plugin which writes a status code >= 400 and a response body.
2. Observe the actual response

**Actual behavior**
A Tyk plugin error gets appended to the response body. Example from our application:
`{"error":"Internal server error"}{"error": "plugin function sent error response code: 500"}`
The first JSON object is from our plugin. The second one is from Tyk and shouldn't be there as the response is not a valid JSON anymore.

**Additional context**
I will create a PR with a potential fix in a minute.

**Comment by andyo-tyk** [comment]
Hi @PatrickTaibel ,
Sorry for the slow acknowledgement on this - well spotted (we've also spotted this and it's logged on the backlog to be fixed). Thanks for the PR - I'll get the team to review this.

**Comment by jvisker** [comment]
I (as a part of BYU) logged this same issue internally as well.

**Comment by karthikbhat03** [comment]
Hi @jvisker ,
Any ETA for this release, we are also kind of blocked due to this for our production release as we want to maintain compatibility with our older android and ios released apps.

Thanks.

**Comment by andyo-tyk** [comment]
Hi @PatrickTaibel @jvisker @karthikbhat03,

I'm pleased to confirm that we've got a fix for this issue - it'll be available in Tyk 5.0.7 / Tyk 5.2.2 releases.

Thanks for supporting Tyk!
