### ISSUE TITLE
Method name wildcards in matchers

### ISSUE THREAD

**Issue by LowCostCustoms** [TykTechnologies/tyk#5146]
**Is your feature request related to a problem? Please describe.**
Sometimes, an endpoint must uniformly handle requests regardless of their nature, for instance, a mock for the wrong method calls.

**Describe the solution you'd like**
It would be nice if `Method` matchers had an option to match _any_ method.

**Comment by andyo-tyk** [comment]
Hi @LowCostCustoms,

Thanks for your suggestion.

Unfortunately at this time we're not considering implementing such a solution, so you would need to configure separate mock responses for each method.

We are looking at improving flexibility and reusability when creating APIs, so will bear this use case in mind.

Thank you for supporting Tyk!
