### ISSUE TITLE
Swap uuid library

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#524]
We use https://github.com/nu7hatch/gouuid. Last commit more than 3 years ago, lacking many useful features like `UUID.Bytes()`.

Let's use https://github.com/satori/go.uuid instead. Actually maintained, much more popular and with many more features, including the method above.

We can still use UUID v4 as specified by RFC 4122, so there should be no changes in behaviour. Some code would get simpler too.

Can do this myself if there are no objections. /cc @buger @lonelycode

**Comment by buger** [comment]
Looks good to me.

**Comment by mvdan** [comment]
Leaving open because I still want to replace `github.com/lonelycode/go-uuid/uuid` with `github.com/satori/go.uuid`.
