### ISSUE TITLE
Mutual TLS authentication 

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#526]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Mutual TLS not supported

**What is the expected behavior?**
Mutual TLS is quite common in B2B API's, it involves creating your own Certification Authority, self-signing the server and client certificate for the Tyk API, and installing your Certification Authority and the client certificate in a browser. Here is really nice explanation https://blog.codeship.com/how-to-set-up-mutual-tls-authentication/

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

**Comment by mvdan** [comment]
We probably want @lonelycode's input on whether this is something we want to do or not. Chances are this feature has been requested before.

**Comment by mvdan** [comment]
Actually, I'm probably wrong as I've never used mutual TLS before, but isn't this a dup of https://github.com/TykTechnologies/tyk/issues/357?

**Comment by buger** [comment]
This looks very similar.

**Comment by lonelycode** [comment]
It is indeed a duplicate. Suggest we stick with the other ticket as it has links with dependent projects already
