### ISSUE TITLE
panic: http: multiple registrations for /

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#531]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Tyk starts failing on start, restarting it does not help.
```
[Feb 16 17:39:01] INFO main: Processed and listening on: /isAlive{rest:.*}
[Feb 16 17:39:01] INFO main: Processed and listening on: /v2.0/{rest:.*}
[Feb 16 17:39:01] INFO main: Processed and listening on: /doc/{rest:.*}
[Feb 16 17:39:01] DEBUG Checker host list
[Feb 16 17:39:01] INFO host-check-mgr: Loading uptime tests...
[Feb 16 17:39:01] DEBUG host-check-mgr: --- Setting tracking list up
[Feb 16 17:39:01] DEBUG Checker host Done
[Feb 16 17:39:01] INFO main: Initialised API Definitions
[Feb 16 17:39:01] INFO main: API reload complete
[Feb 16 17:39:01] DEBUG main: Downloading API Configurations from Dashboard Service
[Feb 16 17:39:01] INFO main: Detected 0 APIs
[Feb 16 17:39:01] INFO main: Loading API configurations.
[Feb 16 17:39:01] DEBUG Storage Engine already initialised...
[Feb 16 17:39:01] DEBUG Received DRL data: {datafront-1 <redacted> 4 0 }
[Feb 16 17:39:01] DEBUG Active Nodes: : 6 [Token Bucket Value]: 600 [Current Load p/s]: 1 [Current Load]: 0.000000
[Feb 16 17:39:02] DEBUG Calling: http://<redacted>:5000/register/ping
[Feb 16 17:39:02] DEBUG Sending Heartbeat as: <redacted>
[Feb 16 17:39:02] DEBUG Sending notification{NoticeGatewayDRLNotification {"HostName":"<redacted>","ID":"<redacted>","LoadPerSec":1,"Percentage":0,"TagHash":""} }
[Feb 16 17:39:02] DEBUG Received DRL data: {datafront-2 <redacted> 1 0 }
[Feb 16 17:39:02] DEBUG Active Nodes: : 6 [Token Bucket Value]: 600 [Current Load p/s]: 1 [Current Load]: 0.000000
[Feb 16 17:39:02] DEBUG Hearbeat Finished: Nonce Set: <redacted>
[Feb 16 17:39:02] DEBUG Checker host list
[Feb 16 17:39:02] INFO host-check-mgr: Loading uptime tests...
[Feb 16 17:39:02] DEBUG host-check-mgr: --- Setting tracking list up
[Feb 16 17:39:02] DEBUG Checker host Done
[Feb 16 17:39:02] INFO main: Initialised API Definitions
[Feb 16 17:39:02] INFO main: Loading policies
[Feb 16 17:39:02] INFO main: Using Policies from Dashboard Service
[Feb 16 17:39:02] INFO policy: Mutex lock acquired... calling
[Feb 16 17:39:02] INFO policy: Calling dashboard service for policy list
[Feb 16 17:39:02] DEBUG Loading Policies Finished: Nonce Set: <redacted>
[Feb 16 17:39:02] INFO policy: Processing policy list
[Feb 16 17:39:02] INFO main: Gateway started (v2.3.2)
panic: http: multiple registrations for /

goroutine 1 [running]:
panic(0xc7e200, 0xc4204fb670)
 /usr/local/go/src/runtime/panic.go:500 +0x1a1
net/http.(*ServeMux).Handle(0xc4202f4120, 0xdb4276, 0x1, 0x12a7de0, 0xc420428fa0)
 /usr/local/go/src/net/http/server.go:2038 +0x5d5
net/http.Handle(0xdb4276, 0x1, 0x12a7de0, 0xc420428fa0)
 /usr/local/go/src/net/http/server.go:2076 +0x55
main.listen(0x12b3020, 0xc4200202a0, 0x12a75e0, 0xc42005c020)
 /src/github.com/TykTechnologies/tyk/main.go:1378 +0xa6c
main.main()
 /src/github.com/TykTechnologies/tyk/main.go:1105 +0x182
```
**What is the expected behavior?**
It should not exit. If possible it should print error, but not terminate the process.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here is the link to the line that cause panic: https://github.com/TykTechnologies/tyk/blob/051374b44f245eab154330f730abe62048247836/main.go#L1378

We do not know yet how to replicate it, but it looks like the issue may happen if "listen" was called multiple times. It is possible if SIGUSR2 was used (can be used by some process managers).

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.2

Worth noticing that one of the possible ways to overcome the issue is adding following lines to config file, which will cause it to use a bit different router logic:
```
    "http_server_options": {
        "override_defaults": true
     }
```

**Comment by buger** [comment]
@matiasinsaurralde it can be related to you changes #377 #412

**Comment by buger** [comment]
More context, the issue can happen if you start the new process right after killing the last one with -9. Maybe it does not free up the socket in time, or something similar.

**Comment by mvdan** [comment]
@buger I don't see how that could be the cause. This is about multiple route handle registrations for "/" on the main router. Whether or not the port/socket is available would make `Listen` fail, which is a different thing.

**Comment by mvdan** [comment]
2.3.3 is already out, so moving to 2.3.4.

**Comment by mvdan** [comment]
@matiasinsaurralde did you have the chance to look into this? waiting on your opinion since you were the last to modify the router setup code.

**Comment by matiasinsaurralde** [comment]
@mvdan Haven't been able to reproduce this, @buger told me he has some tests that indicate issues with the router, they might be helpful for me.

**Comment by lonelycode** [comment]
This can happen when the process forks I think.

**Comment by buger** [comment]
So, here are tests https://github.com/TykTechnologies/tyk/pull/596. I did not found a way to cause this issue to happen, but I replaced "http.Handle" with "http.Serve", which should eliminate such issues, even if function called multiple times.

We have mix of various routers, depending if there is custom domain or separate control API. When `http.Handle` used, it always binds to default Go lang router, which can lead to unexpected behavior.

**Comment by buger** [comment]
This issue require too many commits to be cherry picked, and most of them depend on master code. Considering that this issue happened only for one user, and did not happened any more in recent time, moving it to 2.4 release.

**Comment by mvdan** [comment]
@buger sounds like a good choice. If this panic is reported more, we can always reassess for 2.3.5 and do a separate fix for the 2.3 branch if necessary.

**Comment by bbl232** [comment]
Also seeing this panic in 2.3.4 on container start. The strange thing is that I'm running the same docker image in two places with the same config and one is fine while the other one is seeing this error.

**Comment by buger** [comment]
This issue was fixed quite a long time ago. Note that 2.3 is extremely old. The current release is 2.7.4. 

Cheers.

**Comment by bbl232** [comment]
For what it's worth: restarting the dashboard put things in a good state again... somehow.
