### ISSUE TITLE
[TT-9986] certificate details

### ISSUE THREAD

**Issue by junqigu** [TykTechnologies/tyk#5338]
if want to get the certificate details what value should i set
![微信截图_20230720172958](https://github.com/TykTechnologies/tyk/assets/68135242/b181476c-7e36-4a01-95a5-cec292ddfbf9)

**Comment by andyo-tyk** [comment]
Hi @junqigu,

Thanks for your question.

I'm sorry the docs aren't as clear as they could be - and have raised a ticket to get this improved.

To help unblock you, have you seen this page?
https://tyk.io/docs/basic-config-and-security/security/mutual-tls/concepts/#certificate-management

In terms of the use of the `mode` parameter, looking in the code [here](https://github.com/TykTechnologies/tyk/blob/master/gateway/cert.go#L534), we can see that setting `mode` to `detailed` will return detailed information on the certificates (though not the certificates themselves, for security reasons). If you set `mode` to any other value, or do not provide a value, then the API will return just a list of certificate Ids.

I hope this helps.

Thank you for supporting Tyk!

**Comment by junqigu** [comment]
thanks for your reply！

**Comment by junqigu** [comment]
![image](https://github.com/TykTechnologies/tyk/assets/68135242/cf129254-fead-40fe-8276-8eb06e8c7b6e)
i have tested to set the _mode_ to _detailed_,but still only can get the certificate Id
then i checked the source code which you shared 
![image](https://github.com/TykTechnologies/tyk/assets/68135242/fecfea46-08ba-4e9a-9f71-5d09c016e3e0)
and saw the certID is empty,but still only can get the certificate Id
![image](https://github.com/TykTechnologies/tyk/assets/68135242/4d88a473-a3c4-4bdc-b251-350fe2372add)
Did I do something wrong?

**Comment by junqigu** [comment]
![image](https://github.com/TykTechnologies/tyk/assets/68135242/e2dd3657-73fe-4b5d-90e4-6ba71ccdba53)
i noticed 4.012 branch have this mode verification,but release-4.0.12 branch is not have 
![image](https://github.com/TykTechnologies/tyk/assets/68135242/0858e4a5-f60c-4d71-ad45-5cf0cbc2f5d3)
![image](https://github.com/TykTechnologies/tyk/assets/68135242/e4a112fe-072c-4fe2-8c5c-d78bc9e48c5c)
if i pull image from docker hub,which branch is this image using

**Comment by Ch1Yua** [comment]
i have the same question,wait for a big guy

**Comment by alephnull** [comment]
The git tag v4.0.12 is what you will get from dockerhub. Please tag me if you think that this tag is on the wrong commit.

**Comment by junqigu** [comment]
never mind,just want to confirm which code is docker image using

**Comment by andyo-tyk** [comment]
Hmm... that's not what I expected, I'm sorry for the inconvenience.

I've reopened this issue and we will check it out.

**Comment by junqigu** [comment]
thanks!

**Comment by mhuaco** [comment]
Hi @junqigu To get certificate details please try the API below. No need to add parameters. I confirmed that it works in 5.0.0 and 4.0.8.

/tyk/certs/{certID}

![image](https://github.com/TykTechnologies/tyk/assets/20006884/2b1e91cc-9575-431c-a53f-6dc6445578f0)

**Comment by lghiur** [comment]
Thanks @mhuaco this is indeed the way to retrieve a certificate detail. @junqigu I hope you succeeded to get the details of the cert? I have opened an internal issue to improve/add documentation over certificates endpoints

**Comment by andyo-tyk** [comment]
Closing this as resolved. Please re-open if you still have a problem.

Thank you for supporting Tyk!
