### ISSUE TITLE
[TT-9790] How to parse custom JTW claims?

### ISSUE THREAD

**Issue by amcowkin** [TykTechnologies/tyk#5420]
I want to add new headers: 
x-application-id 
x-application-name 
x-organisation-id 
x-organisation-name

if I do like this **"$tyk_context.jwt_claims_client_metadata.organisation_name"** it does not work.

in the logs I see: **“x-organisation-name-”**

Question: how can I parse an array?

My jwt is:

```json
{
  "pol": "MyAPI",
  "client_metadata": {
    "application_id": "1",
    "application_name": "SuperApp",
    "organisation_id": "1",
    "organisation_name": "SuperOrg"
  },
  "iss": "http://example.com/",
  "scope": "view create",
  "gty": "client-credentials"
}
```

But I can get **pol**:  "$tyk_context.jwt_claims_pol"

the problem is in array

thank you

**Comment by andyo-tyk** [comment]
Hi @amcowkin,
Tyk doesn't currently support nested fields in the JWT.
You should be able to get the result you expect if you remove the nesting, for example:
```
{
  "pol": "MyAPI",
   "application_id": "1",
   "application_name": "SuperApp",
   "organisation_id": "1",
   "organisation_name": "SuperOrg"
  "iss": "http://example.com/",
  "scope": "view create",
  "gty": "client-credentials"
} 
```

Does this work for you?

**Comment by amcowkin** [comment]
Hi @andyo-tyk 
thank you
