### ISSUE TITLE
Support response transformation using CP middleware

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#543]
Do you want to request a feature or report a bug?
Feature/enhancement

What is the current behavior?
At the moment it's possible to override the HTTP response but in a limited way (it's inteded for error responses).

What is the expected behavior?
As a Tyk user I would like to proxy the request through Tyk, take the response and transform it using a CP middleware.

Related to [this community forum post](https://community.tyk.io/t/rich-plugins-transforming-responses/1435/5).

**Comment by jmleoni** [comment]
👍

**Comment by letzya** [comment]
Related to #543

**Comment by buger** [comment]
Closing in favor of https://github.com/TykTechnologies/tyk/issues/1526 and https://github.com/TykTechnologies/tyk/issues/2693
