### ISSUE TITLE
[TT-10180] README appears to be incorrect

### ISSUE THREAD

**Issue by sosheskaz** [TykTechnologies/tyk#5479]
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: N/A

**Describe the bug**
Documentation around supported Golang version is unclear.

**Reproduction steps**

View README.md.
View go.mod

**Actual behavior**
Readme claims that Tyk is compiled with 1.12, and that only up to Go 1.15 is tested.

It appears that Tyk is compiled with Golang 1.19, so this appears inaccurate.

**Expected behavior**
I expect the readme to reflect the current Go version.

**Screenshots/Video**
N/A

**Logs (debug mode or log file):**
N/A

**Configuration (tyk config file):**
N/A

**Additional context**
N/A

**Comment by andyo-tyk** [comment]
Hi @sosheskaz ,
Well spotted, I'm sorry for the confusion - we'll get that corrected.

**Comment by andyo-tyk** [comment]
Hi @sosheskaz,

Thank you again for raising this issue - we've now updated the readme to show the correct Go version.
Sorry for any inconvenience.

Thanks for supporting Tyk@
