### ISSUE TITLE
Operating Requirements?

### ISSUE THREAD

**Issue by mattfarina** [TykTechnologies/tyk#551]
Can you share the operating requirements for Tyk? I see python for middleware. If this is a Go binary is a python container image base all that's needed? What version of python?

Is there anything else that's required?

**Comment by matiasinsaurralde** [comment]
Hi @mattfarina, the Python version is specified [in the docs](https://tyk.io/tyk-documentation/customise-tyk/plugins/rich-plugins/python/requirements/).
Also there's an alternative init script for the Python build, so you should use `tyk-gateway-python` instead of `tyk-gateway` (like `service tyk-gateway-python start`).
The binary is linked to Python 3.4, we may have to switch to the PY_LIMITED to support higher versions in case issues come up.
Best.

**Comment by mattfarina** [comment]
@matiasinsaurralde Thanks.

The docs appear to assume an environment like ubuntu. And, if I look at the tyk gateway docker image it notes ubuntu. That seems heavy for a docker image. Is ubuntu needed or just python 3.4?

Aside from python 3.4 are there other requirements?

**Comment by matiasinsaurralde** [comment]
Ubuntu is recommended as we did a lot of tests with it.
You may build the Protocol Buffers library, it will enhance the performance. The Python module uses a pure-Python version by default.

**Comment by mvdan** [comment]
@mattfarina to clarify, we support Linux, not just Ubuntu - so any distro that doesn't ship an ancient kernel (see the minimum that Go itself requires) should also do.

**Comment by mattfarina** [comment]
@mvdan I'm more looking at running this in a container and trying to figure out the minimum requirements for a container image. If I can avoid passing around large images I would like to do so.

**Comment by mvdan** [comment]
@mattfarina see https://github.com/TykTechnologies/tyk-gateway-docker/issues/7.

On top of that, using an image like Debian would probably reduce size a bit.

**Comment by james-tyk** [comment]
@mattfarina
Python is only needed if you are rolling your own python middleware plugin
For some more info on available tyk packages : https://tyk.io/get-tyk-on-premise/

**Comment by mvdan** [comment]
@mattfarina I'm going to close this now, but feel free to reopen or reach out to us if you have any more questions.
