### ISSUE TITLE
What is the default value TYK_GW_HASHKEYFUNCTION

### ISSUE THREAD

**Issue by jakub-bochenski** [TykTechnologies/tyk#5559]
```
hash_key_function

EV: TYK_GW_HASHKEYFUNCTION
Type: string

Specify the Key hashing algorithm. Possible values: murmur64, murmur128, sha256.
```
The documentation doesn't tell what the default value will be if it's not specified (unlike e.g. basic_auth_hash_key_function)

**Comment by jakub-bochenski** [comment]
You promised to document default values back in May https://github.com/TykTechnologies/tyk-docs/issues/2530

**Comment by jakub-bochenski** [comment]
Seems to be `murmur32` based on those release notes https://github.com/TykTechnologies/tyk-docs/blob/af39a6183263dfe593d31450fafc3aebb4e7236c/tyk-docs/content/release-notes/version-2.7.md?plain=1#L38

Interesting that  `murmur32` is not even documented as a valid option

**Comment by andyo-tyk** [comment]
Hi @jakub-bochenski,

Tyk implements MurmurHash 3 and offers three different output sizes to allow tuning of the hash size and collision probability.

You can select the option you require using the `TYK_GW_HASHKEYFUNCTION` variable:
`murmur32` - 32-bit output
`murmur64` - 64-bit output
`murmur128` - 128-bit output

You can alternatively choose the crytographic `sha256` hashing algorithm.

The default value used by Tyk, if hashing is enabled but no algorithm selected via `TYK_GW_HASHKEYFUNCTION` is `murmur64`.

I'm sorry for the delay getting back to you on this.

Thank you for supporting Tyk!
