### ISSUE TITLE
Support ULID normalizer

### ISSUE THREAD

**Issue by atkrad** [TykTechnologies/tyk#5563]
**Is your feature request related to a problem? Please describe.**
Currently, Tyk provides two predefined URL normalizers: `UUID` and `Number`. In our company, we use UUID, Number (digit), and [`ULID`](https://github.com/ulid/spec) as unique identifiers. To normalize URLs for UUIDs, we simply need to enable "normalise_uuids." However, we encounter an issue with Numbers because enabling "normalise_numbers" conflicts with ULID.

[ULID](https://github.com/ulid/spec) identifiers always start with a digit, causing conflicts with the number normalizer. To address this, we attempted to create a custom pattern under "analytics_config" specifically for ULID. We also turned off "normalise_numbers". Unfortunately, we faced difficulties in crafting a suitable pattern for matching numbers. The problem lies in the fact that we can't specify the replacement part in custom patterns.

To resolve this issue effectively, we would greatly benefit from Tyk supporting ULID as a recognized UID type. This would allow us to enable all predefined normalizers without needing to create a custom pattern.

**Describe the solution you'd like**
Supporting ULID as a predefined URL normalizers

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by p-afraz** [comment]
This feature is much needed since we use ULIDs as unique IDs. It also removes the need to add custom regex (which is limited for now in Golang by its look behind limitations.
https://pkg.go.dev/github.com/s-kozlov/goback/regexp/syntax#hdr-Lookbehind_limitations

**Comment by andyo-tyk** [comment]
Hi @atkrad @p-afraz,

I'm pleased to confirm that this feature will be added in Tyk 5.2.2.

Thank you for supporting Tyk!
