### ISSUE TITLE
Supporting "else" condition in Tyk "url_rewrites.triggers"

### ISSUE THREAD

**Issue by mortymacs** [TykTechnologies/tyk#5567]
**Is your feature request related to a problem? Please describe.**
In our system, we deal with two types of requests: one that relies on Tyk tokens, and the other that operates through OIDC. Our routing decisions are based on the headers of these requests. However, we encounter an issue when users send requests with headers that haven't been explicitly defined in our url_rewrites configuration. In such cases, Tyk throws back a 500 error.
I've gone through your documentation thoroughly, but unfortunately, I couldn't find a way to set up a "fallback" or "else" condition within the url_rewrites attribute.

Tyk config:

```
    -> tyk://apikey
api                 -> tyk://internal -> http://service-endpoint
    -> tyk://oidc
```

```json
"url_rewrites": [ 
  {
    "match_pattern": "/actions/(.*)",
    "method": "GET",
    "path": "/",
    "triggers": [
      {
        "options": {
          "header_matches": {
            "API-Key": {
              "match_rx": ".*"
            }
          }
        },
        "rewrite_to": "tyk://apikey/$1",
        "true": "all"
      },
      {
        "options": {
          "header_matches": {
            "Authorization": {
              "match_rx": ".*"
            }
          }
        },
        "rewrite_to": "tyk://oidc/$1",
        "true": "all"
      }
    ]
  },
] 
```

Request and response:
```bash
$ http http://localhost:8080/actions/ 'Hello:123' 
```
```json
{
    "detail": "There was a problem proxying the request",
    "status": 500,
    "title": "Gateway Error",
    "type": "about:blank"
}
```

Tyk logs:
```
level=debug msg="Started proxy"
level=debug msg="Stripping proxy listen path: /actions/"
level=debug msg="Upstream path is: /" mw=ReverseProxy
level=debug msg=Started api_id=api mw=ReverseProxy
level=debug msg="Upstream request URL: /" api_id=api mw=ReverseProxy
level=debug msg="Outbound request URL: " api_id=api mw=ReverseProxy
level=debug msg="Creating new transport" api_id=api mw=ReverseProxy
level=debug msg="Out request url: " api_id=api mw=ReverseProxy
level=error msg="http: proxy error: unsupported protocol scheme \"\"" mw=ReverseProxy
level=debug msg=Finished api_id=api mw=ReverseProxy
level=debug msg="Upstream request took (ms): 0.406609"
level=debug msg="Done proxy"
```

**Describe the solution you'd like**
It would be really helpful if we could incorporate some kind of "else" conditions.

Something like:
```json
"triggers": [
      {
        "options": {
          "header_matches": {
            "API-Key": {
              "match_rx": ".*"
            }
          }
        },
        "rewrite_to": "tyk://apikey/$1",
        "true": "all"
      },
      {
        "options": {
          "header_matches": {
            "Authorization": {
              "match_rx": ".*"
            }
          }
        },
        "rewrite_to": "tyk://oidc/$1",
        "true": "all"
      },
      {
        "rewrite_to": "tyk://error/$1",
        "true": "not-matched"             <<<<<<<<
      },
    ]
```

**Describe alternatives you've considered**
I've tried some different ways, but unfortunately, none of them worked.

**Additional context**
I'm not sure, but maybe this issue can be "related": https://github.com/TykTechnologies/tyk/issues/2623

**Comment by OldStubbsy** [comment]
Hi @mortymacs 

If none of the URL rewrites apply then the gateway will proxy to the endpoint defined in `proxy.target_url`.  From the error you're getting I think that's blank.

Could you check and confirm it works please?

**Comment by p-afraz** [comment]
> Hi @mortymacs
> 
> If none of the URL rewrites apply then the gateway will proxy to the endpoint defined in `proxy.target_url`. From the error you're getting I think that's blank.
> 
> Could you check and confirm it works please?

This suggestion worked for me and solved the issue. Thanks @OldStubbsy!

Created an internal mock API
```
{
    "name": "No Auth",
    "api_id": "internal-no-auth",
    "internal": true,
    "version_data": {
        "not_versioned": true,
        "versions": {
            "v1": {
                "name": "v1"
            }
        }
    },
    "proxy": {
        "listen_path": "/"
    }
}
```

Then used it as `proxy.target_url` in other APIs
```
{
    "proxy": {
         "target_url": "tyk://internal-no-auth"
    }
}
```

Since the API can not be used without auth, gateway is automatically generating 401 response.

**Comment by mortymacs** [comment]
Awesome!
Thank you, @OldStubbsy and @p-afraz!
