### ISSUE TITLE
Stale Twitter Icon on Website

### ISSUE THREAD

**Issue by Ayush9026** [TykTechnologies/tyk#5836]
**Is your feature request related to a problem? Please describe.**
The Twitter icon on the website appears to be stale or outdated. This issue is created to address and resolve the issue.

**Describe the solution you'd like**
1. Navigate to the website: https://tyk.io/.
2. Locate the Twitter icon [Specify the location, e.g., in the footer].
3. Observe that the icon is not displaying the current or correct information.

**Describe alternatives you've considered**
The Twitter icon should display the correct and up-to-date information. As marked in screenshot twitter is now 'X' Corp.

![Tyk Website](https://github.com/TykTechnologies/tyk/assets/114745463/0af4c174-ae2a-4eb8-9659-60b009b9ca10)

**Additional context**
- Website URL: https://tyk.io/
- Browser: Google Chrome

**Comment by andyo-tyk** [comment]
Hi @Ayush9026,

Thanks for spotting this and raising it to my attention - I've passed this on to the website team and we will get this corrected.

Thanks again for your help.

**Comment by Ayush9026** [comment]
Thanks @andyo-tyk You're very welcome! I'm glad I could help identify the issue. As an open-source contributor, I'm always here to assist with any further improvements or contribute to resolving similar issues. If there's anything specific you'd like me to do or if you need more information, please don't hesitate to reach out.
