### ISSUE TITLE
Feature Request: Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by Ayush9026** [TykTechnologies/tyk#5854]
**Is your feature request related to a problem? Please describe.**
As a user of the website, I would like the ability to toggle between dark and light modes for a more personalized and comfortable browsing experience.

**Describe the solution you'd like**
Introduce a toggle button on the website interface that allows users to switch between dark and light modes seamlessly.

**Describe alternatives you've considered**
 Expected Behavior
- Users can toggle between dark and light modes.
- The selected mode should persist across page reloads.
- Ensure a smooth transition between modes.

**Additional context**
As marked in screenshot below.

![Tyk Website](https://github.com/TykTechnologies/tyk/assets/114745463/19402b11-a8f0-4242-80cb-469c8b986afd)

**Comment by andyo-tyk** [comment]
Hi @Ayush9026,
I've passed this suggestion onto our website team who will consider it in their development of the site.
I've also suggested to them that they add a facility on the site for visitors to provide feedback, so that it goes directly to the right team.
Thank you again for your support and vsaluable suggestions.

**Comment by Ayush9026** [comment]
Thanks @andyo-tyk sir i am open-source contributor at Kubernetes and other CNCF projects also DevOps/SRE enthusiast is your organization is hiring.

**Comment by andyo-tyk** [comment]
Hi @Ayush9026,
Tyk's current vacancies can be found on the website, here: https://tyk.io/current-vacancies/
Thanks for your interest in and support for Tyk. :)
