### ISSUE TITLE
TestHotReloadSingle is still flaky

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#588]
We're still getting the "reload wasn't queued" flake. I thought I had fixed it in https://github.com/TykTechnologies/tyk/pull/581, but apparently I didn't fix it completely.

**Comment by buger** [comment]
How easy is to replicate it? Does it possible to bisect the commit which introduced the bug?

**Comment by mvdan** [comment]
@buger it's very likely when I added the ticker to control it from the tests. The fix I pushed was another test being unreliable and firing a reload when it shouldn't, which meant we were one tick behind.

This is likely another issue like that.

Do we want to use the bug label for test bugs, not actual production code bugs?

**Comment by mvdan** [comment]
Unless what you mean is "let's use the bug label in case this is an actual production code bug".

**Comment by buger** [comment]
Well, it is a bug in the test, so for simplicity reasons lets act accordingly.
