### ISSUE TITLE
Portal domain routing - self hosted Tyk Gateway & Dashboard

### ISSUE THREAD

**Issue by jaykola** [TykTechnologies/tyk#589]
Hi,

I have set up self hosted instances of tyk-gateway and dashboard (connected via pump). So far everything about tyk has been brilliant and it fits with very well with our own platform offering. 

I have configured the gateway to detect APIs registered via the dashboard. I am able to get the dashboard up and running - no issues creating organisations, APIs, setting limits, etc.

However, no matter what I try, the portal always seems to detect the internal IP of the host and not the public IP. I have then tried to configure the 'portal' via the dashboard frontend and also the backend (as suggested in https://github.com/TykTechnologies/tyk/issues/225). I suspect there is some clever internal routing that is making tyk pick up the internal host. I saw a reference to the 'host manager' doing some additional bits to get the docker instances to work. Is the behaviour I am seeing a result of that host manager (now merged into dashboard?) trying to be a bit too clever or something I did to mess up my configuration?

I am happy to give you access to our throw away instance of tyk dashboard if you would like to have a look at the issue. 

I am using the rpm based version of the following components and versions:
- tyk-dashboard.x86_64    --->         1.3.1.2-1                  
- tyk-gateway.x86_64   --->           2.3.3-1               
- tyk-pump.x86_64       ---->          0.4.1.1-1               

Happy to provide other config files that will help with this issue. Our instances are all provisioned via Ansible, so once we get this issue sorted, I'd be happy to contribute those Ansible scripts to the tyk community.

Best Regards,
Jay

**Comment by lonelycode** [comment]
Can you raise thi in our community forum? It would be the appropriate place for this as this is not a bug, but most likely a configuration issue.
