### ISSUE TITLE
Listing Users for an Organization as an Admin

### ISSUE THREAD

**Issue by DavidTPate** [TykTechnologies/tyk#60]
I've been going through working on orchestrating my configuration of Tyk and I'm trying to get a list of users for an organization prior to having an access key.

What I'm doing is very similar to the setup script [here](https://gist.github.com/lonelycode/4f645c4733faaa74d8fd). I'm going through and checking if an organization already exists, if not I'm creating it. Then I need to see if a user already exists and if not create them. The problem I have is that there doesn't seem to be an endpoint outside of the users API to list users, while there is one to create them.

For what I'm doing I'm expecting to have the following flow: `GET /admin/organisations` (`POST /admin/organisations` if the organisation doesn't exist) `GET /admin/users` (`POST /admin/users` if the user doesn't exist).

I tried simply doing a POST to /admin/users to see if it updated the user if they already exist, but that's not the case. The reason why I can't do a `GET /api/users` is because I don't have an API key yet to be able to make that call. I just want to make sure that I avoid creating a ton of users that are unnecessary and the same thing (this script will be run tons of times).

**Comment by lonelycode** [comment]
Hi david,

Yes the high-level admin API is a little limited, it has only very few methods, we'll expand this in future.

In the meantime you can probably get around this by creating a single super-user using the /admin/users command, simply don't assign an Org ID and the user will have a "global" view

You can use this users key to maniulate the users the way you wish.

Let me know if that works, I'll keep this ticket open in the meantime.

**Comment by DavidTPate** [comment]
Gotcha, wasn't aware that a super-user can be created. I'll do that for now, thanks!

**Comment by DavidTPate** [comment]
Looks like I still can't list users for a specific organization with the super-user since the API lists users based upon the organization of the user making the request to the API. That's fine for now, I'll just not worry about creating duplicate users at the moment. 

I'd definitely love to see either the ability for a super-user to list users of an organization or the ability to list users from the admin api. I wasn't able to track down where the functionality is located otherwise I'd open a PR for it.

**Comment by DavidTPate** [comment]
My previous comment about the super-user not being able to see the users of the other organizations is definitely incorrect. After doing some more testing I was able to do it, just not sure what path led me down having the issue before. Will update if I find something else.

**Comment by kohrVid** [comment]
Hi @DavidTPate, 

I've noticed that this issue has been open since 2015. Would it be all right if we closed this or would you still like to see this feature implemented in a future release?

Kind regards,
Jess

**Comment by DavidTPate** [comment]
@kohrVid I think it is still a worthwhile feature, but as mentioned above by @lonelycode there is a workaround for it.
