### ISSUE TITLE
Token recycling

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#605]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
A token can be recycled by following a multi-step process.

**What is the expected behavior?**
A token can be recycled in a single step.

Dev could recycle token via portal.
Admin could recycle tokens via dashboard.

(Needs further discussion and refinement.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
n/a

**Comment by mvdan** [comment]
@davegarvey does this affect just the dashboard, or both dashboard and gateway? (would assume the latter, but just to be sure)

**Comment by davegarvey** [comment]
The functionality should be driven by the Gateway API, since Gateways issue tokens it seems sensible to have them also recycle them. The functionality would be good to provide via the Dashboard client too.

**Comment by ConsM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement token recycling functionality](https://trello.com/c/33thniYt/449-implement-token-recycling-functionality)
