### ISSUE TITLE
Gateway returns 404 error for all api requests

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#606]
ENV: local docker dev-env
Branch: Current gateway master, current dashboard master
Version: On-premise 

Reproduction steps:
1. Log on dashboard
2. Go to API's
3. Create "test-api" api definiton 
4. Set keyless for Authentication mode
5. Save
6. Open api url(in my case http://localhost:8181/test-api/)

Actual:
Gateway returns 404 error for all requests

Expected:
Gateway should proxy request to https://httpbin.org/

Note:
This is visible only on latest gateway master, on release 2.3.3 this issue is not visible, also only on-prem version is affected. Community version is ok

**Comment by buger** [comment]
That sounds bad. Can you try manually trigger reload via /tyk/reload and /tyk/reload/group on Gateway side?

**Comment by mvdan** [comment]
Something to note is that this is only reproducible with api definitions received from a dashboard (on-prem), not from files (community). This is likely why we didn't catch this with our current unit tests.

**Comment by lonelycode** [comment]
As an aside to this issue - if the options in the config.go file for HTTP Server options:

```
type HttpServerOptionsConfig struct {
	OverrideDefaults bool       `json:"override_defaults"`
	ReadTimeout      int        `json:"read_timeout"`
	WriteTimeout     int        `json:"write_timeout"`
	UseSSL           bool       `json:"use_ssl"`
	UseLE_SSL        bool       `json:"use_ssl_le"`
	EnableWebSockets bool       `json:"enable_websockets"`
	Certificates     []CertData `json:"certificates"`
	ServerName       string     `json:"server_name"`
	MinVersion       uint16     `json:"min_version"`
	FlushInterval    int        `json:"flush_interval"`
	SkipURLCleaning  bool       `json:"skip_url_cleaning"`
}
```

Are active, it can affect reload behaviour, so can we make sure that when `ReadTimeout` etc. are set that the reloads are still good (including `SIGUSR2` reloads from the command line).

**Comment by buger** [comment]
@lonelycode this tests already included into my PR's. It use test matrix and test all combinations of OverrideDefaults, with or with GoAgain and with control API on separate and on same port.

**Comment by lonelycode** [comment]
:+1:

**Comment by ilijabojanovic** [comment]
@buger Issue is visible again on current master branch

**Comment by mvdan** [comment]
@buger's PR had tests, so perhaps they failed to cover certain scenarios?

@ilijabojanovic is the issue the exact same as before?

**Comment by buger** [comment]
Yeah, and master have only 2 commits after this PR was merged.

**Comment by ilijabojanovic** [comment]
@buger @mvdan i just tested latest master. So issue is still visible. Seems is related to hot reload. Since when i create api definition over dashboard and try to get that api i have 404, but when i manually trigger gateway hot-reload api working fine

**Comment by buger** [comment]
@ilijabojanovic added fix #631

**Comment by BlackTurtle123** [comment]
I still have a 404/Not found on all api calls.
What should I do?

**Comment by a-wakeel** [comment]
@buger i still have the same issue, does that mean i have some problem in configurations or the bug is still here?

**Comment by joshblakeley** [comment]
This has not been a problem in our testing. What Tyk version are you running?

**Comment by BlackTurtle123** [comment]
latest version.
Clean install.
On the forum my ticket is open for over 2 week or something.

**Comment by a-wakeel** [comment]
@joshblakeley i had that issue in containerized version but with manual on ubuntu, this issue has been resolved.

**Comment by ossvn** [comment]
I have this problem too, after adding the API in the dashboard (with custom domain).

Then I try with postman, it returned 404.

**Comment by buger** [comment]
@ossvn and you can confirm that you calling it with the right domain? Also ensure that you have `enable_custom_domains` set to true. Is this the only API you have? 

Also, can you confirm that Tyk Admin API still works?

**Comment by ossvn** [comment]
Hello @buger 

Yup, I'm sure I'm calling with with right domain (I pointed my domain in cloudflare to the VPS's IP).

I also tried the request with different types, none of them are going to work:

- IP:3000/endpoint
- IP:8080/endpoint
- domain:3000/endpoint
- domain:8080/endpoint

Also, after setting the CNAM for the portal, I followed the instruction to set up the portal in admin, but when I go to the domain:3000/portal, 404 error shows.

not sure what's happening!

**Comment by buger** [comment]
Note that dashboard itself does not expose your APIs itself, the only gateway does. 

Does it mean that API without domain works as expected?

Do you see anything in gateway logs, can you post log output here (especially part when gateway starts, and you make first request).

Thank you.

**Comment by ossvn** [comment]
I will test tomorrow and report for you.

For the question, API without the domain, still not work as well. That's weird.

I will keep you updated!
