### ISSUE TITLE
Make it possible to exclude a node from the DRL

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#613]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a node is reserved as a management node, then it can affect the way the rate limiter calculates bucket sizes making rate limits lower than they are set at.

**What is the expected behavior?**
The rate limits in a set of gateways with a mangement node (reserved, non-active node), should maintain the rate limit appropriately.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Set up three nodes, two behind a load balancer, then send traffic to the LB against a rate limited token, the rate limit will be lower than what is set.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
v2.3.x

**Comment by buger** [comment]
Is the there is a way to know if it is a management node? Or it require adding a new flag?

**Comment by lonelycode** [comment]
It will require a flag to saybitnis one

**Comment by lonelycode** [comment]
Actually, the flag should just stop it from broadcasting its details on the pub sub channel. It should be very straightforward.

**Comment by buger** [comment]
@lonelycode should we also exclude it from the quota calculations?

**Comment by buger** [comment]
Also, it does not look like a proper fix. Maybe it makes sense to add an option which disables any rate limiting and quotas for the whole gateway?

**Comment by lonelycode** [comment]
So quotas are not broadcast and do not affect the server table that gets built up by the nodes. Only the DRL does that.

So the fix is: 

- Add a flag ManagementNode:true
- if set the DRL does not activate at all

This stops the broadcast, the other rate limiters do not make use of broadcast so that's ok and the quota system uses a direct redis counter so this should not need modifying.

A user could just disable the rate limiter by enabling one of the others, but that isn't intuitive.

**Comment by buger** [comment]
We should not forget to update documentation
