### ISSUE TITLE
Malformed webhook payload if template value is missing

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#616]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Example template: 
```
{
    "event": "{{.EventType}}",
    "key": "{{.EventMetaData.Key}}",
    "api_id": "{{.EventMetaData.HostInfo.MetaData.api_id}}"
}
```

If one of the values, in this case `{{.EventMetaData.HostInfo.MetaData.api_id}}` is missing, example JSON response will be truncated to:
```
{
    "event": "{{.EventType}}",
    "key": "{{.EventMetaData.Key}}",
    "api_id": 
```

**What is the expected behavior?**
It should properly handle missing values

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just create a template with a not existing key. Example template above should work.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

**Comment by buger** [comment]
Worth noticing that I did not reproduce issue by myself, @ilijabojanovic pls verify when you have time.

**Comment by buger** [comment]
I verified the issue, and indeed things look bad. All versions of tyk affected.

We have tests covering webhooks, BUT, they do not check for full body, only for some specific strings. For example `TestCreateBody` test, generate `{ "event": "QuotaExceeded", "message": "` payload and pass because it checks for `QuotaExceeded` string 🙈 . 

Error itself says: `executing "default_webhook.json" at <.Meta.Message>: can't evaluate field Message in type interface {}`. It happens when you try to access element from Template which not exist, and path is nested. 

To fix `TestCreateBody` test, it was enough to add `Meta: EventAuthFailureMeta{},` to the template data. We should check all the places where we generate webhooks, and add empty objects, for values which can exist or be missing for the same template (if events share same template, like our `default_webhook.json` suggests.

**Comment by lonelycode** [comment]
Btw it's possible to set different templates per event,  so a user can modify these templates as a workaround.
