### ISSUE TITLE
how can i use tyk without redis

### ISSUE THREAD

**Issue by chenjh880730** [TykTechnologies/tyk#626]
i do not want import any external dependency。how can i use tyk without redis?

**Comment by lonelycode** [comment]
That is not possible, Tyk requires redia

**Comment by chenjh880730** [comment]
can i change redis to any other k/v storage ？like zookeeper ？ consul ?

**Comment by matiasinsaurralde** [comment]
@chenjh880730 Not possible at the moment. We do have long term plans for alternative storage support.
