### ISSUE TITLE
Remove and replace redundant fields in TykJSHttpRequest struct

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#627]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behaviour?**
The `TykJSHttpRequest` struct in `/plugins.go` has both a `Domain` and a `Resources` attribute when only one `URL` property is needed. The `Resources` path is actually used to overwrite the path that would have been generated by the `Domain` attribute which seems unnecessary.

**What is the expected behaviour?**
What I would propose is that these two attributes be replaced with a single `URL` attribute which can be used to derive both the domain and the path.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All previous versions are affected. As the JSVM middleware depends on this object to send HTTP requests, this is likely to be a breaking change.

**Comment by mvdan** [comment]
Keep in mind that if middlewares are covered by the 2.x backwards compatibility rule, removing existing fields should hold off until 3.0.

**Comment by mvdan** [comment]
When this is done, let's do https://github.com/TykTechnologies/tyk/issues/623 too and get rid of the headers map.
