### ISSUE TITLE
Profile Raw Editor cursor placement

### ISSUE THREAD

**Issue by antempus** [TykTechnologies/tyk#6273]
**Branch/Environment/Version**
- Branch/Version: 5.3.0
- Environment: Hybrid

**Describe the bug**
When editing a profile in the raw editor, the actual cursor more left than the visual cursor

**Reproduction steps**
1. Deploy Control Plane
2. Create Profile
3. Edit profile 

**Actual behavior**
Selecting a line and removing/adding characters results in characters to the left of the cursor to change

**Expected behavior**
Selecting a line and removing/adding characters results in characters on the cursor to change

**Screenshots/Video**
https://github.com/TykTechnologies/tyk/assets/5413399/26a4b02d-2e4e-4598-9dba-f2d01f8e336c

**Logs (debug mode or log file):**
N/A
**Configuration (tyk config file):**
N/A

**Comment by lghiur** [comment]
will close this for now, let me know if this still occurs after upgrading
