### ISSUE TITLE
Unable to generate API keys in the master branch

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#628]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When an API key is created in the Dashboard, the following error message appears in the Gateway logs:

    No API Register present!
The Dashboard displays this error:

    Failed to save new session object to Tyk: Failed to create key: Post http://tyk_gateway:8080/tyk/keys/create: EOF

**What is the expected behaviour?**
It should be possible to generate an API key successfully. At present this is only possible in the `stable` branch.
 
**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Build the Tyk environment from the master branch of the Gateway, the Pump and the Dashboard
2. In the Dashboard, create a new API with the default settings
3. Create a new policy with the new API added to the Access Rights
4. On the "Add Key" page, create a new key with the new policy selected from the Available Policies dropdown list.

At this point, the error message should appear in the Dashboard and in the Gateway logs.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Gateway v2.3.99 & Dashboard v1.3.1.2/1.3.2 (the version listed in the tyk-analytics repo seems inconsistent). The stable branch for each of these repos (v2.3.2/v1.3.1.1) is unaffected.

**Comment by mvdan** [comment]
Regression, marking as such.

**Comment by mvdan** [comment]
Also note that this might end up being a dashboard issue, as in an incorrect use of the gateway API. But it's likely just a gateway regression.

**Comment by buger** [comment]
I see following panic:
```
tyk-gateway_1    | 2017/03/17 17:24:18 http: panic serving 172.19.0.5:36612: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | goroutine 13832 [running]:
tyk-gateway_1    | net/http.(*conn).serve.func1(0xc4201def00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1491 +0x12a
tyk-gateway_1    | panic(0xc40a00, 0xc420014060)
tyk-gateway_1    | 	/usr/local/go/src/runtime/panic.go:458 +0x243
tyk-gateway_1    | main.(*DefaultSessionManager).ResetQuota(0xc420404850, 0xc42043ce40, 0x38, 0x0, 0x408f400000000000, 0x408f400000000000, 0x404e000000000000, 0x58cc3313, 0xffffffffffffffff, 0x58cc1bfe, ...)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/auth_manager.go:101 +0x452
tyk-gateway_1    | main.createKeyHandler(0x11ebd00, 0xc420472680, 0xc4200bd770)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/api.go:1210 +0x2999
tyk-gateway_1    | main.InstrumentationMW.func1(0x11ebd00, 0xc420472680, 0xc4200bd770)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/instrumentation_handlers.go:51 +0x97
tyk-gateway_1    | main.checkIsAPIOwner.func1(0x11ebd00, 0xc420472680, 0xc4200bd770)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/main.go:368 +0x1f7
tyk-gateway_1    | net/http.HandlerFunc.ServeHTTP(0xc420458c10, 0x11ebd00, 0xc420472680, 0xc4200bd770)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1726 +0x44
tyk-gateway_1    | github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203b46e0, 0x11ebd00, 0xc420472680, 0xc4200bd770)
tyk-gateway_1    | 	/develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
tyk-gateway_1    | net/http.(*ServeMux).ServeHTTP(0xc4201a03f0, 0x11ebd00, 0xc420472680, 0xc420668f00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2022 +0x7f
tyk-gateway_1    | net/http.serverHandler.ServeHTTP(0xc42041c680, 0x11ebd00, 0xc420472680, 0xc420668f00)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2202 +0x7d
tyk-gateway_1    | net/http.(*conn).serve(0xc4201def00, 0x11eccc0, 0xc4201ced80)
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:1579 +0x4b7
tyk-gateway_1    | created by net/http.(*Server).Serve
tyk-gateway_1    | 	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by mvdan** [comment]
Ah, I am probably to blame for this since I've been replacing non-nil slices and maps with nil ones in early returns. @buger mind if I take this over and look into it on Monday?

**Comment by buger** [comment]
Sure

**Comment by mvdan** [comment]
@buger how exactly are you reproducing the crash? With the dashboard UI, or with an http request on the gateway alone? I haven't been able to reproduce it with `curl`.

Also nothing seems obviously wrong in the code pointed to by the panic trace.

**Comment by buger** [comment]
I tried with the dashboard UI.

**Comment by matiasinsaurralde** [comment]
@mvdan @buger I tried to reproduce it on Friday and no luck!

**Comment by mvdan** [comment]
I followed @kohrVid's steps via the dashboard master on gateway master and wasn't able to reproduce the crash either.

@buger any more details? or perhaps you'd like to take this back from me, since you were able to reproduce it?

**Comment by mvdan** [comment]
To clarify, adding the key seems to work as per the logs:

```
INFO auth-mgr: Reset quota for key. inbound-key=****4efd key=quota-58c95339e1b83206f2ee68cb87ffee9e3ace464b678b34fc75574efd
INFO api: Generated new key: (****4efd) api_id=-- key=****4efd org_id=58c95339e1b83206f2ee68cb path=-- server_name=system status=ok user_id=system user_ip=::1
```

(local and throwaway, ignore the actual ids)

**Comment by kohrVid** [comment]
@mvdan and @matiasinsaurralde, are you guys using Docker to build the environment? If so, are you using quickstart or the develop-env repo?

**Comment by mvdan** [comment]
I'm running both binaries manually with mongo and redis. Both dashboard and gateway from empty configs.

**Comment by matiasinsaurralde** [comment]
I'm running the binaries manually!

**Comment by mvdan** [comment]
So it must be something in how the two are set up in the develop env then, likely some config setting. Assigning back to @buger since he's already hit gold.

**Comment by buger** [comment]
It is weird, but I can't replicate it anymore.

@kohrVid can you try one more time? Does it still happen for you? If so, pls specify exact SHA1 of the commits, and export/upload API, Policy and Key definitions.

Thank you!

**Comment by mvdan** [comment]
Maybe it's some sort of broken gateway state, or a bug that appears somewhat randomly when starting up the gateway.

**Comment by kohrVid** [comment]
Still getting this error tyk-develop-env

tyk-develop-env: 45ef212eac6bb2056ee62ab145a7c878798e18ea
tyk: 9f8424e93d3776d73c5032540c60ff33afd39343
tyk-pump: 798ff33ee62a8f6f425da47d82ce70410a3d6aa7
tyk-analytics: d71d335f2555b6d66ea544b841b37a8d9ccd5f24

**Comment by kohrVid** [comment]
Just an update, I'm now unable to replicate this issue in the `master` branch and I think the issue was probably caused by a missing/incorrect $GOPATH (I think something happened to mine when I upgraded to 1.8).
As no-one else seems to be able to replicate this, it's probably best to close this issue.

**Comment by mvdan** [comment]
Thanks for the update, @kohrVid. @buger was once able to reproduce the same crash though, which is a bit weird. If either of you encounter it again, please reopen this issue.
