### ISSUE TITLE
Gateway unnecessarily sleeps on exit

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#630]
When you ^C the gateway (SIGINT) it waits for a number of seconds before finally exiting.

This is very likely due to the three-second sleep at the end of `main()`. I assume it's there to make sure existing requests are finished being handled before the http server is killed. But it's fairly wasteful - it will still wait for three seconds even if there are zero connections. This is fairly annoying, especially when debugging issues and needing to rebuild and re-start the gateway often.

Luckily, in Go 1.8 `net/http` learned to shut down servers: https://golang.org/pkg/net/http/#Server.Shutdown

We should make Tyk on 1.8 or later use this, with a wait timeout of something like 1s or the existing 3s. Then, if no requests were being processed, the gateway would exit immediately. Otherwise, it would exit as soon as they were all done or the timeout was reached.

**Comment by mvdan** [comment]
1.9 won't be out with enough time for 2.4, so marking for 2.5.

**Comment by lonelycode** [comment]
This will have inplications with the hot reload (sigusr2) signal as well - just to keep it in the picture in terms of testing, between process reloads connections can't be lost.

**Comment by mvdan** [comment]
I'm not sure what you mean - this is replacing a sleep with a blocking call. I don't think I'd be touching any signal code.

Or you mean we should also use the graceful shutdown in hot reloads?
