### ISSUE TITLE
Upstream targets not taken out of pool when upstream tests fail

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#632]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Uptime Tests feature doesn't work well, with this option enabled gateway sends traffic on host which is down
**What is the expected behavior?**
Gateway should exclude down host from routing 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Current Master and Stable 2.3.3

More details:
https://community.tyk.io/t/upstream-targets-not-taken-out-of-pool-when-upstream-tests-fail/1481

**Comment by mvdan** [comment]
Assuming this is not high-priority and adding to 2.4.

**Comment by buger** [comment]
Well, this bug actually sounds like very serious. If we will be able put it to 2.3.4 it will be great. Needs investigation...

**Comment by mvdan** [comment]
2.3.4 is a security release that we said should be cherry-picked by tomorrow. I don't think we should delay it further for a non-security bugfix. Perhaps 2.3.5?

**Comment by buger** [comment]
maybe

**Comment by lonelycode** [comment]
> What is the current behavior?
> Uptime Tests feature doesn't work well, with this option enabled gateway sends traffic on host which is down

What option enabled?

**Comment by buger** [comment]
I initially thought that replicated this tests as well, but found that our default on-premise config have `"uptime_tests": {"disable": true,...` option.  Once I set it to false, everything started working as expected. @ilijabojanovic can you confirm that you can replicated it with this option turned off?

Worth noticing that looking at logs in community forum, they have uptime tests turned on, because there is messages like:
```
time="Mar 21 13:45:40" level=warning msg="[HOST CHECKER MANAGER] Host is DOWN: http://subdomainB:8890/v1/health"
```

**Comment by lonelycode** [comment]
I think it's an interaction with versioning - we know it works with standard default version apis.

**Comment by lonelycode** [comment]
That's why I asked "what option enabled - the bug report is not very clear. And the community forum post will change, so the full replicated bug should be on this ticket.

**Comment by ilijabojanovic** [comment]
I've tired versioned and standard apis. In both cases traffic was send to host which is down. In log i . have error:

tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="[HOST CHECKER] Checking: http://asdajkjkj.org/http://asdajkjkj.org/"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="[HOST CHECKER] Checking: http://httpbin.orghttp://httpbin.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="[HOST CHECKER] [HOST WARNING]: http://asdajkjkj.org/"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Recording uptime stat"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Pushing to raw key list: tyk-uptime-analytics"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Input key was: host-checker:tyk-uptime-analytics"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Appending to fixed key list: host-checker:tyk-uptime-analytics"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Input key was: host-checker:tyk-uptime-analytics"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Update key: PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="[STORE] SET Raw key is: PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Input key was: host-checker:PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="[STORE] Setting key: host-checker:PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Input key was: host-checker:PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="Input key was: host-checker:PollerCheckerInstance:asdajkjkj.org"
tyk-gateway_1    | time="Mar 24 21:57:30" level=warning msg="[HOST CHECKER MANAGER] Host is DOWN: http://asdajkjkj.org/"
tyk-gateway_1    | time="Mar 24 21:57:30" level=debug msg="EVENT FIRED: HostDown"

Analytics recording well this events:
https://screencast.com/t/D4BBKeBv

Here is my testing definition:
{
    "id": "58d596270599ed0264bc3e51",
    "name": "test",
    "slug": "test",
    "api_id": "d95b97454dab4f714c6ef41937126dbd",
    "org_id": "58d595da0599ed0264bc3e4d",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": ""
    },
    "use_basic_auth": false,
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [
            {
                "url": "http://asdajkjkj.org/",
                "method": "GET",
                "headers": {},
                "body": ""
            },
            {
                "url": "http://httpbin.org",
                "method": "GET",
                "headers": {},
                "body": ""
            }
        ],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/test/",
        "target_url": "",
        "strip_listen_path": true,
        "enable_load_balancing": true,
        "target_list": [
            "http://httpbin.org/",
            "http://asdajkjkj.org/"
        ],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "hostname",
            "port_data_path": "port",
            "target_path": "/api-slug",
            "use_target_list": false,
            "cache_timeout": 60,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": null
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false
}

**Comment by lonelycode** [comment]
You don't have the feature enabled that checks against the load balancer:

`check_host_against_uptime_tests: false`

It's an option in the UI above the uptimebtests settings.

**Comment by ilijabojanovic** [comment]
I fixed my api definition few minutes after i added comment. (i put wrong file in comment)

**Comment by ilijabojanovic** [comment]
I investigated more and played with different configs on my local on-prem version and doceker-develop-env.. This seems config issue. 

Issue is always visible with this configuration in tyk gateway (those are default parameters)
"uptime_tests": {
    "disable": false,
    "config": {
      "enable_uptime_analytics": true,
      "failure_trigger_sample_size": 3,
      "time_wait": 300,
      "checker_pool_size": 50
    }

Issue is not visible with this configuration:
"uptime_tests": {
    "disable": false,
    "config": {
      "enable_uptime_analytics": true,
      "failure_trigger_sample_size": 1,
      "time_wait": 2,
      "checker_pool_size": 50
    }

I am 99% sure if they change those parameters everything will work fine. Also @buger please try to test with this configuration.

**Comment by buger** [comment]
I can confirm that uptime tests do not work when with `"failure_trigger_sample_size": 1`. I updated #635 to fix the issue.
