### ISSUE TITLE
Stream Request getting aborted after 2 minutes 

### ISSUE THREAD

**Issue by mshahulpm** [TykTechnologies/tyk#6342]
tyk version : docker open source version

**Describe the bug**
I have an export feature in my application which stream data to the client continuously but if the request is taking longer than 2 minutes it is getting aborted, how to fix it ? 

**Reproduction steps**

1. create web server with stream api with stream time more than 2 minutes 
2. add the api to tyk and access the stream api through tyk url

**Actual behavior**
after 2 minutes it will get aborted with ERR_INCOMPLETE_CHUNKED_ENCODING browser error 

**Expected behavior**
the request should be finished without any time limit

**Comment by lolleko** [comment]
Do you have any proxy (e.g. Nginx) between the gateway and your server or between the gateway and client?

Some proxies set timeouts for connections.

In addition to checking the configuration of your proxies (if any exist) also make sure you configured the tyk timeout https://tyk.io/docs/tyk-oss-gateway/configuration/#http_server_optionsread_timeout

**Comment by mshahulpm** [comment]
> @mshahulpm are you still having this problem?

I couldn't solve this issue so I configured nginx as gateway and removed tyk from the project

**Comment by andyo-tyk** [comment]
Thanks for letting me know, @mshahulpm. I hope that nginx is offering all the functionality you need - if you need more dedicated API management capability in future, I hope you will come back and give Tyk another try!
