### ISSUE TITLE
No account lockout has been configured within the Dashboard

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk#637]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behaviour?**
No account lockout has been configured within the Dashboard meaning that an attacker can use an automated online brute force attack against a known valid user with impunity.

**What is the expected behaviour?**
Add an option which limits the amount of failed logins attempts and disallow login for the IP or login for some time.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All previous versions are affected.

**Comment by buger** [comment]
Migrated to Dashboard repository https://github.com/TykTechnologies/tyk-analytics/issues/208

Will keep this issue updated as well.
