### ISSUE TITLE
proxy.service_discovery.cache_timeout is not used

### ISSUE THREAD

**Issue by etsatsina** [TykTechnologies/tyk#638]
In the source code `tyk/tyk_reverse_proxy_clone.go:55` we can see that the default value (60s) for cashing is being used. We would expect to have a possibility to change this value through setting up `proxy.service_discovery.cache_timeout` (as it said in the tyk doc).

Affected version is v2.3.3.

**Comment by mvdan** [comment]
I believe the current code is correct. As you can see in the godoc https://godoc.org/github.com/patrickmn/go-cache#pkg-constants:

    // For use with functions that take an expiration time. Equivalent to
    // passing in the same expiration duration as was given to New() or
    // NewFrom() when the cache was created (e.g. 5 minutes.)
    DefaultExpiration time.Duration = 0

So passing an expiration of 0 uses the expiration passed to `New`, which already uses the gateway config option:

```
expiry := 120
if globalConf.ServiceDiscovery.DefaultCacheTimeout > 0 {
        expiry = globalConf.ServiceDiscovery.DefaultCacheTimeout
}
ServiceCache = cache.New(time.Duration(expiry)*time.Second, 15*time.Second)
```

Did you find this bug in practice, or was this something that you found when reading the code?

**Comment by mvdan** [comment]
Friendly ping @etsatsina

**Comment by mvdan** [comment]
Since there hasn't been a reply, I'll assume this was a misunderstanding of the code as I explained above. @etsatsina if you think I'm wrong, feel free to re-open this issue with details. Thanks.
