### ISSUE TITLE
As a user I should be able to define routing rules based on a combination of header, query param, content and path components

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#639]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Currently I can only redirect requests based on their inbound URL (using the URL rewriter), however if I want to route based on other factors (e.g. in a microservices pattern where a facade may expose a wide variety of underlying containers), then I can;t do this easily without resorting to virtual endpoints.

**What is the expected behavior?**
I should be able to route based on combinations of factors. 

**There are two components:**

For complex routing scenarios, I should probably use the JSVM and JSVM middleware, since I can just program it all, but currently when I return a different path, i cannot alter the target hostname. So an extension to the JSVM API might be the way to go so that I can return `"new_target": "foo"`, or add a host to the returned URL and Tyk will interpret it as a host-based reroute.

This can actually be triggered easily, since the URL rewriter just sets a context variable that sets a new target.

For simpler routes, we could extend the URL rewriter to include options such as:

```
"headers_must_contain": {"header": "{regex}"}
"query_param_must_contain"" {"variable": "{regex}"}
```

Then I can write a capture path, a regex to interpret for rewriting, and then only execute when the headers and query params are present. 

Open to more ideas on this?

**Comment by willks** [comment]
I voted for this feature as we are migrating from another gateway that had this functionality.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I should be able to define routing rules based on a combination of header, query param, content and path components](https://trello.com/c/rnM3o0mj/464-as-a-user-i-should-be-able-to-define-routing-rules-based-on-a-combination-of-header-query-param-content-and-path-components)

**Comment by bitsofinfo** [comment]
We have the need in URL rewrites to simply match on anything in the full URI + query params.

**Comment by nickReyn** [comment]
To all following this ticket in the community, what do you think of this as the UI for advanced routing? Anything you would do differently?
Essentially you can add `Triggers` to your url rewrites where you can define match params. In the `Match type` dropdown there would be:
- Header matches
- Query string variable/value matches
- Path part matches, i.e. components of the path itself
- Session meta data values (edit)
- Payload matches

![group 1](https://user-images.githubusercontent.com/15945383/33773949-8d5b2992-dc31-11e7-8f06-1f35ea0f074b.png)

@bitsofinfo @willks

**Comment by bitsofinfo** [comment]
@peloncano @ewah

**Comment by bitsofinfo** [comment]
@nickReyn looks ok but wouldn't you need an `ANY | ALL` for the match behavior across MULTIPLE of those match conditions

i.e 

`queryString[regex:.*] AND header[regex:Content-Type:xxdx]`
`queryString[regex:.*] OR header[regex:Content-Type:xxdx]`

The UI is not clear on how this would work the way that match condition is presented, seems like it should be declared 1x on its own, and NOT "per each row"

**Comment by nickReyn** [comment]
Thanks @bitsofinfo really good point.

Take a look at the revised flow. We're thinking that this will be an extra plugin accessed from the Endpoint designer, and follow the rough flow below.
Let me know your thoughts 

https://www.figma.com/proto/JJXxlc0Cr7yKaHgAYWSx2kRR/Routing-rules?scaling=contain&node-id=49%3A18

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advanced URL Re-write](https://trello.com/c/QWH8t6S8/501-advanced-url-re-write)
