### ISSUE TITLE
As a user I should be able to run JSVM functions on response objects

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#641]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can dynamically transform inbound requests with JavaScript, but i cannot do it with outbound data. 

An example use case might be: To translate chinese characters in outbound traffic.

**What is the expected behavior?**
That I can add a JSVM function to the response processors just the same way that I can to inbound as middleware.

**Comment by l3ender** [comment]
Will this be accomplished with https://github.com/TykTechnologies/tyk/issues/1526?

**Comment by sedkis** [comment]
Yes @l3ender  thanks
