### ISSUE TITLE
Make swagger imports generate tracked URLs instead of white listed URLs

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#643]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When I import a swagger definition, it generates a base API with all the paths listed as white lists, thbis is not ideal as it locks down the API unnecessarily.

**What is the expected behavior?**
The paths that are generated should be "tracked paths" instead as this is more useful and serves as a better start

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This is only really possible since v2.2 or so because that's when tracked paths were introduced.

**NOTE**: This must be ported to the dashboard too.

**Comment by mvdan** [comment]
@lonelycode I understand the dashboard also needs a fix for this - has a separate issue been open for it, or should we keep this one open?
