### ISSUE TITLE
Add a Search and Replace method to the Body Transform mechanism

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#644]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
It currently isn't possible to change parts of the response returned by an API call to endpoint

**What is the expected behaviour?**
We would like to add a feature to the Body Transform functionality that allows users to search for a particular key-value pair in a response and modify it (e.g., return "https" instead of "http" in a `page_url` element).

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This is for a new feature meaning that all previous versions are affected.

**Comment by Pinpin31** [comment]
We try to do a body transform like that with plugin body transform :
`
{"url":"https://original_url/1535719117-daff25c796e29855b2ae8df7194cbe2b2753739f-attestation.pdf"}
`
to 
`
{"url":"https://other_url/1535719117-daff25c796e29855b2ae8df7194cbe2b2753739f-attestation.pdf"}
`
I think that a search/replace functions would be great to do that.
Is this possible to add functions from gtf library ? https://github.com/leekchan/gtf

**Comment by joshblakeley** [comment]
Looks like it could be a good enhancement - and cheap to implement. I'll see if I can slip it into a patch if it tests ok.

**Comment by buger** [comment]
Note that `gtf` library `replace` function is not what it looks, it actually a "strip" function :)

**Comment by Pinpin31** [comment]
Yes replace from gtf is a strip function; 
Sprig seems better : http://masterminds.github.io/sprig/ ?

I see another issue #640 with the same request.
