### ISSUE TITLE
Add response middleware to Tyk

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#645]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
There currently isn't  a way to process a response before sending data back to the end user.

**What is the expected behaviour?**
We would like to make it possible to add middleware that will perform a function (e.g., an XMLHttpRequest function) on a response before returning it to the user.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This is for a new feature meaning that all previous versions are affected.

**Comment by lonelycode** [comment]
Might have already added this as #641 :-/ sorry
