### ISSUE TITLE
 http: panic serving 11.0.9.182:50530: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#649]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**

```
2017/03/31 03:20:30 http: panic serving 11.0.9.182:50530: runtime error: invalid memory address or nil pointer dereference
goroutine 1818005 [running]:
net/http.(*conn).serve.func1(0xc421d975e0)
	/mnt/shared/go/src/net/http/server.go:1721 +0xd0
panic(0xca71c0, 0x133bd20)
	/mnt/shared/go/src/runtime/panic.go:489 +0x2cf
main.(*DefaultSessionManager).ResetQuota(0xc420c14490, 0xc421f29800, 0x38, 0x0, 0x408f400000000000, 0x408f400000000000, 0x404e000000000000, 0x0, 0xffffffffffffffff, 0x59cb18fe, ...)
	/mnt/shared/go-T/src/github.com/tyk/auth_manager.go:101 +0x471
main.createKeyHandler(0x128a620, 0xc4223b4380, 0xc4223ac400)
	/mnt/shared/go-T/src/github.com/tyk/api.go:1346 +0x39a6
main.InstrumentationMW.func1(0x128a620, 0xc4223b4380, 0xc4223ac400)
	/mnt/shared/go-T/src/github.com/tyk/instrumentation_handlers.go:52 +0x97
main.CheckIsAPIOwner.func1(0x128a620, 0xc4223b4380, 0xc4223ac400)
	/mnt/shared/go-T/src/github.com/tyk/main.go:384 +0x1ee
net/http.HandlerFunc.ServeHTTP(0xc420a6dd20, 0x128a620, 0xc4223b4380, 0xc4223ac400)
	/mnt/shared/go/src/net/http/server.go:1942 +0x44
github.com/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4219ea000, 0x128a620, 0xc4223b4380, 0xc4223ac400)
	/mnt/shared/go-T/src/github.com/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.(*ServeMux).ServeHTTP(0xc421cea690, 0x128a620, 0xc4223b4380, 0xc421428200)
	/mnt/shared/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420426000, 0x128a620, 0xc4223b4380, 0xc421428200)
	/mnt/shared/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc421d975e0, 0x128b4a0, 0xc421340f00)
	/mnt/shared/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/mnt/shared/go/src/net/http/server.go:2668 +0x2ce
```

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

tyk 2.3.3
Go 1.8

By checking, the code comes from:
```
// If we have enabled HMAC checking for keys, we need to generate a secret for the client to use
if !apiSpec.DontSetQuotasOnCreate {
	// Reset quota by default
	apiSpec.SessionManager.ResetQuota(newKey, newSession)
	newSession.QuotaRenews = time.Now().Unix() + newSession.QuotaRenewalRate
}

```

**Comment by lonelycode** [comment]
What were you doing when this bug happened?

**Comment by penhauer-xiao** [comment]
I through the dashboard to create a key

**Comment by lonelycode** [comment]
Interesting, I thought we had fixed this bug. It essentially means the key you created was for an api that was not live or loaded by the gateway. 

Has the api been loaded on the gateway yet?

**Comment by penhauer-xiao** [comment]
if apiSpec != nil {    //  From this line of code speculation that the API was successfully loaded by the gateway

`
apiSpec := GetSpecForApi(apiId)
if apiSpec != nil {   
    checkAndApplyTrialPeriod(newKey, apiId, &newSession)
    // If we have enabled HMAC checking for keys, we need to generate a secret for the client to use
    if !apiSpec.DontSetQuotasOnCreate {
        // Reset quota by default
        apiSpec.SessionManager.ResetQuota(newKey, newSession)
        newSession.QuotaRenews = time.Now().Unix() + newSession.QuotaRenewalRate
}
`

**Comment by penhauer-xiao** [comment]
This panic is reported from the http2 package

**Comment by penhauer-xiao** [comment]
![image](https://cloud.githubusercontent.com/assets/6280121/24545358/738574dc-1639-11e7-8219-bc4150da18bd.png)

**Comment by penhauer-xiao** [comment]
![image](https://cloud.githubusercontent.com/assets/6280121/24545586/46bf500c-163a-11e7-8eeb-584837d202e7.png)

**Comment by mvdan** [comment]
> Go 1.8

Have you tried reproducing the crash with Go 1.7.5? Tyk 2.3.x official binaries are built with Go 1.7.x, so just to confirm that's not the issue.

**Comment by penhauer-xiao** [comment]
@mvdan   For  Go 1.7.5,  the tyk version 2.3.3  has the same issue.

**Comment by lonelycode** [comment]
@penhauer-xiao The panics, according to the trace and the tag, starts here (line 101):

```
func (b *DefaultSessionManager) ResetQuota(keyName string, session SessionState) {

	rawKey := QuotaKeyPrefix + publicHash(keyName) // 101 right here
```

... in `auth_manager.go` Which is a weird place for a nil pointer dereference. If you are using the dashboard, then you really should be using our packaged releases - have you tried replicating with them?

Also, have you made any changes to the source?

We will need a full STR (Steps to Reproduce) and to see the changes in order to help as we can't replicate this otherwise.

**Comment by penhauer-xiao** [comment]
@lonelycode,  the file auth_manager.go,  as below: 
`package main

import (
	"encoding/base64"
	"encoding/json"
	"strings"
	"time"

	"github.com/nu7hatch/gouuid"

	"github.com/TykTechnologies/logrus"
)

// AuthorisationHandler is used to validate a session key,
// implementing IsKeyAuthorised() to validate if a key exists or
// is valid in any way (e.g. cryptographic signing etc.). Returns
// a SessionState object (deserialised JSON)
type AuthorisationHandler interface {
	Init(StorageHandler)
	IsKeyAuthorised(string) (SessionState, bool)
	IsKeyExpired(*SessionState) bool
}

// SessionHandler handles all update/create/access session functions and deals exclusively with
// SessionState objects, not identity
type SessionHandler interface {
	Init(store StorageHandler)
	UpdateSession(keyName string, session SessionState, resetTTLTo int64) error
	RemoveSession(keyName string)
	GetSessionDetail(keyName string) (SessionState, bool)
	GetSessions(filter string) []string
	GetStore() StorageHandler
	ResetQuota(string, SessionState)
}

// DefaultAuthorisationManager implements AuthorisationHandler,
// requires a StorageHandler to interact with key store
type DefaultAuthorisationManager struct {
	Store StorageHandler
}

type DefaultSessionManager struct {
	Store StorageHandler
}

func (b *DefaultAuthorisationManager) Init(store StorageHandler) {
	b.Store = store
	b.Store.Connect()
}

// IsKeyAuthorised checks if key exists and can be read into a SessionState object
func (b *DefaultAuthorisationManager) IsKeyAuthorised(keyName string) (SessionState, bool) {
	jsonKeyVal, err := b.Store.GetKey(keyName)
	var newSession SessionState
	if err != nil {
		log.WithFields(logrus.Fields{
			"prefix":      "auth-mgr",
			"inbound-key": ObfuscateKeyString(keyName),
			"err":         err,
		}).Warning("Key not found in storage engine")
		return newSession, false
	}

	if err := json.Unmarshal([]byte(jsonKeyVal), &newSession); err != nil {
		log.Error("Couldn't unmarshal session object: ", err)
		return newSession, false
	}

	newSession.SetFirstSeenHash()
	return newSession, true
}

// IsKeyExpired checks if a key has expired, if the value of SessionState.Expires is 0, it will be ignored
func (b *DefaultAuthorisationManager) IsKeyExpired(newSession *SessionState) bool {
	if newSession.Expires >= 1 {
		return time.Now().After(time.Unix(newSession.Expires, 0))
	}
	return false
}

func (b *DefaultSessionManager) Init(store StorageHandler) {
	b.Store = store
	b.Store.Connect()
}

func (b *DefaultSessionManager) GetStore() StorageHandler {
	return b.Store
}

func (b *DefaultSessionManager) ResetQuota(keyName string, session SessionState) {

	rawKey := QuotaKeyPrefix + publicHash(keyName)
	log.WithFields(logrus.Fields{
		"prefix":      "auth-mgr",
		"inbound-key": ObfuscateKeyString(keyName),
		"key":         rawKey,
	}).Info("Reset quota for key.")

	rateLimiterSentinelKey := RateLimitKeyPrefix + publicHash(keyName) + ".BLOCKED"
	// Clear the rate limiter
	go b.Store.DeleteRawKey(rateLimiterSentinelKey)
	// Fix the raw key
	go b.Store.DeleteRawKey(rawKey)
	//go b.Store.SetKey(rawKey, "0", session.QuotaRenewalRate)
}

// UpdateSession updates the session state in the storage engine
func (b *DefaultSessionManager) UpdateSession(keyName string, session SessionState, resetTTLTo int64) error {
	if !session.HasChanged() {
		log.Debug("Session has not changed, not updating")
		return nil
	}

	v, _ := json.Marshal(session)

	// Keep the TTL
	if config.UseAsyncSessionWrite {
		go b.Store.SetKey(keyName, string(v), resetTTLTo)
		return nil
	}
	return b.Store.SetKey(keyName, string(v), resetTTLTo)
}

func (b *DefaultSessionManager) RemoveSession(keyName string) {
	b.Store.DeleteKey(keyName)
}

// GetSessionDetail returns the session detail using the storage engine (either in memory or Redis)
func (b *DefaultSessionManager) GetSessionDetail(keyName string) (SessionState, bool) {
	jsonKeyVal, err := b.Store.GetKey(keyName)
	var session SessionState
	if err != nil {
		log.WithFields(logrus.Fields{
			"prefix":      "auth-mgr",
			"inbound-key": ObfuscateKeyString(keyName),
			"err":         err,
		}).Debug("Could not get session detail, key not found")
		return session, false
	}

	if err := json.Unmarshal([]byte(jsonKeyVal), &session); err != nil {
		log.Error("Couldn't unmarshal session object (may be cache miss): ", err)
		return session, false
	}

	session.SetFirstSeenHash()

	return session, true
}

// GetSessions returns all sessions in the key store that match a filter key (a prefix)
func (b *DefaultSessionManager) GetSessions(filter string) []string {
	return b.Store.GetKeys(filter)
}

type DefaultKeyGenerator struct {
}

// GenerateAuthKey is a utility function for generating new auth keys. Returns the storage key name and the actual key
func (b *DefaultKeyGenerator) GenerateAuthKey(OrgID string) string {
	u5, _ := uuid.NewV4()
	cleanSting := strings.Replace(u5.String(), "-", "", -1)
	newAuthKey := expandKey(OrgID, cleanSting)

	return newAuthKey
}

// GenerateHMACSecret is a utility function for generating new auth keys. Returns the storage key name and the actual key
func (b *DefaultKeyGenerator) GenerateHMACSecret() string {
	u5, _ := uuid.NewV4()
	cleanSting := strings.Replace(u5.String(), "-", "", -1)
	newSecret := base64.StdEncoding.EncodeToString([]byte(cleanSting))

	return newSecret
}
`

**Comment by lonelycode** [comment]
That's completely unreadable - can you use the proper formatting tools so we can read it? (Three backticks to open and close a code block)

Also - are you saying that this is your modified version?

**Comment by penhauer-xiao** [comment]
@lonelycode   No,  I can't to modify it.

**Comment by lonelycode** [comment]
Ok so you're just compiling our code and it's causing this error?

Have you tried our packaged versions?

**Comment by penhauer-xiao** [comment]
Yes, I have just only compiling tyk code and causing this error.  
I haven't tried the tyk packages version from github release.

**Comment by mvdan** [comment]
@penhauer-xiao have you tried the latest gateway release, 2.3.8?

**Comment by penhauer-xiao** [comment]
@mvdan  No, I still use the old release version.
