### ISSUE TITLE
As a user I should be able to tag api versions

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#651]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Tags are only at a whole api level

**What is the expected behavior?**
I should be able to set a tag on a version so that I can do canary releases for specific versions across a clustered/MDCB deployment

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I should be able to tag api versions](https://trello.com/c/52xeO191/465-as-a-user-i-should-be-able-to-tag-api-versions)
