### ISSUE TITLE
As a user I should be able to access the full URL from rich plugins

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#652]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
The `MiniRequestObject` has an `URL` field that contains just the URL path.
In the CP middleware we have a similar structure (part of the protobuf definition).

**What is the expected behavior?**
It would be good to have the full URL as `URL` and the path as `Path`.
This might break existing plugins.

**Comment by mvdan** [comment]
Current naming is a bit confusing :) If you want to modify the existing field, target to 3.0.

**Comment by lonelycode** [comment]
Can't we version the protobuff?

**Comment by mvdan** [comment]
You mean version the middleware interface separately from the main gateway versioning? That could let us do these changes faster, but we'd need to keep support for older versions of the interface too, adding complexity.

Should we then keep support for older versions of the interface once 3.0 is out?

**Comment by lonelycode** [comment]
You're right it could be an absolute nightmare... let's keep it all in line
