### ISSUE TITLE
When the gateway detects a listen path collision, it should modify the listen paths

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#658]
**Do you want to request a *feature* or report a *bug*?**
bug/feature

**What is the current behavior?**
When two APIs are created that share a listen path, the colision causes them both to not be loaded by the gateway, which can have side-effects such as the gateway not being able to generate tokens for that ID.

**What is the expected behavior?**
The gateway should still load the API, but should modify the listen paths so that other operations can continue - it should throw an error to inform the user what has happened.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create an API with the listen path `/test`
2. Create another with the same listenm path
3. Both APIs will not load in the gateway

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
How should the modifications be? Appending underscores at the end until no collisions are found?

**Comment by buger** [comment]
Or just making path random uuid, as it done now when you by default create API without listen path.

**Comment by mvdan** [comment]
Or something like `<original-path>-<short-uuid>`? I'm thinking that keeping the original path somewhere would make it more intuitive for the user.

**Comment by buger** [comment]
Yes, make sense. We can try include it to the 2.3.5 if it will be easy to fix.

**Comment by lonelycode** [comment]
Well, if the api is tagged then we could use the tag in kreference of a uuid?

**Comment by mvdan** [comment]
Do we know for sure that `<original-path>-<tag>` will be unique, or are you saying that we should try that first before short UUIDs?

**Comment by lonelycode** [comment]
Yeah, I think we could dontag first then uuid so its a hierarchy, would be v. Useful for management gateways that are managing many tagged clusters - and it's predictable, whereas uuid would be good to just helpnusers out that are making mistakes

**Comment by mvdan** [comment]
After a crash found by @lghiur, @buger figured out that this can lead to crashes because we end up with an APISpec that hasn't been initialized, i.e. has a nil `store` and causes a nil pointer panic.

Moving up to 2.3.6.

**Comment by mvdan** [comment]
Reopening for the backport.

**Comment by mvdan** [comment]
Cherry-picked.
