### ISSUE TITLE
Attached key to a policy does not inherit the expiration date

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk#666]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Setting trial period to "Do not expire key" and attach this policy to a Key the latter does not inherit the trial period time.

**What is the expected behavior?**
A key attached to a policy with "Do not expire key" should never expire.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Set policy's "Trial period" to "Do not expire key"
- Update the policy
- Attach this policy to a key, that key will be set to expire in "About an hour"

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
Important addition, this bug happens ONLY if policy expiration set to "Never". In rest of the cases it inherited as expected.

**Comment by mvdan** [comment]
What's the severity of this, then? Should we aim to release with the bugfix releases in two weeks, or leave for the major releases a couple of months away?

Not knowing much about policies, this seems bad enough to fix in the upcoming bugfix.

**Comment by buger** [comment]
@ConsM make sense create this issue in dashboard repository

**Comment by buger** [comment]
Moved to dashboard repo
