### ISSUE TITLE
Change default values for uptime tets in default tyk.config 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#668]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
uptime_tests”: {
       “disable”: false,
       “config”: {
           “failure_trigger_sample_size”: 3,
           “time_wait”: 300,
           “checker_pool_size”: 50,
           “enable_uptime_analytics”: true
       }
   },

time_wait value is 300 seconds (5 minutes) 
**What is the expected behavior?** 
In order to improve host checking we should set lower value in default tyk configuration

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

We need to update documentation and default tyk configuration files on all distributions (packages, docker images..)

**Comment by buger** [comment]
Found it there:
```
./install/data/tyk.self_contained.conf:
   56      "config": {
   57        "enable_uptime_analytics": false,
   58:       "failure_trigger_sample_size": 3,
   59        "time_wait": 300,
   60        "checker_pool_size": 50

./install/data/tyk.with_dash.conf:
   73      "config": {
   74        "enable_uptime_analytics": true,
   75:       "failure_trigger_sample_size": 3,
   76        "time_wait": 300,
   77        "checker_pool_size": 50
```

**Comment by buger** [comment]
Currently, it means that for Tyk installed from packages, uptime tests almost did not work, because host will be marked as down only after 20 minutes (3 + 1) * 300s.

**Comment by buger** [comment]
Page that should be updated once Issue get closed https://tyk.io/tyk-documentation/ensure-high-availability/uptime-tests/

**Comment by ilijabojanovic** [comment]
@buger approved :D
