### ISSUE TITLE
Incorrect default value for uptime_tests.time_wait

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk#669]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When the tyk.conf file doesn't contain a default value for `"uptime_tests"."config"."time_wait"`, the value is assumed to be 1 second.

**What is the expected behaviour?**
Tyk should assume that the value is 10 seconds.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Run a Tyk using the default configuration settings, without `uptime_tests` section
2. Attempt to run Uptime tests whilst a host is down
3. Check the Gateway logs

The logs should contain an error like the following:

    time="Apr 11 10:39:21" level=warning msg="[HOST CHECKER MANAGER] Host is DOWN: http://{{IP_ADDRESS}}:8080/instanceStatus"
    time="Apr 11 10:39:34" level=error msg="http: proxy error: dial tcp {{IP_ADDRESS}}:8080: getsockopt: no route to host" api_id={{API_ID}} org_id={{ORG_ID}} server_name="{{IP_ADDRESS}}:8080" user_id= user_ip="{{USER_IP}}:46654, 10.0.0.0" user_name=
    time="Apr 11 10:39:34" level=error msg="request error: There was a problem proxying the request" api_id={{API_ID}} org_id={{ORG_ID}} path="/path/resource/rest/api/" server_name= user_id= user_ip="{{USER_IP}}:46654, 10.0.0.0"
     time="Apr 11 10:39:37" level=error msg="http: proxy error: dial tcp {{IP_ADDRESS}}:8080: getsockopt: no route to host" api_id={{API_ID}} org_id={{ORG_ID}} server_name="{{IP_ADDRESS}}:8080" user_id= user_ip="{{USER_IP}}:46654, 10.0.0.0" user_name=
    time="Apr 11 10:39:37" level=error msg="request error: There was a problem proxying the request" api_id={{API_ID}} org_id={{ORG_ID}} path="/path/resource/rest/api/" server_name= user_id= user_ip="{{USER_IP}}:46654, 10.0.0.0"

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions of Tyk are affected

**Comment by buger** [comment]
Worth noticing that host checker properly set default value to 10 seconds, BUT, when it set Redis key, to mark host as down, instead of default value, it always use config value (which 0) + 1. So this host down key expire in 1 second, and next check in 9 seconds (10 - 1). So for this 9 seconds Tyk will send data to the down host.

**Comment by ilijabojanovic** [comment]
@buger verified and approved for merge
