### ISSUE TITLE
Hostname overrides control_api_hostname

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#670]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**

“hostname”: “api.tyk-test.com”,
   “enable_api_segregation”: true,
   “control_api_hostname”: “www.tyk-test.com“,

Tyk admin endpoint does not work on www.tyk-test.com/tyk/

**What is the expected behavior?**
hostname value in tyk.conf should not override control api (/tyk/)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Add hostname in gateway configuration file
2. Add control_api_hostname in in gateway configuration file
3. Start gateway 
4. curl http://{control_api_hostname}/tyk/apis

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.4 and master 2.4

**Comment by mvdan** [comment]
Reopening for the cherry-pick.
