### ISSUE TITLE
Enable hash for api tokens in logs when gateway runs in hybrid mode

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#671]
**Do you want to request a *feature* or report a *bug*?**
Enhancement
**What is the current behavior?**
When gateway running in hybrid mode, in logs api tokens are visible without hash
 
tyk-gateway_1  | time=“Apr 11 22:33:00” level=info msg=“Recreating session for key: 58ed4f65bfc49b000106dbda7373d7a8daf34487447a3419e27c2ebd”
tyk-gateway_1  | time=“Apr 11 22:33:00” level=debug msg=“Lifetime is: 0"

**What is the expected behavior?**
Log should display hash for api token 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.4 and master 2.4

**Comment by lonelycode** [comment]
Note: we have a function that truncated and semi-anonymises a token (******abcdf) instead of the hash, we use this elsewhere in the audit logs, might be worth using that?
