### ISSUE TITLE
When detailed recording is switched on, the body data that gets recorded should be sanitised of any sensitive information

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#689]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
When body data is recorded, it will store all headers and other data in cleartext.

**What is the expected behavior?**
Tyk should attempt to remove data that it knows is sensitive, e.g. the raw token

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
What is the purpose of the detailed recording? I always assumed that this is for debugging, so any information is useful.

Probably it should be optional and user should we specify list of headers that should be sanitized.

**Comment by lonelycode** [comment]
You enable detail recording in the tyk.conf in the analytics section, once enabled the gateway will record the requestvand the response data in wire format as part of the analytics record.

This is disabled on cloud (you can imagine the disk space requirements), But some users prefer a full log of all data.

It *can* be enabled with a config change to the organisation key (the object used to enforce quotas on tenants, if present) and therefore can be used for debug logging, but many users need a full audit trail and want to record everything. 

Because it's a wire format string blob, we don't want to have to re-parse it to target segments of the object, I'd rather just have a list of regexes to run that do the redacting since the user might not be using headers, I.e. Auth in JSON body, auth in querystring and auth in header.

Adding user-defined regexes is a good idea - similar to our URL normalisation list. Would be useful for removing personally identifiable info from a log for e.g. Healthcare providers.

**Comment by QuduSEC** [comment]
@lonelycode, we have already discussed this issue on the support.tyk.io. Please make the option to activate/disable the sanitization process. For example, in our company it is very important to see all HTTP query params, but Tyk removes this data. We can delete such data ourselves when parsing logs, for example in logstash.

**Comment by buger** [comment]
Introducing new option, which holds an array of regexp sounds like a good idea.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When detailed recording is switched on, the body data that gets recorded should be sanitised of any sensitive information](https://trello.com/c/cgE9XOfe/467-when-detailed-recording-is-switched-on-the-body-data-that-gets-recorded-should-be-sanitised-of-any-sensitive-information)
