### ISSUE TITLE
The packaged version of Tyk (and other packages) should not need to run as root

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#690]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Tyk (and others) run as root. 

**What is the expected behavior?**
They should run as a system user. While this can be changed by the end user when they set things up, these security issues should be handled by default.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All packaged versions

**Comment by buger** [comment]
I assume this is connected with #691

**Comment by buger** [comment]
Here is related fpm options:
```
   --deb-user USER               (deb only) The owner of files in this package (default: "root")
   --deb-group GROUP             (deb only) The group owner of files in this package (default: "root")

     --rpm-user USER               (rpm only) Set the user to USER in the %files section. Overrides the user when used with use-file-permissions setting.
    --rpm-group GROUP             (rpm only) Set the group to GROUP in the %files section. Overrides the group when used with use-file-permissions setting.

```

**Comment by buger** [comment]
@excieve assign to you

**Comment by nickReyn** [comment]
@excieve poke - what's the status on this :)

**Comment by excieve** [comment]
@nickReyn Haven't touched this yet. Can prioritise if that's needed rather sooner, along with others related to packaging.

**Comment by lonelycode** [comment]
We can bump this to patch.

**Comment by excieve** [comment]
https://github.com/TykTechnologies/tyk/pull/1330. As well as in other components.
