### ISSUE TITLE
The packaged version of Tyk (and other packages) will make config files world readable

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#691]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Config files in Tyk (and pump and dashboard) are world readable, since they contain sensitive info, this should not be possible.

**What is the expected behavior?**
While this can be changed by the end user, the default installer should do this as best practice.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All packaged versions

**Comment by buger** [comment]
You mean unix file mode, right?

If so, you probably mean it should be readable only by special user, created by us, and Tyk process running with same user. 

What is the origin of this issue? Can you provide more details?

**Comment by lonelycode** [comment]
No, I mean that the file mode shouldn't allow "other" read access - it's user/group/all at the moment it's r/r/r 

So it is connected, but they are not dependent on each other.

**Comment by buger** [comment]
@excieve ^

**Comment by lonelycode** [comment]
Bump to patch

**Comment by excieve** [comment]
Addressed in https://github.com/TykTechnologies/tyk/pull/1330. As well as in other components.
