### ISSUE TITLE
Allow endpoints with insecure SSL certificates

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#693]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Currently, Tyk can't send a request to API endpoints with self-signed certificates.
**What is the expected behavior?**
Add option which skips verification for self-signed certificates
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
Golang TSL library supports setting `InsecureSkipVerify` flag https://golang.org/pkg/crypto/tls/ to fix this issue. We need to make it configurable.

**Comment by mvdan** [comment]
@buger we probably want to move this to 2.3.6
