### ISSUE TITLE
Proposal: a version of the /tyk/reload endpoint that blocks

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#703]
`/tyk/reload` currently just queues a reload (if none is already queued) and always returns 200 immediately.

I suggest adding another endpoint, like `/tyk/reload-block` or whatever name we fancy, that doesn't return 200 until a reload has been finished.

If a reload was already queued, it waits for that one to finish. If none was queued, it waits for the one it queued to finish.

It would still always return 200, because reloads don't currently catch any errors. But if in the future they do, this blocking version may return other status codes.

This is especially useful for scripting and our tests. Right now, if you want to fire a reload and wait for it, you have no option but to sleep for an arbitrary amount of time. Currently, our tests do this in a very hacky way, by first doing the `GET` and then just doing a reload manually:

```
 {method: "GET", path: "/tyk/reload/", adminAuth: true, code: 200, afterFn: func() { doReload() }},
```

This can lead to two reloads that are racy too.

CC @buger @lonelycode

**Comment by buger** [comment]
I like the idea, but I think it can be just query string param instead of new url.

**Comment by mvdan** [comment]
> I think it can be just query string param instead of new url

Sure. Perhaps `?block=true`, defaulting to false.

**Comment by mvdan** [comment]
Also thinking that it would make sense for the endpoint to block by default or always. But not sure if we can do that while keeping backwards compatibility. The current endpoint is always async and it's already shipped in 2.3.x.

**Comment by lonelycode** [comment]
Also most users will use the group reload, which is actually a pubsub trigger and a sync by default because we don't know about the state of other gateways.

Agree that it should be possible to have the reload call block, seems more like what you would expect.

What would be great is somehow seeing a group status of when each node last reloaded so I can confirm that a whole cluster is up to date.

**Comment by mvdan** [comment]
> seems more like what you would expect

I agree, but the old reload code was completely async (it just fired a few goroutines and returned 200) so I don't want to break backwards compatibility in 2.4. Unless that is fine by you?

> What would be great is somehow seeing a group status of when each node last reloaded so I can confirm that a whole cluster is up to date.

Broke this off into its own issue, since I was writing a wall of text :)
