### ISSUE TITLE
As a user I should be able to add correlation IDs to all my requests

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#713]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
All requests coming through the gateway are not uniquely identified

**What is the expected behavior?**
Tyk should tag up each request with a correlation ID (UUID), that can be injected as a header using the `tyk_context` namespace

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
Would this be the same thing as a "request ID"?

Would this be used by us, by users, or both?

**Comment by lonelycode** [comment]
Yes it's the same thing as a request ID, mainly used for auditing. To be used by users, we've been asked for this for ages, so much so that we set up a python plugin that does it:

https://github.com/TykTechnologies/tyk-plugin-correlation

But now it can be part of the main build (optionally added by enabling the context variable option in the api spec).

**Comment by buger** [comment]
I assume this Task also requires updating documentation

**Comment by lonelycode** [comment]
Yes it will

**Comment by ilijabojanovic** [comment]
@lonelycode @buger I need some documentation or example in order to test this :)

**Comment by mvdan** [comment]
@ilijabojanovic have you seen the test added in the PR? https://github.com/TykTechnologies/tyk/pull/715/files

**Comment by mvdan** [comment]
Meant to just comment, not reopen.

**Comment by buger** [comment]
@ilijabojanovic yeah, details indeed missing.

Here is documentation for this feature https://tyk.io/tyk-documentation/transform-traffic/request-headers/

To test it, your API definition should have the following `global_headers` section:
```
+	"version_data": {
 +		"not_versioned": true,
 +		"versions": {
 +			"v1": {
 +				"name": "v1",
 +				"expires": "2100-01-02 15:04",
 +				"use_extended_paths": true,
 +				"paths": {
 +					"ignored": [],
 +					"white_list": [],
 +					"black_list": []
 +				},
 +				"global_headers":{
 +					"X-Static": "foo",
 +					"X-Request-ID":"$tyk_context.request_id",
 +					"X-Path": "$tyk_context.path",
 +					"X-Remote-Addr": "$tyk_context.remote_addr"
 +				}
 +			}
 +		}
 +	},
```

So basically this PR's adds a new variable to $tyk_context.

**Comment by lonelycode** [comment]
I'm a bad person - sorry I should have made it clearer.
