### ISSUE TITLE
Extend Virtual Paths to call gRPC endpoints

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#718]
Currently it's possible to have Tyk proxy to a service and for it to run local JS code to handle orchestrations, however this can be quite expensive and lead to a latency hit.

It would be better (and more extensible) if I could set up an API in tyk that has as it;s target a gRPC server and then set up endpoints that map to functions on the gRPC host, essentially creating an RPC API Gateway.

The feature would mean that Tyk supports Websockets, HTTP Rest and RPC natively, it also significantly extends the capability of Tyk as a proxy for anyone using gRPC as a pattern, or more likely, need to provide glue-code and orchestration code that is more performant than Otto.

**Comment by l3ender** [comment]
As we start to use gRPC more in our environment, being able to use Tyk to proxy gRPC would be a great benefit.

**Comment by l3ender** [comment]
Please keep open. Native gRPC support would be a great feature for Tyk.

**Comment by andyo-tyk** [comment]
I think this ticket should have been closed some time ago; Tyk can now be used as a gRPC proxy, as detailed [here](https://tyk.io/docs/key-concepts/grpc-proxy/).
