### ISSUE TITLE
Proposal: rename all middlware_*.go files to mw_*.go

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#724]
This is mainly because it's tedious to have to write `middleware_foo` instead of just `mw_foo` before being able to hit "tab" and get the completion for the proper file. Doesn't help that there is a `middleware` directory.

Some of these filenames are also fairly long, like `middleware_organisation_activity.go` or `middleware_key_expired_check.go`. Neither have a test file, so it can get even worse like `middleware_key_expired_check_test.go`.

CC @matiasinsaurralde @buger

**Comment by matiasinsaurralde** [comment]
Makes sense, I think there's a plan to move the middleware to separate directories as well, right?

**Comment by mvdan** [comment]
Yes, but unfortunately the middleware code is tightly coupled to `APISpec`, which is tightly coupled to basically everything. So that will take months, at least.

If we ever move these to `middleware/`, we could get rid of the prefix altogether. For now, making the prefix shorter makes our lives easier.

**Comment by mvdan** [comment]
We're done with all the bugfix releases (for now), so I'll try to get this merged ASAP.
