### ISSUE TITLE
API definition loading process changed to be Dashboard driven

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#726]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
When API sharding is used, the Gateway receives all the API definitions from the Dashboard then discards the definitions which do not match the tags which have been configured for the Gateway.

**What is the expected behavior?**
Dashboard is able to provide only the API definitions that the Gateway requires.

Reasoning for this is that if the Gateway host is compromised, only a subset of the API definitions would be obtainable, rather than all of them.

Client request reads as follows:

> In order to isolate a specific gateway per organisation I want to use API sharding to make sure that my gateways only contain the API information from the specific organisation which it's configured to represent.
> 
> The situation as it is right now, this works but the gateways receive information about APIs which don't belong to the organisation which it's configured to represent.
> 
> The problem with this setup is that once a gateway is compromised a hacker could alter the tyk-gateway configuration and receive API info from all organisations.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
n/a

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
n/a

**Comment by davegarvey** [comment]
I think the implications for implementing this are quite large as it affects how APIs are loaded and probably how nodes register with a dashboard. It appears that the dashboard needs to define which APIs are available on a per-gateway basis, rather than being configured from the gateway side.

**Comment by jfranx** [comment]
That makes sense. Each API needs to be selected before sending by the dashboard. 
The bright side is that the dashboard has this information available. It needs to load the API definitions and match the tag with the node identifier.

Maybe there's even a better approach, match tyk-gateway identifiers with organisation objects.
Then you can send only the API's belonging to an organisation to a gateway of choice. This provides a very acceptable level of separation. On the gateway side you would not even need tags, they could still be available for whoever wants to use them but it'd not have to be required for sharding.

I'm aware that what I'm asking isn't a small feature but it would be a huge security benefit.

**Comment by buger** [comment]
@jfranx actually what you described, is already how our Hybrid solution works. We have a lot of organizations, and each hybrid customer only loads API's belonging to their organization. 

This works because of what we call multi-data center bridge, or "MDCB", which is a closed-source component, and basically acts as RPC proxy, which handles this logic and way more. This is a part of our enterprise offering, and if you are interested in it, feel free to reach using form below this page: https://tyk.io/enterprise-api-management/
