### ISSUE TITLE
Investigate why SessionState.MetaData is interface{}

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#730]
In the middle of a refactor, so can't do this right now. Will get to it soon - hence the reminder.

The field seems to always be used as a map.

**Comment by lonelycode** [comment]
It wasn't meant to be much broader, so it's an interface, but it gets used as a map all the time so we should change it.

**Comment by mvdan** [comment]
On the plus side, I had a quick look around and it seems to be the last field of its kind. `UserData` is an empty interface too, but that can be a `string` or a `SessionState`.

**Comment by mvdan** [comment]
Actually, this was probably because sometimes we assign `map[string]string` to it, not just `map[string]interface{}`. But that's even worse, because it can lead to panics due to type mismatches.
