### ISSUE TITLE
jsvm: bundle js/tyk.js as a string literal in the source code

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#739]
`js/tyk.js` has glue/helper code that is used by JS plugins. The JSVM runs it as a string, so it doesn't need it to be in a file on disk. The code is also internal, so there is no reason why it should be easily accessible and modifyiable by a gateway user.

I propose that we move it to a string literal and simplify things. This would also mean we could get rid of the `js` directory in the root of the repo, since there doesn't seem to be any other use for it.

@matiasinsaurralde mentioned that the file could be useful for users to run some global JS code prior to initializing their JS plugins. Do we support that officially? I could not find any docs around it.

If the "global" code only has to run before a plugin is set up, it could also just be added a the beginning of a plugin JS file.

/cc @lonelycode @buger

**Comment by buger** [comment]
Recent example: one of the users wanted to use base64 encoding inside middleware to make a HTTP request to URL protected by basic auth. Otto itself does not have such built-in function, so he had to embed it into middleware itself. 

So, there are multiple solutions to this issue.
1) Leave it as it is
2) Hide Tyk specific stuff into the string, and bundle to binary, and add an alternative solution for loading external code: for example load *all* files in js directory. 
3) Hide this stuff as in step 2, and tell user embed all needed functions right into the middleware. 

In my view, 3) is easiest to support and maintain.

**Comment by mvdan** [comment]
Agreed on 3. That's what I meant by "added at the beginning of a plugin JS file".

Also, coincidentally in https://github.com/TykTechnologies/tyk/pull/721 I'm adding newly exposed base64 funcs. Maybe we should make then "official". Or we can just leave them as is, undocumented, and we don't have to worry about supporting them and backwards compat.

**Comment by buger** [comment]
Note that this task will probably require tuning our release script, so it will stop including this file into distribution.

**Comment by nickReyn** [comment]
@ilijabojanovic any reason you moved this back to in progress? Trying to figure out what is needed for this issue

**Comment by mvdan** [comment]
@nickReyn because he believes he found an issue - see https://github.com/TykTechnologies/tyk/pull/1097. I replied there.

**Comment by ilijabojanovic** [comment]
@nickReyn @mvdan responded, on all tasks where i found some issues am moving them back to in progress since they are not finished

**Comment by nickReyn** [comment]
Cool, thanks 👍  sorry was reviewing quickly while on planning call and didn't see the PR

**Comment by mvdan** [comment]
We will include this in the release notes, not the docs - closing.
