### ISSUE TITLE
Put version number in Dashboard

### ISSUE THREAD

**Issue by saaqibz** [TykTechnologies/tyk#74]
Request to have an easy way to access version number in the tyk dashboard for version of tyk gateway and tyk dashboard. maybe a little, unobtrusive footer?

**Comment by mvdan** [comment]
This feature request affects the dashboard, not the open source gateway. As such, I've moved the issue to our internal repo.

I'm closing this for now, but we'll post a comment once it is fixed.

**Comment by peterhurford** [comment]
I see that the version number is now at the top-left of the dashboard. Nice!
