### ISSUE TITLE
As a user I should be able to block duplicate requests

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#740]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
I can submit the same request twice

**What is the expected behavior?**
 The gateway should be able to prevent this by checking a pre-specified header (e.g. Request ID)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
I don't understand - it's the gateway that randomly assigns request IDs when it receives a new request. How could two requests have the same ID?

**Comment by lonelycode** [comment]
Assume a downstream proxy or trusted client inserts its own IDs

**Comment by mvdan** [comment]
If this is custom IDs, should this not be done via a middleware/plugin? Or are you suggesting that we add a readily available middleware to make it really easy?

**Comment by buger** [comment]
This is quite common in modern APIs to use this approach, and here is a nice description: https://myobie.svbtle.com/how-we-allow-any-request-to-be-safely-repeated-at-anytime-for-wunderlist

I assume that basic idea is that even if upstream API does not support request-id feature, Tyk can augment this functionality on top of it. 

So the basic plan is to have a new option which specifies `request-id` header name, and if it is non-empty, Tyk will remember requests with this ids (if response was 2XX), and if a new request with the same ID comes it, it gets rejected with `409 Conflict`.  It should work with both Redis and RPC mode, including MDCB.

**Comment by buger** [comment]
Just an addition to the message above. I assume we need to introduce 3 options here `block_duplicate_requests`, `request_id_header`, and `duplicate_request_expire`.

**Comment by marians** [comment]
Stripe also has a good implementation of this concept with some advanced guarantees. They obviously need it to prevent undesired multiple financial transactions through retries. The key term is **idempotency**.

See https://stripe.com/docs/api?lang=curl#idempotent_requests

If this is what the original requester intended, I add my +1 for the feature request! We are currently implementing this on a per-endpoint basis and would love to offload this to the gateway.

**Comment by rhuiser** [comment]
This is exactly what I meant opening this CR.

Best -- Robin

**Comment by munimanjunath** [comment]
This is fantastic  feature  which was already implemented in other  API Gateways like Apigee not sure why it can't be done here out of box
