### ISSUE TITLE
using mutual ssl for authentication

### ISSUE THREAD

**Issue by mwaaas** [TykTechnologies/tyk#748]
**Requesting a feature or how can I write my own plugin***

I have assigned to look for api gateway that fits our requirements, tyk fits all of them apart from authentication. 
The requirements is to use ssl for authentication then add ssl cert info in the request header.

**Comment by buger** [comment]
Hello, glad to header it!

Mutual SSL is on our roadmap for next major release https://github.com/TykTechnologies/tyk/issues/357
