### ISSUE TITLE
Add CORS headers to error message if a token is invalid

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk#757]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If Tyk API used inside browser, browser can’t read values with CORS headers. So when Tyk raise 403 Key Expired error, browser can’t read it

**What is the expected behavior?**
OPTIONS pass through should enable a full set of CORS headers for invalid tokens

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

Was speaking with @buger , who might be able to provide more information if needed.

**Comment by buger** [comment]
Tyk abandons requests before CORS middleware adds its headers. Probably just need move this middleware before Auth checker.

**Comment by MangoMM** [comment]
@buger @ConsM  Started working on this issue & have a PR #1199 of what I I think solves the problem. Having said this, I am still a little unclear of expected logic & expected outputs given certain inputs.

e.g. Is the following logic correct?

GIVEN:
I send an OPTIONS request
WHEN
Request Token is expired or is invalid
THEN
Gateway should proxy OPTIONS request to upstream target

**Comment by MangoMM** [comment]
@buger @ConsM I need further clarification on this task as I cannot recreate issue. I need an API definition with the actual request that was made, response received, and expected response.

**Comment by lonelycode** [comment]
@MangoMM That logic is correct, but should actually already be applied because OPTIONS requests when the feature is enabled always get passed straight upstream. 

Might drop this issue form the milestone into a patch.

**Comment by buger** [comment]
@asoorm can you recap what is the current status of this task?

**Comment by letzya** [comment]
@asoorm Can you please update what's the status of this bug? thanks

**Comment by asoorm** [comment]
This ticket seems to be an incorrect description of the actual issue. Closing in favour of: https://github.com/TykTechnologies/tyk/issues/1506
