### ISSUE TITLE
Specify rate limit weights using upstream headers

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#760]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
By default, each request counted as 1 rate limit point. Sometimes there are endpoints which consume a different amount of resources, and it makes sense to apply different weight for them when calculating rate limits. 

This is an essential feature for granular rate limiting for GraphQL and similar APIs: where the complexity of response heavily depends on user search query.

**What is the expected behavior?**
A server can respond with: `X-Rate-Limit-Weight` header, which specifies the weight of current request.

**Comment by lonelycode** [comment]
This should be configurable as a header so it works with different things

Also maybe we should ensure that rate limits and quotas can use arbitrary metrics first (generalised metric counter), then we can easily plug new ones in

**Comment by buger** [comment]
@lonelycode can you add some examples on "generalised metric counter"? Not sure if I fully understand the concept.

**Comment by lonelycode** [comment]
So if a user wants to do "100 records per second", how do you define a record if a request could return 1 or 50 objects in a list? And that data might be in XML or JSON? 

So you'd want something that can take an arbitrary object, parse it, make some basic assumptions and then count the number of records - if it's generic enough it can fit any use case

Another one we get a lot is KB or MB per second or total - so based on content-size. But that's not generalisable I think.

**Comment by buger** [comment]
@joshblakeley moving to 2.7

This is definitely should be done in a more generalized way. Its configuration file can look smth like:
"weight": {
   "extract_from": "header",
   "extract_from_key": "X-Rate-Limit-Weight"
}

In addition to "header", possible values can be "response_size", or "response_time". 

Additionally, I'm not sure which object should own these settings. It really looks like Key and Policy attributes. And since we planning [rate limits per path](https://github.com/TykTechnologies/tyk/issues/1108), this weighting can be extended to paths as well.

It feels like can be a big theme for a separate release.

**Comment by joshblakeley** [comment]
I was looking at this today and I think this is really the starting point for a more overarching compatibility with GraphQL, happy to leave this for now but will keep researching around it and having a play in a branch with the way it will work when I have time.

**Comment by nathanschepers** [comment]
To echo what @lonelycode said above. I think there could be great value in offering 'speed limits' or 'traffic limits' in addition to 'rate limiting'.

Especially for endpoints that may return large amounts of data, clients may want to 'speed limit' that endpoint by MB/s rather than #requests/sec.

It may be worth investigating both whether any competitors have this feature, and which (potential) clients of ours have requested it.

**Comment by asoorm** [comment]
In addition to the ability to couple with response from upstream headers/body size:

What about within API definition, would it be possible to assign different weights to different paths?

```
/foo wgt: 5
/bar wgt: 1
```

If I hit `/foo` twice and `/bar` three times, then I consumed 13 of my `per` - which is defined at key/policy level.

**Comment by letzya** [comment]
The per path rate limit is resolved as part  #1108
But  is there a real use case to set weight in the api def and not as part of the upstream’s response? 
If we set it in the api def, we don’t need to do anything on the upstream code but on the other hand, on changes in the upstream the user needs to remember to update the weight in tyk.

**Comment by asoorm** [comment]
Having thought about it a bit more, it feels like specifying RL based on upstream headers might be kind of an anti-pattern.

Defining the rate limits seems to be API manager responsibility, not the underlying service. I would advocate at the moment to define RL weights in api definition rather than headers from upstream.

Are there any standards based examples of a gateway enforcing rate-limits based on header responses returned from an upstream?

**Comment by nathanschepers** [comment]
Whatever approach we take, we need to be sure that all of this is captured in analytics. Users should be able to query historical API usage data based on these kinds of weights.
