### ISSUE TITLE
GIL error when using Python bundles

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#761]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the bundles are loaded or reloaded, a GIL error shows up. This happens intermittently.
This might be related to recent changes in the API loader.

**What is the expected behavior?**
The bundles should be loaded correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Load a Python plugin, start/stop Tyk a few times.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions.

**Comment by mvdan** [comment]
Assuming it is a dup.
