### ISSUE TITLE
mw: use named constants for special error codes 666 and 1666

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#764]
The error codes `666` and `1666` are special in middlewares - the first makes the gateway respond to the client immediately, and the second makes processing the request stop entirely.

At the moment these numbers are hard-coded in multiple places and it isn't obvious what they do, unless you already know or unless you grep the whole codebase for how they're used.

I propose we replace them with descriptive names, like `mwStatusRespond` and `mwStatusStop`.

See my confusion in https://github.com/TykTechnologies/tyk/pull/763#discussion_r118194613.

/cc @matiasinsaurralde @buger

**Comment by mvdan** [comment]
Also, if you have better names, please speak up.

**Comment by matiasinsaurralde** [comment]
These names look fine to me!

**Comment by mvdan** [comment]
@lonelycode @matiasinsaurralde btw, I just realised that `1666` is only checked, but never set in our codebase. Do we want to remove this magic code? It seems like it has never been used either.
