### ISSUE TITLE
Transform GET request into a POST

### ISSUE THREAD

**Issue by adrien-f** [TykTechnologies/tyk#77]
Hello !

I've been trying to get into Tyk for an API at work and one of its specialties is that it only support POST request and we're trying to transform it into a REST API. 

Is it possible with Tyk to transform a GET request with its query parameters into a POST request with a JSON body (created from the query paremeters) ?

Thanks you in advance

**Comment by lonelycode** [comment]
Hi,

Not at the moment, however it's definetely a feature we'd consider adding.

will add it as an enhancment :-)

Thanks,
Martin

**Comment by adrien-f** [comment]
Thanks for the quick reply, I'll watch out for any changes then !

**Comment by lonelycode** [comment]
There's a method conversion middleware in v2.2
