### ISSUE TITLE
Apply policy when I request token dat in the gateway api

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#771]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

**Comment by lonelycode** [comment]
Stupid mobile version of GH lost all my input

**Comment by mvdan** [comment]
:/ I always use the desktop version on my phone and zoom around, because the mobile one is so crippled and awful...
