### ISSUE TITLE
Protocol Buffers based middleware does not support binary uploads (multi-part/form data)

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#778]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When uploading or sending a request that is a binary upload the middleware breaks:

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:621] String field 'coprocess.MiniRequestObject.body' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

**What is the expected behavior?**
It should be possible to process requests that include binary data (bytes) or multi-part form uploads

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a middleware function, then try to upload an image

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
Very similar thing happened (and was fixed) in the JS plugins: https://github.com/TykTechnologies/tyk/issues/351

@matiasinsaurralde I believe we already discussed this one when investigating the JS one - you can likely just use `bytes` instead of `string` for the bodies in the protobuf.
