### ISSUE TITLE
Deprecate HealthCheck API

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#784]
HealthCheck API is unreliable and should be deprecated.

It should be turned off by default, official config should not mention this options, and docs should explicitly say that it was deprecated.

**Comment by mvdan** [comment]
Perhaps we should even add a warning on startup if it's enabled, given how problematic it is.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deprecate Health check API](https://trello.com/c/3og0FQCM/461-deprecate-health-check-api)
