### ISSUE TITLE
Allow to specify custom analytics tags using headers

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#790]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
It will be useful to allow users to tag requests with custom values, like api version, country, or maybe Request-ID. Right now it is set of fixed values like `api-*`, `org-*` and etc. 

With this custom tags, it will be possible to use standard log viewer to view advanced request details, without enabling detailed logging.

My proposal is to introduce a new config option, where we specify list of headers which will be extracted to be tags. For example if we specify `X-Request-Id` header to act as tag, it will generate  `x-request-id-<header_value>` tag.

**Comment by lghiur** [comment]
Define a list of header in Apis designer (Advanced Options), name of section TBD.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow to specify custom analytics tags using headers](https://trello.com/c/alO1EibF/468-allow-to-specify-custom-analytics-tags-using-headers)

**Comment by lonelycode** [comment]
Is there a back-end PR for this? This has a gateway dependency.

**Comment by ilijabojanovic** [comment]
Verified and approved for merge
