### ISSUE TITLE
How do I restrict the parameters in the API like this ?

### ISSUE THREAD

**Issue by artemus717** [TykTechnologies/tyk#801]
![image](https://user-images.githubusercontent.com/16465173/27070119-21843330-504a-11e7-8475-d5f91320feca.png)

**Comment by buger** [comment]
Hello! You probably mean not restrict, but mark some of the as required?

**Comment by artemus717** [comment]
Yes, i want to define every parameter in the request, then Illegal request will not be forwarded to backend servers .
For example, i define an id param as a long data type, when a request with ?id=test will be forbidden.
I want to build a waf with modsecurity in front of api gateway to filter illegal request first, and api gateway as a second protection

**Comment by lonelycode** [comment]
We don't have an input validation middleware at the moment, though it's been asked for enough times - maybe we should generalise this to include XML schemas and JSON schema?

**Comment by artemus717** [comment]
Glad to hear that. Is there anything i can help ?

**Comment by buger** [comment]
You can help with planning phase if you want: define the scope of the issue, check what is currently missing in Tyk to make it work and etc. Is there anything we can re-use to implement this task faster, for example, jsonschema? Swagger definition by itself support this kind of attributes, but internal Tyk api definition not. 

In addition to Gateway we will need to update dashboard as well, so we need to think about the UI.

But as mentioned above

**Comment by artemus717** [comment]
We want to define request input parameter information and restrict them.

1. param order
