### ISSUE TITLE
It is recommended to replace the command line resolution package.

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#802]
In the command line parameter analysis; suggested using spf13/cobra packet replacement docopt/docopt.go

**Comment by mvdan** [comment]
@penhauer-xiao any specific reason why? Also note that these two libraries are vastly different. `docopt` just handles usage printing and options, while `cobra` is a CLI app library and has many more features, adding complexity.

**Comment by penhauer-xiao** [comment]
@mvdan   I agree with your opinion. I think it's complicated.

**Comment by mvdan** [comment]
Note that I agree that `docopt` is not particularly idiomatic in Go, but at the moment we're trying to focus on 2.4 features and fixes. We can't be refactoring the codebase forever. We might replace it at some point in the future.

**Comment by penhauer-xiao** [comment]
I see, thanks. @mvdan
