### ISSUE TITLE
Support gRPC and Go plugins by default

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#811]
**Do you want to request a *feature* or report a *bug*?**
Enhancement
**What is the current behavior?**
Currently if you want to support gRPC you need to use the "coprocess" and "grpc" build tags.
As I work on the plugins, I introduced a "go" build tag but I would like to get rid of it.

**What is the expected behavior?**
It would be much better if we support Go and gRPC plugins by default, as these don't require cgo at all.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All.

**Comment by mvdan** [comment]
Sounds good. No reason to keep it hidden in a build tag.

**Comment by lonelycode** [comment]
Constraint on this should be gRPC for now, we still need a good way to build go plugins.

**Comment by matiasinsaurralde** [comment]
It would be useful to have a gRPC-Go plugin tutorial for now, based on [this request](https://community.tyk.io/t/update-tyk-protobuf-repo/2312/5).

**Comment by buger** [comment]
@matiasinsaurralde can you clarify a bit. From what I understand having tags that build things separately not that bad, main idea here is that we should ship this functionality in default binaries. 

Can this task be solved purely by our packaging scripts, and just including "coprocess" tag in all our builds by default?
