### ISSUE TITLE
can't load package: package github.com/TykTechnologies/tyk: case-insensitive import collision

### ISSUE THREAD

**Issue by penhauer-xiao** [TykTechnologies/tyk#812]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

can't load package: package github.com/TykTechnologies/tyk: case-insensitive import collision: "github.com/TykTechnologies/tyk/vendor/github.com/Sirupsen/logrus" and "github.com/TykTechnologies/tyk/vendor/github.com/sirupsen/logrus"

**What is the expected behavior?**

To build it is ok

From file :D:\$docker\go-T\src\github.com\TykTechnologies\tyk\log\log.go
```
 import (
	"os"
	"strings"

	"github.com/Sirupsen/logrus"  //  like this should be changed to "github.com/sirupsen/logrus", is all lowercase, the author has been renamed.
	prefixed "github.com/x-cray/logrus-prefixed-formatter"
)
```

I was removed from the vendor directory, used to use glide to manage the dependencies, it is really easy to use. Do not need to go go one by one get the depend on the package.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

$git:(master*) go build 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

master branch

**Comment by lonelycode** [comment]
You need to re-pull dependencies - logrus jas since renamed back, this is an issue with your build env, travis Ci is passing.
