### ISSUE TITLE
Tyk buffers whole reply even if streaming is enabled

### ISSUE THREAD

**Issue by whizz** [TykTechnologies/tyk#824]
**Do you want to request a *feature* or report a *bug*?**
A bug I believe.

**What is the current behavior?**
When the backend server uses chunked encoding to send a large reply (over 1G of data), Tyk seems to wait until the whole answer arrives and only then starts sending to client. The transfer initiated with curl then fails with "curl: (18) transfer closed with outstanding read data remaining". The data looks intact and is the same as when calling the backend directly, but for some reason curl emits this error. The backend uses chunked encoding and the data starts to arrive after few seconds. The whole process lasts about 20 minutes. Then calling the backend directly, the data is coming during the whole process, but thru Tyk it waits for 20 minutes and then the data comes all at once.

I have seen issue #106. I have setup tyk to use flush interval of 100 (milliseconds) with close_connections set to false.

**What is the expected behavior?**
Data should start coming as soon as the backend starts sending it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

The backend is private, so I cannot provide a working example.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.6

I think it used to work in pre 2.0 versions.

**Comment by mvdan** [comment]
There are instances in the gateway where we read the entire request's body. One such example is JS plugins, since the interface requires passing the body as a string. Similar situations happen for coprocess plugins (Python, etc) and body transform middlewares.

Could you share your API definition details? Perhaps disabling one of those features would be enough to keep Tyk from reading the entire body.

**Comment by whizz** [comment]
Here is the API definition
```
{
    "id": "5808b72f69381f2114000001",
    "name": "myapi",
    "slug": "myapi",
    "api_id": "2feafc635c514ed16046113fdf9abe18",
    "org_id": "5800e79669381f3e71000001",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization"
    },
    "use_basic_auth": false,
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/myapi/",
        "target_url": "",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": true,
            "query_endpoint": "http://consulserver:8500/v1/health/service/myapi-api?passing",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "Node.Address",
            "port_data_path": "Service.Port",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 60,
            "endpoint_returns_list": true
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": null,
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": null
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": false,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": null
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false
}
```

**Comment by mvdan** [comment]
Could you try setting `"do_not_track": true`? Analytics is another case where the body is copied.

**Comment by whizz** [comment]
Is it possible to set this thru dashboard somehow? I do not see it anywhere in the API definition and do not have any experience with the dashboard API. Could you maybe provide a curl command to upload the new definition from JSON file?

Also, this will completely disable the API statistics, right? That is not exactly what we want.

**Comment by mvdan** [comment]
I don't think this is configurable via the dashboard at the moment.

Analytics copies the entire response's body (when I said "request" earlier, I meant response), so I'm afraid I don't see a workaround for you in the current version of Tyk.

We'll look into this as part of an upcoming release. Hopefully there's a way to avoid keeping the entire response (and/or request) body in memory unless strictly necessary.

**Comment by whizz** [comment]
I updated the definition thru dashboard API, `do_not_track` is set to `true`, but no effect on the streaming. It still does not work.

**Comment by whizz** [comment]
Any news on this issue? The last suggestion did not fix it. Thanks for any updates.

**Comment by mvdan** [comment]
No updates yet, no. As said, I don't think there's a workaround for the stable version so there's not much we can do in the short term. A fix couldn't make it into stable as it would touch too many components and have a rather high risk of breaking stuff.

If we have a patch for 2.4 or 2.5, we'll be sure to ask you to try it out :)
