### ISSUE TITLE
JSVM: fix config_data, add a test and document it with examples (JS plugins and virtual paths)

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#829]
This was broken unintentionally on master, because there were no tests and not even any docs for this feature.

In https://github.com/TykTechnologies/tyk/pull/820 I'm already fixing it and adding the test. This issue is to track adding documentation for it, including an example.

My test there should be a good start for an example.

**Comment by mvdan** [comment]
Fix done, only the documentation remains.

**Comment by buger** [comment]
Needs to be fixed for JSVM as well.

**Comment by mvdan** [comment]
(it never existed nor worked for the JSVM, so this is a new feature for that middleware)
