### ISSUE TITLE
Replace rsc/letsencrypt with x/crypto/acme/autocert

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#834]
As per the warning in https://github.com/rsc/letsencrypt:

> In the long term you should be using https://golang.org/x/crypto/acme/autocert instead of this package. Send improvements there, not here.

Also, the one we use seems to be semi-abandoned, whereas the other is much more active.

**Comment by mvdan** [comment]
Speaking of which, do we have tests of any kind for this? We don't seem to have unit tests in this repo. @buger @ilijabojanovic

**Comment by mvdan** [comment]
Ah, unfortunately the APIs are slightly different. `autocert` does not have Manager methods to marshal and unmarshal the internal state into a string.

**Comment by mvdan** [comment]
I believe the right fix is to supply a `Manager.Cache` backed by Redis, instead of using `Watch` in combination with `Marshal` and `Unmarshal`. To confirm my suspicion, I've sent https://groups.google.com/forum/#!topic/golang-nuts/LHEuEUHWnGI.

In any case, this switch is less trivial than I thought and the library we currently use isn't bringing any trouble. Moving back to 2.5.

**Comment by dernise** [comment]
Bump, the letsencrypt package is now broken and certificate issuance isn't working anymore
