### ISSUE TITLE
TestGetAPISpecsRPCSuccess is flaky, sometimes fails to bind

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#835]
Full log: https://api.travis-ci.org/jobs/245838707/log.txt?deansi=true

```
=== RUN   TestGetAPISpecsRPCSuccess
2017/06/22 15:34:10 gorpc.Server: [:9090]. Cannot listen to: [listen tcp :9090: bind: address already in use]
2017/06/22 15:34:10 gorpc.Server: [:9090]. Cannot accept new connection: [accept tcp [::]:9090: use of closed network connection]
2017/06/22 15:34:10 gorpc.Client: [:9090]. Cannot decode response: [read tcp 127.0.0.1:35700->127.0.0.1:9090: read: connection reset by peer]
[Jun 22 15:34:10]  WARN RPC Handler: GetApiDefinitions() returned nil, returning empty string
[Jun 22 15:34:10] ERROR Failed decode: unexpected end of JSON input
[Jun 22 15:34:10]  INFO main: Detected 0 APIs
--- FAIL: TestGetAPISpecsRPCSuccess (0.00s)
	api_definition_test.go:380: Should return array with one spec []
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x939f25]

goroutine 319 [running]:
testing.tRunner.func1(0xc4202a3790)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/testing/testing.go:622 +0x29d
panic(0xcd6380, 0x13b7710)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc.(*defaultListener).Close(0xc4207703f0, 0xc4208d4000, 0xe5b950)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/vendor/github.com/lonelycode/gorpc/transport.go:76 +0x25
github.com/TykTechnologies/tyk.stopRPCMock(0xc4203e1340)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/api_definition_test.go:336 +0xab
github.com/TykTechnologies/tyk.TestGetAPISpecsRPCSuccess(0xc4202a3790)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/api_definition_test.go:382 +0x12a
testing.tRunner(0xc4202a3790, 0xe5b530)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/testing/testing.go:697 +0x2ca
exit status 2
```

Not sure why this would happen. I assume we have all the ports to ourselves.

I can look into this once I'm done with the 2.3.7 stuff.

**Comment by mvdan** [comment]
@buger as you said once, Travis overwrites the build logs if you re-start it. >:( Good thing I copied the relevant part.

**Comment by mvdan** [comment]
Something to note too is that the test sometimes takes really long:

```
 $ gt -v -run TestGetAPISpecsRPCSuccess -count 5
=== RUN   TestGetAPISpecsRPCSuccess
--- PASS: TestGetAPISpecsRPCSuccess (0.01s)
=== RUN   TestGetAPISpecsRPCSuccess
--- PASS: TestGetAPISpecsRPCSuccess (1.02s)
=== RUN   TestGetAPISpecsRPCSuccess
--- PASS: TestGetAPISpecsRPCSuccess (0.01s)
=== RUN   TestGetAPISpecsRPCSuccess
--- PASS: TestGetAPISpecsRPCSuccess (1.02s)
=== RUN   TestGetAPISpecsRPCSuccess
--- PASS: TestGetAPISpecsRPCSuccess (0.01s)
```

Given how Travis is slower, perhaps it's hitting some sort of timeout with either the RPC server or client.

**Comment by buger** [comment]
`TestSyncAPISpecsRPCFailure` and `TestSyncAPISpecsRPCSuccess` both start RPC server, so this tests can't be run in parallel. 

We can make it work, if modify `startRPCMock` to use random port. In theory changing `gorpc.NewTCPServer(":9090",` to `gorpc.NewTCPServer(":0",` should do the job. Feel free to apply the fix.

**Comment by mvdan** [comment]
Note that no tests run in parallel. And what I showed above is running only one of the two.

**Comment by buger** [comment]
Stacktrace tells `Cannot listen to: [listen tcp :9090: bind: address already in use]`, and this is the only place where we start server on this address.  Also note that there is test `TestWriteDefaultConf` which sets `TYK_GW_LISTENPORT` to 9090 (and actually should be smth like 8181), and forget to set this value back to defaults. So there is chance that we start our internal server on this port somewhere (depends on tests order).

**Comment by mvdan** [comment]
I had a quick go at using `:0`, but it doesn't work because we start the server asynchronously, and the GRPC code doesn't expose the final port it will be running on (that I could find).

I think this is related to gorpc alone, and not `TYK_GW_LISTENPORT` (but that should be fixed too), since as I showed above it's wonky even if used on its own with `go test -run ... -count N`.

Since gorpc starts and stops the server asynchronously, perhaps it's related to how we can't know for sure if the server is up or down by the time we have to use it in the test.

**Comment by buger** [comment]
It exposes port in Addr variable, and we already assign connection string like this `config.SlaveOptions.ConnectionString = server.Addr`

**Comment by mvdan** [comment]
Yes, but when you use `:0` it should get replaced with whatever random, available port it selected. It just keeps on being `:0`, even if I sleep for a long time. I suspect gorpc doesn't expose the final port it got from the TCP listen on `:0`.

**Comment by buger** [comment]
Right, I remember that it is why I set fixed port there. Not sure what is the best way to do it, maybe dig inside gorpc library to extract port...

**Comment by mvdan** [comment]
Maybe we should select a really high, random port ourselves and hope for the best :)

I just tried that (random port between 30k and 60k) but some test runs still take ~1s instead of ~0s. I wonder if it would fix the flake, though.

**Comment by mvdan** [comment]
This is getting worse - it's bit me three times in the past week on Travis.

**Comment by mvdan** [comment]
Well, it just happened on 1.8.3 again now, thanks to our new panic:

```
=== RUN   TestGetAPISpecsRPCSuccess
--- FAIL: TestGetAPISpecsRPCSuccess (0.00s)
panic: gorpc.Server: [:9090]. Cannot listen to: [listen tcp :9090: bind: address already in use] [recovered]
	panic: gorpc.Server: [:9090]. Cannot listen to: [listen tcp :9090: bind: address already in use]
goroutine 696 [running]:
testing.tRunner.func1(0xc42006d380)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:622 +0x29d
panic(0xcc6e40, 0xc4204b9290)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/TykTechnologies/tyk.startRPCMock(0xc42072af48, 0xdd20a8)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/api_definition_test.go:325 +0x1fb
github.com/TykTechnologies/tyk.TestGetAPISpecsRPCSuccess(0xc42006d380)
	/home/travis/gopath/src/github.com/TykTechnologies/tyk/api_definition_test.go:375 +0xe6
testing.tRunner(0xc42006d380, 0xe64d20)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/TykTechnologies/tyk	0.509s
go test errored
```
