### ISSUE TITLE
Modify the load balancer to return a proper error if all hosts are down

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#836]
**What is the current behavior?**

If all hosts are down, the load balancer will route to any of them.

**What is the expected behavior?**

Instead of that, return a meaningful error response like "all hosts are down, please try again later".

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

Affects 2.3.x and master.

Note that I haven't encountered this nor reproduced this, but it's fairly obvious from the code that this is what we're doing - and we shouldn't do it.

/cc @buger

**Comment by mvdan** [comment]
Confirmed by @ilijabojanovic.

@buger thoughts on backporting this to 2.3.x? The patch would be simple. We could include it in 2.3.7 or 2.3.8.

**Comment by buger** [comment]
Standard response code for this error is 503

**Comment by mvdan** [comment]
Should we include any details from the hosts? For instance, if hosts are down with a 403, it might be useful for the client to know that. Or is hiding this from the user fine, since the gateway operator still has access to the details?

**Comment by buger** [comment]
Hiding is fine

**Comment by lonelycode** [comment]
We shouldn't leak log information to a client (a potentially hostile one in case of a DDoS).

We should defjnetely return a meaningful response.

**Comment by mvdan** [comment]
Cool, will work on a patch then. I'll let either of you decide if we should promote this to 2.3.7/2.3.8.

**Comment by mvdan** [comment]
Upon closer inspection, this will need some non-trivial refactoring to "bubble up" the error. So backporting would be a pain in the arse.

Since this is not a regression nor a critical bugfix, I'd say let's leave it for 2.4.
