### ISSUE TITLE
Can't initiated User and Organization by using Bootstrap

### ISSUE THREAD

**Issue by rabin111** [TykTechnologies/tyk#843]
Hello,

I have follow [this guide](https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/dashboard/) how to install tyk on Ubuntu and I was installed it on Ubuntu 14.04

From Step 4, To initialize user and organisation by using Bootstrap I got this result.

```
 root@ubuntu:~# sudo /opt/tyk-dashboard/install/bootstrap.sh 139.162.50.101
 Creating Organisation
 ORGID: 595351701d41c80fefec9089
 Adding new user
 USER AUTH: a9c8d7de667a4dd07d0741588cb025c8
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
 KeyError: 'users'
 NEW ID:
 Setting password
 
 DONE
 ====
 Login at http://139.162.50.101:3000/
 User: hc30or5e57@default.com
 Pass: test123
```

Then I'm going to the above URL and Login and it said "Credentials are incorrect, please try again"

Please advise.

**Comment by james-tyk** [comment]
Hi - please visit https://community.tyk.io/ and post your query there. Or search the forum for a potential answer from other users.

James
