### ISSUE TITLE
As a developer I should be able print directly to the console without logger

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#844]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Currently, users can use `log` function, and it formats the content, adds date, escapes special characters and etc.
**What is the expected behavior?**
Goal of the new `print` function is to avoid any formatting and print directly to gateway log

**Comment by mvdan** [comment]
You're talking about the JSVM, correct? Could you please clarify that in the title and/or description?
