### ISSUE TITLE
Cannot check if my api is working

### ISSUE THREAD

**Issue by RajeshKumar1990** [TykTechnologies/tyk#849]
I am new to tyk api gateway.I  m installing it in CentOS. I m following the tutorial given in your website.I already set up the api using the dashboard.But when i call it,
`curl -H "Authorization: null" http://127.0.0.1/test-api/get`
it says
` curl: (7) Failed connect to 127.0.0.1:80; Connection refused`

My dashboard looks like this 
![screenshot from 2017-07-01 09-27-13](https://user-images.githubusercontent.com/22511293/27758103-87612e94-5e3f-11e7-8a84-9f28cd85c8a7.png)

May i know what went wrong....

**Comment by mvdan** [comment]
Have you had a look at the gateway logs? Especially when you use the API or trigger a hot reload.

**Comment by RajeshKumar1990** [comment]
This is what i found from  tyk-gateway.stderr 


```
time="Jul  3 06:12:56" level=error msg=" --> Response was: {\"Status\":\"Error\",\"Message\":\"No nodes available\",\"Meta\":null}\n" 
time="Jul  3 06:13:00" level=error msg="Failed to register node, retrying in 5s" 
time="Jul  3 06:13:00" level=error msg=" --> Response was: {\"Status\":\"Error\",\"Message\":\"No nodes available\",\"Meta\":null}\n" 
time="Jul  3 06:13:01" level=error msg="Failed to register node, retrying in 5s" 
time="Jul  3 06:13:01" level=error msg=" --> Response was: {\"Status\":\"Error\",\"Message\":\"No nodes available\",\"Meta\":null}\n" 
time="Jul  3 06:13:05" level=error msg="Failed to register node, retrying in 5s" 
time="Jul  3 06:13:05" level=error msg=" --> Response was: {\"Status\":\"Error\",\"Message\":\"No nodes available\",\"Meta\":null}\n" 
```

This is found in tyk-dashboard.stderr
```
time="Jul  3 06:15:06" level=error msg="No nodes available" 
time="Jul  3 06:15:10" level=error msg="No nodes available" 
time="Jul  3 06:15:11" level=error msg="No nodes available" 
time="Jul  3 06:15:15" level=error msg="No nodes available" 
time="Jul  3 06:15:16" level=error msg="No nodes available" 
time="Jul  3 06:15:20" level=error msg="No nodes available" 
time="Jul  3 06:15:21" level=error msg="No nodes available" 
```
May i know why it says no nodes available.

**Comment by buger** [comment]
Looks like your license does not support this amount of nodes. Check your
dashboard ui nodes section, to see how many active nodes you currently have.
