### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#852]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
Not possible.

**What is the expected behavior?**
As a developer I can define a custom event which can be hooked into by other parts of my code. These are in addition to events such as QuotaExceeded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
N/A

**Comment by mvdan** [comment]
If it's a custom event, how is it fired? By a plugin/middleware/coprocess?

**Comment by matiasinsaurralde** [comment]
There's a `DispatchEvent` call in the RPC service definition, and a similar method for native middleware, both expect a JSON argument, let me see if I can come up with a sample.
