### ISSUE TITLE
Improved management of virtual endpoint JS code

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#853]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
Virtual endpoints are defined as separate code blocks. There may be duplication of code within these code blocks. If you want to load a particular code block first you need to use a long hostname in the API definition so that the API definition is loaded first.

**What is the expected behavior?**
As a developer I can define a JS file which would be loaded prior to any virtual endpoint code so that it can be used as a shared code file by virtual endpoints.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
N/A

**Comment by mvdan** [comment]
We could also do this globally for all JS code, similar to the discussion in https://github.com/TykTechnologies/tyk/issues/739.

In other words, a JS file that can be loaded once and whose funcs can be called by all JS VMs (Otto), be it from JS plugins or from virtual endpoints.

**Comment by davegarvey** [comment]
Sounds good!
