### ISSUE TITLE
Extend OIDC support to also handle OIDC Access Tokens

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#871]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Tyk only works with OIDC ID Tokens

**What is the expected behavior?**
Tyk should also support OIDC Access tokens that are JWTs

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by lonelycode** [comment]
This can be tricky, I may decommission this requirement because Access tokens deployed by OIDC IPDs can vary, so there's no guarantee that they will follow a specification in terms of JWT structure. Also, access token validation must be done by the [client according to the core spec here](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitTokenValidation).

**Comment by altaurog** [comment]
I am not sure what in the spec requires that individual services should perform validation as opposed to an API gateway, but I have seen arguments that [access tokens should be preferred over id tokens](https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis) for apis.  In any case, as far as I can tell, the openid middleware should work with [any jwt containing an `iss` and `aud` claim](https://github.com/TykTechnologies/tyk/blob/master/mw_openid.go#L111).
FWIW, we are using this with okta and it works.  I just set `issuer` to the contents of `iss` claim and `client_ids` keys to the base64 encoding of the `aud` claim.
But looking at the example auth0 access token in above-linked article, I see they have an array as the `aud` claim, so yeah, I guess that is variation that might be tricky to deal with.
