### ISSUE TITLE
Delete cache endpoint returns 404 error 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#900]
Branch: master
ENV: All

Reproduction steps:

1. Create api definiton 
2. Trigger cache invalidation 
```
Method: DELETE 
Endpoint: /tyk/apis/{api_id}
```
Actual:
In response we have this error:
404 page not found
Response code: 404

Expected:
We should got: Message: OK

**Comment by mvdan** [comment]
I could not reproduce, not with a unit test nor a web browser. Did your request URL path have a trailing slash, like `/tyk/apis/1/`?

**Comment by mvdan** [comment]
I meant `/tyk/cache/1/` by the way - I guess that was a typo in your original issue.

**Comment by ilijabojanovic** [comment]
@mvdan i made huge mistake. This issue is for tyk-analytics repo. This issue can be reproduced over dashboard api.
