### ISSUE TITLE
Get API Tokens return 404 error

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#901]
Branch: Master
ENV: All

Reproduction steps:

1. Create api definition 
2. Create tokens for that api definition 
3. Call:
```
Method: GET
/tyk/apis/{api_id}/keys
```
Actual:
{'Status': 'Error', 'Message': 'Could not retrieve keys', 'Meta': None}
Response code: 404

Expected:
We should got list

**Comment by mvdan** [comment]
That's not a valid endpoint, at least not in the gateway @ilijabojanovic. Any pointers?

**Comment by ilijabojanovic** [comment]
@mvdan i made huge mistake. This issue is for tyk-analytics repo. This issue can be reproduced over dashboard api.
