### ISSUE TITLE
Make `x-tyk-*` headers configurable

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk#917]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
N/A

**What is the expected behavior?**
As a user I should be able to configure the `x-tyk-*` headers or they could be optional.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
What's the root problem here? Does a user want to use different header names, such as ones that mention their product/company name instead of Tyk?
