### ISSUE TITLE
Add support for docker swarm mode service discovery

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#918]
I see that the service discovery integration does not support docker swarm.

Would be great if support for letting the gateway determine targets could integrate w/ docker swarm manager APIs automatically (i.e. fetch all containers ips/ports via the swarm service api)

**Comment by buger** [comment]
Can you clarify a bit, which exactly protocol does not supported by Tyk? 

Looking at the docs I see that https://docs.docker.com/swarm/discovery/ that for Swarm you can use either Consul, Etcd or ZooKeeper, and all of them supported by Tyk. 

See https://tyk.io/docs/ensure-high-availability/service-discovery/examples/ and https://tyk.io/docs/ensure-high-availability/service-discovery/

Basic idea is that Tyk can work with any service discovery which provides data in JSON format, and examples describe below, is just list of rules on how to parse this JSON.

**Comment by bitsofinfo** [comment]
yes read all that, but out of the box since docker 1.12+ "swarm mode" is the default clustering mech in docker https://docs.docker.com/engine/swarm/

By default all this information is stored in the swarm managers themselves and accessible via the services/networks/tasks APIs in docker. This is where the info is (not consul, etcd etc)

**Comment by buger** [comment]
I see what you mean. Well, we indeed do not support this yet. But from what I understand one of the main ideas of Swarm is to get away from service discovery tools like Consul. Swarm provides built-in DNS server, and you can just give this DNS address to Tyk and allow Swarm load-ballance by himself. And if you need more control, put proxy like nginx to do the job. 

But frankly I do not have enough information, so can only speculate on this.

**Comment by bitsofinfo** [comment]
good point yes, we could just have a static route that points to a LB that fronts all swarm nodes and it would do the same thing
