### ISSUE TITLE
Dashboard not connecting to localhost mongod

### ISSUE THREAD

**Issue by toringe** [TykTechnologies/tyk#92]
Using latest dashboard 0.9.6 with default configuration
 
     "mongo_url": "mongodb://localhost/tyk_analytics", 

Results in the following error:

    INFO[0000] Loading configuration from ./tyk_analytics.conf  
    ERRO[0011] Mongo connection failed (retrying):no reachable servers  
    ERRO[0023] Mongo connection failed (retrying):no reachable servers 

Mongod is listening

    tcp      0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN     

and localhost resolves properly

     $ host -r localhost
     localhost has address 127.0.0.1

But if I change localhost to 127.0.0.1 in `tyk_analytics.conf`

     "mongo_url": "mongodb://127.0.0.1/tyk_analytics", 

It works!

I used `localhost` in my config for dashboard 0.9.5.3, so I suspect it may be something that changed in the 0.9.6 release.

**Comment by lonelycode** [comment]
How odd, it may have something to do with Go 1.5. host lookup is handled differently. Will investigate :-)

**Comment by james4e** [comment]
My installation had the same issue. I changed to  "mongo_url": "mongodb://127.0.0.1/tyk_analytics". It works.

**Comment by emonik** [comment]
My Setup had the same issue & changed the config to 127.0.0.1 instead of localhost ... & it worked

**Comment by lomori** [comment]
+1

**Comment by hsen-dev** [comment]
+1

**Comment by lonelycode** [comment]
This is a bug in golang's resolver, using the 127.0.0.1 IP is the recommended way to fix this.
