### ISSUE TITLE
Unable to update key while it contains access to a deleted api results in confusing error message.

### ISSUE THREAD

**Issue by BetaGrumm** [TykTechnologies/tyk#921]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Currently, if you create an api, add it to a key, then delete the api, the access right is still on the key, and it prevents you from updating the key in any way until you remove it, but the error message is very confusing.
**What is the expected behavior?**
Provide a better error message stating that the key has access to a specific api that doesn't exist, or don't prevent update of the key.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create an API via the Dashboard.
Add access rights to a key.
Delete the API.
Create a new api.
Attempt to add the new api access right to the key, click update, see error message that is confusing as to what the real issue is.
Error message: "User does not have permission to add API to key Access Rights!"
Since I was trying to add a new api to the key, I didn't realize that the error message was referring to an old api that was removed. Simply stating the name of the offending api in the error message would have save me a lot of head scratching.
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard v1.3.6

**Comment by buger** [comment]
Thank you for the reporting!
