### ISSUE TITLE
Add HTTPS scheme support to the bundle downloader

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk#925]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Tyk support the HTTP scheme for bundle URLs. HTTPS isn't supported.

**What is the expected behavior?**
Support HTTPS URLs in the bundle downloader.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by mvdan** [comment]
The title is too broad and confusing. HTTPS scheme support where?

**Comment by buger** [comment]
@mvdan yeah, basic idea is that plugins/bundles are downloaded from the URL defined in API definition. Right now it allows only "HTTP".
