### ISSUE TITLE
Full OAuth 2 Support

### ISSUE THREAD

**Issue by ivanmartinvalle** [TykTechnologies/tyk#93]
First off, I know that there is a OAuth issue on https://trello.com/b/59d5kAZ5/tyk-api-gateway-roadmap . This is mainly for clarification/documentation purposes.

What do you believe to be the current state of the OAuth 2 flow? We are in the process of evaluating different API gateways, and need them to fully support OAuth 2 in production with several million API calls a month.

Needed features
- Password Grant flow
- Implicit Grant flow
- Authorization Code flow
- Client Credentials flow
- Ability to revoke refresh and access tokens

Of the above, it looked like to us that client credentials is missing from the current feature set. Is our conclusion correct? Furthermore, the we didn't see any support for refresh tokens either or revoking tokens based on a certain criteria (the authenticated user, for example).

Your perspective on this would be much appreciated. The OAuth implementations of every other API gateway are incredibly young. A good implementation would set this project above the rest. If you have a general idea of what you planned out for this and were to note your plan here, I might be able to code up a pull request.

**Comment by lonelycode** [comment]
Tyk's Oauth driver supports all of the modes you've listed, however we haven't investigated the flows for them yet since Oauth and third party gateways can provide problems since the spec isn't designed around a third party sitting between the resource owner and the client.

Support currently looks like this:

- Password Grant flow - driver supports it, not implemented or tested
- Implicit Grant flow - sit-up ported out of the box
- Authorization Code flow - supported out of he box
- Client Credentials flow - driver supports it, not implemented or tested 
- Ability to revoke refresh and access tokens - you can revoke access tokens if you know what they are, but not refresh tokens.

We use this fork of Osin (the Oauth lib) to handle the various grants https://github.com/lonelycode/osin

(We vendor it because the original upstream version keeps making breaking changes).

But as you can see it has all of your access types, we just need torn able them in our flows: 

https://github.com/lonelycode/osin/blob/master/access.go

The number of requests for more OAuth support has been increasing, so we'd be looking to expand on this feature set soon.

Of course, we would love some help in this regard as OAuth flows are complicated and can be very nuanced, making them hard to test :-)

**Comment by czerwina** [comment]
Oauth2 support would bd a game changer. I'd love to help but not a golang programmer. Would someone be willing to make a beta version with all the flows turned on? I assume this uses redis for token storage?

**Comment by lonelycode** [comment]
Update on this issue - master branch of the gateway now supports password grant flow:

- Create new client
- Create a basic auth key for each user
- Set the `allowed_access_types` array to include `password`
- Generate a valid access request with the client_id:client_secret as a Basic auth header and the u/p in the form of the body.
- POST to: `/oauth/token/` endpoint on your OAuth-enabled API
- If successfull, the user will get: 

```
{"access_token":"4i0VmSYMQ2iN7ivX0LaYBw","expires_in":3600,"refresh_token":"B_99PjEmQquufNWs8QYbow","token_type":"bearer"}
```

This will be in the next point release.

**Comment by czerwina** [comment]
Cool - thanks for the update

**Comment by lonelycode** [comment]
Latest point release is out that begins to address this issue - includes Password OAuth support: https://github.com/lonelycode/tyk/releases/tag/v1.8.3.2

**Comment by allenmoatallen** [comment]
Do you have plans for the Client Credential flow?

**Comment by lonelycode** [comment]
Eventually, yes. We're adding to the OAuth feature set all the time, we're basically working through the list in this ticket. 
The last release had password flow, this release we're smoothing out some issues around request token invalidation and configurable access token lengths.
We'll be addressing each of them as we get to them :-)

**Comment by allenmoatallen** [comment]
Based on the list looks like it would be the next to be looked at given that you said Implicit and Auth are already supported. That's good news. If I knew GO I would try to contribute but I think it is a bit beyond my skill.

**Comment by lonelycode** [comment]
Update: Refresh token invalidation now has an API endpoint in Tyk develop branch.

**Comment by gtrias** [comment]
Thank you for the explanation. I think could be great if the documentation would explain how to use the Tyk OAuth2 Flow, i.e I didn't know I had to put Basic Auth header with client_id:secret keys..

**Comment by nazarhussain** [comment]
@lonelycode I am trying this curl request: 

```bash
  curl -X POST http://company.cloud.tyk.io/api/oauth/token/ \
    --header "Authorization: Basic md5_of_client_id:client_secret" \
    --data "grant_type=password" \
    --data "username=username" \
    --data "password=password"
```

Its giving me the error: 

```json
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}
```

I had enabled "Password Access Type", as per your comment on https://github.com/TykTechnologies/tyk/issues/93#issuecomment-140101815 it seems perfect but not working for me. 

Can you please highlight what's wrong in it?

**Comment by lonelycode** [comment]
I think the Authorization header needs to be base64 encoded as per the Basic Auth spec. You don't need to md5 the client id. That may be your issue here.

**Comment by nazarhussain** [comment]
Yes you are right. It was mistake by me. I corrected it and it is working fine. 

```bash
curl -X POST http://company.cloud.tyk.io/api/oauth/token/ \
    --header "Authorization: Basic base64_of_client_id:client_secret" \
    --data "grant_type=password" \
    --data "username=username" \
    --data "password=password"
```

One thing I noticed further is I use url `http://company.cloud.tyk.io/api/oauth/token/` it works fine. If I remove trailing slash and use `http://company.cloud.tyk.io/api/oauth/token` it gave "Requested endpoint is forbidden". Why should it be like this?

**Comment by lonelycode** [comment]
Our URL matcher is quite strict, so the slash is required. We're looking to fix this in the next point release as it trips up a few people.

**Comment by nazarhussain** [comment]
@lonelycode Sorry to make this issue as discussion board. But I am working on a scenario and need to implement it. 

With password flow, is it possible that tyk add a header entries into request for all tags and meta data associated to authenticated key(username/password) before passing to my backend api?

**Comment by lonelycode** [comment]
Yup, this isn't the place for it.

The scenario is possible, read the docs on transformations

Further questions would be best in the community mailing list where there's already discussions on this.

**Comment by ashee** [comment]
Any chance OAuth 2 client_credentials can be implemented? I need something like - https://dev.twitter.com/oauth/application-only or http://docs.apigee.com/api-services/content/oauth-20-client-credentials-grant-type

**Comment by lonelycode** [comment]
It's on the roadmap :-)

**Comment by mNantern** [comment]
In [OAuth 2.0 documentation page](https://tyk.io/tyk-documentation/security/your-apis/oauth-2-0/) it's written that:

> Tyk supports the following grants:
Authorization Code
Refresh token
Password
Client Credentials

Is it possible to use client credentials grant type or it's a mistake in docs ?

**Comment by lonelycode** [comment]
Client credentials is supported

**Comment by mNantern** [comment]
Great news ! Do you have documentation (or an example) on how to use it ?

What is missing to close that issue ?

**Comment by ibondare** [comment]
+1 - I don't see any useful information on supporting the client credentials flow in the latest release.

**Comment by lonelycode** [comment]
It's been supported for a while now, in the dashboard auth options you can now select client credentials as an option and use that flow.

**Comment by ibondare** [comment]
Thanks! Perhaps I am overlooking in it, but where exactly do I provision the client_id and client_secret for my API consumers?

**Comment by lonelycode** [comment]
Create an aPI and set it to use OAuth2 (and set the client creds option) then in the api list there's an OAuth clients button next to the api name where yu can add clients

**Comment by ibondare** [comment]
Got it. Thank you! Perhaps the documentation could be improved a bit? Specifically, once I have the client_id and client_secret, what is the target URL for my API consumers to obtain OAuth tokens? Assuming that my API is exposed by the Tyk proxy at http://localhost:8080/v1/, is it http://localhost:8080/v1/oauth/token, or something else?

**Comment by lonelycode** [comment]
There's an overview of the most standard flow here:

https://tyk.io/tyk-documentation/security/your-apis/oauth-2-0/

And sample code here:

https://github.com/TykTechnologies/tyk-oauth-flow-example

**Comment by ibondare** [comment]
Had anyone else out there got the client credentials flow documented? I must be the slowest person on here :) Looking at the Golang example, I am starting to question whether or not OAuth 2 client credentials flow works out of the box at all. The example creates a Tyk session, is aware of the policy ID. I want my API consumers to obtain OAuth tokens with *no* extra code on the backend, given that the API consumer is in a possession of a valid, Tyk-generated cilent_id and client_secret value. So far, I see no way to do that. It's a showstopper for me.

P.S. lonleycode - I appreciate your willingness to help, and your timelines, very much.

**Comment by lonelycode** [comment]
The examples all use the authorisation flow because it's the most complex, client credentials should use the same flow as just standard access token without the bit where a login is required. 

There's a test you can use for reference here:

https://github.com/TykTechnologies/tyk/blob/master/oauth_manager_test.go#L437

**Comment by ibondare** [comment]
Thank you, that helped a bit, but I see that your test passes an Authorization header with a Basic value set in it. What's that for? My Tyk gateway rejects the request to /widgets/oauth/token with 
{
    "error": "Authorization field missing"
}

without the header. 
 
Any further info on it? Thanks.

**Comment by lonelycode** [comment]
It's b64 encoded clientid:secret as a basic auth header, pretty standard for OAuth

**Comment by ibondare** [comment]
Thanks! Got it.

**Comment by nchapon** [comment]
Hello, I am blocked with client_credentials flow !

When I try to get an access token I have a 403 : 
{
  "error": "Requested endpoint is forbidden"
}

My query with my API /catalog

curl -i -X POST \
--url http://localhost:8080/catalog/oauth/token/ \
--data "client_id=c51666e49bc34be96bc0142e5d34fcc6" \
--data "client_secret=MTBhZGNmZTMtZGQzOC00NjBmLTU1MzEtZjZhMzA5OGQzMDU0" \
--data  "grant_type=client_credentials"

Any suggestions ?

Thanks

**Comment by mvdan** [comment]
@nchapon unless there's something I'm missing, your question has nothing to do with Oauth2. Please take this to the community forum: https://community.tyk.io/
