### ISSUE TITLE
Help users to provide valid API definition objects

### ISSUE THREAD

**Issue by marians** [TykTechnologies/tyk#942]
**Do you want to request a *feature* or report a *bug*?**

Debatable. I'd like the feature of providing an API definition to become more useable and future-proof.

Similar to https://github.com/TykTechnologies/tyk/issues/336 (which is for the tyk configuration), I'd like better support for the user providing API definitions. Don't know what the best would be. Better log output, more detailed Rest API error messages, or a lint command would all help.

Furthermore, it appears as if users are forced to provide huge definition objects, while only a few are really required. So far I couldn't find a place in the documentation that clarifies on this. All the examples I find provide contain all possible attributes, where most are empty. (This also makes me wonder about future migrations: Will later versions of tyk accept older definitions where some attributes aren't provided yet?)

**What is the current behavior?**

- When providing an API definition JSON in the `apps` directory, the definition is either loaded on tyk startup or on a request of `/tyk/reload` of the Tyk API. The log output there is not helpful to find errors in the definition. Requests to ``/tyk/reload` don't provide any feedback on the definition content.
- When submitting a new API definition via the Tyk API, feedback is given in the form of the response. The feedback does only include a binary info whether or not the submission has been accepted. Example:

```
HTTP/1.1 400 Bad Request
Content-Length: 46
Content-Type: application/json
Date: Tue, 25 Jul 2017 10:29:40 GMT

{
    "error": "Request malformed",
    "status": "error"
}
```

**What is the expected behavior?**

- Output in logs and on Rest requests should contain enough info to help me fix a broken API definition.
- Docs should tell me which attributes are really required and which can be ommitted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.3.7

**Comment by buger** [comment]
Make sense. Worth noticing that we sort of solved this issue if you are using Dashboard. We have jsonschema for the API definition, and if you try to submit broken definition to Dashboard API, it will give you the list of meaningful errors. Probably make sense implement the same thing in Gateway.

**Comment by marians** [comment]
@buger Is that jsonschema available somewhere?

A bit of background: I am currently evaluating. Our workflow would most likely be git-based, so that our API definitions would live in JSON files in a repository. I don't see a use currently for the Dashboard. Requiring the dashboard to submit some more or less static API definitions doesn't seem the right way to me.

**Comment by buger** [comment]
Just to clarify, Dashboard is not just a GUI. It is more like a distributed API to control gateway cluster. And UI itself it just built on top of this API. A lot of our clients use dashboard headlessly via API, and include it to CI/CD cycle. 

 
Here is JSON schema file we use at the dashboard.
https://gist.github.com/buger/0a11b20ab3e44b5535c25cf96169656b

**Comment by marians** [comment]
Thanks for the schema Gist. Any plans to make that live in an open repository?

**Comment by buger** [comment]
We do, but can't give you any ETA yet. Next milestone is very dense.

**Comment by marians** [comment]
Thanks for you quick responses, here and in the other issues.
