### ISSUE TITLE
API Whilte List / Mock Response endpoint camel case bug.

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#948]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Within the mock response,
For example, if I have an endpoint  as `/abc`, it will respond as what I want;
However, if create a similar response like `/aBc`, other definitions are totally same. it will not give the response I want, but give a `403` response as 
```
{
    "error": "Requested endpoint is forbidden"
}
```
and the gateway log will be 
```
tyk_gateway_1    | time="Jul 26 08:17:05" level=error msg="request error: Requested endpoint is forbidden" api_id=f10ded6113084f414eccfb02efb22f20 org_id=596c7df74c0b330001610671 path="/fundCashBalance" server_name="http://httpbin.org/" user_id= user_ip=172.22.0.1 
```
**What is the expected behavior?**
Response as the user defined mock response.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create the mock response endpoint with both all small case and camel case. eg. `abc` and `aBc`
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.7

**Comment by hustshawn** [comment]
It seems that when defined in a camel case endpoint, the defined path would be exclude outside of the `whitelist`, that's should be what `Requested endpoint is forbidden` mean.

**Comment by mvdan** [comment]
I'm not sure I understand the bug. Could you provide complete steps to reproduce it, including the API definition and what requests were made to the gateway?

**Comment by hustshawn** [comment]
@mvdan  Thanks for your reply, and you probably refer to such API endpoint definition snippets.
```
...
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "white_list": [
                        {
                            "path": "someEndpoint",
                            "method_actions": {
                                "GET": {
                                    "action": "reply",
                                    "code": 200,
                                    "data": "[\n    {\n        \"clientCode\": \"i8619515\",\n        \"cashBalanceItemJsons\": [\n            {\n                \"currency\": \"USD\",\n                \"balance\": 10000000,\n                \"pending\": 2000000,\n                \"available\": 8000000\n            },\n            {\n                \"currency\": \"HKD\",\n                \"balance\": 50000000,\n                \"pending\": 0,\n                \"available\": 50000000\n            }\n        ]\n    }\n]",
                                    "headers": {}
                                }
                            }
                        },
                        {
                            "path": "someendpoint",
                            "method_actions": {
                                "GET": {
                                    "action": "reply",
                                    "code": 200,
                                    "data": "[\n    {\n        \"clientCode\": \"i8619515\",\n        \"cashBalanceItemJsons\": [\n            {\n                \"currency\": \"USD\",\n                \"balance\": 10000000,\n                \"pending\": 2000000,\n                \"available\": 8000000\n            },\n            {\n                \"currency\": \"HKD\",\n                \"balance\": 50000000,\n                \"pending\": 0,\n                \"available\": 50000000\n            }\n        ]\n    }\n]",
                                    "headers": {}
                                }
                            }
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
...
```
Basically, I wanna get the mock response from  `/someEndpoint` , but it seems I can only define the name as `/someendpoint` and it may work. Otherwise i will get the previous mentioned `403` response.

**Comment by mvdan** [comment]
So just to be clear, do you want both `/someendpoint` and `/someEndpoint` to work and either doesn't (when you declare the two), or do you just want one of them to work and it's wonky?

**Comment by hustshawn** [comment]
@mvdan I want the mock response of `/someEndpoint` work.

**Comment by lonelycode** [comment]
This isn't a bug, since mocks piggyback on list functionality, the inbound path is matched to the defined one in lowercase, this means that /aBc will match against /abc.

Have tu tried using the camel case request against a lowercase definition?

**Comment by hustshawn** [comment]
@lonelycode Yes, it really works as what you described.  But I also find the non-mock APIs are case sensitive.  it looks wired that for mocks are non-case-sensitive, while those none mock APIs are not.

Is it possible to uniform both of them to case sensitive?

**Comment by lonelycode** [comment]
It's because the mocks execute alongside a list, and since lists are there for securing an API they apply case insensitivity, while others don't 

Eventually we need to move the mocks into their own middleware, if you want to raise an issue for it it'll be on our radar?

**Comment by hustshawn** [comment]
@lonelycode Yes. Thanks.
