### ISSUE TITLE
config_data is restricted to map[string]string on stable

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#951]
See https://community.tyk.io/t/config-data-more-complex-values/1788.

This is fixed on master, as the type there is `map[string]interface{}`.

**Comment by mvdan** [comment]
Merged.

**Comment by bitsofinfo** [comment]
@mvdan just want to confirm that this will support a fully nested/typed JSON element for `config_data` meaning complex object keys, ints, booleans, strings etc.
