### ISSUE TITLE
Feature: support multiple HTTP methods in Endpoint Designer

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#954]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Single HTTP method per URI match and action

**What is the expected behavior?**

Multiple HTTP methods or "ANY" per single URI match and action

In endpoint designer, I have some endpoints that can be called w/ multiple HTTP methods, currently it seems I have to keep defining separate duplicate configs for header mutations that I want to do, one for GET w/ same path, another for PUT with same path.

Is there any support for just "*" or "ANY" request method? Or plan to support it?

https://community.tyk.io/t/endpoint-designer-support-for-multiple-http-methods/1791

**Comment by bitsofinfo** [comment]
Any thoughts on this? Without this it makes for a lot of repetitive declarations when multiple verbs are allowed on certain endpoints

**Comment by buger** [comment]
Make sense! I added this to the milestone.

**Comment by gathuku** [comment]
Is this complete? any docs?

**Comment by bitsofinfo** [comment]
Not stale

**Comment by bitsofinfo** [comment]
hey, I'm long removed from my old project that used tyk so I can't recall the use case anymore.

**Comment by andyo-tyk** [comment]
Thanks for coming back to me on this. I've still got this in the suggestion backlog but will close this ticket due to the age and the fact you're no longer directly pushing for it.
If anyone else has specific interest in this suggestion, please don't hesitate to comment here and we can discuss your needs.

**Comment by p-afraz** [comment]
we do not use Endpoint Designer but this is a nice feature to be supported in the configuration. Currently we are duplicating all our definitions for each method. It will be nice to have the feature to provide multiple values in an array or a keywords like `any` as method.
