### ISSUE TITLE
Add a way to define a default API version for when none is requested

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#955]
If an API endpoint is versioned and a request comes through without specifying a version, we return a `Version information not found` error.

I propose adding a new setting alongside `not_versioned`, called `default_version`, that optionally sets the version that will be used if none is requested.

If `default_version` is not set or left as an empty string, the current behavior is kept.

Note that this won't change the behavior if a request asks for a version that doesn't exist - that will still be the same error.

An example config:

```
"version_data": {
    "not_versioned": true,
    "default_version": "v2",
    "versions": {
        "v1": {"name": "v1", ...},
        "v2": {"name": "v2", ...}
    }
}
```

Original thread with the suggestion: https://community.tyk.io/t/is-there-a-way-to-set-up-a-default-version/1792

**Comment by mvdan** [comment]
I forgot to add; @lonelycode was suggesting that the gateway should in some way tell the user what version was selected. Otherwise, the API user might not have a way to know what version they're using.

One way to accomplish this would be via a `X-Tyk-*` header. For example, when a default version is set up like in the config above and the gateway falls back to it , it could set `X-Tyk-Default-Version: v2`.

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a way to define a default API version for when none is requested](https://trello.com/c/z8GtNmIY/484-add-a-way-to-define-a-default-api-version-for-when-none-is-requested)

**Comment by nickReyn** [comment]
@mvdan This came up at the event last night. They asked if you don't specify a version, can it just use the latest version.
Instead of having the error come up regarding the below:
> If default_version is not set or left as an empty string, the current behavior is kept.
Could we just say if they leave the default version unset, it defaults to the latest version of the API?

**Comment by mvdan** [comment]
> Could we just say if they leave the default version unset, it defaults to the latest version of the API?

Not in 2.x. That would be breaking backwards incompatibility. I belive right now it picks the first version, not the last.

However, we could add a way to specify the last (the latest), such as `"default_version": "latest"`. Of course, if `"latest"` actually existed as a version, it wouldn't use that instead.

There's always the option of doing what you propose in 3.0, but that would mean waiting until 3.0 to provide any way to do this. Which I think is not a good plan.

**Comment by lonelycode** [comment]
What's the plan and approach with this issue - can't see how it is being resolved anywhere. Will mark as requires planning until there is clarity in the thread.

**Comment by joshblakeley** [comment]
@lonelycode I've got an open PR for this which should be done soon. See TykTechnologies/tyk#1340 on GH

**Comment by nickReyn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a way to define a default API version for when none is requested](https://trello.com/c/P2blKPpc/505-add-a-way-to-define-a-default-api-version-for-when-none-is-requested)

**Comment by buger** [comment]
@joshblakeley pls create Dashboard UI related issue for 2.6
