### ISSUE TITLE
Parse context variable/JWT claims when using OIDC

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#957]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
The JWT claims cannot be parsed when using OIDC.
**What is the expected behavior?**
Context variables (eg. jwt_claims_CLAIMNAME)can be used and parse the JWT claims as simple JWT auth method. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.7

**Comment by buger** [comment]
Actually, I believe it should work. Can you provide an example of how you trying to use it?

https://tyk.io/docs/security/your-apis/openid-connect/
https://tyk.io/docs/transform-traffic/request-headers/

Example of using it when rewriting headers
```
         "global_headers":{
                    "X-Static": "foo",
                    "X-Request-ID":"$tyk_context.request_id",
                    "X-Path": "$tyk_context.path",
                    "X-Remote-Addr": "$tyk_context.jwt_claims_oci"
                }
```

**Comment by hustshawn** [comment]
@buger My configuration is like below:
```
                "global_headers": {
                    "X-Custom-Header": "$jwt_claims_sth",
                    "X-Custom-Token": "$token"
                },
...
...
    "enable_context_vars": true,
```


Below are the headers that passed to the upstream:
```
{"host": "10.0.1.145:8088", "user-agent": "python-requests/2.18.1", "accept": "*/*", "accept-encoding": "gzip, deflate", "authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImlwaG9uZTcifQ.eyJpc3MiOiJodHRwOi8vMTAuMC4xLjE0NS8iLCJzdWIiOiIwIiwiaWF0IjoxNDk4ODM4NDAwLCJleHAiOjE4MTQzNzEyMDAsInN0aCI6InNvbWUgc3RyaW5nIiwiYXVkIjoiaXBob25lNyJ9.BqYn2oPVfIVgMCW7vxWAPtBeSADp2KifU-j1GGmFh-SjB1XVuUp9zd25-S-fKkSb0TngJq2Dtq8yhRg39DLnLqTwdWAm0aH8T0A1kvzlF6RcPtYog2IqiZmcL1EU0NJCZKhK34UeG3qNVchmsK30Ud7i0hEBAw35wJMPLCqiPGNNBeLxqrpJUsvxcQcy_7xmb08SVqlzxNH16E2RgzGomWpVzPeE2SVPcNXLt9bBphCEb-4sqxkcgRZ6LZge8QmkSS2Tl-GRGkE8gRnESfKsoeOeCrwOOwM5VfBvbgQfGFhc1SWNkvn7poJrFlo9EVZnwMvPGUfn6Lu8C748KqRkMQ", "x-custom-header": "$jwt_claims_sth", "x-custom-token": "$token", "x-forwarded-for": "172.19.0.1"}
```

**Comment by buger** [comment]
As you can see, instead it should be prefixed with "$tyx_context.". See my example.

**Comment by hustshawn** [comment]
@buger ya, it's my typo. Please close this issue.
