### ISSUE TITLE
Mutate proxy.target_url from JSVM middleware

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#960]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

No way to alter the proxy.target_url from JSVM middleware for the current request only

**What is the expected behavior?**

Is there anyway to mutate the proxy.target_url from middleware? (besides the url rewriter)

I have the need to define an API that supports this

http://my-es-host/[target-backend]/[api-path]

So based on target-backend, my proxy.target_url would change to http://$target-backend-value/$api-path instead of a hardwired one (affect current request only)

**Comment by bitsofinfo** [comment]
Any thoughts on when this could go into a release or where we should look to do a PR?

**Comment by matiasinsaurralde** [comment]
Hi @bitsofinfo, we'll discuss this with the team.
Thanks for the suggestion.

**Comment by bitsofinfo** [comment]
Note - if https://github.com/TykTechnologies/tyk/issues/1453 becomes workable/fixed, then this (albiet nice to have) would not be necessary.

**Comment by buger** [comment]
Moving to 2.7 (considering that #1453 will be fixed asap)

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
not stale @buger @ilijabojanovic
