### ISSUE TITLE
mw: HMAC failure does not trigger an EventAuthFailure

### ISSUE THREAD

**Issue by othane** [TykTechnologies/tyk#963]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I call an endpoint with an invalid `Authorization` token it does not trigger a EventAuthFailure event.

**What is the expected behavior?**
I would expect an EventAuthFailure event to fire as is the case for the `JWT` or the `Auth Token` (although I might be wrong about this so please correct me before I make a PR for this).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
If I configure a WebHook for the AuthFailure event it triggers for `JWT` and `Auth Token` but not for `HMAC` if I send requests with invalid Authorization headers 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I am using the latest Tyk gateway from docker hub (https://hub.docker.com/r/tykio/tyk-gateway/tags/)

**Comment by mvdan** [comment]
You're right - this auth middleware is missing the code to fire the event. Should be a fairly easy fix.

**Comment by othane** [comment]
Cool, thanks for the quick response !! ... I am not much of a Go developer, but I will try my hand at a PR in the next few days. I have something I think basically works now, but I need to brush up on my unit testing in Go :)

**Comment by mvdan** [comment]
Happy to review a patch!

We currently have no tests that run an entire auth middleware and check that they sent an event. However, `mw_hmac_test.go` does have tests that set up an http middleware chain and run a request through the HMAC middleware in various scenarios.

It should be possible to add a check that EventAuthFailure was sent if and only if the auth failed.

**Comment by othane** [comment]
Hi mvdan, thanks for the advice.

I have the simple part ready to go I think (https://github.com/othane/tyk/commit/efe83a26e0aca891b6017a3640aeb58685d692e3)

I have tested this with `fmt.Printf` statements and it seems to work, but I think I am a bit out of my depth with mocking the `AuthFailed` call in go to ensure it is fired when the tests fail. Do you have any advice?

I didn't want to submit a PR unit I have some unit tests.

**Comment by mvdan** [comment]
You don't need to mock `AuthFailed` - what it does is fire an event. That event goes to whatever event handler an API spec (the internal structure for an API definition plus extra info) has registered.

A good example is this, from the host checker tests: https://github.com/TykTechnologies/tyk/blob/master/host_checker_test.go#L88

Basically, you want a test that has an API spec with an `EventAuthFailure` handler, and then use it in a HMAC middleware and trigger certain types of failures - and verify that you got the event for each one of them.

I realise this isn't straightforward. If you don't have the time to work on a test, or if you give up at some point, I can do the test and keep your authorship of the fix itself. But of course, if you're willing to do both, I won't stand in the way :)

**Comment by othane** [comment]
Cool thanks for the support. I will try to do a test in the next couple of days as you suggest but if I don't get there I'll sing out for some help thanks. It is a nice change for me to do some GO, but I just need to find time :)

**Comment by mvdan** [comment]
Hi @othane!

This patch missed 2.3.8 just by a couple of weeks. However, a couple of important issues have come up and we're going to do 2.3.9 soon. Since this is a small patch and an easy win, we've included it in the release.

I can't give an ETA, but for sure it will be shipped much before 2.4.

**Comment by othane** [comment]
Awsome ... Thanks for the update 😀
