### ISSUE TITLE
Swagger docs won't validate in new Portal catalogue UI

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk#964]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Upload a swagger doc as documentation for a portal entry, view the documentation, you will see in the bottom right that it does not validate.

This [community forum post](https://community.tyk.io/t/swagger-validation-badge-always-displays-red-error/1800) explains it as well

It looks like it is just the wrong URL being passed to the swagger interpreter, it is missing the domain.

**What is the expected behavior?**
That the swagger doc should validate and the icon should be green.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Upload a swagger doc as documentation for a portal entry, view the documentation in the portal, you will see in the bottom right that it does not validate.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Tyk Dashboard (Cloud) v1.3.7

**Comment by ilijabojanovic** [comment]
I need to reopen this issue since fix is on visible on staging cloud:

Here is example:
https://tyk-qa-test-org.cloudv2.tyk.io/portal/apis/598a38a8082a9500010f23c7/documentation/

Validator is still red and we don't have domain in url:
https://online.swagger.io/validator/debug?url=/portal/apis/598a38a8082a9500010f23c7/documentation/raw

Also i tried to update new swagger doc, still same.

https://screencast.com/t/IE7arpezUH

**Comment by ilijabojanovic** [comment]
Here is updated url:
https://tyk-qa-test-org.cloudv2.tyk.io/portal/apis/598a3b811ea6180001fc0f73/documentation/

**Comment by ConsM** [comment]
@ilijabojanovic if you check the page source of the url you provided you will see that it still uses the old code inside the `getUrl` function
Here https://github.com/TykTechnologies/tyk-analytics/blob/master/portal/templates/swagger.html#L58 is the updated function that it should work

**Comment by ilijabojanovic** [comment]
@ConsM yes, seems latest changes are not on dashboard staging cloud. 
@buger could you deploy dashboard again on staging cloud?

**Comment by ilijabojanovic** [comment]
Verified and fixed on staging-cloud
