### ISSUE TITLE
Feature: JSVM import common code/routines from other files

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#973]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The only way to reference common JSVM code/functions is to place them in tyk.js

**What is the expected behavior?**

Should be able to include or reference other custom JSVM functions that are defined in other files

https://community.tyk.io/t/reference-other-jsvm-middleware-functions/1808/3

**Comment by buger** [comment]
I think the easiest solution here is to make `tyk_js_path` config option support directories. So instead of pointing to js file, it will point to a directory and load all of the JS files it can find.

**Comment by bitsofinfo** [comment]
I'd be good with that! Right now I'm having to chain communication through multiple middleware steps in the "PRE" section via custom headers I am injecting on the request to convey state of the processing flow.

**Comment by bitsofinfo** [comment]
Note, this is possible via: https://github.com/TykTechnologies/tyk/issues/1517

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
Thanks for this suggestion, this isn't something we are actively progressing, so I'm closing the ticket.

Please feel free to comment and I can re-open if you feel this is still required.
