### ISSUE TITLE
Add global request timeout on API level

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk#974]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Currently, default upstream response timeout is 10 seconds, and if needed more, it require specified "enforced timeout" for the each URL.

It should be possible to specify timeout on the global API level.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

**Comment by buger** [comment]
It is actually a bit weird that timeout is 10s, because it should be 30s by default. The only 10s I see is the TSL handshake timeout, but it can happen only if smth wrong with SSL on the other side, not request timeout itself.

https://github.com/TykTechnologies/tyk/blob/release-2.3/tyk_reverse_proxy_clone.go#L316

**Comment by buger** [comment]
It is quite easy to test using http://httpstat.us/200?sleep=300000 (5 minutes).

**Comment by l3ender** [comment]
This would be a good feature to have.
