### ISSUE TITLE
Permit inline edit/re-import of API JSON config through dashboard

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#977]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Today I can export an API def to JSON, then edit it, but I must DELETE the API and then re-import it to utilize that edit (this also causes the API id to change)

In my use case I need to add some custom PRE middleware to the API def, my PRE middleware plugins utilize data from the `config_data` element of the API def, and one of those elements is the `api_id` itself (for dynamically setting access rights for a session)

So my issue is this. 

a)  My admin creates the basic API def in the gui, then exports it

b) we edit the exported file adding the middleware references 

c) We then delete the API, and re-import it

d) Then we have manually edit the `config_data` section (via gui) to update w/ the new `api_id`

**What is the expected behavior?**

Would just be great to give direct raw edit capability to the API def JSON. Or just a "re-import" feature that PRESERVES the api id

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by lonelycode** [comment]
You can use the dashboard API and just PUT the API back? There's full CRUD functionality built into every dashboard operation (the dashboard is just itself an API client)

also, instead of the API file export, use the dashboard GET api for the api definition?

This is the API in question:

https://www.tyk.io/docs/tyk-dashboard-api/api-definitions/

**Comment by bitsofinfo** [comment]
Correct, but I've got a bunch of admins that are not developers who don't know/do REST! :)

**Comment by nickReyn** [comment]
We've got a feature lined up for v1.6 dashboard which allows you to edit the raw API def in the API Designer - should solve your issues here 👍

**Comment by bitsofinfo** [comment]
not stale

**Comment by agata-wit** [comment]
@bitsofinfo this is an old request and I was wondering if the "View Raw Definition" feature in API Designer, ability to edit it and update straight from the Dashboard UI works for your use case? 
You could now copy/paste API definition with the same api_id in there and avoid making changes to it but at the same time have your middleware references added.
![image](https://user-images.githubusercontent.com/85508803/129571182-c7cdcc30-2139-4b58-a49f-0adbcb045700.png)
 And then:
 
![image](https://user-images.githubusercontent.com/85508803/129571233-8631aa10-a963-4920-9a2e-f600ad9e01dd.png)
