### ISSUE TITLE
Expose API context information to JSVM middleware

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#978]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently the parameters passed to JSVM middleware don't contain any info about the API context being invoked.

**What is the expected behavior?**

Would be great to get some contextual information about what API is being invoked (api_id, org_id, etc)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by bitsofinfo** [comment]
in addition to this: https://github.com/TykTechnologies/tyk/issues/961

**Comment by mvdan** [comment]
I believe @buger proposed this internally already, as an extension to `config_data`.
