### ISSUE TITLE
Can't search "Activity by Key" via key alias

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#980]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I have a key w/ an alias, but in "Activity by Key" I can't search on it. Only the key hash itself works. Its listed in the view, but who wants to page through everything to find a key via an alias?

**What is the expected behavior?**

Searching should also interrogate against alias

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by ConsM** [comment]
Thanks for your suggestion. 
This is more like an enhancement rather than a bug and it's already in our Dashboard backlog, it will appear in a feature release.
