### ISSUE TITLE
Feature: expose murmur3 hash function to JSVM middleware

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#981]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

I have no way to replicate hashed key values from within JSVM middleware, this can lead to un-needed complexity w/ doing custom Auth Token header implementation, vs what is actually stored as the key name in redis, leading to having to use aliases, that can't be searched on.  

See: https://community.tyk.io/t/npm-and-jsvm-custom-basic-auth-plugin-more-details/1752/34?u=bitsofinfo

https://community.tyk.io/t/hash-via-murmur3-from-within-jsvm-middleware/1820/3?u=bitsofinfo

**What is the expected behavior?**

Would be great to just hash via murmur3 within JSVM middleware. This can be done by exposing access via a go function in otto

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by mvdan** [comment]
Note https://github.com/TykTechnologies/tyk/issues/509 - we should plan ahead for a future where Tyk's hash function is not limited to murmur3.

In that scenario, we should probably make the high-level "hash" function available in the JSVM, saying that it's the same that Tyk itself uses at the moment, but without ensuring that it's always murmur3.

Unless murmur3 is particularly useful in JS for some reason?

**Comment by bitsofinfo** [comment]
I just have a scenario where I would like to 

a) hash fast (embedding a hash func in JS is super slow compared to being able to access go's crypt libs)

b) hash in the same method as however Tyk is doing so if enabled

**Comment by bitsofinfo** [comment]
not stale

**Comment by andyo-tyk** [comment]
Thanks for this suggestion, it's definitely something we will consider so I have added it to the list of feature requests for improving Tyk's custom middleware support. I propose closing this ticket due to its age, but will make a note to update with a comment as and when we address this request.

Please feel free to comment and I can re-open if you prefer.
