### ISSUE TITLE
[dashboard] search in developers

### ISSUE THREAD

**Issue by tumluliu** [TykTechnologies/tyk#985]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
no search box for developers 

**What is the expected behavior?**
search developers by their registered email address

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
v2.3.7

Is it possible to add a search box on the developers tab in the dashboard? It's so painful to help a developer revoke his/her old key when he/she lost it by accident with the following workflow:

1. copy the poor user's email addr
2. open the developers tab in the dashboard
3. search the user's record with `cmd+f`
4. click the next page with such a paging control which is not really pretty:

![screen shot 2017-08-04 at 16 21 40](https://user-images.githubusercontent.com/1563792/28972835-82a7c52c-7931-11e7-84f7-4481378521d9.png)

5. goto step 3. until it appears in the current page

where the step 4 is actually the most painful, absolutely :P

**Comment by buger** [comment]
It is already implemented for the next major release :)

**Comment by ConsM** [comment]
Thanks for your suggestion!
This feature has been in our backlog and it will appear in the 1.4 release.

**Comment by tumluliu** [comment]
thanks a lot for the lighting quick response, Kos!
