### ISSUE TITLE
Figure out the double-sorting of APIs fed to the router

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk#988]
Around line 50 of `api_loader.go`:

```
func prepareSortOrder(apiSpecs []*APISpec) {
        sort.Sort(SortableAPISpecListByHost(apiSpecs))
        sort.Sort(SortableAPISpecListByListen(apiSpecs))
}
```

All the APIs are fed to the main HTTP router shortly after this.

The intent here is to avoid conflicts, such as `/foo` being loaded before `/foo-bar`. thus making the second API not work as they would simply go through the first.

But the code is clearly broken. These are not stable sorts, thus the first sort is completely useless. At the moment, we can only assert that the APIs end up sorted by listen path, from highest to lowest (comparing strings). This avoids the issue shown above.

If the second sort was stable, then you could also say that those that have the same listen paths will be sorted by hostname from highest to lowest. But is that useful at all? As far as I know, host names are matched exactly, not by prefix, so there shouldn't be the same problem that we see with listen paths.

@lonelycode why did you add the host sorting? Am I missing someting?

/cc @buger

**Comment by buger** [comment]
Right, so the right way to fix the issue define single sorting function `SortableAPISpecListByHostAndListen`, which will sort by both params.

**Comment by mvdan** [comment]
> which will sort by both params

This is the same as making the second sort stable. But my main point here is why did we ever need sorting by hostname in the first place. I can't see a reason why it would be useful.

**Comment by buger** [comment]
You can have APIs on the different domains, but with same listen paths.

**Comment by mvdan** [comment]
Yes, of course - but how is the sorting relevant at all. As said, the hostname matching should be an exact match, not a prefix match.

**Comment by buger** [comment]
Right, I see what you mean now. So since host names bind to separate domains, there can't be any listen path conflict between them apriori. So this check is redundant.
