### ISSUE TITLE
Gateway build failing 

### ISSUE THREAD

**Issue by ilijabojanovic** [TykTechnologies/tyk#993]
Branch: release-2.3
environment: all

When we try to build gateway we have this error:

tyk-gateway_1    | # github.com/TykTechnologies/tyk
tyk-gateway_1    | ./tyk_reverse_proxy_clone.go:405: undefined: globalConf in globalConf.ProxyDefaultTimeout
tyk-gateway_1    | ./tyk_reverse_proxy_clone.go:424: undefined: globalConf in globalConf.ProxyDefaultTimeout
compose_tyk-gateway_1 exited with code 2

**Comment by mvdan** [comment]
Can be easily spotted: https://github.com/TykTechnologies/tyk/commits/release-2.3

Should be an easy fix - assigning to @buger since he broke it
