### ISSUE TITLE
Feature: expose HTTP request attributes in the JSVM 'request' object

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#994]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

In JSVM middlewhere I have no ability to detect and or do something based on the HTTP method of the request, host header etc.

**What is the expected behavior?**

I should be able to get all attributes of the http request, including the method (GET/POST... etc etc), host header.. all or nothing!

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

1.3.7/2.3.7

**Comment by bitsofinfo** [comment]
For more context, I need this because due to the inability to do versioning w/ my URIs I need to port to Tyk: https://github.com/TykTechnologies/tyk/issues/995

My goal is to whitelist certain URLs and HTTP methods, trying to do it this way doesn't fit my need: https://community.tyk.io/t/api-endpoint-designer-whitelisting-issue/1829/7?u=bitsofinfo

So I'd just like to write a middleware plugin where I can do my own http method restrictions.

**Comment by willks** [comment]
We require this as well. We have a use-case for doing some auth logic based on GET/POST/PUT requests. I realise it's silly to have this in middleware, but unfortunately we are accessing legacy systems that are no longer being actively developed.

As a workaround, I tried manipulating headers and injecting a new header "X-TYK-METHOD" using endpoint designer, but the injected values aren't reflected in the middleware request.

**Comment by bitsofinfo** [comment]
Any ideas when this might be incorporated?

**Comment by bitsofinfo** [comment]
Host header?

**Comment by buger** [comment]
Not there yet, but will be in 2.5 https://github.com/TykTechnologies/tyk/pull/1422

**Comment by nickReyn** [comment]
@bitsofinfo v2.5 will be released this week :pray:
