### ISSUE TITLE
Feature: capture "version" via regex from URL

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk#995]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

For capturing "version" in a URL, I'm limited to the FIRST element only. 

https://community.tyk.io/t/api-endpoint-designer-whitelisting-issue/1829/16?u=bitsofinfo

**What is the expected behavior?**

I should be able to extract a "version" value from anywhere in the URL. First, Last, or something in the middle. Would be preferred to be able to define a simple regex capture for the version element...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://community.tyk.io/t/api-endpoint-designer-whitelisting-issue/1829/16?u=bitsofinfo

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

2.3.7

**Comment by bitsofinfo** [comment]
For more context: https://community.tyk.io/t/api-endpoint-designer-whitelisting-issue/1829/7?u=bitsofinfo

**Comment by bitsofinfo** [comment]
not stale, these stale bots are ultra annoying

**Comment by andyo-tyk** [comment]
I'm closing this as "won't fix" as it seems to be influenced by a specific use case. I will keep it logged in my own list of feature requests, to be reviewed in detail when we next look at this area of the product, however I cannot make any commitment that we will change the behaviour of Tyk here.
