### ISSUE TITLE
JWT authentication bug in latest release v2.3.7

### ISSUE THREAD

**Issue by hustshawn** [TykTechnologies/tyk#996]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When using JWT auth, always got 
```
tyk_gateway_1    | time="Aug  8 02:25:30" level=warning msg="Key not found in storage engine" err="Key not found" inbound-key="****64da" 
tyk_gateway_1    | time="Aug  8 02:25:30" level=error msg="Could not identify a policy to apply to this token from field!" 
tyk_gateway_1    | time="Aug  8 02:25:30" level=error msg="request error: Key not authorized: no matching policy found" api_id=b43fe0023c554e0c59c62c7b8a4932bc org_id=59891ee6da2c2f
```
and I am sure the policy was created and linked to the api, and the policy id in JWT is correct.
Sometimes, I found it was due to the `sub` field in the JWT, in my another case, if the `sub` is `"0"`, I can get passed the auth, but other values cannot pass.
**What is the expected behavior?**
Pass the auth using JWT.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Since I am using the docker release, please pull the latest from docker hub. and configure a simple endpoint like `/test` with JWT auth, use `sub` as identity source, `kid` as policy identifier, and make a policy link to it.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
v2.3.7 affected. When I roll back to v2.3.4, it works fine.

**Comment by lonelycode** [comment]
> `kid` as policy identifier, and make a policy link to it.

This is not a claim, it is a header, which is why this probably will not work. Add a new claim for the policy for this to work with JWT. `kid` is reserved for key IDs

**Comment by hustshawn** [comment]
Just find if I put the `kid` in JWT payload, the auth passed. 

It is quite annoying that such kind of behavior changed in blackbox. It should have had a reason or announcement to tell it works in previous version but current release not.

**Comment by lonelycode** [comment]
That's quite a long time ago, what did yu upgrade from? 

The change is because the kid header is reserved for key IDs, therefore if the JWT is used elsewhere you break the spec.

Better idea is to not use a reserved header.
